### ISSUE TITLE
Remove section for Help 

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#1005]
That's for the old CHM-style help files that no longer exist in the product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8116c71f-c2e1-0d19-7a06-10daf832cc62
* Version Independent ID: 93d928a8-b733-1dec-b31b-339c0730ab84
* Content: [Accessibility - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/understand/accessibility-features#bkmk_ahelp)
* Content Source: [sccm/core/understand/accessibility-features.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/accessibility-features.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by jpcast88** [comment]
@aczechowski Can this issue be closed? Was the help section already removed?

**Comment by aczechowski** [comment]
Yes, thanks for catching it @jpcast88!
