### ISSUE TITLE
Key International academy 

### ISSUE THREAD

**Issue by Key-international** [MicrosoftDocs/SCCMdocs#1007]
https://www.keyinternational.academy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cf527c7-1ec4-cc8c-67fc-94336e2a12d8
* Version Independent ID: 6100f037-c599-62e0-6ed5-00804ca75c73
* Content: [Support for virtualization - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/support-for-virtualization-environments)
* Content Source: [sccm/core/plan-design/configs/support-for-virtualization-environments.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/support-for-virtualization-environments.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Assuming this is spam. Closing and locking
