### ISSUE TITLE
User Deployments do not work against MPs using DB Replica

### ISSUE THREAD

**Issue by excelsi** [MicrosoftDocs/SCCMdocs#1011]
That's a non documented Limitation see:
https://twitter.com/djammmer/status/1060903565311520768

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e05b125-c8e8-0eab-5b2b-2bc60fe33654
* Version Independent ID: fcf9f58f-1ab5-9132-7de8-539a32b57862
* Content: [Management point database replicas - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/database-replicas-for-management-points)
* Content Source: [sccm/core/servers/deploy/configure/database-replicas-for-management-points.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/database-replicas-for-management-points.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @excelsi for filing the issue. I think this should also include a note on the [app deployment article](https://docs.microsoft.com/sccm/apps/deploy-use/deploy-applications)
