### ISSUE TITLE
1806 - Enhanced HTTP site system 

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/SCCMdocs#1015]
The docs can be updated to mention that the MP's don't have to be in HTTPS if they are running ConfigMgr 1806, the enhanced HTTPS site system can be used and the MP can stay in HTTP mode.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acbd8029-6391-7ae1-a098-9c348be1dd98
* Version Independent ID: e202fe2f-876c-44a5-5e03-d769ef31f72c
* Content: [Install the client with Azure AD - Configuration Manager](https://docs.microsoft.com/en-au/sccm/core/clients/deploy/deploy-clients-cmg-azure)
* Content Source: [sccm/core/clients/deploy/deploy-clients-cmg-azure.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/deploy-clients-cmg-azure.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by jocasti** [comment]
@aczechowski I'm thinking we could just add an additional bullet under the section "Configure all MPs for https mode" with something like, "If on version 1806, enabling enhanced http site system will allow the MP to stay in http mode." OR should the entire doc be reviewed and updated? thoughts?
