### ISSUE TITLE
remove comma from script example

### ISSUE THREAD

**Issue by nclinch** [MicrosoftDocs/SCCMdocs#1018]
https://docs.microsoft.com/en-us/sccm/apps/deploy-use/create-deploy-scripts#create-a-new-folder-and-file 
remove the comma after [string]$FileName,
or you will get this error

At line:5 char:19
+ [string]$FileName,
+                   ~
Missing expression after ','.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterToken
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c7d1db7-6812-ff3c-9aac-0f55800ed665
* Version Independent ID: a4499cf7-ed5a-710c-66e0-005563b9c015
* Content: [Create and run scripts - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/create-deploy-scripts#create-a-new-folder-and-file)
* Content Source: [sccm/apps/deploy-use/create-deploy-scripts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/create-deploy-scripts.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @nclinch for the feedback. If you're willing and interested in submitting the change yourself, I'm happy to help and review it for publication. For more information, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute).

**Comment by jocasti** [comment]
Created PR https://github.com/MicrosoftDocs/SCCMDocs-pr/pull/3067

**Comment by aczechowski** [comment]
Thanks @jocasti for fixing this. The change should be live later today around 11am Pacific time. Closing this issue.
