### ISSUE TITLE
You also have to delete and re-add any Azure services

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/SCCMdocs#1022]
You also have to delete and re-create any Azure service connectors (only Intune is mentioned here) that were created before the recovery or they won't work after the recovery on the new hardware due to having a NULL SecretKeyforSCP

Error in cloudmgr.log is "Index (zero-based) must be greater than or equal to zero"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2bf93f-aa79-ef8a-ee16-c1ed27eb8e13
* Version Independent ID: d64f0463-a1e0-b80b-f16b-39f54dd87154
* Content: [Site recovery - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/recover-sites)
* Content Source: [sccm/core/servers/manage/recover-sites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/recover-sites.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by russrimm** [comment]
Error in cloudmgr.log is "Index (zero-based) must be greater than or equal to zero"

**Comment by aczechowski** [comment]
Thanks @russrimm for the feedback, I'll investigate.

**Comment by aczechowski** [comment]
Still working to confirm. 
Cross-linking with internal doc [bug 3487266](https://msazure.visualstudio.com/Configmgr/_workitems/edit/3487266)

**Comment by aczechowski** [comment]
I revised this article, the changes will publish live on Monday 8/26 around 11am Pacific time.
