### ISSUE TITLE
Fat32 Partition Update

### ISSUE THREAD

**Issue by foldzan1** [MicrosoftDocs/SCCMdocs#1024]
If you are using a newer version of ADK the partition needs to be at least 600mb and not 500mb. If you set it to 500mb you may get errors of "not enough disk space" when trying to boot into WinPE via the task sequence. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8eaf0aab-4d02-82dd-007f-8457e648984d
* Version Independent ID: 4ea5614c-5e4d-537d-4b98-5ddead504359
* Content: [Task sequence steps to manage BIOS to UEFI conversion - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/task-sequence-steps-to-manage-bios-to-uefi-conversion)
* Content Source: [sccm/osd/deploy-use/task-sequence-steps-to-manage-bios-to-uefi-conversion.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/task-sequence-steps-to-manage-bios-to-uefi-conversion.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @foldzan1, I'm investigating

**Comment by MrTech86** [comment]
Changing to 600MB fixed mine as well.

**Comment by hert87** [comment]
Same here, and can be found online to:
https://deploymentresearch.com/Research/Post/631/Error-0x80070070-in-ConfigMgr-OSD-during-BIOS-to-UEFI-step

**Comment by ingd** [comment]
@aczechowski, any news about this case?

**Comment by aczechowski** [comment]
I found this UVI: https://configurationmanager.uservoice.com/forums/300492-ideas/suggestions/31958464-bios-to-uefi-problem-rebooting-back-into-winpe-d
which was declined. Given that, I’ll just add a note to this doc article about the issue, so that the workaround is a bit more discoverable.

**Comment by aczechowski** [comment]
I added a tip for this (as well as a general review of this old article), it should publish tomorrow.
