### ISSUE TITLE
more precise detail required on "Azure Administrator"

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/SCCMdocs#1031]
at this time being a subscription administrator with a precreated service principal apparently isn't enough.

this document doesn't provide the precise details of what is required in terms of permissions and access of the service principal within Azure AD 

provide more details of what is required and fulfil Microsoft's own vision of removing the need for GA rights in its RBAC model!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778368d0-1054-678c-4d74-5dce1b5826c8
* Version Independent ID: aaac7308-66e6-66f0-8248-14e1505c11a6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/plan-cloud-management-gateway)
* Content Source: [sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @bakerm00 for the feedback. Let me check with the engineering team to clarify.

**Comment by aczechowski** [comment]
For CMG deployment, the requirement is an Azure Subscription Admin

For Azure AD onboarding (which is a CMG prereq for using Azure Resource Manager):
- Option 1: if you're creating the Azure AD apps in the SCCM console, you need to be an Azure AD Global Admin 
- Option 2: work with an Azure AD Global Admin to pre-create the apps. The SCCM admin imports those apps into SCCM providing the necessary details.

**Comment by aczechowski** [comment]
This issue is closed because I made a tweak to the article for this feedback. The change should publish live later today.
