### ISSUE TITLE
Special Characters Password

### ISSUE THREAD

**Issue by natiT** [MicrosoftDocs/SCCMdocs#1032]
As panu mentioned on Twitter you cannot use the character % in a password because it always says bad password. This should written down in the top of the article https://twitter.com/panusaukko/status/1062697825778257920?s=19

(admin edit: add metadata block for article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f80cf3-6f36-cb44-d0e5-d186164d6281
* Version Independent ID: ada8a281-7d9f-e82e-e4e8-056b93e8b36d
* Content: [Accounts used - Configuraton Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/accounts)
* Content Source: [sccm/core/plan-design/hierarchy/accounts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/accounts.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @natiT for the feedback. Agreed, a great tip to include for all accounts.

**Comment by aczechowski** [comment]
I added a tip for this. It will publish live on Monday
