### ISSUE TITLE
Device Guard - Pre-Release Feature

### ISSUE THREAD

**Issue by excelsi84** [MicrosoftDocs/SCCMdocs#1039]
"Device Guard management is a pre-release feature for Configuration Manager, and is subject to change." 
I think this is not true anymore in CB 1806. Am I correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2082f138-28f2-d410-d607-4fcb1ddf12db
* Version Independent ID: 7ce37b4e-9330-73d9-f3bb-2f0af4ec6073
* Content: [How to manage Windows Device Guard - Configuration Manager](https://docs.microsoft.com/en-us/sccm/protect/deploy-use/use-device-guard-with-configuration-manager)
* Content Source: [sccm/protect/deploy-use/use-device-guard-with-configuration-manager.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/use-device-guard-with-configuration-manager.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @excelsi84, it is still a prerelease feature. If you follow the link to the list of pre-release features, it's not yet added as a full feature. I review this list with engineering with every release to ensure accuracy. I'm closing this issue as there's nothing actionable at this time.

**Comment by excelsi** [comment]
Thanks for the hint!
