### ISSUE TITLE
"enables you to concurrently manage Windows 10 version 1709"

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/SCCMdocs#1040]
Should say Windows 10 version 1709 and later to avoid any confusion

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07e9b780-6cad-d3f3-d0f2-e13a577890cc
* Version Independent ID: 18c7f0aa-884a-349b-e416-74d02adc4474
* Content: [Co-management for Windows 10 devices - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/co-management-overview)
* Content Source: [sccm/core/clients/manage/co-management-overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/co-management-overview.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @russrimm for the feedback. I think that intro paragraph is the only instance that doesn't already say that. 😃

**Comment by aczechowski** [comment]
I'm closing this issue. A big revision to the co-management content will publish soon and address this issue.
