### ISSUE TITLE
Prerequisites 

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/SCCMdocs#1042]
Under Prerequisites it says:
EMS or Intune license for all users
Azure AD automatic enrollment enabled

To use Azure AD automatic enrollment, an Azure AD Premium license is required. The documentation should be updated to include 2 options. EMS license, or Intune license + Azure AD Premium.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7294682b-1bfb-54e4-0bdb-178e6fe2cc9a
* Version Independent ID: 6c5f1cfb-ae12-1fd2-80ef-1f67e419f4c5
* Content: [Prepare Windows 10 for co-management - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/co-management-prepare)
* Content Source: [sccm/core/clients/manage/co-management-prepare.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/co-management-prepare.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I'm closing this issue. A big revision to the co-management content will publish soon and address this issue. When it publishes, all of the prerequisites are centralized on a single overview article, and I think I clarified this point based on your feedback. After the new content publishes, if you think further clarification is necessary, please file a new issue on the new article.
