### ISSUE TITLE
OperationType_DW  field not updating

### ISSUE THREAD

**Issue by kmohdnawaz** [MicrosoftDocs/SCCMdocs#1043]
HI,
i disabled one computer account in AD and then deleted it from SCCM console and then ran synchronization and even waited for a day for actual synchronization to happen. But the OperationType_DW = 'U' is showing "U' instead of 'D" . when will be this record updated ?, I am being waited for days.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a4274db-5f5b-c169-c69e-68146e92836f
* Version Independent ID: a28966e9-88cc-6910-c270-7f14818f832a
* Content: [Data warehouse - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/data-warehouse)
* Content Source: [sccm/core/servers/manage/data-warehouse.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/data-warehouse.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.  
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.  
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.  

I'm closing this issue as there's nothing actionable for docs at this time.
