### ISSUE TITLE
Get started with caching technologies

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#1044]
This article explains each of the supported peer caching technologies, there are individual articles on each, and there's an article on [Optimize Windows 10 update delivery](https://docs.microsoft.com/sccm/sum/deploy-use/optimize-windows-10-update-delivery) with a section on choosing the right one, but we should have a "getting started" guide for peer content. Feedback from a customer at CCP event: they understand the concepts and it makes sense, but they don't know where to start or which one to use for their scenarios. Engineering team has presentation with recommendations to include (see email subject "My Content Distribution PPT").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff2f1985-822a-f9aa-8368-9abf85c50118
* Version Independent ID: 3401e963-f1cf-a15d-01f2-c1754a7d9336
* Content: [Content management fundamentals - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by martinkupka** [comment]
Hi, is this sentence in "Binary differential replication" section really correct? 

"Binary differential replication (BDR) is a prerequisite for distribution points. It's sometimes known as delta replication."

As far as I understand it BDR and Delta replication are two different technologies. Delta is enabled by default and BDR can be enabled on packages on top of it.

**Comment by aczechowski** [comment]
@martinkupka can you please file a separate issue for your question? I have an answer, and I'd like to track it separately from this issue on caching technologies.
