### ISSUE TITLE
Fallback status point missing prereqs

### ISSUE THREAD

**Issue by marybethtice** [MicrosoftDocs/SCCMdocs#1046]
The FSP also requires BITS Server Extensions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9070eb9b-0e5f-a877-e02e-2d1cea2a2b38
* Version Independent ID: df251762-f2d6-9f06-4fa9-ec5cea2cca0a
* Content: [Site prerequisites - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/site-and-site-system-prerequisites#feedback)
* Content Source: [sccm/core/plan-design/configs/site-and-site-system-prerequisites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/site-and-site-system-prerequisites.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @marybethtice for the feedback. If you're willing and interested to submit this change yourself, I'm happy to review and help. For more information, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute).

**Comment by aczechowski** [comment]
Thanks @jocasti for submitting a change for this. I'm closing this issue; the change should publish Monday around 11am Pacific.
