### ISSUE TITLE
Db sizing

### ISSUE THREAD

**Issue by Garthmj** [MicrosoftDocs/SCCMdocs#1048]
Can you confirm that MS is still recommend such small db sizes for each level of Client numbers? ~3mb a client is tiny, these days. What does the telemetry data say the real numbers are? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e67ddd45-90df-32cd-3cbe-9e1443b2540f
* Version Independent ID: dee7fcb8-a7b7-e5a1-9c04-c113805be0da
* Content: [Recommended hardware - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/recommended-hardware)
* Content Source: [sccm/core/plan-design/configs/recommended-hardware.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/recommended-hardware.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Garthmj for filing this issue. I'll check with engineering what current data we have on this size.

**Comment by aczechowski** [comment]
The long answer is that it depends upon the hierarchy type, the configuration, and the number of clients. (Interesting note, it's generally less for larger environments. In other words, smaller sites have more database usage per client.) 

But in short, based on the data, a safe estimate is **10 MB** per client

@Garthmj do you want to make this edit?

**Comment by aczechowski** [comment]
I made this change, it will publish live tomorrow
