### ISSUE TITLE
Connect-AutopilotIntune does not work with MFA account and crash/closes the PS prompt

### ISSUE THREAD

**Issue by benoithamet** [MicrosoftDocs/SCCMdocs#1051]
When trying to connect to Autopilot using Connect-AutopilotIntune with a GA account which has MFA enabled, the connection apparently failed and immediately crashes/closes the PowerShell prompt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac2470bb-8bcb-d07d-71c3-261b84762419
* Version Independent ID: 868cabe3-5088-fa54-cba0-56ff1d2259ef
* Content: [Technical preview 1810 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/capabilities-in-technical-preview-1810)
* Content Source: [sccm/core/get-started/capabilities-in-technical-preview-1810.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/capabilities-in-technical-preview-1810.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by benoithamet** [comment]
ok, finally found the issue
You need to add one additional step:Import-Module WindowsAutopilotIntune

**Comment by aczechowski** [comment]
Thanks @benoithamet for the feedback. I'm investigating this.

**Comment by aczechowski** [comment]
Thanks @benoithamet. The difference may be whether the PSModulePath had already been updated. But including the Import-Module command should always work. I submitted a fix that should publish later today. Closing this issue.
