### ISSUE TITLE
Ports for migration

### ISSUE THREAD

**Issue by YuvarajMS** [MicrosoftDocs/SCCMdocs#1053]
The ports mentioned in the documentation only specifies the belowing
NetBIOS/SMB - 445 (TCP)
RPC (WMI) - 135 (TCP)
SQL Server - The TCP ports in use by both the source and destination site databases.

The WMI connection will not work unless you add the below along with the ports mentioned above. 
UDP - 135
TCP  - Dynamic ports (RPC WMI)

The Gather task will fail unless you add these ports.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f4161a-9856-e257-ac0d-921a2ad11e3e
* Version Independent ID: 634ea573-57a1-c72e-9f87-5f697ca8674e
* Content: [Migration prerequisites - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/migration/prerequisites-for-migration)
* Content Source: [sccm/core/migration/prerequisites-for-migration.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/migration/prerequisites-for-migration.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @YuvarajMS for the feedback

**Comment by enriccorrea** [comment]
Can you especify the correct number port and protocol for all connections and the direction of the communication between source hierarchy and destination hierarchy?

**Comment by aczechowski** [comment]
I made a change for this, it will publish live tomorrow.
