### ISSUE TITLE
Upgrade to a new version of SQL Server

### ISSUE THREAD

**Issue by sympleconfigmgr** [MicrosoftDocs/SCCMdocs#1054]
In regards to Secondary sites that use SQL express, what is the recommendation for upgrade? This document does not discuss SQL express upgrades. Or does it even matter when its SQL express and we should only worry about secondary sites that have a full SQL installation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71096754-a158-0c4f-9d87-6a0575139573
* Version Independent ID: 4e148fe9-9c18-228a-60ea-eecc081291e1
* Content: [Upgrade on-premises infrastructure - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/upgrade-on-premises-infrastructure)
* Content Source: [sccm/core/servers/manage/upgrade-on-premises-infrastructure.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/upgrade-on-premises-infrastructure.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @sympleconfigmgr for the feedback. Let me investigate this.

**Comment by SCCM-IT** [comment]
Any update on this?  I have this same scenario.

**Comment by aczechowski** [comment]
Thanks for bumping this, sorry for the delay. Yes, you can upgrade SQL Express for secondary sites. Engineering verified the scenario works fine. For example, upgrade SQL Express 2014 to SQL Express 2017, and then update to version 1902.

**Comment by aczechowski** [comment]
Thanks @Brenduns for adding some text for this issue. I'm closing the issue. The change will publish live tomorrow (Tuesday, 11 June) around 11am Pacific time.
