### ISSUE TITLE
Screen shots update

### ISSUE THREAD

**Issue by L00kout** [MicrosoftDocs/SCCMdocs#1055]
Request an update to the Lookout screenshots as we've updated our Lookout console.  I'd be happy to assist the appropriate person if helpful.  
Thanks 
Clayton Barnard, Lookout.  (b-clbarn@microsoft.com / clayton.barnard@lookout.com)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1283d9d3-fe56-57f5-3659-6367985b206b
* Version Independent ID: 3d1935fe-cb93-e480-55e5-30b1fc5d6735
* Content: [Set up your Lookout subscription - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/set-up-your-subscription-with-lookout)
* Content Source: [sccm/mdm/deploy-use/set-up-your-subscription-with-lookout.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/set-up-your-subscription-with-lookout.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
hybrid end of service is this coming weekend, closing this issue
