### ISSUE TITLE
Please describe basic authentication with proxy server is not supported by SCCM SUP

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/SCCMdocs#1059]
@yushinok commented on [Fri Nov 30 2018](https://github.com/MicrosoftDocs/SCCMDocs.ja-jp/issues/24)

Could you please describe basic proxy authentication with proxy server is not supported by SCCM SUP?
Related to this blog article. I would like to make this statement official on this page.
When customer enabled basic authentication on WSUS console, it will be unchecked by WCM.

How Can We Enable Basic Proxy Authentication On The Software Update Points?
https://blogs.technet.microsoft.com/carlossantiago/2008/08/05/how-can-we-enable-basic-proxy-authentication-on-the-software-update-points/

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 926d0167-454c-f8c0-177d-0b1de31b8a77
* Version Independent ID: e1a16df1-da95-3783-c683-cd80fe43bf6d
* Content: [プロキシ サーバーのサポート - Configuration Manager](https://docs.microsoft.com/ja-jp/sccm/core/plan-design/network/proxy-server-support#feedback)
* Content Source: [sccm/core/plan-design/network/proxy-server-support.md](https://github.com/Microsoft/SCCMDocs.ja-jp/blob/live/sccm/core/plan-design/network/proxy-server-support.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

---

@aczechowski commented on [Fri Nov 30 2018](https://github.com/MicrosoftDocs/SCCMDocs.ja-jp/issues/24#issuecomment-443317320)

@MicrosoftDocs/mor - are you able to [transfer this issue](https://help.github.com/articles/transferring-an-issue-to-another-repository/) to the main [SCCMDocs repo](https://github.com/MicrosoftDocs/SCCMdocs)? (I'm not an admin on the localized repos to move it.)

**Comment by yushinok** [comment]
Hi there,

Can I know the progress of this feedback?

Best regards,
Yusuke

**Comment by SonjaSaltzman** [comment]
@arob98 - could you help route this to the proper contact, as it's a source issue?  Thanks :-)

**Comment by aczechowski** [comment]
I've got it, just was out last week.
@yushinok, I need to check with engineering to confirm. But I can't provide any ETA on potential updates to the article.

**Comment by mestew** [comment]
Thanks again for the feedback. We moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
