### ISSUE TITLE
Unable to Import Task sequence

### ISSUE THREAD

**Issue by SHAVALAG** [MicrosoftDocs/SCCMdocs#1061]
Hi ,

I am unable to import task sequence with content. Error says: System out of memory exception is thrown.
Increased WMI memory to 1GB and handles per host to 8192 but no help.
SCCM is running on a 32GB RAM server.

Please suggest

**Comment by aczechowski** [comment]
Thanks @SHAVALAG for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.  
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.  
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.  

I'm closing this issue as there's nothing actionable for docs at this time.
