### ISSUE TITLE
Grouping Detection Clauses?

### ISSUE THREAD

**Issue by Brachus12** [MicrosoftDocs/SCCMdocs#1062]
"When you create more than one detection method for a deployment type, create more complex logic by grouping the clauses together. "

Is this actually available yet? If so, exactly HOW is it accomplished?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db758241-5a9e-47dc-0104-8d8c1072a2f2
* Version Independent ID: d54013ba-afcb-6795-9fb5-3668a8afec32
* Content: [Create applications - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/create-applications#bkmk_dt-detect)
* Content Source: [sccm/apps/deploy-use/create-applications.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/create-applications.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Brachus12, thanks for the feedback. Yes, it is available! I agree with you that we could add some further information to clarify how to do this. 

Here are the basics:
- Create three or more detection method clauses on a deployment type.  
- Select two or more consecutive clauses, and choose **Group**. You'll see parentheses added to the associated columns. These marks show where the group starts and ends.   

For example:

| Connector | ( | Clause | ) |
|-|-|-|-|
|&nbsp;|&nbsp;|MSI Product Code|&nbsp;|
|Or|(|file1.txt exists|&nbsp;|
|And|&nbsp;|file2.txt exists|)|

To remove the group, select the grouped clauses, and choose **Ungroup**.

**Comment by Brachus12** [comment]
Thanks so much! I was able to follow those tips to get our detection created as needed.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by aczechowski** [comment]
Thanks to @Brenduns for adding content to fix this issue. I'm closing it now. The change will go live tomorrow (Tuesday, 11 June) around 11am Pacific time.

**Comment by AndrzejWojtowicz** [comment]
How is the example from below interpreted actually? 
MSI product or file1 has to exist AND file 2 has to exist at the same time?
this is really confusing I must say and we are migrating from Altiris.


> Hi @Brachus12, thanks for the feedback. Yes, it is available! I agree with you that we could add some further information to clarify how to do this.
> 
> Here are the basics:
> 
> * Create three or more detection method clauses on a deployment type.
> * Select two or more consecutive clauses, and choose **Group**. You'll see parentheses added to the associated columns. These marks show where the group starts and ends.
> 
> For example:
> 
> Connector	(	Clause	)
>  	 	MSI Product Code	 
> Or	(	file1.txt exists	 
> And	 	file2.txt exists	)
> To remove the group, select the grouped clauses, and choose **Ungroup**.

**Comment by aczechowski** [comment]
Hi @AndrzejWojtowicz 
The app is detected by one of two ways:

1. It detects the MSI product code registered with Windows
2. Both file1 and file2 exist

In other words:

- If the MSI code is registered, then the app is detected as installed.
- If the MSI code is not registered, but both file1 AND file2 exist, then the app is detected as installed.
- If the MSI code isn't registered, and file1 or file2 (or both) don't exist, then the app isn't detected.

I hope that helps explain how it works.

**Comment by BobNaijaGuy** [comment]
Thanks a lot this grouping method resolved my Detection Method error.
