### ISSUE TITLE
Enrollment errors

### ISSUE THREAD

**Issue by SC2385** [MicrosoftDocs/SCCMdocs#1064]
It would be useful if you can share some info on how to track the reason or the fix the issues with Co-Management enrollment errors in extension to this document as co-management handler logs are not really helpful.

(1/13/2019: admin edit to rehome with new article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc1ee352-7d48-d065-ec99-f1e309f65e56
* Version Independent ID: 2969fd93-1cca-fa3f-8530-74046d93c559
* Content: [Monitor co-management - Configuration Manager](https://docs.microsoft.com/en-us/sccm/comanage/how-to-monitor#enrollment-errors)
* Content Source: [sccm/comanage/how-to-monitor.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/how-to-monitor.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @SC2385 for the feedback. We're already working on this! No ETA right now though.

**Comment by aczechowski** [comment]
Cross reference internal [BUG 3158555](https://msazure.visualstudio.com/Configmgr/_workitems/edit/3158555)

**Comment by aczechowski** [comment]
We closed this issue because I merged an update to this article that addresses this feedback. It will publish live tomorrow (Tuesday, 12 February around 11am Pacific time). If you have any additional feedback once it goes live, please open a new issue.
