### ISSUE TITLE
Hybrid to Standalone migration - After user and associated device are migrated to intune, policy removal is suspended for 7 days.

### ISSUE THREAD

**Issue by JarrettRenshaw** [MicrosoftDocs/SCCMdocs#1066]
Can the public doc's be updated to document this behavior.

Following doc can be update with a Note to mentioned. removal of policy would be suspended for 7 days when a user is moved from Hybrid to Standalone.

It is a request from customer as it took long time to get to understand this behaviour and no public facing information is available. Also this is related to Hybrid to Standalone migration which we expect more and more customer doing it in coming months.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e430e343-868a-8116-62d5-cd5bf14b6648
* Version Independent ID: 0746a0dd-35ab-f81e-41d7-7c05c16be612
* Content: [Migrate hybrid MDM resources to Intune standalone - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/migrate-hybridmdm-to-intunesa)
* Content Source: [sccm/mdm/deploy-use/migrate-hybridmdm-to-intunesa.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/migrate-hybridmdm-to-intunesa.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

For internal reference only:
Requested via CSS CONTENT IDEA REQUEST 93681 - JarrettR
[internal KB](https://internal.support.services.microsoft.com/en-us/help/4473876)
and
[internal reference](https://icm.ad.msft.net/imp/v3/incidents/details/90187335/home)

**Comment by aroe88** [comment]
Hi,

I've no idea why this information isn't already public!

We are currently piloting our Hybrid Intune migration, and everything seems to work fine until day 7, when we start to get removal of policy and generally unreliable behaviour from the devices. 

Until we can better understand what is happening under the hood, and potentially find a way to mitigate, we'll have to apply the brakes to the migration.

**Comment by IntrepidBlazon** [comment]
I would like to add I'm experiencing the same issue and have been told by my Fast Track Engineer this is a known issue and a fix should be in place soon. I was told to submit a support ticket to have the fix applied to my tenant sooner.

**Comment by aczechowski** [comment]
I added a note for this to the following article which talks more about the process: https://docs.microsoft.com/sccm/mdm/deploy-use/migrate-mixed-authority#migrate-a-test-group-of-users-to-intune-standalone
I'm closing this issue. The change should make daily publishing today around 11am Pacific time.
