### ISSUE TITLE
Reports Language

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/SCCMdocs#1067]
The documentation states: "When report folders are created and reports are copied to the report server, Configuration Manager determines the appropriate language for the objects. If the associated language pack is installed on the site, Configuration Manager creates the objects in the same language as the operating system running on the report server on the site." - This is actually not true, since the language to use for the reports is based on the input/system locale of Local System. Since many users have an English OS, but use other input/system locales, you can end up with reports in non english (f.e. in my case Dutch) while the installed OS is english. Problem is that many "community" addons like dashboards assume that the ConfigMgr reports are there installed using the English names. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed3637a6-0616-a14a-2864-9c7d6bbc70e0
* Version Independent ID: 7b0ddfd8-2c0f-9518-39e6-e49130ae2f58
* Content: [Configure reporting - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/configuring-reporting)
* Content Source: [sccm/core/servers/manage/configuring-reporting.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/configuring-reporting.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @kennethvs for the feedback. I'll do some investigation on this.

**Comment by aczechowski** [comment]
Here's an initial summary, some additional details are still to be determined:

1. Install report/create folder: create objects using locale of the site server OS (static)
2. Web reports
    a. Folder/report names displayed in same locale as above (static)
    b. Report contents: browser locale (dynamic)
3. Console reports
    a. Folder/report names: console locale (dynamic)
    b. Report contents: console locale (dynamic)

I'm still trying to get clarity around how the addition of language packs for the site modifies this behavior, if at all.

**Comment by aczechowski** [comment]
I revised this article, the changes will publish live around 11am Pacific time
