### ISSUE TITLE
Limitation to Uninstalling?

### ISSUE THREAD

**Issue by dt98** [MicrosoftDocs/SCCMdocs#1072]
Is there a limitation when you have a powershell script that uninstalls a program?  When I run the script locally it works fine, but when I run it via SCCM, the script returns a 1603 error code.  I've used multiple scripts in the past doing other functions that have worked great, and this is the first time I've tried uninstalling something this way via SCCM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c7d1db7-6812-ff3c-9aac-0f55800ed665
* Version Independent ID: a4499cf7-ed5a-710c-66e0-005563b9c015
* Content: [Create and run scripts - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/create-deploy-scripts#limitations)
* Content Source: [sccm/apps/deploy-use/create-deploy-scripts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/create-deploy-scripts.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @dt98 for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.  

I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by dt98** [comment]
I will take that as a no then.  Thanks

**Comment by aczechowski** [comment]
Not necessarily.  More of "I don't know" - but this isn't intended to be a support channel. You might get a different/better response from forums or professional support.
