### ISSUE TITLE
Custom Classes via WMI

### ISSUE THREAD

**Issue by PrinceMarkieD** [MicrosoftDocs/SCCMdocs#1073]
Once a Custom Class has been added via WMI of remote Device, is it still necessary to extend the inventory by appending information to the Configuration.mof file?
Also, it appears you can only add custom classes to the Default Client settings, where you may not want to enable it. You can then enable the Custom Class in a more granularly scoped Client Settings item.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54dd8166-9fb1-3027-ad24-6a14c2dd5f3f
* Version Independent ID: 02c01bf8-020c-b29a-ab8f-1541c83743b5
* Content: [Extend hardware inventory - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/inventory/extend-hardware-inventory)
* Content Source: [sccm/core/clients/manage/inventory/extend-hardware-inventory.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/inventory/extend-hardware-inventory.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @PrinceMarkieD for the feedback. I'll investigate.

**Comment by PrinceMarkieD** [comment]
I can confirm those statements above. With that, this is the easiest way to add custom classes that I have used. This is actually so powerful, and simple that a person can build one class that holds every single bit of information they want to report on, and reduce the need to collect on many of the data tables that contain only one or two useful columns.
Also the issue i was having that made me wonder if extending the mod was needed, was my fault for some reason BITS was disabled on my machine. I will add enabling BITS in the configuration item.
Thank you again for this!

**Comment by aczechowski** [comment]
Some further clarification that I think warrants addition to this article to enhance it:

If the WMI class doesn't already exist on the client (if you need to extend the WMI schema):
- Edit the configuration.mof on the CAS (or standalone primary). Review dataldr.log to see the site add it. 
- Refresh policy on a client, wait for it to compile on the client 
- Use Default Client Settings to **Add** the new class to hardware inventory. You don't have to enable this class in Default Client Settings. You can then enable it in a custom device client setting. 

So the distinction is between "extend", "add" and "enable". 
- **Extend**: add a new WMI class to the client. This action is done manually via editing the configuration.mof on the top-level site (CAS or standalone primary).  
- **Add**: if a WMI class exists on the client and is known to the site, this action includes it to the possible set of hardware inventory classes. This action is only on default client settings.  
- **Enable**: enable some or all attributes of a class. This action instructs the hardware inventory agent to collect it on clients. You can do this in default client settings, or custom device client settings.

**Comment by aczechowski** [comment]
I added this information to the article, it will publish tomorrow
