### ISSUE TITLE
Update for 1810 - SQL AO Support on Site Servers

### ISSUE THREAD

**Issue by excelsi84** [MicrosoftDocs/SCCMdocs#1074]
Can you update the Docs for SQL Always On Support on the Site Servers?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c416209-7476-14b2-a60b-9f3477dc79be
* Version Independent ID: 765534af-f933-c768-0994-fa8d0a5712a0
* Content: [Site server high availability - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/site-server-high-availability)
* Content Source: [sccm/core/servers/deploy/configure/site-server-high-availability.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/site-server-high-availability.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
@excelsi84 can you please clarify your question? What specifically are you suggesting we update?

**Comment by excelsi84** [comment]
For example this:
"Both site servers must use the same site database, which must be remote each site Server" 
The Database could be on the Site Servers itself in a SQL Always On AG since 1810.

Additionally maybe also a step by step guide how to Deploy a two Box HA Solution (Site Server + SQL Always On)

**Comment by aczechowski** [comment]
I made revisions to this article, so closing this issue. The changes should publish later today or tomorrow morning at the latest.

**Comment by excelsi** [comment]
Hm, only the the Top Article was updated not this one...?

**Comment by aczechowski** [comment]
We haven't had a publishing event yet. That should happen in the next hour on our daily schedule.

**Comment by excelsi** [comment]
Ok Thanks!
