### ISSUE TITLE
SQL change tracking cleanup

### ISSUE THREAD

**Issue by PrajwalDesai** [MicrosoftDocs/SCCMdocs#1076]
I have tried the command for tracking clean up but i still see the warning during prerequisite check. In fact i ran the command multiple times, it shows the query is complete but i have no idea how to fix that warning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db678f94-700f-ad35-9fdc-d165893b5373
* Version Independent ID: 2ee761db-4b3b-6fa0-c195-ad85ebbac70d
* Content: [Prerequisite checks - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/list-of-prerequisite-checks#bkmk_changetracking)
* Content Source: [sccm/core/servers/deploy/install/list-of-prerequisite-checks.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/list-of-prerequisite-checks.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback, and sorry for the problems. I'm checking with engineering on best next steps.

**Comment by PrajwalDesai** [comment]
> Thanks for the feedback, and sorry for the problems. I'm checking with engineering on best next steps.

No worries. Thanks Aaron.

**Comment by michielvanheerde** [comment]
Hi, any news on the status of this issue? I am running into it as well and it looks like the the @CleanupChangeTracking = 1 is not doing anything as it returns the same results as the command without that declaration.

**Comment by maniaX1** [comment]
Hell, I went into this problem, too. Is there any solution available at the moment? Thank you.

**Comment by aczechowski** [comment]
Engineering reviewed one report of this and didn't find any issues, the warning went away.

There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
- Send [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) to file the issue directly with the engineering team. 

I don't have anything actionable for docs at this time, so I'm closing this issue.

**Comment by PrajwalDesai** [comment]
Hi Aaron, the warning is still seen when the SQL version is 2014 SP3.
