### ISSUE TITLE
CMG Naming Restrictions

### ISSUE THREAD

**Issue by bankimp** [MicrosoftDocs/SCCMdocs#1080]
Unsupported characters (like dashes) for the CMG FQDN should be called out. 

(admin edit - revised metadata to switch target article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c095180-90a2-79c6-a7fb-6504cafbcfb6
* Version Independent ID: fb9c2930-b213-3eef-c7bb-c8f11ec97aca
* Content: [CMG Certificates](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway#bkmk_serverauth)
* Content Source: [sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @bankimp, that's a good tip.

**Comment by aczechowski** [comment]
I moved this over to the CMG certificates article, which is where we already have the tip about checking that the **Service FQDN** is globally unique in Azure. I also checked with engineering for the extent of the naming restrictions:

> We have more restrictive rule in the wizard because we also use the same string as the storage account name when deploying CMG. 
> “The host name should be between 3 and 24 characters in length and should have alphabets and numbers only.”

**Comment by russrimm** [comment]
I think we could use more info on the SUP certificate options for CMG. Is httpE required for the CMG SUP to support http? Or is an http CMG SUP supported regardless of 1806 and httpE being enabled?

**Comment by aczechowski** [comment]
(Refer to #1148 for @russrimm's question about SUP)

**Comment by aczechowski** [comment]
I'm closing this issue as I made changes to the article that will publish with the 1906 content in the near future
