### ISSUE TITLE
Property Names Markdown is Hosed

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/SCCMdocs#1081]
Somehow the Property names (captions/labels) are formatted such that they're hard to pick out without 42 cups of coffee and a jeweler's eyepiece.  Please make them bold and easier to find?  Thank you- you guys rocks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a714c8ed-9275-0502-d6a6-36c2abd6cda9
* Version Independent ID: 89f8673b-1545-d54a-1b66-dac64ef06941
* Content: [SMS_PackageBaseclass Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/core/servers/configure/sms_packagebaseclass-server-wmi-class)
* Content Source: [sccm/develop/reference/core/servers/configure/sms_packagebaseclass-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/core/servers/configure/sms_packagebaseclass-server-wmi-class.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Skatterbrainz for the feedback. Agreed, the code formatting for the sections is not very useful. Just a matter of switching the \` tags to an H3: precede the line with `###`. Can even just add the H3 and keep the code tags, that should work as well. I'll make this issue for good-first-issue if someone from the community is interested in fixing it. (And I assume it's not just this article, but probably most of the SDK reference articles.) [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute)

**Comment by aczechowski** [comment]
Fixed by referenced pull request, closing
