### ISSUE TITLE
Missing Products in SUP 

### ISSUE THREAD

**Issue by felymich** [MicrosoftDocs/SCCMdocs#1089]
Hello,
I have several products with updates published (Google, Firefox) which does not show up in SUP Products List in SCCM Console &gt; Site &gt; Component. Adobe is showing but it is the only one except Microsoft.
How are they added to the SCCM Console from the publishing in SCUP?
Thanks,
Dom 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ba7dbf0-30e8-bb4f-da83-410521eee746
* Version Independent ID: a07106bb-fcd6-bda8-c8e1-91b4cbe030d5
* Content: [Configure options - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/tools/updates-publisher-options)
* Content Source: [sccm/sum/tools/updates-publisher-options.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/tools/updates-publisher-options.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Once the content is published into WSUS, then the normal process applies. Just as if Microsoft adds a new product. For that information, see [Configure classifications and products](https://docs.microsoft.com/sccm/sum/get-started/configure-classifications-and-products). For example, when you first configure a SUP, it doesn't list newer products like Windows 10 until you do the first synchronization between WSUS and SCCM. 
I'm closing this issue as doc-provided.
