### ISSUE TITLE
Clarification?

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/SCCMdocs#1100]
On this line, I'm thinking it shouldn't say to run the command-line but rather copy and paste it (without the ccmsetup.msi) into the Intune app that is being created?
5. After the app is updated, configure the app information by running the following command-line argument:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7294682b-1bfb-54e4-0bdb-178e6fe2cc9a
* Version Independent ID: 6c5f1cfb-ae12-1fd2-80ef-1f67e419f4c5
* Content: [Prepare Windows 10 for co-management - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/co-management-prepare)
* Content Source: [sccm/core/clients/manage/co-management-prepare.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/co-management-prepare.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Yes, thanks @russrimm for the feedback. I hope to rework this entire article in the near future.

**Comment by aczechowski** [comment]
I'm closing this issue. A big revision to the co-management content will publish soon and address this issue.
