### ISSUE TITLE
Proofing tools support updates Configmgr

### ISSUE THREAD

**Issue by thysj** [MicrosoftDocs/SCCMdocs#1105]
I have an issue with updating Office 365 with configuration manager when I have proofing tools installed for example Microsoft Office 365 ProPlus de-de.proof or nl-nl.proof

I can only select full language package support but not specific proofing tools in Config manager even with the full language pack it does not update the proofing tools?
My default XML contains proofing tools but update files are missing in O365 client updates:
&lt;Product ID="ProofingTools"&gt;
&lt;Language ID="de-de"/&gt;
&lt;Language ID="nl-nl"/&gt;

This is the error I have in SCCM client:
DTS job failed to download source file ***sp321031.cab to destination C:\WINDOWS\ccmcache\44.B26B.dlt\Office\Data\16.0.10730.20262\sp321031.cab with error 0x80190194

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1da48af-4783-bd17-67f3-f265df93503f
* Version Independent ID: 17432b22-04cb-f47f-1634-e5b7fc99c37d
* Content: [Manage Office 365 ProPlus updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/manage-office-365-proplus-updates)
* Content Source: [sccm/sum/deploy-use/manage-office-365-proplus-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/manage-office-365-proplus-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @thysj for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
