### ISSUE TITLE
missing guidance on support of third party MDM (original: サードパーティの MDM のサポートに関する案内が不足している)

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/SCCMdocs#1106]
@Satoshi-Mori commented on [Thu Dec 20 2018](https://github.com/MicrosoftDocs/SCCMDocs.ja-jp/issues/26)

System Center Configuration Manager Current Branch で Microsoft Intune 以外の MDM 製品がインストールされた端末が管理できない動作を確認している。サードパーティ製品の MDM ソリューションのサポート状況について記載を追加して欲しい。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: aa13f673-5774-5dbf-1e5c-96dc8bf4cb3a
* Version Independent ID: 03e05465-5742-9e6c-1ac4-9b2e197978da
* Content: [オンプレミス MDM の計画 - Configuration Manager](https://docs.microsoft.com/ja-jp/sccm/mdm/plan-design/plan-on-premises-mdm#feedback)
* Content Source: [sccm/mdm/plan-design/plan-on-premises-mdm.md](https://github.com/Microsoft/SCCMDocs.ja-jp/blob/live/sccm/mdm/plan-design/plan-on-premises-mdm.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by CeciAc** [comment]
Hi team,
There's a suggestion to the documentation from this contributor
Rough translation:

> We are missing guidance on support of third party MDM
> 
> System Center Configuration Manager Current Branch confirms operations that can not be managed by terminals installed with MDM products other than Microsoft Intune. Please add a description about support status of MDM solution of third party products.

**Comment by aczechowski** [comment]
Thank you @Satoshi-Mori for the feedback.

**Comment by aczechowski** [comment]
The article that I think answers this question is [Third-party MDM coexistence with Configuration Manager](https://docs.microsoft.com/sccm/comanage/coexistence). At this time I don't plan on adding anything in the on-prem MDM content about third-party MDM. We will be revising the on-prem MDM content in the near future due to the hybrid end of service.
