### ISSUE TITLE
The Connections in Primary Role setting is Yes

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/SCCMdocs#1107]
Under the sub-topic "Each replica member must have the following configuration:", i'm not sure if it's specific to SQL 2017, but when looking at this setting in my environment, there is no YES option, only a "Allow all connections" and a "Allow read/write connections"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53d1da83-d988-fb2b-82c5-fd9cf117cd42
* Version Independent ID: 2b1a3bd2-5116-1f21-c196-e3e5698a83c9
* Content: [SQL Server Always On - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database)
* Content Source: [sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by ChrisKibble** [comment]
Looks like this is fixed in #1110 and can be closed.
