### ISSUE TITLE
Autopilot information collection

### ISSUE THREAD

**Issue by deanellerby** [MicrosoftDocs/SCCMdocs#1116]
In the "New Windows 10 Devices" section, it suggests that ConfigMgr 1806 can be used to collect the information required for Autopilot enrolment, however it then refers to using this information to enrol into Intune / WSfB and then install the ConfigMgr client.

It doesn't seem possible to gather the required information before installing the ConfigMgr client, so I'd suggest this information is in the wrong place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7294682b-1bfb-54e4-0bdb-178e6fe2cc9a
* Version Independent ID: 6c5f1cfb-ae12-1fd2-80ef-1f67e419f4c5
* Content: [Prepare Windows 10 for co-management - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/co-management-prepare)
* Content Source: [sccm/core/clients/manage/co-management-prepare.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/co-management-prepare.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @deanellerby for the feedback. It's really a precursor for the [Autopilot for existing devices](https://docs.microsoft.com/sccm/core/clients/manage/co-management-prepare#new-windows-10-devices) scenario. But I agree that without that additional context it does seem out of place.

**Comment by aczechowski** [comment]
I'm closing this issue. A big revision to the co-management content will publish soon and address this issue.
