### ISSUE TITLE
Co-management workload grayout

### ISSUE THREAD

**Issue by labalex** [MicrosoftDocs/SCCMdocs#1117]
Hi, seems that once created I can't delete the co-management or modify propreties on the worloads, it's grayout. Is there something we need to do to enable that?

Version is 1806 and I'm a full administrator.

Thanks

Alex

![image](https://user-images.githubusercontent.com/7939167/50494976-61439500-09f4-11e9-9b62-884986d15686.png)

**Comment by aczechowski** [comment]
Thanks @labalex for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by labalex** [comment]
Thanks, you are right, to change the workload you need to be Full administrator but the scope need to be "All instance of the objects that are related to assigned security role". Whitout that, no way to change the Co-management workloads.

![image](https://user-images.githubusercontent.com/7939167/50520797-60f8d780-0a90-11e9-89f9-00a4614b5d5a.png)

**Comment by aczechowski** [comment]
Yes, see the important note at the top of this section to [Enable co-management](https://docs.microsoft.com/sccm/core/clients/manage/co-management-overview#enable-co-management)
