### ISSUE TITLE
Add PowerShell cmdlet examples for each task sequence step

### ISSUE THREAD

**Issue by elang-bmrn** [MicrosoftDocs/SCCMdocs#1118]
It would be great if there were references to the PowerShell cmdlets for each task sequence step, along with examples. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1187d55d-d8b3-ebc8-37e8-8de14807be4e
* Version Independent ID: daff4a99-10ac-b424-f08a-9024407e667a
* Content: [Task sequence steps - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/understand/task-sequence-steps#BKMK_ApplyDriverPackage)
* Content Source: [sccm/osd/understand/task-sequence-steps.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/understand/task-sequence-steps.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @elang-bmrn for the feedback. That's a great idea. I think the examples would live best with the cmdlet documentation, but I like the thought of interlinking them.

**Comment by aczechowski** [comment]
I revised the article to include all of the currently available cmdlets for TS steps. The change will publish live on Monday.
