### ISSUE TITLE
Peer cache ports

### ISSUE THREAD

**Issue by KentaShibatani** [MicrosoftDocs/SCCMdocs#1119]
[Enter feedback here]
Hi,
My customer found that ports for client peer cache that means 8003 and 8004 is not included at this document https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/ports .
Could you add these ports for peer cache at "Client -> Client" section?

https://docs.microsoft.com/en-us/sccm/osd/get-started/prepare-windows-pe-peer-cache-to-reduce-wan-traffic

Thanks,
Kenta

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f658ee4b-d051-0d7c-4656-19a846908469
* Version Independent ID: 3478e881-199c-f0c4-b218-0dd609eb0427
* Content: [Ports used for connections - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/ports)
* Content Source: [sccm/core/plan-design/hierarchy/ports.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/ports.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Good catch, thanks @KentaShibatani

**Comment by aczechowski** [comment]
Thanks @jocasti for submitting an edit for this. The revision should publish live tomorrow.
