### ISSUE TITLE
What does this line mean?

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/SCCMdocs#1126]
"Scenario 3 only: A client running Windows 10 version 1803 and joined to Azure AD." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cfc73c1-e15c-5dde-2a22-5cfc3eb7eb1c
* Version Independent ID: 50df732f-9232-74f6-f7d2-dda59c9b125b
* Content: [Enhanced HTTP - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/enhanced-http#bkmk_scenario3)
* Content Source: [sccm/core/plan-design/hierarchy/enhanced-http.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/enhanced-http.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
That prerequisite is only for the third scenario, not the other two. Do you have suggestions on how to make that more clear?

**Comment by TroyMartinNet** [comment]
Aaron, I would maybe add "(**For**?) Scenario 3 only: _clients must be running Windows 10 1803 (or later) and joined to Azure AD_."

**Comment by Silencer0001** [comment]
In scenario 3 you are mentioning "Azure AD-joined" and "hybrid Azure AD device".
Does the remark in this line mean that W10 version 1803 (and later) is only required for "Azure AD-Joined" devices and not for "Hybrid Azure AD device"?

In scenario 3 you are mentioning: "without an Azure AD user signed in" and "The cloud-based device identity is now sufficient to authenticate with the CMG and management point for device-centric scenarios.".
Does the remark in this line mean that when an Azure AD user is signed in, communication can always be done (W10 all versions) for both user and device scenario. And that for W10 1803 (and later) the Azure AD (without user) is sufficient?

Or does it mean that Windows 10 1803 (or later) is required to authenticate with the Azure AD computer account for Azure AD Joined and Hybrid Azure AD Joined devices?

**Comment by aczechowski** [comment]
In general, I think this issue is resolved now. I added one further bit to the third prereq in an attempt to help clarify even further, and address @Silencer0001's questions. And to that - it's your last point. In order for device auth to work, you need Win10 1803 or later, and joined to Azure AD.

The change should publish during tomorrow's daily process (around 11am Pacific)
