### ISSUE TITLE
No reboot

### ISSUE THREAD

**Issue by Henrikcj** [MicrosoftDocs/SCCMdocs#1127]
Hello.
Acroding to this: https://docs.microsoft.com/en-us/windows/deployment/upgrade/windows-10-edition-upgrades pro til Enterprise dose not require a reboot. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f49b9244-7797-8fbb-afb9-dd245692be2f
* Version Independent ID: 5c7d7bde-2fe5-54f6-55fe-db4b2631f9a7
* Content: [Upgrade Windows devices to a different version - Configuration Manager](https://docs.microsoft.com/en-us/sccm/compliance/deploy-use/upgrade-windows-version)
* Content Source: [sccm/compliance/deploy-use/upgrade-windows-version.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/compliance/deploy-use/upgrade-windows-version.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Henrikcj for the feedback

**Comment by Henrikcj** [comment]
Just to be clear, it wont reboot a pc if this is done by SCCM ?

**Comment by aczechowski** [comment]
The SCCM client is just calling the Windows API to trigger the edition upgrade. Historically it was Windows that then triggered the restart. So if that API no longer requires a restart, then that shouldn't happen in this scenario.

**Comment by aczechowski** [comment]
Thanks @brenduns for submitting an edit to improve this article. I'm closing this issue. The change will publish live tomorrow (Tuesday, 11 June) around 11am Pacific time.
