### ISSUE TITLE
AAD Auth won't work when you follow above steps to import Apps.

### ISSUE THREAD

**Issue by motaj1** [MicrosoftDocs/SCCMdocs#1135]
AAD Auth won't work on the clients when you follow the above steps to manually Create the Web/Native Apps in the Portal and Import it in SCCM.
We may see following error in the client logs:
Getting AAD (user) token with: ClientId = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, ResourceUrl = https://ConfigMgrService, AccountId = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx           ccmsetup               11/27/2018 10:18:23 PM  4208 (0x1070)
WAM token request failed. Status 5, Details 'AADSTS50001: The application named https://ConfigMgrService was not found in the tenant named xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.  This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant.  You might have sent your authentication request to the wrong tenant.
You would have to do two changes for AAD Auth to work with manual App import:
1. APP ID URI cannot be left to default when importing the Server App. You must use what is configured under the App Properties in Azure Portal. 
2. You may have to specific “ms-appx-web://Microsoft.AAD.BrokerPlugin/&lt;Client App ID&gt;” as Redirect URI under Client App properties.
Note: CMG would work fine if Certs are used for Authentication. It’s only AAD Auth which doesn’t work.
Please let me know if you need additional details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e03621cf-11f9-e98c-8006-9288bfc77c7e
* Version Independent ID: d3b84cd8-05cb-3a77-5c5e-4d7703298202
* Content: [Configure Azure services - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/azure-services-wizard)
* Content Source: [sccm/core/servers/deploy/configure/azure-services-wizard.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/azure-services-wizard.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @motaj1 for the feedback. I confirmed with engineering that both are valid points.

**Comment by ml58158** [comment]
Any update to this: I tried the above steps but it doesn't accept ms-appx-web://Microsoft.AAD.BrokerPlugin/... due to it doesnt start with http/https.

**Comment by aczechowski** [comment]
@ml58158 I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Via MicrosoftDocs/memdocs#1417 I've learned that the manual steps for app registrations have changed yet again, so I need to make changes to the several articles that have similar steps. You can subscribe to that issue to be notified when I make those changes (no current ETA).
