### ISSUE TITLE
Within the support Config for SQL

### ISSUE THREAD

**Issue by Garthmj** [MicrosoftDocs/SCCMdocs#1142]
Is there are reason why SSRS/RP is not listed as support role for all version of SQL above?
AKA likes this? 

A central administration site
A primary site
A secondary site
And Reporting Points

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb55272-b9ee-0407-d034-f6fc37c979a3
* Version Independent ID: 9745517a-b005-84a8-d45a-fe02a636134f
* Content: [Supported SQL Server versions - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/support-for-sql-server-versions)
* Content Source: [sccm/core/plan-design/configs/support-for-sql-server-versions.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/support-for-sql-server-versions.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by CraigB7708** [comment]
is Sql 2019 not support with the current branch?

**Comment by aczechowski** [comment]
@CraigB7708, offtopic for this specific issue, but I can answer: we'll add version 2019 when we've tested and verified it meets our customers' requirements for performance and function. That's in progress, so we'll update the doc when ready.

**Comment by aczechowski** [comment]
I submitted a change for both of these points 😉 
Once the pull request merges, this issue will auto close.
I'm actually thinking of doing an out of band publish this afternoon, so you should see the changes live shortly
