### ISSUE TITLE
For best performance, install the reporting services point on a remote site system server

### ISSUE THREAD

**Issue by Garthmj** [MicrosoftDocs/SCCMdocs#1143]
How was this determine? Shouldn't RP be on the same server as SQL? Thereby allowing for faster query execution and reduced network traffic? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce5953cb-562f-3eab-9fcc-8d7b987ac025
* Version Independent ID: 2b5ddaf1-b68c-b8cc-cf65-9327779cce64
* Content: [Reporting best practices - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/best-practices-for-reporting)
* Content Source: [sccm/core/servers/manage/best-practices-for-reporting.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/best-practices-for-reporting.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Garthmj, good question, let me check.

**Comment by aczechowski** [comment]
In making some changes for 2002 content, I'm actually going to remove this article. I'm moving the content as a subsection of the planning article. But I can answer this question (and the revision will include a summary):

> The RSP does work in the background. Not having that work performed on the site server means it uses less resources on the site server. It’s really just that simple. For example if you have a set of reports that you have scheduled to run as a subscription, that’s work the SRS instance has to do. performance is so variable and dependent on so many other things. It really depends on how much report usage you are really doing. Some folks set up MP replica DB’s and configure their reporting instance to point to that so there is no reporting against the live production database. It’s all very dependent on many variables, but in general if you have intensive performance needs then offloading any CPU/Memory usage from the site would help.

I'm closing this issue.
