### ISSUE TITLE
What about SUP?

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/SCCMdocs#1148]
There's some confusion on blogosphere about whether or not Enhanced HTTP is required to use an HTTP SUP on CMG. You're able to set a SUP to HTTP without enabling Enhanced HTTP, so I don't believe it is required?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cfc73c1-e15c-5dde-2a22-5cfc3eb7eb1c
* Version Independent ID: 50df732f-9232-74f6-f7d2-dda59c9b125b
* Content: [Enhanced HTTP - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/enhanced-http)
* Content Source: [sccm/core/plan-design/hierarchy/enhanced-http.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/enhanced-http.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Good question @russrimm, I'm checking on this

**Comment by aczechowski** [comment]
SUP has always supported HTTP with CMG. It uses a different auth mechanism, different from cert or token client auth that's used with the MP. 

This point is probably good to note. 😄

**Comment by ReneKierstein** [comment]
Are there plans to include SUP in the Enhanced http model, so we can avoid PKI?

**Comment by torontojc** [comment]
@ReneKierstein The SUP can either be in HTTP or HTTPS mode. Note that this HTTPS mode is not the same as a MP in HTTPS mode. The SUP/WSUS HTTPS mode is only a server side cert and no client certificates or keys come into play with respect to PKI as far as I know. [WSUS](https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/deploy/2-configure-wsus#bkmk_2.5.ConfigSSL) [SUP](https://docs.microsoft.com/en-us/sccm/sum/get-started/install-a-software-update-point#configure-ssl-communications-to-wsus)

**Comment by aczechowski** [comment]
This issue is closed because I made a change to the article to add this information. The updated article should publish live tomorrow around 11am Pacific.
