### ISSUE TITLE
Add ConfigMgr Antivirus Exclusions Article

### ISSUE THREAD

**Issue by brmcmill** [MicrosoftDocs/SCCMdocs#1154]
We have been having a lot of different feedback in regards to providing official guidance regarding Antivirus Exclusions for ConfigMgr or other products collectively in MS Docs where we can collectively reference our Support Articles covering recommendations for customers.  Previously we had been leveraging other sources such as Blogs or Wiki pages to evangelize updated articles on Microsoft products.  Here is a recent example that would be more appropriately detailed in MS Docs:

https://techcommunity.microsoft.com/t5/Core-Infrastructure-and-Security/Configuration-Manager-Current-Branch-Antivirus-Exclusions/ba-p/884831

Thanks again for your time!

Brandon

**Comment by aczechowski** [comment]
I'm closing this issue, we're tracking with an internal work item (7035138)
