### ISSUE TITLE
Binary Differential Replication Question/Confusion

### ISSUE THREAD

**Issue by bryandam** [MicrosoftDocs/SCCMdocs#1155]
The BDR description here is really confusing to me.
What does "Binary differential replication (BDR) is a prerequisite for distribution points" mean?  BDR isn't an OS feature although Remote Differential Compression (which I believe it requires) is.
"It then replicates only the changed files to destination sites and distribution points" Wait ... is BDR binary/block level or file level?  The current description sounds a lot like Single Instance Storage, not binary differential working at the block level.  The whole section seems to have that confusion.  If I was certain of the answer I'd just edit it myslef.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff2f1985-822a-f9aa-8368-9abf85c50118
* Version Independent ID: 3401e963-f1cf-a15d-01f2-c1754a7d9336
* Content: [Content management fundamentals - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management#binary-differential-replication)
* Content Source: [sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by bryandam** [comment]
Alright, nevermind, Kerwin laid down some truth on Technet.  Small PR incoming.

**Comment by aczechowski** [comment]
Fixed by #1159
