### ISSUE TITLE
Known Issues with Azure Services

### ISSUE THREAD

**Issue by rondls4** [MicrosoftDocs/SCCMdocs#1163]
Please update the 'Known Issues with Azure Services' to include that the Cloud Management Gateway (if installed) on the Primary, needs to be uninstalled first to expand a stand-alone primary site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b3c02ca-4813-9b76-65a6-e9afce739bad
* Version Independent ID: 8fd815c3-c681-247a-7674-76109d5ed1e6
* Content: [Prerequisites for sites - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/prerequisites-for-installing-sites)
* Content Source: [sccm/core/servers/deploy/install/prerequisites-for-installing-sites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/prerequisites-for-installing-sites.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by rondls4** [comment]
Thanks for the response but running the Prerequisite Check during the CAS expansion results in 'Unsupported Cloud Management Gateway...' message. It clearly states that 'You must uninstall the Cloud Management Gateway from the primary site before you can continue'.

![cas_prereq_check_cmgissue](https://user-images.githubusercontent.com/46690108/51333911-91021d80-1a33-11e9-8f78-abe3670c24d6.jpg)

**Comment by aczechowski** [comment]
This issue is closed because I submitted a change for it that will publish tomorrow
