### ISSUE TITLE
Prerequisites - Microsoft Intune

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/SCCMdocs#1164]
Under Prerequisites - Microsoft Intune it points to a setup Intune link. I think it should also be clear that Intune automatic enrollment needs to be configured. The setup Intune link is generic. The tutorial for setting up Co-management covers this requirement but it should be listed under the requirements on this page.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f24ae716-bf27-7d45-cb15-0bc6eea64374
* Version Independent ID: f444ef64-9b7d-999f-3fb3-6ac6cda3ef88
* Content: [Co-management for Windows 10 devices - Configuration Manager](https://docs.microsoft.com/en-us/sccm/comanage/overview)
* Content Source: [sccm/comanage/overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/overview.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Good point, thanks @nhogarth86

**Comment by aczechowski** [comment]
@nhogarth86 looking further at this issue. I'm reading two things in your comment that I'd like to distinguish:
1. "Intune automatic enrollment needs to be configured" - this is already in the prereqs under the Azure AD section. I honestly debated where to place it. It's an Intune requirement, but the action is in Azure AD. I can assume from your feedback that you expect it to be under the Intune section?
2. "The setup Intune link is generic." - it links to the main "how-to" guide to set up Intune. what else do you suggest as a target for this fundamental Intune prereq?

**Comment by nhogarth86** [comment]
Hi Aaron - my opinion is that the Intune automatic enrollment should be under the Intune section (I know that its configured in Azure AD section). If its near the Intune section, then the main Intune how-to guide is fine. To be honest I didn't even see it under the Azure AD section at first, probably because I wasn't expecting it. After reading it all again though it makes more sense.

**Comment by aczechowski** [comment]
Great thanks. I just submitted a change to adjust this, thus the issue is closed. The change should publish live tomorrow around 11am Pacific.
