### ISSUE TITLE
Enrollment point requirement for WCF support in IIS

### ISSUE THREAD

**Issue by matthew-richards** [MicrosoftDocs/SCCMdocs#1168]
I'm troubleshooting an issue with Microsoft support and it is unclear in this documentation for Enrollment point that WCF in IIS is used. We were able to fix an ongoing issue at our site by commenting out various sections of the web.config and machine.config in the .NET config for IIS, but as a result it also breaks Enrollment Point. It would have been helpful to have some official documentation the WCF is involved. Unfortunately I couldn't provide that level of detail to your IIS team until I found a reference to it on a forum post on another website. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9070eb9b-0e5f-a877-e02e-2d1cea2a2b38
* Version Independent ID: df251762-f2d6-9f06-4fa9-ec5cea2cca0a
* Content: [Site prerequisites - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/site-and-site-system-prerequisites)
* Content Source: [sccm/core/plan-design/configs/site-and-site-system-prerequisites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/site-and-site-system-prerequisites.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @matthew-richards for the feedback. I'll check on this requirement with our engineering team.

**Comment by aczechowski** [comment]
Yes, WCF is required. 

I only found two mentions of WCF in our doc library, both of which are rather generic:
- [Set up your lab](https://docs.microsoft.com/sccm/core/get-started/set-up-your-lab#BKMK_OtherTasksLab)
- [Prepare Windows Servers to support site systems](https://docs.microsoft.com/sccm/core/plan-design/network/prepare-windows-servers#features)

**Comment by aczechowski** [comment]
This issue is closed because I revised the article to include this information. The changes should publish live tomorrow (Thursday, 7 March) around 11am Pacific time.
