### ISSUE TITLE
Could be improved by expanding values for Sources, Types

### ISSUE THREAD

**Issue by JuliusPIV** [MicrosoftDocs/SCCMdocs#1173]
Hi Team.  The documentation for the SMS_UserMachineRelationship Server WMI Class could be improved by providing details of what valid values are for Sources and Types and an explanation of said values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52f5960-4077-0c4f-5cee-82a755c74dee
* Version Independent ID: cf9ca255-90ea-d747-0fe6-d7084eeb5cd7
* Content: [SMS_UserMachineRelationship Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/core/clients/manage/sms_usermachinerelationship-server-wmi-class)
* Content Source: [sccm/develop/reference/core/clients/manage/sms_usermachinerelationship-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/core/clients/manage/sms_usermachinerelationship-server-wmi-class.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by JuliusPIV** [comment]
I poked at this a bit today and it seems like for Sources:
     1 = Catalog Defined
     2 = Administrator
     4 = Usage Agent Defined
     6 = OSD Defined
I can't figure out what 7 means other than maybe the user listed in UniqueUserName has logged into the machine at least once.


As for Types it seems as though 1 means the user listed in UniqueUserName has been assigned as a Primary User of the device and if it's null/empty then they are not listed as a Primary User.

**Comment by JuliusPIV** [comment]
Thanks for taking the time to reply @aczechowski and I understand completely.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
