### ISSUE TITLE
OfferFlags = 8 not described

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/SCCMdocs#1180]
Please update to describe what a value of 8 is for OfferFlags?  Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44b8a49c-e3ea-21ef-c13f-b7ffb228919b
* Version Independent ID: dc505ab5-6ff5-4fb2-7ca0-9783457b4d06
* Content: [SMS_ApplicationAssignment Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/apps/sms_applicationassignment-server-wmi-class)
* Content Source: [sccm/develop/reference/apps/sms_applicationassignment-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/apps/sms_applicationassignment-server-wmi-class.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by codaamok** [comment]
Hey @Skatterbrainz I just found this when looking at the `OfferFlags` property for `SMS_ApplicationAssignment` class in WMIExplorerv2:

```
       OfferFlags - UInt32
        
       Qualifiers: bits, CIMTYPE, not_null
       
       [Description Not Available]
       
       Possible Bit Values: 
       PREDEPLOY(1)
       ONDEMAND(2)
       ENABLEPROCESSTERMINATION(4)
       ALLOWUSERSTOREPAIRAPP(8)
       RELATIVESCHEDULE(16)
       HIGHIMPACTDEPLOYMENT(32)
```

The docs could do with updating. I'll create PR now. I'm not sure where WMIExplorer is pulling from to get this information but I'd love to know.

**Comment by Skatterbrainz** [comment]
Hey! I pulled that from a sql query actually, but wmi would probably return
the same values.
