### ISSUE TITLE
Path to SCAP extensions folder

### ISSUE THREAD

**Issue by jpcast88** [MicrosoftDocs/SCCMdocs#1184]
In my v1806 lab I found the SCAP extensions folder under "...\Microsoft Configuration Manager\AdminConsole\bin\SCAP Extensions". If this is the correct path, should we add 'bin' to the path in the 'Install SCAP extensions' section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d0098dd-8fe4-9651-f691-d81fd5674329
* Version Independent ID: 4ab396a7-c337-e53e-978a-a46761ef0aa6
* Content: [Install and configure SCAP extensions - Configuration Manager](https://docs.microsoft.com/en-us/sccm/compliance/plan-design/scap/install-configure-scap#bkmk_install)
* Content Source: [sccm/compliance/plan-design/scap/install-configure-scap.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/compliance/plan-design/scap/install-configure-scap.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Checking...

**Comment by aczechowski** [comment]
Closing this issue as I'm removing this content. Version 1806 is out of support, and SCAP isn't available in later versions.
