### ISSUE TITLE
Clarify "update" versus "distribute"

### ISSUE THREAD

**Issue by griswolm** [MicrosoftDocs/SCCMdocs#1185]
To make things crystal clear I suggest that the section on "distribute content" should point out that it pulls from the primary site's content library.  Similar, on "Update Distribution Point" it should use similar wording to say it pulls from the original package source location.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 658824b0-308f-88e5-4292-52a34587a111
* Version Independent ID: db08f7ce-3c4b-f7ba-e6f6-e22d00be8757
* Content: [Deploy content - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/deploy-and-manage-content)
* Content Source: [sccm/core/servers/deploy/configure/deploy-and-manage-content.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/deploy-and-manage-content.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @griswolm, good feedback! 😄
