### ISSUE TITLE
Report missing

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/SCCMdocs#1189]
The list mentions the following list "Details of firmware states on devices" however i have checked two instances of configmgr 1810 and the report does not exist. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a01dd64-8ff0-4bf0-a8af-6036abcad725
* Version Independent ID: 48b86273-4bd1-6ec5-cb42-a202cccb0433
* Content: [List of reports - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/list-of-reports)
* Content Source: [sccm/core/servers/manage/list-of-reports.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/list-of-reports.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @alexverboon for taking the time to share this with the Configuration Manager documentation team. I can see it in our test environment, and I don't see any active bugs about it missing.

I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by aczechowski** [comment]
OK, I checked with engineering. The report was pulled from 1810 due to issues with it, but is back in the later builds I was looking at. I'll reopen this issue to note that the report is not in 1810.

**Comment by aczechowski** [comment]
We closed this issue because I submitted a change to address it. It will publish live tomorrow around 11am Pacific.
