### ISSUE TITLE
Formatting is Broken

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/SCCMdocs#1192]
Below "ResourceType" the indention is weird.  Also, the property names are difficult to spot using the current style.  They should be H2 or H3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c042909-6e62-1bfa-a2f9-8e277653a1d6
* Version Independent ID: 6fec2a17-7919-ebb1-553e-63a892300592
* Content: [SMS_DistributionPointInfo Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/core/servers/configure/sms_distributionpointinfo-server-wmi-class)
* Content Source: [sccm/develop/reference/core/servers/configure/sms_distributionpointinfo-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/core/servers/configure/sms_distributionpointinfo-server-wmi-class.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Skatterbrainz for the feedback. If you're willing, you can submit an edit to fix it! For more information, see [How to contribute](https://docs.microsoft.com/en-us/sccm/core/understand/use-docs#bkmk_contribute).

**Comment by aczechowski** [comment]
I fixed this last week, thus closed the issue. The change should go live shortly with today's daily publishing process.
