### ISSUE TITLE
Service Connection Point and CMG Connection Point

### ISSUE THREAD

**Issue by rdr222** [MicrosoftDocs/SCCMdocs#1194]
I don't see any communication in the list for the Site Server to either the Service Connection point or CMG Connection Point.  Shouldn't there be at least a listing for RPC, RPC Dynamic, and SMB from the site server to these roles like there is for most other roles?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f658ee4b-d051-0d7c-4656-19a846908469
* Version Independent ID: 3478e881-199c-f0c4-b218-0dd609eb0427
* Content: [Ports used for connections - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/ports)
* Content Source: [sccm/core/plan-design/hierarchy/ports.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/ports.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @rdr222 for the feedback. Yes, those should be listed but are not.

**Comment by aczechowski** [comment]
I just made a change for this issue. It should publish live later this afternoon.
