### ISSUE TITLE
Hybrid Intune

### ISSUE THREAD

**Issue by LeThijs** [MicrosoftDocs/SCCMdocs#1197]
Would it be possible to provide a note that Hybrid setup with Intune is EOL?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6f96bb1-5fb9-6086-335f-e5069313d9cf
* Version Independent ID: 4b3a73cd-07e6-9999-abae-26168f0dfa1e
* Content: [Choose a device management solution  - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/choose-a-device-management-solution)
* Content Source: [sccm/core/plan-design/choose-a-device-management-solution.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/choose-a-device-management-solution.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @LeThijs for the suggestion. I just submitted a change to this article, which should publish tomorrow. I'm closing this issue.
