### ISSUE TITLE
Upload Offline Feedback issue

### ISSUE THREAD

**Issue by gary-cassidy** [MicrosoftDocs/SCCMdocs#1199]
I have attempted to use the upload offline feedback feature whilst behind a proxy server and I am unable to send the feedback. The command doesn't appear to support a proxy server as the help doesn't mention any proxy specific commands. I require this as an issue I have originates in an 1810 environment without internet connection and the internet connected environment uses a proxy server. I cannot submit feedback currently unless I do this from home etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a504ecc8-34dd-2827-660a-0e5303e88e49
* Version Independent ID: 79ba1a30-59d4-2fd0-f73d-4c1e9fcada74
* Content: [Technical Preview 1805 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/capabilities-in-technical-preview-1805)
* Content Source: [sccm/core/get-started/capabilities-in-technical-preview-1805.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/capabilities-in-technical-preview-1805.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @gary-cassidy for the feedback. Definitely a good point to call out in the docs. I'll share the feedback with the feature team as well.

**Comment by aczechowski** [comment]
This was fixed in the tool in [version 1910](https://support.microsoft.com/help/4535776/summary-of-changes-in-microsoft-endpoint-configuration-manager-current) (search for "proxy"). We just need to pull those new parameters into the doc for the tool: https://docs.microsoft.com/mem/configmgr/core/understand/find-help#BKMK_NoInternet
