### ISSUE TITLE
Azure SQL Database Managed Instance

### ISSUE THREAD

**Issue by Btreyo** [MicrosoftDocs/SCCMdocs#1200]
Are Azure SQL Database Managed Instance's supported with ConfigMgr - as the application is compatible with SQL Always On, just wondering whether there is support for SQL Managed Instances?

**Comment by aczechowski** [comment]
Hi @Btreyo. From [Configuration Manager on Azure FAQ](https://docs.microsoft.com/sccm/core/understand/configuration-manager-on-azure#how-can-i-make-my-database-highly-available-can-i-use-azure-sql-database-or-do-i-have-to-use-microsoft-sql-server-in-a-vm):

> **How can I make my database highly available? Can I use Azure SQL Database? Or do I have to use Microsoft SQL Server in a VM?**
> You need to use Microsoft SQL Server in a VM. Configuration Manager does not support Azure SQL Server at this time. But you can use functionalities like [AlwaysOn Availability Groups](https://docs.microsoft.com/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database) for your SQL server. AlwaysOn Availability Groups are recommended and are officially supported starting with version 1602 of Configuration Manager.

I'm closing this issue
