### ISSUE TITLE
Additional requirements from CMG installation

### ISSUE THREAD

**Issue by djanny22** [MicrosoftDocs/SCCMdocs#1201]
SCCM Console must be run as administrator, or you can experience "Password is not correct" error when adding certificate.
Resource providers that need to be enabled on Subscription, some of which are not there by default and are not enabled automatically:
o	Microsoft.Storage
o	Microsoft.ClassicCompute
o	Microsoft.ClassicNetwork
o	Microsoft.ClassicStorage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778368d0-1054-678c-4d74-5dce1b5826c8
* Version Independent ID: aaac7308-66e6-66f0-8248-14e1505c11a6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/plan-cloud-management-gateway)
* Content Source: [sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @djanny22 for the feedback. In talking with the engineering team, only the following resources should be required for CMG/CDP as an Azure Resource Manager deployment:

- Microsoft.Storage
- Microsoft.ClassicCompute

Also reference the following [post on Twitter](https://twitter.com/StevybSC/status/1089882229940125697)

**Comment by torontojc** [comment]
@djanny22 @aczechowski  The Microsoft.ClassicCompute is mentioned in [Set up Cloud Management Gateway](https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/setup-cloud-management-gateway.md) I've created a pull request to also add Microsoft.Storage to that document.

**Comment by Brenduns** [comment]
@torontojc; @djanny22   Closing some loose ends, as I see the PR that updates the 'Set up cloud management gateway for Configuration Manager article went live some time back. Our thanks for the original question and PR that helped update the related content.
