### ISSUE TITLE
Could you document use of Nested Groups with Maintenance Windows?

### ISSUE THREAD

**Issue by philc52** [MicrosoftDocs/SCCMdocs#1206]
I have been trying to nest 2 collections, with Different maintenance windows under a collection which has 2 maintenance windows. This is for patching, with the intention that:
1. I only need to deploy patches to the top level collection;
2. I therefore reduce the number of deployments needed each month for patching.
However, this doesn't seem to work as patches wait until the deadline before they install.
Reading the above, I suspect that this is not how maintenance windows work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a69524-75f1-5c55-5091-66b7c3326a7b
* Version Independent ID: 48b982d2-1ee9-7d2a-a1f9-14cdf0dadb6a
* Content: [Use maintenance windows - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/collections/use-maintenance-windows)
* Content Source: [sccm/core/clients/manage/collections/use-maintenance-windows.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/collections/use-maintenance-windows.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by jocasti** [comment]
@philc52 AFAIK, the option of having deployments target the top-level collection and include the sub collections is no longer available. There are now include and exclude query membership rules that you can use to add all your target systems into one collection to reduce the number of deployments.

**Comment by philc52** [comment]
Thanks for your reply.
As I work in the server space, this is a bit of a nuisance. We have lots of
servers which need to be patched at different times. It seemed an obvious
use of a collection including other collections.

Cheers,
Phil Crawford
+61 423 824 185 (Australia)

**Comment by aczechowski** [comment]
Thanks @philc52 for the feedback. I need to investigate this with engineering

**Comment by mathieudesjardins** [comment]
Same here, the idea of nesting collection for a single deployment of patches on a server was a good idea but with different maintenance window for Dev, QA and Prod is having the behavior that in the end, all servers will have several maintenance window and will be harder to manage restart.

**Comment by philc52** [comment]
Hi Mathieu,
Having researched a bit more, I think that it is possible, but only have
Maintenance Windows in the lower groups, not in the top collection.
I will test with next month's patches.

Cheers,
Phil Crawford
+61423824189

**Comment by mathieudesjardins** [comment]
For now I removed the inclusion of all other collection and I will deploy the same update group 5 time, one on each collection.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by philc52** [comment]
That's what I have done for this month's patches.
I will experiment with Test domain next cycle.


Cheers,
Phil Crawford
+61423824189

**Comment by torontojc** [comment]
@philc52 
You can have Collection A with a software update group deployment to. (assuming the deployment is NOT overriding maintenance windows)
Then add an include rule to Collection B & C. Both of those collections with different maintenance windows.
Once the deadline hits the software updates will be installed in the next available maintenance window.

What I hear you saying is that you have a machine that is in a maintenance window, with updates deployed but not past the deadline and you expect it to be installed.  This is controlled by client settings and not maintenance windows: https://docs.microsoft.com/en-us/sccm/core/clients/deploy/about-client-settings#period-of-time-for-which-all-pending-deployments-with-deadline-in-this-time-will-also-be-installed

IE if this setting is configured to 5 days, and there's a pending software update that's has deadline of 6 days away and the system goes into maintenance mode it will not install. But if a system enters maintenance mode and it's within 5 days of the deadline it will install it ahead of the deadline.

**Comment by philc52** [comment]
Thanks a lot for this clarification.


Cheers,
Phil Crawford
+61423824189

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
