### ISSUE TITLE
Additional Hotfix KB4487960

### ISSUE THREAD

**Issue by paulwetter** [MicrosoftDocs/SCCMdocs#1207]
Hotfix KB4487960 Released on 1/17/2019.
https://support.microsoft.com/en-us/help/4487960/intune-connector-certificate-does-not-renew-in-configuration-manager

Fixes Intune connector certificate renewal process fails.  For Windows Server 2012 and 2012R2 with InTune Hybrid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22765ffe-cef8-a88f-5f71-00caf9b47046
* Version Independent ID: cb5ad492-39d1-f63d-0bd2-7f3a0b1d8af0
* Content: [What's new in version 1806 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/whats-new-in-version-1806)
* Content Source: [sccm/core/plan-design/changes/whats-new-in-version-1806.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/changes/whats-new-in-version-1806.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @paulwetter for the feedback. @bhuney submitted a change for this, which should publish later today. I'm closing this issue.
