### ISSUE TITLE
Connection Point metrics

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/SCCMdocs#1208]
When viewing a connection point, the console shows "Total requests in last 30 days" and "Max concurrent requests in last 30 days" in the Connection Points view - what does this identify - what client actions are included in a request?  If a client is online for 8 hours, would it just be one request every 60 minutes due to policy retrieval and 1 if it does a software update scan?  If it downloads content from a DP would that be one additional request or could it potentially be many more?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a21a4b1e-ade5-1955-d464-b538939b1419
* Version Independent ID: e5485051-d7c6-d2f0-5c44-5dde4570f82c
* Content: [Monitor cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/monitor-clients-cloud-management-gateway)
* Content Source: [sccm/core/clients/manage/cmg/monitor-clients-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/monitor-clients-cloud-management-gateway.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
This issue is closed because I made a change to the article with some additional information from the feature team. The updated article should publish live tomorrow (Wednesday) around 11am Pacific time.
