### ISSUE TITLE
Windows 10 version prerequsite

### ISSUE THREAD

**Issue by chiners68** [MicrosoftDocs/SCCMdocs#1211]
Does the prerequsite section need updating.

Windows 10 Insider Preview version 17758 or later

should this not be replaced with 
Windows 10 version 1809 (17763) or later???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e127b958-368c-fde6-0228-c18168bf496e
* Version Independent ID: 82abfe81-e404-3d60-3d11-ca28ad399eb2
* Content: [Task sequence support of Windows Autopilot for existing devices](https://docs.microsoft.com/en-us/sccm/core/get-started/includes/1810/1358333#bkmk_autopilot-image)
* Content Source: [sccm/core/get-started/includes/1810/1358333.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/includes/1810/1358333.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @chiners68 for the feedback. Technically, yes. But I generally don't revise technical preview articles, I see them more as point-in-time content. Once this content is moved over to the core docs, then it will reflect the current prerequisites. 
I'm closing this issue, as I don't plan any changes to this article.
