### ISSUE TITLE
Does power management plan applied by ConfigMgr affect computer performance?

### ISSUE THREAD

**Issue by ahcash** [MicrosoftDocs/SCCMdocs#1214]
It's not been mentioned anywhere in the document but I would like to find out.
Does applying power plan from SCCM affect the CPU / GPU performance especially on a laptop?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50e4ee97-90b8-7ffb-7aa0-c6b81f18e6e2
* Version Independent ID: 02cc3bf5-e48d-8e08-6fff-60e6dd24ba26
* Content: [Introduction to power management - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/power/introduction-to-power-management)
* Content Source: [sccm/core/clients/manage/power/introduction-to-power-management.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/power/introduction-to-power-management.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
It will depend upon the settings of the power plan. It's like any [Windows power plan](https://docs.microsoft.com/windows-hardware/manufacture/desktop/create-a-custom-power-plan-technicalreference), but the SCCM power plans don't have as many properties. Looking at the list in SCCM, there aren't any settings for CPU throttling or other performance-related aspects. The only possible property to impact performance is **Turn off hard disk after (minutes)**. All of the others relate to power state and power-related actions. Also note that these settings aren't applied by default; you have to turn on power management in SCCM and then configure a power plan on a collection. 

I'm closing this issue
