### ISSUE TITLE
URL's + article consolidation

### ISSUE THREAD

**Issue by faulknerp** [MicrosoftDocs/SCCMdocs#1216]
Would be useful to publish the URL's required to be allowed through proxy to get this to work. We've been battling for 3 months to get this to work as proxy issues, and took a while to identify the URL's required (even premier support couldn't tell us). Also we found there were many different articles about this that seem to contradict each other, it took a lot of reading and testing to find out which articles were correct.

(6/19 admin edit: moving feedback to new article [which publishes live on 6/20])

Add a note here:
* Content: [Upgrade Readiness - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/upgrade-readiness)
* Content Source: [sccm/core/clients/manage/upgrade-readiness.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/upgrade-readiness.md)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c5e66c1-d90f-2a99-cd61-a5a4c7560c65
* Version Independent ID: e48e6c28-53b9-79bd-64ba-f30e7728fb1b
* Content: [Internet access requirements - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/network/internet-endpoints)
* Content Source: [sccm/core/plan-design/network/internet-endpoints.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/network/internet-endpoints.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @faulknerp for the feedback. This information is something we need to include for all connected services.

**Comment by Yevrag35** [comment]
Built the web app in the Azure portal, went to import it into the SCCM console, and when I click "Verify" I get an error that says "App already exists."  Isn't that what the SCCM wizard is expecting; it to already exist?

**Comment by kennethvs** [comment]
Having similar issues, for example officecdn.microsoft.com.edgesuite.net is not listed as "to-be" allowed URL's.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions. For this specific item, we already consolidated all of the endpoints for ConfigMgr features into a single article. Upgrade Readiness is now end of life.

If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
