### ISSUE TITLE
All Software Updates Node

### ISSUE THREAD

**Issue by gepettoTPM** [MicrosoftDocs/SCCMdocs#1217]
The note on this page indicates: "On the All Software Updates node, by default, Configuration Manager displays only software updates with a Critical and Security classification and that were released in the last 30 days." Is this configurable? My console appears to be displaying the first 1000 results from my entire catalog. I'd like to revert back to the default or configure a more limited default search scope, but I can't figure out if that's possible or how to do it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc0e842-f963-81af-750b-d6dd432584bc
* Version Independent ID: afab2474-c668-351c-b804-1a5bd4df19c6
* Content: [Add updates to an update group  - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/add-software-updates-to-an-update-group)
* Content Source: [sccm/sum/deploy-use/add-software-updates-to-an-update-group.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/add-software-updates-to-an-update-group.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
That note is incorrect. We show everything except updates in the Upgrades classification and updates in the Office 365 Client product classification. In that view you can **Add Criteria** to include **Update Classification** among other properties.

**Comment by aczechowski** [comment]
Thanks to @jocasti for submitting an edit for this issue. The revision should publish tomorrow (Wednesday, 20 March).

**Comment by gepettoTPM** [comment]
Thank you for your help!

Greg
