### ISSUE TITLE
ConfigMgr 2012 R2 SP1 version of this page

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/SCCMdocs#1219]
Is there still a 2012 R2 SP1 version of this page?  Not finding it after much searching.  I do see that 1507 and 1511 are supported on the "Deploy windows 10" walkthrough docs page, but I'm thinking they should be here as well since 2012 R2 SP1 is supported until 2022.  For anyone riding out 2012 R2 support until the end, I think it should be mentioned that only up to Win10 1511 is supported as a client on CM 2012 R2 SP1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86d400f-d2a6-d50b-8d1f-18893af56d67
* Version Independent ID: 793a7196-8549-329c-bad5-c6b33f466ae7
* Content: [Supported clients and devices - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/supported-operating-systems-for-clients-and-devices)
* Content Source: [sccm/core/plan-design/configs/supported-operating-systems-for-clients-and-devices.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/supported-operating-systems-for-clients-and-devices.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
The docs.microsoft.com/sccm content is specific to current branch and technical preview branch, as should be noted at the top of every article under the title. 

The historical content is available in the previous versions docset. The old version of this article is here: https://docs.microsoft.com/en-us/previous-versions/system-center/system-center-2012-R2/gg682077(v%3dtechnet.10)
