### ISSUE TITLE
Is SQL 2012 SP3 still supported with CB 1810 ?

### ISSUE THREAD

**Issue by jemmail** [MicrosoftDocs/SCCMdocs#1221]
Can you confirm SQL 2012 SP3 is still supported in CB 1810. In the following document
https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/whats-new-in-version-1810

there is a mention of minimal version of SQL 2012 SP4, but maybe only for native client and support of TLS 1.2. Right ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb55272-b9ee-0407-d034-f6fc37c979a3
* Version Independent ID: 9745517a-b005-84a8-d45a-fe02a636134f
* Content: [Supported SQL Server versions - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/support-for-sql-server-versions)
* Content Source: [sccm/core/plan-design/configs/support-for-sql-server-versions.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/support-for-sql-server-versions.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Correct, the 1810 new requirement is just for the [SQL native client](https://docs.microsoft.com/sccm/core/servers/deploy/install/list-of-prerequisite-checks#sql-native-client) to support TLS 1.2. 

This article is still accurate for 1810. SQL 2012 SP3 is still supported for the site database.
