### ISSUE TITLE
Configure and support Test environments

### ISSUE THREAD

**Issue by ugeeku** [MicrosoftDocs/SCCMdocs#1225]
Added documentation is needed for test environments and other possible scenarios.  Larger companies will want to transition from their familiar non-prod environment isolated processes to a possible new way of thinking and anyway to present a better way of understanding a many to one environment would be beneficial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778368d0-1054-678c-4d74-5dce1b5826c8
* Version Independent ID: aaac7308-66e6-66f0-8248-14e1505c11a6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/plan-cloud-management-gateway#hierarchy-design)
* Content Source: [sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ugeeku for the feedback. 😃 I agree it would be a good addition to the design information in this article.

**Comment by ugeeku** [comment]
Looking forward to it - Thanks!
