### ISSUE TITLE
"server on which an automatic deployment rule was created" needs clarification

### ISSUE THREAD

**Issue by davidpaMSFT** [MicrosoftDocs/SCCMdocs#1226]
Automatic Deployment Rules are typically created by Administrators using a console or PowerShell. Therefore, it is not clear what server is "server on which an automatic deployment rule was created" referring to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 926d0167-454c-f8c0-177d-0b1de31b8a77
* Version Independent ID: e1a16df1-da95-3783-c683-cd80fe43bf6d
* Content: [Proxy server support - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/network/proxy-server-support)
* Content Source: [sccm/core/plan-design/network/proxy-server-support.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/network/proxy-server-support.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I confirmed with engineering team, I'm not sure why that's worded that way. It should just be the site server.
