### ISSUE TITLE
ADK support statement is misleading

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#1229]
> Microsoft recommends using the Windows ADK that matches the version of Windows you're deploying. For example, use the Windows ADK for Windows 10 version 1703 when deploying Windows 10 version 1703.

The first sentence works in a new version scenario, but not a previous version scenario. The second sentence makes it worse. A customer who is still deploying v1703 might think they can only use the 1703 ADK, which isn't supported by Configuration Manager current branch. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc732ec0-eb14-8da2-7688-dd74a72cdae5
* Version Independent ID: a93682ff-2984-38e0-5a0d-6f77c1c9e5db
* Content: [Support for Windows 10 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/support-for-windows-10#windows-10-adk)
* Content Source: [sccm/core/plan-design/configs/support-for-windows-10.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/support-for-windows-10.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by codaamok** [comment]
Great comment. What about a customer who is deploying 2016 LTSC with 1810 and 1809 ADK?

**Comment by aczechowski** [comment]
Closing this issue as the text will be reworded with the 1902 update content.
