### ISSUE TITLE
MBR2GPT Error in Windows 10 v1809 

### ISSUE THREAD

**Issue by radhabshrestha** [MicrosoftDocs/SCCMdocs#1235]
I have Windows10 Version 1809 Legacy BIOS mode. I want to change to UEFI and I downloaded ADK and PE for version 1809 and created Bootable WINPE. Since I had more than 4 partitions and I had to delete all partitions including System Reserved Healthy (Primary Partition). Then only I could extend volume to C drive. When I run WINPE and run MBR2GPT /Convert I get error "Cannot find OS Partition(s) for disk 0". I even used reagentc /enable from my Laptop (the Dell Vostro 5468), I am getting "The Windows RE image was not found". I have only One C drive. How will I can change from Legacy BIOS mode to UEFI for my laptop?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8eaf0aab-4d02-82dd-007f-8457e648984d
* Version Independent ID: 4ea5614c-5e4d-537d-4b98-5ddead504359
* Content: [Task sequence steps to manage BIOS to UEFI conversion - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/task-sequence-steps-to-manage-bios-to-uefi-conversion#convert-from-bios-to-uefi-during-an-in-place-upgrade)
* Content Source: [sccm/osd/deploy-use/task-sequence-steps-to-manage-bios-to-uefi-conversion.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/task-sequence-steps-to-manage-bios-to-uefi-conversion.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @radhabshrestha for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
