### ISSUE TITLE
EM+S  dual CAL equivalent for SCCM

### ISSUE THREAD

**Issue by RobertHemsley** [MicrosoftDocs/SCCMdocs#1236]
So I understand that EM+S has dual CAL equivalent rights for SCCM.
However, where can the software media for SCCM be downloaded once you assign users with EM+S?
This is for a CSP customer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 295caa58-e5d5-4b95-9287-62af7e118241
* Version Independent ID: 77e831e1-ff78-2b4e-2d90-341bb4c3b3a4
* Content: [Get installation media - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/get-install-media)
* Content Source: [sccm/core/servers/deploy/install/get-install-media.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/get-install-media.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @RobertHemsley for the comment. See the following FAQ: https://docs.microsoft.com/sccm/core/understand/product-and-licensing-faq#bkmk_csp

Also reference the following issue for additional information: https://github.com/MicrosoftDocs/SCCMdocs/issues/493
