### ISSUE TITLE
Add "http://go.microsoft.com" as a URL to the below statement. Other documents reference this. Thanks!

### ISSUE THREAD

**Issue by garrettmsft** [MicrosoftDocs/SCCMdocs#1240]
Another common download issue occurs when proxy server settings prevent downloads from http://silverlight.dlservice.microsoft.com and http://download.microsoft.com.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b51948e-fdf8-3a75-2a81-27ff452a6f9d
* Version Independent ID: 924773d6-e3d4-5452-6bc2-3640e96b9099
* Content: [Checklist for 1810 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/checklist-for-installing-update-1810#feedback)
* Content Source: [sccm/core/servers/manage/checklist-for-installing-update-1810.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/checklist-for-installing-update-1810.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @garrettmsft for the suggestion. If you're interested/willing to make this edit yourself, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute).

**Comment by aczechowski** [comment]
Closing this issue, fixed by #1243
