### ISSUE TITLE
Granting access to SQL for Management point connection account 

### ISSUE THREAD

**Issue by Yupiter2005** [MicrosoftDocs/SCCMdocs#1246]
Management point connection account must be added to SQL manually with smsdbrole_MP scheme. 
For some reason, it's not handled by site server at least when modifying already installed MP properties

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f80cf3-6f36-cb44-d0e5-d186164d6281
* Version Independent ID: ada8a281-7d9f-e82e-e4e8-056b93e8b36d
* Content: [Accounts used - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/accounts#management-point-connection-account)
* Content Source: [sccm/core/plan-design/hierarchy/accounts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/accounts.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Yupiter2005 for the feedback. I'm checking with the engineering team. I wonder if this is a doc bug or a possible product bug.

**Comment by aczechowski** [comment]
I haven't been able to find anyone to definitely respond to this. It doesn't seem like proper behavior, so if you haven't already, please file a frown in the console, or open a support case.
