### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by bdowner2** [MicrosoftDocs/SCCMdocs#1249]
I search "sccm create static computer collection", knowing that a device collection is a list of computers that is dynamically generated but I want to make a static list that does not automatically change.
Result: Microsoft.com -&gt; "How to Create a Static Collection"   &lt;- Promising
blah blah blah VBScript or C# code it yourself. ........what?!
SCCM is painful enough with absolutely no logic in how it is designed or functions.  Why does the Documentation have to suck even worse then the product!? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19ae23b9-9a79-ce32-522b-e59697716bb3
* Version Independent ID: 83637444-e3ce-6c02-3617-d22842fb95b6
* Content: [Create a Static Collection - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/core/clients/collections/how-to-create-a-static-collection)
* Content Source: [sccm/develop/core/clients/collections/how-to-create-a-static-collection.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/core/clients/collections/how-to-create-a-static-collection.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
The [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/), which outlines the expectations for community interactions in and around docs.microsoft.com, is designed to help "provide a welcoming and inspiring community for all." The content of this issue appears to be out of sync with the code of conduct. Thank you for closing it.
