### ISSUE TITLE
WSUS servers for secondary sites, don't run WSUS cleanup for expired updates.

### ISSUE THREAD

**Issue by ddubs1** [MicrosoftDocs/SCCMdocs#1250]
I believe support was added in 1810 for cleanup on secondary sites

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38bacc7a-d602-e825-bff3-5d9232f03f72
* Version Independent ID: 7de8c181-3252-de71-bdfe-70b68dd966c5
* Content: [Software updates maintenance - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/software-updates-maintenance)
* Content Source: [sccm/sum/deploy-use/software-updates-maintenance.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/software-updates-maintenance.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by Zebbelin** [comment]
Yes looks like this works now for secondary sites as well

**Comment by aczechowski** [comment]
Yes, that's correct. Just haven't added to core docs yet.

**Comment by aczechowski** [comment]
Closing this issue. @mestew submitted a change to add this info. It will publish live tomorrow (Wednesday, 20 February) around 11am Pacific time.
