### ISSUE TITLE
Win32 Apps (Intune) and Co-Managed devices

### ISSUE THREAD

**Issue by MariusWeiss** [MicrosoftDocs/SCCMdocs#1256]
It's written that every deployed app from Intune will be available, this is actually not working. MSI and Win32 Apps are not available if co-managment is enabled on the devices

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70ebc3e6-359e-3067-3cfd-149052df1123
* Version Independent ID: 723165f6-6bfa-ed78-fbda-23c12bc07b9d
* Content: [Co-management workloads - Configuration Manager](https://docs.microsoft.com/en-us/sccm/comanage/workloads#client-apps)
* Content Source: [sccm/comanage/workloads.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/workloads.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
