### ISSUE TITLE
Use Cases & Benefits

### ISSUE THREAD

**Issue by NeighborGeek** [MicrosoftDocs/SCCMdocs#1259]
I only see one sentence in the current article which even hints at when and why I might want to use this - "Azure AD replaces the need to configure and use client authentication certificates."  
Please consider adding more info on what use cases this best serves, and what the benefits of using AzureAD auth are over existing methods.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acbd8029-6391-7ae1-a098-9c348be1dd98
* Version Independent ID: e202fe2f-876c-44a5-5e03-d769ef31f72c
* Content: [Install the client with Azure AD - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/deploy/deploy-clients-cmg-azure)
* Content Source: [sccm/core/clients/deploy/deploy-clients-cmg-azure.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/deploy-clients-cmg-azure.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @NeighborGeek for the feedback. It probably just needs a link over to the Azure AD section of this article: https://docs.microsoft.com/sccm/core/plan-design/security/plan-for-security#bkmk_planazuread, which provides this information.

**Comment by NeighborGeek** [comment]
Unless I'm missing something, that link talks about what SCCM features use
AzureAD integration, which I don't think is quite what I was looking for.
I wanted to know, when would I need to configure an SCCM client
specifically to use AzureAD authentication, as opposed to certificate
auth?

When I enable co-management for example, it works for all of my existing
SCCM clients, I don't have to switch them over to AzureAD auth.  Unless
that's being done automatically behind the scenes?

**Comment by aczechowski** [comment]
Setting up Azure AD may be easier for some customers than setting up PKI. If you're already using certificate authentication, then there are not many client-side benefits. There are features that require you onboard the site to Azure AD, but don't necessarily require the clients to be Azure AD-joined. I'm working on this article right now, so I'll add some language around this topic, and then close this issue. Thanks for the feedback!

**Comment by aczechowski** [comment]
The changes should publish live tomorrow (Wednesday, 6 March) around 11am Pacific time.
