### ISSUE TITLE
Script Monitoring

### ISSUE THREAD

**Issue by sympleconfigmgr** [MicrosoftDocs/SCCMdocs#1260]
Script Monitoring should include a section that outlines how long script data is retained in the database and visible in the console.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c7d1db7-6812-ff3c-9aac-0f55800ed665
* Version Independent ID: a4499cf7-ed5a-710c-66e0-005563b9c015
* Content: [Create and run scripts - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/create-deploy-scripts#script-monitoring)
* Content Source: [sccm/apps/deploy-use/create-deploy-scripts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/create-deploy-scripts.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @sympleconfigmgr for the suggestion. We have some work planned on this article in the near future, so will try to include this information at that time.

**Comment by mestew** [comment]
Information about how long we retain the data has been added under the [Script Monitoring section](https://docs.microsoft.com/sccm/apps/deploy-use/create-deploy-scripts#script-monitoring). The changes should be published in the next day or so.  We keep the data until either the script is deleted or until the Delete Aged Client Operations maintenance task is run. 
#please-close
