### ISSUE TITLE
Incremental updates limit in the hierarchy

### ISSUE THREAD

**Issue by arwidmark** [MicrosoftDocs/SCCMdocs#1267]
I thought the "The threshold is about 200 collections in your hierarchy" limit/recommendation was removed a while back? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbccb59f-9513-3990-28b3-822f5cd44c69
* Version Independent ID: 89404c66-cedd-c696-a98a-c4ac8d062eb6
* Content: [Collections best practices - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/collections/best-practices-for-collections)
* Content Source: [sccm/core/clients/manage/collections/best-practices-for-collections.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/collections/best-practices-for-collections.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aftermonths** [comment]
Is there any chance that this question could be answered please?  It would be really good to have this confirmed, as there is so little information on this topic. I appreciate your time.

**Comment by aczechowski** [comment]
I'm actually going to close this issue. I checked with the engineering team, this guidance is still valid. There's no calculated limit, "200" is a general guide. We've seen customers have delays with 20 really complex collections, or not until almost 4000 collections. It’s as much a function of “number of changes” as it is number of collections. The more change a rule result set experiences, the higher the load on incremental eval. Many factors affect collection evaluation and those factors change instantly.
