### ISSUE TITLE
Does this document need updating?

### ISSUE THREAD

**Issue by santoshseth** [MicrosoftDocs/SCCMdocs#1268]
SCCM and Azure are fast changing products, This is a Two years old document, should it not be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0da69878-a841-1f05-32c2-a1fcba10506f
* Version Independent ID: 769913cc-0fa4-cd5b-b015-b7c5f38fc0d4
* Content: [Configuration Manager on Azure](https://docs.microsoft.com/en-us/sccm/core/understand/configuration-manager-on-azure)
* Content Source: [sccm/core/understand/configuration-manager-on-azure.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/configuration-manager-on-azure.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @santoshseth for the feedback. Is there anything specific that you think is outdated or missing?

**Comment by santoshseth** [comment]
It will be great if document has the details of 

1. Can Azure File storage be used for hosting Remote content library and Package source directory?
2. Possibility (along with prerequisites and limitations) of doing OSD via Azure hosted SCCM?

**Comment by santoshseth** [comment]
Any update on these please?

**Comment by krishnasharma399** [comment]
> Any update on these please?

I also need info on the queries Santosh posted, please. My main concern is WDS supportability on Azure VMs.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback. I'm going to track this review with an internal work item (7209017).
