### ISSUE TITLE
SQL Server Always On is not supported.

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/SCCMdocs#1274]
@tahakogi commented on [Tue Feb 26 2019](https://github.com/MicrosoftDocs/SCCMDocs.ja-jp/issues/27)

SQL Server Always On need SQL Server Enterprise License.

https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database#limitations-and-known-issues

Unsupported SQL Server options and configurations
Basic availability groups: Introduced with SQL Server 2016 Standard edition, basic availability groups don't support read access to secondary replicas. Configuration requires this access. For more information, see Basic SQL Server availability groups.

SQL License with SCCM is SQL Server Standard License.
SQL Server Standard License can use basic availability groups.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: c3b9a7fa-9585-a2fb-590e-0b74e128035d
* Version Independent ID: 9aae8e97-de68-c274-b4c6-cd925568c75b
* Content: [製品とライセンスに関する FAQ - Configuration Manager](https://docs.microsoft.com/ja-jp/sccm/core/understand/product-and-licensing-faq#bkmk_sql)
* Content Source: [sccm/core/understand/product-and-licensing-faq.md](https://github.com/Microsoft/SCCMDocs.ja-jp/blob/live/sccm/core/understand/product-and-licensing-faq.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by CeciAc** [comment]
Hi team,
I'm moving this here since the contributor's suggestion is on the original documentation
best

**Comment by aczechowski** [comment]
Thanks @tahakogi for the feedback. SQL Server Always On is supported, but you're correct it does require an enterprise SQL license. That's an aspect of the product and licensing FAQ that we haven't yet clarified, but it is good to explicitly note.

**Comment by gary-cassidy** [comment]
I am in the middle of a SCCM design project and would like to have some clarity on this issue. Existing AO instances are not readable, so to work around that I would like to use a separate SQL AO setup just for SCCM. 

So, can we use SQL Enterprise with SCCM using Always On without any additional licensing beyond SCCM licensing?

**Comment by aczechowski** [comment]
@gary-cassidy see my [recent comment on the main issue](https://github.com/MicrosoftDocs/SCCMdocs/issues/464#issuecomment-470239203). It's not a definitive answer yet, but provides the text from the product terms.

**Comment by santoshseth** [comment]
So, Is Enterprise license free to use with SCCM or not because its not clear?

**Comment by SteffenBaro** [comment]
Any update on this ?
We plan to use a sql always on cluster for the two scom databases.
For a full always on cluster, sql enterprise is required.

**Comment by aczechowski** [comment]
I submitted a change. This issue will auto close when that change merges. It will go live with the next daily publishing, today (Wednesday) about 11am Pacific.

The change is removing "SQL Server Always On" from the list.

If you have any further questions, please talk with your Microsoft account manager on your organization's licensing, and review the official [product terms](https://www.microsoftvolumelicensing.com/DocumentSearch.aspx?Mode=3&DocumentTypeId=53).
