### ISSUE TITLE
The behavior of "cleanup for software update configuration items in the Configuration Manager database" needs to be confirmed.

### ISSUE THREAD

**Issue by davidpaMSFT** [MicrosoftDocs/SCCMdocs#1278]
This "This cleanup won't remove expired updates from the Configuration Manager console if they're currently deployed" appears to be incorrect, i.e. observed behavior is that expired updates are removed even if they are deployed. Their individual deployments are removed as well. The Software Update Group deployments also seem to be removed, at least in a scenario where they contain a single expired update. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38bacc7a-d602-e825-bff3-5d9232f03f72
* Version Independent ID: 7de8c181-3252-de71-bdfe-70b68dd966c5
* Content: [Software updates maintenance - Configuration Manager](https://docs.microsoft.com/en-ca/sccm/sum/deploy-use/software-updates-maintenance)
* Content Source: [sccm/sum/deploy-use/software-updates-maintenance.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/software-updates-maintenance.md)
* Product: **configuration-manager**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@davidpaMSFT
Hey David,
1. What version are you seeing the behavior in? 
   - I haven't dug super deep into the Configuration Manager SUM CI cleanup in a while but historically speaking, we have always excluded deployed update CIs  from being removed. 
2. If you don't already have one, get a case on on the unexpected behavior.
3. If you have a wsyncmgr.log showing a specific updateID (or more) being expired, **email** me:
      - A share location I can read the log from
      -  The updateIDs that were removed unexpectedly 
      - The case number so I can track it and keep in touch with the owner

Thanks, 
Meghan

**Comment by ohorvath** [comment]
I see the same behaviour in 1810 build 8740. All of the expired cumulative updates for Windows 10 and Server 2006 has been removed from the deployed software update groups. However I still can see them listed under all software updates as expired and not deployed.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback. Meghan is tracking this internally.
