### ISSUE TITLE
Co-Management

### ISSUE THREAD

**Issue by ITOpsReborn** [MicrosoftDocs/SCCMdocs#1280]
Can you expand into CAS supported client numbers when co-management is enabled?  https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/size-and-scale-numbers#bkmk_cas

How does this affect client numbers? Are co-managed devices considered "cloud devices"? I quote: "For example, in a hierarchy you can support 700,000 desktops, up to 25,000 Mac and Windows CE 7.0 devices, and up to 300,000 cloud-based devices when you integrate Microsoft Intune"  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c595a86-976c-dc2c-5b01-fb9d6b761f17
* Version Independent ID: a90f5193-559b-07b0-519a-d5ef32de3151
* Content: [Size and scale - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/size-and-scale-numbers#bkmk_cas)
* Content Source: [sccm/core/plan-design/configs/size-and-scale-numbers.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/size-and-scale-numbers.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ITOpsReborn for the feedback. Co-management doesn't change the scale limits. The phrase "cloud-based devices when you integrate Microsoft Intune" refers to mobile devices in a hybrid MDM configuration. (NOTE: hybrid is now deprecated.) Co-managed clients are still normal Configuration Manager clients. If they are also internet-based, then if anything the scale of the cloud management gateway is probably the limiting factor before the site limit.

**Comment by ChrisKibble** [comment]
@aczechowski - should the cloud-based devices line be removed entirely, along with the other four references in the same article?

**Comment by aczechowski** [comment]
@ChrisKibble, yeah thanks. With hybrid EOL, those values are irrelevant now.

**Comment by ChrisKibble** [comment]
PR submitted.

**Comment by aczechowski** [comment]
Closing this issue. I have changes in for broader hybrid deprecation, which includes updates here. It won't publish for a few days, but this specific work is done
