### ISSUE TITLE
Storage spaces for DB files

### ISSUE THREAD

**Issue by rdoloto** [MicrosoftDocs/SCCMdocs#1281]
This would be great to include or explicitly  define if storage spaces or NVME configuration for primary sites.  This  is still is based on old RAID configurations from my understanding 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e67ddd45-90df-32cd-3cbe-9e1443b2540f
* Version Independent ID: dee7fcb8-a7b7-e5a1-9c04-c113805be0da
* Content: [Recommended hardware - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/recommended-hardware)
* Content Source: [sccm/core/plan-design/configs/recommended-hardware.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/recommended-hardware.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @rdoloto for the feedback. You can find more information on the topic in the [perf and scale whitepaper](https://gallery.technet.microsoft.com/Configuration-Manager-ba55428e). In the future I hope to incorporate that content directly into the core docs, but leverage that resource for now.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. I am tracking the work on the perf/scale whitepaper in an internal item, so I'll link to this for future reference. But am going to close this issue.
