### ISSUE TITLE
Add log called smsdpusage.log and details

### ISSUE THREAD

**Issue by DavidHBaur** [MicrosoftDocs/SCCMdocs#1282]
Add log called smsdpusage.log and details

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 972d8899-c8a4-28c5-fabe-5ab294bac22d
* Version Independent ID: 7f772e7a-836c-a18d-df8d-c3d115cb3d9f
* Content: [Log files for troubleshooting - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/log-files#BKMK_SiteSiteServerLog)
* Content Source: [sccm/core/plan-design/hierarchy/log-files.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/log-files.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @DavidHBaur for the feedback. Not sure why that's not already in the list, it's been in the product since 2012 SP2. 😮 

It logs the smsdpusage exe that runs and gathers data for the dp usage report.

It resides on every DP in the DP logs folder

**Comment by aczechowski** [comment]
Thanks to @jocasti for contributing a change to add this information, thus the issue is closed. The update will publish live tomorrow (Friday) around 11am Pacific time.
