### ISSUE TITLE
 Reload the boot image with latest version of WinPE from the current version of Windows ADK  For Custom Boot Images is not written 

### ISSUE THREAD

**Issue by SudheeshGH** [MicrosoftDocs/SCCMdocs#1283]
If we are using reload the boot image with latest version of WinPE from the Windows ADK option then we would miss the Modification done on the boot image which were done out of ConfigMgr. So we should not be using this in case of Custom boot images.  Also we should have more information on what this options does. It would go ahead and use the boot images (default) available in the Current version of ADK and then apply the drivers and optional components which are aware from the configmgr end. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 371ecfcd-7505-e201-60af-cc59c5de2c85
* Version Independent ID: e3321fbb-b479-9168-31b3-e610f044bd5e
* Content: [Manage boot images  - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/get-started/manage-boot-images#feedback)
* Content Source: [sccm/osd/get-started/manage-boot-images.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/get-started/manage-boot-images.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @SudheeshGH for the feedback. I suppose it's good to be clear that any customizations made outside of SCCM aren't retained when you reload the boot image.

**Comment by aczechowski** [comment]
This issue is closed because I revised this article. The changes will publish live tomorrow (Friday, 1 March) around 11am Pacific time.
