### ISSUE TITLE
Remote Content Library on Azure File Storage supported configuration? 

### ISSUE THREAD

**Issue by Btreyo** [MicrosoftDocs/SCCMdocs#1285]
For the HA feature is the Remote Content library supported when hosted on an Azure File Storage? Where the Site Servers and Site Systems are running in an IaaS configuration. 

https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/the-content-library#bkmk_remote

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92260657-2102-c15f-a844-5fa3aff64aae
* Version Independent ID: a4597d2d-9441-61f2-718d-c0a54a46d3fd
* Content: [The content library - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/the-content-library#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/the-content-library.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/the-content-library.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
We've not tested this configuration, so not sure if it will work, thus not supported. If Azure is sharing the content as any Windows file share, then it might just work. But again, not something we've tested. If you want the product to consider support for this scenario, please file [product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback). I'm closing this issue as there's nothing actionable for docs at this time; we don't generally document what we don't support.
