### ISSUE TITLE
PXE support

### ISSUE THREAD

**Issue by santoshseth** [MicrosoftDocs/SCCMdocs#1291]
If PXE support is required, you must use on-premises distribution points (standard or pull) to respond to boot requests. WDS is currently not supported to run on Azure VMs.
Is this still correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0da69878-a841-1f05-32c2-a1fcba10506f
* Version Independent ID: 769913cc-0fa4-cd5b-b015-b7c5f38fc0d4
* Content: [Configuration Manager on Azure](https://docs.microsoft.com/en-us/sccm/core/understand/configuration-manager-on-azure)
* Content Source: [sccm/core/understand/configuration-manager-on-azure.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/configuration-manager-on-azure.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @santoshseth for the feedback. I can't find any further documentation on WDS to dispute it, so assume there's no change. I'm checking with the engineering team if there's any update otherwise.

**Comment by santoshseth** [comment]
Hi, Is there any update from Engineering team?

**Comment by krishnasharma399** [comment]
I also need info on the queries Santosh posted, please. My main concern is WDS supportability on Azure VMs.

**Comment by yogevdaniel** [comment]
Any news about pxe support on azure?
Eta?

**Comment by aczechowski** [comment]
Remember, this feedback mechanism is for product documentation. Right now, I don't have any further information to change what we have documented.

To get feedback directly into the hands of the engineering team, please file [product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback).

In fact, I'm closing this issue as there's nothing actionable for the doc team at this time.
