### ISSUE TITLE
Clarify permissions needed for creating driver package

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#1292]
From #1269 we changed the permissions from **Read/Write** to **Full control**. This level of access may not be least privileged. It also doesn't specify share versus NTFS permissions.

There are also conflicting statements about the role that needs these permissions, whether it's the site server or the SMS Provider. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50ea9684-c819-737b-0644-caec514bcfa0
* Version Independent ID: 22949267-6307-ba3c-04d9-c8d7382d0017
* Content: [Manage drivers  - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/get-started/manage-drivers#feedback)
* Content Source: [sccm/osd/get-started/manage-drivers.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/get-started/manage-drivers.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by greg-lindsay** [comment]
Note: I found that if I add the following NTFS perms on the driver Sources$ share it works. If I only add change permissions for 'Everyone' I get an access error.  This seems to be different from an earlier version of ConfigMgr.

Anyway, here is the command that worked for me:
New-SmbShare -Name Sources$ -Path D:\Sources -FullAccess "NT AUTHORITY\INTERACTIVE", "BUILTIN\Administrators"

**Comment by greg-lindsay** [comment]
The following worked for me. It's SMB permissions.
New-SmbShare -Name Sources$ -Path D:\Sources -FullAccess "NT AUTHORITY\INTERACTIVE", "BUILTIN\Administrators"

**Comment by aczechowski** [comment]
Switching tracking to internal item 7210901
