### ISSUE TITLE
Which version of SCCM in Windows Server that support creating and distributing Windows Store App Package?

### ISSUE THREAD

**Issue by armstrong-charles** [MicrosoftDocs/SCCMdocs#1299]
[Enter feedback here]
Documentation describes that  current branch supports creating and distributing Windows Store apps package thru SCCM. I would like to automatically install the Windows Store apps to client machine directly from the SCCM, is it possible? what version of the SCCM support this functionality?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38871084-9519-7f5c-9061-3151ebbca36a
* Version Independent ID: 9369b95d-4c49-2602-e96d-9e0325be80a7
* Content: [Create Windows applications - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/get-started/creating-windows-applications)
* Content Source: [sccm/apps/get-started/creating-windows-applications.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/get-started/creating-windows-applications.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @armstrong-charles, you can find that information in the following article: [Manage apps from the Microsoft Store for Business with Configuration Manager](https://docs.microsoft.com/sccm/apps/deploy-use/manage-apps-from-the-windows-store-for-business). I'm closing this issue.
