### ISSUE TITLE
Partial content support

### ISSUE THREAD

**Issue by Eri-Ichikawa** [MicrosoftDocs/SCCMdocs#1306]
Does "Partial content support" in chart mean Express download works ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: def581b6-f8e0-f512-2113-9c3495be54c2
* Version Independent ID: 8effe9f9-9e7b-3d6e-033c-639b56acd648
* Content: [Optimize Windows 10 update delivery - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/optimize-windows-10-update-delivery#selecting-the-right-peer-caching-technology)
* Content Source: [sccm/sum/deploy-use/optimize-windows-10-update-delivery.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/optimize-windows-10-update-delivery.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Eri-Ichikawa for the question. Yes, "partial content" effectively means "express". That's good feedback that we don't properly define the "partial content" term in this article.

**Comment by mestew** [comment]
I updated the partial content types with 1910cb updates to this article. The table has been reordered a bit to make the supported content types for partial content clearer.
