### ISSUE TITLE
sysadmin rights over SQL Server instance requirement question?

### ISSUE THREAD

**Issue by diegoalameda2** [MicrosoftDocs/SCCMdocs#1313]
I need to know why installation account or admin account must retain sysadmin rights over SQL Server instance, that´s because a customer´s SQL Administrator want to know a technical reason for that requirement. Thanks in advance. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b3c02ca-4813-9b76-65a6-e9afce739bad
* Version Independent ID: 8fd815c3-c681-247a-7674-76109d5ed1e6
* Content: [Prerequisites for sites - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/prerequisites-for-installing-sites#feedback)
* Content Source: [sccm/core/servers/deploy/install/prerequisites-for-installing-sites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/prerequisites-for-installing-sites.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
The site server computer account needs sysadmin because that's how the product is designed and tested, in case any SQL configuration changes are necessary in the future.
I'm not sure about the installation account, though. I'm checking with engineering.

**Comment by aczechowski** [comment]
The installation account only needs sysadmin permissions during setup. After setup is complete, only the site server computer account requires sysadmin.

**Comment by aczechowski** [comment]
This issue is closed because I submitted a change for it that will publish tomorrow
