### ISSUE TITLE
1806/1810 All Deployement vs Software Updates

### ISSUE THREAD

**Issue by chboeye** [MicrosoftDocs/SCCMdocs#1317]
Need to mention: In 1810, there is a new client setting in "Software Update" to allow the "Software Update window" to run inside the "All Deployments" one.

Behavior clarification: In 1806/1810, there are 2 different things that can happen with theses specific windows:
- You have an All Deployments window AND a SU window: SU will only run during SU window
- You have an All deployments window BUT NO SU Window: Software Updates will run DURING the All deployment window

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a69524-75f1-5c55-5091-66b7c3326a7b
* Version Independent ID: 48b982d2-1ee9-7d2a-a1f9-14cdf0dadb6a
* Content: [Use maintenance windows - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/collections/use-maintenance-windows)
* Content Source: [sccm/core/clients/manage/collections/use-maintenance-windows.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/collections/use-maintenance-windows.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @chboeye, we're still working on finalizing the 1810 content. 

Reference the following articles in the meantime:
- [Improvement to maintenance windows for software updates](https://docs.microsoft.com/sccm/core/get-started/capabilities-in-technical-preview-1809#bkmk_sum-mw)
- [What's new in version 1810](https://docs.microsoft.com/sccm/core/plan-design/changes/whats-new-in-version-1810#improvement-to-maintenance-windows-for-software-updates)

**Comment by aczechowski** [comment]
I made a change for this, it should publish live tomorrow
