### ISSUE TITLE
Please provide version numbers with ADK version

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/SCCMdocs#1318]
Since ADK once installed can only be identified by its version number and doesn't advertise by its &lt;year\month&gt; number, please mention these version numbers on this page as well. The guys from System Center dudes have a good overview: https://www.systemcenterdudes.com/windows-10-adk-version-history/ but this information must be included into the official documentation I.M.H.O. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc732ec0-eb14-8da2-7688-dd74a72cdae5
* Version Independent ID: a93682ff-2984-38e0-5a0d-6f77c1c9e5db
* Content: [Support for Windows 10 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/support-for-windows-10#feedback)
* Content Source: [sccm/core/plan-design/configs/support-for-windows-10.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/support-for-windows-10.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @kennethvs, good feedback. And timely, I'm working on other revisions today.

**Comment by aczechowski** [comment]
I'm closing this issue. I've made the changes, but they won't publish for a few days. 😉

**Comment by kennethvs** [comment]
Thanks Aaron!
