### ISSUE TITLE
Trusted root certificate needs to be added to CMG and Clients both when CA is Internal.

### ISSUE THREAD

**Issue by motaj1** [MicrosoftDocs/SCCMdocs#1319]
This note needs to be edited to include "and Clients" at the end.

"Starting in version 1806, when you create a CMG, you're no longer required to provide a trusted root certificate on the Settings page. This certificate isn't required when using Azure Active Directory (Azure AD) for client authentication, but used to be required in the wizard. If you're using PKI client authentication certificates, then you still must add a trusted root certificate to the CMG."

Customers trying Autopilot with Internal PKI, may run into WINHTTP_CALLBACK_STATUS_FLAG_INVALID_CA on Clients if they don't trust Internal CA (root/intermediate) cert used by CMG.

Our documentations gives an impression that no additional steps are required on Client side when internal CA is used. Doesn't matter Autopilot or not, clients must trust the cert used by CMG.

It seems we clarified here https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway#cmg-trusted-root-certificate-to-clients 
It will be great if we can edit the above note as well to avoid confusions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c095180-90a2-79c6-a7fb-6504cafbcfb6
* Version Independent ID: fb9c2930-b213-3eef-c7bb-c8f11ec97aca
* Content: [CMG Certificates](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway#feedback)
* Content Source: [sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by motaj1** [comment]
Maybe this needs more clarification than what I initially thought.
Adding the trusted root to CMG Settings page won't do anything on the Client side, so we may need clarify that Client Side Trust is external to SCCM and needs to be taken care separately and then refer to: 
https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway#bkmk_cmgroot 
It will also be nice to mention customers can use Intune to add Trusted Root on Clients.

**Comment by aczechowski** [comment]
Thanks @motaj1 for the feedback
