### ISSUE TITLE
Product Lifecycle Node

### ISSUE THREAD

**Issue by SCCMAdmin** [MicrosoftDocs/SCCMdocs#1323]
Team, what does this mean exactly? Please expand on it. "Starting in version 1810, the dashboard includes information for System Center 2012 Configuration Manager and later." I'm guessing SCCM 2012 and older SCCM Current Branch versions will begin to appear in the Product Lifecycle node as expired products.

What permission can I give to only allow a role to see the Product Lifecycle node without making them a full Asset Intelligence role?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e5b5231-0498-f10a-fcd7-58230e43cca5
* Version Independent ID: aa3f037a-f646-e683-867e-b8e16f27966d
* Content: [Product lifecycle dashboard - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/asset-intelligence/product-lifecycle-dashboard)
* Content Source: [sccm/core/clients/manage/asset-intelligence/product-lifecycle-dashboard.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/asset-intelligence/product-lifecycle-dashboard.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by SCCMAdmin** [comment]
PS. How about adding Microsoft Office (volume licensing / MSI) to the node too?
Even though 365 Click-to-Run is in use, there are always some MSI installations hiding somewhere. Would be good to expose the data as for client server and DB already done. Happy to log product feedback if this sounds useful.

**Comment by aczechowski** [comment]
Thanks @SCCMAdmin for the feedback. Yes, if/when you have a version of Configuration Manager that's out of support, this dashboard will show information about it. 

Re Office, see [Office products on lifecycle dashboard](https://docs.microsoft.com/sccm/core/get-started/2019/technical-preview-1901#bkmk_lifecycle) in technical preview version 1901. 

I'm checking with engineering on the roles/permissions. Good note that we don't include that information in the article.

**Comment by SCCMAdmin** [comment]
Nice one @aczechowski . Your face looks familiar. I think I watched you on MVA (RIP to this great site!). :-)

Excellent news re SCCM agents and to come the Office installations. The link you shared did show some simple text, but was unclear if that is for MSI only. i.e. excluding Click-to-Run.

Are you going to reply here with Lifecycle dashboard node only permissions? i.e. should I check her for the answer in future? I'm literally wanting to configure this internally now as I'm giving some managers a view into aged Server and SQL views. Without them accessing it as self-service, we need to provide the data manually. I've pushed one to SSRS reporting so it's not a nice UI in browser (lack of colour more than anything) after they've seen a console screen shot. :-) 

Thanks!

**Comment by aczechowski** [comment]
Yes, once I get info on the permissions I'll update this issue. Then when the time comes that we update this article, we'll add that content. Or if someone from the community wants to make the contribution that may be a faster path to publication. 😄 ([How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute) if you want to review.)

p.s. and yes, I've done some MVA sessions in the past when I was a PM.

**Comment by SCCMAdmin** [comment]
Thank you. I'm waiting for now. Cheers.

**Comment by ddubs1** [comment]
I believe this statement is misleading "Based on inventory data the site collects from managed devices, the dashboard displays information about all current products. However, the information displayed for operating systems and SQL Server is limited to the following versions:"

It says it displays information "about all current products"   that is not the case as it only shows Microsoft Products and not all Microsoft Products.  

Thanks!

**Comment by SCCMAdmin** [comment]
What's the update here?
@aczechowski or anyone else?
Definitely waited patiently enough.

**Comment by aczechowski** [comment]
Hi @SCCMAdmin, yes, thanks for your patience. The previous feature owner left, so I'm trying to track down the current owner and/or someone knowledgeable.

**Comment by SCCMAdmin** [comment]
Thanks @aczechowski for the quick reply. I can confirm that I have provided reporting readers access to the Asset Intelligence > LifeCycle 05A - Product lifecycle dashboard. This works fine for those outside the console. 

So what remains is giving console users access specifically to the Product Lifecycle node and not to all of Asset Intelligence if possible.

**Comment by aczechowski** [comment]
We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.

I unfortunately never got a definitive answer regarding the required permissions.
