### ISSUE TITLE
Clarification to Servicing Process section

### ISSUE THREAD

**Issue by jowiswel** [MicrosoftDocs/SCCMdocs#1324]
Only updates that have a .cab or .msp update can be applied in this fashion, however the GUI allows you to select any available update where the content has been downloaded, regardless of its content type (e.g. The initial install of IE 11 on Windows 7). Documentation should be updated to note that certain updates may be presented for selection, that cannot actually be applied in an offline manner, and will be noted as not supported in the OfflineServicingMgr.log file. "Not applying this update binary, it is not supported.	SMS_OFFLINE_SERVICING_MANAGER	3/13/2019 3:48:35 PM	77356 (0x12E2C)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6d04f4d-edd4-3ba9-0723-e3b2634c1b7e
* Version Independent ID: 216fe20c-5009-bcb5-ee93-fb942a034ba2
* Content: [Manage OS images - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/get-started/manage-operating-system-images#feedback)
* Content Source: [sccm/osd/get-started/manage-operating-system-images.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/get-started/manage-operating-system-images.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jowiswel for the feedback, that's a good point.

**Comment by aczechowski** [comment]
This issue is closed because I made a change to the article to address it. The updated article should publish live tomorrow (Wednesday) around 11am Pacific time.
