### ISSUE TITLE
Configure Enhanced HTTP on CAS

### ISSUE THREAD

**Issue by ehsanomidi** [MicrosoftDocs/SCCMdocs#1327]
On CAS, the checkbox to enable Enhanced HTTP is under General tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cfc73c1-e15c-5dde-2a22-5cfc3eb7eb1c
* Version Independent ID: 50df732f-9232-74f6-f7d2-dda59c9b125b
* Content: [Enhanced HTTP - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/enhanced-http)
* Content Source: [sccm/core/plan-design/hierarchy/enhanced-http.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/enhanced-http.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ehsanomidi, this detail will be added when the technical preview feature releases to current branch. I'm closing this issue as I'm tracking that work elsewhere.
