### ISSUE TITLE
Need more documentation/examples

### ISSUE THREAD

**Issue by DiskCrasher** [MicrosoftDocs/SCCMdocs#1331]
This is a powerful tool but not very intuitive and this page barely covers enough to get someone started. Where is the documentation for all the other buttons/features?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d969e250-c071-1197-8b7c-13ce8362cae1
* Version Independent ID: 7d7a4c67-0776-5ea2-2beb-0b6710d310f4
* Content: [Introduction to WBEMTEST - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/core/understand/introduction-to-wbemtest)
* Content Source: [sccm/develop/core/understand/introduction-to-wbemtest.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/core/understand/introduction-to-wbemtest.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @DiskCrasher for the feedback. We unfortunately have a large backlog of work for the SDK content, but are looking at ways to improve it in the future. Although honestly I don't see us investing much in expanding this article further beyond its current "introductory" state. There are some resources linked at the bottom of the article (although I'm not sure how many are still valid). I would hope there are other community resources available for more in-depth information.

**Comment by aczechowski** [comment]
😆 thanks @ChrisKibble. While it ships in Windows, the history actually goes back to early days of SMS. And there really isn't anything else out there on it. So this issue I think is really more about improving this historical article to help direct folks to more current resources or ways of doing the same thing. A great opportunity for the community to contribute some real-world wisdom on the topic... 😉

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
