### ISSUE TITLE
restoring without site backup / only with database backup  

### ISSUE THREAD

**Issue by jamelia1303** [MicrosoftDocs/SCCMdocs#1332]
I am trying to restore CM Primary Site. I do not have a CM server and site backup and that's why  I do not have CD.latest folder. Is it possible to restore server if you have just DB?

**Comment by aczechowski** [comment]
Thanks @jamelia1303 for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
