### ISSUE TITLE
Update for 1810 for hierarchies

### ISSUE THREAD

**Issue by Yupiter2005** [MicrosoftDocs/SCCMdocs#1334]
Now we support HA for hierarchies, contradicting the statement below:
A site server in passive mode isn't supported in a hierarchy. A hierarchy includes a central administration site and a child primary site. Only create a site server in passive mode at a standalone primary site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c416209-7476-14b2-a60b-9f3477dc79be
* Version Independent ID: 765534af-f933-c768-0994-fa8d0a5712a0
* Content: [Site server high availability - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/site-server-high-availability)
* Content Source: [sccm/core/servers/deploy/configure/site-server-high-availability.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/site-server-high-availability.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback @Yupiter2005. We're still working on integrating 1810 content into the core docs. I'll keep this issue open until I revise this article, which should be soon.

**Comment by aczechowski** [comment]
I made revisions to this article, so closing this issue. The changes should publish later today or tomorrow morning at the latest.

**Comment by ShehzadUIT** [comment]
if I have a standalone primary site and I create a passive site server, how will I manually promote the passive server if the current active server is down and I cannot connect to the ConfigMgr console?

**Comment by ShehzadUIT** [comment]
forgive me. I got the answer from the article. having multiple SMS_Providers….got it Thanks
