### ISSUE TITLE
Documentation standards suggestion

### ISSUE THREAD

**Issue by dieselVtwin** [MicrosoftDocs/SCCMdocs#1337]
This article, https://docs.microsoft.com/en-us/sccm/core/get-started/includes/1811/1359388, has a title that begins with, "Improvements to...".  This implies that the original product version did not have this feature.

I suggest that the document template be amended to include the minimum/maximum product version that the document text applies to.

Regards,
Alan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89376922-8029-19be-a332-0c8d61734b87
* Version Independent ID: bfb4f44e-dc30-f95c-7655-a07ec8f588d5
* Content: [Improvements to task sequence media creation](https://docs.microsoft.com/en-us/sccm/core/get-started/includes/1811/1359388)
* Content Source: [sccm/core/get-started/includes/1811/1359388.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/includes/1811/1359388.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @dieselVtwin for the feedback. This include article is not intended to be viewed directly, but only in the context of the technical preview version in which the feature is available: https://docs.microsoft.com/sccm/core/get-started/capabilities-in-technical-preview-1811#bkmk_tsmedia

Can you let me know how you came across this direct include link? I want to make sure they are not easily discoverable (the include files, the content itself should be discoverable through the tech preview content).
