### ISSUE TITLE
Entry for "Delete Duplicate System Discovery Data" missing

### ISSUE THREAD

**Issue by JoergWu** [MicrosoftDocs/SCCMdocs#1339]
On CAS systems you will find also "Delete Duplicate System Discovery Data" which is missing here.
Even on Google you find exactly for this phrase NOTHING (when used in quotes) so the feature was never documented by Microsoft nor by anyone else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73746b8f-0bb3-a02c-fe91-85395fb33bdd
* Version Independent ID: a7cee2bc-0b6e-e740-238b-9267c3cae370
* Content: [Reference for maintenance tasks - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/reference-for-maintenance-tasks#feedback)
* Content Source: [sccm/core/servers/manage/reference-for-maintenance-tasks.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/reference-for-maintenance-tasks.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @JoergWu for the feedback

**Comment by aczechowski** [comment]
I revised this article, the change should publish live tomorrow
