### ISSUE TITLE
Azure AD SCCM server app

### ISSUE THREAD

**Issue by GiveMeAClue** [MicrosoftDocs/SCCMdocs#1340]
From the above comment.

"Before you import the Azure AD app into Configuration Manager, you need to grant the server application permission to read directory data from Azure AD."

It would be good to explicitly state the required app permissions as SCCM version 1806  doesn't seem to automatically create the apps from what I've tried and researched. Leading to the frustration of unauthorised API call errors when running the Azure AD user discovery from SCCM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dee656d-b593-f096-d65a-d4abdbfae497
* Version Independent ID: b63377c6-4d0f-56e9-b045-280c088fe5e5
* Content: [Configure discovery - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/configure-discovery-methods#azureaadisc)
* Content Source: [sccm/core/servers/deploy/configure/configure-discovery-methods.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/configure-discovery-methods.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @GiveMeAClue for the feedback. I have some similar work to do in the near future, will try to address this at the same time.

**Comment by koenraadrens** [comment]
I had a similar issue.

The information seems outdated. Linked to Legacy App registrations?

**Comment by aczechowski** [comment]
This issue is closed because I submitted a change that will publish tomorrow
