### ISSUE TITLE
network access account in https/pki scenario

### ISSUE THREAD

**Issue by rrsit** [MicrosoftDocs/SCCMdocs#1345]
the documentation states "Starting in version 1806, a workgroup or Azure AD-joined client can securely access content from distribution points without the need for a network access account. This behavior includes OS deployment scenarios with a task sequence running from boot media, PXE, or Software Center. For more information, see Enhanced HTTP."

when i look at the "Enhanced HTTP" page, it tells us how to configure secure communication over HTTP (without S) by using sccm generated certificates. thats fine, but what about HTTPS scenarios with PKI certificates in place? do we still need the NAA? based on my test today, removing the NAA makes all workgroup OSDs fail, so i would conclude: yes, it's still needed. can this be clarified better in the documentation?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f80cf3-6f36-cb44-d0e5-d186164d6281
* Version Independent ID: ada8a281-7d9f-e82e-e4e8-056b93e8b36d
* Content: [Accounts used - Configuration Manager](https://docs.microsoft.com/en-gb/sccm/core/plan-design/hierarchy/accounts#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/accounts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/accounts.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @rrsit for the feedback. Underneath the hood, we've switched to a different form of authentication that relies on tokens. EHTTP enabled token-based auth, thus doesn't require the NAA. Token-based auth is also enabled by default when you're using PKI. So we don't require NAA in a PKI scenario. This behavior would be good to clarify on this page.

If you're having issues with this configuration, then you'll need to pursue a support option. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

**Comment by aczechowski** [comment]
I made a revision to the wording here, it should publish live on Monday. Thanks again for the feedback.
