### ISSUE TITLE
We need documentation on the Client Operations result and monitoring

### ISSUE THREAD

**Issue by SweJorgen** [MicrosoftDocs/SCCMdocs#1352]
We need a new section that describes the Client Operations node under Overview in the console. the different state of the actions and a link to how the old results are cleaned up by a Site Maintenance tasks.

**Comment by aczechowski** [comment]
Thanks @SweJorgen for filing this feedback. 😃

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. We created an internal work item to track it (7187567)
