### ISSUE TITLE
enterprice

### ISSUE THREAD

**Issue by penvanpen** [MicrosoftDocs/SCCMdocs#1355]
[Enter feedback here]

---high
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0fbab5a-8e0f-c050-f439-f3e042cf9321
* Version Independent ID: de0515e8-eff6-792e-4829-f5093275607c
* Content: [Cloud connecting with co-management - Configuration Manager](https://docs.microsoft.com/en-us/sccm/comanage/quickstarts)
* Content Source: [sccm/comanage/quickstarts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/quickstarts.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
This appears to be a typo or test, so I'm closing the issue. If I'm mistaken, please reopen with additional details
