### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by ctholloway** [MicrosoftDocs/SCCMdocs#1358]
When I go to the Microsoft Download Center link to download UpdatesPublisher.msi, I get a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe936b7a-081f-2b5e-9054-00663c13c639
* Version Independent ID: 82f3dd5d-e182-d0ff-aab0-6b7b33b643be
* Content: [Install Updates Publisher - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/tools/install-updates-publisher#feedback)
* Content Source: [sccm/sum/tools/install-updates-publisher.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/tools/install-updates-publisher.md)
* Product: **configuration-manager**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
I can access https://www.microsoft.com/download/details.aspx?id=55543 just fine (as linked in the **Install Updates Publisher** section of this article), so I assume this issue is some transient error. I'm closing the issue.
