### ISSUE TITLE
CD.latest not supported

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#1359]
The [CD.Latest article](https://docs.microsoft.com/sccm/core/servers/manage/the-cd.latest-folder#unsupported-scenarios) notes that you can't install the console from CD.Latest, but we don't mention it in this article on installing the console. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6431e1d-681e-fcfb-8066-8491491723a8
* Version Independent ID: ba71437e-ac4b-b1f4-573b-04c397249b3a
* Content: [Install console - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/install-consoles)
* Content Source: [sccm/core/servers/deploy/install/install-consoles.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/install-consoles.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by ChrisKibble** [comment]
Fixed by #1406
