### ISSUE TITLE
CCMCERTISSUERS Mutiple CA Example

### ISSUE THREAD

**Issue by nathanmaslin** [MicrosoftDocs/SCCMdocs#1361]
Hey Team

The example for mutiple CAs it's translating the HTML code correctly: 
It has CCMCERTISSUERS="CN=Contoso Root CA; OU=Servers; O=Contoso, Ltd; C=US &#124; CN=Litware Corporate Root CA; O=Litware, Inc." 
Iit should be CCMCERTISSUERS=”CN=Contoso Root CA; OU=Servers; O=Contoso, Ltd; C=US | CN=Litware Corporate Root CA; O=Litware, Inc.”
It was confusing me until I worked out what was wrong

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f14a23d-3ca2-0cc9-8fe2-8e5f21d618c7
* Version Independent ID: c2593fb4-2bb7-c645-e9fe-873dbeda2b45
* Content: [Client installation parameters and properties - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/deploy/about-client-installation-properties#feedback)
* Content Source: [sccm/core/clients/deploy/about-client-installation-properties.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/about-client-installation-properties.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by nathanmaslin** [comment]
Looks like GitHub has no problem translating the text, but that's not what I see

**Comment by aczechowski** [comment]
Thanks @nathanmaslin for calling this out. It's a simple fix to change the HTML code to the actual character `|`. Anything in a markdown code block displays as-is. I just submitted a change which will publish tomorrow, so I'm closing this issue. 

P.s. in the future, perhaps consider submitting the edit yourself! For more information, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute). 😃
