### ISSUE TITLE
Further clarification on internet clients

### ISSUE THREAD

**Issue by Yevrag35** [MicrosoftDocs/SCCMdocs#1364]
You say "Configuration Manager does not automatically send the client upgrade package to Configuration Manager cloud-based distribution points.", but I noticed that it DOES send up a copy of the Client Package automatically (at least as of 1810 it does) to cloud distribution points.  There is no separate client upgrade package as far as I can tell anymore, so how has the behavior changed in respect to internet-based clients.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7000ae26-9f15-9644-55b9-e5db68c47ff2
* Version Independent ID: 8a672552-6e90-cd91-419c-ba6a5292fabf
* Content: [Upgrade clients - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/upgrade/upgrade-clients-for-windows-computers#use-automatic-client-upgrade)
* Content Source: [sccm/core/clients/manage/upgrade/upgrade-clients-for-windows-computers.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/upgrade/upgrade-clients-for-windows-computers.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by mestew** [comment]
Changed. Thanks @Yevrag35
