### ISSUE TITLE
Post Update instructions

### ISSUE THREAD

**Issue by dbronco3** [MicrosoftDocs/SCCMdocs#1366]
As the pre-update instructions mention, "Set SQL Server AlwaysOn availability groups to manual failover", the post update instructions should remind users to reset the failover to automatic.  My two cents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b51948e-fdf8-3a75-2a81-27ff452a6f9d
* Version Independent ID: 924773d6-e3d4-5452-6bc2-3640e96b9099
* Content: [Checklist for 1810 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/checklist-for-installing-update-1810#feedback)
* Content Source: [sccm/core/servers/manage/checklist-for-installing-update-1810.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/checklist-for-installing-update-1810.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Great feedback, thanks @dbronco3 for sharing.

**Comment by aczechowski** [comment]
I'm closing this issue as I made a change for the revised checklist that we'll publish for 1906 release.
