### ISSUE TITLE
Microsoft EAP for Auth in VPN

### ISSUE THREAD

**Issue by dotps1** [MicrosoftDocs/SCCMdocs#1368]
I can't believe I am not seeing anything about how the VPN compliance policies do not properly set the auth method when its set to Microsoft EAP.  And it even reports that the machine is compliant.  With SCCM one of the only real ways to deploy AOVPN, how is this not fixed???  https://social.technet.microsoft.com/Forums/exchange/en-US/6b7cd60e-786e-4799-b6e7-3fdc3df8c42b/vpn-authentication-with-eap-peap-is-not-applied-to-the-client?forum=ConfigMgrCBGeneral

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dd4b289-bd23-a3ef-f778-9d7030d6f499
* Version Independent ID: b0bcb635-b4b8-ee2f-14d7-ce9f65d52982
* Content: [What's new in version 1810 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/whats-new-in-version-1810#feedback)
* Content Source: [sccm/core/plan-design/changes/whats-new-in-version-1810.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/changes/whats-new-in-version-1810.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @dotps1 for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

You can also file [product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback).

I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by dotps1** [comment]
thanks, but, here's the issue with that, I found an issue very similar to this, opened on this repo, also closed by you saying you would get it over to right people.  I have obviously searched for a solution, as I included a link from technet.  Microsoft keeps getting more 'transparent' yet the resolution to an issue opened practically anywhere is "you need to ask your question in some other place".  I mean if you go look at the _documentation_ for this SCCM feature, it is "wrong" because you can't actually do the things it says it can be done.  I am opening an issue on GitHub because its one the only places there seems to ever be any activity from Microsoft Employees.

And to go any further.  We have an enterprise agreement with Microsoft and an account manager and all those things.  I have been waiting over a week for any word back from them.  Im really running out of patience.  And outside of deploying AOVPN via SCCM.  The Microsoft Docs say to use login scripts.  What is that?  either use SCCM that doesn't work, or use logon scripts because there is no GPOs?!  what is going on over there?

**Comment by aczechowski** [comment]
What's the other issue to which you're referring? (You can easily reference another issue using `#123`, where the number is the issue number. There's also a icon in the editor control to reference an issue.)

Can you also be more specific on what's wrong in the feature documentation? Which specific article? What are the things that it says to do that you can't do? That's the sort of thing that I'm interested in, and is something actionable for the docs team. If you can file feedback on that specific article, with details of what's incorrect, then I can triage and investigate that. 

I'm sorry that you're having problems, but getting a case open with support is always the best way to get the fastest assistance. They are resourced to handle the issue at the right priority, and if necessary can also back channel to the engineering team.

**Comment by dotps1** [comment]
per the documentation, it says Always On VPN can be deployed via SCCM.  in configuration section of the vpn, step 12, it says to use Microsoft EAP: https://docs.microsoft.com/en-us/windows-server/remote/remote-access/vpn/always-on-vpn/deploy/vpn-deploy-client-vpn-connections#configure-the-template-vpn-profile-on-a-domain-joined-client-computer (I know it says to do this via a template end point, the the VPN configuration dialog in SCCM is literally the same dialogs).  And you can complete that all the same.  but when deploying the vpn with this setting, it does not take affect.  So.  If the documentation tells me to set it up this way, and that it can be deployed via SCCM, but it can't the setting doesn't take affect.  And really this page really needs to be updated as well: https://docs.microsoft.com/en-us/sccm/protect/deploy-use/create-vpn-profiles

I apologize for my attitude, but I have been messing with this for 2 weeks and have gotten 0 support from anyone at Microsoft.  And with this AOVPN replacing Direct Access and given 1 tool to deploy it, SCCM, and that doesn't even work, my patience level is at 0.   And I just called primer support to get my TAMs manager because they haven't responded in over a week.  BAH!
