### ISSUE TITLE
Step 10 under "Set up a CMG" needs additional detail

### ISSUE THREAD

**Issue by jowiswel** [MicrosoftDocs/SCCMdocs#1372]
In Step 10 where the document details adding certificates to the CMG it mentions how many Root and Intermediate certificates you can add, however it does not specify that if you're using PKI certificates for your clients you need to specify both the Root and Intermediate certificate from that certificate chain. If both certificates are not specified (e.g. only the Root certificate is specified) then the client will experience a 401 Unauthorized response from the CMG when trying to communicate until the appropriate Intermediate certificate is also supplied in the CMG properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fb371d2-b1f1-68ca-ed95-abf37e3ecf28
* Version Independent ID: cd7fc055-b430-3a4a-1002-c69087f30714
* Content: [Set up cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/setup-cloud-management-gateway#feedback)
* Content Source: [sccm/core/clients/manage/cmg/setup-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/setup-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jowiswel, fair feedback. I try not to wade too deep into PKI fundamentals, but that's a good suggestion to clarify. I should probably also note it on the [CMG certificates](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway#bkmk_clientroot) article.

**Comment by aczechowski** [comment]
This issue is closed because I made a tweak to the article for this feedback. The change should publish live later today.
