### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by nezaras2000** [MicrosoftDocs/SCCMdocs#1373]
It's a good idea to have a REST link to the tools itself
download link to  SCCM 2012R" toolkit is:
"https://www.microsoft.com/en-us/download/details.aspx?id=50012"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c47a4fa-cc4b-49f7-d850-312dcf59ac8c
* Version Independent ID: 26c1bc31-5c98-346b-6a27-50de3da938e0
* Content: [Configuration Manager Tools - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/support/tools#feedback)
* Content Source: [sccm/core/support/tools.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/support/tools.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @nezaras2000 for the feedback. See the note at the top of the article:

> The [System Center 2012 R2 Configuration Manager Toolkit](https://www.microsoft.com/en-us/download/details.aspx?id=50012) is still available from the Microsoft Download Center. For Configuration Manager version 1806 and later, use the versions of the tools in the CD.Latest folder on the site server. Some tools were formerly in the toolkit but not included in version 1806. These legacy tools are no longer supported.

I'm closing this issue as the link is already included.
