### ISSUE TITLE
Task sequence support for boundary groups vs Prefer distribution points over peers

### ISSUE THREAD

**Issue by franckmi** [MicrosoftDocs/SCCMdocs#1375]
[Enter feedback here]

Task sequence support for boundary groups
When a device runs a task sequence and needs to acquire content, it now uses boundary group behaviors similar to the Configuration Manager client.

The section states a TS behaves like a client. It seems the Boundary Group option “Prefer distribution points over peers within the same subnet" only works for a “full client”, NOT for a Task Sequence

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dd4b289-bd23-a3ef-f778-9d7030d6f499
* Version Independent ID: b0bcb635-b4b8-ee2f-14d7-ce9f65d52982
* Content: [What's new in version 1810 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/whats-new-in-version-1810#feedback)
* Content Source: [sccm/core/plan-design/changes/whats-new-in-version-1810.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/changes/whats-new-in-version-1810.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @franckmi for the feedback. We also need to note that behavior in the target article, https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/boundary-groups#bkmk_bgr-osd

**Comment by aczechowski** [comment]
This is fixed in the boundary groups article, closing
