### ISSUE TITLE
Contradictory information for Cloud DP

### ISSUE THREAD

**Issue by santoshseth** [MicrosoftDocs/SCCMdocs#1379]
Use Azure Resource Manager for cloud services section still has the mention of Cloud DP
Starting in this current branch version, Azure Resource Manager is the only deployment mechanism for new instances of the cloud management gateway and cloud distribution point.
However, Deprecated features and operating systems section says You won't be able to create a traditional cloud distribution point in the future.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f7079b3-29e1-3132-2224-62d0b64928bf
* Version Independent ID: 2335eaff-13c7-0a2e-c234-3f160452864b
* Content: [What's new in version 1902 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/whats-new-in-version-1902#use-azure-resource-manager-for-cloud-services)
* Content Source: [sccm/core/plan-design/changes/whats-new-in-version-1902.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/changes/whats-new-in-version-1902.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @santoshseth for the feedback. 
Yes, but you can still create a traditional CDP. 😄 When we announce deprecation, that's informing customers that we're changing some behavior. It's not until the support is removed that the change is implemented. So you can still create a CDP in version 1902, you can only do so using Azure Resource Manager. 
I'm closing this issue.
