### ISSUE TITLE
Misleading Information On The Article

### ISSUE THREAD

**Issue by ZamfirMadalina** [MicrosoftDocs/SCCMdocs#1382]
Hey,
There's a small misleading information below the screenshot at the 1st step explanation:

"The CMPivot window contains the following elements:

The collection that CMPivot currently targets is in the title bar at the top, and the status bar at the bottom of the window. For example, All Systems in the above screenshot."

In the screenshot, the targeted collection is not ALL SYSTEMS but PM_Team_Machines. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c8158c-1c8e-1567-d96d-222f5b4aec21
* Version Independent ID: f6674943-3564-2250-2334-b88c42f3a8a6
* Content: [CMPivot for real-time data - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/cmpivot#feedback)
* Content Source: [sccm/core/servers/manage/cmpivot.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/cmpivot.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@ZamfirMadalina  thanks! I actually have a few changes for that page that I am working on now. I made this change while I was there. This should be published in the next few days. 
#please close.
