### ISSUE TITLE
SCAP Dashboard Screenshots

### ISSUE THREAD

**Issue by davi-cruz** [MicrosoftDocs/SCCMdocs#1384]
I have noted that all screenshots presented on this page are related to the pre-release feature released on 1806, which was removed later. 
Would be wiser to update the documentation with the information that these screens are from this release or to remove them once in later releases (1902 at the time of this writing) this cannot be done.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f65e77c-5d4b-e02a-8591-4eaaa24e0acc
* Version Independent ID: 02969497-0684-5450-e008-4e075954cefe
* Content: [Deploy and monitor SCAP compliance - Configuration Manager](https://docs.microsoft.com/en-us/sccm/compliance/plan-design/scap/deploy-monitor-export#feedback)
* Content Source: [sccm/compliance/plan-design/scap/deploy-monitor-export.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/compliance/plan-design/scap/deploy-monitor-export.md)
* Product: **configuration-manager**
* Technology: **configmgr-compliance**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @davi-cruz for the feedback. We added the following note to the [main SCAP page](https://docs.microsoft.com/sccm/compliance/plan-design/scap/about-scap):

> This version of the tool is a pre-release feature that's only available in version 1806. This version isn't certified by NIST.
> If you require a certified tool, or are using another version of Configuration Manager current branch, use the following version of the SCAP extensions:
>
> - [Download SCAP Extensions for System Center Configuration Manager](https://www.microsoft.com/download/details.aspx?id=48741)
> - [Documentation for SCAP Extensions Version 3.0](https://docs.microsoft.com/previous-versions/system-center/system-center-2012-R2/mt228311(v%3dtechnet.10))

But perhaps we should also add it to the other pages for better visibility.

**Comment by aczechowski** [comment]
Closing this issue as I'm removing this content. Version 1806 is out of support, and SCAP isn't available in later versions.
