### ISSUE TITLE
parameter newMaxRunTime  can have an max value of 12 h = 720

### ISSUE THREAD

**Issue by MSJensG** [MicrosoftDocs/SCCMdocs#1386]
[Enter feedback here]

We should add an note that parameter newMaxRunTime  can have an max value of 12 h = 720
This is documented on:
https://docs.microsoft.com/en-us/sccm/apps/deploy-use/packages-and-programs 

If the value is set to Unknown, Configuration Manager sets the maximum allowed run time as 12 hours (720 minutes).

Every higher value will ignore from EXECMGR component and set to 720 minutes / 43200 seconds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93c4b77e-ff91-f63a-f5e7-c4baf9e3f4ad
* Version Independent ID: 1037eb78-c120-e751-e3de-ae2c1caf0321
* Content: [Create a Program - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/core/servers/configure/how-to-create-a-program#feedback)
* Content Source: [sccm/develop/core/servers/configure/how-to-create-a-program.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/core/servers/configure/how-to-create-a-program.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @MSJensG for the feedback. Good points to include.

**Comment by ChrisKibble** [comment]
@aczechowski, housecleaning item - Looks like this is all set, I didn't go back to see which PR covered it, but there is now a remark in the article:

> If you set this value to Unknown, Configuration Manager sets the maximum allowed run time as 12 hours (720 minutes).

Seems OK to close.

**Comment by aczechowski** [comment]
Hi @chriskibble, That's in the [packages and programs](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/packages-and-programs) article, but Jens' feedback is that it should also be noted in the [create a program](https://docs.microsoft.com/en-us/sccm/develop/core/servers/configure/how-to-create-a-program) article, which it is not. 😉

**Comment by aczechowski** [comment]
This issue auto-closed thanks to @jpcast88 for fixing it. 😄
