### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by ITOpsReborn** [MicrosoftDocs/SCCMdocs#1387]
Under prerequisites, the link for "How to change the location where WSUS stores updates locally" is broken. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 054797d3-c4d8-2c2e-9940-e8763f6f3881
* Version Independent ID: 9751d801-35de-ebd8-29ea-57e459f845dc
* Content: [Enable third party updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/third-party-software-updates)
* Content Source: [sccm/sum/deploy-use/third-party-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/third-party-software-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ITOpsReborn for the feedback. With the retirement of TechNet blogs there are probably a number of these sorts of links. So we need to scrub our entire library and then find or generate suitable replacements.

**Comment by aczechowski** [comment]
This link is working ok now, closing issue
