### ISSUE TITLE
New Check in 1902?

### ISSUE THREAD

**Issue by jpoling1** [MicrosoftDocs/SCCMdocs#1388]
The upgrade to 1902 seems to be checking for Network Access Protection being available? "Checking whether there are software updates that are enabled for NAP"  This does not seem to be documented anywhere related to 1902?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db678f94-700f-ad35-9fdc-d165893b5373
* Version Independent ID: 2ee761db-4b3b-6fa0-c195-ad85ebbac70d
* Content: [Prerequisite checks - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/list-of-prerequisite-checks)
* Content Source: [sccm/core/servers/deploy/install/list-of-prerequisite-checks.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/list-of-prerequisite-checks.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jpoling1 for the feedback. Yes...and refresh the page in about 60-90 minutes. 😃 I submitted a change that will publish shortly, the article was missing quite a few prereq checks. 
I'm closing this issue.

**Comment by jpoling1** [comment]
Thanks ??

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jpoling1** [comment]
Not sure why my previous comment had question marks after "thanks" . . .it was supposed to be a smiley :-)
