### ISSUE TITLE
Integration with Azure AD for Cloud Management requirement

### ISSUE THREAD

**Issue by jhongjr** [MicrosoftDocs/SCCMdocs#1398]
In the "Set up cloud management gateway" page, it's mentioning that the "Integration with Azure AD" is already a requirement when using ARM. It's not listed in this section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778368d0-1054-678c-4d74-5dce1b5826c8
* Version Independent ID: aaac7308-66e6-66f0-8248-14e1505c11a6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/plan-cloud-management-gateway#feedback)
* Content Source: [sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jhongjr, good feedback. The requirement for Azure AD is mentioned at the bottom of the list of requirements, but only in the context of Windows 10. I think we can modify this sentence to something like:

> Integration with Azure AD is needed for Azure Resource Manager deployments. It may also be required for Windows 10 clients.

**Comment by aczechowski** [comment]
Thanks to @jpcast88 for making this change, which should publish in less than an hour

**Comment by bmilbauer** [comment]
I'm still confused. What does "integration" mean exactly? That we need our machines Azure AD or hybrid joined? Do I need to have all my users that will connect via CMG Azure AD licensed? Signed into the machine with an Azure AD identity?
