### ISSUE TITLE
_SMSTSClientCache variable

### ISSUE THREAD

**Issue by mattsmacblog** [MicrosoftDocs/SCCMdocs#1400]
Does "_SMSTSClientCache" still exist in 1806 onwards?   As it's not referenced over on the main Variables page - https://docs.microsoft.com/en-us/sccm/osd/understand/task-sequence-variables

(admin edit, moving issue link to article that needs the change)
The variable s mentioned in https://docs.microsoft.com/sccm/osd/deploy-use/create-a-task-sequence-to-install-an-operating-system

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 659b0c85-eac7-591e-42d3-8ca629fd6c84
* Version Independent ID: 392139c6-3e46-c0b8-bd1b-ebfc51615fc7
* Content: [Task sequence variable reference - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/understand/task-sequence-variables#feedback)
* Content Source: [sccm/osd/understand/task-sequence-variables.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/understand/task-sequence-variables.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @mattsmacblog for the feedback. Yeah, we don't generally remove variables. There are a number of variables that aren't included in the doc, and on my to do list to work with engineering to review and revise (see #551). 

I'm going to adjust this feedback to link to the variables article, as that's where the change needs to happen.
