### ISSUE TITLE
DIsabled/Missing link Best practices for software updates in Configuration Manager doc

### ISSUE THREAD

**Issue by mengoglia** [MicrosoftDocs/SCCMdocs#1401]
[Enter feedback here]

•How to implement a shared SUSDB for Configuration Manager software update points under the Best practices for software updates in Configuration Manager doc appears to be broken or disabled

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc6a30e0-d898-a063-927a-4fb463073260
* Version Independent ID: d813ba1e-dd70-6bf6-95fa-1011e9bdef7c
* Content: [Best practices for software updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/plan-design/software-updates-best-practices#bkmk_shared-susdb)
* Content Source: [sccm/sum/plan-design/software-updates-best-practices.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/plan-design/software-updates-best-practices.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @mengoglia, a known issue that we're trying to address. A number of links to old TechNet blogs are now retired, so we're working on a plan. We already have a fix in for the second link in that list you reference.

**Comment by jpcast88** [comment]
@mengoglia @aczechowski Both links seem to be working, so I think this issue can be closed out?

**Comment by mengoglia** [comment]
Looks good thanks so much

Have a good weekend




Matt Engoglia
Infrastructure Engineering & Delivery
End user Experience (EUX)
progressive insurance
440.395.0178 (w)  |  440.478-1182(m)  |  matt_engoglia@progressive.com<mailto:matt_engoglia@progressive.com>

**Comment by aczechowski** [comment]
Great, thanks for following up!
