### ISSUE TITLE
Port Requirements for Remote Content Library

### ISSUE THREAD

**Issue by kfernand** [MicrosoftDocs/SCCMdocs#1402]
Can this page be updated to reflect the port requirements for Remote Content Library? Remote Package Shares?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f658ee4b-d051-0d7c-4656-19a846908469
* Version Independent ID: 3478e881-199c-f0c4-b218-0dd609eb0427
* Content: [Ports used for connections - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/ports#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/ports.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/ports.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Yes, thanks @kfernand, good feedback.

**Comment by aczechowski** [comment]
FYI, I checked with engineering, this feature should only require SMB 445

**Comment by kfernand** [comment]
Great!  I made that assumption but didn't want to be surpised when I was testing and have to go back to our firewall admins.

**Comment by aczechowski** [comment]
Thanks to @jpcast88 for making this change, which should publish in less than an hour
