### ISSUE TITLE
IP Helper vs DHCP Options clarification

### ISSUE THREAD

**Issue by daldwinc** [MicrosoftDocs/SCCMdocs#1405]
Hello,

In reference to this note:

> When configuring a single PXE enabled distribution point to support multiple subnets it is not supported to use DHCP options. Configure IP helpers on the routers to allow PXE requests to be forwarded to your PXE enabled distribution points.

Can I suggest a change to the wording of this statement? It leads our clients to believe that DHCP Options do not work for this purpose, which is incorrect. In an enterprise, multi-tenant environment with hundreds of routed networks, using DHCP options is safer, and scales easily.

How about:

> When configuring a single PXE enabled distribution point to support multiple subnets it is preferred to use IP helpers. Microsoft Support for PXE is not available for configurations using DHCP options. Configure IP helpers on the routers to allow PXE requests to be forwarded to your PXE enabled distribution points.

Thanks!

(4/18 admin edit: adding doc footer to link to article in question)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3527c358-cf3f-07ec-1cb8-88982ff99122
* Version Independent ID: 2c618192-bb71-d934-d20e-1ceb15cb2e01
* Content: [Use PXE for OSD over the network - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network#BKMK_Configure)
* Content Source: [sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @daldwinc for the feedback. Let me check with the engineering and support teams that contributed to this statement.

**Comment by aczechowski** [comment]
Hi @daldwinc -
I discussed your concern with the team. This guidance was recently added after much discussion, and it's based on what the product team actually tests. It's also based on data from the support team about what is consistently most successful for customers. 

Keep in mind that this support statement means that we don't test DHCP options, and also don't recommend DHCP options based on data from Microsoft Support. But that doesn't mean it doesn't work. If you had some issue with PXE, and called support for assistance, it would be best-effort. And they might ask to remove that variable first to eliminate a known unsupported scenario.

If you feel strongly about this, I suggest you file [product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) for it to support DHCP options. (A UserVoice idea is probably the best starting point, to gather community interest in the idea.) Although I'll be honest, the engineering and support teams are pretty passionate *against* DHCP options. 🤔 

So thank you for the feedback, but we're not going to change this statement. I'm closing this issue.
