### ISSUE TITLE
WSUS console is a requirement on primary site servers

### ISSUE THREAD

**Issue by sigurd-de** [MicrosoftDocs/SCCMdocs#1409]
WSUS console is still still a requirement on primary site servers, e.g installation of site server in passive mode fails w/o installing 'Install-WindowsFeature -Name UpdateServices-Ui'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9070eb9b-0e5f-a877-e02e-2d1cea2a2b38
* Version Independent ID: df251762-f2d6-9f06-4fa9-ec5cea2cca0a
* Content: [Site prerequisites - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/site-and-site-system-prerequisites#feedback)
* Content Source: [sccm/core/plan-design/configs/site-and-site-system-prerequisites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/site-and-site-system-prerequisites.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @sigurd-de for catching this. Yes, this is a [prerequisite](https://docs.microsoft.com/sccm/core/servers/deploy/install/list-of-prerequisite-checks#wsus-on-site-server). I'm not sure why it's not listed here.

**Comment by AndrewJNet** [comment]
@aczechowski I'm claiming this issue for #MMS2019Docathon

**Comment by aczechowski** [comment]
Thanks to @AndrewJNet, this issue is fixed. The change is published live.
