### ISSUE TITLE
1710 to 1902 upgrade is not supported remove it from https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/whats-new-in-version-1902

### ISSUE THREAD

**Issue by suchouh** [MicrosoftDocs/SCCMdocs#1411]
https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/whats-new-in-version-1902

"Apply this update on sites that run version 1710, 1802, 1806, or 1810. When installing a new site, it's also available as a baseline version. "

Remove 1710 as 1710 to 1902 Upgrade is not supported. Supported scenario:

1810 --> 1902
1806 --> 1902
1802 --> 1902
2012 R2 SP1 /SP2 à 1902 (the only CD support)

**Comment by mestew** [comment]
@suchouh Thanks for noticing this!
