### ISSUE TITLE
Lid close action description

### ISSUE THREAD

**Issue by JustMatthew** [MicrosoftDocs/SCCMdocs#1415]
The Lid close action description "Specifies the action that occurs when the user closes the lid of a portable computer." is duplicated in several item settings. Is this a typo? Or, meant to indicate that the item setting also applies to or effects the Lid close action?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fd918fb-7d8a-cc92-f8d9-339c2db98cb1
* Version Independent ID: 9cb416d9-1927-eb95-4e3f-ef9f9684b14b
* Content: [Create and apply power plans - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/power/create-and-apply-power-plans#feedback)
* Content Source: [sccm/core/clients/manage/power/create-and-apply-power-plans.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/power/create-and-apply-power-plans.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @JustMatthew for catching this. I double-checked with the engineering team, it's definitely a copy/paste error. That sentence only applies to the lid close action, it should be removed from all other settings that have it. 

I'll be honest, it's unlikely that we'll get to fixing this issue anytime soon, as there are no planned investments at this time in this feature area. So I've marked this issue with one of the community tags for help. If you want to make the change yourself, you can find instructions in [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute).

**Comment by aczechowski** [comment]
Thanks to @jpcast88 for submitting a change for this issue, which is why it closed. The change should publish live tomorrow (Thursday, April 18) around 11am Pacific time.
