### ISSUE TITLE
Server Management Licenses

### ISSUE THREAD

**Issue by bryandam** [MicrosoftDocs/SCCMdocs#1419]
According to Jason Sandys*, the product team has said a Server Management License is only required if the Configuration Item feature is used.  Otherwise, server OS can be managed using Client Management Licences.  That seems almost too good to be true and I couldn't find any reference anywhere regarding that.  So if it is indeed true, can we add a note here?

*https://www.reddit.com/r/SCCM/comments/bdh7pr/sccm_licensing_for_server_clients/ekya0s6?utm_source=share&utm_medium=web2x

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3b9a7fa-9585-a2fb-590e-0b74e128035d
* Version Independent ID: 9aae8e97-de68-c274-b4c6-cd925568c75b
* Content: [Product and licensing FAQ - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/understand/product-and-licensing-faq#feedback)
* Content Source: [sccm/core/understand/product-and-licensing-faq.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/product-and-licensing-faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @bryandam for filing the issue. As you might expect, I need to inquire about this one. 😄

**Comment by bryandam** [comment]
You don't have every line of the licence agreement committed to memory?  Shocked, shocked I tell you!

Re-reading this I probably should have asked a more generic/high-level question such as 'can I use a Client ML on a server OS' or 'When do I need a Server ML'.

**Comment by aczechowski** [comment]
There's nothing about this in the [product licensing terms](https://www.microsoft.com/licensing/product-licensing/products) ([Direct link to English product terms doc](http://www.microsoftvolumelicensing.com/Downloader.aspx?documenttype=PT&lang=English)), and our licensing team said that all server OS environments require server MLs. They're not aware of any exception. 

As @jason4tw notes in the reddit thread, folks should be asking these questions to their Microsoft account team to contact the licensing desk. But most likely the outcome is as stated above. 

I'm closing this issue.

**Comment by bryandam** [comment]
Awesome, thanks for confirming Aaron.  Too good to be true indeed.
