### ISSUE TITLE
Need clarification regarding Ubuntu 16.04 LTS support

### ISSUE THREAD

**Issue by aborzenk** [MicrosoftDocs/SCCMdocs#1420]
This page states that the latest supported Ubuntu version is 14.04 LTS, while UNIX/Linux Client has support for 16.04 LTS when assigned even to ConfigMgr 2012 sites:
https://www.microsoft.com/en-us/download/details.aspx?id=47719
The GUI of ConfigMgr LTSB allows us to choose Ubuntu 16.04 LTS as a target OS when we create Package/Program.

If that was tested with an older ConfigMgr 2012, can we expect docs update regarding Ubuntu 16.04 LTS support by ConfigMgr 1606 LTSB?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f2052d9-969f-257c-fcc3-8239c210401f
* Version Independent ID: 4cd87f51-eb47-26df-b64f-987bce82042a
* Content: [Supported Configurations for the LTSB  - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/understand/supported-configurations-for-ltsb)
* Content Source: [sccm/core/understand/supported-configurations-for-ltsb.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/supported-configurations-for-ltsb.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @aborzenk for the feedback. I'm checking on this.

**Comment by aczechowski** [comment]
Note the following statement in this [same article](https://docs.microsoft.com/sccm/core/understand/supported-configurations-for-ltsb#general-statement-of-support): 

> Limitations for future support: The LTSB has limited support for future server and client operating systems and product dependencies. The platforms list for the LTSB is fixed for the life of the release

The download page is only regarding the current branch. So this article is current and accurate for the supported configuration of LTSB. The newer client might technically work, but it's not tested, thus not officially supported. 

I'm closing this issue.
