### ISSUE TITLE
SCCM upgrade 1810 SQL Server Configuration for site upgrade [Failed]:Checks if the specified SQL Server meets the minimum requirements for site upgrade.

### ISSUE THREAD

**Issue by pierredarmanin** [MicrosoftDocs/SCCMdocs#1424]
Need help to upgrade Configuration manager to 1810.

upon running prerequisite checks for SQL Server Configuration for site upgrade [Failed]: Checks if the specified SQL Server meets the minimum requirements for site upgrade.

The version of SQL server is:
SQL2017	RTM	Standard Edition (64-bit)	14.0.3048.4

this is supported?

regards

Pierre

**Comment by aczechowski** [comment]
For the list of supported SQL versions, see [Supported versions of SQL Server
](https://docs.microsoft.com/sccm/core/plan-design/configs/support-for-sql-server-versions#bkmk_SQLVersions). For 2017, the site requires at least CU2.

I'm closing this issue.

**Comment by pierredarmanin** [comment]
Hi Aaron, thanks for your reply

My version of SQL is 2017 CU13 and during upgrade check it still giving the error that version not supported.

**Comment by aczechowski** [comment]
I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I've closed this issue as there's nothing actionable for docs at this time.

**Comment by pierredarmanin** [comment]
Hi Aaron,

thanks again for your message. I try to contact them.

regards,
Pierre
