### ISSUE TITLE
Incorrect path/architecture for CmRcViewer.exe

### ISSUE THREAD

**Issue by Maymne** [MicrosoftDocs/SCCMdocs#1427]
The currently listed information for the viewer says:
At the Windows command prompt, type &lt;Configuration Manager Installation Folder&gt;\AdminConsole\Bin\x64\CmRcViewer.exe
However, on both individually installed AdminConsole clients as well as the main SCCM server itself, it is instead found in the i386 folder, not x64. It's possible that an upcoming version of the CmRcViewer.exe will be found in the 64-bit folder, but as the current GA release (1810, 5.00.8740.1042) still includes the 32-bit version from January 2018 (5.0.8540.1001), the current information on the page is incorrect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 540c8e57-5bed-a284-6360-f37498c24e4e
* Version Independent ID: 35f90d83-56cf-6f60-ff3b-642c1b1ba041
* Content: [Remotely administer Windows computer - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/remote-control/remotely-administer-a-windows-client-computer#feedback)
* Content Source: [sccm/core/clients/manage/remote-control/remotely-administer-a-windows-client-computer.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/remote-control/remotely-administer-a-windows-client-computer.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @Maymne for the feedback, we'll double-check to confirm, but on first glance it does look like a doc bug. My 1902 console has it in the i386 folder.
