### ISSUE TITLE
Reporting Service point are NOT supported SQL Cluster

### ISSUE THREAD

**Issue by tahakogi** [MicrosoftDocs/SCCMdocs#1429]
I’ve had this discussion now with a few people but I want to verify.  The only role supported on a SQL Cluster is the Site database correct?  Here is the reference:  https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/use-a-sql-server-cluster-for-the-site-database 
 
That would lead me to believe that the **other roles are NOT supported, such as the reporting services point.**  Is that correct?

If this is correct, I think it should be listed as a prerequisite.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12c24984-164b-ca1e-a5c4-234eed99b01c
* Version Independent ID: 1073b072-8451-2bf0-bbf1-f5a01e404b60
* Content: [Prerequisites for reporting - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/prerequisites-for-reporting)
* Content Source: [sccm/core/servers/manage/prerequisites-for-reporting.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/prerequisites-for-reporting.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @tahakogi for the feedback. I need to check with the engineering team to verify.

**Comment by aczechowski** [comment]
After some discussion with the engineering team, this isn't a scenario that's currently tested. So following that path, we generally don't support what we don't test. But we also don't generally document what we don't support. Since it's not something we've tested, I'm reluctant to make any explicit statements either way. I'm closing this issue.
