### ISSUE TITLE
Enable Service Broker doesn't work when DB is in AOAG

### ISSUE THREAD

**Issue by SMSAgentSoftware** [MicrosoftDocs/SCCMdocs#1432]
You can't enable the Service Broker option on a database that's already part of an availability group. You have to enable that option before adding it to the availability group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53d1da83-d988-fb2b-82c5-fd9cf117cd42
* Version Independent ID: 2b1a3bd2-5116-1f21-c196-e3e5698a83c9
* Content: [SQL Server Always On - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database#feedback)
* Content Source: [sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @SMSAgentSoftware for the feedback. One of our engineers recently reviewed this article and provided some detailed feedback for revision. We'll look at updating it in the future.

**Comment by aczechowski** [comment]
I'm closing this issue as it's addressed in the 1906 content that will publish soon.
