### ISSUE TITLE
Remote Content Library - Uses the "Site System Installation Account" if specified.

### ISSUE THREAD

**Issue by SCCMWalker** [MicrosoftDocs/SCCMdocs#1439]
Hello, one thing that is not called out here that should be mentioned is that if you use a Site System Installation Account that is not the machine account, it will use the site installation account instead of your site server machine account to attempt to login to your remote content library and access the files. This is very problematic when you are using a DMZ account as the site system installation account as you either have to give perms to the content library to the DMZ account, have to give the site server machine account access into the DMZ or have to create a local account in the DMZ and remote content library with the necessary perms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92260657-2102-c15f-a844-5fa3aff64aae
* Version Independent ID: a4597d2d-9441-61f2-718d-c0a54a46d3fd
* Content: [The content library - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/the-content-library)
* Content Source: [sccm/core/plan-design/hierarchy/the-content-library.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/the-content-library.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @SCCMWalker for the feedback. What version of ConfigMgr are you seeing this behavior? It might be a product bug, I'm checking with engineering to confirm.

**Comment by SCCMWalker** [comment]
1806, I am talking with someone on the Premiere Support team and they indicate this is a known behavior. Also I posted elsewhere and Kerwin confirmed this is the expected behavior.

**Comment by vinaypamnani-msft** [comment]
Hi, @SCCMWalker, This is a known behavior, but the issue isn't very common. For that reason,  we recently documented the behavior in a [KB article](https://support.microsoft.com/help/4508653) rather than the documentation. #please-close
