### ISSUE TITLE
Copy Edit 

### ISSUE THREAD

**Issue by jginternet** [MicrosoftDocs/SCCMdocs#1443]
"For example, you if your site runs version 1606, you can install an update for version 1610. Updates can also install fixes for a known issue, without modifying the sites version."

*Remove "you" after "For example,"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f28ef46-ec10-139e-0667-6f61958fbc73
* Version Independent ID: e6d7f0a4-63fa-af34-b022-0f23fa50450c
* Content: [About upgrade, update, and install - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/understand/upgrade-update-install#feedback)
* Content Source: [sccm/core/understand/upgrade-update-install.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/upgrade-update-install.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jginternet for the feedback. If you would like to make this change yourself, select the **Edit** option at the top of the article. For more information, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute).

**Comment by aczechowski** [comment]
Thanks to @jpcast88 for making this edit. I'm closing the issue so no one else picks it up.

NOTE: the change won't publish until at least Monday, 6 May, due to a publishing freeze this week.
