### ISSUE TITLE
what about version between 1802 and 1810?

### ISSUE THREAD

**Issue by say2wc** [MicrosoftDocs/SCCMdocs#1446]
The top section talk about WOL 1810 and after, the second section talks about 1802 and older. What about version 1806?? 
Does it use the old way or the new way??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ab1f8a1-053c-d088-3b82-a3963b4a969f
* Version Independent ID: 0ed1e3ef-fd26-472b-2f49-1a98572add4b
* Content: [Configure Wake on LAN - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/deploy/configure-wake-on-lan#feedback)
* Content Source: [sccm/core/clients/deploy/configure-wake-on-lan.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/configure-wake-on-lan.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@say2wc 
Hi Raymond, 
That is completely my fault. The two headings that state 1802 should say 1806. I am changing it now, but it will be about a week before the change is actually published on this document.  1806 uses the old version of Wake on LAN. Thanks for catching this!
-Meghan
