### ISSUE TITLE
ADK 1903 compatibility with SCCM

### ISSUE THREAD

**Issue by Sansing1** [MicrosoftDocs/SCCMdocs#1448]
[Enter feedback here]
ADK 1903 is available for download through below link, however, its compatibility with different versions of SCCM is not listed.
https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install 

Please update the following link with latest information:
https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/support-for-windows-10#windows-10-adk
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc732ec0-eb14-8da2-7688-dd74a72cdae5
* Version Independent ID: a93682ff-2984-38e0-5a0d-6f77c1c9e5db
* Content: [Support for Windows 10 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/support-for-windows-10#windows-10-adk)
* Content Source: [sccm/core/plan-design/configs/support-for-windows-10.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/support-for-windows-10.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Sansing1 for the feedback. We've been having some internal discussions on this topic, will update the article in the near future.

**Comment by aczechowski** [comment]
I closed this issue as I made an update to teh article that will publish shortly.
