### ISSUE TITLE
The Prerequisites for Hub are missing key details. 

### ISSUE THREAD

**Issue by Garthmj** [MicrosoftDocs/SCCMdocs#1453]
Must have .Net 4.6.1
Must have Windows 10 built 17110 or later. (Windows 2016??)

aka Server 2012 R2 is not support but that is supported for CMTP. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 223fd312-fa85-dbb0-08da-c9f2b8109f3b
* Version Independent ID: 16344b39-3f33-7243-debb-8ac731fc16b3
* Content: [Technical preview 1904 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/2019/technical-preview-1904#prerequisites)
* Content Source: [sccm/core/get-started/2019/technical-preview-1904.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/2019/technical-preview-1904.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by mestew** [comment]
Hey @Garthmj,
Thanks for pointing this out. I am adding the OS and .Net version as a prereq to the 1904 TP doc. 
-Meghan
