### ISSUE TITLE
Missing page for System Boot Summary data

### ISSUE THREAD

**Issue by zsattler** [MicrosoftDocs/SCCMdocs#1457]
Please create a new page documenting what the data in Resource Explorer - System Boot Summary stands for and represents.

(admin edit - add article metadata to create link to target)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6d67116-14b6-bec6-01ca-1e4d40ec3f09
* Version Independent ID: 8a7b5a36-18fd-6392-d60c-da717a26b004
* Content: [How to use Resource Explorer - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/inventory/use-resource-explorer-to-view-hardware-inventory)
* Content Source: [sccm/core/clients/manage/inventory/use-resource-explorer-to-view-hardware-inventory.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/inventory/use-resource-explorer-to-view-hardware-inventory.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @zsattler for the idea! I can't find any reference to Resource Explorer classes otherwise, so I think the article on using Resource Explorer is probably the best spot for this. It might make for a good list of everything that's available/possible (at least by default).

**Comment by aczechowski** [comment]
Claiming this for MMS JE demo 😄 https://sched.co/S1aD

**Comment by aczechowski** [comment]
Adam's new article should publish live tomorrow: https://docs.microsoft.com/configmgr/core/clients/manage/inventory/resource-explorer-classes
@zsattler I'm going to close this issue. 😄 However, the new article may not technically answer your fundamental question, it currently just details the attributes. So if necessary after you review the new article, please reopen this issue (or file a new one).
