### ISSUE TITLE
Broken Link (Calling-Code-Snippets.md)

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1466]
On page:
SCCMdocs\sccm\develop\core\understand\calling-code-snippets.md

The following link is dead, cannot find a replacement.

(admin edit, adding footer to link page)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fa167c2-60ca-abac-4dda-e52e65ad6f9e
* Version Independent ID: 554fa966-7294-dc9b-653f-cc9bf20c14fc
* Content: [Calling Code Snippets - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/core/understand/calling-code-snippets)
* Content Source: [sccm/develop/core/understand/calling-code-snippets.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/core/understand/calling-code-snippets.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by 1RedOne** [comment]
This link is alive again.

**Comment by AndrewJNet** [comment]
I think @ChrisKibble  is referring to [Creating Your Own HTA's](http://go.microsoft.com/fwlink/?LinkId=110367). Still dead, I'm unable to find it on the web. 

@aczechowski What do we do in this scenario? Remove the link?

**Comment by aczechowski** [comment]
Yeah, the target link redirects to https://www.microsoft.com/technet/scriptcenter/topics/htas/part2/answer8.mspx

I don't think it's exactly the same content, but Scripting Guy has some create HTA examples: https://devblogs.microsoft.com/scripting/?s=create+HTA 

The alternative is to just delete that note entirely. Especially the reference to Vista 😮

**Comment by AndrewJNet** [comment]
I like the alternative! I’ll go with that and submit a PR.
