### ISSUE TITLE
Broken Link (microsoft-sql-server-2012-native-client.md)

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1468]
In the following file:
SCCMdocs\sccm\core\misc\eula\microsoft-sql-server-2012-native-client.md

The following link is broken, cannot find alternative:
http://go.microsoft.com/fwlink/?LinkID=231864

**Comment by aczechowski** [comment]
We chased this down and the link was actually inadvertently removed. It's back up now, so I'm closing this issue.
