### ISSUE TITLE
Broken Link (example-deployment-of-pki-certificates)

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1469]
In the file:
SCCMdocs\sccm\core\plan-design\network\example-deployment-of-pki-certificates.md

The following link is broken, could not find alternative:
https://msdn.microsoft.com/library/gg551726.aspx

> [How to Add a Management Certificate to a Windows Azure Subscription](http://go.microsoft.com/fwlink/?LinkId=241722) in the Windows Azure Platform section of the MSDN Library

(admin edit, add source markdown, and metadata for article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c66e3e8a-bd8e-7ae3-aecc-cd9073e2238e
* Version Independent ID: 45572c91-8194-096d-2356-80a9b1b356ef
* Content: [Deployment PKI certificates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/network/example-deployment-of-pki-certificates)
* Content Source: [sccm/core/plan-design/network/example-deployment-of-pki-certificates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/network/example-deployment-of-pki-certificates.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
I searched on the old article title, and it looks like this current article is a good replacement: https://docs.microsoft.com/azure/azure-api-management-certs

(note, make sure to not include a locale like en-us in the URL)

**Comment by aczechowski** [comment]
This is already fixed, now points to https://docs.microsoft.com/azure/cloud-services/cloud-services-configure-ssl-certificate-portal#step-3-upload-a-certificate
