### ISSUE TITLE
Broken Link (Privacy-Statement.md)

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1471]
In File:
SCCMdocs\sccm\core\misc\privacy\privacy-statement.md

The following link is broken, cannot find alternative:
http://go.microsoft.com/fwlink/?LinkID=251808

**Comment by AndrewJNet** [comment]
Since Silverlight has been dropped completely since 1806, should this section be removed? @aczechowski

**Comment by aczechowski** [comment]
Generally I don't allow changes to these articles under core/misc
In this instance, there's some bad redirection going on, it should just go to https://privacy.microsoft.com/privacystatement
You can make that change if you want.

**Comment by ChrisKibble** [comment]
Thank you @aczechowski - PR #1522 submitted.

**Comment by ChrisKibble** [comment]
@AndrewJNet - good idea, maybe put that on the todo list once 1806 goes EOL?
