### ISSUE TITLE
Broken Link (enroll-hybrid-ios-mac.md)

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1472]
In the file:
SCCMdocs\sccm\mdm\deploy-use\enroll-hybrid-ios-mac.md

The following link is broken:
http://go.microsoft.com/fwlink/?LinkId=269844

This links to an Apple site with a specific key, so I'm not sure what it'd be replaced with.

(admin edit, add metadata for article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36fa2425-75b6-781f-1656-92ce0ba456c3
* Version Independent ID: f84126e3-c02e-be32-dc74-da3b8b2d8889
* Content: [Set up iOS and Mac hybrid device management with Microsoft Intune - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/enroll-hybrid-ios-mac)
* Content Source: [sccm/mdm/deploy-use/enroll-hybrid-ios-mac.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/enroll-hybrid-ios-mac.md)
* Product: **configuration-manager**
* Technology: **configmgr-hybrid**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I searched on the link title noted in the article, and it looks like this is a current link: https://identity.apple.com/pushcert

**Comment by ChrisKibble** [comment]
Acknowledged and making the change.
