### ISSUE TITLE
Broken Links (configuration-manager-programming-fundamentals.md)

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1473]
In file:
sccm\develop\core\understand\configuration-manager-programming-fundamentals.md

The following URLs are dead and need to be replaced with new content:

http://go.microsoft.com/fwlink/?linkid=43948
http://go.microsoft.com/fwlink/?linkid=43949

**Comment by aczechowski** [comment]
Well, that's one way to fix it. I removed this file a few weeks ago, it was basically just a TOC
