### ISSUE TITLE
Broken Link (privacy-statement.md)

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1476]
In the file:
SCCMdocs\sccm\core\misc\privacy\privacy-statement.md

The following link is broken:
http://go.microsoft.com/fwlink/p/?LinkId=224911

**Comment by aczechowski** [comment]
This target is probably the best replacement: https://privacy.microsoft.com/privacystatement

**Comment by ChrisKibble** [comment]
Fixing in upcoming PR.
