### ISSUE TITLE
Broken Link (manage-settings-for-software-updates.md)

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1477]
In File:
SCCMdocs\sccm\sum\get-started\manage-settings-for-software-updates.md

The following link is broken:
http://go.microsoft.com/fwlink/p/?LinkId=58313

I could not find a replacement link.

(admin edit: add metadata for article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54216432-726f-0fbb-5001-1c1021320ba9
* Version Independent ID: b39f5e74-541d-de5b-4a93-77f9627775f5
* Content: [Manage settings for software updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/get-started/manage-settings-for-software-updates)
* Content Source: [sccm/sum/get-started/manage-settings-for-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/get-started/manage-settings-for-software-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Looks like this is the best current spot: https://portal.msrc.microsoft.com/

Might be good to mention as a note or tip with this bullet:

```markdown
> [!Note]
> The way Microsoft documents security updates is changing. The previous model used security bulletin webpages and included security bulletin ID numbers (e.g. MS16-XXX) as a pivot point. This form of security update documentation, including bulletin ID numbers, is being retired and replaced with the Security Update Guide. Instead of bulletin IDs, the new guide pivots on vulnerability ID numbers and KB Article ID numbers. For more information, see the [Security Update Guide FAQs](https://www.microsoft.com/msrc/faqs-security-update-guide).
```
