### ISSUE TITLE
Broken Link (samples-guide.md)

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1478]
In File:
SCCMdocs\sccm\mdt\samples-guide.md

This link is broken and I could not find a replacement:
http://msdn.microsoft.com/library/windows/desktop/hh847866.aspx

(admin edit: add metadata for article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc2393d-6a81-c9c9-87bb-b40b66f26d68
* Version Independent ID: fda85f4c-33ec-d0aa-b793-381d2bebb57d
* Content: [MDT Samples - Microsoft Deployment Toolkit](https://docs.microsoft.com/en-us/sccm/mdt/samples-guide)
* Content Source: [sccm/mdt/samples-guide.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdt/samples-guide.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I think the best action here is to remove that entire H4 section (lines 167-180, starting with `####  <a name="LoadMDTSnapInImport"></a> Load the MDT Windows PowerShell Snap-In Using the Import System Modules Task`). There's a note that it's only available in Win7, and that with PoSh v3 it does it automatically. So let's just modernize it by removing it 😄

**Comment by ChrisKibble** [comment]
Incoming PR to make this change...
