### ISSUE TITLE
Broken Link (troubleshoot-endpoint-client.md)

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1479]
In the following file: 
SCCMdocs\sccm\protect\deploy-use\troubleshoot-endpoint-client.md 

The following link is broken:
http://www.microsoft.com/en-ph/security_essentials/Support/8c9074b6-1558-4d14-bc39-d294ced11096.aspx

(admin edit: add metadata for link to article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 940822dc-f344-a2ee-b63d-bc65e2705584
* Version Independent ID: 1f85b90e-b13f-f89f-99e9-d0e11d1fab1e
* Content: [Troubleshooting Windows Defender or Endpoint Protection client - Configuration Manager](https://docs.microsoft.com/en-us/sccm/protect/deploy-use/troubleshoot-endpoint-client)
* Content Source: [sccm/protect/deploy-use/troubleshoot-endpoint-client.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/troubleshoot-endpoint-client.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
I think the best new target is https://support.microsoft.com/supportforbusiness/productselection, but that note needs some rewording, here's my suggestion:

```markdown
> [!CAUTION]  
> When you remove security programs, your computer is unprotected. If you have problems installing Windows Defender after you remove existing security programs, contact [Microsoft Support](https://support.microsoft.com/supportforbusiness/productselection) for **Windows Defender** in the **Security** product family.  
```

**Comment by ChrisKibble** [comment]
That's @aczechowski - looks good, I'll make the update.
