### ISSUE TITLE
Broken Link (user-driven-installation-developers-guide.md)

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1480]
In the following file:
C:\Users\chris\SCCMdocs\sccm\mdt\user-driven-installation-developers-guide.md

The following links are broken:
http://www.microsoft.com/visualstudio/products/2010-editions

(admin edit: adding metadata for article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b8ccfad-d059-783f-4384-b5c5c5a4f493
* Version Independent ID: bbc0603d-eb09-66d6-4888-5dfc0d226454
* Content: [User driven installation - Microsoft Deployment Toolkit](https://docs.microsoft.com/en-us/sccm/mdt/user-driven-installation-developers-guide)
* Content Source: [sccm/mdt/user-driven-installation-developers-guide.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdt/user-driven-installation-developers-guide.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
There are two instances of this link, on lines 89 and 101. I suggest switching it to just http://docs.microsoft.com/visualstudio (make sure to not include the locale such as en-us in the markdown URL)
