### ISSUE TITLE
Broken Link (whats-new-in-hybrid-mobile-device-management.md)

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1482]
The file:
SCCMdocs\sccm\mdm\understand\whats-new-in-hybrid-mobile-device-management.md

Includes the following broken link that should be corrected:
https://docs.microsoft.com/intune/intune-user-help/sync-your-device-manually-windows#sync-from-device-taskbar-or-start-menu

(admin edit: add metadata for article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09aaf204-6890-76e6-a0fe-e246847c893f
* Version Independent ID: 421111f1-df75-f692-aaeb-e6b5ecfdfe2d
* Content: [What's new in hybrid MDM - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management)
* Content Source: [sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/understand/whats-new-in-hybrid-mobile-device-management.md)
* Product: **configuration-manager**
* Technology: **configmgr-hybrid**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
An easy fix, just drop the first "intune/" from the path, for example:

https://docs.microsoft.com/intune-user-help/sync-your-device-manually-windows#sync-from-device-taskbar-or-start-menu

**Comment by ChrisKibble** [comment]
@aczechowski - this was fixed in commit 711153c976c3fa3f53d1e99aeef3f7d819ac9461 (not by me) and can be closed.
