### ISSUE TITLE
Broken Link (monitor-windows-analytics.md)

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1486]
The file:
SCCMdocs\sccm\core\clients\manage\monitor-windows-analytics.md

Contains the following broken link:
https://docs.microsoft.com/previous-versions/windows/internet-explorer/ie-developer/platform-apis/ms537183

**Comment by AndrewJNet** [comment]
This appears to be fixed in the source doc. Correct link:
https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/ms537183(v=vs.85)

I think this can be closed @aczechowski

**Comment by aczechowski** [comment]
Right, the URL doesn't work when viewed in markdown, but it works ok when published. See my longer explanation on #1485  😄 
Closing this issue.
