### ISSUE TITLE
Broken Link (enroll-devices.md)

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1487]
The File:
SCCMdocs\sccm\desktop-analytics\enroll-devices.md 

Contains the following broken link:
https://docs.microsoft.com/previous-versions/windows/it-pro/windows-7/ee126127

**Comment by AndrewJNet** [comment]
This appears to be fixed in the source doc. Correct link:

https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-7/ee126127(v=ws.10)

I think this can be closed @aczechowski

**Comment by aczechowski** [comment]
Same reason as #1486 , closing 😄
