### ISSUE TITLE
Broken Links (upgrade-on-premises-infrastructure.md)

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/SCCMdocs#1488]
The File:
SCCMdocs\sccm\core\servers\manage\upgrade-on-premises-infrastructure.md

Contains the following broken links:
https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn303416
https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh852345

**Comment by AndrewJNet** [comment]
These appear to be working now. Correct links in the doc:

https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn303416(v=ws.11)

https://docs.microsoft.com/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh852345(v=ws.11)#new-and-changed-functionality

If someone wants to confirm, I think this can be closed @aczechowski

**Comment by aczechowski** [comment]
Yep, links work ok from published article, closing
