### ISSUE TITLE
Can you show steps on how to do this with just intune, no sccm, such as in 365 business?

### ISSUE THREAD

**Issue by gkens** [MicrosoftDocs/SCCMdocs#1505]
Can you show steps on how to do this with just intune, no sccm, such as in 365 business?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bed718c9-fa4d-d78e-3be2-fbc390a80406
* Version Independent ID: cd67f1d8-70a9-1a70-4d8f-1a8063aa0857
* Content: [Windows Autopilot for existing devices - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/windows-autopilot-for-existing-devices#feedback)
* Content Source: [sccm/osd/deploy-use/windows-autopilot-for-existing-devices.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/windows-autopilot-for-existing-devices.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @gkens for the feedback. That would be a good link to add to the Next Steps section:

```markdown
- [Enroll Windows devices in Intune by using the Windows Autopilot](https://docs.microsoft.com/intune/enrollment-autopilot)
```

**Comment by aczechowski** [comment]
I made this change, it will publish live tomorrow
