### ISSUE TITLE
DEM

### ISSUE THREAD

**Issue by nickekallen** [MicrosoftDocs/SCCMdocs#1513]
There is some uncertaintity regarding devices enrolled using DEM. If those are migrated - will devices migrate successfully?

Should support - as stated - be contacted before the switch to Intune Standalone, or before the cut is made?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4913cd11-dd09-791f-af96-9849efa08ef9
* Version Independent ID: 4e271b5d-8d9f-7837-867e-1fc1fffd3242
* Content: [Change the MDM authority - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/migrate-mixed-authority#feedback)
* Content Source: [sccm/mdm/deploy-use/migrate-mixed-authority.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/migrate-mixed-authority.md)
* Product: **configuration-manager**
* Technology: **configmgr-hybrid**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @nickekallen for the feedback. I'm checking with the feature team for more information.

**Comment by nickekallen** [comment]
Response from Support;



As discussed over call, please don’t migrate or remove the DEM user accounts from Intune Subscription collection in SCCM. When the subscription is deleted and change the MDM authority to Intune standalone the devices enrolled by DEM automatically migrates to standalone Intune.



In case if we remove the DEM user from the subscription collection, the user will lose the ability of DEM role and only 15 devices/max devices limit set in restrictions will be migrated to standalone Intune. Rest of the devices should be reenrolled after adding the user as DEM account in Intune standalone.

Snippet from document.



________________________________

**Comment by aczechowski** [comment]
In discussing with the feature team, what is in the article (and mentioned by support) holds true:

- As long as you aren't migrating your DEM user accounts before switching to Intune as their MDM authority, you don't need to call support. 
- Only if you migrate your DEM user account before the tenant level MDM authority switch, support should be reached out to migrate the associated devices.

**Comment by Denjiki** [comment]
@nickekallen @aczechowski Thank you for your help with this! I was assuming I had to contact support to migrate my DEM-enrolled devices as well. Thanks to you, I no longer have to wait for Microsoft to answer my 3 separate support tickets (they failed to respond to any of them over a long period).

**Comment by aczechowski** [comment]
We discontinued the hybrid MDM service in September 2019. For more information, see the main [hybrid MDM](https://docs.microsoft.com/sccm/mdm/understand/hybrid-mobile-device-management) article. We plan to completely retire the documentation in a couple of months. Since we're no longer maintaining this content, I'm closing this issue.
