### ISSUE TITLE
Visual c++ redistributable no longer supported.

### ISSUE THREAD

**Issue by AquinoN** [MicrosoftDocs/SCCMdocs#1526]
At MMS, and Product team indicated that c++ runtime is required and supported but the redistributable is not being installed. 

Doc says redistributable is required. 2013 c++ redistributable is no longer supported. 

https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6058d56b-cad2-e63a-4a23-f9289a83ea39
* Version Independent ID: eb53e852-4eed-680e-6746-64029244f70e
* Content: [Windows client deployment prerequisites - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/deploy/prerequisites-for-deploying-clients-to-windows-computers#feedback)
* Content Source: [sccm/core/clients/deploy/prerequisites-for-deploying-clients-to-windows-computers.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/prerequisites-for-deploying-clients-to-windows-computers.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @AquinoN, I'm checking with the engineering team to clarify. Stay tuned.

**Comment by aczechowski** [comment]
I made a change for this, it should publish live tomorrow.
The current version of VCRedist 2013 that we're using in ConfigMgr version 2002 is supported at the time of release.
