### ISSUE TITLE
Support for 'Windows 10 Enterprise 2019 LTSB' 

### ISSUE THREAD

**Issue by hishono** [MicrosoftDocs/SCCMdocs#1527]
Hi Experts,

My customers have a plan to manage 'Windows 10 Enterprise  2019 LTSB' at SCCM LTSB 1606.
Is the 'Windows 10 Enterprise  2019 LTSB' supported at SCCM LTSB 1606?
 
Public information is not included in  'Windows 10 Enterprise  2019 LTSB'.
https://docs.microsoft.com/en-us/sccm/core/understand/supported-configurations-for-ltsb#client-management 
 
Also, is the domain functional level of "Windows Server2016" supported?
 
https://docs.microsoft.com/en-us/sccm/core/understand/supported-configurations-for-ltsb#support-for-active-directory-domains
 
Best,
Hirohito

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f2052d9-969f-257c-fcc3-8239c210401f
* Version Independent ID: 4cd87f51-eb47-26df-b64f-987bce82042a
* Content: [Supported Configurations for the LTSB  - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/understand/supported-configurations-for-ltsb#feedback)
* Content Source: [sccm/core/understand/supported-configurations-for-ltsb.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/supported-configurations-for-ltsb.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
@hishono, the following statements are at the top of this article:

> Additionally, products and product versions that are not listed in the following topics are not supported unless they have been announced on the Enterprise Mobility + Security Blog.
>
> Limitations for future support: The LTSB has limited support for future server and client operating systems and product dependencies. The platforms list for the LTSB is fixed for the life of the release

You should also review [Which branch of Configuration Manager should I use?](https://docs.microsoft.com/sccm/core/understand/which-branch-should-i-use). 

The current branch provides support for newer OS platforms, and recommended for most customers. The LTSB is intended for customers who allow Software Assurance or equivalent subscription rights to expire. For more information, see [Frequently asked questions for Configuration Manager branches and licensing](https://docs.microsoft.com/sccm/core/understand/product-and-licensing-faq).

**Comment by hishono** [comment]
Thanks for the answer.

I understand.
I was able to answer  to my customers!!

Thanks,
Hirohito
