### ISSUE TITLE
Inconsistent documentation and SCCM console for boundary group options

### ISSUE THREAD

**Issue by WolfgangSauer** [MicrosoftDocs/SCCMdocs#1529]
The documentation here https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/boundary-groups#bkmk_bgoptions4 talks about "Prefer cloud **distribution points** over distribution points". The actual GUI in 1902 says "Prefer **cloud based sources** over on-premise sources". Has the meaning of this option changed in 1902 or is just refering to DPs as documented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7db5025d-eff5-5acb-dd57-0895828e1657
* Version Independent ID: 1b5e1df8-e30a-6eef-b5c6-5f3a4c89131c
* Content: [Configure boundary groups - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/boundary-groups#feedback)
* Content Source: [sccm/core/servers/deploy/configure/boundary-groups.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/boundary-groups.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @WolfgangSauer for the feedback. I'm confirming with the feature team.

**Comment by aczechowski** [comment]
This issue is closed because I made a change to the articles to address this feedback. The updated articles should publish live in the next hour.
