### ISSUE TITLE
Typo in RFC for TFTP

### ISSUE THREAD

**Issue by jowiswel** [MicrosoftDocs/SCCMdocs#1532]
In note 4 (https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/ports#bkmk_note4) the correct RFC for TFTP is 1350, not 350.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f658ee4b-d051-0d7c-4656-19a846908469
* Version Independent ID: 3478e881-199c-f0c4-b218-0dd609eb0427
* Content: [Ports used for connections - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/ports#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/ports.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/ports.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks to @FrankRoj for fixing this issue. The change should publish live tomorrow (Tuesday, 14 May) around 11:00 Pacific time. I'm closing this issue.
