### ISSUE TITLE
Typo under "Existing Configuration Manager server components on server"

### ISSUE THREAD

**Issue by somebum** [MicrosoftDocs/SCCMdocs#1538]
Is:
A site server or site system role isn't already installed on the server selected for site installation.
Should be:
A site server or site system role is already installed on the...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db678f94-700f-ad35-9fdc-d165893b5373
* Version Independent ID: 2ee761db-4b3b-6fa0-c195-ad85ebbac70d
* Content: [Prerequisite checks - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/list-of-prerequisite-checks#feedback)
* Content Source: [sccm/core/servers/deploy/install/list-of-prerequisite-checks.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/list-of-prerequisite-checks.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
I think the intent for these checks is that the description is of the success case. Which in this case, "isn't" is correct. The check succeeds if there isn't any components. 

So I'm going to close this issue. If you're passionate about further clarity, reopen the issue, and we can look at how to make that more clear. The catch is that we'll need to adjust all of the rules accordingly to be consistent, which is time consuming.
