### ISSUE TITLE
ICBM and CMG together for the same primary site?

### ISSUE THREAD

**Issue by irfan-fakih** [MicrosoftDocs/SCCMdocs#1541]
Hello,

Can a single SCCM Site be configured for both - Internet-Based Client Management (IBCM) and also Cloud Management Gateway (CMG)?  

Because we already have IBCM configured on our single primary site to manage only all servers in DMZ network.  All these servers do not have Internet connection (for security).  Now, to manage laptops that are on the Internet, we want to use CMG, so can we configure our primary site for CMG implementation?

Is this supported by Microsoft or can this be even implemented?

Your feedback will be valuable. 

(admin edit: add metadata to link article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ef9884b-385c-a5c1-7449-43d3fff9d84d
* Version Independent ID: 6b0135c4-bd5e-fa24-9528-8d24a4604f01
* Content: [Manage clients on the internet - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/manage-clients-internet)
* Content Source: [sccm/core/clients/manage/manage-clients-internet.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/manage-clients-internet.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @irfan-fakih for the feedback. I need to confirm with the engineering team.

**Comment by aczechowski** [comment]
If a device gets policy from the site for both IBCM and CMG, then it randomizes between them for communication. 

If your DMZ clients can't access the CMG (no internet access) and the HTTPS MP in the DMZ isn't exposed to the internet (not really IBCM), then internet-based clients should only use the CMG.

I'll keep this issue open to include a note about this topic in this article. But I suggest you may also want to file [product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) as well.

**Comment by irfan-fakih** [comment]
Thank you Aaron Czechowski on following up on this issue.

Here are some observations based on my ConfigMgr CB 1810 version environment with 20,000 Windows workstations & 3000+ Windows Servers & 200+ servers in DMZ.

Your Response:  “If a device gets policy from the site for both IBCM and CMG, then it randomizes between them for communication.”
My feedback:  Correct, Within a single Site, I had seen this behavior on 200+ IBCM configured servers in our DMZ.

Your Response:  “If your DMZ clients can't access the CMG (no internet access) and the HTTPS MP in the DMZ isn't exposed to the internet (not really IBCM), then internet-based clients should only use the CMG.”
My feedback:  Correct, all our 2000+ Internet based laptops (running SCCM Clients) are using only CMG extensively and accordingly, we see all statistics on the CMG report (Good).  But, on the 200 servers in DMZ, we see random site-system names selection (IBCM or CMG, as you said).  So, for those Servers in DMZ (with no Internet connection) where it selects CMG, it is a big problem now because the SCCM Client on those DMZ servers goes dormant after a while (my observation), nothing happens on these servers.  For these specific DMZ servers, I can confirm this by periodically looking from Control Panel -> ConfigMgr applet, -> Network Tab, and I can see the CMG server FQDN name under IBCM MP field staying there forever.  Hence, going forward, any SCCM operations (patching, etc.) do not work on these DMZ servers.

Another thought:
In order to resolve this issue and in consideration of my ConfigMgr environment (which is currently just single primary site), I thought about creating a secondary site in DMZ based on HTTPS.  Then, I can install the SCCM client (as IBCM) on all 200+ DMZ Servers reporting to this newly created secondary site (with new sitecode).  While the primary site is still remains HTTP taking care of 20,000 Windows workstations & 3000+ Windows Servers.  And I will leave the existing CMG on the primary site for the laptops.

Will this work? Is IBCM configuration (not real IBCM) supported on secondary site?  Will this scenario be supported by Microsoft?

Your feedback/advice will be helpful.

Irfan.Fakih@hotmail.com<mailto:Irfan.Fakih@hotmail.com>
Mobile#: 1-908-295-8271.

**Comment by aczechowski** [comment]
Thanks @irfan-fakih for the followup. Although it's quickly surpassed the scope of what we can provide here. As I previously mentioned, you could try filing product feedback to suggest a better way of handling this scenario built into the product. 

As for the alternative process you propose, I suggest one of the following options to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
