### ISSUE TITLE
ADK - 19H1 - Known Issues Section (ADK 10.0.18362.1 + KB4497936 18362.113)

### ISSUE THREAD

**Issue by NeoBeum** [MicrosoftDocs/SCCMdocs#1542]
ADK 1903 DISM errors with May 2019 LCU KB4497936
SCCM will be affected as ADK DISM is universal for Deployment Scenarios.

Working Image is unmounted, however Add-Package continues operation using Host System Registry Hive. DISM operation should cease when image unmount is detected.

Pastebin logs linked in the following issue:
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/3699 

```
PS E:\WinROG> DISM /Mount-Image /ImageFile:winre.wim /Index:1 /MountDir:mount\RE                                                                                                                                                             
Deployment Image Servicing and Management tool
Version: 10.0.18362.1

Mounting image
[==========================100.0%==========================]
The operation completed successfully.
PS E:\WinROG> DISM /Image:mount\RE /Add-Package /PackagePath:"\\Nb-domain-hq\hq-hdd\1903\2019-05\windows10.0-kb4500109-x64_b727d70aacc30ac3522c02b285164d908e818ad6.msu"                                                                     
Deployment Image Servicing and Management tool
Version: 10.0.18362.1

Image Version: 10.0.18362.30

Processing 1 of 1 - Adding package \\Nb-domain-hq\hq-hdd\1903\2019-05\windows10.0-kb4500109-x64_b727d70aacc30ac3522c02b285164d908e818ad6.msu
[==========================100.0%==========================]
The operation completed successfully.
PS E:\WinROG> DISM /Image:E:\WinROG\mount\RE /Add-Package /PackagePath:"E:\WinROG\windows10.0-kb4497936-x64_4ac9328bb1376d2cadb09f56ba95ac9b08b88fba.msu"                                                                                    
Deployment Image Servicing and Management tool
Version: 10.0.18362.1

Image Version: 10.0.18362.30

Processing 1 of 1 - Adding package E:\WinROG\windows10.0-kb4497936-x64_4ac9328bb1376d2cadb09f56ba95ac9b08b88fba.msu
[==========================100.0%==========================]
E:\WinROG\windows10.0-kb4497936-x64_4ac9328bb1376d2cadb09f56ba95ac9b08b88fba.msu: An error occurred applying the Unattend.xml file from the .msu package.
For more information, review the log file.
 Error: 0x80070002

Error: 2

The system cannot find the file specified.

The DISM log file can be found at C:\WINDOWS\Logs\DISM\dism.log

PS E:\WinROG> DISM /Image:E:\WinROG\mount\RE /Add-Package /PackagePath:"E:\WinROG\windows10.0-kb4497936-x64_4ac9328bb1376d2cadb09f56ba95ac9b08b88fba.msu"                                                                                    
Deployment Image Servicing and Management tool
Version: 10.0.18362.1


Error: 50

DISM does not support servicing a Windows Vista RTM or earlier operating system.
If the operating system is supported check that SSShim.DLL is present.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc732ec0-eb14-8da2-7688-dd74a72cdae5
* Version Independent ID: a93682ff-2984-38e0-5a0d-6f77c1c9e5db
* Content: [Support for Windows 10 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/support-for-windows-10#feedback)
* Content Source: [sccm/core/plan-design/configs/support-for-windows-10.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/support-for-windows-10.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by NeoBeum** [comment]
It's not really a fixable thing from my end - as one of the components for WinPE is working properly, or the ADK itself.

I sent a tweet to @robdotyork 
I don't really know where ADK belongs, as there's no direct channel for it and falls in many categories.
Especially because the 1903 ADK is still released as a preview build iso.

However thank you.
