### ISSUE TITLE
DeviceManageabilityCSP issue for ConfigMgr clients

### ISSUE THREAD

**Issue by PrinceMarkieD** [MicrosoftDocs/SCCMdocs#1546]
We pre-provision devices with SCCM and then enroll them in Intune manually. How can we stop ConfigMgr from making itself the MDM in the registry of a device that just completed a task sequence. The ConfigMgr client has to be scrubbed and the DeviceManageabilityCSP registry key deleted, or the enrolled devices show up as "See/ConfigMgr" in Intune, and are not manageable. We do not do co-management or hybrid join. 
Is there a way to stop SCCM from making itself the MDM Authority even though we have no connector setup, and no co-management.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b82df45-3900-c15c-5838-6983b6a862f5
* Version Independent ID: 86ff67a2-f224-096b-7905-ec5d6523c4bd
* Content: [Change your MDM authority to Intune - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/migrate-change-mdm-authority)
* Content Source: [sccm/mdm/deploy-use/migrate-change-mdm-authority.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/migrate-change-mdm-authority.md)
* Product: **configuration-manager**
* Technology: **configmgr-hybrid**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @PrinceMarkieD for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

Note: Version 1806 + hotfix or 1810 should not have this issue.

**Comment by PrinceMarkieD** [comment]
Thank you, we are on 1810 and still see the issue with the Piloting client. Maybe on 1902 we will not. we are going 1902 tonight. Thanks.

**Comment by aczechowski** [comment]
If you're still seeing the issue, please file a frown or open a case with support.
