### ISSUE TITLE
Cost Calculator

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/SCCMdocs#1548]
Can we get a one stop calculator designed specifically for 'cloud management gateway'?  Currently as I read i have to use three different calculators.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778368d0-1054-678c-4d74-5dce1b5826c8
* Version Independent ID: aaac7308-66e6-66f0-8248-14e1505c11a6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/plan-cloud-management-gateway)
* Content Source: [sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Barleyologist for sharing this feedback. Not really for docs, as we document what the product provides. If you want to share product feedback, you can select the **This product** option in the Feedback section of the article, or see [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback).

In this specific instance, this feature is already in the works. 😄 For more information, see [Cloud services cost estimator](https://docs.microsoft.com/sccm/core/get-started/2019/technical-preview-1903#bkmk_cmg) from technical preview branch version 1903.

I'm closing this issue as there's nothing actionable for docs at this time.
