### ISSUE TITLE
Questions regarding Licensing for SCCM

### ISSUE THREAD

**Issue by AndySanchezVM** [MicrosoftDocs/SCCMdocs#1549]
1. Can SCCM be licensed via CSP? I see a footnote in EM+S E3 regarding SCCM but it is not clear. Can my customer purchase an EM+S E3 license via CSP and it be used for SCCM?
2. Also, is one SCCM license required for each server being used per site? or can we use one server as a distribution point for the additional sites? and are there any bandwidth limitations by using one site?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b91889c-f6ad-7c70-9af9-404217959982
* Version Independent ID: bbb6de08-1b45-73b5-585f-3c460b359c22
* Content: [Learn More about licensing and branches - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/understand/learn-more-editions)
* Content Source: [sccm/core/understand/learn-more-editions.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/learn-more-editions.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @AndySanchezVM 

A few additional resources that should help:
- [Frequently asked questions for Configuration Manager branches and licensing](https://docs.microsoft.com/sccm/core/understand/product-and-licensing-faq)
- [Product terms](https://www.microsoft.com/licensing/product-licensing/products)
    - [Direct link to English product terms doc](http://www.microsoftvolumelicensing.com/Downloader.aspx?documenttype=PT&lang=English)

Realistically for licensing questions you should discuss with your Microsoft account team or from where ever you get your licensing.

Some of the questions in your second are more implementation design questions, which would be dependent upon your specific environment. 

There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to open an advisory case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
