### ISSUE TITLE
Pre-cache content wording

### ISSUE THREAD

**Issue by jeffdfield** [MicrosoftDocs/SCCMdocs#1570]
"When there's more than one package, Configuration Manager adds a numerical suffix to the variable name. For example, if you specify %mycontent% as a custom variable" Shouldn't be there. SCCM always adds a numerical value regardless if there is more than one. The wording is correct in the SCCM console task sequence editor.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfe3442-b59d-0d77-d9af-f18e787ec99d
* Version Independent ID: 60cb54a2-d1fd-92b5-b027-de8a85c7af64
* Content: [Create an OS upgrade task sequence - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system#feedback)
* Content Source: [sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jeffdfield for the feedback. I just submitted a change to remove the leading clause "when there's more than one package". It should make daily publishing today, around 11am Pacific. I'm closing this issue.
