### ISSUE TITLE
Windows 1809 not 1810

### ISSUE THREAD

**Issue by SasStu** [MicrosoftDocs/SCCMdocs#1576]
In the Prerequisites section part about Windows Defender Application Guard file trust criteria Windows 10 1810 is mentioned 1809 should be correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e01e1f4e-9da8-331c-4a4b-74480571a37a
* Version Independent ID: 7933dc64-42dd-1e13-73d1-010bc02124fd
* Content: [Technical preview 1905 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/2019/technical-preview-1905)
* Content Source: [sccm/core/get-started/2019/technical-preview-1905.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/2019/technical-preview-1905.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @SasStu for catching that. I've submitted a change that should publish in the next hour or so. 😄 
I'm closing this issue.

**Comment by aczechowski** [comment]
FYI, there's a GitHub outage right now that's impacting our ability to publish. The revision for this is in-flight, publishing timeline is TBD.
