### ISSUE TITLE
word missing

### ISSUE THREAD

**Issue by ISSC-Workplace** [MicrosoftDocs/SCCMdocs#1577]
"When content is missing for a software update in a deployment created at a parent site, the software update needs to [BE ??] replicated or redistributed to the child site."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 524deab5-2856-c816-c1be-c93ee71910a6
* Version Independent ID: eb9d7d68-a321-c33f-41b7-fe370d15d806
* Content: [Icons used for software updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/understand/software-updates-icons#feedback)
* Content Source: [sccm/sum/understand/software-updates-icons.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/understand/software-updates-icons.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @ISSC-Workplace for catching that. If you'd like to submit the change yourself, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute). 😉 

I suggest changing it to a more active voice: 
> When content is missing for a software update in a deployment created at a parent site, you need to replicate or redistribute the software update to the child site.

**Comment by mestew** [comment]
I made this change while I happened to be in the article.
