### ISSUE TITLE
v_ClientDeploymentState questions

### ISSUE THREAD

**Issue by slkissinger** [MicrosoftDocs/SCCMdocs#1578]
in the view v_ClientDeploymentState, there are other date/time fields other than 'LastMessageTime', which the documentation currently states is "The LastMessageStateID column contains the state ID for topic type 800".  Could you describe what the other date/time fields represent?
Thanks, 
Sherry Kissinger

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5697f065-d903-1afe-5537-fcacaee983a2
* Version Independent ID: 41088c64-826d-6843-c735-d4464a10ff07
* Content: [Client deployment views - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/core/understand/sqlviews/client-deployment-views-configuration-manager#feedback)
* Content Source: [sccm/develop/core/understand/sqlviews/client-deployment-views-configuration-manager.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/core/understand/sqlviews/client-deployment-views-configuration-manager.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @slkissinger for the question. I checked with engineering and received some additional information that may help answer your question. 

Note: We unfortunately have a large backlog of work for the PowerShell & SDK content, but are looking at ways to improve it in the future. If you'd like to submit a change for this issue, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute).

**DeploymentBeginTime**: The last message time when the message’s state id is STATE_STATEID_CLIENT_DEPLOYMENT_STARTED (100), telling the server deployment starts. It clears the DeploymentEndTime time

**DeploymentEndTime**: The last message time when the state id is
STATE_STATEID_CLIENT_DEPLOYMENT_SUCCEEDED (400) or STATE_STATEID_CLIENT_DEPLOYMENT_SUCCEEDED_REBOOT_SUCCEEDED(401). Telling the server the deployment ends.

**AssignmentBeginTime**: Similarly, it’s the time when getting state id STATE_STATEID_CLIENT_ASSIGNMENT_STARTED (500)

**AssignmentEndTime**: It’s the time that the assignment was done with id STATE_STATEID_CLIENT_ASSIGNMENT_SUCCEEDED (700)

**Comment by aczechowski** [comment]
I added these to this article, it should publish live tomorrow.
