### ISSUE TITLE
IIS is prereq for admin service

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#1579]
Every provider attempts to install the admin service. Admin service has a dependency on IIS to bind a cert to https port 443. Either SCCM does the binding in EHTTP mode or admin does it out of band using PKI cert, a cert is required. We use IIS APIs to check whether binding is done already or we have to do binding using our SCCM-generated cert in EHTTP mode. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 070c2bc6-3086-7237-d19c-951f000b4531
* Version Independent ID: 95c62945-77dc-0ce0-e4ee-1116343b7ea6
* Content: [Plan for the SMS Provider - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/plan-for-the-sms-provider#installation-prerequisites)
* Content Source: [sccm/core/plan-design/hierarchy/plan-for-the-sms-provider.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/plan-for-the-sms-provider.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by jpcast88** [comment]
@aczechowski I'm thinking we can add it under this section (/sccm/core/plan-design/hierarchy/plan-for-the-sms-provider#installation-prerequisites), but does it need to specify the IIS configuration similar to this? https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/site-and-site-system-prerequisites#iis-configuration

Also, we would probably need to update this section as well?
https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/site-and-site-system-prerequisites#bkmk_2012smsprovpreq

**Comment by aczechowski** [comment]
Thanks @jpcast88, yes for both article references. Let me check on the IIS config.

**Comment by aczechowski** [comment]
you just have to enable the feature, but none of the subcomponents or services need to be enabled.

**Comment by jpcast88** [comment]
@aczechowski Gotcha, thanks for the update...I'll work on submitting a PR for these changes.
