### ISSUE TITLE
What is CDNBaseUrl for Insider (Fast) ?

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/SCCMdocs#1580]
When using Insider (Fast) , what is CDNBaseUrl ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1da48af-4783-bd17-67f3-f265df93503f
* Version Independent ID: 17432b22-04cb-f47f-1634-e5b7fc99c37d
* Content: [Manage Office 365 ProPlus updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/manage-office-365-proplus-updates#change-the-update-channel-after-you-enable-office-365-clients-to-receive-updates-from-configuration-manager)
* Content Source: [sccm/sum/deploy-use/manage-office-365-proplus-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/manage-office-365-proplus-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by stdin82** [comment]
http://officecdn.microsoft.com/pr/5440fd1f-7ecb-4221-8110-145efaa6372f

**Comment by hkusulja** [comment]
@stdin82  thank you, that is it and fully working, it would be nice to update documentation with this link also

**Comment by ChrisKibble** [comment]
Don't see this on any official MS doc, but it seems pretty widely documented on 3rd party sites.  I'll update and submit a PR.

**Comment by aczechowski** [comment]
Thanks all for the discussion and feedback. A few notes:

- We're working with the Office team on totally rewriting this content. 😄 
- Insider Fast isn't a supported build
- We don't want you making these edits in the registry. Changing channels isn't as simple as changing one registry key. You should use group policy or the Office Deployment Tool to change the update channel.

So I'm actually going to close this issue, as there's nothing actionable for docs.

**Comment by hkusulja** [comment]
@aczechowski - not all types of office desktops have ability to use group policy or office deployment tool, so SCCM, Intune, and registry options are also needed to change branch. Also registry information I got from offical support ticket to change branche.
Event if "Fast Insider" branch is not production supported build, it exists and should be documented as an option, since it is not so clear on https://insider.office.com/en-us/join , which redirects "to your local admin" which needs to reference official documentation about this.
Also, any ETA on new docs content?
