### ISSUE TITLE
Co-management link

### ISSUE THREAD

**Issue by James-MCT** [MicrosoftDocs/SCCMdocs#1583]
The link "Co-management with Microsoft Intune" returns to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6f96bb1-5fb9-6086-335f-e5069313d9cf
* Version Independent ID: 4b3a73cd-07e6-9999-abae-26168f0dfa1e
* Content: [Choose a device management solution - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/choose-a-device-management-solution#feedback)
* Content Source: [sccm/core/plan-design/choose-a-device-management-solution.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/choose-a-device-management-solution.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by ChrisKibble** [comment]
Looks like all four of those links point to the same page, but with bookmarks that bring you to that section of the page.  The bookmark in the link is **bkmk_intune**, but the actual bookmark (anchor) is **bkmk_comanage**.  

I've updated the link and left the bookmark as is (in case other pages are referencing this existing bookmark).  Submitted PR for review.

**Comment by aczechowski** [comment]
Thanks @James-MCT for catching this, and thanks @ChrisKibble for submitting the fix. It should go live with the next daily publishing process on Tuesday, May 28 (due to the US holiday on Monday). I'm closing this issue.
