### ISSUE TITLE
More Information On Errors

### ISSUE THREAD

**Issue by matrixtushar** [MicrosoftDocs/SCCMdocs#1587]
It would be really beneficial if more information is added on the errors. While using the tool I faced an error that mentioned "Array Dimension Exceeded after downloading a few cab files. There was nowhere on the internet I could find help with such an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a116b8a6-3c73-0b7d-56f3-c83b1d901565
* Version Independent ID: bd78266e-abaa-1515-c02f-a5b230d94955
* Content: [Service Connection Tool - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/use-the-service-connection-tool#feedback)
* Content Source: [sccm/core/servers/manage/use-the-service-connection-tool.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/use-the-service-connection-tool.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @matrixtushar for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'll keep the issue open and we'll check with the engineering team if there are common errors that we can include for troubleshooting purposes. But I suspect it will be difficult to document every error, as some may be environmental or situational.

**Comment by aczechowski** [comment]
Thanks again @matrixtushar for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
