### ISSUE TITLE
Device Configuration slider

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/SCCMdocs#1589]
@edr1986 commented on [Thu May 23 2019](https://github.com/MicrosoftDocs/SCCMDocs.nl-nl/issues/4)

Does the Device Configuration slider also includes the Antimalware policies? This is a bit confusing because in ConfigMgr this is below Endpoint Protection. I know the Antimalware policies are not included in the Endpoint Protection slider

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 70ebc3e6-359e-3067-3cfd-149052df1123
* Version Independent ID: 723165f6-6bfa-ed78-fbda-23c12bc07b9d
* Content: [Workloads voor CO-beheer - Configuration Manager](https://docs.microsoft.com/nl-nl/sccm/comanage/workloads)
* Content Source: [sccm/comanage/workloads.md](https://github.com/Microsoft/SCCMDocs.nl-nl/blob/live/sccm/comanage/workloads.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

---

@CeciAc commented on [Thu May 23 2019](https://github.com/MicrosoftDocs/SCCMDocs.nl-nl/issues/4#issuecomment-495312190)

Hello, @edr1986 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

---

@aczechowski commented on [Thu May 23 2019](https://github.com/MicrosoftDocs/SCCMDocs.nl-nl/issues/4#issuecomment-495313345)

@CeciAc - I think there may be something we need to clarify in the docs here. Can you please move/clone this over to MicrosoftDocs/SCCMDocs and I'll followup?

---

@aczechowski commented on [Fri May 24 2019](https://github.com/MicrosoftDocs/SCCMDocs.nl-nl/issues/4#issuecomment-495713917)

@edr1986 to answer your question, antimalware policies are a part of the Endpoint Protection workload. When you switch, the SCCM policies are retained on the device until the Intune policies overwrite. This behavior makes sure that the device still has protection policies in the interim. EP is a part of Device Configuration, so the same behavior applies when you switch the DC workload. I'll work on clarifying this point in the en-us article (which will take some time to localize to nl-nl).

---

@aczechowski commented on [Fri May 24 2019](https://github.com/MicrosoftDocs/SCCMDocs.nl-nl/issues/4#issuecomment-495722261)

@edr1986 I'm submitting a change to the article that I hope will sneak in for today's daily publishing process in a few minutes. If my note above still doesn't address your feedback, please reopen this issue or file another.

---

@edr1986 commented on [Fri May 24 2019](https://github.com/MicrosoftDocs/SCCMDocs.nl-nl/issues/4#issuecomment-495751372)

@aczechowski thank you! Clear to me

**Comment by CeciAc** [comment]
Hi @aczechowski
Sorry for the delay, my PC's drive was reset and I just saw the notification for this issue.
best regards

**Comment by aczechowski** [comment]
Fixed by MicrosoftDocs/SCCMDocs-pr#3801
Closing
