### ISSUE TITLE
Delete Aged Delete Detection Data

### ISSUE THREAD

**Issue by BritV8** [MicrosoftDocs/SCCMdocs#1590]
"By default, Extraction Views are disabled. You only enable them by using the Configuration Manager SDK. Unless Extraction Views are enabled, there is no data for this task to delete."
I believe this is incorrect. I did and update from 1703 to 1810 over a weekend and the Extraction Views were created over that weekend. Thats the SCCM_Ext.vex* views we are talking about?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73746b8f-0bb3-a02c-fe91-85395fb33bdd
* Version Independent ID: a7cee2bc-0b6e-e740-238b-9267c3cae370
* Content: [Reference for maintenance tasks - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/reference-for-maintenance-tasks#feedback)
* Content Source: [sccm/core/servers/manage/reference-for-maintenance-tasks.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/reference-for-maintenance-tasks.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
I revised this article, the change should publish live tomorrow
