### ISSUE TITLE
How about a powershell script in addition to the vbscript.

### ISSUE THREAD

**Issue by jadelise** [MicrosoftDocs/SCCMdocs#1591]
As it s 2019, perhaps the script examples should include PoweShell versions. Correct me if I am wrong, but isn't PowerShell the primary scripting language in the Microsoft environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9b9fdee-e834-affe-d7cd-61854d4a6925
* Version Independent ID: 1fb998eb-2449-1e17-fc6d-48a3a5c4f4e5
* Content: [Manage clients - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/manage-clients#feedback)
* Content Source: [sccm/core/clients/manage/manage-clients.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/manage-clients.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jadelise for the feedback. For any new examples, we try to use PowerShell. With over 2,600 articles in this library, and new major releases every four months, we revise existing articles when we're able. 

We also encourage those in our user community to contribute to our open source content, and updating a script sample is a perfect example of that. If you're interested in learning more, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute).

**Comment by cliffhobbs** [comment]
@aczechowski I guess the problem is how to ensure the quality of the scripts in the articles/to try and introduce some standardisation?

If you guys already have a bunch of scripts ready to go and it's just a case of inserting them into the relevant articles, then of course happy to help with that. Just LMK ;-)

**Comment by aczechowski** [comment]
@cliffhobbs I wish it were that easy. 😄 When we do add script samples, we generally try to reduce down to the most basic element. A few reasons for that:
- Long-term supportability of the script sample
- Reduce the amount of additional text in the article
- Let customers use and adapt the sample as best fits the needs and requirements of their unique environment
Obviously a balancing act.

In a similar vein, this [docsmsft proposal](https://github.com/dotnet/docfx/issues/4677) might interest you

**Comment by cp07451** [comment]
Wouldn't it be easier to just use this powershell command?
Invoke-WMIMethod -Namespace root\ccm -Class SMS_CLIENT -Name TriggerSchedule “{00000000-0000-0000-0000-000000000021}”

good article just little weird to see vbscript

**Comment by aczechowski** [comment]
I revised this article, including swapping out the script sample. it should publish live tomorrow
