### ISSUE TITLE
DEM enrolled device apps after migration

### ISSUE THREAD

**Issue by mikaelfun** [MicrosoftDocs/SCCMdocs#1594]
So what if we have DEM enrolled devices on SCCM, and we deploy the apps to the device collection in SCCM? Will the apps be removed after we change the tenant MDM authority to Intune, and the DEM devices are migrated to Intune? As far as we run the import tool, the apps are imported to Intune already but not the assignment to DEM device collection. So there will be a gap between the transition.

If the apps will be lost and will need to be re-assigned on Intune portal, is there a way to prevent this? Eg. will the powershell cmd Switch-MdmDeviceAuthority to migrate individual devices to Intune help? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4913cd11-dd09-791f-af96-9849efa08ef9
* Version Independent ID: 4e271b5d-8d9f-7837-867e-1fc1fffd3242
* Content: [Change the MDM authority - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/migrate-mixed-authority#migrate-devices-without-user-affinity)
* Content Source: [sccm/mdm/deploy-use/migrate-mixed-authority.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/migrate-mixed-authority.md)
* Product: **configuration-manager**
* Technology: **configmgr-hybrid**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
We discontinued the hybrid MDM service in September 2019. For more information, see the main [hybrid MDM](https://docs.microsoft.com/sccm/mdm/understand/hybrid-mobile-device-management) article. We plan to completely retire the documentation in a couple of months. Since we're no longer maintaining this content, I'm closing this issue.
