### ISSUE TITLE
Incorrect information regarding configuration of HTTPS DP as a source DP.

### ISSUE THREAD

**Issue by Sansing1** [MicrosoftDocs/SCCMdocs#1595]
Hi Team, 
It seems that the information listed in the "Important" section is not valid as we do get the option to configure HTTPS DP as a source DP in Pull DP properties. I have tested the same in lab running SCCM 1810 and 1802. Please update the document with correct information, as we now only need SCCM client and Client Authentication certificate on the Pull DP to allow it to download content from a Source DP configured on HTTPS.

Regards,
Sandeep Singh
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4055a018-68cf-1d48-df84-ea3d7f994f75
* Version Independent ID: 172470eb-4528-cab4-8ebe-dae2ed006523
* Content: [Pull-distribution point - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/use-a-pull-distribution-point#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/use-a-pull-distribution-point.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/use-a-pull-distribution-point.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
This has been fixed
