### ISSUE TITLE
Grace Period Needs More Detail

### ISSUE THREAD

**Issue by bryandam** [MicrosoftDocs/SCCMdocs#1599]
This came up again on Reddit and it's a common question: How _exactly_ do Grace Periods work?  We know the intent but enough people's experiences seem to differ from how they expect it to work that I think it bears clarification.

When I set a grace period of X hours what does that actually mean? X hours from ... what? Everyone says the deadline but that makes no sense and would invalidate the whole point of the feature.

When do grace periods apply? All the time or just during maintenance windows or business hours?

What happens at the end of the grace period?  Do updates just start installing right away like a Maintenance Windows would?

Based on my testing I _think_ that the behavior is this: X hours from when the client gets the new policy _if_ the client is currently during the user-configured business hours.  The grace period is only in effect during those business hours.  After _either_ business hours or the grace period expires updates will install the next time a software update evaluation occurs.

I'd just update the docs myself but testing this is super cumbersome so while I've done plenty of it I'm still not 100% certain I have it correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f74f4a-560f-2510-1ae8-fd3976a2197e
* Version Independent ID: 0851f834-e9a1-d0a6-ee60-934bcd3a79fe
* Content: [Client settings - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/deploy/about-client-settings)
* Content Source: [sccm/core/clients/deploy/about-client-settings.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/about-client-settings.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @bryandam, did you see this? https://docs.microsoft.com/sccm/apps/deploy-use/deploy-applications#delay-enforcement-with-a-grace-period
I think the last paragraph in that section answers your questions. (But let me know if not.)
It looks like the client settings page links to the article, but not this anchor. So that might be a good add.
I also got a good diagram from the feature team, I'm going to work with our art service team to clean it up and will embed that as well (in the deploy apps article).

**Comment by bryandam** [comment]
Ah yes, that's actually where I should have left this feedback. Sorry, I knew there was a better explanation somewhere.
The last paragraph, in my opinion, is what confuses people.  "After deadline, the client installs the application ... up to this grace period".  I see people interpreting that to mean that the grace period countdown starts from the static deadline.  So if the deadline is Friday, and you have a 24 hour grace period then when the user comes in Monday morning that logic means they're getting everything installed right now.
Grace periods are X hours from ... something.  If that something is the deadline then grace periods are for all practical purposes useless and the scenario described (user returning from a long vacation) won't matter.  The deadline + grace period is long gone by the time they return and they're getting everything immediately.
However, testing bears out that this is not the case and that the feature works more or less as described.  So it leaves me with the question: X hours from what?  This might sound academic but when people say grace periods aren't working and we try to help figure it out this question comes up every time.

**Comment by aczechowski** [comment]
It starts when the device comes back online. The primary scenario is the user is on vacation, they shutdown before they leave. When they come back, they power on the device. Instead of having to wait hours while SCCM pummels the device with required deployments, they can read through their gajillion emails in peace. They can manually trigger the deployment(s) if they want, or it will happen automatically during non-business hours or at the end of the grace period. 

I think the diagram will help. Here's the rough draft:
![image](https://user-images.githubusercontent.com/26784733/58722329-08559f80-838c-11e9-87aa-fb6c3431929d.png)

**Comment by bryandam** [comment]
Awesome, I think 'when it comes online' needs clarified.  Because I'm a huge detail nut I'd be legit interested to know if that's truly 'power on', 'log on', 'on network', or when the client starts (my guess).  Secondary, does it matter if the client got the policies in question before or after they left for vacation?

Lastly, if there's any relevant logging examples that would be swell.  I've tried helping people figure out why grace periods seemed to not work but I'm not even sure what, where, or when I'm looking for entries in the logs.

**Comment by aczechowski** [comment]
Most of the time it will be when the device is powered off while the user is out of the office. (That's at least the primary scenario for which this feature was designed.) But technically, it's when the client gets policy. So it could be that someone stops ccmexec, and then restarts it at some later time after the deployment deadline.

Logs...there should be mentions of "soft deadline" in the app and SUM enforcement logs.

**Comment by jpcast88** [comment]
I created a PR#3849 to update the link to the deploy apps article to include the anchor for the grace period section. The diagram above would also be very helpful to include in this article.

**Comment by aczechowski** [comment]
Thanks @jpcast88 for the edit. I added the diagram, as well as a note to clarify the start of the grace period per Bryan's question. So the issue is now closed; the article changes will be live tomorrow (Wednesday, 5 June) around 11am Pacific.
