### ISSUE TITLE
Permissions to run RLA are incorrect

### ISSUE THREAD

**Issue by Yupiter2005** [MicrosoftDocs/SCCMdocs#1603]
&gt;The account that you use to run the Replication Link Analyzer must have local administrator rights on each computer that is involved in the replication link. The account does not require a specific role-based administration security role. 

That's not enough, since RLA also performs SELECT queries to few DB tables, and machine admin is not necessary even a DB reader for SQL. 
So we also require at least SQL DB Reader to run the tool properly, and maybe more permissions to perform fixes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 669373a9-3d4b-73dd-5d3e-1bca2af0ccf4
* Version Independent ID: 81b0c667-debc-7053-6678-26724f52b81b
* Content: [Monitor replication - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/monitor-hierarchy-and-replication-infrastructure#feedback)
* Content Source: [sccm/core/servers/manage/monitor-hierarchy-and-replication-infrastructure.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/monitor-hierarchy-and-replication-infrastructure.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @Yupiter2005, I'm currently reviewing this article along with others for some new content we're adding. I noticed that the RLA prereq section has two bullets, one for local admin rights, and one for sysadmin rights.  (I can't link straight to that section with how the current article is structured, but go to the [RLA section](https://docs.microsoft.com/sccm/core/servers/manage/monitor-hierarchy-and-replication-infrastructure#BKMK_RLA) and then scroll down to the bold text: **Prerequisites to use the Replication Link Analyzer:**)
I think that addresses your concern, so I'm going to close this issue. Please reopen the issue if I'm missing something.
