### ISSUE TITLE
Maintenance Mode permissions

### ISSUE THREAD

**Issue by skoal2k4** [MicrosoftDocs/SCCMdocs#1606]
Doc currently reads "To put a distribution point in maintenance mode, your user account requires the Modify permission on the Site class. For example, the Infrastructure Administrator and Full Administrator built-in roles have this permission."

What i'm seeing in our environment is that the All security scope is also needed for the user.  Any way to verify proper permissions required?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b49b7692-2fba-a5b6-cc24-3b2621b7f5dd
* Version Independent ID: bbc48abf-20cb-18f4-0db4-467cb0408b30
* Content: [Manage distribution points - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/install-and-configure-distribution-points#feedback)
* Content Source: [sccm/core/servers/deploy/configure/install-and-configure-distribution-points.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/install-and-configure-distribution-points.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @skoal2k4 for the feedback.
I checked with engineering, this is a known bug that will be fixed in an upcoming hotfix rollup.
I'm closing this issue as there's nothing actionable for docs at this time.
