### ISSUE TITLE
Delivery Optimization - Content source priority?

### ISSUE THREAD

**Issue by SLeuthold** [MicrosoftDocs/SCCMdocs#1607]
Hi Team!

Please help verify where Delivery Optimization falls into the content source priority section of this doc. My understanding is that DO is a Windows 10 OS content management and not necessarily SCCM. However, SCCM boundary groups can be used with DO and now DOINC caching server in TP I think should be considered in the content source priority section.

Thank you for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff2f1985-822a-f9aa-8368-9abf85c50118
* Version Independent ID: 3401e963-f1cf-a15d-01f2-c1754a7d9336
* Content: [Content management fundamentals - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @SLeuthold for the feedback. I'll check with engineering to determine where DO slots in this list.

**Comment by aczechowski** [comment]
The short answer is that that list is totally N/A in case of DO. Here's why:
1. That ordered list is a hard coded fallback for our agent.
2. When we distribute an update, we talk to WUA. WUA does its thing, and for downloads it calls DO.
3. What happens after we hand it over to WUA is totally out of our control.
4. If WUA can’t find the content, it can fallback to us. When it falls back, then we use our own agent and our own ordering in that list.

I'll need to clean this up and figure out how to incorporate in the article, but I think still worthy of clarification for future reference.

**Comment by SLeuthold** [comment]
Thank you Aaron! I appreciate it.




[cid:InvokeV2_320x123_a1057048-27ef-466c-97e5-e700c239d335.png]<http://www.InvokeLLC.com>

[cid:Twitter_b17288c0-c42e-4e7b-bc77-033c4322b063.png]   <https://twitter.com/InvokeLLC>  [cid:Facebook_df83b2d8-63dc-4240-81e8-612606d7af58.png]    <https://www.facebook.com/InvokeLLC/>  [cid:LinkedIn_c54ffc3c-9f7d-485b-81ad-8b3c147d5a66.png]  <https://www.linkedin.com/company/7798865/>



Stephen Leuthold / Principal Consultant
Stephen.Leuthold@InvokeLLC.com<mailto:Stephen.Leuthold@InvokeLLC.com>
+1 (713) 553-1639

Invoke, LLC
+1 (713) 909-0411
118 Vintage Park Blvd. #W
Houston, Texas 77070
https://InvokeLLC.com


________________________________

Invoke is a 5x Microsoft Gold Partner
[cid:MicrosoftPartner_Logo-01_300x123_cf8f859d-0382-47ab-8666-69eec230198a.png]


________________________________

**Comment by SLeuthold** [comment]
@aczechowski I think I understand! Please clarify if your response is in the context of clients that are enabled for Windows Update for Business.

**Comment by aczechowski** [comment]
It can be. There are several scenarios in which clients use DO. The [tech preview 1903 content on DOINC](https://docs.microsoft.com/sccm/core/get-started/2019/technical-preview-1903#bkmk_doinc) has the best list I think.
