### ISSUE TITLE
feedback for new hub page

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#1610]
## [docs.microsoft.com/sccm](https://docs.microsoft.com/sccm)

For the month of June we're testing out a new hub page for the Configuration Manager documentation library. It's using a new design with updated links to commonly used or recommended content. Share your feedback by commenting on this issue.

**Comment by bryandam** [comment]
Huuuuge fan. Huuuuuge.  I might almost bookmark this and use it instead of permanently relying on remember Google search strings appended with site:docs.microsoft.com

**Comment by aczechowski** [comment]
Main Twitter post for reference: https://twitter.com/AaronCzechowski/status/1135605240923693056

**Comment by ChrisKibble** [comment]
Love it @aczechowski.  Can we add the Slack reference from #1516 in the next rev?  If you're accepting PRs, I'm happy to contribute.

**Comment by cliffhobbs** [comment]
I prefer this. A couple of suggestions:

1. Would be great (if technically possible) if folks could re-order/display the tiles that are relevant to them in the order they want.

2.  I think you should group the related areas together into top-level categories E..g a "Management" category that includes Co-management, Real-time management, etc.. Another for Content deployment to include things like deploying/updating apps, OSD, SW updates, etc. I do appreciate trying to decide where everything lives is not an easy decision and everyone has their own opinion on stuff like this ;-)

**Comment by bryandam** [comment]
For anyone who would like to compare, here's an archive of the previous iteration: https://web.archive.org/web/20190510225718/https://docs.microsoft.com/en-us/sccm/

**Comment by aczechowski** [comment]
Thanks @bryandam for the historical comparison 😄 
Thanks @cliffhobbs for the feedback. The docs PM/design team is watching this space for such feedback!

@ChrisKibble thanks for the reminder. Although my catch at this point is that there's currently an even six tiles in the Community & Support section. If I add one more, I think it will add a third row with just one tile. 😢 So are there any other community/support options to help fill out a third row? Doesn't @NCBrady run a Facebook group?

**Comment by bryandam** [comment]
I _think_ it's Anoop but I could be wrong, here's the link: https://www.facebook.com/groups/ConfigMgr2012 (That's an unfortunate URL)

If you need a third, maybe a reference to the Community Hub?  Tangentially fits in.

**Comment by jpewterbaugh** [comment]
Looks great! Are the top six dynamic? For instance if a lot of people start going to CMPivot docs will that get featured in the top six?

**Comment by jpcast88** [comment]
Looks awesome. I like the different icons and how you can see right off the bat what the topic is related to, whether it's deploy, architect, learn, etc., I think it would be helpful to provide a way to filter by these icons to get only those topics, but it could get a little tricky as some topics may fall into multiple categories.

**Comment by cliffhobbs** [comment]
Historically I believe Microsoft didn’t add links to 3rd party communities as they couldn’t be seen to endorse/recommend them, plus be held accountable for the information on them.

I’m not a lawyer and hope that’s changed, but I wouldn’t be surprised if the lawyers enforce this (hopefully some kind of disclaimer could be a workaround to this).

Cliff

**Comment by ChrisKibble** [comment]
> Historically I believe Microsoft didn’t add links to 3rd party communities as they couldn’t be seen to endorse/recommend them, plus be held accountable for the information on them. I’m not a lawyer and hope that’s changed, but I wouldn’t be surprised if the lawyers enforce this (hopefully some kind of disclaimer could be a workaround to this). Cliff
> […](#)

They have Reddit on there  now, and I found other docs pages that link to other communities (see the PR I reference above), so I think there’s some openness on the part of MS for external linking now.

**Comment by aczechowski** [comment]
Thanks all for the feedback! In case you missed it, I recently published some updates to the hub page, some of which based on your feedback.

FYI, in some cases your feedback is more for the docs platform team. But keep it coming, they are also reviewing this feedback.

**Comment by NCBrady** [comment]
just saw this now, @Aaron Czechowski <Aaron.Czechowski@microsoft.com> yes i
do and it's https://www.facebook.com/groups/windowsnoob/

sorry for the delay in responding
cheers
niall

**Comment by aczechowski** [comment]
Thanks all for the feedback; I'm closing this issue as the pilot is complete.
