### ISSUE TITLE
Promote pre-production client greyed out

### ISSUE THREAD

**Issue by RaidenXII** [MicrosoftDocs/SCCMdocs#1617]
Hi,
I am unable to promote pre-production client to production in configmgr 1810 after rollup hotfix kb4488698 was updated.
My account was added to full administrator security role site. I've tried on the insole and on the site server console. I've also tried with site server install account and promote pre-production client is still greyed out. 
Could you advise what I am missing here? Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c6ecf9a-a586-1f34-5c41-b41081cb5e55
* Version Independent ID: e29256cd-00f0-0dc9-88ea-988425858d64
* Content: [Test client upgrades pre-production collection - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/upgrade/test-client-upgrades)
* Content Source: [sccm/core/clients/manage/upgrade/test-client-upgrades.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/upgrade/test-client-upgrades.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @RaidenXII for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
