### ISSUE TITLE
Express Updates EOL

### ISSUE THREAD

**Issue by SLeuthold** [MicrosoftDocs/SCCMdocs#1622]
It appears Express Updates are no longer supported in favor of a "New Model" starting with 1809. Should the SCCM docs be updated to reflex this so the community has awareness.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcccfa90-7c10-2327-e3af-dbc1cb31b054
* Version Independent ID: c1d90427-19a0-c36c-8888-46707b4ee8c9
* Content: [Manage Windows 10 express updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/manage-express-installation-files-for-windows-10-updates)
* Content Source: [sccm/sum/deploy-use/manage-express-installation-files-for-windows-10-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/manage-express-installation-files-for-windows-10-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @SLeuthold for the feedback. Yes, that change in on our to do list

(Internal reference MicrosoftDocs/SCCMDocs-pr#3687)

**Comment by mestew** [comment]
This is getting changed in the client settings page shortly. There may be additional changes later as well. 
https://docs.microsoft.com/sccm/core/clients/deploy/about-client-settings
