### ISSUE TITLE
Peer Cache - Content version increase

### ISSUE THREAD

**Issue by SLeuthold** [MicrosoftDocs/SCCMdocs#1623]
Concerning Peer Cache, does a content version increase on a package still invalidate the whole package, causing it to transfer again across the network to the client?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29b8c8d-60fa-4403-29a7-8e7c61b2f638
* Version Independent ID: c7610ca2-5607-d1fe-f629-9d0614a26569
* Content: [Client Peer Cache - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/client-peer-cache)
* Content Source: [sccm/core/plan-design/hierarchy/client-peer-cache.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/client-peer-cache.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
@SLeuthold, yes that's correct.
Can you help me with where in this article it would be useful to add that point? What were you reading when this question came to you?

**Comment by SLeuthold** [comment]
Hi Aaron,

Got this from https://blogs.technet.microsoft.com/swisspfe/2018/01/25/branch-cache-vs-peer-cache/




[cid:InvokeV2_320x123_a1057048-27ef-466c-97e5-e700c239d335.png]<http://www.InvokeLLC.com>

[cid:Twitter_b17288c0-c42e-4e7b-bc77-033c4322b063.png]   <https://twitter.com/InvokeLLC>  [cid:Facebook_df83b2d8-63dc-4240-81e8-612606d7af58.png]    <https://www.facebook.com/InvokeLLC/>  [cid:LinkedIn_c54ffc3c-9f7d-485b-81ad-8b3c147d5a66.png]  <https://www.linkedin.com/company/7798865/>



Stephen Leuthold / Principal Consultant
Stephen.Leuthold@InvokeLLC.com<mailto:Stephen.Leuthold@InvokeLLC.com>
+1 (713) 553-1639

Invoke, LLC
+1 (713) 909-0411
118 Vintage Park Blvd. #W
Houston, Texas 77070
https://InvokeLLC.com


________________________________

Invoke is a 5x Microsoft Gold Partner
[cid:MicrosoftPartner_Logo-01_300x123_cf8f859d-0382-47ab-8666-69eec230198a.png]

**Comment by CaptainUnlikely** [comment]
If I can add my opinion, I think it would be useful to add under "Guidance for cache management".  Yes, it's not strictly related to the cache sizing etc, but it's consideration for how long the content might remain useful in the cache.

**Comment by aczechowski** [comment]
I'm resolving this issue in part because we moved repositories, but also because I'm going to track this work via an internal work item.

(internal reference 2838731)
