### ISSUE TITLE
Site Onboarding Question

### ISSUE THREAD

**Issue by johnjohnjohn87** [MicrosoftDocs/SCCMdocs#1629]
Does this apply if I've just onboarded the site and am running 1902?

    If you've already met this prerequisite for your site, you need to update the Azure AD application. In the Configuration Manager console, go to the Administration workspace, expand Cloud Services, and select Azure Active Directory Tenants. Select the Azure AD tenant, select the web application in the Applications pane, and then select Update application setting in the ribbon.

Also, are there logs to verify that setting up Enhanced HTTP worked?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cfc73c1-e15c-5dde-2a22-5cfc3eb7eb1c
* Version Independent ID: 50df732f-9232-74f6-f7d2-dda59c9b125b
* Content: [Enhanced HTTP - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/enhanced-http#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/enhanced-http.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/enhanced-http.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @johnjohnjohn87 for the feedback.
That comment only applies if your site was 1802 with an Azure AD connection. So in your case you shouldn't need to perform that action. We can probably clarify that a bit better.
I'll check on log files.

**Comment by johnjohnjohn87** [comment]
Thanks! As a follow up, should I be in the habit of updating those Azure apps each time the site is upgraded?

John Bart
________________________________

**Comment by aczechowski** [comment]
You shouldn't need to as part of a regular update. It's only needed when we change the functionality of the app, and we *should* specify that. I have a pending work item to add more info about this action in general.

**Comment by aczechowski** [comment]
Instead of diving in logs, the best way to verify is check the cert as described towards the end of the section on [configuring the site](https://docs.microsoft.com/sccm/core/plan-design/hierarchy/enhanced-http#configure-the-site). The you can compare that cert with the certificate binding in IIS for the HTTPS port.

**Comment by johnjohnjohn87** [comment]
Hmm... I don’t see that cert bound. I bound an internal cert there before to handle the app catalog, but I’ve recently gotten rid of it to use the new user app deployment method. I wonder if that caused an issue.

Should I see a cert called SMS Issuing in the primary server’s personal cert store? I don’t see one by that name as an option to bind in IIS.

Thanks for all the help, by the way. You guys have been on fire since the move to CB.
________________________________

**Comment by aczechowski** [comment]
@johnjohnjohn87 I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

**Comment by johnjohnjohn87** [comment]
No worries. Thanks for the clarification. I'll follow up on those channels.

John
________________________________

**Comment by aczechowski** [comment]
@mestew is making a change to remove this paragraph from the list of prereqs.
Thanks again for the feedback.
