### ISSUE TITLE
Client locations

### ISSUE THREAD

**Issue by jreckelberry** [MicrosoftDocs/SCCMdocs#1631]
In the Workgroup section, "Can use a cloud distribution point." should also include information about the cloud management gateway now that you won't be able to create a traditional cloud distribution point in the future. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff2f1985-822a-f9aa-8368-9abf85c50118
* Version Independent ID: 3401e963-f1cf-a15d-01f2-c1754a7d9336
* Content: [Content management fundamentals - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management#client-locations)
* Content Source: [sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jreckelberry for the feedback. Yes, good point.
