### ISSUE TITLE
Description of setting to Retain client status history

### ISSUE THREAD

**Issue by TacoCholoLocoYolo** [MicrosoftDocs/SCCMdocs#1638]
Under "Retain client status history for the following number of days," the description is literally just a re-wording, not a definition in any way shape or form.  It literally says: Retain client status history for the following number of days: Specify how long you want the client status history to remain in the site database. The default value is 31 days.  Have you ever heard the phrase "You can't define a term with a term"?  Simply jumbling the words around and re-writing them provides no value, you should have just written "the default value is 31 days," OR Actually put some useful information in there, such as: What information drops out of SCCM after 31 days?  Do you still have any ability to manage the clients?  How do you remediate inactive clients that haven't communicated in 31 days and have dropped off?  Either way, in it's current form, you are just defining a definition with itself, I can't believe Microsoft paid someone to write that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68a9bfdc-90f8-9ef4-5530-5e8bf80091e8
* Version Independent ID: 256ad96b-d22d-67a2-efa5-da336801220e
* Content: [Configure client status - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/deploy/configure-client-status#feedback)
* Content Source: [sccm/core/clients/deploy/configure-client-status.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/configure-client-status.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thank you @TacoCholoLocoYolo for your feedback. First, the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/), which outlines the expectations for community interactions in and around docs.microsoft.com, is designed to help "provide a welcoming and inspiring community for all." The tone of your feedback appears to be out of sync with the code of conduct.

We'll look at improving the description on this setting when we can get some additional details from the engineering team.
