### ISSUE TITLE
Are the peer cache ports all TCP?

### ISSUE THREAD

**Issue by SLeuthold** [MicrosoftDocs/SCCMdocs#1642]
For those discussions with the network team :)

Port for the initial network broadcast to find a peer cache source. By default, this is port 8004.
- Is this UDP?

Port for content downloading from a peer cache source (HTTP and HTTPS). By default, this port is 8003.
- I'm assuming this is TCP but some folks might not be aware.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd7a196d-4829-4b01-0bc0-8c14fd52dc1a
* Version Independent ID: db302fc5-0610-b270-0202-16fb4606a588
* Content: [Prepare Windows PE peer cache to reduce WAN traffic - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/get-started/prepare-windows-pe-peer-cache-to-reduce-wan-traffic)
* Content Source: [sccm/osd/get-started/prepare-windows-pe-peer-cache-to-reduce-wan-traffic.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/get-started/prepare-windows-pe-peer-cache-to-reduce-wan-traffic.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @SLeuthold for the feedback. Here you go:
- 8004: UDP
- 8003: TCP

Should also note that here: https://docs.microsoft.com/en-us/sccm/core/clients/deploy/about-client-settings#client-cache-settings

And perhaps the best solution in both instances is to just link to the [ports article](https://docs.microsoft.com/sccm/core/plan-design/hierarchy/ports#BKMK_PortsClient-ClientWakeUp) which already has this information. 😄

**Comment by aczechowski** [comment]
Thanks to @jpcast88 for submitting some changes for this issue, which is why it's now closed. The changes should publish live tomorrow (Thursday, 20 June) around 11am Pacific time.
