### ISSUE TITLE
Broken link leads to 404 error

### ISSUE THREAD

**Issue by colliefury** [MicrosoftDocs/SCCMdocs#1644]
Broken link "Update rollup for Configuration Manager current branch, version 1902." leads to 404 error

**Comment by aczechowski** [comment]
Hi @colliefury, in which article do you see this link?

**Comment by colliefury** [comment]
Hi Aaron,

aka.ms/dadocs -> Tutorials-> Pilot Windows 10 -> under topic "Connect Configuration Manager"

I am v-dadut btw

Thanks,
Damian

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aczechowski** [comment]
Got it. Yep, by design. That article isn't published yet. More coming soon.
