### ISSUE TITLE
Client Computer Communication vs Communication Security

### ISSUE THREAD

**Issue by Garthmj** [MicrosoftDocs/SCCMdocs#1645]
Is there an reason why in TP vs CB these are different? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cfc73c1-e15c-5dde-2a22-5cfc3eb7eb1c
* Version Independent ID: 50df732f-9232-74f6-f7d2-dda59c9b125b
* Content: [Enhanced HTTP - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/enhanced-http)
* Content Source: [sccm/core/plan-design/hierarchy/enhanced-http.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/enhanced-http.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Yes, because it changed in tech preview. 😉 
I'll keep this issue open to update this article (and search for others) in 1906 CB update.

**Comment by aczechowski** [comment]
Reference internal [BUG 4561015](https://msazure.visualstudio.com/Configmgr/_workitems/edit/4561015)

**Comment by aczechowski** [comment]
I'm closing this issue as it's fixed in the 1906 content, which will publish when 1906 releases. 😉
