### ISSUE TITLE
Support for Windows 10 for Enterprise for Virtual Desktops?

### ISSUE THREAD

**Issue by julesman101** [MicrosoftDocs/SCCMdocs#1647]
This articles specifically indicates support for the following editions of the Windows 10 semi-annual channel: Enterprise, Pro, Education, and Pro Education.

Is there any support, either now or planned, for the Windows 10 SAC edition called : "Windows 10 Enterprise for Virtual Desktops"?  This edition is available  in Azure only via the new Azure service called "Windows Virtual Desktop".

Thanks.. JD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc732ec0-eb14-8da2-7688-dd74a72cdae5
* Version Independent ID: a93682ff-2984-38e0-5a0d-6f77c1c9e5db
* Content: [Support for Windows 10 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/support-for-windows-10)
* Content Source: [sccm/core/plan-design/configs/support-for-windows-10.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/support-for-windows-10.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@julesman101 
There **might** have been something about this in the [1906 Technical Preview](https://docs.microsoft.com/en-us/sccm/core/get-started/2019/technical-preview-1906#bkmk_winsku) =) Granted, being in a TP doesn't necessarily mean that it will be in the 1906 CB release, but it's a very good indication that we are thinking about it.
#please-close
