### ISSUE TITLE
[Updated] tag w/more info

### ISSUE THREAD

**Issue by edhcah** [MicrosoftDocs/SCCMdocs#1654]
Wondering if anyone would find it helpful if, in addition to the page displaying [Updated], that a date stamp was added?  I come here when the RSS feed updates for me, then I just do a find on page for [Updated].  Seems like the tag is never removed, so I check each item until I see one that is new.  Would be great if a date was added so if the change is truly new I can just read about that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f7079b3-29e1-3132-2224-62d0b64928bf
* Version Independent ID: 2335eaff-13c7-0a2e-c234-3f160452864b
* Content: [What's new in version 1902 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/whats-new-in-version-1902#feedback)
* Content Source: [sccm/core/plan-design/changes/whats-new-in-version-1902.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/changes/whats-new-in-version-1902.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @edhcah for the feedback! I think that's a good idea. @mestew and I will discuss how best to implement.

**Comment by mestew** [comment]
Hey @edhcah,
@aczechowski and I discussed it and going forward with the 1902 doc updates, we will add the date next to the updated feature. 
#please-close

**Comment by edhcah** [comment]
> Hey @edhcah,
> @aczechowski and I discussed it and going forward with the 1902 doc updates, we will add the date next to the updated feature.
> #please-close

That was an amazing turn around for something so minor.  Thank you!
