### ISSUE TITLE
Device Limiation

### ISSUE THREAD

**Issue by Garthmj** [MicrosoftDocs/SCCMdocs#1656]
It says 10 devices and only WS OS are listed. What about server OS? Do they not count to this limit? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5372b7d8-70a9-2e0f-43fd-70f073ffb1ff
* Version Independent ID: f74edf5d-61f3-5f3d-3a9b-872c8ccb5d74
* Content: [Technical preview releases - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/technical-preview#feedback)
* Content Source: [sccm/core/get-started/technical-preview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/technical-preview.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Garthmj for the feedback. Let me confirm with the engineering team what we actually test with tech preview builds.

**Comment by aczechowski** [comment]
We support total of 10 clients for tech preview including server OS client
I'll update this with the next TP release

**Comment by Garthmj** [comment]
Newman!!!

Sent from my iPhone

On Sep 24, 2019, at 6:33 PM, Aaron Czechowski <notifications@github.com<mailto:notifications@github.com>> wrote:


We support total of 10 clients for tech preview including server OS client
I'll update this with the next TP release
