### ISSUE TITLE
Feedback on the section titled "Do I need Azure ExpressRoute?"

### ISSUE THREAD

**Issue by julesman101** [MicrosoftDocs/SCCMdocs#1659]
The section titled "DO I need Azure ExpressRoute?"   does not appear to make sense to me.  
The 1st Paragraph says, in my view correctly, that you do not need ExpressRoute.
The 2nd Paragraph is very confusing. 
a) If a customer is using ExpressRoute Private Peering only, then there should be no impact to the network paths that Internet Clients, or the on-premises SCCM Server would use to communicate with the CMG.
b) If a customer is using ExpressRoute with Microsoft Peering enabled for the relevant Azure Region, then there will still be no impact to Internet Clients. They will continue to communicate with the CMG via its public IP over the Internet.  However, for on-premises SCCM servers, the network path would now be directed away from the customers usual internet egress path and onto the ExpressRoute path, thereby adding additional privacy to the communications channel. 

Isolating the the CMG into its own subscription serves no purposes with regards to ExpressRoute.  if option b) above is enabled, then this redirection of traffic from the Internet path to the Expressroute path applies to all PaaS resources with a Microsoft owned public IP, irrespective of which subscription they sit.

I hope you can see why I find this FAQ entry confusing and would like you to bring some clarity to the published entry based on this feedback.   

Many Thanks... JD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a99f1b09-f669-e3c8-e9a1-c2594f329e12
* Version Independent ID: b022b0cd-f045-418a-be0e-f15f699f9d35
* Content: [CMG FAQ](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/cloud-management-gateway-faq)
* Content Source: [sccm/core/clients/manage/cmg/cloud-management-gateway-faq.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/cloud-management-gateway-faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @julesman101 for calling that out. We removed some similar content a while back and obviously missed this one. I'll update it now. 

This issue will auto close once the change is merged, but you won't see it live until the next daily publishing cycle. Right now that should be tomorrow (Thursday, 20 June) around 11am Pacific time.

**Comment by githubanurag** [comment]
Hello @aczechowski, it seems @julesman101 feedback is still not merged with production pages. Production documentation is still not clear on "Do I need Azure ExpressRoute?". ExpressRoute, or other such virtual network connections if used a Azure Subscription which is used by CMG, will then CMG work properly for Internet machines?

**Comment by aczechowski** [comment]
Hi @githubanurag, see the FAQ, [Do I need Azure ExpressRoute](https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/cloud-management-gateway-faq#do-i-need-azure-expressroute). An excerpt here, with a few key phrases in **bold**:

> ### Do I need Azure ExpressRoute?
> ***No***. Azure ExpressRoute lets you extend your on-premises network into the Microsoft cloud. **ExpressRoute, or other such virtual network connections aren't required for the Configuration Manager cloud management gateway.** The design of the cloud management gateway allows internet-based clients to communicate through the Azure service to on-premises site systems with **no additional network configuration**. For more information, see Plan for cloud management gateway.
