### ISSUE TITLE
SCCM SCAP extension pre-release availability

### ISSUE THREAD

**Issue by iadgovuser1** [MicrosoftDocs/SCCMdocs#1661]
The page says **This version of the tool is a pre-release feature that's only available in version 1806. This version isn't certified by NIST.** Is it true that it was only available in 1806? https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/core/get-started/capabilities-in-technical-preview-1803.md#scap-extensions suggests it was available in 1803 TP and later, but I didn't find it for 1902.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a689124-c901-d2e0-508f-998b39852315
* Version Independent ID: 6f6dc930-ad34-e747-f03f-93c46a3e237c
* Content: [SCAP extensions - Configuration Manager](https://docs.microsoft.com/en-us/sccm/compliance/plan-design/scap/about-scap)
* Content Source: [sccm/compliance/plan-design/scap/about-scap.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/compliance/plan-design/scap/about-scap.md)
* Product: **configuration-manager**
* Technology: **configmgr-compliance**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by iadgovuser1** [comment]
https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/compliance/plan-design/scap/install-configure-scap.md also mentions the same path of **cd.latest\SMSSETUP\TOOLS\ConfigMgrSCAPExtension\ConfigMgrExtensionsForSCAP.msi** without  the 1806 only caveat being mentioned anywhere.

**Comment by aczechowski** [comment]
Yes. It was first available in 1803 technical preview branch. Then it should only be available in current branch version 1806. It was removed from later current branch versions. I don't know if it's still in the technical preview branch. The feature team made the decision to remove it, but wanted to keep the documentation. 

If you want more information on the status of the tool, see the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) section in our docs to file feedback to the engineering team. 

I'm closing this issue as there's nothing actionable for docs at this time.
