### ISSUE TITLE
 Auto-enroll existing clients

### ISSUE THREAD

**Issue by shyamag001** [MicrosoftDocs/SCCMdocs#1664]
[Enter feedback here]
As a prerequisite for Auto-enroll existing clients, active directory federation services (ADFS) with pass-through authentication (PTA) and

As stated, I think it's a mistake in Active Directory Federation Services (ADFS) **or** pass-through authentication (PTA)
Basically, I think it's hard to think of a case of enabling PTA in an AD FS environment.

So please modify this sentense as below.
Active Directory Federation Services (ADFS) **or** pass-through authentication (PTA)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edf22630-0e3f-4db6-2cc4-105ef94d1410
* Version Independent ID: 4903eb43-67ac-f398-c00d-86d1950e4800
* Content: [Paths to co-management - Configuration Manager](https://docs.microsoft.com/en-us/sccm/comanage/quickstart-paths#feedback)
* Content Source: [sccm/comanage/quickstart-paths.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/quickstart-paths.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by mestew** [comment]
This article has been corrected and will update tomorrow.
