### ISSUE TITLE
Run PowerShell Script Encoding

### ISSUE THREAD

**Issue by monkeyskullfire** [MicrosoftDocs/SCCMdocs#1669]
This page notes that signed PowerShell scripts for the Run PowerShell Script step need to be Unicode and not ANSI, but that's only partially correct.  In fact the scripts must be encoded as UCS-2 LE BOM specifically, not just any encoding of Unicode.  Reference support ticket 14724944.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1187d55d-d8b3-ebc8-37e8-8de14807be4e
* Version Independent ID: daff4a99-10ac-b424-f08a-9024407e667a
* Content: [Task sequence steps - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/understand/task-sequence-steps#BKMK_RunPowerShellScript)
* Content Source: [sccm/osd/understand/task-sequence-steps.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/understand/task-sequence-steps.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @monkeyskullfire, I had a side conversation with the engineering team to get some additional information on this, and wanted to clarify a few things with you (I didn't see any specific mention of it in the support case notes that I saw):
- is your script signed?
- were you pasting it into the script window for this step, or using the option to "open" it?

**Comment by monkeyskullfire** [comment]
Hi @aczechowski.  Yes, the script is signed.  I used the Open option to load an existing file.

I did a bit of testing and found that changing the encoding will break a signed script in general.  My original script was in UTF-8 and I changed the encoding to a few other variants of Unicode, including UCS-2 LE BOM, and found that the signature broke each time.  So I think there are two factors at play here.  First, It appears PowerShell signatures are sensitive to changes in file encoding, not just file contents.  This of course is not a CM issue.  Second, I'm guessing that somewhere (maybe at the SQL level) CM is enforcing UCS-2 LE BOM for the content in the Run PowerShell Script step.  I'm happy to do testing with pasting content in versus using the Open button but it will be a week or two before I can get to that.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
