### ISSUE TITLE
Outdated information about Service Connection Point

### ISSUE THREAD

**Issue by PanuSaukko** [MicrosoftDocs/SCCMdocs#1675]
This page contains pretty old information about Service Connection Point (SCP). 

It should be updated with e.g. following topics:
1) Hybrid mobile device management will be retired on Sept 1, 2019
2) SCP is also responsible to configure/monitor CMG
3) SCP does Azure AD discovery
4) Integration with Microsoft Store for Business is done by SCP

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26fc3067-8a85-2455-8b71-69cf46cbb7e0
* Version Independent ID: a90ca598-c5fa-f245-eafc-0fd95f9eaca9
* Content: [Service connection point - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/about-the-service-connection-point#feedback)
* Content Source: [sccm/core/servers/deploy/configure/about-the-service-connection-point.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/about-the-service-connection-point.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
I made updates to this article with broader hybrid deprecation work that will publish soon. I'm closing this issue.
