### ISSUE TITLE
Management Point preference

### ISSUE THREAD

**Issue by tieronebanter** [MicrosoftDocs/SCCMdocs#1676]
The line: "In version 1802, you must configure all CMG-enabled management points to use HTTPS." suggests that HTTPS CMG enabled MPs and HTTP MP's can coexist. My understanding of MP preference is that a client will always pick an MP that is HTTPS first. Is it possible to have the HTTP MP's utilised when clients are on-prem? Or will clients always choose the CMG-enabled MP regardless of location because it is HTTPS.  I'm aware that enhanced HTTP may resolve this but am not confident that it meets the security requirement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778368d0-1054-678c-4d74-5dce1b5826c8
* Version Independent ID: aaac7308-66e6-66f0-8248-14e1505c11a6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/plan-cloud-management-gateway)
* Content Source: [sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @tieronebanter for the feedback. Two quick comments:
- As you mentioned, Enhanced HTTP negates this guidance, and is our recommended configuration
- Version 1802 will be out of support soon.

Otherwise, if you're using version 1802 and using HTTPS MPs for CMG, you can set the CMG MPs to ‘Internet Only” so that intranet clients don’t try and prefer them

**Comment by tieronebanter** [comment]
Appreciate the response! Our preference would be to not to have a dedicate MP for CMG. In my opinion this starts leaning towards IBCM (extra server, license etc etc). Hopefully we can convince Security that Enhanced HTTP is a safe option. HTTP always gets those alarm bells ringing!

**Comment by aczechowski** [comment]
I'm closing this issue as I made changes to the article that will publish with the 1906 content in the near future
