### ISSUE TITLE
Reassign a distribution point to a Secondary Site

### ISSUE THREAD

**Issue by AlexCesarini** [MicrosoftDocs/SCCMdocs#1677]
I understand the Reassignment of the DP has only been tested with Primary sites,
although the UI allows reassignments to secondary sites as well and I've done several tests and it worked ok, in my environments. Is there any known reason why it should not work for secondary sites as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b49b7692-2fba-a5b6-cc24-3b2621b7f5dd
* Version Independent ID: bbc48abf-20cb-18f4-0db4-467cb0408b30
* Content: [Manage distribution points - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/install-and-configure-distribution-points)
* Content Source: [sccm/core/servers/deploy/configure/install-and-configure-distribution-points.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/install-and-configure-distribution-points.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @AlexCesarini for the feedback. Sorry if you got that impression, we do test and support moving DP from Primary to Primary and Secondary to Primary. We've also tested Primary to Secondary although that’s probably the least used path.

**Comment by ChrisKibble** [comment]
Do we think this needs to be called out specifically in the doc?  "Starting in version 1802, this feature lets you reassign a distribution point **from a primary or secondary site** to another primary **or secondary** site without redistributing the content."  perhaps?

**Comment by AlexCesarini** [comment]
That would be perfect IMHO,
I know of several customers that did not use it on secondary sites because it was not documented.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by aczechowski** [comment]
Thanks @ChrisKibble for the suggestion. Perhaps divide into two sentences for simplicity:

> Starting in version 1802, this feature lets you reassign a distribution point to another site without redistributing the content. The target and destination sites can be either a primary or secondary site.

**Comment by Anoni-Mouse** [comment]
Hi
I have issues with this. We are in the process to flatten our SCCM infrastructure by removing the secondary sites and replace them by distribution points and when necessary MP as well. We have a remote secondary site and a DP assigned to this secondary site. From SCCM console, when I try to reassign the DP to my primary site, I get the following error

****** [42000][50000][Microsoft][SQL Server Native Client 11.0][SQL Server]Error! Failed to update sql data for reassign distribution point. : spMoveDistributionPoint***

There are no other roles installed on the server other than the DP role. I also have checked this query and fortunately I have no records:

SELECT * FROM DistributionContentVersion DCV
LEFT JOIN DistributionPoints DP ON DP.NALPath = DCV.DPNALPath
WHERE DCV.SiteCode <> DP.SMSSiteCode

Still I do not understand what the issue really is!

From SQL, I tried to run this:

EXEC spMoveDistributionPoint 'PRI', '["Display=\FQDN"]MSWNET:["SMS_SITE=SS1"]\FQDN'

But I got the following error

Msg 50000, Level 16, State 1, Procedure spMoveDistributionPoint, Line 321 [Batch Start Line 7]

Error! Failed to update sql data for reassign distribution point.

I have looked at tons of other articles on the web, but none solved my issue

**Comment by Uriel-FR** [comment]
Hello @aczechowski, 

sorry to dig up a thread from 2019 but we are facing this exact scenario today (reassigning numerous DPs to few secondary sites) I'm wondering why the documentation is still showing : 

_"This feature lets you reassign a distribution point to another primary site without redistributing the content. The distribution point's current site can be either a primary or secondary site. This action updates the site system assignment while persisting all of the content on the server."_
instead of what has been validated in PR#1970 
_"The target and destination sites can be either a primary or secondary site."_

Could you please verify and clarify the documentation if possible?
