### ISSUE TITLE
Clarify IPU is only supported to Windows 10

### ISSUE THREAD

**Issue by frankroj** [MicrosoftDocs/SCCMdocs#1678]
Hey Aaron/Meghan,

Can we clarify at this page that IPU is only supported to go to Windows 10 (for client OS) or Windows Server 2016/2019 (for server OS)? Windows Server 2019 also seems to be missing from supported OSes to go to. Also want to make sure IPU to 2019 is supported.

Thanks!

Frank

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05088ead-21fe-a787-b5b6-d0a90c219f5b
* Version Independent ID: a801446b-a068-f305-3fcc-a84420698bb9
* Content: [Upgrade to Windows 10 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/upgrade-windows-to-the-latest-version)
* Content Source: [sccm/osd/deploy-use/upgrade-windows-to-the-latest-version.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/upgrade-windows-to-the-latest-version.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @frankroj for the feedback. Yes, I'll need to rework it a bit to clarify both the "from" and the "to" for both desktop and server editions.
