### ISSUE TITLE
The following registry key can be set to 2

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/SCCMdocs#1681]
Under "To identify clients that use WUfB", when it says "can be set to 2", what can set it to 2?  Is it required that you create a CI/GPO/etc to set it to 2 to identify the Wufb managed machines?  When you deploy client settings to disable software updates, it seems to stay at a value of 1, so i'm curious if this should say something like "can be set by CI, package, GPP, etc." to 2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85ae5b79-2cc7-1a6b-10e2-3ff434dbc521
* Version Independent ID: 588472d2-8f23-56e8-ed59-1501a9557c3f
* Content: [Integration with Windows Update for Business in Windows 10 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/integrate-windows-update-for-business-windows-10)
* Content Source: [sccm/sum/deploy-use/integrate-windows-update-for-business-windows-10.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/integrate-windows-update-for-business-windows-10.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @russrimm for calling this out. After some investigation, there's some additional history on this topic. We'll work on getting it cleaned up.

A few internal references:
- MicrosoftDocs/SCCMDocs-pr#2058
- Email from MikeCure with Word attachment, subject "[MicrosoftDocs/SCCMdocs] The following registry key can be set to 2 (#1681)"

**Comment by mestew** [comment]
Tweaking this. When you disable SUM in SCCM, we remove UseWUServer. However, if someone enabled WSUS scanning via GPO, you would see UseWuServer set to 1. This setting sometimes doesn't get cleaned up when you remove the WUA GPO. 2 is actually not a valid value for UseWUServer. Added in collection query for finding clients where UseWUServer = null as well to find these clients.
