### ISSUE TITLE
No mention of OSD passwords including PXE password

### ISSUE THREAD

**Issue by frankroj** [MicrosoftDocs/SCCMdocs#1683]
Under the post recovery tasks there is no mention of having to reenter OSD related passwords. For example the PXE password used on PXE DPs and the various passwords found in Task Sequences (domain join password, local administrator password, run as account in Run Command Line tasks (if specified))

(admin edit: tag article for proper linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2bf93f-aa79-ef8a-ee16-c1ed27eb8e13
* Version Independent ID: d64f0463-a1e0-b80b-f16b-39f54dd87154
* Content: [Site recovery - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/recover-sites#post-recovery-tasks)
* Content Source: [sccm/core/servers/manage/recover-sites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/recover-sites.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
I revised this article, the changes will publish live on Monday 8/26 around 11am Pacific time.
