### ISSUE TITLE
1902 doco update needed

### ISSUE THREAD

**Issue by ceriaz** [MicrosoftDocs/SCCMdocs#1697]
Just noticed this line needs to be updated: When using the PXE responder without WDS instead of WDS, it is not supported to also run DHCP on the same server.. 
To this as of 1902 update:
When you enable a PXE responder on a distribution point without Windows Deployment Service, it can now be on the same server as the DHCP service. For more information, see Configure at least one distribution point to accept PXE requests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f4fb1c-8d88-ff2f-813a-3f2e7a9a6cfc
* Version Independent ID: df2889fa-04c0-163b-0bae-050990930c81
* Content: [OSD infrastructure requirements - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/plan-design/infrastructure-requirements-for-operating-system-deployment#feedback)
* Content Source: [sccm/osd/plan-design/infrastructure-requirements-for-operating-system-deployment.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/plan-design/infrastructure-requirements-for-operating-system-deployment.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ceriaz for finding that. I just made a quick update to the article to pull in the same language from another that I had already updated. The change should go live later today around 11am Pacific time with our daily publishing process.
