### ISSUE TITLE
Deploying Certificates to non-Intune enrolled Windows 10 Devices

### ISSUE THREAD

**Issue by dashoffma** [MicrosoftDocs/SCCMdocs#1706]
To deploy profiles to Android, iOS, Windows Phone, and enrolled Windows 8.1 or later devices, these devices must be enrolled in Microsoft Intune. For information about how to get your devices enrolled, see Enroll devices for management in Intune.

The above warning is part of the instructions on how to use this feature. What does "enrolled Windows 8.1 or later" mean? We have non-Intune Windows 10 devices on our network we would like to use this SCCM feature for. We're unsure if it would work if they are NOT Intune MDM managed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdeb92e9-6d70-2f1b-cf66-ce37d74d7bf5
* Version Independent ID: f4132bb4-dc38-1a91-15e8-88b443dfee61
* Content: [How to create Wi-Fi profiles - Configuration Manager](https://docs.microsoft.com/en-us/sccm/protect/deploy-use/create-wifi-profiles#feedback)
* Content Source: [sccm/protect/deploy-use/create-wifi-profiles.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/create-wifi-profiles.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @dashoffma for the question. That note is only for hybrid managed devices, so doesn't apply to your situation. In the next several months we'll be removing that content anyway, since hybrid is deprecated and support ends in a few months.
I'm closing this issue as there's not anything actionable for docs at this time.
