### ISSUE TITLE
Download Package Content tasks lists Boot Images

### ISSUE THREAD

**Issue by frankroj** [MicrosoftDocs/SCCMdocs#1712]
The Download Package Content task lists Boot Images as supported with this task. However testing in my 1902 lab boot images are not available when selecting content in the Download Content Package task. Is the documentation incorrect or is this a product bug that the boot images are not showing up?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1187d55d-d8b3-ebc8-37e8-8de14807be4e
* Version Independent ID: daff4a99-10ac-b424-f08a-9024407e667a
* Content: [Task sequence steps - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/understand/task-sequence-steps#BKMK_DownloadPackageContent)
* Content Source: [sccm/osd/understand/task-sequence-steps.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/understand/task-sequence-steps.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Yep, confirmed with engineering team that this functionality was removed, the doc is wrong.

**Comment by aczechowski** [comment]
Fixed with MicrosoftDocs/SCCMDocs-pr#4056, closing
