### ISSUE TITLE
Intune only?

### ISSUE THREAD

**Issue by gutjahr** [MicrosoftDocs/SCCMdocs#1728]
DA is described as a cloud based service that integrates with ConfigMgr. What about AAD Intune only clients? Is that possible or will this only work if the Intune client is co-managed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8d7ece-b19f-1431-a619-e57ce6469c28
* Version Independent ID: 86a3d7a5-695b-d3d9-498c-e6b6e03169f8
* Content: [Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/sccm/desktop-analytics/overview)
* Content Source: [sccm/desktop-analytics/overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @gutjahr for the question. Right now, Desktop Analytics only integrates with Configuration Manager. If a device is co-managed, then you can configure Desktop Analytics policies for it.

I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by Scoobysnax97** [comment]
Hi.... can you clarify if you MUST have ConfigMgr in the configuration?  Will you still collect data in Log Analytics if you haven't integrated CM?

**Comment by aczechowski** [comment]
Yes, ConfigMgr is required. We will discard processing data for devices that aren't enrolled with SCCM. For more info on this topic, see https://github.com/MicrosoftDocs/SCCMdocs/issues/1727#issuecomment-510566330
