### ISSUE TITLE
Odata query with $select does not return all records

### ISSUE THREAD

**Issue by darrindyson** [MicrosoftDocs/SCCMdocs#1735]
I am trying to retrieve records for a particular entity.  The filter portion works just fine and I get the results I desire.  If I add a $select to retrieve just the fields I care about and reduce the payload, it only returns a single record

Returns all records
https://mysite/AdminService/wmi/SMS_G_System_ADD_REMOVE_PROGRAMS_64?$filter=ResourceID eq 16777462

Returns single record
https://mysite/AdminService/wmi/SMS_G_System_ADD_REMOVE_PROGRAMS_64?$filter=ResourceID eq 16777462&$select=ResourceID, DisplayName

**Comment by aczechowski** [comment]
Thanks @darrindyson for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
