### ISSUE TITLE
Updates listed have been superseded

### ISSUE THREAD

**Issue by Speersy82** [MicrosoftDocs/SCCMdocs#1736]
Windows 7 with Service Pack 1 Download the update: KB 2952664 - has been superseded by KB4507456

Windows 7 Install the October 2018 monthly rollup, KB4462923 - has been superseded by KB4507449 

These updates appear to be superseded each month. Can you confirm?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 113ad599-a2ac-a376-70d7-86088c90f06e
* Version Independent ID: 3e781a76-9e2c-50f8-7afa-a52cb944008b
* Content: [Enroll devices in Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/sccm/desktop-analytics/enroll-devices#update-devices)
* Content Source: [sccm/desktop-analytics/enroll-devices.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/enroll-devices.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Speersy82 for the feedback. I'm confirming with the feature team.

**Comment by aczechowski** [comment]
@juanandmsft submitted a change a while back that will address this. I just finalized and signed off, it might go live later today, if not tomorrow for sure.

The key point for you @Speersy82:
> If your organization doesn't apply "Monthly Quality Rollup" updates to Windows 7 devices, and only applies "Security Only" updates, you'll find some "Security Only" updates in the [list of updates superseding KB 2952664](https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=ad3652cd-2689-4726-b3ef-b086ded23c7c). You can install these newer updates instead of KB 2952664.

I'm closing this issue.
