### ISSUE TITLE
MultiSubnetFailover was implemented in 1902

### ISSUE THREAD

**Issue by Yupiter2005** [MicrosoftDocs/SCCMdocs#1737]
Need to fix this statement:
MultiSubnetFailover: It's not supported to use an availability group with Configuration Manager in a multi-subnet configuration. You also can't use the MutliSubnetFailover keyword connection string.

See https://blogs.technet.microsoft.com/umairkhan/2019/05/11/the-case-of-unexplained-configmgr-console-slowness-after-moving-to-sql-always-on-multi-subnet-configuration/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53d1da83-d988-fb2b-82c5-fd9cf117cd42
* Version Independent ID: 2b1a3bd2-5116-1f21-c196-e3e5698a83c9
* Content: [SQL Server Always On - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database)
* Content Source: [sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Yupiter2005 for the feedback. We're already tracking this via an internal issue, which I've linked here. The update is scheduled to happen with the 1906 current branch content.

**Comment by aczechowski** [comment]
I'm closing this issue as it's addressed in the 1906 content that will publish soon.
