### ISSUE TITLE
Application Requirements - using a Custom Condition with "One Of" operator

### ISSUE THREAD

**Issue by PLogFinder** [MicrosoftDocs/SCCMdocs#1753]
Under Deployment Type - Requirements:
Please let us know what syntax to use for multiple values for a custom condition string with the "One Of" operator, eg commas, one per line (or either); and how to quote values to include data with spaces, commas, other special characters?  Also for other data types eg number.  

Further thoughts: Does it need its own page for all the detail, or is there another SCCM function that uses the same underlying code that can be referenced?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db758241-5a9e-47dc-0104-8d8c1072a2f2
* Version Independent ID: d54013ba-afcb-6795-9fb5-3668a8afec32
* Content: [Create applications - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/create-applications#feedback)
* Content Source: [sccm/apps/deploy-use/create-applications.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/create-applications.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @PLogFinder, I'm checking with engineering. 

Note we do have a separate article on [creating global conditions](https://docs.microsoft.com/sccm/apps/deploy-use/create-global-conditions) but it doesn't go into this level of detail.

I took a quick look - did you try just using a comma delimited list? A default "one of" clause, like for Windows versions, is just comma delimited:
![image](https://user-images.githubusercontent.com/26784733/61733868-910e0d80-ad35-11e9-88b1-86a22dccb006.png)

**Comment by aczechowski** [comment]
@PLogFinder can you help clarify which specific UI surface you're talking about? What are the steps to get to where you're looking?
In many instances, when using the "One Of" operator, the Values field has validation that you have to enter one entry per row. I'm still checking on it to confirm, but I assume that it's the same in other instances. The UI is just a user-friendly version of the underlying XML where these rules are defined as separate nodes.

**Comment by PLogFinder** [comment]
Thank you, one entry per row worked.

**Comment by aczechowski** [comment]
@mestew will make a revision for this

**Comment by Milosz1984** [comment]
Having the same problem, trying use Manufacturer property from Win32_ComputerSystem class.
Adding HP and Hewlett-Packard (one entry per row) as values for "one of" statement and it will always return requirement not met. Could dash in Hewlett**-**Packard be a problem here ? And if so, how to escape it ?
