### ISSUE TITLE
SCCM Current Branch Compatibility matrix

### ISSUE THREAD

**Issue by santoshseth** [MicrosoftDocs/SCCMdocs#1754]
Does MDT build 8456 support SCCM 1902?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b1c8a5d-b639-d555-0850-b98a9010023c
* Version Independent ID: b20fdb1c-8d40-c3b2-2265-779a3f2dfe98
* Content: [MDT release notes](https://docs.microsoft.com/en-us/sccm/mdt/release-notes#supported-platforms)
* Content Source: [sccm/mdt/release-notes.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdt/release-notes.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @santoshseth, please see [this FAQ](https://docs.microsoft.com/en-us/sccm/mdt/release-notes#bkmk_note2)

**Comment by Kegoel** [comment]
Hello Aaron.

I have following queries,

1. Would you know when is the next release of MDT scheduled for?
2. Does Microsoft recommend upgrading SCCM to version 1906 while keeping MDT build at version 8456.
3) MDT Document shows supported Windows version as 1809. Does 8456 supports 1903 as well
