### ISSUE TITLE
How do i get the PackageID programmatically after creation of the Package?

### ISSUE THREAD

**Issue by SgtApone117** [MicrosoftDocs/SCCMdocs#1755]
After creating the package with this method. How do i fetch the PackageID of the created package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f40b32f-46e7-f068-bbdf-459c13243d7f
* Version Independent ID: 2759a959-7650-0817-3360-3fb2c1f37581
* Content: [Create a Package - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/core/servers/configure/how-to-create-a-package#feedback)
* Content Source: [sccm/develop/core/servers/configure/how-to-create-a-package.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/core/servers/configure/how-to-create-a-package.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @SgtApone117 - We unfortunately have a large backlog of work for the PowerShell & SDK content, but are looking at ways to improve it in the future.

I'll keep this issue open, but here are a few options to get more immediate help:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

**Comment by ChrisKibble** [comment]
I thought it was returned by .put() but I’ll confirm. Also we should replace the VBS with PoSH. I’ll add it to my list and tackle when I have some time if someone doesn’t beat me to it.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
