### ISSUE TITLE
Wrong Entry

### ISSUE THREAD

**Issue by natiT** [MicrosoftDocs/SCCMdocs#1758]
Hi,

"This file or folder is associated with a 32-bit application on 64-bit systems: This option is selected by default. The client first checks 32-bit file locations for the specified file or folder. If the file or folder isn't found, the client then searches 64-bit locations."

This option is NOT selected by default :) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db758241-5a9e-47dc-0104-8d8c1072a2f2
* Version Independent ID: d54013ba-afcb-6795-9fb5-3668a8afec32
* Content: [Create applications - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/create-applications#feedback)
* Content Source: [sccm/apps/deploy-use/create-applications.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/create-applications.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @natiT for the feedback. This setting is on by default when I create a new detection rule in our test environment:
![image](https://user-images.githubusercontent.com/26784733/61811462-5e781980-adf6-11e9-8c3e-4f4ebd3733b1.png)
I'll check with engineering if there's some circumstance in which it's not the default. Is this the same UI you're looking at?

**Comment by natiT** [comment]
Hi Aaron i just checked. You are right in File System the Mark is checked.  
In the Registry Detection Method its not checked.  
I may mixed this things up :) 
![image](https://user-images.githubusercontent.com/24733009/63272077-b68e2880-c29b-11e9-8bfa-a32b33566361.png)

**Comment by aczechowski** [comment]
Ok, thanks for clarifying. I'll keep it open to make a quick clarification.

**Comment by ChrisKibble** [comment]
Is this intended behavior that we should document or a bug that should go to dev?

**Comment by aczechowski** [comment]
You can certainly file a frown, but personally I don't think it warrants a product change. Just a brief edit to the doc that the setting is on by default *in some scenarios*. Or just strike the sentence about the default behavior altogether.

**Comment by aczechowski** [comment]
@mestew will make this revision today.
