### ISSUE TITLE
No Flowcharts

### ISSUE THREAD

**Issue by gabrielAlmado** [MicrosoftDocs/SCCMdocs#1760]
https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/about-the-service-connection-point.md
missing urls:
https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/core/servers/manage/download-updates-flowchart
https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/core/servers/manage/update-replication-flowchart
![obraz](https://user-images.githubusercontent.com/40490624/61874903-cb201080-aee9-11e9-96bf-caca30224b81.png)

**Comment by aczechowski** [comment]
Hi @gabrielAlmado, please make sure you're browsing our content on docs.microsoft.com, not github.com. The content is meant to be read on the docs site. If you use the main article at https://docs.microsoft.com/sccm/core/servers/deploy/configure/about-the-service-connection-point, you'll find the links to the flowcharts work ok.

**Comment by gabrielAlmado** [comment]
Thx. Work like a charm.
