### ISSUE TITLE
Section - Updating a Linked Deployment Share Using Windows PowerShell

### ISSUE THREAD

**Issue by BlackV** [MicrosoftDocs/SCCMdocs#1768]
In Section
Updating Deployment Media Using Windows PowerShell

Step 4
4. Update the deployment share using the Update-MDTDeploymentShare cmdlet, as shown in the following example:

The example says 
Update-MDTLinkedDS -Path "DS002:\Linked Deployment Shares\LINKED002"  

rather than
Update-MDTDeploymentShare  -Path "DS002:\Linked Deployment Shares\LINKED002" 

So either your step is wrong or your example is wrong, given its the same example in section - Updating a Linked Deployment Share Using Windows PowerShell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc2393d-6a81-c9c9-87bb-b40b66f26d68
* Version Independent ID: fda85f4c-33ec-d0aa-b793-381d2bebb57d
* Content: [MDT samples - Microsoft Deployment Toolkit](https://docs.microsoft.com/en-us/sccm/mdt/samples-guide#feedback)
* Content Source: [sccm/mdt/samples-guide.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdt/samples-guide.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by BlackV** [comment]
Update-MDTLinkedDS -Path "DS002:\Linked Deployment Shares\LINKED002" is the example in the section - Updating Deployment Media Using Windows PowerShell.

I put the wrong title section

**Comment by aczechowski** [comment]
Hi BlackV - you're welcome to submit the edit yourself, 😄 for more info see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute). Otherwise I've tagged this issue for help from the community.

**Comment by BlackV** [comment]
Fair enough. I'll have a look later on

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
