### ISSUE TITLE
Poor formatting of switch examples

### ISSUE THREAD

**Issue by jowiswel** [MicrosoftDocs/SCCMdocs#1770]
Multiple examples of how to specify switch information (e.g. /G) are exhibiting incorrect characters and in the case of some browsers are also missing key pieces of the example text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a1b8816-b6c5-1f46-7afd-8076b7d8aec7
* Version Independent ID: c50eeb12-1033-c2b6-1471-0e84b1b3c64b
* Content: [OS Deployment CreateMedia.exe - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/osd/operating-system-deployment-createmedia.exe#feedback)
* Content Source: [sccm/develop/reference/osd/operating-system-deployment-createmedia.exe.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/osd/operating-system-deployment-createmedia.exe.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
This issue is closed because I submitted a change for it which will publish on Monday around 11am Pacific. Thanks for the feedback!
