### ISSUE TITLE
Add support statement on WDS-less PXE

### ISSUE THREAD

**Issue by frankroj** [MicrosoftDocs/SCCMdocs#1771]
In the Note under the following section:

https://docs.microsoft.com/en-us/sccm/core/understand/configuration-manager-on-azure#what-about-content-distribution-and-content-management-should-standard-distribution-points-be-in-azure-or-on-premises-and-should-i-use-branchcache-or-pull-distribution-points-on-premises-or-should-i-make-exclusive-use-of-cloud-distribution-points

can we add clarification that the WDS-less PXE responder is also not supported? I would submit change myself but want verification that this in fact is the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0da69878-a841-1f05-32c2-a1fcba10506f
* Version Independent ID: 769913cc-0fa4-cd5b-b015-b7c5f38fc0d4
* Content: [Configuration Manager on Azure](https://docs.microsoft.com/en-us/sccm/core/understand/configuration-manager-on-azure#what-about-content-distribution-and-content-management-should-standard-distribution-points-be-in-azure-or-on-premises-and-should-i-use-branchcache-or-pull-distribution-points-on-premises-or-should-i-make-exclusive-use-of-cloud-distribution-points)
* Content Source: [sccm/core/understand/configuration-manager-on-azure.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/configuration-manager-on-azure.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
There's a reference in the Azure networking content that talks about protocol use: https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-faq#what-protocols-can-i-use-within-vnets
It doesn’t explicitly mention PXE, but excludes DHCP which is effectively the same (and it also mentions multicast, which we should probably add). So while that might help answer some “why” questions, it does still leave some room for questions. So for now, let’s reduce the statement down to just the following:

> If PXE or multicast support is required, you must use on-premises distribution points (standard or pull) to respond to boot requests.

Then if we get further feedback with lots of “why” questions, we can add a reference to the Azure networking doc.

**Comment by aczechowski** [comment]
Fixed by MicrosoftDocs/SCCMDocs-pr#4199
