### ISSUE TITLE
SMSTSRebootRequested - missing info about possible value "WinPE"

### ISSUE THREAD

**Issue by Cydron** [MicrosoftDocs/SCCMdocs#1773]
SMSTSRebootRequested can take the value "true", but can also be set to "WinPE". This is needed if you are in the WinPE phase of a Task Sequence and wish to reboot back into WinPE again. If you just set SMSTSRebootRequested to "true" whilst in WinPE you get the error "Task sequence cannot continue after reboot because TS Manager is not configured to auto-start or GINA is not installed”. It took me ages to discover this - it would be nice if it was noted in this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 659b0c85-eac7-591e-42d3-8ca629fd6c84
* Version Independent ID: 392139c6-3e46-c0b8-bd1b-ebfc51615fc7
* Content: [Task sequence variable reference - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/understand/task-sequence-variables#feedback)
* Content Source: [sccm/osd/understand/task-sequence-variables.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/understand/task-sequence-variables.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Cydron for the feedback, and sorry for the difficulty. I checked with engineering: the proper values for this variable are `HD` or `WinPE`. It's never set to true or false.

**Comment by aczechowski** [comment]
I revised this article, the change will publish live on Monday 8/26 around 11am Pacific time.

**Comment by beanmeister** [comment]
I know this article is closed, however I noticed a glaring discrepency between the comment above and the details on the variable SMSTSRetryRequested, which mentions "If this task sequence variable is set, also set the SMSTSRebootRequested variable to true". If this is the case, can SMSTSRetryRequested also be clarified and fixed up?
