### ISSUE TITLE
Management Point now requires NT\NETWORK SERVICE to have SQL rights if the Management Point and DB server are collocated 

### ISSUE THREAD

**Issue by jrosser1221** [MicrosoftDocs/SCCMdocs#1779]
With our new User Service component of the Management Point, we connect to SQL using the NT\NETWORK SERVICE account when the MP and DB servers are collocated. Otherwise, we use the system account of the Management Point. As NT\NETWORK SERVICE is not listed with SQL permission requirements up until now, we should consider adding this as a check prior to deploying a Management Point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9070eb9b-0e5f-a877-e02e-2d1cea2a2b38
* Version Independent ID: df251762-f2d6-9f06-4fa9-ec5cea2cca0a
* Content: [Site prerequisites - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/site-and-site-system-prerequisites#feedback)
* Content Source: [sccm/core/plan-design/configs/site-and-site-system-prerequisites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/site-and-site-system-prerequisites.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @jrosser1221, thanks for the input. I checked with engineering on this: 
Hman manages sql role memberships automatically on role install/uninstall:
-	If MP is co-located, Network Service is added to user service sql role
-	If MP is not co-located, machine account is added to user service sql role
It’s not something admin needs to do unless there is an issue (which does happen on occasion). Feels like it’s more of a support doc. We're actually looking into the level of technical troubleshooting content we want to start adding to our content, so I'll keep this open until we finalize that plan.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
