### ISSUE TITLE
Include link to other troubleshooting page

### ISSUE THREAD

**Issue by jandreacola** [MicrosoftDocs/SCCMdocs#1782]
There is another support page with extensive application troubleshooting that should be included with this https://support.microsoft.com/en-us/help/4509382/troubleshooting-application-deployment-in-configuration-manager 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6783f42-7ea1-bbb5-9fd0-8eed2daf8c17
* Version Independent ID: 9fc83fef-d55a-9f18-6a6a-8316ecaae740
* Content: [Troubleshoot app deployments - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/troubleshoot-application-deployment)
* Content Source: [sccm/apps/deploy-use/troubleshoot-application-deployment.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/troubleshoot-application-deployment.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jandreacola for the suggestion! We've been working with folks in support to move some specific troubleshooting content from KBs (internal and external) over to core docs.
@mestew FYI

**Comment by aczechowski** [comment]
This is done. Vinay migrated that KB to docs: https://docs.microsoft.com/en-us/mem/configmgr/apps/understand/app-deployment-technical-reference (and it's linked from this article)
