### ISSUE TITLE
How to update portal URL?

### ISSUE THREAD

**Issue by freebird8x** [MicrosoftDocs/SCCMdocs#1784]
Hi, how could I update the portal URL? Currently I'm using ManagementObject.InvokeMethod("GetPortalUrlValue", args) to retrieve the portal URL but it always give me back an outdated URL. How would I update the portal URL so that when I invoke the method, it'll give me back the new one?

**Comment by aczechowski** [comment]
Thanks @freebird8x for taking the time to share this with the Configuration Manager documentation team.

With my limited knowledge of this topic, you may want to look at
[Lazy properties](https://docs.microsoft.com/sccm/develop/core/understand/configuration-manager-lazy-properties).

I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
