### ISSUE TITLE
"Schedule Updates" with SCCM 1902

### ISSUE THREAD

**Issue by PehDeh** [MicrosoftDocs/SCCMdocs#1785]
I have 2 SCCM CB 1902 Systems one with the latest Rollup KB4500571.
On that Server I can´t "Schedule Updates" for the Operating System Windows Server 2016. It´s simply greyed out.
If i copy the same Windows Server 2016 wim to the Server without the Update Rollup and it works.

Windows Server 2019 Works on both.
I stumbled upon several posts with a possible solution: https://forums.prajwaldesai.com/threads/server-2016-wim-schedule-updates-greyed-out.2625/
But my Table showed correct values.
Some say it´s fixed in 1906 but I´m not in the Fastring.
Any hints/ideas or is it just an issue till it get´s fixed in 1906.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6d04f4d-edd4-3ba9-0723-e3b2634c1b7e
* Version Independent ID: 216fe20c-5009-bcb5-ee93-fb942a034ba2
* Content: [Manage OS images - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/get-started/manage-operating-system-images#feedback)
* Content Source: [sccm/osd/get-started/manage-operating-system-images.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/get-started/manage-operating-system-images.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by PehDeh** [comment]
Tried view more things:
* tried it with a new extracted wim -> doesn´t work
* tried it after i imported the wim i could service on the host without latest 1902 hotfix rolup, stays greyed out.

**Comment by PehDeh** [comment]
This might be the solution, contacting support on Monday 
https://lurrker.com/r/SCCM/comments/cdgoon/sccm_1902_server_2016_wim_offline_servicing

**Comment by aczechowski** [comment]
Thanks @PehDeh for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by Zenrin** [comment]
It appears that this same issue is occurring for Windows Server|2004 (2020-04) release.  The SupportedProductsForOfflineServicing table has 10.0.19035 for Windows Server|2004, when it should be 10.0.19041 in the OsVersionBuild column.  I updated my database, restarted SCCM and now the Schedule updates is no longer greyed out for Windows Server 2020-04 release. :)
