### ISSUE TITLE
Note about Hybrid MDM is confusing

### ISSUE THREAD

**Issue by JAPainter** [MicrosoftDocs/SCCMdocs#1790]
The note section "If you have a hybrid MDM environment (Intune integrated with Configuration Manager)," is somewhat circular and confusing because both Co-Management and Hybrid MDM are technically "Intune integrated with Configuration Manager".  Can this section be updated for clarity, maybe noting the difference in which mechanism is the authority?  ie: in hybrid MDM, SCCM is the authority and receives Intune features pushed down and in co-management Intune is the authority and SCCM features are pulled up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f24ae716-bf27-7d45-cb15-0bc6eea64374
* Version Independent ID: f444ef64-9b7d-999f-3fb3-6ac6cda3ef88
* Content: [Co-management for Windows 10 devices - Configuration Manager](https://docs.microsoft.com/en-us/sccm/comanage/overview#feedback)
* Content Source: [sccm/comanage/overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @JAPainter, thanks for the feedback and sorry for the confusion. Hybrid MDM is a specific SCCM configuration that pre-dates co-management. For more information, see [What is hybrid MDM](https://docs.microsoft.com/sccm/mdm/understand/hybrid-mobile-device-management). Also note, as you'll see if you look at that article, it's deprecated and going away in a month. So if you're using it, you should know it, and be working to get off of it (migrate to Intune standalone). If you're not using it, don't worry about it. 😄 That note will go away entirely in a few months after the service is turned off. I'm closing this issue.

**Comment by JAPainter** [comment]
Thanks for the info!


Jacob
