### ISSUE TITLE
Remove message about optional pre-release features

### ISSUE THREAD

**Issue by kmyrup** [MicrosoftDocs/SCCMdocs#1791]
"Configuration Manager doesn't enable this optional feature by default. You must enable this feature before using it. For more information, see Enable optional features from updates."
This is no longer needed.  In current branch, this is a "Release" feature (as of several releases back, not sure which one it started, but I checked 1902 and it is "Release" there). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a429ba7-b6ca-4def-d32f-1face0cf2864
* Version Independent ID: a23d121d-cc09-61e9-5b70-f6e15cf1574a
* Content: [Introduction to certificate profiles - Configuration Manager](https://docs.microsoft.com/en-us/sccm/protect/deploy-use/introduction-to-certificate-profiles#feedback)
* Content Source: [sccm/protect/deploy-use/introduction-to-certificate-profiles.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/introduction-to-certificate-profiles.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Via internal thread, confirmed that this feature is [optional](https://docs.microsoft.com/sccm/core/servers/manage/install-in-console-updates#bkmk_options), not to be confused with [pre-release](https://docs.microsoft.com/sccm/core/servers/manage/pre-release-features).
