### ISSUE TITLE
This article needs to be expanded to include Data collected and how its used

### ISSUE THREAD

**Issue by Ramonin** [MicrosoftDocs/SCCMdocs#1794]
In order to overcome concerns around data privacy - this article should link to the data classes and details collected and how they are used.   This will be required for most customers.  There is not enough detail in this article 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0650268-f62a-bee5-1f2b-2889dfaae842
* Version Independent ID: 392f6f86-8d43-d296-dade-6bd451582f75
* Content: [Desktop Analytics data privacy - Configuration Manager](https://docs.microsoft.com/en-us/sccm/desktop-analytics/privacy)
* Content Source: [sccm/desktop-analytics/privacy.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/privacy.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by PeteHaigh-MSFT** [comment]
Hi team - yes the Diag Data is covered, but we don't document the information flowing via "Configuration Manager synchronizes device collections and deployments plans with Desktop Analytics". This is a net new info flow to our cloud services that didn't exist with Windows Analytics.

**Comment by Ramonin** [comment]
Here is the last email thread and copying Brjann and the rest of the team.

My understanding is this is on for today your time at 3:30 PM PST.

Ramon Infante
Principal Program Manager
M365 and Security Group

Microsoft
Office: +1 (425)538-0610
Mobile: 201-647-4962
ramonin@microsoft.com<mailto:ramonin@microsoft.com>

**Comment by Ramonin** [comment]
@Martin Coetzer<mailto:martinco@microsoft.com> who drives content and docs

Brjann

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Ramon Infante <Ramon.Infante@microsoft.com>
Sent: Monday, December 2, 2019 4:49:33 AM
To: MicrosoftDocs/SCCMdocs <reply@reply.github.com>; MicrosoftDocs/SCCMdocs <SCCMdocs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Brad Tresky <btresky@microsoft.com>; Dino Ciccone <dinoc@microsoft.com>; Nasos Kladakis <atkladak@microsoft.com>; Brjann Brekkan <bbrekkan@microsoft.com>
Subject: RE: [MicrosoftDocs/SCCMdocs] This article needs to be expanded to include Data collected and how its used (#1794)


Here is the last email thread and copying Brjann and the rest of the team.



My understanding is this is on for today your time at 3:30 PM PST.



Ramon Infante

Principal Program Manager

M365 and Security Group



Microsoft

Office: +1 (425)538-0610

Mobile: 201-647-4962

ramonin@microsoft.com<mailto:ramonin@microsoft.com>

**Comment by aczechowski** [comment]
(admin note: I deleted two comments that were inadvertently posted via email)

**Comment by aczechowski** [comment]
Per side discussion with @PeteHaigh-MSFT - we need to also link to ConfigMgr article on [diagnostics and usage data](https://docs.microsoft.com/configmgr/core/plan-design/diagnostics/diagnostics-and-usage-data), which covers what data is shared regarding collections.

**Comment by aczechowski** [comment]
Looks like I fixed this in December but never closed the issue
