### ISSUE TITLE
This page seems to be an article for Hybrid MDM.

### ISSUE THREAD

**Issue by buhibu9** [MicrosoftDocs/SCCMdocs#1804]
Since it is unsuitable for Co-Management, please add a notice at the top of the page as soon as possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 202c6d0a-3d3f-f5dc-b115-4542f167c08a
* Version Independent ID: 91a495ab-5f58-bdf9-1147-d1ab98900b28
* Content: [Enroll devices with device enrollment manager  - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/enroll-devices-with-device-enrollment-manager#add-a-device-enrollment-manager)
* Content Source: [sccm/mdm/deploy-use/enroll-devices-with-device-enrollment-manager.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/enroll-devices-with-device-enrollment-manager.md)
* Product: **configuration-manager**
* Technology: **configmgr-hybrid**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @buhibu9 for the feedback. We added a deprecation notice to the top of articles that had a significant number of page views, but not all hybrid MDM articles. But easy enough to add one here, I'll do that now.

**Comment by aczechowski** [comment]
The article will update live tomorrow with a notice at the top.

**Comment by buhibu9** [comment]
Hi aczechowski,
Thank you for your quick response!
