### ISSUE TITLE
Data-Warehouse: Error opening reports 

### ISSUE THREAD

**Issue by hbaes** [MicrosoftDocs/SCCMdocs#1805]
When following the work around exactly like described:
- IIS is not installed if you run Database on separate Server (as already mentioned)
- SQL will start up any more because of the following error: "Unable to load user-specified certificate [Cert Hash(sha1) "800659287F252B28A973C7F80AA00B8679916202"]. The server will not accept a connection. You should verify that the certificate is correctly installed. See "Configuring Certificate for Use by SSL" in Books Online."
What´s missing is the Read Assignment to the certificates private key for the SQL Service account asdescribed here: https://manage.accuwebhosting.com/knowledgebase/2924/Fix--Server-Unable-to-load-user-specified-certificate-The-server-will-not-accept-a-connection.html

br
Harald Bäs-Fischlmair
unicredit Services

(admin edit: adding article metadata for proper link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a4274db-5f5b-c169-c69e-68146e92836f
* Version Independent ID: a28966e9-88cc-6910-c270-7f14818f832a
* Content: [Data warehouse - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/data-warehouse#error-opening-reports)
* Content Source: [sccm/core/servers/manage/data-warehouse.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/data-warehouse.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @hbaes for the feedback

**Comment by aczechowski** [comment]
I made a change for this issue. It should publish later today. Thanks again for the feedback
