### ISSUE TITLE
What fixes are in this release?

### ISSUE THREAD

**Issue by DavidHBaur** [MicrosoftDocs/SCCMdocs#1811]
Where do we find fixes that have been resolved by this release?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 665f93d6-3748-8bf8-c0db-fac2a4702d61
* Version Independent ID: 527f481e-e003-6b4d-a2d2-273dc1134b01
* Content: [Technical preview 1906 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/2019/technical-preview-1906)
* Content Source: [sccm/core/get-started/2019/technical-preview-1906.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/2019/technical-preview-1906.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by mestew** [comment]
@davidhbaur I'm pretty sure this is what you are looking for: https://support.microsoft.com/help/4514258 
It just published today. Sometimes the fix list KB comes a little later. We will get this added to the What's new page for 1906 as well. https://docs.microsoft.com/sccm/core/plan-design/changes/whats-new-in-version-1906

If this isn't what you were looking for, feel free to reopen the issue. 
#please close
