### ISSUE TITLE
LTSB not supported list should grow

### ISSUE THREAD

**Issue by MSFTJerryAb** [MicrosoftDocs/SCCMdocs#1823]
The LTSB not supported list should ideally grow, noting that no cloud services are supported. Would be nice to continue to add things like CMG, Desktop Analytics, Azure AD authentication, Windows Store for Business, etc. to clarify that the list of unsupported features will continue to increase.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b4e6c18-babd-5009-0af4-786fa91e3d5a
* Version Independent ID: b42f0c87-a277-185c-1b61-ec20f1367a40
* Content: [Introduction to the Long-Term Servicing Branch - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/understand/introduction-to-the-ltsb)
* Content Source: [sccm/core/understand/introduction-to-the-ltsb.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/introduction-to-the-ltsb.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @MSFTJerryAb, good feedback 😄

**Comment by aczechowski** [comment]
I revised this article, it will publish live on Monday around 11am Pacific
