### ISSUE TITLE
Press ENTER for network boot service

### ISSUE THREAD

**Issue by PriyaranjanSCCM** [MicrosoftDocs/SCCMdocs#1828]
Hello,

The message "Press ENTER for network boot service" is for very short time. How can we increase the response time?

Many thanks!

**Comment by aczechowski** [comment]
Hi @PriyaranjanSCCM, that prompt is usually from the hardware itself, not Configuration Manager. Please contact your hardware vendor, or use one of the following options for the best support:

- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
