### ISSUE TITLE
Typo in article

### ISSUE THREAD

**Issue by janvik207** [MicrosoftDocs/SCCMdocs#1829]
https://docs.microsoft.com/en-us/sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system

Location:
Set Windows default apps and associations

Typo in step 4.
DefaultAppAssocations.xml is missing an i.
Should be 
DefaultAppAssociations.xml

(admin edit: adding metadata to link to article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfe3442-b59d-0d77-d9af-f18e787ec99d
* Version Independent ID: 60cb54a2-d1fd-92b5-b027-de8a85c7af64
* Content: [Create an OS upgrade task sequence - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system#set-windows-default-apps-and-associations)
* Content Source: [sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @janvik207, good catch!
I just submitted a fix that will publish live in about an hour with our daily publishing process.

In the future, you can submit this change yourself! For more information, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute). 😉
