### ISSUE TITLE
SMSTSSoftwareUpdateScanTimeout default value

### ISSUE THREAD

**Issue by codaamok** [MicrosoftDocs/SCCMdocs#1838]
In the flowchart, it suggests the default value for SMSTSSoftwareUpdateScanTimeout  is 60 minutes. Whereas [here](https://docs.microsoft.com/en-us/sccm/osd/understand/task-sequence-steps#BKMK_InstallSoftwareUpdates) states it's 30 minutes. I'm keen to update the doc, I just don't immediately know which is the default.

(admin edit, fixing metadata to [actual] target article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1187d55d-d8b3-ebc8-37e8-8de14807be4e
* Version Independent ID: daff4a99-10ac-b424-f08a-9024407e667a
* Content: [Task sequence steps - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/understand/task-sequence-steps#BKMK_InstallSoftwareUpdates)
* Content Source: [sccm/osd/understand/task-sequence-steps.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/understand/task-sequence-steps.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by codaamok** [comment]
I'm pretty sure it's 60mins because I think I saw a Tip mentioning it changed in 1803 or something. :)

**Comment by aczechowski** [comment]
Confirmed, 60 is the new default.
