### ISSUE TITLE
Upgrade assessment condition incorrect

### ISSUE THREAD

**Issue by Xavantsa** [MicrosoftDocs/SCCMdocs#1840]
_SMSTSOSUpgradeActionReturnCode should be continue if condition "equals" 3247440400 because that means there was no issues found.

(admin edit: adding metadata to link with assumed article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfe3442-b59d-0d77-d9af-f18e787ec99d
* Version Independent ID: 60cb54a2-d1fd-92b5-b027-de8a85c7af64
* Content: [Create an OS upgrade task sequence - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system#perform-an-inline-compatibility-assessment)
* Content Source: [sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Xavantsa, I'm assuming you're referring to this section to [Perform an inline compatibility assessment](https://docs.microsoft.com/sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system#perform-an-inline-compatibility-assessment). The condition applies to the Run Command Line step, which fails the task sequence with that return code. So you only want it to happen when the result of the assessment is anything other than success.

I'll keep this issue open, as given your question, I think we should clarify it a bit to explain the use of the Run Command Line step. Thanks for the feedback.

**Comment by aczechowski** [comment]
I made a change for this to help clarify, it should publish live later today. Thanks again for the feedback! 😄
