### ISSUE TITLE
Primary site content library using multiple drives seems incorrect

### ISSUE THREAD

**Issue by marcgoff** [MicrosoftDocs/SCCMdocs#1843]
The statement in the central administration site section doesn't seem correct.

"Similar to the content library on other site servers and on distribution points, when the drive that contains the content library runs out of available disk space, the content library automatically spans to the next available drive."

In practice on Current branch 1902, it does not seem to expand to a new drive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92260657-2102-c15f-a844-5fa3aff64aae
* Version Independent ID: a4597d2d-9441-61f2-718d-c0a54a46d3fd
* Content: [The content library - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/the-content-library#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/the-content-library.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/the-content-library.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @marcgoff for the feedback. I'm checking with the engineering team whether this is a doc bug that's been there for years, or a product bug. I found the same wording in the [SCCM 2012 R2 docs](https://docs.microsoft.com/en-us/previous-versions/system-center/system-center-2012-R2/gg682083%28v%3dtechnet.10%29#about-the-content-library-on-the-central-administration-site).

**Comment by aczechowski** [comment]
Response from engineering is that's how it should behave. If it's not, then there's something wrong (may not necessarily be a product bug, it could be something environmental). You have a few options:
- File [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback). This goes directly to the engineering team, who can triage and raise as a bug if warranted.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by marcgoff** [comment]
Thanks for digging into it Aaron. I have submitted some product feedback.
