### ISSUE TITLE
Request for additional details to be added to this article

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/SCCMdocs#1845]
- Will the Edition Upgrade convert MAK client to KMS?
- If the client's OS is not activated will it perform an edition upgrade?
- If so will it activate the client at that time?
- What about clients using an OEM key, how will this handle the process?
- If the client is not pointing at a KMS server how will you get that information to the client with this policy?
- 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f49b9244-7797-8fbb-afb9-dd245692be2f
* Version Independent ID: 5c7d7bde-2fe5-54f6-55fe-db4b2631f9a7
* Content: [Upgrade Windows devices to a different version - Configuration Manager](https://docs.microsoft.com/en-us/sccm/compliance/deploy-use/upgrade-windows-version)
* Content Source: [sccm/compliance/deploy-use/upgrade-windows-version.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/compliance/deploy-use/upgrade-windows-version.md)
* Product: **configuration-manager**
* Technology: **configmgr-compliance**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Barleyologist, thanks for taking the time to share this with the Configuration Manager documentation team. This article is about the ConfigMgr feature to trigger edition upgrade, which is a Windows API. For more information, see the following articles in the Windows doc library:
- [Plan for volume activation](https://docs.microsoft.com/windows/deployment/volume-activation/plan-for-volume-activation-client)
- [Windows 10 edition upgrade](https://docs.microsoft.com/windows/deployment/upgrade/windows-10-edition-upgrades)

I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

(p.s. I will add the two URLs above to a "see also" section at the bottom of the article)
