### ISSUE TITLE
Non-production/dev environment

### ISSUE THREAD

**Issue by epoch71** [MicrosoftDocs/SCCMdocs#1848]
Does a non-production/dev environment require an explicit licence?  By non-prod I mean an instance of Configuration Manager purely for testing current branch upgrading etc.  Not servicing production clients and having a limited footprint.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3b9a7fa-9585-a2fb-590e-0b74e128035d
* Version Independent ID: 9aae8e97-de68-c274-b4c6-cd925568c75b
* Content: [Product and licensing FAQ - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/understand/product-and-licensing-faq#feedback)
* Content Source: [sccm/core/understand/product-and-licensing-faq.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/product-and-licensing-faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @epoch71, good question. I'll answer here, and then also update the article to include this as a FAQ.

The short answer is yes, you need an explicit license. You'd need to check with your account team to determine if your actual licensing agreement covers multiple instances in multiple environments. For a temporary environment, you can use the evaluation version for 180 days. For a lab environment, you can use the technical preview branch. Tech preview has the same functionality as current branch, but has some limitations in terms of scale and supported platforms.
