### ISSUE TITLE
Programmatic access to management insights

### ISSUE THREAD

**Issue by bmilbauer** [MicrosoftDocs/SCCMdocs#1849]
Can management insights be interacted with via scripting? We want to automate health checks for a large number of SCCM environments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2e6be06-feac-a941-72bc-16ca5c983bd6
* Version Independent ID: 6fd43cff-1c96-6111-5689-a7d6d4a86302
* Content: [Management insights - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/management-insights#feedback)
* Content Source: [sccm/core/servers/manage/management-insights.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/management-insights.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@bmilbauer I don't see any MI PowerShell cmdlets in the docs. I also don't see references to MI in the API docs. I am double checking this with the PG for you as well.

**Comment by mestew** [comment]
@bmilbauer 
Unfortunately, I've confirmed there aren't any PowerShell cmdlets or anything in the API for interacting with Management Insights. It would be a cool future addition to Configuration Manager though. Hit up [Configuration Manager UserVoice](https://configurationmanager.uservoice.com) and put it in as a product suggestion.
