### ISSUE TITLE
WinPE still needed on SMS Provider?

### ISSUE THREAD

**Issue by CaptainUnlikely** [MicrosoftDocs/SCCMdocs#1850]
Since the WinPE component has been split from the ADK, is WinPE still required to be installed on the SMS Provider or does the ADK alone suffice?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f4fb1c-8d88-ff2f-813a-3f2e7a9a6cfc
* Version Independent ID: df2889fa-04c0-163b-0bae-050990930c81
* Content: [OSD infrastructure requirements - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/plan-design/infrastructure-requirements-for-operating-system-deployment#windows-adk-for-windows-10)
* Content Source: [sccm/osd/plan-design/infrastructure-requirements-for-operating-system-deployment.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/plan-design/infrastructure-requirements-for-operating-system-deployment.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @CaptainUnlikely, thanks for the question. Both components are required on the provider.
