### ISSUE TITLE
Admin permission prereqs

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#1852]
Any catalog operations (add/edit/subscribe/delete/sync etc) all require SMS_SITE perms, so SUM admins may not be able to right-click and “sync now” for those.

Update operations (publish content for an update) should work as long as user has access to individual updates (SUM admins).

From internal [BUG 5281372](https://msazure.visualstudio.com/Configmgr/_workitems/edit/5281372)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 054797d3-c4d8-2c2e-9940-e8763f6f3881
* Version Independent ID: 9751d801-35de-ebd8-29ea-57e459f845dc
* Content: [Enable third party updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/third-party-software-updates#prerequisites)
* Content Source: [sccm/sum/deploy-use/third-party-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/third-party-software-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by TrevorDukeMS** [comment]
Starting with 1909TP the permissions required for the Sync Now option for 3rd party catalogs have changed to match the Sync permissions for the main software updates node. Specifically, the action requires the Modify right on the SMS_SoftwareUpdate class.
