### ISSUE TITLE
Functional level discrepancy

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#1853]
This article says that Server 2008 is supported, yet the [List of prerequisite checks](https://docs.microsoft.com/sccm/core/servers/deploy/install/list-of-prerequisite-checks) says Server 2008 R2 is the minimum.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c40b1d1-a46d-9e33-8bd5-f79e420d5d9c
* Version Independent ID: d90820d6-bd8f-34d9-68ac-5300bf4fb516
* Content: [Supported Active Directory domains - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/support-for-active-directory-domains#feedback)
* Content Source: [sccm/core/plan-design/configs/support-for-active-directory-domains.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/support-for-active-directory-domains.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by jpcast88** [comment]
@aczechowski Which article would need to be updated? I'm guessing the "prereqs article" since the end of support date for 2008/2008R2 has not been reached yet.

**Comment by aczechowski** [comment]
Hi @jpcast88, sorry I missed this response! I checked with the engineering team, and our prereq check is still for 2003. 😮 So I suppose technically both articles should be updated to state 2003 domain functional level. (That seems a little weird to do, but it's honest and accurate.) 

There was also a recent email thread about forest functional level. I honestly don't think it matters, but suppose we could add that as well in the same context. 

@mestew any opinions?
