### ISSUE TITLE
Additional "See also" Microsoft.ConfigurationManagement.Messaging reference, the Microsoft.ConfigurationManagement.Messaging package includes support for creating Schedule Tokens

### ISSUE THREAD

**Issue by DavstewMS** [MicrosoftDocs/SCCMdocs#1864]
https://docs.microsoft.com/en-us/previous-versions/system-center/developer/mt746124(v=cmsdk.12)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5438ae14-23ec-d0f3-db29-19f67d1c8138
* Version Independent ID: 300a606e-472d-28ac-df90-d7bdce8cb98f
* Content: [Configuration Manager Schedules](https://docs.microsoft.com/en-us/sccm/develop/core/understand/about-configuration-manager-schedules#feedback)
* Content Source: [sccm/develop/core/understand/about-configuration-manager-schedules.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/core/understand/about-configuration-manager-schedules.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I submitted a change for this, it will publish live later today
