### ISSUE TITLE
incorrect info about Azure VM pricing/sizing

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/SCCMdocs#1865]
The section on Azure cloud services says it uses an A2 VM.
https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/plan-cloud-management-gateway#virtual-machine

Following the link to the azure pricing calculator and choosing Azure Cloud Services, there is no option for an A2 VM.  So is it a VM or is it a cloud service?  How do I obtain accurate pricing if the calculator doesn't reflect what the article states?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778368d0-1054-678c-4d74-5dce1b5826c8
* Version Independent ID: aaac7308-66e6-66f0-8248-14e1505c11a6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/plan-cloud-management-gateway#virtual-machine)
* Content Source: [sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @poortom1004, it's an A2 V2 VM. If you add a VM to the pricing calculator, you'll see A2 V2 in the list of instances, for example:

![image](https://user-images.githubusercontent.com/26784733/64721467-6ad93400-d481-11e9-8148-a156cd068094.png)

Some regions may not support this VM instance, but most of the ones I flipped through showed it as an option.

**Comment by poortom1004** [comment]
So it's a virtual machine, not a cloud service then?  The article is misleading if that's the case.

**Comment by aczechowski** [comment]
Hi @poortom1004, can you help me understand how you think it's misleading? The Cost section introductory statement is "CMG uses the following Azure components, which incur charges to the Azure subscription account:" Then the first subsection is named "virtual machine" and mentions the term or acronym "VM" six times. Do you have any suggestions on how I can clarify?

**Comment by poortom1004** [comment]
The very first bullet
"CMG uses Azure Cloud Services as platform as a service (PaaS)"

**Comment by poortom1004** [comment]
if it's not a cloud service, then I would suggest removing that part.

**Comment by poortom1004** [comment]
I realize where I may have not been clear now.  The Azure Calculator has a section under Compute called Cloud Services.  This is why I was thinking there was something wrong with the document.
