### ISSUE TITLE
Unclear on Pre-Caching 

### ISSUE THREAD

**Issue by jeffdfield** [MicrosoftDocs/SCCMdocs#1868]
It says "To determine which driver package it downloads during pre-caching, the client evaluates the model against the Win32_ComputerSystemProduct WMI property." It doesn't say which properties it uses. Name and Version often contain information. Lenovo uses version where as Microsoft Surface devices use Name. So the question is which does it use? All 3?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4313411e-8322-21b1-da7f-4a1f21c58b10
* Version Independent ID: cfc0fe3f-667f-ff01-b623-75a315b8e1f6
* Content: [Configure pre-cache content - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/configure-precache-content#feedback)
* Content Source: [sccm/osd/deploy-use/configure-precache-content.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/configure-precache-content.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by jeffdfield** [comment]
@aczechowski, thanks for the clarification. Does this support wildcards? The reason I ask is because Lenovo does it differently. If it can't support wildcards, can we match on either version or name? We have 7 different "names" for the M92P version but only one driver package from Lenovo for the M92P. Several other models are the same story.

**Comment by aczechowski** [comment]
@jeffdfield, I'll check on the wildcard support. Please file [product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) if you'd like to see it match on other properties.

@jguevarajr, the behavior for a required deployment is different, so I don't think it applies here. But I'm double-checking with the engineering team. (BTW, in the future, please create a new, separate issue/feedback instead of commenting on an existing issue. It's difficult to manage the separate topics in a single thread.)

**Comment by aczechowski** [comment]
@jeffdfield it looks like you can use a wildcard
@jguevarajr pre-caching works for required too

**Comment by snalamalpu** [comment]
I have tried the Task sequence pre-cache feature in SCCM CB 1906, for an in-place upgrade we have set of driver packages (some 10 models) and apply the condition to check the WMI class for "Name" in "Win32_ComputerSystemProduct" download only that particular driver package. However, it is being pre-caching the complete content of all Driver packages that are in TS, not the required one...Did I miss anything here?

FYI..TS deployment settings that I have set was...
General: selected "Pre-download content for this task sequence"
Deployment Settings: Set "Available"
Scheduling: No expiry
User experience: select all the options except "Internet-based clients"
Distribution points: selected "Download content locally when needed by the running task sequence"

**Comment by aczechowski** [comment]
Hi @snalamalpu, I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
