### ISSUE TITLE
ENV should not be used as a site code

### ISSUE THREAD

**Issue by paulwetter** [MicrosoftDocs/SCCMdocs#1871]
ENV should not be used as a sitecode either.  This can result in contention with the **Env** PSDrive provider already in use in PowerShell and would probably lead to issues using the CM powershell module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea680ada-dfb2-f789-8af2-d5674618a43d
* Version Independent ID: 796a8e22-0815-6a18-ac51-b92100c41170
* Content: [Prepare to install sites - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/prepare-to-install-sites#bkmk_sitecodes)
* Content Source: [sccm/core/servers/deploy/install/prepare-to-install-sites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/prepare-to-install-sites.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@paulwetter 
Hey Paul, I'm verifying if **ENV** should be added to reserved names list for SCCM site codes. 
Thanks for the heads up.

**Comment by mestew** [comment]
@paulwetter
Confirmed. The document will be updated in the next day or two.
