### ISSUE TITLE
Clarification on prerequisites for DA

### ISSUE THREAD

**Issue by ajaswal1982** [MicrosoftDocs/SCCMdocs#1874]
At the moment, for the DA that I am testing, I have an Azure AD Tenant with a valid Subscription and along with that I have a Trial Office 365 E5 Subscription with License assigned to the Tenant Admin. Plus ConfigMgr is installed with 1902 + Hotfix and the Windows 10 Enterprise OSs are Eval 1903 with the latest patches/cumulative updates.

I don't read this anywhere in the documentation, but do we need to setup Hybrid Azure AD Join, where the devices are Hybrid Azure AD Joined + EMS E5 Subscription to get Azure AD Premium P2 service and Intune and assign Windows 10 Enterprise E3/E5 Licenses for this?

My devices are showing up in the View recent data pane, but they have not reported anything in the DA Dashboard and in ConfigMgr it is saying Awaiting Enrollment.

It has been 48 hours.

Do I need to wait for full 72 hours or more? As the message says, "We are processing your data. If this message persists for more than 72 hours, you may be having connection health issues".
The devices are showing all successful in all the communication in ConfigMgr.

Configuration wise on Azure side and ConfigMgr side, I have followed this documentation as it is and all the permissions and settings seem to be correct.

Also, getting an error in the data currency flyout as attached.

Any assistance here would be appreciated. Thanks in advance.

![image](https://user-images.githubusercontent.com/55318393/64908268-7051ab00-d71b-11e9-9cb4-94a39c4760a5.png)

* ID: 2d8d7ece-b19f-1431-a619-e57ce6469c28
* Version Independent ID: 86a3d7a5-695b-d3d9-498c-e6b6e03169f8
* Content: [Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/sccm/desktop-analytics/overview#feedback)
* Content Source: [sccm/desktop-analytics/overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by ajaswal1982** [comment]
Any updates to this question?

**Comment by aczechowski** [comment]
Thanks @ajaswal1982 for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by aczechowski** [comment]
p.s. hybrid Azure AD join isn't a prerequisite
