### ISSUE TITLE
Confusing information

### ISSUE THREAD

**Issue by AndyChips** [MicrosoftDocs/SCCMdocs#1875]
Why does this document describe how to install and configure the Application Catalog when in the previous section we're told how to remove it because it has been deprecated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b63a5c3-b4c4-d60b-fac9-f625edb74022
* Version Independent ID: ca712b3a-aa29-9ef2-dbf0-d0a8589245d1
* Content: [Plan for application management - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/plan-design/plan-for-and-configure-application-management#bkmk_remove-appcat)
* Content Source: [sccm/apps/plan-design/plan-for-and-configure-application-management.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/plan-design/plan-for-and-configure-application-management.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Purely for customers that might still be on an earlier but still supported version of ConfigMgr: https://docs.microsoft.com/sccm/core/servers/manage/updates#supported-versions
