### ISSUE TITLE
DOINC "beta" label in the console.  

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/SCCMdocs#1877]
DOINC doesn't appear to be tagged with a "beta" label in the console.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3da55fd-6184-9baa-9278-9d807a7e44db
* Version Independent ID: 115bdf2d-7766-0053-11b2-5d36260fe4f8
* Content: [Delivery Optimization In-Network Cache - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/delivery-optimization-in-network-cache#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/delivery-optimization-in-network-cache.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/delivery-optimization-in-network-cache.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @russrimm for the feedback, the linked license terms does state that it's "beta". I'll check with the PM how we want to talk about this right now.

**Comment by aczechowski** [comment]
Fixed with #1899, thanks @kerimhanif! 
The change should publish later this morning
