### ISSUE TITLE
Define Kbps

### ISSUE THREAD

**Issue by jn007** [MicrosoftDocs/SCCMdocs#1878]
Kbps = Kilobits
KBps = Kilobytes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f74f4a-560f-2510-1ae8-fd3976a2197e
* Version Independent ID: 0851f834-e9a1-d0a6-ee60-934bcd3a79fe
* Content: [Client settings - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/deploy/about-client-settings#feedback)
* Content Source: [sccm/core/clients/deploy/about-client-settings.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/about-client-settings.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @jn007, the [Microsoft Style Guide](https://docs.microsoft.com/style-guide/acronyms) is to not define common industry acronyms that are in the [American Heritage dictionary](https://ahdictionary.com/word/search.html?q=kbps).

**Comment by jn007** [comment]
Thank you for the reply.  The Microsoft Style Guide also recommends spelling the term the first time an acronym is used in a document:

https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/bits-bytes-terms

This suggestion would be in line with APA 6th edition style guidelines as well.

I logged this entry because I found a discrepancy in an industry book authored by: Kerrie Meyler, Gerry Hampson, Saud Al-Mishari, Greg Ramsey, Kenneth van Surksum, Michael Gottlieb Wiles.

https://books.google.com/books?id=TrBVDwAAQBAJ&pg=PT426&lpg=PT426&dq=sccm+client+settings+bits+kilobit+or+kilobyte+default&source=bl&ots=EwzFaLvTvL&sig=ACfU3U2jEhoAaUfM6i1-xMUKBX3TTOQ1fg&hl=en&sa=X&ved=2ahUKEwjf0ODJ19XkAhV9GTQIHTSdDKQQ6AEwCnoECAsQAQ#v=onepage&q=sccm%20client%20settings%20bits%20kilobit%20or%20kilobyte%20default&f=false

Thanks for your time.
