### ISSUE TITLE
Content and Title Don't Match?

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/SCCMdocs#1879]
The title of the page is "Recommended Hardware" But more than half of the page is software and software settings.  Maybe split out a new page as "Recommend Configuration Settings" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e67ddd45-90df-32cd-3cbe-9e1443b2540f
* Version Independent ID: dee7fcb8-a7b7-e5a1-9c04-c113805be0da
* Content: [Recommended hardware - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/recommended-hardware#feedback)
* Content Source: [sccm/core/plan-design/configs/recommended-hardware.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/recommended-hardware.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @Skatterbrainz for the feedback, but can you clarify further? It looks like mostly hardware configurations (memory, processor, disk) configurations to me. There are a few software settings, like for WSUS app pools, but that's relatively minimal in context of the larger article content.

**Comment by Skatterbrainz** [comment]
nix this one.  I was confusing it with another page I had open at the same time, with 3 people talking to me, 2 dogs barking and an empty wine glass that was crying for a refill.  All good now. :)

**Comment by mestew** [comment]
@Skatterbrainz  I see our lives are very similar =)
