### ISSUE TITLE
Windows 7 RTM Support Unclear

### ISSUE THREAD

**Issue by monkeyskullfire** [MicrosoftDocs/SCCMdocs#1882]
This page does not list whether Windows 7 RTM (AKA SP0) is supported and the list of deprecated/unsupported OSes also does not list Windows 7 RTM.  This leaves it unclear whether it's supported.  Please update either page to indicate whether SCCM currently supports Windows 7 RTM or has deprecated support for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86d400f-d2a6-d50b-8d1f-18893af56d67
* Version Independent ID: 793a7196-8549-329c-bad5-c6b33f466ae7
* Content: [Supported clients and devices - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/supported-operating-systems-for-clients-and-devices)
* Content Source: [sccm/core/plan-design/configs/supported-operating-systems-for-clients-and-devices.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/supported-operating-systems-for-clients-and-devices.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @monkeyskullfire that's called out in the [supported configurations](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/supported-configurations) overview article:

> The products and technologies that are described in the following topics are supported by Configuration Manager. However, their inclusion in this content does not imply an extension of support for any product beyond that product's individual support lifecycle. Products that are beyond their support lifecycle are not supported for use with Configuration Manager. For more information about Microsoft Support Lifecycles, visit the [Microsoft Support Lifecycle](https://go.microsoft.com/fwlink/p/?LinkId=208270) website.

**Comment by monkeyskullfire** [comment]
<facepalm>  Thanks Aaron!
