### ISSUE TITLE
SUSDB Replica on a WSUS Server in an untrusted domain

### ISSUE THREAD

**Issue by RobinSherwood100** [MicrosoftDocs/SCCMdocs#1883]
Our setup includes a WSUS Server and a remote SUSDB as well as a replica set up on a second WSUS Server in an untrusted domain.

I assume we need to grant the WSUS Server in the untrusted domain with certain permissions to continuing the indexing operation - and the WSYNCMGR.log is demonstrating that the indexing failed.

How do we address this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38bacc7a-d602-e825-bff3-5d9232f03f72
* Version Independent ID: 7de8c181-3252-de71-bdfe-70b68dd966c5
* Content: [Software updates maintenance - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/software-updates-maintenance#feedback)
* Content Source: [sccm/sum/deploy-use/software-updates-maintenance.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/software-updates-maintenance.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
You can add the indexes manually and run the cleanup for obsolete updates via script. We recently added a known issues section for 1906 changes. For a WSUS in an untrusted domain, you can use the same workaround: https://docs.microsoft.com/sccm/sum/deploy-use/software-updates-maintenance#remove-obsolete-updates-from-the-wsus-database
