### ISSUE TITLE
Additional costs associated with this feature

### ISSUE THREAD

**Issue by blyons-ga** [MicrosoftDocs/SCCMdocs#1885]
While this sounds like a great opportunity to incorporate off-site users into the environment, there's no notation of cost, outside of the Intune licensing, with regards to data transfers and/or other options.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778b6484-ea66-9518-778d-cea65fd183fa
* Version Independent ID: 1ea23258-33b6-738a-cc46-a4059e0d3f42
* Content: [Tutorial: Enable co-management for internet devices - Configuration Manager](https://docs.microsoft.com/en-us/sccm/comanage/tutorial-co-manage-new-devices#feedback)
* Content Source: [sccm/comanage/tutorial-co-manage-new-devices.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/tutorial-co-manage-new-devices.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @blyons-ga, aside from the licensing for Azure, Intune, and Configuration Manager, the only other associated cost is for the cloud management gateway service in Azure. Guidance for estimating costs for that service are detailed in the article to [plan for the CMG](https://docs.microsoft.com/sccm/core/clients/manage/cmg/plan-cloud-management-gateway#cost).

As this article is a tutorial to get started with the feature, I'm closing this issue.
