### ISSUE TITLE
'SchUseStrongCrypto' and primary site server

### ISSUE THREAD

**Issue by jose-camacaro** [MicrosoftDocs/SCCMdocs#1891]
From the following:

"...Make sure to set the following registry keys on any computer that communicates across the network with a TLS 1.2-enabled system. For example, Configuration Manager clients, or any remote site system role that's not installed on the site server."

I'm particularly interested on the "not installed on the site server" part. What are the negative consequences of creating and configuring 'SchUseStrongCrypto' registry setting on a server hosting a 'Site Server' role?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8474fb4-44ec-a664-ce17-adaeb0bed730
* Version Independent ID: a2e22bfa-ef98-a824-1e35-ae62737950cd
* Content: [How to enable TLS 1.2 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/security/enable-tls-1-2#feedback)
* Content Source: [sccm/core/plan-design/security/enable-tls-1-2.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/security/enable-tls-1-2.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @jose-camacaro! 😄 
Sorry for the confusion, I obviously need to reword that to clarify.
It's just referring to any site system that is not the site server, thus a remote site system.
There's no negative consequence of setting this value on the site server itself
