### ISSUE TITLE
Missing video file from link

### ISSUE THREAD

**Issue by StephenMatthewsBA** [MicrosoftDocs/SCCMdocs#1894]
Link to video not available..  Where to look up your active Software Assurance agreement (starting at 43 seconds)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b91889c-f6ad-7c70-9af9-404217959982
* Version Independent ID: bbb6de08-1b45-73b5-585f-3c460b359c22
* Content: [Licensing and branches - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/understand/learn-more-editions#feedback)
* Content Source: [sccm/core/understand/learn-more-editions.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/learn-more-editions.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @StephenMatthewsBA, sorry for the hiccup, but it's working ok for me now.
