### ISSUE TITLE
Forefront Endpoint Protection 2010 has stopped supporting

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/SCCMdocs#1896]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/SCCMDocs.zh-cn/issues/5
The user is making a suggestion on the original documentation.

*The comment below was Machine translated*
@TANSHUAI1993 commented 31 minutes ago — with docs.microsoft.com
Forefront Endpoint Protection 2010 has stopped supporting and is no longer in the WSUS catalog. Whether the document should replace Forefront Endpoint Protection 2010 with System Center Endpoint Protection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a20a2b3-4bee-2b91-5f23-b6e6fcb23f6e
* Version Independent ID: e38ad0a6-cff2-f098-ec97-6fda24d681d1
* Content: [Endpoint Protection malware definitions - Configuration Manager](https://docs.microsoft.com/en-us/sccm/protect/deploy-use/endpoint-definitions-configmgr#feedback)
* Content Source: [sccm/protect/deploy-use/endpoint-definitions-configmgr.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/endpoint-definitions-configmgr.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thank you @TANSHUAI1993 for the feedback. Yes, we need to remove references to Forefront from our documentation.

**Comment by aczechowski** [comment]
I made changes to this article, thus the issue closed.
