### ISSUE TITLE
missing RSS change log subscription

### ISSUE THREAD

**Issue by MSJensG** [MicrosoftDocs/SCCMdocs#1897]
we should add RSS change log subscription so that customer can subscribe and get information if changes are happen.

Example:

https://docs.microsoft.com/en-us/office365/enterprise/urls-and-ip-address-ranges

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c5e66c1-d90f-2a99-cd61-a5a4c7560c65
* Version Independent ID: e48e6c28-53b9-79bd-64ba-f30e7728fb1b
* Content: [Internet access requirements - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/network/internet-endpoints#feedback)
* Content Source: [sccm/core/plan-design/network/internet-endpoints.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/network/internet-endpoints.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @MSJensG for the feedback. This idea is related to documentation, but would require some engineering effort. We have a [UserVoice item](https://configurationmanager.uservoice.com/forums/300492/suggestions/38390521) tracking the same, so I'm going to close this issue as a duplicate. Please encourage others to vote up the UVI.

**Comment by aczechowski** [comment]
A workaround is to use the docs search functionality to be [notified of any changes](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_notifications) to the article.

So you could use this RSS URL for this specific article:

`https://docs.microsoft.com/api/search/rss?search=%22internet+access+requirements+-+configuration+manager%22&locale=en-us&%24filter=scopes%2Fany%28t%3A+t+eq+%27ConfigMgr%27%29`

(Note: the 'locale' parameter is required, but you can change from 'en-us' if necessary.)
