### ISSUE TITLE
No such option: Include autorun.inf file on media

### ISSUE THREAD

**Issue by heldley** [MicrosoftDocs/SCCMdocs#1900]
Hi,

We are running 1902, but cannot find this option when creating new boot media "Include autorun.inf file on media"
Is there anything we need to do to make it visible after 1902 upgrade?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4dbcfec-5ab9-a896-c00c-579a443423ab
* Version Independent ID: 08236cde-a689-3806-aab0-271011e4f6fd
* Content: [Create bootable media - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/create-bootable-media#feedback)
* Content Source: [sccm/osd/deploy-use/create-bootable-media.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/create-bootable-media.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @heldley, easy answer: it's a 1906 feature. I'm not sure how our wires got crossed such that we documented it for 1902, but I'll get it fixed up. Sorry for the confusion, and thank you for calling it out.

**Comment by aczechowski** [comment]
I submitted a change which should publish later today

**Comment by heldley** [comment]
Thanks for your quick response

BTW, similar issue on the page for "Create stand-alone media": https://docs.microsoft.com/en-us/sccm/osd/deploy-use/create-stand-alone-media
