### ISSUE TITLE
Clarification on distinct test and production Azure AD environments, but single centralized Azure hosting subscription

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/SCCMdocs#1902]
Hi,
I would like more details on how to setup such scenario. For example, having test.onmicrosoft.com with users and devices, and prod.onmicrosoft.com having the Azure subscription where CMG will need to be created ...
- Would have to run Azure Services Wizard in CM twice, creating both server and client app in each AAD tenant?
- Would it make sense to create client app in one AAD and server app in the other?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a99f1b09-f669-e3c8-e9a1-c2594f329e12
* Version Independent ID: b022b0cd-f045-418a-be0e-f15f699f9d35
* Content: [CMG FAQ - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/cloud-management-gateway-faq)
* Content Source: [sccm/core/clients/manage/cmg/cloud-management-gateway-faq.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/cloud-management-gateway-faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @juanand, thanks for the feedback. I checked with engineering on your question:

> Yes, If Azure subscription is associated with another AAD tenant, you will need to onboard CM twice, one for enabling AAD auth against user/devices in the tenant, one for server(web) app (subscription permission) for CMG deployment. (And you are right, client app is actually not necessary for the latter one).

A good clarification that we can add here.

**Comment by MSBeatriz** [comment]
You will need to Cloud Management Azure services. 
One for CMG subscription AAD tenant and other for the other subscription where client AAD resides.
And even the second (CMG AAD) is not required, is requested, cant be avoided on wizard :)
