### ISSUE TITLE
Syntax wrong in WMI example

### ISSUE THREAD

**Issue by bubbletroubles** [MicrosoftDocs/SCCMdocs#1908]
The WMI example 
SELECT * FROM Win32_OperatingSystem WHERE OSArchitecture LIKE '%64%' AND OSLanguage=1033`

has incorrect syntax (the OSLanguage value quotes are incorrect). It should be:

SELECT * FROM Win32_OperatingSystem WHERE OSArchitecture LIKE '%64%' AND OSLanguage=**'1033'**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4313411e-8322-21b1-da7f-4a1f21c58b10
* Version Independent ID: cfc0fe3f-667f-ff01-b623-75a315b8e1f6
* Content: [Configure pre-cache content - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/configure-precache-content#feedback)
* Content Source: [sccm/osd/deploy-use/configure-precache-content.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/configure-precache-content.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @bubbletroubles for catching this. I just submitted a change that should publish tomorrow (Thursday, 3 October) around 11:00 Pacific time.
