### ISSUE TITLE
Defference b/w Defender and SCEP

### ISSUE THREAD

**Issue by mzafzal1** [MicrosoftDocs/SCCMdocs#1909]
Im not satisfied with the above answer regarding differences. According to it Defender is asoftware that detects and stops spyware?? What about malicious software, including viruses, spyware, and other potentially unwanted softwares? Windows Defender doesnt block them? Can you please provide features supported by Defender and SCEP?? Are they both same? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8ceb2cb-2877-aa05-e702-ab78310689e0
* Version Independent ID: c5c1dff8-8e3a-266d-d6ce-e683d1b9f1ff
* Content: [Endpoint Protection client frequently asked questions - Configuration Manager](https://docs.microsoft.com/en-us/sccm/protect/deploy-use/endpoint-protection-client-faq#whats-the-difference-between-endpoint-protection-and-windows-defender)
* Content Source: [sccm/protect/deploy-use/endpoint-protection-client-faq.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/endpoint-protection-client-faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @mzafzal1 for the feedback. That response is unfortunately out of date, as it only applies to the early Windows Defender feature of Windows 8. The current Microsoft Defender built-in to Windows 10 is an industry-leading protection suite. For more information, see [Threat Protection](https://docs.microsoft.com/windows/security/threat-protection/)
