### ISSUE TITLE
DOINC WMI object 

### ISSUE THREAD

**Issue by rdoloto** [MicrosoftDocs/SCCMdocs#1911]
Will there be any way to set these options via WMI/Powershell? It's great this exists but if you have couple hundred DPS it would be great to  set these with wmi and or powershell 

(admin edit: adding metadata to link with main article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3da55fd-6184-9baa-9278-9d807a7e44db
* Version Independent ID: 115bdf2d-7766-0053-11b2-5d36260fe4f8
* Content: [Delivery Optimization In-Network Cache - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/delivery-optimization-in-network-cache)
* Content Source: [sccm/core/plan-design/hierarchy/delivery-optimization-in-network-cache.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/delivery-optimization-in-network-cache.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @rdoloto for the feedback. I was going to just close this as product feedback, but let me double-check with the engineering team first. It's likely there's at least a WMI route.

The catch though is that we're heavily backlogged on SDK/PowerShell docs. So I might be able to share some details here, but I can't promise that it will see formal docs anytime soon. 😢 Just want to set your expectations.

**Comment by aczechowski** [comment]
p.s. I linked this with the main DOINC article, which is what I assume you were reading when you wrote this. Let me know if it was something different.

**Comment by aczechowski** [comment]
There's no PowerShell, file [Product Feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) for that.

For WMI, as is the case for all site roles, it's done via the [SMS_SCI_SysResUse class](https://docs.microsoft.com/sccm/develop/reference/core/servers/configure/sms_sci_sysresuse-server-wmi-class). For example, [Programming the site roles](https://docs.microsoft.com/sccm/develop/osd/about-operating-system-deployment-site-role-configuration#programming-the-site-roles).

Update the SMS_SCI_SysResUse instance for the DP, set the below properties:
- AgreeDOINCLicense, Value = 1
- Flags, Value |= 4 for enabling, Value &= ~4 for disabling
- DiskSpaceDOINC, Value = <number>, Value1 = “Percentage” or “GB”
- RetainDOINCCache, Value = 0 or 1
- LocalDriveDOINC, Value1 = “Automatic”, or “C:”, or “D:”, etc

**Comment by rdoloto** [comment]
Thank you @aczechowski  that's exactly what i was looking to accomplish

**Comment by aczechowski** [comment]
I just added this detail to the MCC article. The change should publish later this afternoon.
