### ISSUE TITLE
Missing step in the connection procedure

### ISSUE THREAD

**Issue by SamuelPoulin** [MicrosoftDocs/SCCMdocs#1915]
After trying Get-CMSite, you shouldn't be able to just do "CD &lt;sitecode&gt;:". As also mentionned by "http://garrettyamada.com/connecting-to-sccm/", you first need to add the site using the following command: 

New-PSDrive -Name [yoursitecode] -PSProvider "AdminUI.PS.Provider\CMSite" -Root "[your SCCM server's FQDN]" -Description "SCCM Site"

After doing so, the SCCM site should be accessible using  "CD &lt;sitecode&gt;:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5e2395b-2e17-1133-8fc3-338b5560950f
* Version Independent ID: add00879-f28c-369d-f02d-55b0625e40c1
* Content: [Connecting with Windows PowerShell - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/core/understand/connecting-to-configuration-manager-with-windows-powershell#feedback)
* Content Source: [sccm/develop/core/understand/connecting-to-configuration-manager-with-windows-powershell.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/core/understand/connecting-to-configuration-manager-with-windows-powershell.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @SamuelPoulin, thanks for the comment. I checked with engineering. When you start PowerShell from the console, it will automatically create the PSDrive as a convenience for the currently connected site. Get-CMSite doesn't do that for you. If you're in a hierarchy, you would need to use the command you suggested to create another PSDrive for another site.

**Comment by aczechowski** [comment]
I made a change for this, it should publish live tomorrow. Basically I ripped out this collection of articles in the core ConfigMgr SDK content, and then made the appropriate updates to the overview article in our PowerShell content: https://docs.microsoft.com/powershell/sccm/overview?view=sccm-ps
