### ISSUE TITLE
v_UpdatePrograms does not exist in SCCM 1902. Is this a new view in 1906 or is this just wrong?

### ISSUE THREAD

**Issue by miaminemo** [MicrosoftDocs/SCCMdocs#1919]
v_UpdatePrograms does not exist in SCCM 1902. Is this a new view in 1906 or is this just wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9aa57e3f-c260-5d55-149a-c5dff5a6aeef
* Version Independent ID: 573abed1-5a6a-3904-06f3-e10547a77a13
* Content: [Sample queries for software updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/core/understand/sqlviews/sample-queries-software-updates-configuration-manager)
* Content Source: [sccm/develop/core/understand/sqlviews/sample-queries-software-updates-configuration-manager.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/core/understand/sqlviews/sample-queries-software-updates-configuration-manager.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @miaminemo, thanks for the feedback. These SQL View articles were copied as-is from ConfigMgr 2012 R2 content. So my assumption is that the view no longer exists in the current branch at all, although I don't know specifically from which version it was removed.

**Comment by ChrisKibble** [comment]
Can confirm doesn't exist in 1906 either.

**Comment by ChrisKibble** [comment]
Doesn't look like it existed in 2012 and was probably a copy/paste that made it's way back from 2007:
https://social.technet.microsoft.com/Forums/en-US/d47da8e7-89d7-4767-846d-7b0562ac5cc3/vupdateprograms-in-sccm-2012?forum=configmanagerapps

I'll remove it and submit a PR.
