### ISSUE TITLE
CMG vs IBCM

### ISSUE THREAD

**Issue by gate502** [MicrosoftDocs/SCCMdocs#1921]
Is a CMG needed for Intune Comanagement or can we configure this if we are using an IBCM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f24ae716-bf27-7d45-cb15-0bc6eea64374
* Version Independent ID: f444ef64-9b7d-999f-3fb3-6ac6cda3ef88
* Content: [Co-management for Windows 10 devices - Configuration Manager](https://docs.microsoft.com/en-us/sccm/comanage/overview#feedback)
* Content Source: [sccm/comanage/overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @gate502, after some discussion with the engineering team, it's accurate as documented. We recommend using the CMG when needed for the second path of co-management for internet-based devices. I'm closing this issue as there's nothing actionable for docs.
