### ISSUE TITLE
Log Analytics data retention costs

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/SCCMdocs#1922]
Regarding data ingestion, I think it is clear that Desktop Analytics as its predecessor is "zero-rated" despite of the pricing tier. 

However about data retention leaves some open ends in the note that says "If your workspace is on the free plan, then Desktop Analytics retains the last 30 days of "daily snapshots" that are collected in the workspace."

The article refers to "Free" pricing tier, but new subscriptions only have "Per GB (2018)" option (https://docs.microsoft.com/en-us/azure/azure-monitor/platform/manage-cost-storage#legacy-pricing-tiers).

If customer has a "Per GB (2018)" plan (only option for new subscriptions), raising the retention bar beyond 30 days would mean cost for Desktop Analytics?
As per "Data Retention" blade note, "31 days of retention is included with your pricing plan. Longer retention will incur additional charges."

Additionally, according to https://docs.microsoft.com/en-us/azure/azure-monitor/platform/manage-cost-storage#legacy-pricing-tiers, Free plans retention is only 7 days, not 30 days as stated in the note.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8d7ece-b19f-1431-a619-e57ce6469c28
* Version Independent ID: 86a3d7a5-695b-d3d9-498c-e6b6e03169f8
* Content: [Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/sccm/desktop-analytics/overview#prerequisites)
* Content Source: [sccm/desktop-analytics/overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Fixed by a private PR that will publish live tomorrow
