### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by parabolic123** [MicrosoftDocs/SCCMdocs#1925]
Can a cloud management gateway be used on non-domain joined computers? We have a number of workgroup servers in our DMZs we'd like to provide security updates to.  Azure AD join isn't an option for us at the moment as our domain functional level is 2003.

If you're using a CMG for software updates, are you charged for data egress on software updates (e.g. OS patches)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778368d0-1054-678c-4d74-5dce1b5826c8
* Version Independent ID: aaac7308-66e6-66f0-8248-14e1505c11a6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/plan-cloud-management-gateway)
* Content Source: [sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @parabolic123,

- CMG supports workgroup clients. There's some mention in the article on [certificates](https://docs.microsoft.com/sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway). The main issue with workgroup clients is configuring the certificates, as there's no centralized way to do that. For more information on managing workgroup clients, see [Workgroup computers](https://docs.microsoft.com/sccm/core/clients/deploy/deploy-clients-to-windows-computers#BKMK_ClientWorkgroup)

- In the [Cost](https://docs.microsoft.com/sccm/core/clients/manage/cmg/plan-cloud-management-gateway#cost) section of this planning article, see the first bullet under **Content storage**: 

    > Internet-based clients get Microsoft software update content from Windows Update at no charge. Don't distribute update packages with Microsoft update content to a cloud distribution point, otherwise you may incur storage and data egress costs.

In both instances, I think this planning article can probably include some more explicit information on these two points. Thanks for the feedback!

**Comment by aczechowski** [comment]
I just submitted a change. Once the pull request merges, this issue will automatically close. The change is in our 2002 release branch, so it won't be live until that publishes, which should be *soon* 😉
