### ISSUE TITLE
Upgrade Readiness migration details

### ISSUE THREAD

**Issue by juanand** [MicrosoftDocs/SCCMdocs#1931]
Few questions around migration scenarios neither in this FAQ not in KB4521815 ...
- My understanding is that last UR snapshot would occur on 31st of January 2020. After that, Log Analytics workspace data retention settings will cause data to go away over time, so customers willing to keep data will need to export it before that happens.
- Customers willing to migrate WA data to Desktop Analytics have to do it *before* Log Analytics data retention policy causes last WA snapshot to go away from the workspace based on their retention policy settings. Otherwise, no data will be there to migrate (i.e. you plan to migrate data on mid February, but your retention is 7 days).
- In order to migrate data at a later time, the section at https://docs.microsoft.com/en-us/sccm/desktop-analytics/faq#im-not-ready-yet-can-i-migrate-after-the-initial-onboarding does not clearly state that customers still must choose the existing WA workspace but turn off the "Do you want to see inputs from Windows Analytics" during enrollment, in "Set up your workspace" step. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ec6aa6e-5695-4efa-c781-0554c112518c
* Version Independent ID: 6d588337-349a-2ae7-c5cc-8e53adf2d9d5
* Content: [FAQ for Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/sccm/desktop-analytics/faq#feedback)
* Content Source: [sccm/desktop-analytics/faq.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by iceorbital** [comment]
Submitted PR 4516 to address his issue
