### ISSUE TITLE
Still in Portal

### ISSUE THREAD

**Issue by Kazzan** [MicrosoftDocs/SCCMdocs#1932]
The Hybrid is deprecated and will be turned off in 2019/11 as stated in service communications. Why the customer which does not onboard to MDM have still choose MDM authority in Intune Wizard between SCCM and Intune?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2e3e98-795c-b869-ac54-bf617960face
* Version Independent ID: 9b7bcb6a-7106-5d64-c8be-bda513f28f99
* Content: [Choose Intune standalone - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/understand/choose-between-standalone-intune-and-hybrid-mobile-device-management)
* Content Source: [sccm/mdm/understand/choose-between-standalone-intune-and-hybrid-mobile-device-management.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/understand/choose-between-standalone-intune-and-hybrid-mobile-device-management.md)
* Product: **configuration-manager**
* Technology: **configmgr-hybrid**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Kazzan, can you please help clarify? Perhaps with a screenshot (just paste in a comment here, or drag/drop). I don't want to assume what I think you're asking.

**Comment by Kazzan** [comment]
Hi @aczechowski, tenant where Office 365 MDM, nor Intune nor SCCM Hybrid was activated. When admin first click on Intune blade, it requires choose MDM authority and offer options Intune and SCCM. But Intune should be only one and correct option, yes? So why SCCM is still there. Click to learn more in this blade take admin to this page saying that hybrid is deprecated.

![choose-mdm](https://user-images.githubusercontent.com/15342088/67070405-42c7a980-f180-11e9-8644-9e1c0342d998.JPG)

**Comment by aczechowski** [comment]
Thanks @Kazzan for clarifying. I'm checking with the Intune team who owns that portal. I suggest you contact them as well, see [How to get support for Intune](https://docs.microsoft.com/intune/fundamentals/get-support).
I'm going to close this issue as there's nothing directly actionable for this article.
