### ISSUE TITLE
Server Side includes is not a Requirement..

### ISSUE THREAD

**Issue by DavidHBaur** [MicrosoftDocs/SCCMdocs#1934]
Server Side includes is not a Requirement..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e9b7de4-5860-4eda-a0e5-d34f69a63fd5
* Version Independent ID: b3140976-dc93-deab-1f90-d5479c8403af
* Content: [Set up your lab - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/set-up-your-lab)
* Content Source: [sccm/core/get-started/set-up-your-lab.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/set-up-your-lab.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I'm going to consolidate this all into a single item #1936
