### ISSUE TITLE
Several listed items that aren't requirements

### ISSUE THREAD

**Issue by DavidHBaur** [MicrosoftDocs/SCCMdocs#1936]
- Server Side includes is not a Requirement.. (#1934)
- FTP Service is not required. (#1935)

- The only Security Options Required are: Request Filtering and Windows Authentication

None of these are requirements:
Basic Authentication
Client Certificate Mapping Authentication
IP and Domain Restrictions
URL Authorization

(admin edit: consolidating three issues into a single)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e9b7de4-5860-4eda-a0e5-d34f69a63fd5
* Version Independent ID: b3140976-dc93-deab-1f90-d5479c8403af
* Content: [Set up your lab - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/set-up-your-lab)
* Content Source: [sccm/core/get-started/set-up-your-lab.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/set-up-your-lab.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @DavidHBaur for the feedback. I've consolidated the three issues into a single one.

**Comment by DavidHBaur** [comment]
Anytime. Many Thanks!

 

David Baur

**Comment by ChrisKibble** [comment]
@aczechowski is this confirmed with the product team?

**Comment by aczechowski** [comment]
@ChrisKibble, no, I haven't had the opportunity yet to confirm.

**Comment by aczechowski** [comment]
I'm closing this since it's in the retired repo and there's another issue filed on the article in the new repo (see the link above). Still hope to revise the article, just consolidating the feedback. If you want to receive updates on the issue, follow the link to MicrosoftDocs/MEMDocs#159 and select the button in the right side menu to subscribe to notifications.
