### ISSUE TITLE
Supersendence and Application groups

### ISSUE THREAD

**Issue by seilermi** [MicrosoftDocs/SCCMdocs#1941]
A supersedence link does not work if the application is assigned to a client with an application group.

Are there already solutions or instructions on the topic of supersedence and application groups?

(admin edit - adding metadata for article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b75008-ff8a-3cef-f465-1bc93f7caa42
* Version Independent ID: fe6e1908-4efc-db07-9d84-24ee7b8d74e7
* Content: [Create application groups - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/apps/deploy-use/create-app-groups)
* Content Source: [sccm/apps/deploy-use/create-app-groups.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/create-app-groups.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
There are some additional known issues with app groups that are not currently documented, but I'll be adding those with the 1910 content to publish in the near future with that release. Supersedence currently isn't on that list, though. @AdamGrossTX, one of our MVPs 😄, [mentioned on Twitter](https://twitter.com/AdamGrossTX/status/1191384137535500289) he got an app group to work with supersedence.

I'm going to use this issue to track adding the other known issues. But @seilermi I suggest perhaps you provide [product feedback](https://docs.microsoft.com/configmgr/core/understand/find-help#product-feedback) instead or [contact support](https://docs.microsoft.com/configmgr/core/understand/find-help#BKMK_SupportOptions) for assistance with supersedence.

**Comment by aczechowski** [comment]
I'm closing this issue, as I made changes in the 1910 content that will release in the near future.
