### ISSUE TITLE
Provide information on how to update when server has no internet connection

### ISSUE THREAD

**Issue by phreeze83** [MicrosoftDocs/SCCMdocs#1946]
In many entreprise environments, the servers have no internet connection at all. How to upgrade manually ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18318259-bc99-7525-c775-a5f3fefab715
* Version Independent ID: 3dc5cd89-0023-fb3a-a938-764bae9afbc3
* Content: [Checklist for 1906 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/checklist-for-installing-update-1906)
* Content Source: [sccm/core/servers/manage/checklist-for-installing-update-1906.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/checklist-for-installing-update-1906.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @phreeze83 for the feedback. We can explicitly add that to the next checklist going forward.

Right now you have to click through a few articles to find the information:

- At the bottom of this article, "For more information about installing updates, see [In-console updates and servicing](https://docs.microsoft.com/sccm/core/servers/manage/updates#bkmk_inconsole)."
- In the updates article, "When your service connection point is in offline mode, use the service connection tool to manually sync with the Microsoft cloud. For more information, see [Use the service connection tool](https://docs.microsoft.com/sccm/core/servers/manage/use-the-service-connection-tool)."

The article on the service connection tool has the information that you need to download ConfigMgr updates to an offline environment.

**Comment by phreeze83** [comment]
i have seen it later, thx.  Perhaps also explain what sort of data is downloaded and the size of it. I had to download over 30GB of data over 9hours to update from 1806 to 1906 and surely not all of the data was used

**Comment by aczechowski** [comment]
I revised the checklist for the upcoming version 1910, so am closing this issue. That checklist will publish when that version releases. Thanks again for the feedback
