### ISSUE TITLE
Clarification on macro assessment

### ISSUE THREAD

**Issue by bubbletroubles** [MicrosoftDocs/SCCMdocs#1950]
The page has a "Detailed macro readiness" heading, and says to install the "Office Readiness Toolkit" for more comprehensive reporting.

However the page also says that starting in ConfigMgr 1906, there is a new dashboard to report on macro readiness.

Does ConfigMgr 1906 supercede the "Office Readiness Toolkit", or does the "Office Readiness Toolkit" still provide enhanced coverage over what ConfigMgr 1906 has?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aa228c2-5f36-29b9-33e3-2f854ed3d685
* Version Independent ID: bbb1fbf3-839f-eb26-78a2-c8e52aa3ca47
* Content: [Office 365 Client Management dashboard - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/office-365-dashboard)
* Content Source: [sccm/sum/deploy-use/office-365-dashboard.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/office-365-dashboard.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@bubbletroubles I am looking for clarification on this for you.

**Comment by mestew** [comment]
@bubbletroubles The readiness toolkit is still required to get more detailed info about the macros in 1906. ConfigMan's inventory agent picks up results from the toolkit to display in 1906, but the toolkit has more detailed information. 

I'll update the doc with this information. Thanks for the great question.
