### ISSUE TITLE
DeploymentIntent

### ISSUE THREAD

**Issue by codaamok** [MicrosoftDocs/SCCMdocs#1953]
The docs suggest DeploymentIntent (linked to SMS_AppDeploymentAssetDetails) can be like the following:

1	Install
2	Uninstall
3	Preflight

However what I am actually seeing is 1 for required and 2 for available regardless whether it's install or uninstall.

I would PR this but I'm not sure if there are more possible values. Previously WMIExplorer has shown me possible values for properties but it returns nothing in this instance so not sure submitting my own here is best thing to do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc9994ef-1281-f93c-f899-2c10515eb188
* Version Independent ID: 6e1c3716-049d-ed07-38cc-eed5394eb501
* Content: [SMS_DeploymentSummary Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/apps/sms_deploymentsummary-server-wmi-class)
* Content Source: [sccm/develop/reference/apps/sms_deploymentsummary-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/apps/sms_deploymentsummary-server-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks to @jpcast88 who submitted a fix for this issue. It will publish live tomorrow.
