### ISSUE TITLE
Page is murky and confusing about which features of the admin service are supported, and on which version

### ISSUE THREAD

**Issue by 1RedOne** [MicrosoftDocs/SCCMdocs#1955]
It's convoluted to read the description of the CM Admin Service.  Also, no mention is made of if any special considerations are needed to isntall it or enable it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 070c2bc6-3086-7237-d19c-951f000b4531
* Version Independent ID: 95c62945-77dc-0ce0-e4ee-1116343b7ea6
* Content: [Plan for the SMS Provider - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/plan-for-the-sms-provider#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/plan-for-the-sms-provider.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/plan-for-the-sms-provider.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @1RedOne for the feedback. We actually met with the engineering team a few weeks ago to talk about plans to improve this content. Stay tuned! 😉

**Comment by aczechowski** [comment]
I'm closing this issue. I have a big change coming soon for admin service content to address this. The changes will publish with the 2002 content soon 😉
