### ISSUE TITLE
SMS Provider Size and Scale Number

### ISSUE THREAD

**Issue by ITOpsReborn** [MicrosoftDocs/SCCMdocs#1958]
I believe SMS Provider use to have a section on this page.  What is the recommended number of console connections to one sms_provider? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c595a86-976c-dc2c-5b01-fb9d6b761f17
* Version Independent ID: a90f5193-559b-07b0-519a-d5ef32de3151
* Content: [Size and scale - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/size-and-scale-numbers)
* Content Source: [sccm/core/plan-design/configs/size-and-scale-numbers.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/size-and-scale-numbers.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @ITOpsReborn, thanks for the feedback. This blurb is in the [Plan for SMS Provider](https://docs.microsoft.com/configmgr/core/plan-design/hierarchy/plan-for-the-sms-provider#bkmk_location) article:

> Each instance of the SMS Provider supports simultaneous connections from multiple requests. The only limitations on these connections are the number of server connections that are available to Windows, and the available resources on the server to service the connection requests.

I pulled it into a new section in this article for better visibility. This issue will automatically close when the pull request merges. I'm making the change in our release branch for version 2002, so it won't publish live until that releases. That should be *soon* 😉

**Comment by aczechowski** [comment]
I just submitted a change. Once the pull request merges, this issue will automatically close. The change is in our 2002 release branch, so it won't be live until that publishes, which should be *soon* 😉
