### ISSUE TITLE
Note for Content source priority

### ISSUE THREAD

**Issue by JustMatthew** [MicrosoftDocs/SCCMdocs#1960]
Would it be possible (for this particular document) to make it a little more clear that the content source priority order does not apply the same to OSD task sequences.

(admin edit: add article metadata to properly link issue)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff2f1985-822a-f9aa-8368-9abf85c50118
* Version Independent ID: 3401e963-f1cf-a15d-01f2-c1754a7d9336
* Content: [Content management fundamentals - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management#content-source-priority)
* Content Source: [sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I made a change for this issue, it should publish live this afternoon.
Thanks for the feedback!
