### ISSUE TITLE
script rewrite

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/SCCMdocs#1964]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/SCCMDocs.fr-fr/issues/6

@michel-priori commented 3 days ago — with docs.microsoft.com
SET NOCOUNT ON
DECLARE @dbname NVARCHAR(128) = db_name(DB_ID());
DECLARE @msg nvarchar(max) = 'ERROR: Script is targetting a ' + @dbname +' system database. It should be targeting "user" database.';
Declare @Result Table
(parametre nvarchar(256)
,current_value nvarchar(256)
,needed_value nvarchar(256)
,remediation_script NVARCHAR(max)
);

IF (db_id()&lt;5 OR @dbname = N'distribution' )
BEGIN
RAISERROR(@msg, 0, 1)
GOTO Branch_Exit;
END

/* Debut des vérifications */

Insert into @Result(parametre,current_value,needed_value,remediation_script)
select 'clr enabled', cast(c.value_in_use as nvarchar(256)), 1
,'sp_configure ''show advanced options'', 1; GO; RECONFIGURE; GO; sp_configure ''clr enabled'', 1; GO; RECONFIGURE; '
FROM sys.configurations c
WHERE c.name = 'clr enabled'
AND c.value_in_use = 1

Insert into @Result(parametre,current_value,needed_value,remediation_script)
select 'max text repl size (B)', cast(c.value_in_use as nvarchar(256)),2147483647
,'EXECUTE sp_configure ''max text repl size (B)'', 2147483647'
FROM sys.configurations c
WHERE c.name = 'max text repl size (B)'
AND c.value_in_use = 2147483647

Insert into @Result(parametre,current_value,needed_value,remediation_script)
select 'Database Owner', User_name(db.owner_sid), user_name(0x01)
,' use ' + @dbname + '; GO; EXEC sp_changedbowner ' + suser_sname(0x01)
FROM sys.databases db
WHERE db.database_id = DB_ID()
AND db.owner_sid = 0x01

Insert into @Result(parametre,current_value,needed_value,remediation_script)
SELECT 'is_trustworthy_on',db.is_trustworthy_on , 1
,'ALTER DATABASE ' + @dbname + ' SET TRUSTWORTHY ON;'
FROM sys.databases db
WHERE db.database_id = DB_ID()
AND db.is_trustworthy_on = 1

Insert into @Result(parametre,current_value,needed_value,remediation_script)
SELECT 'is_broker_enabled', db.is_broker_enabled , 1
,'ALTER DATABASE ' + @dbname + ' SET ENABLE_BROKER'
FROM sys.databases db
WHERE db.database_id = DB_ID()
AND db.is_broker_enabled = 1

Insert into @Result(parametre,current_value,needed_value,remediation_script)
SELECT 'is_honor_broker_priority_on', db.is_honor_broker_priority_on , 1
,'ALTER DATABASE ' + @dbname + ' SET HONOR_BROKER_PRIORITY ON; ALTER DATABASE ' + @dbname + ' SET ENABLE_BROKER WITH ROLLBACK IMMEDIATE'
FROM sys.databases db
WHERE db.database_id = DB_ID()
AND db.is_honor_broker_priority_on = 1

select * from @Result
Branch_Exit:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53d1da83-d988-fb2b-82c5-fd9cf117cd42
* Version Independent ID: 2b1a3bd2-5116-1f21-c196-e3e5698a83c9
* Content: [SQL Server Always On - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database)
* Content Source: [sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
