### ISSUE TITLE
ClientAuthTrustMode

### ISSUE THREAD

**Issue by skoal2k4** [MicrosoftDocs/SCCMdocs#1973]
Wasn't mentioned on this doc, so thought i'd share.  When setting up a Pull DP, we kept receiving 403.16 and 403.7 http errors in the DataTransferService.log and PullDP.log files of the pull DP.  We had to set ClientAuthTrustMode to a value of 2 on the Source DP, as described in the following url, and reboot the source DP... after that was complete, Pull DP started pulling content from the source DP.  We normally set this registry value for hour https MPs, but didn't realize we also need to set it for the https source DPs as well

https://blogs.technet.microsoft.com/configurationmgr/2013/08/13/support-tip-a-configmgr-2012-management-point-enabled-for-ssl-fails-with-403-forbidden/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4055a018-68cf-1d48-df84-ea3d7f994f75
* Version Independent ID: 172470eb-4528-cab4-8ebe-dae2ed006523
* Content: [Pull-distribution point - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/use-a-pull-distribution-point)
* Content Source: [sccm/core/plan-design/hierarchy/use-a-pull-distribution-point.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/use-a-pull-distribution-point.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @skoal2k4 for the feedback, that's a great tip to include in the article. 

If you're interested in adding it directly, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute). 😄

**Comment by RAJU2529** [comment]
@skoal2k4. Sir create new PR for adding your contribution

**Comment by zebulun78** [comment]
This just saved me a lot of pain (further than the day's worth so far).  I vote for adding this detail to the official docs.

**Comment by aczechowski** [comment]
I made a change to include this tip, the change should publish live on Monday
