### ISSUE TITLE
 service plan has no option Type of deployment

### ISSUE THREAD

**Issue by IvyMS1990** [MicrosoftDocs/SCCMdocs#1977]
Based on doc, end-user can select Type of deployment. But this option does not show in console

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 216e808f-64f5-7681-3f7b-bfc1f4193b71
* Version Independent ID: 8f9a6ef6-6eff-430f-a6d8-b59143c7fdb2
* Content: [Manage Windows as a Service - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/manage-windows-as-a-service#feedback)
* Content Source: [sccm/osd/deploy-use/manage-windows-as-a-service.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/manage-windows-as-a-service.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by RAJU2529** [comment]
@IvyMS1990. Sir will you upload the proof, like photos here

**Comment by aczechowski** [comment]
Thanks @IvyMS1990 for the feedback.
@mestew I'm remembering seeing something about this somewhere else, but now I can't find the reference. Do you remember?

**Comment by IvyMS1990** [comment]
Hi Experts,

Thanks for tracking this issue. Below is one screenshot of service plan properties. Based on doc, there is ‘Type of deployment’ which can modify Required and Available. But it does not exist.
[cid:image001.jpg@01D5909E.4D4AFC10]


Thanks,
Ivy

**Comment by mestew** [comment]
@IvyMS1990 Thanks for noticing this. I will get that changed shortly. 
@aczechowski While I was there, I noticed a few other needed edits that I made as well.
