### ISSUE TITLE
Diagnostic Endpoint URL's need to be udpated

### ISSUE THREAD

**Issue by brianbar-MSFT** [MicrosoftDocs/SCCMdocs#1979]
The URL's posted here https://docs.microsoft.com/en-us/sccm/desktop-analytics/monitor-connection-health#windows-diagnostic-endpoint-connectivity need to be updated to match the URL's posted here: https://docs.microsoft.com/en-us/sccm/desktop-analytics/enable-data-sharing#endpoints

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d515f55-4e5f-4096-865d-799ec7d2f2fd
* Version Independent ID: 525deae7-d300-6128-a082-6da52ea45ce2
* Content: [Monitor connection health - Configuration Manager](https://docs.microsoft.com/en-us/sccm/desktop-analytics/monitor-connection-health?source=docs#feedback)
* Content Source: [sccm/desktop-analytics/monitor-connection-health.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/monitor-connection-health.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by RAJU2529** [comment]
@brianbar-MSFT. Sir will you create a new PR on based on your comment.

**Comment by aczechowski** [comment]
Thanks @brianbar-MSFT 😄 
I'll review this today so that they are consistent

**Comment by aczechowski** [comment]
I made the language consistent between the two articles. The revision should publish live later today.
