### ISSUE TITLE
This page needs a minor update

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/SCCMdocs#1981]
the last entry - "Select the Software Updates group. Configure to Yes the setting to Enable installation of Express Updates on clients. Configure the Port used to download content for Express Updates with the port used by the HTTP listener on the client."

in 1906, these options appear to now be "Allow clients to download delta content when available"  and "Port that clients use to receive requests for delta content"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcccfa90-7c10-2327-e3af-dbc1cb31b054
* Version Independent ID: c1d90427-19a0-c36c-8888-46707b4ee8c9
* Content: [Manage Windows 10 express updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/manage-express-installation-files-for-windows-10-updates#feedback)
* Content Source: [sccm/sum/deploy-use/manage-express-installation-files-for-windows-10-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/manage-express-installation-files-for-windows-10-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @PaulKlerkx - I think we have/had this tracked elsewhere, but good to have the visibility for others.

**Comment by mestew** [comment]
@PaulKlerkx Thanks. This wording changed in 1902. I'll make a note of it in the doc.

**Comment by mestew** [comment]
Change should go live Monday-ish.
