### ISSUE TITLE
ADK support for Windows 10 1909?

### ISSUE THREAD

**Issue by BritV8** [MicrosoftDocs/SCCMdocs#1982]
When will this support information for the ADK version for Windows 10 1909 be available? 
Page says Windows 10 1909 on SCCM CB 1906 is supported but does not indicate if ADK 1903 will support Windows 10 1909

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc732ec0-eb14-8da2-7688-dd74a72cdae5
* Version Independent ID: a93682ff-2984-38e0-5a0d-6f77c1c9e5db
* Content: [Support for Windows 10 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/support-for-windows-10#feedback)
* Content Source: [sccm/core/plan-design/configs/support-for-windows-10.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/support-for-windows-10.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @BritV8, thanks for the question. There won't be a 1909 ADK, but the best reference for that I can find right now is via [Twitter](https://twitter.com/sudhagart/status/1185026692785422336). And we try really hard to not talk about the Windows support matrix in this article, just keep it to ConfigMgr. So our article is accurate as it applies to ConfigMgr: version 1906 supports both latest versions: 1909 client and 1903 ADK.

Perhaps file the same feedback on the Windows ADK content? This article on [ADK scenarios](https://docs.microsoft.com/windows/deployment/windows-adk-scenarios-for-it-pros) doesn't mention *any* versions, but perhaps the best spot for such feedback. (The ADK download article doesn't allow feedback.)

I'm closing this issue.
