### ISSUE TITLE
Server 2016 issue?

### ISSUE THREAD

**Issue by kewljoe** [MicrosoftDocs/SCCMdocs#1984]
line 14 item $hashAlgorithm.ComputHash does not work, however Intellisense offers $hashAlgorith.ComputeHash which does work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a13ac879-ae61-a880-6276-9e6146be971e
* Version Independent ID: 0c96a5d2-3e78-3ecb-822e-a7471ca7e8cd
* Content: [View diagnostics data - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/diagnostics/view-diagnostics-and-usage-data?redirectedfrom=MSDN&source=docs)
* Content Source: [sccm/core/plan-design/diagnostics/view-diagnostics-and-usage-data.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/diagnostics/view-diagnostics-and-usage-data.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @kewljoe, can you confirm? The article has `ComputeHash` - which is what you say works? 🤔 Is that just a typo in your comment?

I successfully tested the script from the article on my Win 10 v1909 machine, and can probably test on a server build tomorrow.

**Comment by kewljoe** [comment]
Hey Aaron,

Disregard this, I was typing this on a class network from unclass and must’ve mistyped the previous $hashAlgorithm section (line12) which then prompted intellisense to reference my mistyped variable.... typo mistake made in leu of copy (burn) paste to class network.

Thanks
José

José Riaño
PFE | Configuration Manager | jose.riano@microsoft.com | 314-995-3102

________________________________

**Comment by aczechowski** [comment]
Ah, got it. After five years in MCS in the DC area, I understand 😉
