### ISSUE TITLE
Create Target Collection Before Starting Wizard

### ISSUE THREAD

**Issue by sandersap** [MicrosoftDocs/SCCMdocs#1986]
Suggestion to create the Desktop Analytics target collection before starting the wizard, as you cannot select outside of the wizard once you start it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b58dfdf5-6060-e4fa-a806-456ca196ede7
* Version Independent ID: 1f8325fb-518d-412e-f011-7fd62311b087
* Content: [Connect Configuration Manager - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/desktop-analytics/connect-configmgr#feedback)
* Content Source: [sccm/desktop-analytics/connect-configmgr.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/connect-configmgr.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @sandersap, good feedback. That suggestion would make a great tip here and in the tutorial.

**Comment by aczechowski** [comment]
Thanks to @baardhermansen for making this change in the linked pull request. I'm closing this issue. It should publish live tomorrow.
