### ISSUE TITLE
script DT does not honor the program visibility setting

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#1988]
Consider the following scenario:

1. A script installer (i.e. an .exe installer) does not need user interaction when run but does show progress or non-interactive dialog boxes
2. An Application is created with a Deployment Type of Script Installer with the script installer from Step 1
3. For the Deployment tab of the Application in Step 2, the Installation program command line under the Programs tab of does not contain any switches that suppresses UI or causes the program to run hidden or quiet
4. For the Deployment tab of the Application in Step 2, under the User Experience tab of the Deployment Type the Installation program visibility is set to Hidden
5. Application is deployed to a PC

there is no single way to suppress UI installation screens, and so the script DT does not honor the program visibility setting. The setting only works in the context of an MSI deployment type, because MSI packages allow us the ability to suppress their UI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db758241-5a9e-47dc-0104-8d8c1072a2f2
* Version Independent ID: d54013ba-afcb-6795-9fb5-3668a8afec32
* Content: [Create applications - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/apps/deploy-use/create-applications#bkmk_dt-ux)
* Content Source: [sccm/apps/deploy-use/create-applications.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/create-applications.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by martshep** [comment]
Note that if you select "Run installation and uninstall program as a 32-bit process on 64-bit clients" then the "Allow users to view and interact with the program installation" setting IS honored (by launching the installer in session 0). It is only if you select to run the installer as 64-bit that the setting is not honored (the installation runs in the user's logon session).

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
