### ISSUE TITLE
Primary Site - Downstream SUPs

### ISSUE THREAD

**Issue by miguelrodriguezeicke** [MicrosoftDocs/SCCMdocs#1994]
When executing the SQL Maintenance Jobs, does the Siteserver not use 1433 to connect to the SUSDB on those Downstream SUPs? If thats the case i assume those requirements are missing from the docs...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f658ee4b-d051-0d7c-4656-19a846908469
* Version Independent ID: 3478e881-199c-f0c4-b218-0dd609eb0427
* Content: [Ports used for connections - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/ports#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/ports.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/ports.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @miguelrodriguezeicke, I'm hoping @mestew can help with this

**Comment by mestew** [comment]
@aczechowski @miguelrodriguezeicke yeah. Did a quick double check on the code for WSUS cleanup. We are connecting straight to the SUSDB with a SQL connection when adding the indexes and cleaning obsolete updates (I didn't poke further than that). We do this using the SQL server name, so the port itself can vary if it was changed from the default value of 1433. I'm putting in a doc change for this. I just want a second set of eyes on the change before I publish it to make sure I didn't goof during my review.
