### ISSUE TITLE
Please correct spelling of available

### ISSUE THREAD

**Issue by PeteHaigh-MSFT** [MicrosoftDocs/SCCMdocs#1996]
"avaliable" - line 3, para 1 under 'Tip'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf24a1d9-b5e0-7031-fe6d-dd49cfb8b58f
* Version Independent ID: 5d1a29bf-4299-6700-2797-7e24b931f598
* Content: [Enable data sharing - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/desktop-analytics/enable-data-sharing#feedback)
* Content Source: [sccm/desktop-analytics/enable-data-sharing.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/enable-data-sharing.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @PeteHaigh-MSFT for catching that.

**Comment by aczechowski** [comment]
@ChrisKibble is going to use this for a demo 😄

**Comment by aczechowski** [comment]
The change that Chris filed today will publish tomorrow around 11am Pacific

**Comment by PeteHaigh-MSFT** [comment]
Sweet – happy to hep guys 😃

Peter Haigh : Technology Strategist : Microsoft NZ
peter.haigh@microsoft.com<mailto:peter.haigh@microsoft.com>  : Office: +64 4 4706598 : Mobile +64 27 2235329
