### ISSUE TITLE
Clarity on Sign in requirements for Intune tenant

### ISSUE THREAD

**Issue by faceball2000** [MicrosoftDocs/SCCMdocs#2000]
In section "Enable co-management starting in version 1906", on subscription page step it says to: "Sign in to your Intune tenant, and then select Next."

Please can you clarify the account requirements here - e.g is this a one time sign-in?, does this require an Intune Administrator role and are these credentials stored in SCCM/ECM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f5f810-0397-1cb0-3dc8-ca3a06fce1da
* Version Independent ID: fb6d937b-7681-5a5c-0fb5-ac7fa5faf7b9
* Content: [Tutorial: Enable co-management for existing clients - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/comanage/tutorial-co-manage-clients#feedback)
* Content Source: [sccm/comanage/tutorial-co-manage-clients.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/tutorial-co-manage-clients.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @faceball2000, see the [permissions](https://docs.microsoft.com/configmgr/comanage/tutorial-co-manage-clients#permissions) section at the top of the article which includes the necessary accounts required for this process.

But good feedback that we should clarify that it's only a one-time sign-in, the credentials aren't stored or reused.

**Comment by faceball2000** [comment]
thanks for the info :)

**Comment by aczechowski** [comment]
A submitted a change for this issue. It will publish live tomorrow (Wednesday) around 11:00 Pacific time.
