### ISSUE TITLE
Impact/changes to SCCM once co-management is enabled

### ISSUE THREAD

**Issue by ristephens43** [MicrosoftDocs/SCCMdocs#2002]
Once enabled what impact/changes does this have on the existing SCCM infrastructure/database? 

I’m aware as we onboard devices we would expect to certain table updates like v_CombinedDeviceResources to reflect that the device is now co-managed.

Should we expect to see many more changes in the database?

**Comment by aczechowski** [comment]
Hi @ristephens43, can you expand upon your question? Why are you asking? What behavior would it drive to understand these details? I ask because we generally don't document that level of detail for a given feature. So I'm trying to understand the driver behind the question.

**Comment by ristephens43** [comment]
Hey Aron,

Sure.. I have a slightly "protective" SCCM admin team which provide me "challenges" when I try to get new features enabled. As such when I was requested Co-Management to be enabled I was asked what impact will this have on SCCM. 

Knowing how thorough they can be I was looking almost for list of everything that's changed in SCCM when co-management is enabled. 

I expect that be different depending on which work loads are enabled?  

I hope this makes some kind of sense. 

Thanks
Richard

**Comment by aczechowski** [comment]
If you just enable co-management, that action alone doesn’t really make any changes to the site. Any Windows 10 clients that meet the prereqs receive a policy, and can then become co-managed. If you enable co-management, but don’t turn on auto-enrollment, then the clients essentially remain ConfigMgr-managed unless you manually enroll the device. Even after MDM enrollment, the device is still ConfigMgr-managed, you just get some additional functionality from Intune.

The only broader changes to the site would be if you take other actions, like for the [second path scenario](https://docs.microsoft.com/configmgr/comanage/overview#paths-to-co-management) with Azure AD or CMG. As I previously mentioned, we don’t document the minute level of detail such as changes to SQL tables. So I’m going to close this issue. If you think it warrants additional content, feel free to reopen. We could perhaps include it in an FAQ.
