### ISSUE TITLE
Question About: Client PCs must have connectivity to their Domain Controller in order for a Windows Defender Application Control policy to be processed successfully.

### ISSUE THREAD

**Issue by lunarbinary** [MicrosoftDocs/SCCMdocs#2006]
What do we mean when we say Client PCs must have connectivity to their Domain Controller? When do they need connectivity to the DCs? Does this mean that laptops that go offline for periods of time aren't good candidates for this feature? What is the connectivity to the DCs used for in this context? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2082f138-28f2-d410-d607-4fcb1ddf12db
* Version Independent ID: 7ce37b4e-9330-73d9-f3bb-2f0af4ec6073
* Content: [How to manage Windows Device Guard - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/protect/deploy-use/use-device-guard-with-configuration-manager?source=docs#feedback)
* Content Source: [sccm/protect/deploy-use/use-device-guard-with-configuration-manager.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/use-device-guard-with-configuration-manager.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@lunarbinary It's not a requirement. I am removing it for you. I suspect the change will be seen in the doc around Monday the 25th of November.
