### ISSUE TITLE
Terminology Switch

### ISSUE THREAD

**Issue by JordanTheITGuy** [MicrosoftDocs/SCCMdocs#2007]
When talking about planning the software update environment, the terminology for "SUP" and "WSUS" is commonly changed around. 

While the two are related they are two different things here is a specific example:

" Unlike in the design of management points, there are client and network performance costs in the software update point design when clients switch to a new software update point. When the client switches to a new WSUS server to scan for software updates, the result is an increase in the catalog size and associated client-side and network performance demands. Therefore, the client preserves affinity with the last software update point from which it successfully scanned."

I think this is important especially as the in the console we call it "SUP Switching" not "WSUS" switching. While the performance hit involved has nothing to do with the SUP change and everything to do with the WSUS change if that's the purpose here then maybe we can find a way to call this out better. Does this make sense or just more confusing. 

(admin edit: adding metadata for linkage with one target article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d69fe2fa-2d4c-e3fe-ed03-3fae067bca3b
* Version Independent ID: 9b781cea-18dc-79af-0158-59abc861b601
* Content: [Plan for software updates - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/sum/plan-design/plan-for-software-updates)
* Content Source: [sccm/sum/plan-design/plan-for-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/plan-design/plan-for-software-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback. We have another item in our internal backlog (Azure DevOps) that would address this feedback.
