### ISSUE TITLE
Issue: Page "Create a task sequence to upgrade an OS in Configuration Manager" has incorrect registry key example

### ISSUE THREAD

**Issue by OftKilted** [MicrosoftDocs/SCCMdocs#2008]
Source File: https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system.md#remove-default-apps

The registry key example to remove default apps (and keep them out when upgrading) says:

"Some customers remove default provisioned apps in Windows 10. For example, the Bing Weather app, or the Microsoft Solitaire Collection. In some situations, these apps return after updating Windows 10. For more information, see How to keep apps removed from Windows 10.

Add a Run Command Line step to the task sequence in the Prepare for Upgrade group. Specify a command line similar to the following example:

`cmd /c reg delete "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned\Microsoft.BingWeather_8wekyb3d8bbwe" /f`"

According to [https://docs.microsoft.com/en-us/windows/application-management/remove-provisioned-apps-during-update](url) you "Remove the registry keys belonging to the apps you want to keep. For example, if you want to keep the Bing Weather app, delete this registry key: <key>"

The code appears as though it should actually be:

`cmd /c reg add "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned\Microsoft.BingWeather_8wekyb3d8bbwe" /f`

Which would add the registry key to the list of software that you are attempting to ensure is removed and deprovisioned on the upgrade. (Instead of deleting the registry key from the list of software to be deprovisioned ... which would instead keep that software.)

(admin edit: add metadata to link to article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfe3442-b59d-0d77-d9af-f18e787ec99d
* Version Independent ID: 60cb54a2-d1fd-92b5-b027-de8a85c7af64
* Content: [Create an OS upgrade task sequence - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system)
* Content Source: [sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Ah, good catch @OftKilted. I just submitted a change for this, it will publish live tomorrow. Thanks!
