### ISSUE TITLE
Clarification needed re: device 'reenrollment'

### ISSUE THREAD

**Issue by x9** [MicrosoftDocs/SCCMdocs#2009]
The documentation states that:

"You need to reenroll devices to Desktop Analytics that you previously enrolled in Windows Analytics."

This sentence makes no sense - devices are not 'enrolled' in either Desktop Analytics or Windows Analytics. They report telemetry to Microsoft which is then passed to the correct Azure Log Analytics workspace based on the Commercial ID present within the telemetry data.

If the the same Log Analytics workspace is used during a Windows Analytics -&gt; Desktop Analytics migration and the Commerical ID does not change, then in theory no action should be required for devices to be visible in Desktop Analytics. If this is the case, the documentation should be updated to reflect this.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd47a59b-8033-9e94-6f54-0ac1b6c9007e
* Version Independent ID: d26141cd-e979-607b-f7db-57c762b329e4
* Content: [Set up Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-au/configmgr/desktop-analytics/set-up#feedback)
* Content Source: [sccm/desktop-analytics/set-up.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/set-up.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by danchemistruck** [comment]
I have reenrolled devices with Log Analytics many times, but do not receive any telemetry in Desktop Analytics. Is SCCM a requirement for Desktop Analytics? Cloud-only environments (AAD only, no on-prem AD) are not eligible for this service?

**Comment by aczechowski** [comment]
@x9, "enroll" is the same verb/term that Windows Analytics used. 😄 [For example](https://docs.microsoft.com/windows/deployment/update/windows-analytics-get-started).

It’s basically just the term that we’re using for configuring the settings on the device. And that process is different between WA/DA. With WA you used a script or GPO, but it’s a simplified process integrated with ConfigMgr. I suppose “register” or "reconfigure" is perhaps a more accurate term for the specific action, but we’re using "enroll."

@danchemistruck - ConfigMgr is currently required to work with Desktop Analytics. See [this FAQ](https://docs.microsoft.com/configmgr/desktop-analytics/faq#bkmk_intune). To share your feedback with the engineering team, please vote up or file an item on the [product UserVoice site in the Desktop Analytics group](https://configurationmanager.uservoice.com/forums/300492-ideas?category_id=366805).
