### ISSUE TITLE
Missing link for CMG

### ISSUE THREAD

**Issue by GlennJC** [MicrosoftDocs/SCCMdocs#2010]
4th bullet point under "How to do it" section is missing the link to the CMG content.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31ae394c-390c-c2c5-33a3-051ad3d630f5
* Version Independent ID: 09d20de9-0c78-6abe-46e7-9add29d90081
* Content: [Upgrade Windows 10 - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/comanage/quickstart-upgrade-win10#feedback)
* Content Source: [sccm/comanage/quickstart-upgrade-win10.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/quickstart-upgrade-win10.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @GlennJC for the feedback. It should link to this article: [Deploy Windows 10 in-place upgrade via CMG](https://docs.microsoft.com/configmgr/osd/deploy-use/deploy-a-task-sequence#deploy-windows-10-in-place-upgrade-via-cmg)

Did you know you can submit the edit yourself? 😄 For more information, see [How to contribute](https://docs.microsoft.com/configmgr/core/understand/use-docs#bkmk_contribute).
