### ISSUE TITLE
Add SMS Role SSL certificate info

### ISSUE THREAD

**Issue by MSBeatriz** [MicrosoftDocs/SCCMdocs#2011]
We need to add the info for HTTPe selfsigned certificate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c095180-90a2-79c6-a7fb-6504cafbcfb6
* Version Independent ID: fb9c2930-b213-3eef-c7bb-c8f11ec97aca
* Content: [CMG Certificates - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/manage/cmg/certificates-for-cloud-management-gateway#bkmk_cmgroot)
* Content Source: [sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @MSBeatriz, can you please expand a bit more on this? For example:
- Which certificate are you referring to?
- What additional info is needed?

**Comment by MSBeatriz** [comment]
Hi Aaron,

I was going to draft it but I lost my access to Github.
(Waiting on support as I have not recovery keys on my current pc (renewed) and for some reason on authenticatior tool Github was removed. They will remove my account and I will re-setup it… At least I had nothing there that I have not saved locally)

About SMS Role SSL certificate:
What we need is to clarify that when we setup HTTPe, there´s a selfsigned certificate added into IIS web service from MP secure communication.
This causes many issues on customer environments, where the cert is not configured properly, and customers are un-aware of this.

This could be added on  section: Enable Management point certificate for HTTPs, with a note regarding HTTPe certificate.
Or adding new section for HTTPe Management Point ¿?

There´s another certificate to mention related to CMG CP we might need to clarify as well.
We need client auth cert locally on server cert store, so we might need add another section? Or maybe add this info on other place of docs?

Let me know if those certificate info should be here or not. CMG functionality depends on them both.

Best regards,

Beatriz Moran Serrano
SEE EMEA Configuration Manager - Customer Services and Support
TLF: +34 (91) 3919641
Email: bmoran@microsoft.com<mailto:bmoran@microsoft.com>

Did I help you today?  Please provide feedback  or Send Kudos: http://kudos/
Manager:  Stefan Nachreiner (stefan@microsoft.com) +49 (89) 31762417
