### ISSUE TITLE
Monitoring CMG traffic graph in console after Upgrade to 1906 from 1806

### ISSUE THREAD

**Issue by eogmau** [MicrosoftDocs/SCCMdocs#2012]
After upgrade to 1906 from 1806 the CMG traffic graph shows much more egress traffic than before the upgrade. After verification the  in Azure portal, we have identified that the excess data egress is coming from Storage Account for this CMG and in particular from the Tables data. 
Looking at SCCM documentation of what is new, I cannot see any changes that will show additional data egress in CMG traffic (Last 30days) graph in console. Is this behaviour normal or there is an issue with our CMG implementation?
Can this be documented why we see in console monitoring the egress data from the Storage Account and especially the Table data and when this have changed.

The red line in first screenshot is the time when SCCM was upgraded to 1906 from 1806.
![CMG Traffic Graph](https://user-images.githubusercontent.com/21968661/68933480-a697bf00-078c-11ea-9be1-cb1687989b57.PNG)
![Azure Storage Traffic](https://user-images.githubusercontent.com/21968661/68933481-a7305580-078c-11ea-809d-27fa5be157e5.PNG)

**Comment by aczechowski** [comment]
I had originally thought of closing this as a support request, but wanted to double-check with the engineering team. Client upgrades could have been one cause for this. But ultimately you'd need to engage with support to dig in further.
