### ISSUE TITLE
ConsoleBuilder

### ISSUE THREAD

**Issue by amar-r** [MicrosoftDocs/SCCMdocs#2013]
Hi, 

I mentioned last week in MMS Jazz edition if we could have documentation on Console Builder that would be fantastic.  Sort of a "How to use" documentation. I believe there are only a handful of blog posts from the community with some examples. 

You guys are the best! It was great meeting some of you. 

(admin edit: changing metadata to rehome to main SDK article as a closer target)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e4b9eb3-4d9c-69eb-6692-8ed943de5e94
* Version Independent ID: 4dda8059-5662-fe84-9163-f3f2f766e1be
* Content: [Configuration Manager SDK](https://docs.microsoft.com/en-us/configmgr/develop/core/misc/system-center-configuration-manager-sdk)
* Content Source: [sccm/develop/core/misc/system-center-configuration-manager-sdk.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/core/misc/system-center-configuration-manager-sdk.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @amar-r for the feedback at MMS, and thank you for filing this to track it. I need to do some investigation with engineering.

A quick search yielded the following blog post that at first glance appears to be fairly thorough: https://blogs.technet.microsoft.com/matt_hinsons_manageability_blog/2013/08/21/using-configmgr-2012-console-builder-create-custom-console-nodes/

**Comment by amar-r** [comment]
That is a good blog, thanks for sharing.  The more I think about it, I realize my goal is to make people more aware of it.  

The thought about documenting that software seems like a nightmare. I, personally, am fine with you guys closing this "issue".  However, if the engineering team can come up with something that'd be great too.

**Comment by duff2481** [comment]
Download link is broken for Configuration Manager SDK using above provided link. Can we fix?

**Comment by aczechowski** [comment]
@amar-r - thanks for the response. I talked more with the engineering team, and even doing something like porting Matt Hinson's blog is more effort than they're willing to invest right now. So I'll take you up on your offer and close this issue. 😄 If you think it deserves more attention, perhaps file an idea on UserVoice, then we can gauge community interest in more thorough support for the tool.

@duff2481 - long story short: aside from just the fact that there's a broken link in our docs that we need to fix, is there something you need from the SDK download that isn't already available elsewhere? (p.s. I'm closing this issue which is unrelated to the SDK download link, so if needed, please file another issue.)
