### ISSUE TITLE
Enabling feature

### ISSUE THREAD

**Issue by timmmay** [MicrosoftDocs/SCCMdocs#2018]
Can we add a prerequisite that this is a feature that must be enabled in the Configuration Manager console under Administration &gt; Updates and Servicing &gt; Features.  Without the feature enabled, the options for the Software Update Point are not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 054797d3-c4d8-2c2e-9940-e8763f6f3881
* Version Independent ID: 9751d801-35de-ebd8-29ea-57e459f845dc
* Content: [Enable third party updates - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/sum/deploy-use/third-party-software-updates#feedback)
* Content Source: [sccm/sum/deploy-use/third-party-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/third-party-software-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@timmmay Thanks for noticing that and letting us know! I'll get a note added that the optional feature needs to be enabled.
