### ISSUE TITLE
Customers without Configuration Manager

### ISSUE THREAD

**Issue by bchris999** [MicrosoftDocs/SCCMdocs#2019]
Are there any Windows Analytics features that aren't available in Desktop Analytics?
Yes, the following Windows Analytics features will either be retired or aren't yet available in Desktop Analytics:
Support for scenarios that don't require Configuration Manager.

- Can you provide details of what are the plans / options for customers that don't have Configuration Manager? (and have no plans to get Configuration Manager)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ec6aa6e-5695-4efa-c781-0554c112518c
* Version Independent ID: 6d588337-349a-2ae7-c5cc-8e53adf2d9d5
* Content: [FAQ for Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/desktop-analytics/faq#existing-windows-analytics-customers)
* Content Source: [sccm/desktop-analytics/faq.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @bchris999, aside from the first FAQ in this article ([Can I use Desktop Analytics with Intune-managed devices?](https://docs.microsoft.com/configmgr/desktop-analytics/faq#bkmk_intune)), we don't general include future plans in our technical documentation. To provide feedback on the service itself, please file an idea on the Configuration Manager [UserVoice site in the Desktop Analytics section](https://configurationmanager.uservoice.com/forums/300492-ideas?category_id=366805). I'm closing this issue as there's nothing actionable for docs.
