### ISSUE TITLE
Why Device health is not part anymore of desktop analytics? 

### ISSUE THREAD

**Issue by JuGhithub** [MicrosoftDocs/SCCMdocs#2021]
I don't really understand why Device health is not inside desktop analytics? There is a reason for it? Did you plan to reintagrate in the futur? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ec6aa6e-5695-4efa-c781-0554c112518c
* Version Independent ID: 6d588337-349a-2ae7-c5cc-8e53adf2d9d5
* Content: [FAQ for Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/desktop-analytics/faq#feedback)
* Content Source: [sccm/desktop-analytics/faq.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @JuGhithub, we don't generally include future plans in our technical documentation. To provide feedback on the service itself, please file an idea on the Configuration Manager [UserVoice site in the Desktop Analytics section](https://configurationmanager.uservoice.com/forums/300492-ideas?category_id=366805). I'm closing this issue as there's nothing actionable for docs.

**Comment by JuGhithub** [comment]
Hi,

OK to use uservoice, but why didyou remove device health?

Regards,
Julien guegan

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________
