### ISSUE TITLE
msDS-AllowedDNSSuffixes required?

### ISSUE THREAD

**Issue by Yupiter2005** [MicrosoftDocs/SCCMdocs#2022]
This article doesn't tell do we require msDS-AllowedDNSSuffixes to be configured or not for ConfigMgr. Do we, btw?
The statement is quite vague:
"To allow a computer to access domain controllers that are disjoint, change the msDS-AllowedDNSSuffixes Active Directory attribute on the domain object container."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c40b1d1-a46d-9e33-8bd5-f79e420d5d9c
* Version Independent ID: d90820d6-bd8f-34d9-68ac-5300bf4fb516
* Content: [Support for Active Directory domains - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/configs/support-for-active-directory-domains#configure-disjoint-namespace)
* Content Source: [sccm/core/plan-design/configs/support-for-active-directory-domains.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/support-for-active-directory-domains.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @Yupiter2005, thanks for the feedback, but can you clarify? I don't understand what you find vague. The statement seems very straight forward to me: In a disjointed namespace, configure that attribute.

**Comment by Yupiter2005** [comment]
We have AD infras that don't have msDS-AllowedDNSSuffixes configured and working: the customer just needs to use service user accounts whenever possible. Why exactly we require customers to use this attribute for ConfigMgr?

**Comment by aczechowski** [comment]
Hi @Yupiter2005, it's been that way for many years. To get help with a potential alternative solution, there are a couple of options:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
