### ISSUE TITLE
Enable BDR section

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/SCCMdocs#2025]
The BDR section implies that without BDR enabled, the whole software update package would be sent out.  This seems to conflict with https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/fundamental-concepts-for-content-management#feedback.  Wouldn't delta replication still apply, so that even with BDR disabled, only newly added and changed files would be replicated out (and deleted ones deleted) and not the whole package as stated here?  Would BDR be very beneficial w/software updates even though its almost always new files added, old ones deleted, vs blocks within the individual files changing?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc1bc8d-2e4b-650b-7644-84e5790e4630
* Version Independent ID: 9488c8c6-c912-1667-db02-f8a29f5c2023
* Content: [Automatically deploy software updates - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/sum/deploy-use/automatically-deploy-software-updates)
* Content Source: [sccm/sum/deploy-use/automatically-deploy-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/automatically-deploy-software-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
Edited BDR section to remove insinuation and just link to BDR page for more info on how BDR functions
