### ISSUE TITLE
If a file changes, use BDR to do the work 

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/SCCMdocs#2026]
In the section "BDR or delta replication" it states that it uses BDR to do the work if a file changes.  Why would you need to enable BDR in that case if it's using BDR to do the work for the file changes anyway when delta replication is in effect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff2f1985-822a-f9aa-8368-9abf85c50118
* Version Independent ID: 3401e963-f1cf-a15d-01f2-c1754a7d9336
* Content: [Content management fundamentals - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/fundamental-concepts-for-content-management#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @russrimm, we should clarify that a bit further - it only applies if the package is configured to use BDR. For some content, such as apps, the setting is enabled by default.

**Comment by aczechowski** [comment]
I made a change for this, it should publish live later today
