### ISSUE TITLE
Offboarding instructions need updating

### ISSUE THREAD

**Issue by gaknigge** [MicrosoftDocs/SCCMdocs#2027]
This document describes in two sections how to create an offboarding package for Configuration Manager. In both cases, it says logon to ATP and select the Endpoint Management menu. I don't actually see such a menu in ATP. I think the directions should say, logon to ATP and select Settings. Under the Machine Management heading, select Offboarding.
Thank you, Gary Knigge

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 565cfa51-ee26-5fbd-ab3d-e8176e994f78
* Version Independent ID: 441218c9-c56f-3532-145e-8039c67e6b1d
* Content: [Microsoft Defender Advanced Threat Protection - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/protect/deploy-use/windows-defender-advanced-threat-protection?redirectedfrom=MSDN)
* Content Source: [sccm/protect/deploy-use/windows-defender-advanced-threat-protection.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/windows-defender-advanced-threat-protection.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @gaknigge, it looks like the interface has changed since we created this article. There's an [ATP onboarding article](https://docs.microsoft.com/windows/security/threat-protection/microsoft-defender-atp/onboard-downlevel) that's consistent with your description.
