### ISSUE TITLE
Announcement blog post link broken

### ISSUE THREAD

**Issue by Stroell** [MicrosoftDocs/SCCMdocs#2029]
The Announcement blog post link is broken: 
https://aka.ms/cmannounce

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d85f062-c5c7-53f9-6bc6-958603bc6d57
* Version Independent ID: 690fc31d-2b4b-330f-7c07-1ded67e39bd0
* Content: [Technical preview 1911 - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/get-started/2019/technical-preview-1911)
* Content Source: [sccm/core/get-started/2019/technical-preview-1911.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/2019/technical-preview-1911.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@Stroell I'm not seeing that it's broken. The page comes up for me. HOWEVER, it looks like it isn't localized and might be English only. When I change en-us to de-de or es-es, the page isn't found. Are you seeing your URL trying to reach the de-de site automatically?

Works for me: 
https://www.microsoft.com/en-us/microsoft-365/blog/2019/11/04/use-the-power-of-cloud-intelligence-to-simplify-and-accelerate-it-and-the-move-to-a-modern-workplace/ 
Doesn't work for me: 
- https://www.microsoft.com/de-de/microsoft-365/blog/2019/11/04/use-the-power-of-cloud-intelligence-to-simplify-and-accelerate-it-and-the-move-to-a-modern-workplace/
- https://www.microsoft.com/es-es/microsoft-365/blog/2019/11/04/use-the-power-of-cloud-intelligence-to-simplify-and-accelerate-it-and-the-move-to-a-modern-workplace/

**Comment by Stroell** [comment]
Ah good point. Yep that seems to be the issue

**Comment by mestew** [comment]
I'm going to hardcode the aka link to en-us for now until we can get to the bottom of this. Thanks for the heads up! I appreciate it.
