### ISSUE TITLE
the execution of connect-autopilotintune is not valid

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/SCCMdocs#2031]
Moving this from here: https://github.com/MicrosoftDocs/SCCMDocs.zh-cn/issues/8

@goxia commented 18 hours ago — with docs.microsoft.com

My current system version is 1909, according to the documentation installation and import module (install-moudel azure and install-module windowsautopilotintune and import-module windowsautopilotintune), the execution of connect-autopilotintune is not valid, is the need to restart the boot of the computer? Not in detail in the documentation?
文档详细信息

⚠ 请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。

    ID: bed718c9-fa4d-d78e-3be2-fbc390a80406
    Version Independent ID: cd67f1d8-70a9-1a70-4d8f-1a8063aa0857
    Content: 面向现有设备的 Windows Autopilot - Configuration Manager
    Content Source: sccm/osd/deploy-use/windows-autopilot-for-existing-devices.md
    Product: configuration-manager
    Technology: configmgr-osd
    GitHub Login: @aczechowski
    Microsoft Alias: aaroncz

@goxia docs.microsoft.com
Author
goxia commented 18 hours ago — with docs.microsoft.com

After testing and validation, I found that connect-msgraph should be used instead of connect-autopilotintune, and if the document ation is correct, then a bug may have occurred on windowsauto modulepilot ver 3.7.
@srvbpigh
Member
srvbpigh commented 17 hours ago

Hello, @goxia

Thank you for your feedback.

We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team
@srvbpigh srvbpigh assigned CeciAc 17 hours ago

@aczechowski commented 16 hours ago

Thanks @goxia for the feedback. I'll need to check with the engineering team.

@CeciAc please move this over to SCCMDocs

Here's the metadata for the target article:
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

    ID: bed718c9-fa4d-d78e-3be2-fbc390a80406
    Version Independent ID: cd67f1d8-70a9-1a70-4d8f-1a8063aa0857
    Content: Windows Autopilot for existing devices - Configuration Manager
    Content Source: sccm/osd/deploy-use/windows-autopilot-for-existing-devices.md
    Product: configuration-manager
    Technology: configmgr-osd
    GitHub Login: @aczechowski
    Microsoft Alias: aaroncz

@goxia
Author
goxia commented 14 hours ago

    Thanks @goxia for the feedback. I'll need to check with the engineering team.

    @CeciAc please move this over to SCCMDocs

    Here's the metadata for the target article:
    Document Details

    ⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

        ID: bed718c9-fa4d-d78e-3be2-fbc390a80406
        Version Independent ID: cd67f1d8-70a9-1a70-4d8f-1a8063aa0857
        Content: Windows Autopilot for existing devices - Configuration Manager
        Content Source: sccm/osd/deploy-use/windows-autopilot-for-existing-devices.md
        Product: configuration-manager
        Technology: configmgr-osd
        GitHub Login: @aczechowski
        Microsoft Alias: aaroncz

I saw this article "https://oofhours.com/2019/11/02/whats-new-with-the-windowsautopilotintune-powershell-module/"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bed718c9-fa4d-d78e-3be2-fbc390a80406
* Version Independent ID: cd67f1d8-70a9-1a70-4d8f-1a8063aa0857
* Content: [Windows Autopilot for existing devices - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/osd/deploy-use/windows-autopilot-for-existing-devices)
* Content Source: [sccm/osd/deploy-use/windows-autopilot-for-existing-devices.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/windows-autopilot-for-existing-devices.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @goxia for the feedback. I confirmed with the PM:

> We changed the WindowsAutopilotIntune module to be based on the Microsoft.Graph.Intune module, leveraging it for authentication and web requests.  (That has the benefit of only requiring you to authenticate once as you do things across Intune and Autopilot.)  As a result, you need to use “Connect-MSGraph” to authenticate instead of “Connect-AutopilotIntune”.
>
> The WindowsAutopilotIntune module will automatically install Microsoft.Graph.Intune and NuGet if it needs to, but if they are already installed it will use what’s there.  So while they are dependencies now, it should “just work” if they switch to “Connect-MSGraph.”
> 
> Reading through the rest of the doc, it should still work if you change “Connect-AutopilotIntune” to “Connect-MSGraph”.

**Comment by goxia** [comment]
@aczechowski thank you a lot.

**Comment by lijo123456** [comment]
Please update the documentation to use  Connect-MSGraph instead of  Connect-AutopilotIntune .

https://oofhours.com/2019/11/02/whats-new-with-the-windowsautopilotintune-powershell-module/

**Comment by aczechowski** [comment]
Thanks to @adriandavey for fixing this issue in #2308
