### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by stromnessian** [MicrosoftDocs/SCCMdocs#2032]
Does this mean that CM clients that use WUfB instead of CM for Windows/Microsoft updates will be able to take advantage of DOINC?  I'm assuming so, but just wanted confirmation.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3da55fd-6184-9baa-9278-9d807a7e44db
* Version Independent ID: 115bdf2d-7766-0053-11b2-5d36260fe4f8
* Content: [Delivery Optimization In-Network Cache - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/delivery-optimization-in-network-cache#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/delivery-optimization-in-network-cache.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/delivery-optimization-in-network-cache.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @stromnessian, yes, as listed in the [Verify](https://docs.microsoft.com/configmgr/core/plan-design/hierarchy/microsoft-connected-cache#verify) section:

> Cloud-managed content includes the following types:
>
> ...
> - If you enable [Windows Update for Business policies](https://docs.microsoft.com/sccm/sum/deploy-use/integrate-windows-update-for-business-windows-10): Windows 10 feature and quality updates

I'm closing this issue as I don't think there's anything actionable for docs at this time. If you disagree, please reopen and let me know your feedback on how I can better clarify. Thanks!
