### ISSUE TITLE
MVLC XML file

### ISSUE THREAD

**Issue by kyouells** [MicrosoftDocs/SCCMdocs#2033]
This article says to contact Microsoft to learn how to create an XML file from MVLC.  The MVLC Team says there is no way to export licensing to XML, it can only be CSV.  So why does this article say to contact Microsoft to find out how to export to XML? 

(admin edit: add metadata to link with assumed target article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f49b9244-7797-8fbb-afb9-dd245692be2f
* Version Independent ID: 5c7d7bde-2fe5-54f6-55fe-db4b2631f9a7
* Content: [Upgrade Windows devices to a different version - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/compliance/deploy-use/upgrade-windows-version)
* Content Source: [sccm/compliance/deploy-use/upgrade-windows-version.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/compliance/deploy-use/upgrade-windows-version.md)
* Product: **configuration-manager**
* Technology: **configmgr-compliance**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @kyouells, can I assume you're referring to this article? https://docs.microsoft.com/configmgr/compliance/deploy-use/upgrade-windows-version. It's the only one I can think of and find that references both VLSC and an XML file.

**Comment by aczechowski** [comment]
Ok, assuming that's what you're talking about, see this [blog post](https://blogs.technet.microsoft.com/mniehaus/2016/02/23/building-a-provisioning-package-to-upgrade-to-windows-10-mobile-enterprise/) that has more detail. I have limited VLSC access, and was able to find the ISO for Windows 10 Mobile Enterprise which includes this license XML. That's what this article is referencing. As far as I know, this is the only Windows 10 edition that supports this XML process at this time. So we can definitely improve the level of detail in this article on how to find this XML file.

**Comment by aczechowski** [comment]
I made a change for this issue, it should publish live later today
