### ISSUE TITLE
Cloud Services Usage Estimation not present in 1906

### ISSUE THREAD

**Issue by DavidHBaur** [MicrosoftDocs/SCCMdocs#2036]
Where it states "In the Configuration Manager console, go to the Monitoring workspace, and select the Cloud Management node." There is no "Cloud Services Usage Estimation" listed in that area, just information showing connections. 
Are there other requirements as the links to other documentation do not show anything that has to be done to be able to see this...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa77f39-daa6-299e-d1ea-5e9595878761
* Version Independent ID: b4d05af0-610e-0e62-2c13-8b45bc734b5d
* Content: [Technical preview 1903 - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/get-started/2019/technical-preview-1903#bkmk_cmg)
* Content Source: [sccm/core/get-started/2019/technical-preview-1903.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/2019/technical-preview-1903.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @DavidHBaur, yes this feature is still only in technical preview branch and not available yet in the current branch. See the list of [Features in previous technical previews](https://docs.microsoft.com/configmgr/core/get-started/technical-preview#features-in-previous-technical-previews).
I'm closing this issue as there's nothing actionable for docs at this time.
