### ISSUE TITLE
Support for 1903 and 1909

### ISSUE THREAD

**Issue by jleger88** [MicrosoftDocs/SCCMdocs#2037]
Does MDT 8456 support Windows 10, versions 1903 and 1909?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b1c8a5d-b639-d555-0850-b98a9010023c
* Version Independent ID: b20fdb1c-8d40-c3b2-2265-779a3f2dfe98
* Content: [MDT release notes](https://docs.microsoft.com/en-us/configmgr/mdt/release-notes#feedback)
* Content Source: [sccm/mdt/release-notes.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdt/release-notes.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @jleger88, see the following question from the [MDT release notes FAQ](https://docs.microsoft.com/configmgr/mdt/release-notes#frequently-asked-questions):

> **Is this release only supported with Windows 10, Windows ADK, or Configuration Manager version X?**
> We primarily tested this build of MDT with the configuration listed above. Unless there are any explicit known issues, anything outside of the above configuration has a high probability of still working. Your mileage may vary as we haven’t explicitly tested other combinations.

I'm closing this issue as there isn't anything actionable for docs
