### ISSUE TITLE
Customized image

### ISSUE THREAD

**Issue by TonitoDux** [MicrosoftDocs/SCCMdocs#2038]
Hi,

the sentence: "You have custom requirements including using a custom base image, using third-party disk encryption, or require WinPE offline operations." I am having an issue where I want to clear out built in apps, I do this with dism, but still after the TS is finished, I get the "original" OS with all the built in apps installed. Why is this happening?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05088ead-21fe-a787-b5b6-d0a90c219f5b
* Version Independent ID: a801446b-a068-f305-3fcc-a84420698bb9
* Content: [Upgrade to Windows 10 - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/osd/deploy-use/upgrade-windows-to-the-latest-version#feedback)
* Content Source: [sccm/osd/deploy-use/upgrade-windows-to-the-latest-version.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/upgrade-windows-to-the-latest-version.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @TonitoDux for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
