### ISSUE TITLE
What's windows auth states for?

### ISSUE THREAD

**Issue by Yupiter2005** [MicrosoftDocs/SCCMdocs#2039]
&gt;Windows authentication: Require authentication with Active Directory domain credentials. This setting is the previous behavior, and the current default setting. When you update the site, there's no change to the authentication level.

Is it about Kerberos or NTLM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 070c2bc6-3086-7237-d19c-951f000b4531
* Version Independent ID: 95c62945-77dc-0ce0-e4ee-1116343b7ea6
* Content: [Plan for the SMS Provider - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/plan-for-the-sms-provider)
* Content Source: [sccm/core/plan-design/hierarchy/plan-for-the-sms-provider.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/plan-for-the-sms-provider.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Yupiter2005, it's the same way that the provider has authentication users for years. So it depends upon how you configure Windows authentication on your devices in your domain. If a user can authenticate to Windows using AD credentials, and they are a user in ConfigMgr, then they can query the SMS Provider using the console or other methods. ConfigMgr itself doesn't handle the authentication, it relies upon Windows.
