### ISSUE TITLE
Need a rewrite of a paragraph

### ISSUE THREAD

**Issue by baardhermansen** [MicrosoftDocs/SCCMdocs#2041]
There's a paragraph in need of a rewrite, seems to be lacking both punctuation and a few words:

"For a co-managed device and when Intune is configured to take ConfigMgr compliance assessment result as part of the overall compliance status that gets sent to Azure Active Directory and be used for conditional access to customers' Office 365 resources."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a304313-63b1-3904-c38d-20bdcc04c0c2
* Version Independent ID: bff30820-5e3f-3536-9c06-717ed5438457
* Content: [What's new in version 1910 - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/changes/whats-new-in-version-1910)
* Content Source: [sccm/core/plan-design/changes/whats-new-in-version-1910.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/changes/whats-new-in-version-1910.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @baardhermansen for the feedback! I just revised that paragraph
Fixed by MicrosoftDocs/SCCMDocs-PR#4732
Change is live now
