### ISSUE TITLE
Analyze method for Unknown Readiness not mentioned

### ISSUE THREAD

**Issue by sainirak** [MicrosoftDocs/SCCMdocs#2044]
no information on conversion process of Packages which are in unknown readiness status 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fddea97-52c4-a4ef-09f2-1f3c32dc1d03
* Version Independent ID: b6eb170d-20d0-a97a-72f5-0c0204c992cd
* Content: [How to analyze and convert packages - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/apps/pcm/how-to-analyze-and-convert#feedback)
* Content Source: [sccm/apps/pcm/how-to-analyze-and-convert.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/pcm/how-to-analyze-and-convert.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @sainirak for the feedback! I checked with the engineering team, we should add information to this article. For a package with a state **Unknown**, first run the **Analyze** task, or wait for the next scheduled analysis. If the state doesn't change, then the next step is to [Troubleshoot PCM](https://docs.microsoft.com/configmgr/apps/pcm/troubleshoot-pcm).
