### ISSUE TITLE
Cache retention

### ISSUE THREAD

**Issue by Stroell** [MicrosoftDocs/SCCMdocs#2045]
Please document how long content is kept on the Connected Cache Server.
If it is possible to configure the value, please document that as well
Thanks :-) 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c1fbe6e8-4883-644e-8412-2e69759fe482
* Version Independent ID: 41f3fdea-c476-bd2b-131b-1100bbede7b2
* Content: [Microsoft Connected Cache - Configuration Manager](https://docs.microsoft.com/de-de/configmgr/core/plan-design/hierarchy/microsoft-connected-cache)
* Content Source: [sccm/core/plan-design/hierarchy/microsoft-connected-cache.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/microsoft-connected-cache.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by andyrivMSFT** [comment]
Connected Cache is using IIS Application Request Routing to build the web farms where the content is cached.  The default cache size on disk is set to 100 GB.  If cache size on disk size exceeds the allocated space, then ARR will clear space by removing content based on ARR heuristics. We don't provide any cache purging functionality in ConfigMgr.

One of the ways you can view the size size of the cache on disk is by looking at the Microsoft Connected Cache farm (DOINC) and viewing the properties under Monitoring and Management.

**Comment by aczechowski** [comment]
I've made changes for this issue that will publish with the 2002 content, which will go live soon. I'm closing this issue.
