### ISSUE TITLE
Restore certificate Section missing END

### ISSUE THREAD

**Issue by JordiSG** [MicrosoftDocs/SCCMdocs#2049]
On the SQL script to restore the Certificate (https://docs.microsoft.com/en-us/configmgr/protect/deploy-use/bitlocker/encrypt-recovery-data#restore-certificate), it's missing an "END" at the end of the script

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a2f36a3-1dfd-4116-9600-7614df64ce50
* Version Independent ID: 21f250a8-199d-5a4d-1180-c82ee058d1a7
* Content: [Encrypt recovery data - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/protect/deploy-use/bitlocker/encrypt-recovery-data#feedback)
* Content Source: [sccm/protect/deploy-use/bitlocker/encrypt-recovery-data.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/bitlocker/encrypt-recovery-data.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @JordiSG for catching that. If you want to submit an edit for this, see [How to contribute](https://docs.microsoft.com/configmgr/core/understand/use-docs#bkmk_contribute). 😉

**Comment by JTav-64** [comment]
The comments about the restore and backup scripts requiring "END" are incorrect. "END" is needed if the script has a "BEGIN" statement (such as the script above to create the certificate), but neither the MBAM cert Backup or Restore script has a "BEGIN" statement and "END" is not needed. If you add it, the script will fail with a syntax error near "END."

**Comment by aczechowski** [comment]
Thanks @JTav-64 for the explanation. Pull request #2133 should resolve the issue.
