### ISSUE TITLE
Spelling error 

### ISSUE THREAD

**Issue by merlinfrombelgium** [MicrosoftDocs/SCCMdocs#2055]
In the first note on this page, it says 'complaint' in stead of 'compliant'

PCs should be domain joined or be complaint with the policies set in Intune.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69caa436-7335-8209-200f-3d9b8e86e7b4
* Version Independent ID: 3bf97b11-a3ed-e089-24f1-4c609b490fe0
* Content: [Manage SharePoint Online access - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/mdm/deploy-use/manage-sharepoint-online-access#feedback)
* Content Source: [sccm/mdm/deploy-use/manage-sharepoint-online-access.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/manage-sharepoint-online-access.md)
* Product: **configuration-manager**
* Technology: **configmgr-hybrid**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @merlinfrombelgium - likely this article will be removed completely in a few weeks with the hybrid retirement. but before I just close this issue, I need to check whether this functionality persists without hybrid.
