### ISSUE TITLE
DistributionPointInstallIIS

### ISSUE THREAD

**Issue by codaamok** [MicrosoftDocs/SCCMdocs#2059]
When trying to install 1902 base line, if you don't specify `DistributionPointInstallIIS` in the .ini file the installation coughs up an error that the configuration file is incorrect. A lot of examples online suggest `DistributionPointInstallIIS=0` but then the IIS components for the DP aren't created, whereas if `DistributionPointInstallIIS=1` then they are. It appears `DistributionPointInstallIIS` isn't documented here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a393419-2d34-ebba-9482-7c988797f5c9
* Version Independent ID: 95f509c1-5494-7f40-6392-6f7f8988dd2e
* Content: [Setup command-line options - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/servers/deploy/install/command-line-options-for-setup)
* Content Source: [sccm/core/servers/deploy/install/command-line-options-for-setup.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/command-line-options-for-setup.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @codaamok for the feedback. We moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. Since then, another item was filed on the new article under docs.microsoft.com/mem/configmgr: 
MicrosoftDocs/memdocs#717. So we'll track this request under the new issue.
