### ISSUE TITLE
configuration manager console -documentation

### ISSUE THREAD

**Issue by MOHZM** [MicrosoftDocs/SCCMdocs#2062]
Hi ,
Unable to access to Community Node -Documentation section in configuration manager console and getting the below erorr .

"An error occurred while retrieving content

The following exception occurred.

Exception type: System.Net.Http.HttpRequestException + System.Net.WebException
Message: An error occurred while sending the request. The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

Please check internet proxy settings and connectivity then click Retry to load the page."

![SCCM_documentation](https://user-images.githubusercontent.com/58650529/70385861-5e8e4580-19a2-11ea-80b3-a936080e4429.PNG)

>>>>
I know the issue related to proxy since we're it .
Can you share the required URL for access documentation.

**Comment by aczechowski** [comment]
Hi @MOHZM, see the following article for the required URLs to allow: [Internet access requirements - Community workspace, Documentation node](https://docs.microsoft.com/configmgr/core/plan-design/network/internet-endpoints#community-workspace-documentation-node)
