### ISSUE TITLE
PowerShell Execution Policy can't be set to Restricted. (are the scripts signed?)

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/SCCMdocs#2064]
Our policy is set to allsigned, will that work?  We already know that Win10 diagnostics don't work in our environment because the PS1 scripts used for that aren't signed.  Are these ones signed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7bd107-2a52-dcac-92a9-3b756a84114a
* Version Independent ID: 024860de-ea76-6bf5-06ad-0cc08d1a7949
* Content: [Deploy and update Microsoft Edge, version 77 and later - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/apps/deploy-use/deploy-edge)
* Content Source: [sccm/apps/deploy-use/deploy-edge.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/deploy-edge.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by PaulKlerkx** [comment]
Does this Edge Install replace the built in Edge or add an extra Edge like the currently available online version?

**Comment by aczechowski** [comment]
Thanks @PaulKlerkx for the feedback.
- This install adds an extra Edge, it doesn't replace the built-in version.
- The PowerShell script is Microsoft signed, so it should work with AllSigned or RemoteSigned. (If it doesn't, file a frown.) This tidbit is useful info that should probably be included in this article as a tip.

**Comment by PaulKlerkx** [comment]
awesome, thanks for the info.
