### ISSUE TITLE
question about provide the following driver content to Windows Setup 

### ISSUE THREAD

**Issue by Typhoon87** [MicrosoftDocs/SCCMdocs#2066]
Can the docs clarify how the driver content is provided if driver package is chosen?

If choosing a driver package is the whole package chosen? of does it load it in real time from the DP? it seems like driver package would be the preferred choice but if you choose multiple packages and there is no way to limit via WMI query you could end up downloading gigs of packages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1187d55d-d8b3-ebc8-37e8-8de14807be4e
* Version Independent ID: daff4a99-10ac-b424-f08a-9024407e667a
* Content: [Task sequence steps - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/osd/understand/task-sequence-steps)
* Content Source: [sccm/osd/understand/task-sequence-steps.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/understand/task-sequence-steps.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Typhoon87 for the feedback. It depends upon the step that you're using. For an overivew, see [Use task sequences to install drivers](https://docs.microsoft.com/configmgr/osd/get-started/manage-drivers#BKMK_TSDrivers). For more detail, see the sections for each step:

- [Auto Apply Drivers](https://docs.microsoft.com/configmgr/osd/understand/task-sequence-steps#BKMK_AutoApplyDrivers)
- [Apply Driver Package](https://docs.microsoft.com/configmgr/osd/understand/task-sequence-steps#BKMK_ApplyDriverPackage)

If you use the **Apply Driver Package** step, also lookat at how to 
[Configure pre-cache content](https://docs.microsoft.com/configmgr/osd/deploy-use/configure-precache-content). I think this last bit might be to your main question.

I'll keep this feedback open, I think we could expand upon this topic a bit more in this article, and make references to these other resources. Especially on the Apply Driver Package section, linking to the pre-cache content article.

**Comment by Typhoon87** [comment]
Maybe some additional data to help clarify. 
Scenario: 
-Using SCCM 1902
- using the MS provided "upgrade an operating system" sccm template
- for the operating system install example from 1709 to 1809 and you need updated driver packs for some models.
- You check the box for "provide the following driver content to Windows Setup during upgrade" then choose the "Driver Package" bubble. You click browse and choose the packages for all applicable hardware manufactures and models.

If you do this and there is no WMI query to have it parse the model to package correlation how does the setup manage that. Does it download all the drivers at once potentially bloating the space needed and putting extra strain on DP's.
Does it scan all drivers then download only those applicable by hardware id but not a model WMI query?
                               If so this could cause drivers for the same hardware ID but that belong to                                    different driver packages to be mixed and matched potentially causing issues if you worry about hardware vendor version certification.

The documentation does not seem to make clear how this works if you choose multiple driver packs.


Upon looking at the precache driver package this could likely work you would just need a step for each model with a WMI query on each step putting them all in the same location and with the same path variable. If I understand this correctly?

**Comment by mikep12** [comment]
Typhoon87: "You check the box for "provide the following driver content to Windows Setup during upgrade" then choose the "Driver Package" bubble. You click browse and choose the packages for all applicable hardware manufactures and models."
You can't select multiple driver packages here or am I doing something wrong?
As far as I know the only way to pre-cache a driver package in an upgrade task sequence is to create a separate task sequence for each hardware/driver package.

**Comment by aczechowski** [comment]
Thanks @Typhoon87 for the clarification. That option in the Upgrade OS step just passes the content to the [InstallDrivers](https://docs.microsoft.com/windows-hardware/manufacture/desktop/windows-setup-command-line-options#12) parameter for Windows Setup. So it's pretty simple. There's then some more complexity with respect to how Windows Setup handles drivers during in-place upgrade.

If you want to have dynamic content for multiple types of hardware, you'd have to have multiple instances of the step with conditions to distinguish.

Alternatively, you could use multiple instances of the Download Package Content step to place the content in a common location. Then use the "Staged content" option. The benefit here is you have a single Upgrade OS step.

**Comment by aczechowski** [comment]
I made some changes for this issue, but in the 2002 current branch content. This issue will automatically close when the edit merges into our release branch, but it won't publish live until that release.
