### ISSUE TITLE
Links to the DaRT tool are broken

### ISSUE THREAD

**Issue by jeremycolby** [MicrosoftDocs/SCCMdocs#2067]
[Enter feedback here]
These links are broken:
https://www.microsoft.com/en-us/download/details.aspx?id=9257
https://www.microsoft.com/windows/enterprise/products-and-technologies/mdop/dart.aspx

How/where do I get trace32?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37c2dfad-c2e9-1576-c360-36dacb375094
* Version Independent ID: 0a0bd691-d280-c583-7057-d0785bdba205
* Content: [Troubleshoot MDT - Microsoft Deployment Toolkit](https://docs.microsoft.com/en-us/configmgr/mdt/troubleshooting-reference)
* Content Source: [sccm/mdt/troubleshooting-reference.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdt/troubleshooting-reference.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jeremycolby for the feedback. It looks like the latest(?) information is here: https://docs.microsoft.com/microsoft-desktop-optimization-pack/dart-v10/

CMTrace is the current version of the basic log viewer. See https://docs.microsoft.com/configmgr/core/support/cmtrace

**Comment by aczechowski** [comment]
I'm in this article fixing another broken link, will catch this at the same time.
