### ISSUE TITLE
WSUS database now supported in an availability group

### ISSUE THREAD

**Issue by stelmer** [MicrosoftDocs/SCCMdocs#2068]
I was told we can move our WSUS database to SQL Always On now.  Can the unsupported database section be updated to reflect this?

(admin edit: adding metadata for proper article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53d1da83-d988-fb2b-82c5-fd9cf117cd42
* Version Independent ID: 2b1a3bd2-5116-1f21-c196-e3e5698a83c9
* Content: [SQL Server Always On - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database#unsupported-database-use)
* Content Source: [sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @stelmer, who told you that? 😉 I'm also checking on it, but if you have a source for that information, that would be helpful.

**Comment by stelmer** [comment]
My DSE, Andrew Frazier chased down the answer.  We wanted to move them last summer and he came back with the answer. 
    	
    	

    	
    
  




On Thu, Dec 12, 2019 at 11:54 AM -0600, "Aaron Czechowski" <notifications@github.com> wrote:












Hi @stelmer, who told you that? 😉 I'm also checking on it, but if you have a source for that information, that would be helpful.

**Comment by brmcmill** [comment]
I can see where customers can be confused by this blog post:

https://techcommunity.microsoft.com/t5/Device-Management-in-Microsoft/Moving-the-WSUS-database-to-SQL-Always-On/ba-p/377239

**Comment by aczechowski** [comment]
Thanks @brmcmill, that's exactly the reference.

@stelmer, I followed up with your DSE, he should be in touch. 

That blog post isn't an official statement of support from the WSUS team. It's from Microsoft IT on how they implemented it, and includes the following disclaimer:

> **Disclaimer**: This WSUS configuration may not be explicitly supported and this blog post is for informational purposes. This post is provided “AS IS” with no warranties and confers no rights.

WSUS places the database in single-user mode during upgrade, which isn't allowed in an availability group. So that design would need to change for WSUS to support SQL Always On.

I'm closing this issue.
