### ISSUE TITLE
Compatibility settings for CNG certificates

### ISSUE THREAD

**Issue by MichielOverweel** [MicrosoftDocs/SCCMdocs#2070]
For CNG certificates , the Certification Authority and Certificate recipient compatibility settings need to be set to at least Windows Vista/Windows Server 2008, with the recommended value being Windows 8/Windows Server 2012 (see https://docs.microsoft.com/en-us/configmgr/core/plan-design/network/cng-certificates-overview#to-use-cng-certificates). Now that almost all site system roles support CNG certificates, there doesn't appear to be any need to set the compatibility settings to Windows XP/Windows Server 2003 anymore. Maybe it's time this article is re-written for a Windows Server 2012 R2 (or later) CA with CNG certificate templates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c66e3e8a-bd8e-7ae3-aecc-cd9073e2238e
* Version Independent ID: 45572c91-8194-096d-2356-80a9b1b356ef
* Content: [Example PKI certificate deployment - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/network/example-deployment-of-pki-certificates#feedback)
* Content Source: [sccm/core/plan-design/network/example-deployment-of-pki-certificates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/network/example-deployment-of-pki-certificates.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks for the feedback @MichielOverweel, this article is unfortunately in need of some major review and revision, or just retirement completely.

**Comment by aczechowski** [comment]
I'm resolving this issue in part because we moved repositories, but also because I'm going to track this work via an internal work item.

(internal reference 2841906)
