### ISSUE TITLE
Supported computers for Microsoft Defender

### ISSUE THREAD

**Issue by saranrajappa** [MicrosoftDocs/SCCMdocs#2073]
"Intune hybrid MDM-managed computers are not supported." - This is bit confusing to me. Are you saying co-managed (Config Manager+Intune) computers are not supported ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 565cfa51-ee26-5fbd-ab3d-e8176e994f78
* Version Independent ID: 441218c9-c56f-3532-145e-8039c67e6b1d
* Content: [Microsoft Defender Advanced Threat Protection - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/protect/deploy-use/windows-defender-advanced-threat-protection#feedback)
* Content Source: [sccm/protect/deploy-use/windows-defender-advanced-threat-protection.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/windows-defender-advanced-threat-protection.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @saranrajappa, hybrid is a now deprecated service that allowed you to manage MDM-enrolled devices (including iOS and Android) in the ConfigMgr console. For more information, see [What is hybrid MDM](https://docs.microsoft.com/configmgr/mdm/understand/hybrid-mobile-device-management). With hybrid, a Windows device could be a ConfigMgr client, or enrolled to Intune, not both. In the case of the latter, it would still show up in ConfigMgr, but managed via MDM. 

Co-management is completely different. Devices are ConfigMgr clients *and* enrolled to Intune. So then depending upon which authority manages which workload determine which service provides the management. For more information, see [What is co-management](https://docs.microsoft.com/configmgr/comanage/overview)

The good news is that particular comment will be removed in the near future as we retire all of the hybrid content. So I'm closing this issue.

**Comment by saranrajappa** [comment]
Thank you. Please close

Thanks & Regards,
Saravanan Rajappa


On Dec 12, 2019, at 11:35 PM, Aaron Czechowski <notifications@github.com> wrote:

﻿

Hi @saranrajappa<https://github.com/saranrajappa>, hybrid is a now deprecated service that allowed you to manage MDM-enrolled devices (including iOS and Android) in the ConfigMgr console. For more information, see What is hybrid MDM<https://docs.microsoft.com/configmgr/mdm/understand/hybrid-mobile-device-management>. With hybrid, a Windows device could be a ConfigMgr client, or enrolled to Intune, not both. In the case of the latter, it would still show up in ConfigMgr, but managed via MDM.

Co-management is completely different. Devices are ConfigMgr clients and enrolled to Intune. So then depending upon which authority manages which workload determine which service provides the management. For more information, see What is co-management<https://docs.microsoft.com/configmgr/comanage/overview>

The good news is that particular comment will be removed in the near future as we retire all of the hybrid content. So I'm closing this issue.
