### ISSUE TITLE
Visio version of drawing

### ISSUE THREAD

**Issue by thomasrysgaard** [MicrosoftDocs/SCCMdocs#2075]
Is it possible to get the architecture picture in Visio format? SVG Editors does not read that picture formatting very well, so a Visio version would be great. That way I can also incorporate or build upon the components.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f24ae716-bf27-7d45-cb15-0bc6eea64374
* Version Independent ID: f444ef64-9b7d-999f-3fb3-6ac6cda3ef88
* Content: [Co-management for Windows 10 devices - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/comanage/overview#feedback)
* Content Source: [sccm/comanage/overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @thomasrysgaard, sorry but the docs platform doesn't support that file type. SVG is the preferred file type for conceptual art. I have two suggestions:
- File [site feedback](https://aka.ms/sitefeedback), which is also a link in the footer of every docs.microsoft.com page. That feedback goes to the docs.ms platform team, so you could ask/suggest that they support other file types like Visio.
- Download the [Microsoft Azure Cloud and AI Symbol / Icon Set](https://www.microsoft.com/download/details.aspx?id=41937) - it *used* to include Visio templates
I'm closing this issue
