### ISSUE TITLE
Reboots for Applications in Application Groups

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/SCCMdocs#2081]
Can you add a known issue for Application Groups that indicates that in 1910 applications that require a reboot will cause the application group to return a failed status?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b75008-ff8a-3cef-f465-1bc93f7caa42
* Version Independent ID: fe6e1908-4efc-db07-9d84-24ee7b8d74e7
* Content: [Create application groups - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/apps/deploy-use/create-app-groups)
* Content Source: [sccm/apps/deploy-use/create-app-groups.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/create-app-groups.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @AdamGrossTX for the feedback. I added a bullet for this, should publish live in the next hour or so.
