### ISSUE TITLE
Query distinct or not

### ISSUE THREAD

**Issue by alien418** [MicrosoftDocs/SCCMdocs#2084]
Is there a difference in collection query membership rule evaluation cost (evaluation duration) between select and select distinct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 669ca4f9-5d5d-acd7-cdbe-7b3127bb4a58
* Version Independent ID: c2e872b3-4faf-820c-c0f1-84963955f9d5
* Content: [Create collections - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/manage/collections/create-collections#feedback)
* Content Source: [sccm/core/clients/manage/collections/create-collections.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/collections/create-collections.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @alien418 for the filing this feedback. “Select distinct” may result in less rows, so potentially quicker. A useful note to add to this article.

**Comment by aczechowski** [comment]
Thanks to @jpcast88 for adding a tip for this issue. The change will publish live on Monday around 11am Pacific.
