### ISSUE TITLE
AD Site Boundaries are not supported for non domain joined machines

### ISSUE THREAD

**Issue by PingMudit** [MicrosoftDocs/SCCMdocs#2086]
As per MS Ticket# 17257511, the information which I got is from Support Escalation Engineer is AD Sites boundaries in SCCM are not supported during OSD before client joins to domain.
Kindly update this in documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6115449-e733-5bb3-9b9d-b9b39ca33602
* Version Independent ID: 0fa0910c-af20-e914-bd12-4f4514a3135c
* Content: [Use boundaries and boundary groups - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/servers/deploy/configure/define-site-boundaries-and-boundary-groups#feedback)
* Content Source: [sccm/core/servers/deploy/configure/define-site-boundaries-and-boundary-groups.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/define-site-boundaries-and-boundary-groups.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks again for the feedback. I made a change to this article to note the behavior. Although after speaking with engineering, the behavior is different. There is a SQL stored procedure specifically for this process to convert AD site boundaries to IP subnets for Windows PE devices during OSD.
This issue will auto close when my change merges. It will then go live during the next daily publishing cycle, which should be later today.
