### ISSUE TITLE
WinRM 1.1 link to support article 936059 says page not found

### ISSUE THREAD

**Issue by Ska-IsTheBest** [MicrosoftDocs/SCCMdocs#2094]
When visiting the support link for more info about downloading WinRM 1.1, it says page not found.
https://support.microsoft.com/help/936059

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db678f94-700f-ad35-9fdc-d165893b5373
* Version Independent ID: 2ee761db-4b3b-6fa0-c195-ad85ebbac70d
* Content: [Prerequisite checks - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/servers/deploy/install/list-of-prerequisite-checks#sql-server-native-client)
* Content Source: [sccm/core/servers/deploy/install/list-of-prerequisite-checks.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/list-of-prerequisite-checks.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @Ska-IsTheBest for the feedback. I have a change in for this issue. It should auto-close the issue shortly, but with the holiday publishing freeze, it won't be live until Thursday, 26 December.
