### ISSUE TITLE
Client Cache Settings

### ISSUE THREAD

**Issue by ajp999** [MicrosoftDocs/SCCMdocs#2095]
Within the Configuration Manager client settings there is no longer an option 'Under Client Cache Settings, set Enable Configuration Manager client in full OS to share content to Yes'. It appears this has been replaced by the option 'Enable as peer cache source'. In addition the setting 'Enable HTTPS for client peer communication' no longer exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd7a196d-4829-4b01-0bc0-8c14fd52dc1a
* Version Independent ID: db302fc5-0610-b270-0202-16fb4606a588
* Content: [Prepare Windows PE peer cache to reduce WAN traffic - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/osd/get-started/prepare-windows-pe-peer-cache-to-reduce-wan-traffic#feedback)
* Content Source: [sccm/osd/get-started/prepare-windows-pe-peer-cache-to-reduce-wan-traffic.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/get-started/prepare-windows-pe-peer-cache-to-reduce-wan-traffic.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ajp999 for the feedback. I need to set aside some time to do a thorough review of this article.

**Comment by aczechowski** [comment]
I'm resolving this issue in part because we moved repositories, but also because I'm going to track this work via an internal work item.

(internal reference 2838731)
