### ISSUE TITLE
web server certificate template will not work with SSRS

### ISSUE THREAD

**Issue by yannara** [MicrosoftDocs/SCCMdocs#2098]
If the web cert template is done with supply the request, it will not be compatible with SSRS site binding, when enabling 443 there. It will not pop up at bind selection in SSRS management console. As a workaround, I changed the web template from supply request to getting info from AD, but adding all the CNs and DNS fqdn adresses. Saying that, you should consider covering SSRS compatibility also, because it might sit in the same server as the CM does. I feel this article has a lack now then.

See more info;
https://social.technet.microsoft.com/Forums/en-US/7042c8d2-11f3-4a2a-a913-3051d0e411a6/ssrs-certificate-binding-issue?forum=sqlreportingservices

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c66e3e8a-bd8e-7ae3-aecc-cd9073e2238e
* Version Independent ID: 45572c91-8194-096d-2356-80a9b1b356ef
* Content: [Example PKI certificate deployment - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/network/example-deployment-of-pki-certificates#feedback)
* Content Source: [sccm/core/plan-design/network/example-deployment-of-pki-certificates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/network/example-deployment-of-pki-certificates.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @yannara for the feedback and suggestion. This article is quite old, and we need to decide whether to retire it altogether or invest the time to completely revise it....

**Comment by yannara** [comment]
> Thanks @yannara for the feedback and suggestion. This article is quite old, and we need to decide whether to retire it altogether or invest the time to completely revise it....

It is very important, that now after MBAM requires https MP in 1910 release, that the cert templates required for CM are properly documented and tested with all its components. This new fully integrated MBAM release is forcing us to turning to https only mode.

**Comment by aczechowski** [comment]
I'm resolving this issue in part because we moved repositories, but also because I'm going to track this work via an internal work item.

(internal reference 2841906)
