### ISSUE TITLE
Note: Starting in version 1802, Windows BranchCache is always enabled on deployments. 

### ISSUE THREAD

**Issue by ajp999** [MicrosoftDocs/SCCMdocs#2099]
The note that begins "Starting in version 1802, Windows BranchCache is always enabled on deployments" is confusing considering that directly above it states "Peer cache is a custom solution with no reliance on BranchCache. If you don't enable or use BranchCache, peer cache still works". 
Whilst the content of the note is correct, it does not appear to relate to the use of peer cache which this page discusses. Either the note needs to be removed or its relevance to peer caching explained.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29b8c8d-60fa-4403-29a7-8e7c61b2f638
* Version Independent ID: c7610ca2-5607-d1fe-f629-9d0614a26569
* Content: [Client Peer Cache - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/client-peer-cache)
* Content Source: [sccm/core/plan-design/hierarchy/client-peer-cache.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/client-peer-cache.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ajp999 for the feedback. This article is one I need to invest some time in revising and updating.

**Comment by aczechowski** [comment]
I'm resolving this issue in part because we moved repositories, but also because I'm going to track this work via an internal work item.

(internal reference 2838731)
