### ISSUE TITLE
second query needs correction

### ISSUE THREAD

**Issue by kewljoe** [MicrosoftDocs/SCCMdocs#2100]
Joining compliance settings, status, and discovery views the query did not run as is. Currently in SCCM CB 1906 I had to modify this section: v_CIComplianceStatusDetail.Severity to this: v_CIComplianceStatusDetail.RuleSeverity after that change it ran without errors. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 204a6658-b5b6-28ab-22a4-d9cdf0c5f57f
* Version Independent ID: a92d9aae-ce8c-6531-30c6-fd503a645e86
* Content: [Sample queries for compliance settings - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/develop/core/understand/sqlviews/sample-queries-compliance-settings-configuration-manager#feedback)
* Content Source: [sccm/develop/core/understand/sqlviews/sample-queries-compliance-settings-configuration-manager.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/core/understand/sqlviews/sample-queries-compliance-settings-configuration-manager.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @kewljoe for the feedback

**Comment by aczechowski** [comment]
I submitted a change. This issue will auto close when the change merges. It will go live during our next daily publishing, tomorrow (Wednesday) around 11am Pacific.
