### ISSUE TITLE
troubleshooting steps for online apps missing

### ISSUE THREAD

**Issue by sainirak** [MicrosoftDocs/SCCMdocs#2102]
troubleshooting steps for online apps installation on machines such as download issues with error 0x8024500c 
would be helpful. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79d6d496-a7c2-a414-eccc-f1f3a289882e
* Version Independent ID: 90fd043b-f4f7-8823-e2f1-61c692699bf2
* Content: [Troubleshoot MSfB integration - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/apps/deploy-use/troubleshoot-microsoft-store-for-business-integration#bkmk_fail-symptom4)
* Content Source: [sccm/apps/deploy-use/troubleshoot-microsoft-store-for-business-integration.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/troubleshoot-microsoft-store-for-business-integration.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @sainirak for the feedback

**Comment by aczechowski** [comment]
I checked with our support team, and all of the instances of support cases on this specific error code point to the “Do not connect to any Windows Update Internet locations” GPO blocking WU access

**Comment by sainirak** [comment]
Hi Aaron,

Thank you very much for the quick response. Yes, looks like the issue is with the GPO mentioned.

Regards
Rakesh saini

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
