### ISSUE TITLE
MDT version for Win10 v1909

### ISSUE THREAD

**Issue by say2wc** [MicrosoftDocs/SCCMdocs#2104]
MDT build 8456, as of today 12/31/2019, does not list ADK 1903 as supported. So, what version of MDT and ADK should be used for ConfigMgr 1906 or 1910 to deploy Win10 v1909?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc732ec0-eb14-8da2-7688-dd74a72cdae5
* Version Independent ID: a93682ff-2984-38e0-5a0d-6f77c1c9e5db
* Content: [Support for Windows 10 - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/configs/support-for-windows-10#feedback)
* Content Source: [sccm/core/plan-design/configs/support-for-windows-10.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/support-for-windows-10.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @say2wc, please see this FAQ: https://docs.microsoft.com/configmgr/mdt/release-notes#bkmk_note2
I'm closing this issue, as this article is strictly about ConfigMgr support for Windows 10. For MDT support, see the MDT release notes.
