### ISSUE TITLE
Task Sequence Performance Known issue

### ISSUE THREAD

**Issue by JasonNVSD** [MicrosoftDocs/SCCMdocs#2107]
On the page "Manage task sequences to automate tasks", in the section "Performance improvements for power plans", there is a "[Known issue](https://docs.microsoft.com/en-us/configmgr/osd/deploy-use/manage-task-sequences-to-automate-tasks#known-issue)".  It says you have to create a new deployment when disabling the high performance option.  In my testing, you also have to create new deployments when enabling the option as well.

(admin edit: add metadata for article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f539f30-c33c-80d9-218f-0d58fd5a4378
* Version Independent ID: 6057a43d-2a93-fb32-26dd-5d28ad718a72
* Content: [Manage task sequences - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/osd/deploy-use/manage-task-sequences-to-automate-tasks#bkmk_perf)
* Content Source: [sccm/osd/deploy-use/manage-task-sequences-to-automate-tasks.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/manage-task-sequences-to-automate-tasks.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @JasonNVSD, thanks for filing this. I saw the thread on reddit. Please start with filing a frown in the console. That will file a bug with the engineering team to investigate. Then based upon the outcome of that we can update the docs accordingly. I'm closing this issue for now; we can reopen later if engineering confirms the additional issue.

**Comment by aczechowski** [comment]
Comment from engineering: Documentation of the known issue does not cover all bases. The right wording should say that any change to the new setting will not be effective for the existing deployments of the task sequence.

**Comment by aczechowski** [comment]
I submitted a change. This issue will auto close when that change merges. It will go live during our next daily publishing, tomorrow (Wednesday) around 11am Pacific.
