### ISSUE TITLE
Recovering Site Server from 3rd Party Backup

### ISSUE THREAD

**Issue by bryandam** [MicrosoftDocs/SCCMdocs#2108]
In the 'Recover the site server using an existing backup' section it states: "Use this option when you have a _Configuration Manager_ backup".  I think it's reached the level of tribal knowledge now that you can't just restore the OS from a 3rd party product or a VM snapshot.  Even if that backup contains the SQL database.  If that's truly th ecase it'd be great to have that clarified here.  I'd write it up but I don't know this to be true from personal experience or testing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2bf93f-aa79-ef8a-ee16-c1ed27eb8e13
* Version Independent ID: d64f0463-a1e0-b80b-f16b-39f54dd87154
* Content: [Site recovery - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/servers/manage/recover-sites#recover-the-site-server-using-an-existing-backup)
* Content Source: [sccm/core/servers/manage/recover-sites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/recover-sites.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
I assume it's not something we test, thus don't support. Generally we don't doc what we don't support. @bryandam are you suggesting that we make an explicit comment that it's not supported? Can you clarify your request a bit?

**Comment by bryandam** [comment]
>Generally we don't doc what we don't support
Hmm, fair enough, that probably kills it right there.

A lot of people will take a VM snapshot or otherwise backup the OS before doing things like a ConfigMgr site upgrade on the assumption that they can just roll back if things go wrong.  Tribal knowledge says that won't work and is a one-way ticket to Premier support land.  However, those methods aren't documented here thus they're implicitly not supported.  Which means you can close this.  I have a few small edits I might make.

**Comment by aczechowski** [comment]
Discussed with @mestew, closing
Thanks @bryandam 😄

**Comment by mestew** [comment]
After much debate, we decided to list the backup methods we **do** support for site recovery at the top of the [Backup article](https://docs.microsoft.com/configmgr/core/servers/manage/backup-and-recovery) using a warning box. I suspect the change will go live around 11 AM PST today or tomorrow. =)

**Comment by bryandam** [comment]
Beautiful ... <sniff> ... just beautiful.  Thanks for listening!
