### ISSUE TITLE
Config mgr is now a requirement?

### ISSUE THREAD

**Issue by jackvdbuk** [MicrosoftDocs/SCCMdocs#2112]
in windows analytics, no Config manager was required but now in the new desktop analytics suite, this is a pre-requisite. can people who do not use SCCM still utilize this tool like they could with Windows Analytics?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8d7ece-b19f-1431-a619-e57ce6469c28
* Version Independent ID: 86a3d7a5-695b-d3d9-498c-e6b6e03169f8
* Content: [Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-gb/configmgr/desktop-analytics/overview#feedback)
* Content Source: [sccm/desktop-analytics/overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by BeatrizMS2** [comment]
Yes JacKvdbuk.
Desktop Analytics can only be configured with Configuration Manager.

**Comment by aczechowski** [comment]
Thanks @jackvdbuk for the feedback. As @BeatrizMS2 mentioned, ConfigMgr is a prerequisite for Desktop Analytics. There's a [related FAQ](https://docs.microsoft.com/configmgr/desktop-analytics/faq#bkmk_intune) with a bit more info.
Technically, you could still do some very manual configuration with group policy, which we mention tangentially in the [enroll devices](https://docs.microsoft.com/configmgr/desktop-analytics/enroll-devices#device-enrollment) article. But the real benefit of the integrated solution is to be able to *act* upon the insights using ConfigMgr deployments.
I'm closing this issue as there's nothing actionable for docs at this time.
