### ISSUE TITLE
Service Connection Point

### ISSUE THREAD

**Issue by jhongjr** [MicrosoftDocs/SCCMdocs#2116]
One of the requirements as mentioned in this page says "Don't host the service connection point role on either site server configured for high availability." but the "About Service Connection Point" mentions that it can only be installed at the top tier site of the hierarchy. So if I have a CAS and, how can I implement high availability if I need to have this site system role?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c416209-7476-14b2-a60b-9f3477dc79be
* Version Independent ID: 765534af-f933-c768-0994-fa8d0a5712a0
* Content: [Site server high availability - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/servers/deploy/configure/site-server-high-availability#feedback)
* Content Source: [sccm/core/servers/deploy/configure/site-server-high-availability.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/site-server-high-availability.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @jhongjr, good question. I'm actually working on the About SCP article right now, and highlighting this a bit more by creating a new section specifically for "remote site system requirements". The info is already in the article now, see the bold text, **When the role installs on a computer that is remote from the site server**

Basically, the SCP needs to be a part of the CAS *site*, but it doesn't have to be on the *site server*. Install it on a remote site system server that's not the site server.

I'm closing this issue
