### ISSUE TITLE
Windows Defender features are a prerequisite for EP role

### ISSUE THREAD

**Issue by lwhite91** [MicrosoftDocs/SCCMdocs#2120]
I would suggest we add that Windows Defender features are required to be installed on the server that is hosting the EP role. If these features are not installed on the server, you may see errors in the EPSetup.log - "SCEPInstall.exe returns error 0x8004ff73"

Win10 and Server 2016 have Windows Defender features installed by default, but in a lot of environments 3rd party A/V is used and Windows Defender might be uninstalled or disabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fabbf7d6-dfd9-3e74-e172-3ec2b7a86194
* Version Independent ID: 0d111380-ee31-725f-ed24-33bcf0198a0b
* Content: [Create Endpoint Protection point site system role - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/protect/deploy-use/endpoint-protection-site-role#feedback)
* Content Source: [sccm/protect/deploy-use/endpoint-protection-site-role.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/endpoint-protection-site-role.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by TwoXTwentyOne** [comment]
Excellent, this error was rendering me OCD! Finally resolved...
