### ISSUE TITLE
Update for 1910

### ISSUE THREAD

**Issue by xtcw255** [MicrosoftDocs/SCCMdocs#2122]
Could the page be updated with 1910 version? The computer restart settings don't match anything discussed here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3f43b73-de34-a8b0-13c6-c647724161e0
* Version Independent ID: 39e43e5b-626b-b5b9-67de-f7f7a39950cd
* Content: [Device restart notifications - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/deploy/device-restart-notifications#feedback)
* Content Source: [sccm/core/clients/deploy/device-restart-notifications.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/device-restart-notifications.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @xtcw255 for the feedback. I talked with the PM for the feature, he said "Only the strings on the client settings (we simplified them to be more user-friendly)." We'll work on getting those revisions published.

**Comment by aczechowski** [comment]
Just made a big revision to this, the changes should publish today.
