### ISSUE TITLE
Bad CPU type with ccmsetup on macOS Catalina

### ISSUE THREAD

**Issue by daveribs** [MicrosoftDocs/SCCMdocs#2124]
When trying to run ccmsetup on macOS Catalina, MacBook Pro 16, I get Bad CPU Type in executable error message.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec20e40b-461f-9f32-7b77-d06a415fd487
* Version Independent ID: 608ac70d-0bda-4fc5-081a-c689e24f33cd
* Content: [Deploy Mac clients - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/deploy/deploy-clients-to-macs#feedback)
* Content Source: [sccm/core/clients/deploy/deploy-clients-to-macs.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/deploy-clients-to-macs.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @daveribs, see our [Supported configurations](https://docs.microsoft.com/configmgr/core/plan-design/configs/supported-operating-systems-for-clients-and-devices#mac-computers), version 10.15 is not yet supported. Once the engineering team releases an update to the client for macOS, we'll update the supported configurations to reflect that. I'm closing this issue.
