### ISSUE TITLE
"Apply Driver Package" ...via...DISM...

### ISSUE THREAD

**Issue by andykn** [MicrosoftDocs/SCCMdocs#2125]
The "Apply Driver Package" section of this page should include a description of what the "Install driver package via running DISM with recurse option" option does differently to default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1187d55d-d8b3-ebc8-37e8-8de14807be4e
* Version Independent ID: daff4a99-10ac-b424-f08a-9024407e667a
* Content: [Task sequence steps - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/osd/understand/task-sequence-steps?source=docs#feedback)
* Content Source: [sccm/osd/understand/task-sequence-steps.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/understand/task-sequence-steps.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @andykn for the feedback, I'm not sure why that setting isn't mentioned. 🤔 For more detail about that DISM option, see [Windows 10 DISM Command-Line Options](https://docs.microsoft.com/windows-hardware/manufacture/desktop/deployment-image-servicing-and-management--dism--command-line-options).

**Comment by aczechowski** [comment]
I made some changes for this issue, but in the 2002 current branch content. This issue will automatically close when the edit merges into our release branch, but it won't publish live until that release.
