### ISSUE TITLE
Data charges for Azure Windows Clients

### ISSUE THREAD

**Issue by parabolic123** [MicrosoftDocs/SCCMdocs#2126]
We want to use an Azure CMG to apply Windows updates to 2008, 2012 and 2016 servers in Azure. The question I have is whether the CMG itself acts as a Distribution Point fo storing and clients downloading software updates? If the update content is based in Azure and the clients are in Azure, then presumably there's no data transfer charge?

Please advise.
Thanks
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a99f1b09-f669-e3c8-e9a1-c2594f329e12
* Version Independent ID: b022b0cd-f045-418a-be0e-f15f699f9d35
* Content: [CMG FAQ - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/manage/cmg/cloud-management-gateway-faq#feedback)
* Content Source: [sccm/core/clients/manage/cmg/cloud-management-gateway-faq.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/cloud-management-gateway-faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @parabolic123, we talk about this in the [planning article, Cost section](https://docs.microsoft.com/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway#content-storage):

> - Internet-based clients get Microsoft software update content from Windows Update at no charge. Don't distribute update packages with Microsoft update content to a cloud distribution point, otherwise you may incur storage and data egress costs.
