### ISSUE TITLE
MDT Script ZTILangPacksOnline.wsf bug

### ISSUE THREAD

**Issue by pilgi3** [MicrosoftDocs/SCCMdocs#2131]
I try to install the language pack online in the sccm tasksequence with the MDT step.
But in the log file i see:

> Language Packs can only be installed from within Windows Vista, Windows Server 2008, or later 
> OSes

Please look at the code:
```
If iOSVerMajor < 6  or oEnvironment.Item("OSVersion") = "WinPE" then
			oLogging.CreateEntry "Language Packs can only be installed from within Windows Vista, Windows Server 2008, or later OSes", LogTypeError
			Main = Success
			Exit Function
		End if
```
The script looks at the first number of OSVersion and Windows 10 begins with **1**0.0.xxx .
So 1 < 6 and the language pack get not installed.
Could this be fixed with the next MDT release, please?

**Comment by aczechowski** [comment]
Thanks @pilgi3 for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [MDT forum](https://social.technet.microsoft.com/Forums/en-us/home?forum=mdt). It's moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by pilgi3** [comment]
Thanks for the reply and sorry for the circumstances!
