### ISSUE TITLE
Missing content about 'Update distribution point on schedule'

### ISSUE THREAD

**Issue by andydhollander** [MicrosoftDocs/SCCMdocs#2132]
I was looking to find out whether updating the content on a distribution point on a schedule would actually ignore it if the source content did not change, or whether it would redistribute the content regardless of content change. To my surprise I did not find anything related to this option in the "Deploy and Manage Content" section of the docs. 
https://docs.microsoft.com/en-us/configmgr/core/servers/deploy/configure/deploy-and-manage-content

(admin edit: adding metadata for article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 658824b0-308f-88e5-4292-52a34587a111
* Version Independent ID: db08f7ce-3c4b-f7ba-e6f6-e22d00be8757
* Content: [Deploy content - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/servers/deploy/configure/deploy-and-manage-content)
* Content Source: [sccm/core/servers/deploy/configure/deploy-and-manage-content.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/deploy-and-manage-content.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @andydhollander for the feedback. There's really only one mention of the setting **Update distribution points on a schedule** on the **Data source** tab of packages, and that's a brief mention in the article for managing boot images. So definitely something that we could say more about in a general sense.

To answer your question, I checked with an engineer to confirm: if the source doesn't change, then the "update" action doesn't do anything. Only the "distribute" or "redistribute" actions resends everything.

**Comment by aczechowski** [comment]
I made a change for this issue, and totally reviewed this article. The issue will auto close when my change merges. It will go live with the next daily publishing process, which should be on Monday.
