### ISSUE TITLE
Clarify support on client OS

### ISSUE THREAD

**Issue by DeployWindowsCom** [MicrosoftDocs/SCCMdocs#2134]
please clarify requirments for operating system support for Client OS.
LTSB version?
PXE support, specific versions of Windows?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dc0edfd-7799-9246-2e23-f202e31517f9
* Version Independent ID: 8c401426-fcf8-79a9-08fa-95a724b5756d
* Content: [Supported site system servers - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/configs/supported-operating-systems-for-site-system-servers#feedback)
* Content Source: [sccm/core/plan-design/configs/supported-operating-systems-for-site-system-servers.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/supported-operating-systems-for-site-system-servers.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @DeployWindowsCom, can you please provide more information? Did you see this associated articles, [Supported OS versions for clients and devices](https://docs.microsoft.com/configmgr/core/plan-design/configs/supported-operating-systems-for-clients-and-devices) and [Support for Windows 10](https://docs.microsoft.com/configmgr/core/plan-design/configs/support-for-windows-10)? I think those articles cover what you're asking about, but want to clarify before I close this issue.

**Comment by DeployWindowsCom** [comment]
Sorry, I mean for using Windows 10 as a DP, not as a client.
Just looking for clarifying the article about running Windows LTSB as DP with/without PXE.

**Comment by aczechowski** [comment]
Hi @DeployWindowsCom, so specifically the section on [Client OS](https://docs.microsoft.com/configmgr/core/plan-design/configs/supported-operating-systems-for-site-system-servers#bkmk_client). I think the comment to include is probably that we support client as a DP for any supported version of the client OS, with links to the two articles I shared above. So it will depend upon the site version you're using as to which versions of Windows 10 it supports. I think any supported ConfigMgr version supports LTSB/LTSC.

**Comment by aczechowski** [comment]
I submitted a change. This issue will auto close when the change merges. It will go live on the next daily publishing cycle, tomorrow (Wednesday) at 11am Pacific.
