### ISSUE TITLE
Create certificate script missing signs

### ISSUE THREAD

**Issue by MarcusR9170** [MicrosoftDocs/SCCMdocs#2135]
BEGIN
    CREATE MASTER KEY ENCRYPTION BY PASSWORD = MyMasterKeyPassword
END

The password needs to be enclosed like this: 'MyMasterKeyPassword'

(admin edit: add metadata for article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a2f36a3-1dfd-4116-9600-7614df64ce50
* Version Independent ID: 21f250a8-199d-5a4d-1180-c82ee058d1a7
* Content: [Encrypt recovery data - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/protect/deploy-use/bitlocker/encrypt-recovery-data#example-scripts)
* Content Source: [sccm/protect/deploy-use/bitlocker/encrypt-recovery-data.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/bitlocker/encrypt-recovery-data.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @MarcusR9170 for the feedback. I suspect then that all of the password references in the other scripts should be handled the same.

If you'd like to submit this contribution yourself, I'll happily review and publish! 😄 For more information, see [How to contribute to docs](https://docs.microsoft.com/configmgr/core/understand/use-docs#bkmk_contribute).

**Comment by MarcusR9170** [comment]
This is also needed on all the same entries within all provided scripts.

**Comment by aczechowski** [comment]
I submitted a fix. This issue will auto close when the change merges. It should go live with the next daily publishing tomorrow (Wednesday) around 11am Pacific.
