### ISSUE TITLE
distmgr.log for site system role installation

### ISSUE THREAD

**Issue by codaamok** [MicrosoftDocs/SCCMdocs#2136]
distmgr.log also looks helpful info when installing roles such as DP, shows connetion attempts and installation results of components. I'm not sure what wording _should_ be, but would you agree the description for distmgr.log should also include (somehow) a brief summary of that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 972d8899-c8a4-28c5-fabe-5ab294bac22d
* Version Independent ID: 7f772e7a-836c-a18d-df8d-c3d115cb3d9f
* Content: [Log file reference - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/log-files)
* Content Source: [sccm/core/plan-design/hierarchy/log-files.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/log-files.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @codaamok, I think that's probably a good add. I'll want to confirm with engineering. And then need to figure out how best to integrate.

**Comment by PrajwalDesai** [comment]
It can be something like this "Distrmgr.log - Records details about package creation, compression, delta replication, and information updates. It also logs important information when you install or uninstall distribution point role."

**Comment by codaamok** [comment]
IIRC it doesn't just log DP install. It logs attempts to connect to site systems and install result of any role. I think this is what Aaron is double checking with engineering.

**Comment by aczechowski** [comment]
I made a change to include this log file, the change should publish live on Monday
