### ISSUE TITLE
Update Desktop Anaytics Docs page to include note about Azure Government Support

### ISSUE THREAD

**Issue by supportmodern** [MicrosoftDocs/SCCMdocs#2138]
While Desktop Analytics is not technically supported for Azure Government alone, customers can get a CHILD COMMERCIAL azure tenant setup that will support Desktop Analytics. The problem is most people don't know or have knowledge about this who are government customers with Azure Government tenant that need to use Desktop Analytics. As a Dell Technologies field engineer we have to call this out each time and it would be good if Microsoft could add a small note about that on the main DA over view page. What we have seen is once we get onsite or have a kick off call, we ask this question and almost every time so far they only have Azure Government setup, but not the child COMMERCIAL tenant which is needed and thus causes project delays in delivering DA.

Ask:

Is it possible to please update the Desktop Analytics main overview page (linked below) to include a note that customers with Azure Government must setup a COMMERCIAL tenant? Azure Government does NOT support Desktop Analytics.

There are thousands of customers trying to move to cloud and only have Azure Government and this would go a long way to be clear on the requirements for DA to properly work. 

https://docs.microsoft.com/en-us/configmgr/desktop-analytics/overview

Thanks
Nathan Bridges
https://twitter.com/nathanjbridges

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8d7ece-b19f-1431-a619-e57ce6469c28
* Version Independent ID: 86a3d7a5-695b-d3d9-498c-e6b6e03169f8
* Content: [Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/desktop-analytics/overview#feedback)
* Content Source: [sccm/desktop-analytics/overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @supportmodern 😄 
@iceorbital made a change to the article that will publish tomorrow (Friday) around 11am Pacific. He added the term "global Azure" to the list of prerequisites. This terminology aligns with how Azure refers to non-government. [Reference](https://docs.microsoft.com/azure/azure-government/compare-azure-government-global-azure)
