### ISSUE TITLE
Pull DPs on workstation OSes enable BITS with default settings

### ISSUE THREAD

**Issue by CaptainUnlikely** [MicrosoftDocs/SCCMdocs#2142]
I think it's worth mentioning on this page that if you install a pull DP on a workstation OS, the ConfigMgr client will enable BITS with default settings even if the client settings are set to disable BITS.  This means the pull DP's transfers will be throttled regardless of any other settings.  To override this so the pull DP will, for example, use the max available bandwidth when pulling from a DP configured with LEDBAT, you need to set "Limit the maximum network bandwidth for BITS background transfers" to Disabled in GPO.

This is mentioned in a couple of forum threads e.g. https://social.technet.microsoft.com/Forums/lync/en-US/03494089-23ed-419f-936f-a05e37c73c62/configuring-bits-throttling-on-sccm-clients-is-disabled-but-registry-values-change-back-after?forum=ConfigMgrCBGeneral but I don't see this called out in any official documentation, confirmed today this is still the case on ConfigMgr 1902 and Windows 10 1809.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4055a018-68cf-1d48-df84-ea3d7f994f75
* Version Independent ID: 172470eb-4528-cab4-8ebe-dae2ed006523
* Content: [Pull-distribution point - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/use-a-pull-distribution-point)
* Content Source: [sccm/core/plan-design/hierarchy/use-a-pull-distribution-point.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/use-a-pull-distribution-point.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @CaptainUnlikely for the feedback

**Comment by aczechowski** [comment]
Thanks again for the feedback. I made a change to add a note for this feedback. This issue will auto close when my change merges. The changes will go live with the next daily publishing process.
