### ISSUE TITLE
Sandbox

### ISSUE THREAD

**Issue by Chest1** [MicrosoftDocs/SCCMdocs#2145]
Learning

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2c46e8f-8596-dcf2-7d50-a20574bc0c90
* Version Independent ID: 03fbeb63-bdb7-47ba-4f28-c8b69bcd2abb
* Content: [Schema extensions - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/network/schema-extensions#feedback)
* Content Source: [sccm/core/plan-design/network/schema-extensions.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/network/schema-extensions.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Closing test issue
