### ISSUE TITLE
CMG Requirements

### ISSUE THREAD

**Issue by albozadz** [MicrosoftDocs/SCCMdocs#2146]
https://docs.microsoft.com/en-us/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway#requirements 

An extract from the article which requires amendments:

"An Azure administrator needs to participate in the initial creation of certain components, depending upon your design. This persona doesn't require permissions in Configuration Manager." - this statement is confusing, as the user who starts Create Cloud Management Gateway wizard needs to be MECM admin.

(admin edit: adding metadata for article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778368d0-1054-678c-4d74-5dce1b5826c8
* Version Independent ID: aaac7308-66e6-66f0-8248-14e1505c11a6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway#requirements)
* Content Source: [sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @albozadz for the feedback. You're right, we don't mention the ConfigMgr role/permissions that are required to create the CMG. The bullet you mention is purely stating that you can have two separate people involved in the process: a CM admin and an Azure admin. The same person doesn't have to have both security roles.

**Comment by aczechowski** [comment]
I just submitted a change. Once the pull request merges, this issue will automatically close. The change is in our 2002 release branch, so it won't be live until that publishes, which should be *soon* 😉
