### ISSUE TITLE
Deploy Microsoft Edge, version 77 and later

### ISSUE THREAD

**Issue by svschmit** [MicrosoftDocs/SCCMdocs#2147]
Please change the sentence: Admins can pick the Beta or Dev channel, along with a version of the Microsoft Edge client to deploy.   to Admins can pick the Beta,Dev or Stable channel, along with a version of the Microsoft Edge client to deploy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a304313-63b1-3904-c38d-20bdcc04c0c2
* Version Independent ID: bff30820-5e3f-3536-9c06-717ed5438457
* Content: [What's new in version 1910 - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/changes/whats-new-in-version-1910#feedback)
* Content Source: [sccm/core/plan-design/changes/whats-new-in-version-1910.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/changes/whats-new-in-version-1910.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @svschmit for the feedback, we'll revise this.

**Comment by mestew** [comment]
Change made. Should be updated a little later today. Thanks @svschmit for noticing this!
