### ISSUE TITLE
Edge vs Edge Chromium

### ISSUE THREAD

**Issue by monkeyskullfire** [MicrosoftDocs/SCCMdocs#2149]
This page doesn't clarify whether this feature works with Edge, the new Chromium-based Edge, or both.  Initial testing reveals it only works with "legacy" Edge.  The documentation should be updated to reflect which product this feature supports and whether the new Chromium-based Edge will eventually work with this feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ee3d814-4441-b1b2-3e06-72e348b8ed84
* Version Independent ID: c3dbfe0f-d6ea-7357-7632-e5c609530bd6
* Content: [Configure Microsoft Edge settings - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/compliance/deploy-use/browser-profiles)
* Content Source: [sccm/compliance/deploy-use/browser-profiles.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/compliance/deploy-use/browser-profiles.md)
* Product: **configuration-manager**
* Technology: **configmgr-compliance**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @monkeyskullfire for the feedback. These settings only apply to the older version of Edge.

**Comment by CMACKINTOSH75** [comment]
Is it possible to add details about what exactly is set on the client when this policy gets applied, we have found so far that when edge is set as default browser on the client using this policy, if you try to remove the policy, the client is still being forced to use Edge and the users cant go back to setting their own browser, whats settinsg are being stamped on the device

**Comment by aczechowski** [comment]
I'm working on revisions to this article to clarify that it only applies to Microsoft Edge Legacy (version 45 and earlier). I'll include some links to other content for the newer Microsoft Edge version 77 and later. The changes should publish later this week.

@CMACKINTOSH75, ConfigMgr is using the Windows CSP to configure the settings. All of the policy settings have links through the specific Windows CSP documentation for more information.
