### ISSUE TITLE
Documentation for Deployment via WSUS?

### ISSUE THREAD

**Issue by jeff-bb** [MicrosoftDocs/SCCMdocs#2150]
I realize this is the SCCM page, but feedback can't be left for the parent document of "Deploy Microsoft Edge".

I've used the part of these directions that applies to WSUS; it shows up in the WSUS console and I've approved it for install, but devices are not installing it. The SCCM steps show that it installs the MSI via a Powershell command that specifies the channel to use during the install, but this is entirely optional and installs via MSI work fine (and use channel data from the defined MS Update Edge GPOs).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7bd107-2a52-dcac-92a9-3b756a84114a
* Version Independent ID: 024860de-ea76-6bf5-06ad-0cc08d1a7949
* Content: [Deploy and update Microsoft Edge, version 77 and later - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/apps/deploy-use/deploy-edge?toc=https://docs.microsoft.com/DeployEdge/toc.json&bc=https://docs.microsoft.com/DeployEdge/breadcrumb/toc.json)
* Content Source: [sccm/apps/deploy-use/deploy-edge.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/deploy-edge.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @jeff-bb, sorry that you're having issues. I suggest that you file feedback for the Edge doc team directly, using one of their articles. For example, the [Edge deployment FAQ](https://docs.microsoft.com/DeployEdge/faqs-edge-in-the-enterprise)

I'm closing this issue because there's nothing actionable for the ConfigMgr doc team.

**Comment by andyzei** [comment]
Hey @jeff-bb -- the WSUS updates aren't deployable by themselves -- they will only be offered to clients that have the respective channel installed (they're just updates).
