### ISSUE TITLE
MSI and ADMX downloads delivered non-encrypted

### ISSUE THREAD

**Issue by Conan1989** [MicrosoftDocs/SCCMdocs#2152]
Download pages
https://www.microsoft.com/en-us/edge/business/download

non-encrypted connections, should be HTTPS
http://dl.delivery.mp.microsoft.com/filestreamingservice/files/07367ab9-ceee-4409-a22f-c50d77a8ae06/MicrosoftEdgeEnterpriseX64.msi

http://dl.delivery.mp.microsoft.com/filestreamingservice/files/939b9f9b-a6f7-4ccd-908c-ac50b46a9af0/MicrosoftEdgePolicyTemplates.cab

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b7bd107-2a52-dcac-92a9-3b756a84114a
* Version Independent ID: 024860de-ea76-6bf5-06ad-0cc08d1a7949
* Content: [Deploy and update Microsoft Edge, version 77 and later - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/apps/deploy-use/deploy-edge)
* Content Source: [sccm/apps/deploy-use/deploy-edge.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/deploy-edge.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @Conan1989, this feedback mechanism is for Configuration Manager docs, specifically how to use Configuration Manager to deploy Edge v77+. To share feedback on Edge itself, see [Send feedback to Microsoft with the Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). I'm closing this issue as there's nothing actionable for ConfigMgr docs.
