### ISSUE TITLE
Software Updates Client Setting needs more description

### ISSUE THREAD

**Issue by MaxSCCM** [MicrosoftDocs/SCCMdocs#2154]
There is a setting "Enable installation of software updates in "All deployments" maintenance window when "Software Update" maintenance window is available" which is appeared in 1810. It is not clear how client will behave when the setting is set to "No" and there is no "Software Update" MW available for client. Will client install software updates if client has only "All deployments" MW available?

(admin edit: add metadata for article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f74f4a-560f-2510-1ae8-fd3976a2197e
* Version Independent ID: 0851f834-e9a1-d0a6-ee60-934bcd3a79fe
* Content: [Client settings - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/deploy/about-client-settings#bkmk_SUMMaint)
* Content Source: [sccm/core/clients/deploy/about-client-settings.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/about-client-settings.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @MaxSCCM for the feedback. We'll check with the engineering team on the behavior.

**Comment by aczechowski** [comment]
The default value of this setting is "No" which means it uses the same behavior as before: if both types exist, the window is ignored. (This is the behavior going back to ConfigMgr 2012.)

And if the client has only "All deployments" MW available, it still installs software updates in that window.

**Comment by aczechowski** [comment]
I submitted a change. This issue will auto close when the change merges. It will go live during the next daily publishing cycle, tomorrow (Wednesday) around 11am Pacific.
