### ISSUE TITLE
ccmsqlce.log is not documented

### ISSUE THREAD

**Issue by LucasArona** [MicrosoftDocs/SCCMdocs#2155]
ccmsqlce.log is not in this documentation. Can you add it and provide a description ?
Thanks,
Best regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 972d8899-c8a4-28c5-fabe-5ab294bac22d
* Version Independent ID: 7f772e7a-836c-a18d-df8d-c3d115cb3d9f
* Content: [Log file reference - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/log-files#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/log-files.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/log-files.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @LucasArona for the feedback. You're right, I see it on my device, but there's zero mention of it in any of our docs even beyond this article. I'm checking with engineering on a simple one liner to describe it for this article.

**Comment by ChadSimmons** [comment]
This is helpful, but an official description would be great.  https://social.technet.microsoft.com/forums/en-US/639da674-83bc-467b-b4b8-d90db4650faf/ccmsqlcelog-what-is-this-log-file

**Comment by aczechowski** [comment]
I made a change to include this log file, the change should publish live on Monday
