### ISSUE TITLE
Contact Microsoft Support to obtain the license key

### ISSUE THREAD

**Issue by Blacksuit07** [MicrosoftDocs/SCCMdocs#2158]
Under the FAQ: I have purchased EMS or Microsoft 365 through a Cloud Solution Provider (CSP), do I have rights to use Configuration Manager? Is there a certain number or email address to contact? I called MS Support at 1 (800) 642-7676 and was transferred 4 times even though I repeated the answer word for word. They were clueless even after I informed them to reference article ID 4033838. Oops...I just got transferred for the 5th time as I am writing this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3b9a7fa-9585-a2fb-590e-0b74e128035d
* Version Independent ID: 9aae8e97-de68-c274-b4c6-cd925568c75b
* Content: [Product and licensing FAQ - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/understand/product-and-licensing-faq#feedback)
* Content Source: [sccm/core/understand/product-and-licensing-faq.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/product-and-licensing-faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by Blacksuit07** [comment]
Apparently no one knows how to access their Internal Article database. Still have not been able to get this resolved.

**Comment by Blacksuit07** [comment]
So after 7 transfers and 3 disconnects I was told that since I am not a CSP they would not assist me with getting a license key and go through my CSP...makes zero sense.

**Comment by aczechowski** [comment]
Hi @Blacksuit07, I'm sorry for the frustrating experience. It's unfortunately not the first time I've heard of this either. 😞 I'm checking with some colleagues in support on what we can do to improve the process.

**Comment by winmasterxp** [comment]
Hi @aczechowki, any update on this? I've been trying to several months to obtain the key for SCCM and the SQL instance to run it on. I've opened tickets with MS & my CSP provider (CDW). No one has been able to figure it out. I've reference the internal ticket number on my ticket with MS, but it must not make sense to people because they kept bouncing me around until they just "closed" the ticket.

**Comment by aczechowski** [comment]
I'm appalled that folks in our support org don't know how to access an internal support article. I'm sorry for that experience. 

Well, let's just rely upon proper authentication and authorization to control access. Here's the explicit URL with the step by step instructions: https://internal.support.services.microsoft.com/help/4033838. You *shouldn't* be able to access that, but the support folks you speak with should. If not, they need to escalate the case to someone who can.

**Comment by Blacksuit07** [comment]
I know the feeling. I opened a ticket with my CSP (PCM/Insight) and MS Support has been ignoring their emails.

**Comment by winmasterxp** [comment]
Opened a new case with MS today and referenced the direct link. Will post back with what happens.

**Comment by Blacksuit07** [comment]
Good luck to you my friend. My ticket was opened by my CSP around the 29th. Still no reply from MS Support. I am starting to get stern in my replies because enough is enough already.

**Comment by Blacksuit07** [comment]
This has become comical at best. Here is a response I got back from MS Support.

> Hello All,

Based on the information that I was given, it sounds like this is a licensing issue and not a technical issue. Unfortunately, Premier Support is unable to provide answers to licensing questions. When licensing questions come up, we refer the customer/ partner to the reseller they wish to purchase their licensing from. I do believe PCM has a licensing division you may be able to reach out to.

Please let me know if you have any questions, or if I can do anything else to assist.

Thanks,
Ed

**Comment by aczechowski** [comment]
Can you share a case ID please?

**Comment by Blacksuit07** [comment]
Sure, thanks for any help you can provide.

Ticket #:18481910

**Comment by winmasterxp** [comment]
Hello aczehowsi,
I don't have Premier support, but here are my case IDs
17688031 (Original ticket opened via 365 portal at the end of November)
1911280040001733 (Opened by support after several back and forth emails with different folks)
18565842 (Opened yesterday)

**Comment by simps100** [comment]
Let us know how you get on.. I raised a ticket in 365 support yesterday who say they cant help me and redirected me to the partner portal aka.ms/rsc which I've no access to create a support ticket in.. have asked if they can re-direct my ticket for me will see where I get!

**Comment by rvtdadmin** [comment]
We have contacted Intune support through the Endpoint Management admin console.
Talking to the support agent they are going to transfer it to "Billing" and it may take some time for someone to get back to us.
Case Number: Ticket #:18571781
Intune Technician:

Nitin Singh

Support Engineer
Microsoft Intune
Enterprise Platform Support
Microsoft Services

+1-425-704-3638 Extn: 2265915NOAM Region
v-nits@microsoft.com
Working Hours: Mon-Fri 9:00 AM – 6:30 PM, CDT 

Thank you!

**Comment by Blacksuit07** [comment]
Thank you for your help on this.

**Comment by aczechowski** [comment]
Thanks for sharing the case IDs (no need for the other contact info, so I removed them). I'm working with some folks in the support org on how to better educate the folks that are handling these cases. We need to do better. 
I'm also checking on why they're bouncing/forwarded your cases. Trying to piece together the end to end story to find where things are falling down. Let me know if you have any input/insight on that.
For the immediate needs, keep pushing that URL on them. It literally has the instructions that you need. I don't know how to make that more clear.

**Comment by simps100** [comment]
@aczechowski  should O365 support be able to help? They’ve said they can’t I’ve asked if they can re-route and they’ve said they can’t do that either - ticket number is 18581801 - thank you!

**Comment by yin74** [comment]
Same experience from me too!  Bounced around between 365, billing and VLSC teams, with no Microsoft department knowing what to do.  Constant referral back to software partner and no further forward after over a week of support calls.

**Comment by rvtdadmin** [comment]
I was contacted by Microsoft Commercial Billing pretty quickly stating they would contact me within the hour. That was 6 days ago and there was no response when asking for any update. Thanks again for your help.
Ticket #:18571781

**Comment by simps100** [comment]
I eventually got passed from 365 support to “On-prem” support and finally got keys for sql 2017 standard / enterprise and SCCM.

**Comment by winmasterxp** [comment]
I just wanted to post back that it took a week, but the representative assigned to my case was able to get me the license keys I need. (I haven't used them yet, but fingers crossed!)

For those who come across this post in the future seeking help, I opened my ticket via the Admin portal in 365 and provided the internal ticket URL above and also mentioned that they may need to check with the "On Prem" support team.

**Comment by rvtdadmin** [comment]
We also obtained the keys earlier this week. The ticket was with Billing and I added a note asking for it to be assigned to "on-prem". Someone from Configuration Manager and WSUS Team called and provided the keys. We have not used them yet either. Thanks for your help.

**Comment by liquidspikes** [comment]
Hello, 

I stumbled on this page and I am having this same issue, 
Transferred all over the place with no answers.

On the first case #18918438 I was given:

"Hello Alex,

Yes you can refer the article below:

https://internal.support.services.microsoft.com/en-us/help/4033838 

Thanks & Regards,

Vikash Nodiyal
Microsoft O365|Senior Support Engineer | Microsoft 365 Cloud Support "

A page I don't have access to, and the ticket was then closed. (Ugh, seriously?)

I just opened another Case# 19531478 hopefully I will have more luck.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback. Unfortunately I don't have anything new to share here, and there's nothing actionable at this time for us to add to the docs.
