### ISSUE TITLE
More information about how a client picks up changes to configuration.mof

### ISSUE THREAD

**Issue by FISHMANPET** [MicrosoftDocs/SCCMdocs#2159]
The doc here says the configuration.mof file is included with policy and is compiled by policy.  When developing things it can be useful to manually trigger them to know if they're working properly.  I was just working a new hardware class, and pulling machine policy and running Hardware Inventory wasn't enough to trigger the creation of the WMI class, I had to force a full Hardware Inventory (by deleting the InventoryActionStatus in WMI for Hardware inventory) and then my client compiled the new MOF and properly inventoried the new class.

Being impatient I may have also restarted the client a couple of times, triggered other things, etc etc, so I can't be sure my forcing of a full is what actually triggered the recompliation of the Mof.  So it would be good to know how to manually trigger this compilation, and also generally to know how this process happens (where can I see it in the logs?) to be able to monitor and troubleshoot it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54dd8166-9fb1-3027-ad24-6a14c2dd5f3f
* Version Independent ID: 02c01bf8-020c-b29a-ab8f-1541c83743b5
* Content: [Extend hardware inventory - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/manage/inventory/extend-hardware-inventory)
* Content Source: [sccm/core/clients/manage/inventory/extend-hardware-inventory.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/inventory/extend-hardware-inventory.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @FISHMANPET for the feedback

**Comment by aczechowski** [comment]
Thanks again for the feedback. We moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
