### ISSUE TITLE
DP status messages

### ISSUE THREAD

**Issue by tyddaj** [MicrosoftDocs/SCCMdocs#2163]
I've got DPs with an error messages from March 2017, referencing a package that no longer exists. This is making all the DPs show a yellow alert triangle, so I can't their status without actually drilling into the details tab.
Which logs does the DP status reference, and how do I remove these old package errors from them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa3758ca-9881-acba-c961-a8d60ecdda0b
* Version Independent ID: 407f4d69-c003-6de6-4376-dd629171bc57
* Content: [Monitor content - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/servers/deploy/configure/monitor-content-you-have-distributed#feedback)
* Content Source: [sccm/core/servers/deploy/configure/monitor-content-you-have-distributed.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/monitor-content-you-have-distributed.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @tyddaj for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
