### ISSUE TITLE
Compliant attribute is 2

### ISSUE THREAD

**Issue by fmokren** [MicrosoftDocs/SCCMdocs#2165]
What is the meaning if the "ReasonsForNonCompliance" is empty or null and the Compliant attribute is 2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dc22577-ebee-2785-aa2e-5e00ac6388ea
* Version Independent ID: 2669ae36-6077-39ba-9140-bc264df7cf9d
* Content: [Non-compliance codes - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/protect/tech-ref/bitlocker/non-compliance-codes)
* Content Source: [sccm/protect/tech-ref/bitlocker/non-compliance-codes.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/tech-ref/bitlocker/non-compliance-codes.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Discussed offline, no changes necessary.
