### ISSUE TITLE
References for Latest Hotfixes Missing

### ISSUE THREAD

**Issue by mitlyng** [MicrosoftDocs/SCCMdocs#2167]
KB4535819
https://support.microsoft.com/en-us/help/4535819/update-for-microsoft-endpoint-configuration-manager-version-1910-early

KB4538488
https://support.microsoft.com/en-us/help/4538488/clients-immediately-upgrade-after-updating-to-configuration-manager-cu

KB4538166
https://support.microsoft.com/en-us/help/4538166/client-update-for-configuration-manager-current-branch-version-1910

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a304313-63b1-3904-c38d-20bdcc04c0c2
* Version Independent ID: bff30820-5e3f-3536-9c06-717ed5438457
* Content: [What's new in version 1910 - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/changes/whats-new-in-version-1910)
* Content Source: [sccm/core/plan-design/changes/whats-new-in-version-1910.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/changes/whats-new-in-version-1910.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @mitlyng for the feedback. We'll try to improve our process to get the hotfixes added in a more timely manner. With the recent release of the hotfix rollup update, it supercedes the previously available hotfixes. A change is in to add a note for the hotfix rollup, which should publish live later today. I'm closing this issue.
