### ISSUE TITLE
Incomplete document

### ISSUE THREAD

**Issue by JohnNelsonNmbr2** [MicrosoftDocs/SCCMdocs#2170]
The first sentence of this page kind of ends without explaining exactly what this does

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24d2c785-1d06-2e7b-e47e-721bb26357a1
* Version Independent ID: cbb80938-737e-aea0-981f-6df5ffa773b9
* Content: [DetermineIfRebootPending Method - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/develop/reference/core/clients/sdk/determineifrebootpending-method-in-class-ccm_clientutilities)
* Content Source: [sccm/develop/reference/core/clients/sdk/determineifrebootpending-method-in-class-ccm_clientutilities.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/core/clients/sdk/determineifrebootpending-method-in-class-ccm_clientutilities.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Wow, thanks @JohnNelsonNmbr2 for finding this and sharing the feedback. Unfortunately, I just did a search for `…` in the repo markdown, and there are a *lot* of other instances. 😢 We have a large backlog of work for the PowerShell and SDK content, along with all of the other content we manage and maintain. So I'll keep this open for now, but can't say when we might be able to fix these.

**Comment by aczechowski** [comment]
I made some changes to address this issue. I'm not proud of them, but best I can offer right now. The fancy ellipsis no longer exists across the ConfigMgr content library

**Comment by JohnNelsonNmbr2** [comment]
:) 

![image](https://user-images.githubusercontent.com/56777272/80266322-ca76ff00-8660-11ea-8b3e-fb40ee6e0abc.png)
