### ISSUE TITLE
Intune/Co-Management required?

### ISSUE THREAD

**Issue by SoMuchMedia** [MicrosoftDocs/SCCMdocs#2171]
I do not see Intune listed as a requirement.  Is it?  What I have heard "Its my understanding that Desktop Analytics will not work until the target Windows 10 machines are co-managed with Intune.  "  Is this is true, can we add it to this article?  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8d7ece-b19f-1431-a619-e57ce6469c28
* Version Independent ID: 86a3d7a5-695b-d3d9-498c-e6b6e03169f8
* Content: [Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/desktop-analytics/overview#feedback)
* Content Source: [sccm/desktop-analytics/overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @SoMuchMedia, nope, neither Intune or co-management are requirements for Desktop Analytics. I'm closing this issue.
