### ISSUE TITLE
Step 4 needs both global admin and subscription owner rights

### ISSUE THREAD

**Issue by KenHoover** [MicrosoftDocs/SCCMdocs#2172]
Step 4 needs a "Note" box which indicates that the person executing this step needs to be a global admin for the AzureAD space and ALSO the owner of at least one Azure subscription since this step creates permissions in both spaces.  Ref: ticket #18415127

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd47a59b-8033-9e94-6f54-0ac1b6c9007e
* Version Independent ID: d26141cd-e979-607b-f7db-57c762b329e4
* Content: [Set up Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/desktop-analytics/set-up#feedback)
* Content Source: [sccm/desktop-analytics/set-up.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/set-up.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I checked with our PM team, and we think this requirement is stated in the prereqs already. The tutorial article has a note to remind this, so I copied that over to this article. The issue will auto close when the pull request merges, and then the change should publish tomorrow morning. 
Thanks @KenHoover for the feedback!
