### ISSUE TITLE
Implications of Modern Standby on SCCM Power Management

### ISSUE THREAD

**Issue by jrosser1221** [MicrosoftDocs/SCCMdocs#2177]
It appears based on logging that systems enabled for Modern Standby (Sleep State S0) are not able to be managed by power plans in SCCM. The PwrProvider.log reports this message:

The "Required idleness to sleep" setting (&lt;GUID&gt;) is not supported on this operating system.  This setting will be ignored.

It may be helpful to add a note here regarding Modern Standby and the SCCM client's relation to this sleep state.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fd918fb-7d8a-cc92-f8d9-339c2db98cb1
* Version Independent ID: 9cb416d9-1927-eb95-4e3f-ef9f9684b14b
* Content: [Create and apply power plans - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/manage/power/create-and-apply-power-plans#feedback)
* Content Source: [sccm/core/clients/manage/power/create-and-apply-power-plans.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/power/create-and-apply-power-plans.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback. I made a change to add a note for this. The issue will auto close when my change merges. It will then go live with the next daily publishing cycle.
