### ISSUE TITLE
New dynamic download support for Task Sequences with 1910

### ISSUE THREAD

**Issue by Leon1983** [MicrosoftDocs/SCCMdocs#2180]
Under the heading "Support for Configuration Manager features" This page still states "Task sequences that aren't using boot images and are deployed with an option: Download all content locally before starting task sequence" This is no longer required as of 1910 and should be highlighted https://docs.microsoft.com/en-us/configmgr/core/plan-design/changes/whats-new-in-version-1910#task-sequence-download-on-demand-over-the-internet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778368d0-1054-678c-4d74-5dce1b5826c8
* Version Independent ID: aaac7308-66e6-66f0-8248-14e1505c11a6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway#support-for-configuration-manager-features)
* Content Source: [sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Leon1983 for catching that.

**Comment by aczechowski** [comment]
@PanuSaukko made a change in #2219 for this issue, so I'm closing it.
