### ISSUE TITLE
Markdown file for TP 2001.2 is missing?

### ISSUE THREAD

**Issue by tstolswo** [MicrosoftDocs/SCCMdocs#2181]
I am unable to edit the page; https://docs.microsoft.com/en-us/configmgr/core/get-started/2020/technical-preview-2001-2, it 404's when I make an attempt.

https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/core/get-started/2020/technical-preview-2001-2.md

**Comment by aczechowski** [comment]
Hi @tstolswo 
The markdown file is there now, so I'm closing this issue.

FYI, we have two repositories: sccmdocs (public) and sccmdocs-pr (private). Publishing to docs.microsoft.com happens from the private repo. There's a (usual) daily sync between the public and private repos, to publish contributions from the community, and make the published content available to the community for editing. So after we publish for a release, it can take up to 24 hours before the markdown is sync'd to the public repo for editing. The sync usually happens by 11:00 AM Pacific time.
