### ISSUE TITLE
blog links moved

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#2182]
The five links at the bottom of the page to the series of blogs from Microsoft Support are no longer valid. They are now at the following URLs:
- ConfigMgr 2012 Data Replication Service (DRS) Unleashed - https://techcommunity.microsoft.com/t5/configuration-manager-archive/configmgr-2012-data-replication-service-drs-unleashed/ba-p/339916
- ConfigMgr 2012 DRS – Troubleshooting FAQs - https://techcommunity.microsoft.com/t5/configuration-manager-archive/configmgr-2012-drs-troubleshooting-faqs/ba-p/339934
- ConfigMgr 2012 DRS Initialization Internals - https://techcommunity.microsoft.com/t5/configuration-manager-archive/configmgr-2012-drs-initialization-internals/ba-p/339948
- ConfigMgr 2012: DRS and SQL service broker certificate issues - https://techcommunity.microsoft.com/t5/configuration-manager-archive/configmgr-2012-drs-and-sql-service-broker-certificate-issues/ba-p/339910

The **ConfigMgr DRS Synchronization Internals** post is in progress to move to the same location

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66942850-8515-4767-ae2f-0678536dcfcd
* Version Independent ID: 109df485-0281-1118-5e83-aa14666b6280
* Content: [Troubleshoot SQL replication - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/servers/manage/replication/overview)
* Content Source: [sccm/core/servers/manage/replication/overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/replication/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Most of these were just fixed today with MicrosoftDocs/SCCMDocs-pr#4931, except the first one.

**Comment by umair0204** [comment]
ConfigMgr DRS Synchronization Internals -
https://techcommunity.microsoft.com/t5/configuration-manager-archive/configmgr-drs-synchronization-internals/ba-p/1154317
