### ISSUE TITLE
Decription of two parameters need update

### ISSUE THREAD

**Issue by MarcusR9170** [MicrosoftDocs/SCCMdocs#2183]
Hi all,
the parameter -SqlInstanceName is mentioned not to be used in case the instance is the default for SQL.
I would like to have the "Don't use..." changed into "... must not be used ..." as the the script fails in case of default instancename.
Or in addition to what is written there:  "Don't ..... or the script will fail"
But best would be that the script checks within if the given parameter is the default instance name and would ignore it in combination with the message that it is ignored due to this reason

The parameter "IISWebSite" is mentioned to be used without - ???
From my tests it seems necessary to be used like this "-IISWebSite"
In addition i would like to have the info added here that the target from the parameter -IISWebsite needs to in front of the script is being executed as the script does not create the website on its own..

Thx
Marcus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef6976b2-abf4-87b4-9d94-3098c2636654
* Version Independent ID: 966bc208-38c1-3527-6196-7ef5fbfa817d
* Content: [Set up BitLocker portals - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/protect/deploy-use/bitlocker/setup-websites#feedback)
* Content Source: [sccm/protect/deploy-use/bitlocker/setup-websites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/bitlocker/setup-websites.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @MarcusR9170, thanks for the feedback.

1. With Microsoft Style we generally try to avoid such strong language. As reference, see the style guide for [should vs. must](https://docs.microsoft.com/style-guide/a-z-word-list-term-collections/s/should-vs-must) and [Verbs](https://docs.microsoft.com/style-guide/grammar/verbs).
2. I'll check with the engineering team to confirm the usage of that parameter.

**Comment by MarcusR9170** [comment]
Hi Aaron,

Thx for letting m know about “style guide” Was not aware about having something like this.

So what about adding the info that the script will fail in case of using the parameter with default information (if we can not change the script to avoid this at all)?

Thx
Marcus

**Comment by aczechowski** [comment]
Hi @MarcusR9170, I suggest filing a frown from the ConfigMgr console to suggest a change to the script. I'm still trying to get an answer to the other parameter question.

**Comment by aczechowski** [comment]
I confirmed, dash is required in all parameters. I'm also going to add a note that you need to pre-create a custom website.

**Comment by aczechowski** [comment]
I submitted a change for this, but as part of the version 2002 current branch content, which won't publish for another few weeks. So you'll see this issue close soon when my changes merge into our release branch. But it won't be live until version 2002 early update ring release.
