### ISSUE TITLE
SCCM Remote Control - view only 1 of 2 monitors

### ISSUE THREAD

**Issue by timuze** [MicrosoftDocs/SCCMdocs#2185]
We are running System Center 2012 R2 Configuration Manager Remote Control version 5.00.7958.1000
When trying to remote into a desktop with two monitor (single dual adaptor) we are only seeing the left side monitor. We manage 450 different type of desktops and so far the issue appears to be arbitrary. All desktops are Windows 10.
Have been using SCCM remote for last 8 years and never saw this.
Any ideas?

**Comment by aczechowski** [comment]
Hi @timuze, 
Thanks for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.

FYI, Configuration Manager current branch version 1902 has improved support for this scenario. For more information, see [What's new in version 1902](https://docs.microsoft.com/configmgr/core/plan-design/changes/whats-new-in-version-1902#view-first-screen-only-during-remote-control).
