### ISSUE TITLE
Can a commercial ID be used on more than one Desktop Analytics portal?

### ISSUE THREAD

**Issue by rasldasl** [MicrosoftDocs/SCCMdocs#2188]
We have production Windows Analytics with an existing commercial ID (not yet connected to SCCM). Before migrating and connecting we want to test with our development/lab SCCM environment. Does this require a new commercial ID? Or can we use the same ID for both? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ec6aa6e-5695-4efa-c781-0554c112518c
* Version Independent ID: 6d588337-349a-2ae7-c5cc-8e53adf2d9d5
* Content: [FAQ for Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/desktop-analytics/faq#feedback)
* Content Source: [sccm/desktop-analytics/faq.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @rasldasl, good question. I'm checking

**Comment by aczechowski** [comment]
You can use the same Commercial ID for both. They will show up in the same DA workspace.

**Comment by aczechowski** [comment]
I'm closing this issue, as it's already captured in the [prerequisites](https://docs.microsoft.com/en-us/mem/configmgr/desktop-analytics/overview#prerequisites)
