### ISSUE TITLE
Enabling comanagement on mobile devices. 

### ISSUE THREAD

**Issue by shaq007** [MicrosoftDocs/SCCMdocs#2191]
I have noticed a note "Windows 10 mobile devices don't support co-management" Can you please verify laptops are also included  as mobile devices? We have an http enabled SCCM environment and want to implement bitlocker for our laptop devices. So we were considering to use Microsoft Intune for this purpose and enroll the laptops in comanagement to start encrypting our devices using intune features. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f24ae716-bf27-7d45-cb15-0bc6eea64374
* Version Independent ID: f444ef64-9b7d-999f-3fb3-6ac6cda3ef88
* Content: [Co-management for Windows 10 devices - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/comanage/overview#feedback)
* Content Source: [sccm/comanage/overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @shaq007, that's referring to devices that are running some blend of a Windows 10 mobile OS which doesn't support the ConfigMgr client. You can enroll those devices with Intune or ConfigMgr on-prem MDM, but no co-management.
If your laptops are running a [supported edition of Windows 10](https://docs.microsoft.com/configmgr/core/plan-design/configs/support-for-windows-10#bkmk_win10-notes), then they are supported for co-management.
