### ISSUE TITLE
Boot image Selection - Deployment ID

### ISSUE THREAD

**Issue by Li-xianhua** [MicrosoftDocs/SCCMdocs#2192]
If it finds more than one boot image, it uses the highest or most recent deployment ID. ------
Just an advise to clarify that it's task sequence deployment ID... I've spend an hour to find a "boot image deployment ID", I may not the only one stupid😂...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3527c358-cf3f-07ec-1cb8-88982ff99122
* Version Independent ID: 2c618192-bb71-d934-d20e-1ceb15cb2e01
* Content: [Use PXE for OSD over the network - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network#feedback)
* Content Source: [sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
THanks @Li-xianhua, good clarification. I'm submitting a change now. This issue will auto-close when that change is committed. It will then publish live on the next cycle, which should be tomorrow (Wednesday) around 11am Pacific.
