### ISSUE TITLE
unable to find adminconsole.xml

### ISSUE THREAD

**Issue by LucasArona** [MicrosoftDocs/SCCMdocs#2198]
Where can I find "Adminconsole.xml" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00eb3029-9353-aab5-ea7b-7248b59440cd
* Version Independent ID: 90f111b7-c89a-2180-eca6-e29a34831c59
* Content: [Find a Console Node GUID - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/develop/core/servers/console/how-to-find-a-configuration-manager-console-node-guid)
* Content Source: [sccm/develop/core/servers/console/how-to-find-a-configuration-manager-console-node-guid.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/core/servers/console/how-to-find-a-configuration-manager-console-node-guid.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @LucasArona, thanks for sharing this feedback. I think that file is specific to ConfigMgr 2007, so unfortunate that we still have it called out in this article. Fortunately, it's the only one that references it. I just submitted a quick change to remove the reference. This issue will auto close when the change merges. It will be live on our next publishing cycle, which should be tomorrow (Wednesday) around 11am Pacific.
