### ISSUE TITLE
Windows PE Limitations

### ISSUE THREAD

**Issue by PehDeh** [MicrosoftDocs/SCCMdocs#2204]
Hi, 
it would be nice to get a set of Limitations for Windows PE Bootimages like: https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/whats-new-in-windows-pe-s14
Thing is x64bit should support up to 64TB of Memmory. I had 3 Dell PowerEdge 740xd. 2 with 1.5 TB and 1 with 3 TB. None of these was able to boot and threw "Kernel Security Check Failure" bluescreens.
Solution was we removed all Memmory Modules except 1 and then it worked, but it should´ve worked if the specifications were correct.
Please provide (correct) Information for Bootimage Limitations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 371ecfcd-7505-e201-60af-cc59c5de2c85
* Version Independent ID: e3321fbb-b479-9168-31b3-e610f044bd5e
* Content: [Manage boot images - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/osd/get-started/manage-boot-images)
* Content Source: [sccm/osd/get-started/manage-boot-images.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/get-started/manage-boot-images.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @PehDeh, thanks for the feedback. The challenge is that the configuration and changes of Windows PE is a separate product, so we need to be cautious about overstepping our bounds. We unfortunately can't take on the role of documenting all aspects of such dependencies.
I'm closing this issue.
