### ISSUE TITLE
Message Administrator replaced with Start Teams 

### ISSUE THREAD

**Issue by PrajwalDesai** [MicrosoftDocs/SCCMdocs#2206]
Starting with version 1910, I guess Message Administrator option has been replaced with Start Microsoft Teams chat option. Please update the article.

Thanks,
Prajwal Desai

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f81b196-6d86-0a9e-91ac-471f70dafdbb
* Version Independent ID: 20ce3020-2518-9175-4d32-f5ee5b5f2aaa
* Content: [Configuration Manager console - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/servers/manage/admin-console#feedback)
* Content Source: [sccm/core/servers/manage/admin-console.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/admin-console.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @PrajwalDesai for the feedback.

**Comment by mestew** [comment]
This is getting changed. Thanks much @PrajwalDesai
