### ISSUE TITLE
Proxy Requirement

### ISSUE THREAD

**Issue by Shibaruraya** [MicrosoftDocs/SCCMdocs#2208]
hi
This document does not articulate the requirement for internet connectivity. If the infra uses a proxy server for internet access then MCC doesnot work. Hence would be better if the statement under Prerequisites and limitations for internet access states that "MCC is not proxy aware and would not work in environment where internet access is thru proxy server irrespective whether authenticated or unauthenticated"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1fbe6e8-4883-644e-8412-2e69759fe482
* Version Independent ID: 41f3fdea-c476-bd2b-131b-1100bbede7b2
* Content: [Microsoft Connected Cache - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/microsoft-connected-cache#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/microsoft-connected-cache.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/microsoft-connected-cache.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Shibaruraya for the feedback. I'll check on this

**Comment by aczechowski** [comment]
FYI, this functionality is currently not supported, but a fix in progress.

**Comment by Shibaruraya** [comment]
Thank you, do we have any timelines when this would be addressed

**Comment by Shibaruraya** [comment]
hi
Would MCC work on a Pull Distribution Point ?

**Comment by aczechowski** [comment]
I've made changes for this issue that will publish with the 2002 content, which go live soon. 😉 I'm closing this issue.
