### ISSUE TITLE
Remote Control Options has not been covered

### ISSUE THREAD

**Issue by PrajwalDesai** [MicrosoftDocs/SCCMdocs#2210]
I see in this article which is about "**Software Center user guide**" remote control option is not covered. Under Options tab, just after Computer Maintenance option, we have Remote Control option as well. Although an end user cannot change any of the options under Remote Control, but it's good if you cover them.

Thanks,
Prajwal Desai
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67a999a9-9597-9dcf-bd61-c8320b8a1fae
* Version Independent ID: d99205df-c3d9-f101-13fc-bf7988848190
* Content: [Software Center user guide - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/understand/software-center)
* Content Source: [sccm/core/understand/software-center.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/software-center.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @PrajwalDesai for the feedback, agreed.

**Comment by aczechowski** [comment]
Thanks to @jpcast88 for contributing content for this issue, which is why it closed. The changes will publish live tomorrow around 11:00 Pacific time.
