### ISSUE TITLE
Cloud Only Client

### ISSUE THREAD

**Issue by Darren102b** [MicrosoftDocs/SCCMdocs#2212]
Without installing the Config Manager client can pure cloud systems take advantage of using this cache source? the reason why I ask is the document does not show if the config mgr client is really needed for example; if we have boundary groups set up with AD sites and IP ranges, then can a Cloud only system connect and use the Cache as a source?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1fbe6e8-4883-644e-8412-2e69759fe482
* Version Independent ID: 41f3fdea-c476-bd2b-131b-1100bbede7b2
* Content: [Microsoft Connected Cache - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/microsoft-connected-cache#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/microsoft-connected-cache.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/microsoft-connected-cache.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
No, it requires Configuration Manager

I suggest sharing [product feedback](https://docs.microsoft.com/configmgr/core/understand/find-help#product-feedback) to ask the engineering team to consider supporting this scenario
