### ISSUE TITLE
Example under /Config seems to be glitchy

### ISSUE THREAD

**Issue by JohnNelsonNmbr2** [MicrosoftDocs/SCCMdocs#2215]
In the /Config section (https://docs.microsoft.com/en-us/configmgr/core/clients/deploy/about-client-installation-properties#configconfiguration-file) the example doesn't quite look right:

CCMSetup.exe /config:&lt;Configuration File Name.txt\&gt;
should probably read something like
CCMSetup.exe /config:"Configuration File Name.txt"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f14a23d-3ca2-0cc9-8fe2-8e5f21d618c7
* Version Independent ID: c2593fb4-2bb7-c645-e9fe-873dbeda2b45
* Content: [Client installation parameters and properties - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/deploy/about-client-installation-properties#feedback)
* Content Source: [sccm/core/clients/deploy/about-client-installation-properties.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/about-client-installation-properties.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @JohnNelsonNmbr2 for catching that. Yes, some bad markdown formatting there. I submitted a quick edit; once it merges this issue will auto close. The change should publish live later today around 11am Pacific.

p.s. in the future, for a simple change like this, I encourage you to submit the edit yourself! 😉 For more information, see [How to contribute](https://docs.microsoft.com/configmgr/core/understand/use-docs#bkmk_contribute).
