### ISSUE TITLE
Connect-AutopilotIntune no longer exists

### ISSUE THREAD

**Issue by BradleyKarkanen** [MicrosoftDocs/SCCMdocs#2217]
Connect-AutopilotIntune should be changed to Connect-MSGraph as per https://github.com/MicrosoftDocs/windows-itpro-docs/issues/5443

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bed718c9-fa4d-d78e-3be2-fbc390a80406
* Version Independent ID: cd67f1d8-70a9-1a70-4d8f-1a8063aa0857
* Content: [Windows Autopilot for existing devices - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/osd/deploy-use/windows-autopilot-for-existing-devices#feedback)
* Content Source: [sccm/osd/deploy-use/windows-autopilot-for-existing-devices.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/windows-autopilot-for-existing-devices.md)
* Product: **configuration-manager**
* Technology: **configmgr-osd**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @BradleyKarkanen, already tracking the issue with #2031
