### ISSUE TITLE
ADALOperationProvider.log

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/SCCMdocs#2218]
Hi, for the client log files I can't see a description of ADALOperationProvider.log on this page.  I can see it here though https://docs.microsoft.com/en-us/configmgr/core/clients/manage/azure-ccmsetup

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 972d8899-c8a4-28c5-fabe-5ab294bac22d
* Version Independent ID: 7f772e7a-836c-a18d-df8d-c3d115cb3d9f
* Content: [Log file reference - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/hierarchy/log-files)
* Content Source: [sccm/core/plan-design/hierarchy/log-files.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/log-files.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @nhogarth86 for the feedback. I need to get all feature teams to review this article and provide input on missing pieces.

**Comment by aczechowski** [comment]
I made a change to include this log file, the change should publish live on Monday
