### ISSUE TITLE
Misleading permissions requirements

### ISSUE THREAD

**Issue by NickolajA** [MicrosoftDocs/SCCMdocs#2224]
Hi, it states in the docs that you need Owner, Contributor set on the Resource Group where the Log Analytics workspace resides together with the Azure AD role called Desktop Analytics Administrator. The part regarding the Resource Group is incorrect, as you need to add the permissions on the actual Log Analytics workspace, even though it might be inherited down, it should reflect the actual configuration done by the onboarding setup where the M365 Analytics Client Admins (Log Analytics [Contributor,Owner]) groups are configured.

This is the part that's misleading/incorrect:
Desktop Analytics Administrator role and Owner, or Contributor permissions on the resource group where the workspace was created.

(admin edit: add metadata to link article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8d7ece-b19f-1431-a619-e57ce6469c28
* Version Independent ID: 86a3d7a5-695b-d3d9-498c-e6b6e03169f8
* Content: [Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/desktop-analytics/overview#prerequisites)
* Content Source: [sccm/desktop-analytics/overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @NickolajA for the feedback. Let me check on this

**Comment by aczechowski** [comment]
I accepted Albert's change to help clarify, it will publish live tomorrow morning.
