### ISSUE TITLE
Software updates scan schedule and deployment reevaluation schedule

### ISSUE THREAD

**Issue by codaamok** [MicrosoftDocs/SCCMdocs#2225]
The description for both of these points under [this section](https://docs.microsoft.com/en-us/configmgr/sum/understand/software-updates-introduction#scan-for-software-updates-compliance-types) are the exact same wording.

Currently the wording for the "*Software updates scan schedule*" is:

> At the configured scan schedule, the client connects to WSUS running on the software update point to retrieve the software updates metadata only when the last scan was outside the TTL.

The wording for the *"Deployment reevaluation schedule"* is:

> At the configured deployment reevaluation schedule, the client connects to WSUS running on the software update point to retrieve the software updates metadata only when the last scan was outside the TTL.

Other than just the change in setting name, the wording is identical and doesn't give clear distinction between the two settings and what they mean. What I'm looking for from this change, is a clear distinction between the two client settings *"Software update scan schedule"* and *"Schedule depoyment re-evaluation"*:

![image](https://user-images.githubusercontent.com/6683266/75249669-97ce9880-57ce-11ea-9508-bbe8d89006ac.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20bd976f-017f-b874-aabb-8d2e87fce7c7
* Version Independent ID: 44d2f52c-7b84-eb5e-5593-197169e19f74
* Content: [Introduction to software updates - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/sum/understand/software-updates-introduction#scan-for-software-updates-compliance-types)
* Content Source: [sccm/sum/understand/software-updates-introduction.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/understand/software-updates-introduction.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
@codaamok, look at the [About client settings](https://docs.microsoft.com/configmgr/core/clients/deploy/about-client-settings#software-updates) article, which has more detailed descriptions of these two settings. 

I think @mestew probably needs to do a deeper review of this SUM intro article to see how to best revise these two bullets.

**Comment by aczechowski** [comment]
This was fixed by @jpcast88 via a private PR back in March. Closing...
