### ISSUE TITLE
Description Update

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/SCCMdocs#2227]
This section (https://docs.microsoft.com/en-us/configmgr/core/clients/manage/cmg/cloud-management-gateway-faq#do-i-need-to-maintain-the-azure-virtual-machines) should be updated with the fact that it is NOT using standard virtual machines.  This deploys a legacy "Cloud Service (classic)" environment and a blob storage account.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a99f1b09-f669-e3c8-e9a1-c2594f329e12
* Version Independent ID: b022b0cd-f045-418a-be0e-f15f699f9d35
* Content: [CMG FAQ - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/manage/cmg/cloud-management-gateway-faq#do-i-need-to-maintain-the-azure-virtual-machines)
* Content Source: [sccm/core/clients/manage/cmg/cloud-management-gateway-faq.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/cloud-management-gateway-faq.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @danmyhre, there's still a VM in use. The point of this FAQ is for customers that think they need to maintain those VMs in Azure, and point them to the PaaS security guidance from Azure. 

We have references to the use of the classic cloud service and storage in the article to [set up CMG](https://docs.microsoft.com/configmgr/core/clients/manage/cmg/setup-cloud-management-gateway):

> The **Microsoft.ClassicCompute** & **Microsoft.Storage** resource providers must be registered within the Azure subscription.

So I'm going to close this issue. If you're passionate about us adding something to the FAQ, please reopen and I'll reconsider. 😄
