### ISSUE TITLE
Another correction on DO

### ISSUE THREAD

**Issue by Yupiter2005** [MicrosoftDocs/SCCMdocs#2231]
From [Optimize Windows 10 update delivery - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/sum/deploy-use/optimize-windows-10-update-delivery#windows-delivery-optimization):
> Configuration Manager version 1802 added a new feature to simplify management of this process by integrating boundary groups with Delivery Optimization. When a client wakes up, it talks to its management point to get policies, and provides its network and boundary group information. Configuration Manager creates a unique ID for every boundary group. The site uses the client's location information to automatically configure the client's Delivery Optimization Group ID with the Configuration Manager boundary ID. When the client roams to another boundary group, it talks to its management point, and is automatically reconfigured with a new boundary group ID. With this integration, Delivery Optimization can utilize the Configuration Manager boundary group information to find a peer from which to download updates.

&gt;&gt;Our UpdateDOGPO components sets BOTH GroupID and DODownloadMode values in Local GPO. 
Therefore one should not configure DODownloadMode separately via Domain GPO.

(admin edit: retargeting the metadata to the client settings article where I think a note about this would be best to live.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f74f4a-560f-2510-1ae8-fd3976a2197e
* Version Independent ID: 0851f834-e9a1-d0a6-ee60-934bcd3a79fe
* Content: [Client settings - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/deploy/about-client-settings#delivery-optimization)
* Content Source: [sccm/core/clients/deploy/about-client-settings.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/about-client-settings.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Yupiter2005 for the feedback. This is often the case with most ConfigMgr settings. But it's worth a note to not also set these settings via group policy.

**Comment by aczechowski** [comment]
Thanks to @jpcast88 for adding a note to this article, which is why the issue closed. His change will publish live tomorrow.
