### ISSUE TITLE
Co-Management on Azure AD registered devices

### ISSUE THREAD

**Issue by ClientAdmin** [MicrosoftDocs/SCCMdocs#2234]
Hi team. From this article it's not really clear that an on-prem AD joined device must be also Azure AD joined for co-management (MDM enrollment) to work. It doesn't seem to work with on-prem AD and Azure AD registered devices. Please clarify. Thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f24ae716-bf27-7d45-cb15-0bc6eea64374
* Version Independent ID: f444ef64-9b7d-999f-3fb3-6ac6cda3ef88
* Content: [Co-management for Windows 10 devices - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/comanage/overview#feedback)
* Content Source: [sccm/comanage/overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @ClientAdmin, see [Prerequisites - Azure AD](https://docs.microsoft.com/en-us/configmgr/comanage/overview#azure-ad):

> Windows 10 devices must be joined to Azure AD....

**Comment by ClientAdmin** [comment]
In the prerequisites it's written that the Windows 10 devices must be joined to Azure AD... under the bullet point it's written that the the device must be on-prem AD joined an Azure AD registered. Also the image looks like it only has to be registered. No Azure AD join. Registration and join aren't the same thing. I'm I missing anything?

**Comment by aczechowski** [comment]
Thanks for the clarification, those are incorrect terms. The prerequisite is that the device is AAD joined.

**Comment by aczechowski** [comment]
I've submitted a change to the prereq terminology that will publish later this morning. I'm also trying to track down the graphic source from a colleague to change that.

**Comment by ClientAdmin** [comment]
Thank you very much! This will help to explain to our customer.

**Comment by ClientAdmin** [comment]
Hi Aaron. Already an idea when the modified content will be published?

**Comment by ClientAdmin** [comment]
Hi Aaron. The text part was already corrected. What about the graphic? This is really relevant. Thank you in advance

**Comment by aczechowski** [comment]
Still trying to track down the original source content from the original author. We're currently working on finalizing the content updates for the upcoming 2002 release, which is the current priority.

**Comment by aczechowski** [comment]
Currently tracking the diagram changes with newer issue MicrosoftDocs/memdocs#220
