### ISSUE TITLE
.NET Framework 2.0/3.0 and Java - detection supported?

### ISSUE THREAD

**Issue by 3flex** [MicrosoftDocs/SCCMdocs#2237]
The company I work for has deployed Desktop Analytics with SCCM 1906.

We are getting various app insights for our apps, but there's no filter option for .NET 2.0 or Java as documented here.

Detection for .NET 1.0/1.1 is working for example (using DotNetOne filter in Desktop Analytics) but there's no filter option for .NET 2 or Java. Is it actually supported by the product?

Not sure if docs issue or product issue in our case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83dca92c-95fc-2089-58c1-3922ba1387c7
* Version Independent ID: 99629c0a-d802-873c-2ddd-68d6093b2300
* Content: [Compatibility assessment - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/desktop-analytics/compat-assessment)
* Content Source: [sccm/desktop-analytics/compat-assessment.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/compat-assessment.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @3flex, I'm checking on this

**Comment by aczechowski** [comment]
I confirmed with the engineering team that this is a bug. My understanding is that support has already filed an incident. I'm closing this issue as there's nothing actionable for docs at this time.
