### ISSUE TITLE
Info on settings for version 1910

### ISSUE THREAD

**Issue by Lembasts** [MicrosoftDocs/SCCMdocs#2240]
The computer restart settings mentioned on this page dont exist in version 1910.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f74f4a-560f-2510-1ae8-fd3976a2197e
* Version Independent ID: 0851f834-e9a1-d0a6-ee60-934bcd3a79fe
* Content: [Client settings - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/deploy/about-client-settings#feedback)
* Content Source: [sccm/core/clients/deploy/about-client-settings.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/about-client-settings.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I'm seeing them in our test environment, and I don't know of any optional feature that would require them to be enabled (but I'll check). I'm going to close this issue as there's nothing actionable for us. I'm sorry that you're having problems. I suggest trying one of the following options to get the best level of support for this issue:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
- [Send a frown](https://docs.microsoft.com/configmgr/core/understand/find-help#product-feedback) in the console
(I'll post back here if I hear anything on why this behavior might be happening.)
