### ISSUE TITLE
Missing requirement to update API permissions

### ISSUE THREAD

**Issue by hoppyshaw** [MicrosoftDocs/SCCMdocs#2243]
We followed the doc and still had to open a case with Microsoft because our data was not showing up in the portal. We could see our devices under the "view devices" tab but we never had the data populate. The fix was to "Grant admin consent for (Our Company)" under API permissions in the Desktop Analytics app registered in App registrations. The documentation should be updated to include checking this is granted. The attached example shows green checkmarks however before we granted access the color was amber. 
<img width="1421" alt="Example" src="https://user-images.githubusercontent.com/33108052/76008974-5a03fb00-5ec5-11ea-805b-5d0043c4841f.png">

(admin edit: adding metadata for article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d8d7ece-b19f-1431-a619-e57ce6469c28
* Version Independent ID: 86a3d7a5-695b-d3d9-498c-e6b6e03169f8
* Content: [Desktop Analytics - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/desktop-analytics/overview#prerequisites)
* Content Source: [sccm/desktop-analytics/overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/desktop-analytics/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @hoppyshaw, thanks for the feedback!

**Comment by aczechowski** [comment]
We have this covered in the section of the DA troubleshooting article on [Create app in Azure AD](https://docs.microsoft.com/mem/configmgr/desktop-analytics/troubleshooting#bkmk_AzureADApps)
