### ISSUE TITLE
Is there a way to request that an App add the Offline method?

### ISSUE THREAD

**Issue by rejohnson76** [MicrosoftDocs/SCCMdocs#2245]
Many Store Apps, especially those from Microsoft, do not offer the Offline install method.  Is there a way to request it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 755fdc0f-0098-7694-8373-154cb4f08dcc
* Version Independent ID: 91d19b28-f30f-dfe3-9f87-f6fcf95f2305
* Content: [Microsoft Store apps - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/apps/deploy-use/manage-apps-from-the-windows-store-for-business?source=docs#feedback)
* Content Source: [sccm/apps/deploy-use/manage-apps-from-the-windows-store-for-business.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/manage-apps-from-the-windows-store-for-business.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @rejohnson76, good question, but I don't know the answer. If there's not any obvious contact/feedback method from the store itself, try the following support options:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
