### ISSUE TITLE
Poor wording in KeepActivation

### ISSUE THREAD

**Issue by merlinfrombelgium** [MicrosoftDocs/SCCMdocs#2248]
> `true` to keep the current product activation flag or reset it. The default value is `false`.

Poor use of grammar in this sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e497ffc-841c-8d38-b30f-3d19af5f24ce
* Version Independent ID: c6d5168d-cb3d-f9c1-d908-4e61532da994
* Content: [SMS_TaskSequence_PrepareOSAction Class - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/develop/reference/osd/sms_tasksequence_prepareosaction-server-wmi-class)
* Content Source: [sccm/develop/reference/osd/sms_tasksequence_prepareosaction-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/osd/sms_tasksequence_prepareosaction-server-wmi-class.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Looks like this was fixed back in March, closing.
