### ISSUE TITLE
DP cert deployment clarification

### ISSUE THREAD

**Issue by ChadSimmons** [MicrosoftDocs/SCCMdocs#2251]
In the section "Deploy the client certificate for distribution points" the Note states "This certificate can also be used for media images that do not use PXE boot, because the certificate requirements are the same."

This implies that the DP cert can be enrolled/exported one time (on any computer) and then used for ALL https DPs and boot media; however, the documentation doesn't clearly state where a unique cert is required to be enrolled on each DP.  Can we get a note added to clarify this point?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c66e3e8a-bd8e-7ae3-aecc-cd9073e2238e
* Version Independent ID: 45572c91-8194-096d-2356-80a9b1b356ef
* Content: [Example PKI certificate deployment - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/network/example-deployment-of-pki-certificates#BKMK_clientdistributionpoint2008_cm2012)
* Content Source: [sccm/core/plan-design/network/example-deployment-of-pki-certificates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/network/example-deployment-of-pki-certificates.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
I'm resolving this issue in part because we moved repositories, but also because I'm going to track this work via an internal work item.

(internal reference 2841906)
