### ISSUE TITLE
Endpoint Protection Logs

### ISSUE THREAD

**Issue by tybarwick** [MicrosoftDocs/SCCMdocs#2252]
Please add something to this page describing the Endpoint protection logs. Where to find them on both the SCCM management server and clients. AND how to extend the retention for the logs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5f1a985-8dd9-1732-ee8b-005a89e5a936
* Version Independent ID: 1adbcbad-510b-3018-0bf2-d3ab8a0d4921
* Content: [Endpoint Protection - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/protect/deploy-use/endpoint-protection#feedback)
* Content Source: [sccm/protect/deploy-use/endpoint-protection.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/endpoint-protection.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @tybarwick for the feedback, that would be a good add.

If you don't already know, that edit would just be linking to the Endpoint Protection section of the existing [log files](https://docs.microsoft.com/configmgr/core/plan-design/hierarchy/log-files#BKMK_EPLog) article.
