### ISSUE TITLE
Incorrect wording for Azure AD Global Administrator

### ISSUE THREAD

**Issue by NickolajA** [MicrosoftDocs/SCCMdocs#2256]
In section 2 of the "Enable co-management starting in version 1906", it refers to an "Azure Global Administrator". This is confusing as to there's not such a thing. It should read "Global Administrator in Azure AD" or something more fitting explaining the actual required permission, not what's currently specified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2f5f810-0397-1cb0-3dc8-ca3a06fce1da
* Version Independent ID: fb6d937b-7681-5a5c-0fb5-ac7fa5faf7b9
* Content: [Tutorial: Enable co-management for existing clients - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/comanage/tutorial-co-manage-clients#feedback)
* Content Source: [sccm/comanage/tutorial-co-manage-clients.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/tutorial-co-manage-clients.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by mestew** [comment]
@NickolajA agreed. Changing it now.
