### ISSUE TITLE
typo????

### ISSUE THREAD

**Issue by Garthmj** [MicrosoftDocs/SCCMdocs#2258]
Five bullets from the bottom. There is this line. 
The Admin configures software inventory to inventory files that have the extension .exe by configuring the software inventory client setting Inventory these file types.

I think. it should be. 

The Admin configures software metering rules to inventory files that have the extension .exe by creating a software metering rules to inventory these files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81f9371a-d0e9-383f-6d1d-0f6c3485679b
* Version Independent ID: ed6caf1d-b71e-fbc6-4f60-b251d52a00f8
* Content: [Monitor app usage with software metering - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/apps/deploy-use/monitor-app-usage-with-software-metering?source=docs#prerequisites-for-software-metering)
* Content Source: [sccm/apps/deploy-use/monitor-app-usage-with-software-metering.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/monitor-app-usage-with-software-metering.md)
* Product: **configuration-manager**
* Technology: **configmgr-app**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @Garthmj, I think this is accurate. If you look at the section on [Configure automatic software metering rules](https://docs.microsoft.com/configmgr/apps/deploy-use/monitor-app-usage-with-software-metering?source=docs#configure-automatic-software-metering-rules), when you enable software inventory, then Configuration Manager automatically generates disabled software metering rules from recent usage inventory data.
I'm closing this issue. Please reopen and comment if you disagree 😉
