### ISSUE TITLE
Important statement

### ISSUE THREAD

**Issue by natebo72** [MicrosoftDocs/SCCMdocs#2259]
The statement indicates that your max run time should be shorten to meet the maintenance windows.  I would also suggest and OR statement be included to also increase the maintenance window to meet the max run time.  There are two options and it should be mention.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54216432-726f-0fbb-5001-1c1021320ba9
* Version Independent ID: b39f5e74-541d-de5b-4a93-77f9627775f5
* Content: [Manage settings for software updates - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/sum/get-started/manage-settings-for-software-updates#BKMK_SetMaxRunTime)
* Content Source: [sccm/sum/get-started/manage-settings-for-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/get-started/manage-settings-for-software-updates.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

(admin edit: update anchor in link to proper section)

**Comment by aczechowski** [comment]
Thanks @natebo72 for the feedback. Fair feedback that you can also set the maintenance window to be larger than the max run time value.
