### ISSUE TITLE
Connection analyzer

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/SCCMdocs#2260]
I cannot location the Connection analyzer in 1906 where the documentation points me towards it.  Is there an EXE and can be manually run?  Having trouble getting CMG running and #documentsfailedme

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a21a4b1e-ade5-1955-d464-b538939b1419
* Version Independent ID: e5485051-d7c6-d2f0-5c44-5dde4570f82c
* Content: [Monitor cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/manage/cmg/monitor-clients-cloud-management-gateway)
* Content Source: [sccm/core/clients/manage/cmg/monitor-clients-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/monitor-clients-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Barleyologist for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.

Here's a screenshot of the Connection analyzer as it's described in the doc. So best to handle as a support issue for now:
![image](https://user-images.githubusercontent.com/26784733/77212816-e3bae780-6ac5-11ea-855a-99d17a39ba3b.png)
