### ISSUE TITLE
WVD is not in preview anymore

### ISSUE THREAD

**Issue by GenerAhl** [MicrosoftDocs/SCCMdocs#2261]
This page still reads "Windows Virtual Desktop is a preview feature of Microsoft Azure and Microsoft 365" when in fact WVD has been GA since September 2019.
https://www.microsoft.com/en-us/microsoft-365/blog/2019/09/30/windows-virtual-desktop-generally-available-worldwide/

**Comment by aczechowski** [comment]
Thanks @GenerAhl for the feeback!
This issue is fixed by a pull request in our private repo. That change will publish live on Monday about 11am Pacific. I'm closing this issue.
