### ISSUE TITLE
Cleanup up what CMG service means in the server column

### ISSUE THREAD

**Issue by ddubs1** [MicrosoftDocs/SCCMdocs#2263]
Most customers require point to point firewall rules.   Better define that CMG service = creating a firewall exception to the IP address of the Cloud Classic service when enabling more then one instance.   This is particularly important right now as customers are scaling their Remote Management Capacity

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778368d0-1054-678c-4d74-5dce1b5826c8
* Version Independent ID: aaac7308-66e6-66f0-8248-14e1505c11a6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway#feedback)
* Content Source: [sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @ddubs1 - see the link below the table to the [Internet access requirements](https://docs.microsoft.com/configmgr/core/plan-design/network/internet-endpoints#bkmk_cloud) article. Where possible, it provides the specific endpoint URLs. The CMG service itself is on an Azure endpoint that's specific to your deployment. There's instructions in the linked article on how to query those from your site database.

If you need specific IP addresses, see the section in the internet endpoints article on [Microsoft public IP addresses](https://docs.microsoft.com/configmgr/core/plan-design/network/internet-endpoints#microsoft-public-ip-addresses)
