### ISSUE TITLE
Section"For internet-based clients communicating with the cloud management gateway"

### ISSUE THREAD

**Issue by DavidHBaur** [MicrosoftDocs/SCCMdocs#2264]
This section does not list CB version1910.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c095180-90a2-79c6-a7fb-6504cafbcfb6
* Version Independent ID: fb9c2930-b213-3eef-c7bb-c8f11ec97aca
* Content: [CMG Certificates - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/manage/cmg/certificates-for-cloud-management-gateway#feedback)
* Content Source: [sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @DavidHBaur, thanks for the feedback. For now, consider the "1810" column as "1810 and later". I've already made changes to this article for the 2002 content refresh, which is coming soon. 😉
