### ISSUE TITLE
on-premise should be on-premises

### ISSUE THREAD

**Issue by GenerAhl** [MicrosoftDocs/SCCMdocs#2265]
There are references to the CM GUI component "Prefer cloud based sources over on-premise sources." on this page, for instance "VPN Clients Properties". "on-premise" is not correct, it should be "on-premises".
https://www.grammar-monster.com/easily_confused/premise_premises.htm

PS. Don't forget to fix the GUI string as well as this documentation. Screen shots of GUI dialogs available here: https://techcommunity.microsoft.com/t5/configuration-manager-blog/managing-remote-machines-with-cloud-management-gateway-in/ba-p/1233895

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7db5025d-eff5-5acb-dd57-0895828e1657
* Version Independent ID: 1b5e1df8-e30a-6eef-b5c6-5f3a4c89131c
* Content: [Configure boundary groups - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/servers/deploy/configure/boundary-groups#bkmk_bgoptions4)
* Content Source: [sccm/core/servers/deploy/configure/boundary-groups.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/boundary-groups.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @GenerAhl, a tricky situation for the few instances like this where the *UI* has a typo. We have to decide whether to mimic the UI for alignment and searchability, or to follow proper style in docs.

Please file [product feedback](https://docs.microsoft.com/configmgr/core/understand/find-help#product-feedback) to note the UI issue to the engineering team.

**Comment by mestew** [comment]
I know this filed as a bug already.  I suspect we will see it change. Until then, we will follow the UI in the doc, even though we cringe every time we see it and every time it gets flagged in doc reviews. =) Closing this issue since we will update the doc when the UI bug is resolved.
