### ISSUE TITLE
Summarize Installed Software Data

### ISSUE THREAD

**Issue by chwunder** [MicrosoftDocs/SCCMdocs#2266]
i have just reviewed this paricular maintenance task and saw that this is to summarize software data which got collected via the hardware inventory for the SMS_InstalledSoftware Asset inteligence class! i couldn´t find a link to software inventory as stated in the description of that maintenance task!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73746b8f-0bb3-a02c-fe91-85395fb33bdd
* Version Independent ID: a7cee2bc-0b6e-e740-238b-9267c3cae370
* Content: [Reference for maintenance tasks - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/servers/manage/reference-for-maintenance-tasks?source=docs#feedback)
* Content Source: [sccm/core/servers/manage/reference-for-maintenance-tasks.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/reference-for-maintenance-tasks.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @chwunder, thanks for the feedback. I think what you're asking is about more information on this functionality of asset intelligence. Which means the link we have on this page for this task (currently to hardware inventory) isn't useful. The proper link here should be to the article to [Configure Asset Intelligence](https://docs.microsoft.com/configmgr/core/clients/manage/asset-intelligence/configuring-asset-intelligence#BKMK_ConfigureMaintenanceTasks), which has more information on this topic.

**Comment by chwunder** [comment]
@aczechowski Hi Aaron, appreciate your feedback. in fact, i have actually changed it to hardware inventory. Before there was a link to software inventory which was wrong in my opinion. This particular maintenance task does actually summarize asset intelligence data which is collected by the hardware inventory. So i think the reference to hardware inventory does make sense. Because this is actually the place where to enable and disable such asset intelligence classes!
I have further mentioned the word asset intelligence in the description, so people know what functionality is further involved into this topic! love the collaboration here ;-)
