### ISSUE TITLE
List the Windows 10 products and what they mean

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/SCCMdocs#2271]
not sure if this is a possibility for this page, but I find it difficult to identify out of the 35 - 40 possible windows 10 options which ones I actually need to use.  Maybe a basic explanation of what scenario requires you tick anything other than "Windows 10"
    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a1f31d1-13b4-d057-572b-b1a58af29692
* Version Independent ID: a79a4b2b-145d-b47b-54b9-6536db780f82
* Content: [Configure classifications and products - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/sum/get-started/configure-classifications-and-products)
* Content Source: [sccm/sum/get-started/configure-classifications-and-products.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/get-started/configure-classifications-and-products.md)
* Product: **configuration-manager**
* Technology: **configmgr-sum**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
@mestew made changes to this doc that should address this feedback: https://docs.microsoft.com/en-us/mem/configmgr/sum/get-started/configure-classifications-and-products#configuring-products-for-versions-of-windows-10
