### ISSUE TITLE
What Happens if you lose connection to the On-Prem Environment

### ISSUE THREAD

**Issue by tankcr** [MicrosoftDocs/SCCMdocs#2275]
Without a secondary site server residing on the Azure side, will clients continue to receive patches and packages from the Azure CMG/DP, or will it cease to function until On-Prem comes back online?

**Comment by aczechowski** [comment]
Hi @tankcr, think of the CMG as a cloud proxy for on-prem MP and SUP roles. A secondary site server doesn't play into the scenario at all. In terms of client behaviors, look at this article on [Site failure impacts](https://docs.microsoft.com/configmgr/core/servers/manage/site-failure-impacts). The same behaviors apply in your scenario as when an on-prem client can't reach the MP or the SUP. If it already has policy, and it can access the content (CMG/CDP or MU) then it will install.
I'm closing this issue.
