### ISSUE TITLE
Cloud management gateway connection point Requirements

### ISSUE THREAD

**Issue by DavidHBaur** [MicrosoftDocs/SCCMdocs#2276]
The "Cloud Management Gateway connection point" is a Role, but there are no hardware requirements listed. Really need to know the Recommended Processor, Disk Space, RAM needed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e67ddd45-90df-32cd-3cbe-9e1443b2540f
* Version Independent ID: dee7fcb8-a7b7-e5a1-9c04-c113805be0da
* Content: [Recommended hardware - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/configs/recommended-hardware#feedback)
* Content Source: [sccm/core/plan-design/configs/recommended-hardware.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/recommended-hardware.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @DavidHBaur, thanks for the feedback. In this instance, it falls under the row for "all other site system roles" in the [Remote site system servers](https://docs.microsoft.com/configmgr/core/plan-design/configs/recommended-hardware#bkmk_RemoteSiteSystem) section.

I'll get a note added to the CMG scale/sizing content.

**Comment by aczechowski** [comment]
I just submitted a change. Once the pull request merges, this issue will automatically close. The change is in our 2002 release branch, so it won't be live until that publishes, which should be *soon* 😉

**Comment by DavidHBaur** [comment]
Thanks Aaron!
