### ISSUE TITLE
CmPivot File() Date/Time Issues

### ISSUE THREAD

**Issue by PehDeh** [MicrosoftDocs/SCCMdocs#2277]
In my Case i use a 
Configuration Manager 1910 Hotfix (KB4537079) https://support.microsoft.com/help/4537079
And when i run :
File('C:\\Windows\\System32\\atmfd.dll')
I experience errors in smsprov.log

##############
*** [22007][241][Microsoft][SQL Server Native Client 11.0][SQL Server]Conversion failed when converting date and/or time from character string.    SMS Provider    25.03.2020 14:33:29    15456 (0x3C60)
*~*~[22007][241][Microsoft][SQL Server Native Client 11.0][SQL Server]Conversion failed when converting date and/or time from character string.     ThreadID : 15456 , DbError: 241 , Sev: 16~*~*    SMS Provider    25.03.2020 14:33:29    15456 (0x3C60)
*** [HY010][0][Microsoft][ODBC Driver Manager] Function sequence error    SMS Provider    25.03.2020 14:33:29    15456 (0x3C60)
*~*~[HY010][0][Microsoft][ODBC Driver Manager] Function sequence error   [22007][241][Microsoft][SQL Server Native Client 11.0][SQL Server]Conversion failed when converting date and/or time from character string.  ThreadID : 15456 , DbError: 0 , Sev: -1~*~*    SMS Provider    25.03.2020 14:33:29    15456 (0x3C60)
CMPivotQuery failed to run query.    SMS Provider    25.03.2020 14:33:29    15456 (0x3C60)
######################
File('C:\\Windows\\System32\\atmfd.dll')| projectDevice,Filename
It works when i don´t reutrn date/time....

Looks like a bug in Configuration Manager 1910 Hotfix (KB4537079)
If you have this issue exclude date/time in the returned properties ;-)

https://social.technet.microsoft.com/Forums/en-US/93923b1c-011a-4fb3-b606-c379e4814f3f/cmpivot-returns-no-results-for-some-queries?forum=ConfigMgrCBGeneral

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c8158c-1c8e-1567-d96d-222f5b4aec21
* Version Independent ID: f6674943-3564-2250-2334-b88c42f3a8a6
* Content: [CMPivot for real-time data - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/servers/manage/cmpivot#prerequisites)
* Content Source: [sccm/core/servers/manage/cmpivot.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/cmpivot.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Thanks @PehDeh for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
