### ISSUE TITLE
Clients per DP

### ISSUE THREAD

**Issue by Stroell** [MicrosoftDocs/SCCMdocs#2282]
“Each distribution point supports connections from up to 4,000 clients” is a little bit misleading especially with the Warning “The actual number of clients that one distribution point can support depends on the speed of the network and the hardware configuration of the server” below.

All my customers just see the 4000 Clients/DP Limit and don’t ‘read further or want to be one the save side (we still want MS to support us). That is causing that my customers install too many DPs in some locations (like in production floors with 20.000 PCs).
I´m not sure where the 4000 limit comes from, but I think the numbers should be validated again. If you have a fast server with SSDs and a 10GbE Connection this limit does not make sense. 
If we define a limit here, it should be more realistic and apply to current hardware capabilities. 
And even if you have a slow server with just 1GbE, will there be any technical issue if let´s say 10.000 clients download at the same time apart from slow downloads? If that´s not the case, the number ‘4000’ should be removed and replaced with a more technical answer.
Cheers,
Stefan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c595a86-976c-dc2c-5b01-fb9d6b761f17
* Version Independent ID: a90f5193-559b-07b0-519a-d5ef32de3151
* Content: [Size and scale - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/configs/size-and-scale-numbers)
* Content Source: [sccm/core/plan-design/configs/size-and-scale-numbers.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/size-and-scale-numbers.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by jpcast88** [comment]
https://docs.microsoft.com/en-us/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway#performance-and-scale 

Is there an upper limit on how many CMGs can be created for a site? For example, if we had a CAS hierarchy with 750K clients, we could just implement as many CMGs needed to support count. In this case, 8 CMGs with 16VM instances per CMG (and 32 CMG connection points)

**Comment by aczechowski** [comment]
Thanks again for the feedback. We moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
