### ISSUE TITLE
Exchange 2019?

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/SCCMdocs#2283]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/SCCMDocs.de-de/issues/4

@trudolf-msft commented 7 hours ago — with docs.microsoft.com
Is Exchange 2019 supported or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86d400f-d2a6-d50b-8d1f-18893af56d67
* Version Independent ID: 793a7196-8549-329c-bad5-c6b33f466ae7
* Content: [Supported clients and devices - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/plan-design/configs/supported-operating-systems-for-clients-and-devices#feedback)
* Content Source: [sccm/core/plan-design/configs/supported-operating-systems-for-clients-and-devices.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/supported-operating-systems-for-clients-and-devices.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @trudolf-msft, thanks for the question. That functionality isn't used very much anymore, so we haven't tested with new versions. It might still work. Since we haven't tested it, we don't *officially* support it, so there's nothing to add to the doc. I'm closing this issue.
