### ISSUE TITLE
SQL Server 2012 Native Client is needed at the passive site server

### ISSUE THREAD

**Issue by PanuSaukko** [MicrosoftDocs/SCCMdocs#2290]
SQL Server 2012 Native client is a prerequisite to the passive site server. You need to manually install it, before starting the passive site server role installation. If SQL Server 2012 Native client is missing, the prerequisite checker will incorrectly complain about missing SQL Server permissions. FailoverMgr.log has the following error: CheckAdminOnSQL has failed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c416209-7476-14b2-a60b-9f3477dc79be
* Version Independent ID: 765534af-f933-c768-0994-fa8d0a5712a0
* Content: [Site server high availability - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/servers/deploy/configure/site-server-high-availability#feedback)
* Content Source: [sccm/core/servers/deploy/configure/site-server-high-availability.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/site-server-high-availability.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I fixed this, the change will be live on Monday
