### ISSUE TITLE
Script Location

### ISSUE THREAD

**Issue by Blacksuit07** [MicrosoftDocs/SCCMdocs#2291]
I did not find anywhere in this page where to locate these scripts. I navigated to several links from this page with no luck. I had to search Bing with the PS Script name to find a blog posting where to find them. For first time admins or people planning for SCCM MBAM management, it would have been helpful to have the location put in the documentation.

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef6976b2-abf4-87b4-9d94-3098c2636654
* Version Independent ID: 966bc208-38c1-3527-6196-7ef5fbfa817d
* Content: [Set up BitLocker portals - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/protect/deploy-use/bitlocker/setup-websites#feedback)
* Content Source: [sccm/protect/deploy-use/bitlocker/setup-websites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/bitlocker/setup-websites.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Blacksuit07, see the section in this article to [Run the script](https://docs.microsoft.com/configmgr/protect/deploy-use/bitlocker/setup-websites#run-the-script):

> 1. Copy the following files from `SMSSETUP\BIN\X64` in the Configuration Manager installation folder on the site server to a local folder on the target server...
