### ISSUE TITLE
PowerBI Report Server version

### ISSUE THREAD

**Issue by PanuSaukko** [MicrosoftDocs/SCCMdocs#2301]
The documentation tells that you need to download "Microsoft Power BI Report Server-September 2019". Does this mean that you need to install specifically September 2019 edition or can you also use Power BI Report Server -January 2020 edition?
(https://www.microsoft.com/en-us/download/details.aspx?id=55329)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1a0ca7a-7b8c-e59c-7cc0-05773ea12391
* Version Independent ID: d1d19180-3929-869f-eadd-e0e1858c29fe
* Content: [Integrate with Power BI Report Server - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/servers/manage/powerbi-report-server#feedback)
* Content Source: [sccm/core/servers/manage/powerbi-report-server.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/powerbi-report-server.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by mestew** [comment]
Thanks much @PanuSaukko 
We clarified "or later" for the versions of both the Power BI Report Server and The Power BI Desktop.
We also clarified that Power BI Desktop should be from the download center, not the store and state that it's the version that's "Optimized for Power BI Report Server".
