### ISSUE TITLE
Upgrade SQL Server for PowerBI Report Server?

### ISSUE THREAD

**Issue by PanuSaukko** [MicrosoftDocs/SCCMdocs#2302]
What do you mean that you need to upgrade SQL Server if using Power BI report server:

"To upgrade SQL Server and SQL Server Reporting Services, first remove the reporting services point from the site. After you upgrade SQL Server, then reinstall the reporting services point in Configuration Manager."

Is it really necessary? If so, from which SQL Server to where?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed3637a6-0616-a14a-2864-9c7d6bbc70e0
* Version Independent ID: 7b0ddfd8-2c0f-9518-39e6-e49130ae2f58
* Content: [Configure reporting - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/servers/manage/configuring-reporting#feedback)
* Content Source: [sccm/core/servers/manage/configuring-reporting.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/configuring-reporting.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @PanuSaukko, that's a general comment about reporting services, nothing to do with PowerBI Server. It's a separate section in the article. Sorry for the confusion.
