### ISSUE TITLE
Multible ConfigMgr Instances

### ISSUE THREAD

**Issue by mattwailes** [MicrosoftDocs/SCCMdocs#2305]
Can you clarify if there are any limitations to multiple instances of ConfigMgr in a single tenant using Co-Management?  Can each instance of ConfigMgr in a single tenant have their own CMG that the individual instances can manage?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f24ae716-bf27-7d45-cb15-0bc6eea64374
* Version Independent ID: f444ef64-9b7d-999f-3fb3-6ac6cda3ef88
* Content: [Co-management for Windows 10 devices - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/comanage/overview)
* Content Source: [sccm/comanage/overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @mattwailes, good questions. I'm not aware of any limitations with co-management and multiple tenants. 

For CMG, see [this FAQ](https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/cloud-management-gateway-faq#do-the-user-accounts-have-to-be-in-the-same-azure-ad-tenant-as-the-tenant-associated-with-the-subscription-that-hosts-the-cmg-cloud-service)

NOTE: I do have an update planned for that FAQ to further distinguish proper terminology around subscription vs tenant. The user accounts are in the tenant, the CMG is in the subscription that’s associated with that tenant. One tenant (AAD instance) can have multiple subscriptions (billing, resources, services), but not vice versa. Look for an update to that FAQ coming soon.

**Comment by mattwailes** [comment]
My org will have multiple domains in a single tenant.  Users from multiple domains will be in a single Azure tenant.  We will have multiple instances of CM that will be doing co-management (each domain has a different instance of CM).

There is no technical limitation to hosting the CMG's from the different domains(different CM hierarchies) using a single Azure sub and tenant correct?
________________________________

**Comment by aczechowski** [comment]
Not that I'm aware of. It's the same as having dev/test/prod environments with a single prod AAD tenant. For site A, you create CMG A. For site B, you create CMG B. Clients in site A only know about CMG A because that's the only one defined in the site, so the only one they are provided in policy. The two services operate side-by-side in your subscription with zero interaction.
