### ISSUE TITLE
%USERPROFILE% variable does not work as advertised in CB 1910

### ISSUE THREAD

**Issue by nojp** [MicrosoftDocs/SCCMdocs#2307]
Under the [File System / Path](https://docs.microsoft.com/en-us/configmgr/compliance/deploy-use/create-custom-configuration-items-for-windows-desktop-and-server-computers-managed-with-the-client#bkmk_file) section - there is a Note section talking about %USERPROFILE%. The information does not seem to be accurate for 1910 - the detection method always just resolves to C:\Users\Default on our test systems (Windows 10 1809 / 1903 / 1909) with MEMCM CB 1910.

This forum post also seems to indicate this has been an issue for a while:

https://social.technet.microsoft.com/Forums/ie/en-US/4ebe340f-c127-463c-aa6b-609237ca1728/configuration-item-with-userprofile-variable-does-not-work-as-expected?forum=ConfigMgrCompliance

Relevant log output from DcmWmiProvider.log:

CAppExecutionLibrary::ExpandEnvironmentVariables: %USERPROFILE%\AppData\Roaming\... evaluated to : C:\Users\Default\AppData\Roaming\...

**Comment by aczechowski** [comment]
Reference: https://docs.microsoft.com/configmgr/apps/deploy-use/create-global-conditions

Thanks @nojp for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
