### ISSUE TITLE
Couple of typos under Common Name.

### ISSUE THREAD

**Issue by juelizon** [MicrosoftDocs/SCCMdocs#2311]
There's a couple of typos under Common Name:
Details for the cloud management gateway CSR
Common Name: ClousServiceNameCMG.YourCompanyPubilcDomainName.com

Suggested:
Common Name: CloudServiceNameCMG.YourCompanyPublicDomainName.com

Thanks,
Juan.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778b6484-ea66-9518-778d-cea65fd183fa
* Version Independent ID: 1ea23258-33b6-738a-cc46-a4059e0d3f42
* Content: [Tutorial: Enable co-management for internet devices - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/comanage/tutorial-co-manage-new-devices)
* Content Source: [sccm/comanage/tutorial-co-manage-new-devices.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/tutorial-co-manage-new-devices.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by jpcast88** [comment]
Nice catch @juelizon. If you're interested you could also submit the change yourself, it's pretty straight forward and something I try to do on a regular basis to help the PG team. Check this page out for more info, [How to contribute](https://docs.microsoft.com/en-us/configmgr/core/understand/use-docs#bkmk_contribute). If you need any help, just let me know.

**Comment by aczechowski** [comment]
Thanks to @jpcast88 for fixing this typo, which is why the issue closed. The change will be live later this  morning. Thanks @juelizon for catching the typo, we appreciate the feedback!
