### ISSUE TITLE
Add a warning that Folder Redirection Group Policy will stop applying

### ISSUE THREAD

**Issue by rgsteele** [MicrosoftDocs/SCCMdocs#2315]
This document needs a warning that enabling user data and profiles for compliance settings will prevent folder redirection group policy from applying, per https://support.microsoft.com/en-ca/help/3060058/folder-redirection-group-policy-is-not-applied-in-windows. (This article doesn't list Configuration Manager version 1910 as being affected but I can confirm that it is.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4001519-abf6-f113-605f-b3d920f8024d
* Version Independent ID: 814b95b8-b0df-96be-eb33-921ad762faab
* Content: [Create user data and profiles configuration items - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/compliance/deploy-use/create-user-data-and-profiles-configuration-items)
* Content Source: [sccm/compliance/deploy-use/create-user-data-and-profiles-configuration-items.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/compliance/deploy-use/create-user-data-and-profiles-configuration-items.md)
* Product: **configuration-manager**
* Technology: **configmgr-compliance**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @rgsteele for the feedback.

**Comment by aczechowski** [comment]
I added a note for this to the article. The issue will auto close when my change merges. The change will go live with the next daily publishing process (which at this point is probably tomorrow morning Pacific).
