### ISSUE TITLE
The Configuration Manager client requests the Azure AD user token. The client makes the claim using the application ID of the Azure AD client app, and the server app as the audience. For more information, see Claims in Azure AD Security Tokens.

### ISSUE THREAD

**Issue by rbhoopat501** [MicrosoftDocs/SCCMdocs#2316]
https://docs.microsoft.com/en-us/configmgr/core/clients/manage/azure-ccmsetup#azure-ad-token-request-workflow..

This is misleading.. Does the Configuration client request Azure AD Device Token first and then fallback to Azure AD User token.. Which statement is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e03621cf-11f9-e98c-8006-9288bfc77c7e
* Version Independent ID: d3b84cd8-05cb-3a77-5c5e-4d7703298202
* Content: [Configure Azure services - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/servers/deploy/configure/azure-services-wizard#feedback)
* Content Source: [sccm/core/servers/deploy/configure/azure-services-wizard.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/azure-services-wizard.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @rbhoopat501, thanks for the question. That diagram is just a high level overview of the flow. For more details, see the [Azure AD authentication workflow](https://docs.microsoft.com/mem/configmgr/core/clients/manage/azure-ccmsetup).
I'll add a link from Configure Azure services to that workflow.
