### ISSUE TITLE
Bitlocker Integration when Co-management is Enabled

### ISSUE THREAD

**Issue by JagadheeshPeram** [MicrosoftDocs/SCCMdocs#2321]
Team, I would like to really appreciate that MBAM has now been completely integrated to SCCM, so that we can decommission MBAM servers, and have the portal for self service and recovery help-desk in SCCM itself. 

But what if i have Co-Management enabled, how should i handle this migration?

Because when the Co-management is enabled, and endpoint protection workload is managed by Intune, So in that case bitlocker management will not be managed by SCCM.

let say if we have Migrated to Intune, then where should i look for reports ? how can i recreate self service and recovery service helpdesk portals ?

Thanks,
Jagadheesh.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c7e528c-a28a-3b1a-372d-b17e4101a565
* Version Independent ID: a57fb032-3cf6-29b8-9114-b1ceb78ab2e4
* Content: [Deploy BitLocker management - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/protect/deploy-use/bitlocker/deploy-management-agent#feedback)
* Content Source: [sccm/protect/deploy-use/bitlocker/deploy-management-agent.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/bitlocker/deploy-management-agent.md)
* Product: **configuration-manager**
* Technology: **configmgr-protect**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @JagadheeshPeram for the feedback. I'm checking with the engineering team on the behavior in this situation.

**Comment by aczechowski** [comment]
The ConfigMgr client handler for BitLocker is co-management aware. If the device is under Intune management (it's co-managed and the EP workload is moved) then the ConfigMgr client ignores the BitLocker policy. The legacy MBAM agent is not aware of other management authorities. So to avoid any potential conflict, it's best to remove the MBAM agent.
Also note that when switching encryption management, the drive will likely need to be re-encrypted.
For more information about managing BitLocker with Intune, see the following articles:
- [Use device encryption with Intune](https://docs.microsoft.com/mem/intune/protect/encrypt-devices#bitlocker-encryption-for-windows-10)
- [Troubleshoot BitLocker policies in Microsoft Intune](https://docs.microsoft.com/mem/intune/protect/troubleshoot-bitlocker-policies)

These are good tips that I'll include on this ConfigMgr BitLocker article. Thanks again for the feedback! 😄
