### ISSUE TITLE
DP Mon only works on the primary site

### ISSUE THREAD

**Issue by MatthewCKelly** [MicrosoftDocs/SCCMdocs#2324]
We Have a Primary site in AU and 2 Secondary sites in NZ..  We can use this tool to view the progress of the AU connected sites however there is no option to connect to the the other two sites..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 452c891e-7f1e-fac5-6639-2a9215523dc6
* Version Independent ID: 2536b942-8f17-a701-35f3-3178d9d708b8
* Content: [DP Job Queue Manager - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/support/dp-job-manager#feedback)
* Content Source: [sccm/core/support/dp-job-manager.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/support/dp-job-manager.md)
* Product: **configuration-manager**
* Technology: **configmgr-core**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by aczechowski** [comment]
Hi @MatthewCKelly, that's how the tool works today. In the **Connect** section of the article:

> You can't connect to the central administration site or secondary sites.

I suggest you file [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) to make sure it gets directly into the hands of the engineering team

I'm closing this issue as there's nothing actionable for docs at this time.
