### ISSUE TITLE
CMG on Azure Resource Manager

### ISSUE THREAD

**Issue by CahillRobert** [MicrosoftDocs/SCCMdocs#2325]
If Azure Resource Manager is the only method to install a CMG post 1810.   What is the process for creation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778368d0-1054-678c-4d74-5dce1b5826c8
* Version Independent ID: aaac7308-66e6-66f0-8248-14e1505c11a6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway#feedback)
* Content Source: [sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @CahillRobert, see the accompanying article on how to [set up a CMG](https://docs.microsoft.com/mem/configmgr/core/clients/manage/cmg/setup-cloud-management-gateway), which has the process for creating a CMG.

**Comment by CahillRobert** [comment]
Thank you for your response.

The documentation covers the following.


   -
      1.

      If you want to reuse the same service name:
      1.

         First delete the classic CMG, taking into account the guidance to
         always have at least one active CMG for internet-based clients.
         2.

         Create a new CMG using a Resource Manager deployment. Reuse the
         same server authentication certificate.
         3.

         Reconfigure the CMG connection point to use the new CMG instance.
         2.

      If you want to use a new service name:
      1.

         Create a new CMG using a Resource Manager deployment. Use a new
         server authentication certificate.
         2.

         Create a new CMG connection point and link with the new CMG.
         3.

         Wait at least one day for internet-based clients to receive policy
         about the new CMG.
         4.

Where in Azure or SCCM is Resource Manager?
  I am using version 1910 I'll be damned if I can find anything about this.
 I dont find this document covering it.  Searching resources in Azure I
dont find it.

That is the source of my frustration.


Thanks for your help.

**Comment by aczechowski** [comment]
Hi @CahillRobert, it's a technical implementation of how ConfigMgr deploys the CMG service into our Azure subscription. It's really only important from the perspective of comparison against the original Azure Service Manager implementation with the early version of the CMG, which relied upon shared certificates. Azure Resource Manager provides integration with Azure Active Directory for authentication in this scenario. Again, you don't really need to know about the guts of Azure to deploy a CMG. It's a "platform as a service (PaaS)" where you don't need to worry about the underlying components of the service. If you really want to learn more about Azure Resource Manager, see [this overview](https://docs.microsoft.com/azure/azure-resource-manager/management/overview) in the Azure management docs.
