### ISSUE TITLE
Is Co-management supported with different AADs

### ISSUE THREAD

**Issue by pedrr** [MicrosoftDocs/SCCMdocs#2329]
We have one SCCM Instance for multiple on-prem ADs. They are synced to several AADs and the clients are also hybrid AAD joined to several AADs.
Is Co-Management in SCCM supported for AAD multitenancy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f24ae716-bf27-7d45-cb15-0bc6eea64374
* Version Independent ID: f444ef64-9b7d-999f-3fb3-6ac6cda3ef88
* Content: [Co-management for Windows 10 devices - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/comanage/overview)
* Content Source: [sccm/comanage/overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-comanage**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @pedrr, thanks for asking the question. From the Prerequisites section:

> Enabling co-management itself doesn't require that you onboard your site with Azure AD.

It goes on to explain that there is one scenario for internet-based devices which requires a CMG, which requires the site to be onboarded to Azure AD. 

Then from the [Configure Azure Services article](https://docs.microsoft.com/mem/configmgr/core/servers/deploy/configure/azure-services-wizard#service-details), onboarding the site for cloud management with Azure AD discovery supports multiple tenants. 😄
