### ISSUE TITLE
ConfigMgr 2002 token based authentication details are missing

### ISSUE THREAD

**Issue by PanuSaukko** [MicrosoftDocs/SCCMdocs#2331]
ConfigMgr 2002 clients have an option to use token based authentication between the client and the CMG. "CMG security details" topic should also give additional information about token based authentication.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc088606-ad8a-4a8c-dc06-4af6f92ee104
* Version Independent ID: d482445e-2164-17ed-449b-3074457f2115
* Content: [CMG security and privacy - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/manage/cmg/security-and-privacy-for-cloud-management-gateway)
* Content Source: [sccm/core/clients/manage/cmg/security-and-privacy-for-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/security-and-privacy-for-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @PanuSaukko, great point. I have some other edits to make in the CMG space soon, I'll make sure to add this in.
