### ISSUE TITLE
Required ports should include client connectivity to blob storage

### ISSUE THREAD

**Issue by amandeepmand** [MicrosoftDocs/SCCMdocs#2332]
The required ports section mentions connectivity from the Client to the CMG endpoint, however I believe connectivity from the Client device to blob storage should also be included.
Blob storage connectivity is mentioned on the "Internet access requirements" page for the CMG service connection point, but not the actual clients themselves.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778368d0-1054-678c-4d74-5dce1b5826c8
* Version Independent ID: aaac7308-66e6-66f0-8248-14e1505c11a6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/configmgr/core/clients/manage/cmg/plan-cloud-management-gateway)
* Content Source: [sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* Technology: **configmgr-client**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @amandeepmand, I think you're correct. I have some other edits to make to the CMG content soon, I'll include this.
