### ISSUE TITLE
Convert wim boot image to iso

### ISSUE THREAD

**Issue by rvoj** [MicrosoftDocs/SCCMdocs#2334]
We are having problems in our VMWare environment, as VMWare does not support booting from our SCCM pxe server. WinPE just hangs.
This can easily be fixed by using an iso boot image on our server, but I cant find any method to convert the wim boot images to iso, unless I want to use an usb, which I can't as I'm working remotely.
I have banged my head against this for the last 1,5 years, and never found a method to just convert the wim to iso.
It works flawlessly in MDT, so why not in SCCM?

**Comment by sekorotkov** [comment]
You can create: Bootable or Stand-alone media (.iso) https://docs.microsoft.com/en-us/mem/configmgr/osd/deploy-use/create-stand-alone-media

**Comment by aczechowski** [comment]
Thanks @rvoj for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
