### ISSUE TITLE
Fix Configuration Manager performance and scale guidance whitepaper Link

### ISSUE THREAD

**Issue by AnoopCNair** [MicrosoftDocs/SCCMdocs#2337]
Do we know whether we have any other repository to download this 🔽

Microsoft Doc - Missing Configuration Manager performance and scale guidance whitepaper.
Recommended hardware - Configuration Manager | Microsoft Docs - [https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/configs/recommended-hardware](https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/configs/recommended-hardware)
 @![Docs](https://user-images.githubusercontent.com/37192004/108823611-ad93bb00-75e6-11eb-9524-d4592f453e4d.png) 

@aczechowski

**Comment by aczechowski** [comment]
Thanks @AnoopCNair for the feedback. In the future, please use the [memdocs repo](https://github.com/MicrosoftDocs/memdocs/issues). We may retire this repo in the future, it's not actively used.

Little known fact…we actually migrated the whitepaper to docs a while back, but just needs some cleanup, so hadn’t “announced” it. But the guts of the content is in the same TOC section:

[Site size and performance guidelines](https://docs.microsoft.com/mem/configmgr/core/plan-design/configs/site-size-performance-guidelines)

And then the FAQs from the whitepaper are in a separate article:
[Site size and performance FAQ](https://docs.microsoft.com/mem/configmgr/core/understand/site-size-performance-faq)

I'll update the link you note, and look for any others that we have in our docs.ms content.
