### ISSUE TITLE
Remote Content Library on Azure File Storage supported configuration?

### ISSUE THREAD

**Issue by Sri-Boddupalli** [MicrosoftDocs/SCCMdocs#2340]
For the HA feature is the Remote Content library supported when hosted on an Azure File Storage? Where the Site Servers and Site Systems are running in an IaaS configuration.
[https://docs.microsoft.com/en-us/mem/configmgr/core/plan-design/hierarchy/remote-content-library](url)

**Comment by aczechowski** [comment]
i see you already refiled this in the proper location, so closing this issue
https://github.com/MicrosoftDocs/memdocs/issues/3099
