### ISSUE TITLE
Error 404 from peercache client link

### ISSUE THREAD

**Issue by kayasax** [MicrosoftDocs/SCCMdocs#253]
On the page 
https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md

in the peercache section ( https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md#peer-cache )
the provided link lands on a 404 error page.

the link is : https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/client-peer-cache

it should be :  https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/client-peer-cache.md

**Comment by mtillman** [comment]
@brenduns Please review this issue. If a fix is required, @mention me or @dougeby to have the issue closed when the fix is published.

**Comment by Brenduns** [comment]
@Mike Tillman<mailto:Michael.Tillman@microsoft.com>  @Doug Eby<mailto:dougeby@microsoft.com>

This issue is resolved.  The live content has the correct link.
