### ISSUE TITLE
Include a note on how to delete a VPP Token from the SCCM console

### ISSUE THREAD

**Issue by pphadke** [MicrosoftDocs/SCCMdocs#329]
Include a note or screenshot on how to delete a VPP Token from the SCCM console

**Comment by arob98** [comment]
@mattbriggs @Erikre FYI

**Comment by Erikre** [comment]
This item is being tracked: 820879

**Comment by aczechowski** [comment]
Checking with engineering team

**Comment by aczechowski** [comment]
doc bug 505268 is primary tracking item

**Comment by aczechowski** [comment]
I just submitted a change for this request. This issue should auto-close soon once the pull request is merged and closed. Thanks for your feedback!
