### ISSUE TITLE
ImportMachineEntryToMultipleCollections method is not documented

### ISSUE THREAD

**Issue by davidpaMSFT** [MicrosoftDocs/SCCMdocs#332]
ImportMachineEntryToMultipleCollections method is not documented for SMS_Site class: https://docs.microsoft.com/en-us/sccm/develop/reference/core/servers/configure/importmachineentry-method-in-class-sms_site

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a6c1035-ec59-a689-f62c-2abbab9d70a0
* Version Independent ID: a3ed8be7-b25b-d96f-bc6a-5de229783c7b
* Content: [ImportMachineEntry Method - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/core/servers/configure/importmachineentry-method-in-class-sms_site)
* Content Source: [sccm/develop/reference/core/servers/configure/importmachineentry-method-in-class-sms_site.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/core/servers/configure/importmachineentry-method-in-class-sms_site.md)
* Service: **unspecified**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by arob98** [comment]
@Brenduns FYI

**Comment by aczechowski** [comment]
Filed SMS doc bug 503692 to track

**Comment by aczechowski** [comment]
I received some detail from engineering I'll share until we can get an article published for this SDK method. The two methods are mostly identical, except the first one takes a single CollectionID string, and ImportMachineEntryToMultipleCollections takes an array of collection ID strings.

**Comment by aczechowski** [comment]
This issue is closed because a new article will publish later today for this method. Kudos to @AdamGrossTX for providing the content, and nudging me to make it happen!
