### ISSUE TITLE
Missing parameters for Scripted installation

### ISSUE THREAD

**Issue by Stephanevg** [MicrosoftDocs/SCCMdocs#390]
Hi

it seems that the documentation explaining how to script the isntallation of ConfigMgr ([here](https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/core/servers/deploy/install/command-line-options-for-setup.md)) is missing some sections .

I generated an Ini file based on a Graphical step by step installation process, and found the following sections from which I cannot seem to find the help sections related:

[SystemCenterOptions]
SysCenterId=<Long Hash>

[SABranchOptions]
SAActive=1
CurrentBranch=1

If theses are documented somewhere else, it would either make sense to move them in here, or at least provide a link to their actual location to have a centralized entry point when it comes to scripting the installation of ConfigMgr.

Can someone add a short explanation on these different options and effects they have on the installation.

Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a393419-2d34-ebba-9482-7c988797f5c9
* Version Independent ID: 95f509c1-5494-7f40-6392-6f7f8988dd2e
* Content: [Setup command-line options - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/command-line-options-for-setup)
* Content Source: [sccm/core/servers/deploy/install/command-line-options-for-setup.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/command-line-options-for-setup.md)
* Service: **unspecified**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Stephanevg for reporting this. I filed doc bug 509715 to investigate with the feature team. I know there were changes to setup in the past year or so to prompt for Software Assurance and other licensing aspects, so suspect these are related.

**Comment by Stephanevg** [comment]
Great! 
I am happy to see this is getting forward. (Even though it really feels a bit long).

**Comment by aczechowski** [comment]
I made changes to this article to address this issue, it will publish live later today.
