### ISSUE TITLE
Add information that ConfigMgr reporting account needs db_datareader permissions on data warehouse db

### ISSUE THREAD

**Issue by PanuSaukko** [MicrosoftDocs/SCCMdocs#391]
Add to this page that ConfigMgr reporting account needs db_datareader permissions on data warehouse database. Otherwise, you get access denied error message when you run reports.

**Comment by aczechowski** [comment]
Hi @PanuSaukko. I'm assuming you're talking about this page: https://docs.microsoft.com/en-us/sccm/core/servers/manage/data-warehouse. It does include the following in the troubleshooting section:

> Data warehouse reports fail to open when the data warehouse database and reporting service point are on different site systems.
> 
> Solution:
> Grant the Reporting Services Point Account the db_datareader permission on the data warehouse database.

Was there somewhere else that you were looking for this information and didn't find it?

**Comment by PanuSaukko** [comment]
Hi Aaron,

The order of the information is confusing. The sentence: “Grant the Reporting Services Point Account the db_datareader permission on the data warehouse database” should in Prerequisites for data warehouse service point or in Reporting topic at the latest.

The reporting will fail with 100% of customers without the permissions. ☺

The info could be also in Troubleshooting for users who don’t follow the steps.

Panu

**Comment by aczechowski** [comment]
Ok, verified with engineering team. Filed doc bug 509759 to address this.

**Comment by mestew** [comment]
@aczechowski I created a PR for this. It is currently under review and should go live once that process  completes. 
@PanuSaukko Thanks for noticing this and pointing it out to us!
