### ISSUE TITLE
'CEIP privacy statement' link redirecting to 404

### ISSUE THREAD

**Issue by OfficeGSX** [MicrosoftDocs/SCCMdocs#398]
Fix the incorrect link in the topic below:

URL:  https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/core/plan-design/diagnostics/customer-experience-improvement-program-ceip.md

Incorrect link: [CEIP privacy statement](https://www.microsoft.com/products/ceip/en-us/privacypolicy.mspx)

Correct link: [CEIP privacy statement](https://privacy.microsoft.com/en-us/privacystatement)

Thanks,
Petr

**Comment by aczechowski** [comment]
Thanks @OfficeGSX. I just created a pull request to address this, as well as in another article that has the same (https://docs.microsoft.com/en-us/sccm/mdt/use-the-mdt). 

Reference: https://github.com/MicrosoftDocs/SCCMDocs-pr/pull/2364

**Comment by aczechowski** [comment]
My pull request last week updated the URLs, so closing this issue.
