### ISSUE TITLE
In the docs for Task Sequence steps it doesn't mention that Install applications from variable is case-sensitive

### ISSUE THREAD

**Issue by SweJorgen** [MicrosoftDocs/SCCMdocs#399]
On this page
https://docs.microsoft.com/en-us/sccm/osd/understand/task-sequence-steps 
Under Install Applications and install applications from a list, it should mention that the application name is case-sensitive..

**Comment by aczechowski** [comment]
Thanks, tracking with same doc bug 509714 :)

**Comment by aczechowski** [comment]
Just submitted a change for this. Should go live on next publishing cycle. Thanks again for your feedback.
