### ISSUE TITLE
In the docs for task sequence steps it should state that when installing packages/programs using a dynamic variable, the program name is case-sensitive

### ISSUE THREAD

**Issue by SweJorgen** [MicrosoftDocs/SCCMdocs#400]
On this page
https://docs.microsoft.com/en-us/sccm/osd/understand/task-sequence-steps 
Under Install Pacakge and install package from a list, it should mention that the Program-name is case-sensitive, it mentions that the package name must be in capital letters but not program

**Comment by aczechowski** [comment]
Thanks @SweJorgen! I filed doc bug 509714 to track this issue. I want to verify the behavior with the engineering team first.

**Comment by aczechowski** [comment]
Just submitted a change for this. Should go live on next publishing cycle
