### ISSUE TITLE
Add details for justification of elevated access

### ISSUE THREAD

**Issue by mrbodean** [MicrosoftDocs/SCCMdocs#405]
Based on a twitter discussion a reference of the accounts and roles that require local admin and sysadmin access and why should be added. For example:
Primary Site Server Computer account - This account requires local admin rights on all site servers in order to manage, install, and remove services and update local groups when site roles are added or removed in the admin console. This account requires sysadmin access to the SQL instance in order configure SQL in response to actions taken in the admin console. 
User accounts in the Full Admin role - These accounts require local admin rights on all site servers in order to view, edit, remove, and install services, registry keys and values, wmi objects and repositories. This account requires sysadmin access to the SQL instance in order to install and update the database during a setup or recovery of the application. This access is also required when executing SQL maintenance manually i.e. reindexing and updating statistics. 
*** Note that some environments may choose to remove sysadmin access and only grant it when preforming actions when it is required. In those environments these user accounts should be granted access to read, update, and execute stored procedures on the Configuration Manager database in order to troubleshoot issues without granting sysadmin access.

**Comment by aczechowski** [comment]
Thanks @mrbodean 
So maybe some clarification here? https://docs.microsoft.com/sccm/core/plan-design/hierarchy/accounts

**Comment by aczechowski** [comment]
I added this info, it should publish live on Monday. Thanks again 😄
