### ISSUE TITLE
SCEP Exclusion Settings is incomplete

### ISSUE THREAD

**Issue by jason4tw** [MicrosoftDocs/SCCMdocs#436]
The Exclusion Settings section at https://docs.microsoft.com/en-us/sccm/protect/deploy-use/endpoint-antimalware-policies#exclusion-settings does not include anything about file type or process exclusions including if full path names are required or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5215a151-f390-9123-5384-516ec3ed3078
* Version Independent ID: 62124728-8029-4565-79a6-88f842ad1e73
* Content: [Endpoint Protection antimalware policies - Configuration Manager](https://docs.microsoft.com/en-us/sccm/protect/deploy-use/endpoint-antimalware-policies#exclusion-settings)
* Content Source: [sccm/protect/deploy-use/endpoint-antimalware-policies.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/endpoint-antimalware-policies.md)
* Service: **unspecified**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jason4tw. I filed doc bug 510664 to track. @mestew for visibility

**Comment by aczechowski** [comment]
Thanks to @jpcast88 for making a change for this issue, which is why it closed. The change will publish live tomorrow.
