### ISSUE TITLE
Update PS Cmdlet reference

### ISSUE THREAD

**Issue by steinhkl** [MicrosoftDocs/SCCMdocs#444]
I'm not sure if this is the correct repo but here it goes:

Please update the SCCM PS reference (on a regular basis). The Documentation on the PS Cmdlet is (sometimes very) out of date.
Functions introduced in August 2017 (now in production) are still not documented (such as Set-CMTSStepApplyOperatingSystem). 
I know Get-Help will tell me most things but the reference docs are much more readable.

Thanks for all your hard work!

**Comment by aczechowski** [comment]
@steinhkl thanks for sharing the feedback. It's an obvious issue of which we're well aware. We're examining options to shore up the PowerShell and SDK content, and how to best sustain going forward. We do publish release notes with each new version, for example [1802](https://docs.microsoft.com/powershell/sccm/1802_release_notes?view=sccm-ps). I'm going to close this issue as it's not specifically actionable right now.
