### ISSUE TITLE
SQL broker usage documentation

### ISSUE THREAD

**Issue by dotraphael** [MicrosoftDocs/SCCMdocs#452]
It is well known and documented that the sql broker is used for site replication
(https://docs.microsoft.com/en-us/sccm/core/servers/manage/data-transfers-between-sites - To replicate data between sites, Configuration Manager uses its own database replication service. The database replication service uses SQL Server change tracking to monitor the local site database for changes, and then replicates the changes to other sites by using SQL Server Service Broker (SSB). By default, this process uses TCP/IP port 4022.)

however, it is not known if SQL Broker is required in a single std primary site. as per conversation with PGs, it is required for some functions like BGB, so this information should be documented.

**Comment by aczechowski** [comment]
Thanks for submitting this @dotraphael. I filed internal doc bug 512107 for tracking.

**Comment by ChrisKibble** [comment]
@aczechowski , what about here:
https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/core/plan-design/configs/support-for-sql-server-versions.md

**Comment by aczechowski** [comment]
Thanks @ChrisKibble, yes that's a good spot
