### ISSUE TITLE
Cloud DP Setup

### ISSUE THREAD

**Issue by AnoopCNair** [MicrosoftDocs/SCCMdocs#455]
Azure Portal URL Change Request 

https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/install-cloud-based-distribution-points-in-microsoft-azure#to-set-up-a-cloud-service-in-azure-for-a-distribution-point

1.  Open a web browser to the Azure portal, at https://portal.azure.com, and access your account.  

2.  Click **Subscriptions, <Subscriptions Name>**, and then select **Management Certificates**.  

(ACz edit: adding metadata for article linkage)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44cd259e-b744-f8db-431a-06e884e8349a
* Version Independent ID: 6ee1e977-135e-f83d-77d7-e0ad0e018c67
* Content: [Install cloud-based distribution points - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/install-cloud-based-distribution-points-in-microsoft-azure#feedback)
* Content Source: [sccm/core/servers/deploy/configure/install-cloud-based-distribution-points-in-microsoft-azure.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/install-cloud-based-distribution-points-in-microsoft-azure.md)
* Service: **unspecified**
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @AnoopCNair, the CDP docs are in need of a general overhaul as they haven't been touched in years. It's on my hit list for the next several months, similar to what I recently did with the CMG docs. So I'm going to close this issue for now; I'm tracking the revisions along with minor changes such as this (internal doc bug 512106 among others). Thanks for pointing it out!

**Comment by aczechowski** [comment]
Got another comment on this, so linking with the article and reopening until I make the changes.

**Comment by aczechowski** [comment]
I've finalized revisions for this article and [Use a cloud DP](https://docs.microsoft.com/sccm/core/plan-design/hierarchy/use-a-cloud-based-distribution-point). These revisions will publish with the 1806 content, so I'm closing this issue.
