### ISSUE TITLE
Feedback on Co-Management for Hybrid Active Directory Environments

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/SCCMdocs#470]
Summary - I wrote everything below then decided to summarize it here. My company is trying to plan for implementing Co-Management in a Hybrid AD environment and it would be helpful to have a comprehensive guide (with pre-requisite requirements) to help us determine the scope of work and required resources (people and technology). Additionally, the format of linking from one topic to another which links to others, makes it very hard to determine which step is needed when.

Details
Some quick background first. I made a post on Twitter about setting up Co-Management and how I had some issues with the documentation for doing it. https://twitter.com/AdamGrossTX/status/987175059478515712 and @aczechowski asked me to provide some detail about my issues.  In my company, we've been working to enable Co-Management in our environment with the help of the Microsoft Fast Track team and SCCMDocs and after several attempts, have been unsuccessful due to difficulty understanding the order of things and difficulty understanding the permissions requirements for setting up Azure components. Last night, in a few hours, I was able to follow this guide http://www.scconfigmgr.com/category/co-management/ to set it up in my lab with no real issues.   I hope that my feedback is constructive and useful. I want to help make it better.

The challenge I've faced when trying to use the docs for configuring Co-Management is that there's no real centralized "Start Here" section or a checklist to say "Complete these in this order" type guide.  Most of the presentations about Co-Management and Auto-Pilot make it out to be a super simple setup but gloss over the fact that for Hybrid AD environments, there are a lot more steps that are required to enable Co-Management.  

When I'm building this in a lab, I'm a global admin and have all the rights to all the places to configure all of the pieces.  In my company, these responsibilities are shared across several teams.  We began researching how to enable Co-Management using the Microsoft Docs and were unable to get a full understanding of all of the items that were required.  Depending on where you begin in the documentation, you may click through to several pre-requisites and each of those may have pre-requisites or caveats that lead you down various paths.  None of them seem to be the central, start here, do these things, end up here, type guide.

I do think I understand that, from a documentation perspective, you are trying to have a single source for any given topic so that you don't have to update it in multiple places each time. However, it doesn't flow well when you are at the section "How to configure co-management" https://docs.microsoft.com/en-us/sccm/core/clients/manage/co-management-overview then immediately have to click on "Hybrid Azure AD joined" https://docs.microsoft.com/en-us/azure/active-directory/device-management-hybrid-azuread-joined-devices-setup which assumes you've done other Azure configuration like setup Azure AD Connect, but doesn't have a link or instructions for doing that in the doc so now I have to search for Azure AD Connect documentation and go through all of that. 

Hopefully this provides some insight into my issues. Please contact me if you'd like to discuss further.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07e9b780-6cad-d3f3-d0f2-e13a577890cc
* Version Independent ID: 18c7f0aa-884a-349b-e416-74d02adc4474
* Content: [Co-management for Windows 10 devices - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/co-management-overview)
* Content Source: [sccm/core/clients/manage/co-management-overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/co-management-overview.md)
* Service: **unspecified**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I'm closing this issue. A big revision to the co-management content will publish soon, and I think addresses this issue. After the new content is published, if you don't think this issue is addressed, please file a new issue on the new article(s). (Specifically there's one new tutorial that will publish with the new content, and a second tutorial in the works. That's the content that I think will best address the concerns in this issue.)
