### ISSUE TITLE
Instructions for copying WinPE images to UFD and creating BCD entries would be helpful

### ISSUE THREAD

**Issue by joshuaalm** [MicrosoftDocs/SCCMdocs#479]
Current instructions say to use the .iso file and ignore the .wim files created during the update.  

Instructions on how to create the entry in BCD here are nearly complete:

https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-7/dd744541(v=ws.10)

This page gives a thorough cookbook-like explanation of the BCD editing process for various entry types:

http://supportishere.com/manually-updating-creating-bcd-files-for-windows-78/

I suggest combining them (with original author's permission) into a document that thoroughly explains the process for making a BCD menu for one or more .wim files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 050dc241-8019-e6b2-1cfd-39f95f6fb41d
* Version Independent ID: 7d358f76-efc4-7492-d416-106523d17181
* Content: [Quick Start - Lite Touch Installation - Microsoft Deployment Toolkit](https://docs.microsoft.com/en-us/sccm/mdt/lite-touch-installation-guide)
* Content Source: [sccm/mdt/lite-touch-installation-guide.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdt/lite-touch-installation-guide.md)
* Service: **unspecified**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by joshuaalm** [comment]
https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/mdt/lite-touch-installation-guide.md

Step 4-1

To be fair, there's not much instruction on how to create bootable optical media either; it would seem experience in doing so is assumed.  It just feels incomplete without acknowledging UFDs (which I created today) and I'm used to PXE booting with WDS, so I had to manually create the BCD entry for the LTI wim.  That is to say, I forced myself to create a new entry rather than rename the LTI wim and lose my preciousss vanilla boot.wim.

**Comment by aczechowski** [comment]
(Edited original comment to add metadata block for linkage with target article)

**Comment by RAJU2529** [comment]
I think MDT  can be installed on windows 10 also . But  windows 10  deployment methods are not given in this  article.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
