### ISSUE TITLE
Add Note per customer case

### ISSUE THREAD

**Issue by AndreaFrabotta** [MicrosoftDocs/SCCMdocs#481]
Hey – per feedback from a customer case and our own research, we would like to modify the following note in this document.

•	Current note:
Note
When you have the All users collection selected for the Intune subscription, you are not allowed to add a rule to exclude collections. Create a new collection based on the All users collection, verify that the collection contains the users that you expect, and then edit the Intune subscription to use the new collection. You can exclude user collections from the new collection to migrate users. 

•	Suggested update:

Note
When you have the All users collection selected for the Intune subscription, you are not allowed to add a rule to exclude collections. Create a new collection based on the All users collection, verify that the collection contains the users that you expect, and then edit the Intune subscription to use the new collection. You can exclude user collections from the new collection to migrate users. 
If All Users AND All Groups are included in the SCCM/Hybrid Intune user collection, and a test user in a user collection is excluded from the SCCM/Hybrid Intune user collection, and the user in the excluded user collection is in any group, the user won't be excluded from the SCCM/Hybrid Intune user collection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4913cd11-dd09-791f-af96-9849efa08ef9
* Version Independent ID: 4e271b5d-8d9f-7837-867e-1fc1fffd3242
* Content: [Change the MDM authority for specific users (mixed MDM authority) - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/migrate-mixed-authority#feedback)
* Content Source: [sccm/mdm/deploy-use/migrate-mixed-authority.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/migrate-mixed-authority.md)
* Service: **unspecified**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Have an email thread to investigate further. On the surface this appears to conflict with the information about **Exclude collection rule** on [Create collections](https://docs.microsoft.com/sccm/core/clients/manage/collections/create-collections).

**Comment by ptreptau** [comment]
There is no mention how to import the module for Switch-MdmDeviceAuthority.

Solution: Import-Module .\MicrosoftIntuneDataImporter.Commands.dll (from the Intune Import tool directory)

**Comment by ChrisKibble** [comment]
@AndreaFrabotta, I think I know what you're trying to say, could we word it like this for a bit of clarity and also to cover groups other than "All Groups"?

`
When you have the All Users collection selected for the Intune subscription, you are not allowed to add a rule to exclude collections. Instead, create a new collection based on the All Users collection, verify that the collection contains the users that you expect, and then edit the Intune subscription to use the new collection. You can exclude user collections from the new collection to migrate users.

If you exclude a user from a collection but include a group that the user is a member of, the user will not be excluded from the collection`

**Comment by ChrisKibble** [comment]
@aczechowski - about a month with no response from the original submitter, do you have any comments on the edit?

**Comment by aczechowski** [comment]
Thanks @ChrisKibble, no further comments from me. You can make the change if you want. Honestly, this content is a low priority as the service is deprecated and will be turned off in less than two months.

**Comment by ChrisKibble** [comment]
Understand it's low priority.  Could help someone I suppose, and I already wrote the blurb, so I'll submit a PR.
