### ISSUE TITLE
Update note on disable deadline randomization

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#484]
Currently only software updates feature honor that deadline randomization override. It is not done for required app deployments. The linked page on the client setting only talks about software updates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb29ee1f-a6dc-e390-769d-cbe0fb247564
* Version Independent ID: cc6cccfe-2ab4-cf0a-3f97-e6dc9765b860
* Content: [Virtual desktop infrastructure (VDI) client management  - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/deploy/plan/considerations-for-managing-clients-in-a-vdi#feedback)
* Content Source: [sccm/core/clients/deploy/plan/considerations-for-managing-clients-in-a-vdi.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/plan/considerations-for-managing-clients-in-a-vdi.md)
* Service: **unspecified**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by jocasti** [comment]
@aczechowski How can I help with this issue? Does the note just need to remove the reference to "required application deployments"?

**Comment by aczechowski** [comment]
Thanks @jocasti. Yes, I think that's the extent of it. Easy peasy. 😃

**Comment by jocasti** [comment]
Opened  PR#969 to correct this issue.

**Comment by aczechowski** [comment]
Closing this issue; fixed with referenced pull request by @jocasti
