### ISSUE TITLE
1803 ADK / Windows 1803?

### ISSUE THREAD

**Issue by somewhatlogical** [MicrosoftDocs/SCCMdocs#485]
Where is the guidance on this?  Windows 1803 supported or not?  ADK support or not?  Configurations of 1803 ADK / SCCM / Windows version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc732ec0-eb14-8da2-7688-dd74a72cdae5
* Version Independent ID: a93682ff-2984-38e0-5a0d-6f77c1c9e5db
* Content: [Support for Windows 10 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/support-for-windows-10)
* Content Source: [sccm/core/plan-design/configs/support-for-windows-10.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/support-for-windows-10.md)
* Service: **unspecified**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @somewhatlogical for your question, good timing. I'm literally working on this now.

**Comment by aczechowski** [comment]
Page is updated, closing this issue
