### ISSUE TITLE
Add guidance from Microsoft Premier

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#486]
Tracking item for work with @mkennten on improving this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85f2d833-ba84-c5d0-a0f5-91770355cc79
* Version Independent ID: 0bc4086b-c5fd-45de-bd92-b678d3c8875a
* Content: [Maintenance tasks - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/maintenance-tasks#feedback)
* Content Source: [sccm/core/servers/manage/maintenance-tasks.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/maintenance-tasks.md)
* Service: **unspecified**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by JoergWu** [comment]
Are there any news? Its nearly a year ago.

**Comment by jocasti** [comment]
@aczechowski @mkennten Anything I can do to help with updating this article? I think we're only missing two maintenance tasks: Delete Aged Console Connection Data and Delete Duplicate System Discovery Data

**Comment by aczechowski** [comment]
I'm going to close this issue. @mestew recently revised this article for changes in 1906, and I have a change in for the maintenance task reference article that should publish tomorrow.
