### ISSUE TITLE
Undocumented AdvertFlags

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#487]
From closed pull request #409 by @davidpaMSFT 

> It seems we have some undocumented AdvertFlags. It seems these are for some deployment options added to the product later, e.g.:
>
>19 - "Allow task sequence to run for client on the Internet"
>28 - Deployment Settings\Make available for the following - "Only media and PXE"
>29 - Deployment Settings\Make available for the following - "Only media and PXE (hidden)"
>
>The above flags and corresponding deployment options are based on my observations in the lab and some DL discussions, but should be double-checked and also validate if there are any addtiional un-documented flags.
>
>In addition to documenting the bits we probably need an additional verbiage under the table about bits 28 and 29 - although setting these bits (without bit 18) will be reflected in UI as expected, the PXE (and likely media) clients will not see this advertisement/deployment unless bit 18 is also set.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a4e1c6f-f511-82da-26ce-942618e89408
* Version Independent ID: 884eabf1-5a3f-7deb-a523-2d077b5ef648
* Content: [SMS_Advertisement Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/core/servers/configure/sms_advertisement-server-wmi-class)
* Content Source: [sccm/develop/reference/core/servers/configure/sms_advertisement-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/core/servers/configure/sms_advertisement-server-wmi-class.md)
* Service: **unspecified**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Some detail from engineering on missing flags:

OptionalPredownload = 0x00001000  // If the selected architecture and language matches that of the client, the package content will be downloaded in advance
APTSIntranetOnly = 0x00080000
TargetToWinPE = 0x10000000  // Target this deployment to WinPE only
HiddenInWinPE = 0x20000000  // TS is targeted to WinPE only but hidden in WinPE. It can only be used by TS variable "SMSTSPreferredAdvertID".

**Comment by ChrisKibble** [comment]
Any reason we shouldn't add the new details to the doc?  Happy to jump on it if this isn't internal only or something that doesn't belong.

**Comment by aczechowski** [comment]
Thanks @ChrisKibble, yes this info is from engineering, and good to add to the doc.

**Comment by ChrisKibble** [comment]
Took me a while to figure out the hex -> bit conversion for the mask, so I'm posting here for the next guy:

Mask | Result Bit
-- | --
0x00000001 | 0
0x00000002 | 1
0x00000004 | 2
0x00000008 | 3
0x00000010 | 4
0x00000020 | 5
0x00000040 | 6
0x00000080 | 7
0x00000100 | 8
0x00000200 | 9
0x00000400 | 10
0x00000800 | 11
0x00001000 | 12
0x00002000 | 13
0x00004000 | 14
0x00008000 | 15
0x00010000 | 16
0x00020000 | 17
0x00040000 | 18
0x00080000 | 19
0x00100000 | 20
0x00200000 | 21
0x00400000 | 22
0x00800000 | 23
0x01000000 | 24
0x02000000 | 25
0x04000000 | 26
0x08000000 | 27
0x10000000 | 28
0x20000000 | 29
0x40000000 | 30
0x80000000 | 31
