### ISSUE TITLE
Win10 AADJ devices need IP subnet boundaries

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#488]
AD Site boundaries do not work for pure AzureAD clients. If they roam on-premises they don't fall into any boundary if only defined using AD Sites. Need to add this as a design consideration. 

Need to determine best locations to document this. 

Reference internal engineering item 512535

**Comment by ChrisKibble** [comment]
Seems it would make the most sense here?
sccm/core/servers/deploy/configure/boundaries

**Comment by aczechowski** [comment]
Thanks @ChrisKibble, yes that's probably the best spot.
