### ISSUE TITLE
Software update point requirements

### ISSUE THREAD

**Issue by MartinRain** [MicrosoftDocs/SCCMdocs#490]
Starting 1802, the MP requires to be configured to use HTTPS. What about the SUP, can it still work using HTTP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778368d0-1054-678c-4d74-5dce1b5826c8
* Version Independent ID: aaac7308-66e6-66f0-8248-14e1505c11a6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/plan-cloud-management-gateway)
* Content Source: [sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Service: **unspecified**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the question @MartinRain. Just to clarify, in 1802 the MP only needs to be HTTPS for use with CMG, not in general. As for the SUP, we certainly recommend it is HTTPS as a security best practice. But there is no requirement for it to be HTTPS in this scenario. The CMG (via the CMG connection point) must have an HTTPS MP for client authentication, but HTTPS with the SUP is just to secure the communication channel. I think this is clear in the [Ports and data flow](https://docs.microsoft.com/sccm/core/clients/manage/cmg/plan-cloud-management-gateway#ports-and-data-flow) section, so I'm going to close the issue. Reopen it if you think something is missing from the article.
