### ISSUE TITLE
More Information Would Be Helpful

### ISSUE THREAD

**Issue by ajacks88** [MicrosoftDocs/SCCMdocs#492]
Please provide documentation as to:

* how the script is actually ran on the client. Is this PS Remoting? Is this a client action? If a client action, how is the client notified, and how often? Where is the script stored locally on the client? Are there log files associated with a script that you run?

I've seen non-Microsoft blog post about these topics in greater detail than what is available from Microsoft. It would really be nice to have that information be officially documented here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c7d1db7-6812-ff3c-9aac-0f55800ed665
* Version Independent ID: a4499cf7-ed5a-710c-66e0-005563b9c015
* Content: [Create and run scripts - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/create-deploy-scripts#feedback)
* Content Source: [sccm/apps/deploy-use/create-deploy-scripts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/create-deploy-scripts.md)
* Service: **unspecified**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ajacks88. I understand your questions, but could you please elaborate a bit more on how you would use this detailed information? Is it just a curiosity, or does it help you meet some business requirement?

**Comment by ajacks88** [comment]
Thanks for the quick reply!

It's our standard practice to have a knowledge base article on pretty much everything. We are just about to upgrade our production environment of SCCM to 1802, and are starting to look into how to use the new Scripts feature in our test environment. The normal procedure for the KB article is to explain how to use the feature, and how to troubleshoot it. The documentation that is already posted is great at explaining how to use the feature, but it really doesn't explain how to troubleshoot it at all. Since it is SCCM I assume there are log files associated with this feature, but I cannot seem to find a Microsoft article documenting what those log files are, or where they are located. I checked this article (https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/log-files) but didn't seem any reference to a log file specifically for this feature.

Another question our group had was if this feature just used client communication, or if it was powershell remote being initiated by SCCM. I've found various blog post that explain it using client notifications and caches the scripts locally before the client runs them, which is great! I just was wondering if there is a document already out there that details how this feature works in terms of how the clients receive notice they should be running a script, or if not, that information could be added to this article.

Hope that helps, thanks for any advice you can give!

**Comment by alex-x-st** [comment]
I've figured out logs on client side in folder C:\Windows\CCM\Logs
DataTransferService.log
Scripts.log
StateMessage.log

Found Script GUID records in the logs.

**Comment by mestew** [comment]
@ajacks88 I recently added information about log files for this. The changes should be [in the new log file section](https://docs.microsoft.com/sccm/apps/deploy-use/create-deploy-scripts#log-files) in the next day or so.
I have also created a backlog documentation item about adding additional troubleshooting information.

**Comment by ajacks88** [comment]
@mestew Thank you for filling up on this one!

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
