### ISSUE TITLE
/NoUserInput Parameter not working as described 

### ISSUE THREAD

**Issue by karthic9388** [MicrosoftDocs/SCCMdocs#501]
Hi  am trying to install SCCM CB with ConfigMgrAutoSave.ini files setup

i used below option

Setup.exe /Script ConfigMgrAutoSave.ini /NoUserInput

setup is completing with out any error but i am not getting Display wizard like progress bar.

as per the link given when we use /NopuserInput this  only will disable User input but it will display setup wizard. but i am not getting display wizard. kindly help me.

kindly help me in getting the Display wizard with our user input.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a393419-2d34-ebba-9482-7c988797f5c9
* Version Independent ID: 95f509c1-5494-7f40-6392-6f7f8988dd2e
* Content: [Setup command-line options - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/command-line-options-for-setup)
* Content Source: [sccm/core/servers/deploy/install/command-line-options-for-setup.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/command-line-options-for-setup.md)
* Service: **unspecified**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums]( https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this as it doesn't appear at this time to be an issue with the documentation.
