### ISSUE TITLE
Conflicting statements about multicast support

### ISSUE THREAD

**Issue by LeviStevens** [MicrosoftDocs/SCCMdocs#502]
Under Windows Server 2008 R2 you say "It is still supported for the distribution point site system role, including pull-distribution points and for PXE and multicast." but then in the bullet point you say "Distribution points on this OS do not support Multicast".  So which is it, do you support multicast or not? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dc0edfd-7799-9246-2e23-f202e31517f9
* Version Independent ID: 8c401426-fcf8-79a9-08fa-95a724b5756d
* Content: [Supported site system servers - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/supported-operating-systems-for-site-system-servers#windows-server-2008-r2-with-sp1-x64-standard-enterprise-and-datacenter)
* Content Source: [sccm/core/plan-design/configs/supported-operating-systems-for-site-system-servers.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/supported-operating-systems-for-site-system-servers.md)
* Service: **unspecified**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @LeviStevens for calling this out. To further complicate, there are statements on the [Deprecated for site servers](https://docs.microsoft.com/sccm/core/plan-design/changes/deprecated/removed-and-deprecated-server#deprecated-server-operating-systems) article as well. I need to do some research on change history, and verify with engineering team.

**Comment by aczechowski** [comment]
I updated this with the 1806 content, which will publish soon. I'm closing this issue.
