### ISSUE TITLE
Please confirm Azure-AD Joined criteria for WSFB apps from ConfigMgr

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/SCCMdocs#503]
In this section https://docs.microsoft.com/en-us/sccm/apps/deploy-use/manage-apps-from-the-windows-store-for-business#deploying-online-apps-using-the-microsoft-store-for-business-with-pcs-that-run-the-configuration-manager-client the verbiage **PCs must be joined to Azure Active Directory in the same tenant where you registered the Microsoft Store for Business as a management tool.** From my testing on a hybrid device with co-management enabled, I can select my WSFB licensed apps in the console, create an application, and deploy to hybrid (on-prem AD joined, configmgr co-managed, AAD registered) devices. The devices see the WSFB app in Software Center and can install it just like any other app.  I've tested side by side with an Azure AD Joined, Co-managed device and they behave the same with using Online and Offline WSFB/MS Store/*.AppXBundle packages (assuming that there are no Intune configuration or group policies preventing access to the public or private stores.  My testing has been on ConfigMgr 1802.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 755fdc0f-0098-7694-8373-154cb4f08dcc
* Version Independent ID: 91d19b28-f30f-dfe3-9f87-f6fcf95f2305
* Content: [Manage apps from the Microsoft Store for Business - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/manage-apps-from-the-windows-store-for-business#deploying-online-apps-using-the-microsoft-store-for-business-with-pcs-that-run-the-configuration-manager-client)
* Content Source: [sccm/apps/deploy-use/manage-apps-from-the-windows-store-for-business.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/manage-apps-from-the-windows-store-for-business.md)
* Service: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @AdamGrossTX. To confirm - you're asking about the first part of the requirement (joined to AAD), not the second part (in the same tenant)? I think the point of this statement is primarily for that second part, but I'm checking with some folks to clarify.

**Comment by AdamGrossTX** [comment]
Yes. Just the part about AAD Joined. Thanks!

**Comment by AdamGrossTX** [comment]
I think I missed the part above where it's written out more clearly. 
https://docs.microsoft.com/en-us/sccm/apps/deploy-use/manage-apps-from-the-windows-store-for-business#online-and-offline-apps

> Online - This license type requires users and devices to connect to the store to get an app and its license. Windows 10 devices must be Azure Active Directory domain-joined.

Either way, It would be great to have clarification on why it appears to function for non AAD Joined devices.

Thanks!

**Comment by tieronebanter** [comment]
me too!!  It appears you've confirmed that Hybrid On-prem joined and AAD registered devices are supported for Online WSFB app management through ConfigMgr.

**Comment by nhogarth86** [comment]
In the section where it says "Devices must be joined to Azure AD", Hybrid Azure AD joined does work as well as noted by tieronebanter

**Comment by AdamGrossTX** [comment]
@aczechowski I just set this up in my lab last night. Nothing is Azure AD joined or registered. I simply have to sign in with my work or school account and I’m able to install the apps. This has been a while, but I wonder if you were able to get any extra info about the requirements for this.

**Comment by aczechowski** [comment]
I made revisions to this article with your feedback, the changes will publish live tomorrow.
