### ISSUE TITLE
Custom Client Settings and Hardware Inventory Class Merge

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#504]
Migrated from [UserVoice](https://configurationmanager.uservoice.com/forums/300492-ideas/suggestions/17740330-custom-client-settings-and-hardware-inventory-clas)

> Request is to Add some more details to explain the behaviour with respect to multiple custom client setting and Hardware Inventory merge on this page. 

> if we could just mention, not checking a class in a custom client setting with highest priority doesn’t mean the class would not be inventoried. Not checking a class doesn’t mean disabled. it’s like not configured. So if someone has to not inventory a particular class on most of the machine except few. Then they have to work around with disabling the class on default client setting and then create a specific custom client setting for just few machine where we need to enable the class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4c8ea0b-1432-a243-b45c-ee7311718f39
* Version Independent ID: b801d9a9-76aa-e727-a678-a906f47a25d7
* Content: [Configure hardware inventory - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/inventory/configure-hardware-inventory)
* Content Source: [sccm/core/clients/manage/inventory/configure-hardware-inventory.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/inventory/configure-hardware-inventory.md)
* Service: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by jocasti** [comment]
@aczechowski I wrote something up for this issue and created  Reference PR #983. Any additional input/suggestions you have would be much appreciated, Thanks.
