### ISSUE TITLE
Improve documentation for OMS connector setup procedure

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#506]
Migrated from [UserVoice](https://configurationmanager.uservoice.com/forums/300492-ideas/suggestions/19452463-improve-documentation-for-oms-connector-setup-proc)

> If you walk through the documentation for setting up the OMS connector, the guide is a little vague, it covers the connection – assuming that all went perfect and connected with out a problem. 
> I’m following the guides as outlined here https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-sccm#provide-configuration-manager-with-permissions-to-oms
>
>Step 3 > Step 4.. doesn’t cover the scenario where the azure subscription drop-downs are blank.
>
> Step 4 simply says “If you accomplished all the other procedures successfully”.. so what do you do when it doesn’t ?
> 
> It gives no indication on what to look for. I did find another guide from here https://gallery.technet.microsoft.com/Configure-OMS-Connection-9c9e6bc3, but this guide, page 10, states the application has not been properly granted access..
> 
> All in all very confusing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0cd8692-9d03-cd7c-71d6-a65494f91b17
* Version Independent ID: 3a8650ed-7a40-ace0-b1c7-cc6c3b7c54bc
* Content: [Sync data to OMS - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/sync-data-microsoft-operations-management-suite)
* Content Source: [sccm/core/clients/manage/sync-data-microsoft-operations-management-suite.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/sync-data-microsoft-operations-management-suite.md)
* Service: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by Graygote** [comment]
Couldn't agree more! The documentation is spread all over the place; and, depending which document you find, you get conflicting pieces of information, outdated screenshots, references to settings that no longer exist. Whomever is in charge of editing, creating, proof-reading, and keeping these documents up-to-date there at Microsoft is failing miserably at their job.

**Comment by aczechowski** [comment]
@Graygote thank you for your feedback. I agree this article needs work, and it is on my list of articles to review and update. I recently revised the related [Configure Azure services article](https://docs.microsoft.com/sccm/core/servers/deploy/configure/azure-services-wizard), so I suggest starting there. 

Also, please take a moment to review the Microsoft Open Source Code of Conduct, which outlines the expectations for community interactions in and around docs.microsoft.com. It is designed to help "provide a welcoming and inspiring community for all."

**Comment by aczechowski** [comment]
@mestew is working with a colleague in Azure Monitoring to revamp this content. I'm closing this issue as we're tracking the work separately.
