### ISSUE TITLE
Change of Windows Server Edition supported?

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#509]
Migrated from [UserVoice](https://configurationmanager.uservoice.com/forums/300492-ideas/suggestions/31108930-change-of-windows-server-edition-supported)

> Please add a statement whether it is supported to cdhange the Windows Server Edition from Standard to Datacenter on an installed Site Server. This article already contains a list what cannot be changed after Installation, changin the Edition is nowhere mentioned. For a change of the SQL Server Edition a statement exists as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9070eb9b-0e5f-a877-e02e-2d1cea2a2b38
* Version Independent ID: df251762-f2d6-9f06-4fa9-ec5cea2cca0a
* Content: [Site prerequisites - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/site-and-site-system-prerequisites#feedback)
* Content Source: [sccm/core/plan-design/configs/site-and-site-system-prerequisites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/site-and-site-system-prerequisites.md)
* Service: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by chiners68** [comment]
Is .NET framework 3.5 not required for the Distribution Point? Im sure this was a prerequsite previously and a DP wont install without it.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
