### ISSUE TITLE
Pre-Deploy Software to User's Primary Device

### ISSUE THREAD

**Issue by jpoling1** [MicrosoftDocs/SCCMdocs#513]
Can a section be added to describe what "Pre-Deploy Software to User's Primary Device" actually does?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58bf38ca-c7d6-50e3-9a88-32313f789d62
* Version Independent ID: 393cd01c-1b5f-086a-33cc-28a86a26e303
* Content: [Deploy applications - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/deploy-applications#specify-deployment-settings)
* Content Source: [sccm/apps/deploy-use/deploy-applications.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/deploy-applications.md)
* Service: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jpoling1 for filing this
Reference [Twitter thread](https://twitter.com/AaronCzechowski/status/994295189542850560)

**Comment by aczechowski** [comment]
Fixed this while making some updates to this article for 1806 content. It will publish soon with that release. I'm closing this issue for now.
