### ISSUE TITLE
SDK Documentation ?

### ISSUE THREAD

**Issue by MarkWWest** [MicrosoftDocs/SCCMdocs#516]
Is there any documentation for the new Scripts feature in SCCM in the SDK?  I have been unable to find any information on the server wmi class or how one might run an approved script against a device via C#    Specifically the new Scripts Featured added to SCCM CB 1802.

**Comment by aczechowski** [comment]
@MarkWWest are you asking about a specific API? To what are you referring, "for this new feature"?

**Comment by MarkWWest** [comment]
Yes, I was just wondering if the SCCM SDK document was updated with CB 1802 to include references to managing the new scripts feature via Microsoft.ConfigurationManagement.ManagementProvider
Feature described here:
https://docs.microsoft.com/en-us/sccm/apps/deploy-use/create-deploy-scripts

I was attempting to find a C# ... the class associated with these Script objects , methods, properties, etc. for interfacing this new feature.  I was unable to locate any reference here:
https://docs.microsoft.com/en-us/sccm/develop/osd/operating-system-deployment-computer-management

Any assistance would be appreciated.

**Comment by kalyangit** [comment]
Hi, we are also looking for SDK documentation to use script feature in C#. Can you update if its added ?

**Comment by kalyangit** [comment]
@MarkWWest are you able to share if you found any reference ?

**Comment by MarkWWest** [comment]
@kalyangit , I never found any reference.  The integration points were not documented so i went a different direction.  Though i would revisit this again if the documentation became available.

**Comment by aczechowski** [comment]
At this time, I don't think there are any APIs available. So I suggest filing [product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback). 

I'll keep this issue open for now as I still want to verify.

**Comment by aczechowski** [comment]
There are PowerShell cmdlets that you can use, for example: [Get-CMScript](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmscript?view=sccm-ps)
For more cmdlets, see the related links section of that article
