### ISSUE TITLE
Please Bold EnableSQM Note concerning 1802 and/or add note to examples too

### ISSUE THREAD

**Issue by g4m3c4ck** [MicrosoftDocs/SCCMdocs#517]
It is not very apparent at first glance, will cause failure with 1802 install source and examples still have the parameter in the code.

Note: Starting in Configuration Manager version 1802 the CEIP feature is removed from the product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6431e1d-681e-fcfb-8066-8491491723a8
* Version Independent ID: ba71437e-ac4b-b1f4-573b-04c397249b3a
* Content: [Install console - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/install-consoles)
* Content Source: [sccm/core/servers/deploy/install/install-consoles.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/install-consoles.md)
* Service: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @g4m3c4ck for filing this. Agreed that it shouldn't be in the examples, good catch. My understanding was that it is ignored by consolesetup, thus wasn't as heavily highlighted. I'm confirming with the engineering team.

**Comment by pugmohone** [comment]
So what is the actual command to use with SCCM?  I have tried consolesetup.exe /q TargetDir="C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\bin" DefaultSiteServerName=XXXXXX.XXXX.com and get immediate failures when pushing out to new PC's.

**Comment by aczechowski** [comment]
Hi @pugmohone, sorry for the difficulties. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

Sharing the installation log will help all of those options troubleshoot. If there is an issue with the examples in this article, or some clarification that would help others, please file another issue on this article to improve the documentation.

**Comment by TheMexico** [comment]
@pugmohone

Funny you post about this the just other day. I'm working on it today.

I found there is no need to add `Microsoft Configuration Manager\AdminConsole\bin` to the install path. Only specify the parent directory. 

Specifying %public% as a test it happen to create the "MS Config\AdminConsole" on the all users desktop.

**Comment by TheMexico** [comment]
I fibbed. Really odd false-positive i can re-created.

**Comment by JakeMoe** [comment]
Would be good to put a note in under /q as well, since it says EnableSQM is required; that's what I was mainly interested in, how to deploy it to our IT department via SCCM, so I read the other parameters just to find the syntax.

**Comment by pugmohone** [comment]
We upgraded to 1802 and I was able to use this command:

consolesetup.exe /q TargetDir="C:\Program Files (x86)\Microsoft Configuration Manager\AdminConsole\" DefaultSiteServerName=SCCMSERVER.DOMAIN.com

SCCM Application Detection:
{F3CF82B1-A953-4BAC-9885-4215168FDB90}

**Comment by aczechowski** [comment]
To everyone subscribed to this issue, @ChadSimmons submitted pull request #736 to address this. Before I sign off that change, I wanted to highlight it for others to comment. (Click the link to the pull request, then switch to the Files tab to view the explicit changes. Then make comments on the Conversation tab.) Thanks! Yay, community! 👏

**Comment by aczechowski** [comment]
I should have noted: I'll accept feedback until Tuesday, 14 August. Otherwise I'll sign-off Chad's pull request.

**Comment by aczechowski** [comment]
I signed off on pull request #736, so I'm closing this issue. The update is expected to publish by midday tomorrow. 
Thanks to everyone for your feedback and input on this!
