### ISSUE TITLE
Application Pool Private Memory limit unclear

### ISSUE THREAD

**Issue by aydeisen** [MicrosoftDocs/SCCMdocs#519]
In this article, it mentions this bullet for application pools:
> Increase the WsusPool Private Memory limit x4 times, or set to 0 (unlimited)

What is value supposed to be 4x of?  Physical memory?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d69fe2fa-2d4c-e3fe-ed03-3fae067bca3b
* Version Independent ID: 9b781cea-18dc-79af-0158-59abc861b601
* Content: [Plan for software updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/plan-design/plan-for-software-updates#capacity-planning-recommendations-for-software-updates)
* Content Source: [sccm/sum/plan-design/plan-for-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/plan-design/plan-for-software-updates.md)
* Service: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @aydeisen, sorry for the confusion. I agree that we can better clarify this information. 

My understanding is that means to increase the current limit by four times. So if the current value is 1,000,000 KB then increase it to 4,000,000. [This blog post](https://blogs.technet.microsoft.com/configurationmgr/2015/03/23/configmgr-2012-support-tip-wsus-sync-fails-with-http-503-errors/) from Microsoft Support has some additional detail on this setting that you might find useful in the short term.

**Comment by aydeisen** [comment]
@azcechowski: thanks for the response.  What your saying is inconsistent with [this document](https://support.microsoft.com/en-us/help/4025764/how-to-tr), which says to set the private memory limit to 4-8 GB, as well as [this document](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc72) that it links to, saying the private memory limit should be less than 60% of the physical memory. 

Which guidance is correct?

**Comment by aczechowski** [comment]
Relying on the blog post that I shared the default Private Memory Limit is 1,843,200 KB, which is a little less than 1.8 GB. So four times that is just over 7 GB. 

I think the key thing here is that with any performance guidance, your mileage may vary depending upon hardware, usage, and other variables. 

I need to check with our performance and software updates feature teams to further understand how we can better clarify this guidance for SCCM customers.

**Comment by aczechowski** [comment]
I checked in changes for this issue which will publish with the 1806 content in a few weeks. I borrowed some of the language from the above conversation, and linked out to the related blog post and support article. I'm closing this issue.
