### ISSUE TITLE
Enable the deployment after this rule is run:

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/SCCMdocs#520]
The document says:

> Enable the deployment after this rule is run: Specify whether to enable the software update deployment after the ADR runs. Regarding this specification, consider the following things:

> o When you enable the deployment, the updates that meet the rule's defined criteria are added to a software update group. The software update content is downloaded as necessary. The content is copied to the specified distribution points and the updates are deployed to the clients in the target collection.

> o When you do not enable the deployment, the updates that meet the rule's defined criteria are added to a software update group. The software updates deployment policy is configured. **However, the updates are not downloaded or deployed to clients.** This situation provides time to prepare to deploy the updates, verify the updates that meet the criteria are adequate, and then enable the deployment at a later time.

When an ADR runs with the deployment not enabled, however it still downloads the updates (documentation says it shouldn't) and the deployment is disabled so it won't deploy to clients (this is as expected).
It should say something similar to 

> When you do not enable the deployment, the updates that meet the rule's defined criteria are added to a software update group. The software update content is downloaded as necessary. The content is copied to the specified distribution points and a disabled deployment is created on the Software Update Group to prevent the updates from being deployed to clients. This situation provides time to prepare to deploy the updates, verify the updates that meet the criteria are adequate, and then enable the deployment on the software update group at a later time.

You can see in the rulengine.log that after an ADR is created with a deployment not enabled, it downloads the updates to the deployment package. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc1bc8d-2e4b-650b-7644-84e5790e4630
* Version Independent ID: 9488c8c6-c912-1667-db02-f8a29f5c2023
* Content: [Automatically deploy software updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/automatically-deploy-software-updates)
* Content Source: [sccm/sum/deploy-use/automatically-deploy-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/automatically-deploy-software-updates.md)
* Service: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @nhogarth86 I confirmed with the engineering team that we need to update this article. I'll work on revising it soon.

**Comment by aczechowski** [comment]
I checked in changes for this issue which will publish with the 1806 content in a few weeks. I'm closing this issue.
