### ISSUE TITLE
How is Application Enforcement actually done?

### ISSUE THREAD

**Issue by JB3787** [MicrosoftDocs/SCCMdocs#521]
The very last sentence on this page states that Managed Installer is handled by Applocker and "all enforcement happens with Application". This doesn't make sense, is there supposed to be more to the sentence?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2082f138-28f2-d410-d607-4fcb1ddf12db
* Version Independent ID: 7ce37b4e-9330-73d9-f3bb-2f0af4ec6073
* Content: [How to manage Windows Device Guard - Configuration Manager](https://docs.microsoft.com/en-au/sccm/protect/deploy-use/use-device-guard-with-configuration-manager)
* Content Source: [sccm/protect/deploy-use/use-device-guard-with-configuration-manager.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/use-device-guard-with-configuration-manager.md)
* Service: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @JB3787, I agree that ends abruptly. Let me check with the feature team to understand what that should be stating.

**Comment by aczechowski** [comment]
The last bullet should read:

- Setting up Configuration Manager as a Managed Installer on client PCs uses AppLocker policy. AppLocker is only used to identify Managed Installers and all enforcement happens with *Windows Defender Application Control*.

**Comment by JB3787** [comment]
Thanks for the clarification Aaron, that makes a lot more sense. I don't suppose you'd know if there is any documentation available giving a more in-depth description of how SCCM utilises both Applocker & WDAC?

**Comment by aczechowski** [comment]
Closing this issue as it will be fixed later today with the linked pull request
