### ISSUE TITLE
Supported Active Directory domains for System Center Configuration Manager page update

### ISSUE THREAD

**Issue by JacquesB4** [MicrosoftDocs/SCCMdocs#524]
Support documentation page at https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/support-for-active-directory-domains do not state any requirements for forest levels.  In the previous feedback system a question was posted about this.  It was answered by a Microsoft person stating which forest levels are supported and why, but the article was not updated to reflect the forest functional level requirements.  Please update the document to show both forest and domain level requirements so that it is not left open to assumptions.

**Comment by aczechowski** [comment]
Thanks @JacquesB4 for the question. I'm checking on the answer to this.

**Comment by aczechowski** [comment]
This is fixed: 

> Configuration Manager supports domain and forest functional level of Windows Server 2008 R2 or later.
