### ISSUE TITLE
HTTPS only as of build 1710

### ISSUE THREAD

**Issue by Vallentyne** [MicrosoftDocs/SCCMdocs#525]
I think the option to use HTTP for transfers was removed, it's now only HTTPS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd7a196d-4829-4b01-0bc0-8c14fd52dc1a
* Version Independent ID: db302fc5-0610-b270-0202-16fb4606a588
* Content: [Prepare Windows PE peer cache to reduce WAN traffic - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/get-started/prepare-windows-pe-peer-cache-to-reduce-wan-traffic)
* Content Source: [sccm/osd/get-started/prepare-windows-pe-peer-cache-to-reduce-wan-traffic.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/get-started/prepare-windows-pe-peer-cache-to-reduce-wan-traffic.md)
* Service: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Vallentyne, I've had conversations with the feature team about some broader changes to this article in general.

**Comment by Anoni-Mouse** [comment]
Are self signed certificates OK or does the client have to have a certificate from an internal PKI?

**Comment by aczechowski** [comment]
@Anoni-Mouse I don't think a client certificate is required for peer cache.

**Comment by aczechowski** [comment]
I'm resolving this issue in part because we moved repositories, but also because I'm going to track this work via an internal work item.

(internal reference 2838731)
