### ISSUE TITLE
Management Task missing from documentation

### ISSUE THREAD

**Issue by MOn-STEr** [MicrosoftDocs/SCCMdocs#528]
There is a MT named "Delete Aged Console Connection Data" which appears to be not documented here. Its description says "This task deletes aged console connection data from the site database."

It is present at least in 1706 and 1802.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73746b8f-0bb3-a02c-fe91-85395fb33bdd
* Version Independent ID: a7cee2bc-0b6e-e740-238b-9267c3cae370
* Content: [Reference for maintenance tasks - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/reference-for-maintenance-tasks#feedback)
* Content Source: [sccm/core/servers/manage/reference-for-maintenance-tasks.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/reference-for-maintenance-tasks.md)
* Service: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @MOn-STEr. Related to issue #486. I'm working with folks from Microsoft Premier to review and refresh the maintenance articles.

**Comment by aczechowski** [comment]
I revised this article, the change should publish live tomorrow
