### ISSUE TITLE
location of updates is incorrect

### ISSUE THREAD

**Issue by asjimene** [MicrosoftDocs/SCCMdocs#536]
Second Paragraph:
To get the update for version 1802, you must use a service connection point site system role at the top-level site of your hierarchy. This can be in online or offline mode. After your hierarchy downloads the update package from Microsoft, you can find it in the console under Administration > Overview > Cloud Services > Updates and Servicing.

Should be:
To get the update for version 1802, you must use a service connection point site system role at the top-level site of your hierarchy. This can be in online or offline mode. After your hierarchy downloads the update package from Microsoft, you can find it in the console under Administration > Overview > Updates and Servicing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca18d72d-ad7b-0862-f17b-df1f4c66b562
* Version Independent ID: 2cad51ef-780d-a5b6-6502-b8c8c8cddbcd
* Content: [Checklist for 1802 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/checklist-for-installing-update-1802)
* Content Source: [sccm/core/servers/manage/checklist-for-installing-update-1802.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/checklist-for-installing-update-1802.md)
* Service: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I just updated this language in the code, as well as in the section on running the setup prereq checker. It should publish live on Monday about midday Pacific time.
