### ISSUE TITLE
Client Peer Cache broken?

### ISSUE THREAD

**Issue by ptreptau** [MicrosoftDocs/SCCMdocs#539]
The setting "Allow clients to share content with other clients on the same subnet" seems to have disappeared in application, package and update definitions. Is this now enabled by default?

Also, I understand that PeerCache can be used in conjunction with BranchCache, but nowhere is stated what content delivery mechanism is used, when both are concurrently enabled.

BranchCache would be the better option for updates (due to no content invalidation and block-based replication for larger packages), however PeerCache is more suitable for traditional content delivery (because of lower cache store requirements).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29b8c8d-60fa-4403-29a7-8e7c61b2f638
* Version Independent ID: c7610ca2-5607-d1fe-f629-9d0614a26569
* Content: [Client Peer Cache - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/client-peer-cache)
* Content Source: [sccm/core/plan-design/hierarchy/client-peer-cache.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/client-peer-cache.md)
* Service: **unspecified**
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ptreptau for submitting this issue. I'm checking with the engineering team about that setting; I'm also not seeing it. But we note it in various other articles.

Regarding the interplay between various technologies, see the last bullet in the overview of the [Client Peer Cache](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/client-peer-cache#overview) article. However, it raises the point that we should do a better job of highlighting that point in other areas for better visibility.

**Comment by aczechowski** [comment]
We removed the setting in 1802. BranchCache is now always enabled on clients, and they use it if the DP is BranchCache-enabled. I'll track updates to the various docs via this issue.

**Comment by aczechowski** [comment]
Cross-reference internal doc bug 511475 for related point. Starting in 1802 clients can share large policies if the client and MPs are enabled for BranchCache.

**Comment by aczechowski** [comment]
Need to note that clients need to be upgraded to 1802 as well.

**Comment by aczechowski** [comment]
I revised this article for 1806 release, to include this information. The content should publish soon. I'm closing this issue.
