### ISSUE TITLE
new-cmpackagedeployment missing examples and parameter explanation

### ISSUE THREAD

**Issue by Stephanevg** [MicrosoftDocs/SCCMdocs#540]
The New-CMPackageDeployment cmdlet seems to be missing examples.
The description of each of the parameters is also missing

See here --> https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmpackagedeployment?view=sccm-ps

**Comment by aczechowski** [comment]
Thanks @Stephanevg for filing this issue. We currently have a backlog on SDK content, and are looking at ways to mitigate that going forward.

**Comment by 1RedOne** [comment]
Hey Adam, it's 🎃 Hacktober!  Can you point us at a location where we can fix this and other CM help?

**Comment by Stephanevg** [comment]
Is thre somehwere we can help @aczechowski : Is for example the code avaialble somewhere on github so we can have a look at it?

Otherwise, I agree with @1RedOne anything you can give us for `hacktober`? :)

**Comment by mumian** [comment]
I have included some samples.

**Comment by aczechowski** [comment]
Thanks @mumian, I'm closing this issue. 
@Stephanevg if after the updates publish you have additional comments, feedback is now enabled on all SCCM PowerShell content.
