### ISSUE TITLE
Update Docs for new Builds of MDT/ADK/OS Versions etc

### ISSUE THREAD

**Issue by excelsi84** [MicrosoftDocs/SCCMdocs#541]
Please update the Docs for the new Builds and Versions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cffaa4a7-f102-e9a1-bf37-ba43d4d12225
* Version Independent ID: 14bb9ea7-e9bf-c8b6-92b7-bc4b9502eab9
* Content: [What’s new in MDT 2013 Guide - Microsoft Deployment Toolkit](https://docs.microsoft.com/en-us/sccm/mdt/whats-new-in-mdt)
* Content Source: [sccm/mdt/whats-new-in-mdt.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdt/whats-new-in-mdt.md)
* Service: **unspecified**
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @excelsi84, I'm already working with the feature team on some initial updated content for MDT.

**Comment by aczechowski** [comment]
I worked with the feature PM to make a few revisions to the MDT content. We decided to remove the "what's new" article altogether, and focus the updated content in the [Release Notes](https://docs.microsoft.com/en-us/sccm/mdt/release-notes). I also tweaked the [MDT landing page](https://docs.microsoft.com/en-us/sccm/mdt/), most notably adding a link to the download. I'm closing this issue.
