### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by bemorg** [MicrosoftDocs/SCCMdocs#544]
According to https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/deprecated/removed-and-deprecated-client Linux/Unix clients are deprecated with Current Branch.  This documentation should be updated to reflect the new changes so customers don't have to multiple places to get all the current information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 841982ac-d9da-06c2-1c63-a9c3e75db247
* Version Independent ID: 8d2a6d8a-e0ca-16e1-a208-7e35d79f673a
* Content: [Manage Linux and UNIX clients - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/manage-clients-for-linux-and-unix-servers)
* Content Source: [sccm/core/clients/manage/manage-clients-for-linux-and-unix-servers.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/manage-clients-for-linux-and-unix-servers.md)
* Service: **unspecified**
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @bemorg for the suggestion. I'll look at how we can better connect this content.

**Comment by ChrisKibble** [comment]
Looks like this is complete @aczechowski , the page referenced now states:

> Starting in version 1902, Configuration Manager doesn't support Linux or UNIX clients.

at the top.  Commenting so you can close out and shrink the Issues list a bit :-)
