### ISSUE TITLE
Is there a limit for WSUS shared database?

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#545]
There is a blurb in this article about sharing the WSUS database for multiple SUPs in a primary site, but doesn't provide any guidance for how many, any limitations, and what possible performance concerns. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d69fe2fa-2d4c-e3fe-ed03-3fae067bca3b
* Version Independent ID: 9b781cea-18dc-79af-0158-59abc861b601
* Content: [Plan for software updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/plan-design/plan-for-software-updates#feedback)
* Content Source: [sccm/sum/plan-design/plan-for-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/plan-design/plan-for-software-updates.md)
* Service: **unspecified**
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Don't remember what initiated this issue. Doing a large review of this content for 1806, made some revisions in this context. Ultimately the shared database is just to improve performance when switching SUPs on clients. The SUP scale numbers still apply. Thus I'm closing this issue.

**Comment by mikemagarelli** [comment]
Hi. I'm looking for clarification as to whether there is a hard limit on the number of SUPs that can use a shared SUSDB. There are a number of MS documents that allude to this, but none that are concise. I'm happy to provide links / examples. Can this be clarified in the documentation, please? Thanks! -Mike

**Comment by j-dahl7** [comment]
As @mikemagarelli mentioned, I, too, would like clarification on this.

**Comment by aczechowski** [comment]
There are two references:

- https://docs.microsoft.com/previous-versions/system-center/system-center-2012-R2/hh237369(v=technet.10)

    > The maximum number of WSUS servers that can be configured as part of a network load balancing cluster is four.

- https://techcommunity.microsoft.com/t5/configuration-manager-archive/how-to-implement-a-shared-susdb-for-configuration-manager/ba-p/274103

    > You can have up to 4 front end WSUS servers sharing a SUSDB.

I confirmed that this is still relevant guidance.

This [SCCMDocs repository is no longer actively used](https://github.com/MicrosoftDocs/SCCMdocs/issues/2327), so if you want something about this added to the current ConfigMgr documentation, please file feedback in the current repository: memdocs. For more info, see https://docs.microsoft.com/mem/use-docs#about-feedback
