### ISSUE TITLE
Incorrect Certificate Template Information

### ISSUE THREAD

**Issue by monkeyskullfire** [MicrosoftDocs/SCCMdocs#549]
This page states that Windows Server 2003 Enterprise certificates are still required when that is not in fact the case.  Please update this page to include the information in https://docs.microsoft.com/en-us/sccm/core/plan-design/network/cng-certificates-overview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e6c9b24-f28e-464b-d625-53b7453082b9
* Version Independent ID: 1a657226-b1e7-e14f-656c-dee37cab5beb
* Content: [PKI certificate requirements - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/network/pki-certificate-requirements#feedback)
* Content Source: [sccm/core/plan-design/network/pki-certificate-requirements.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/network/pki-certificate-requirements.md)
* Service: **unspecified**
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by poortom1004** [comment]
Bump.  This article still does not reflect accurate information about sccm current branch.  All supported version of sccm cb support v3 templates.

**Comment by kewljoe** [comment]
According to Configman Feedback site V3 is supported from 1710 onward, is this correct?
https://configurationmanager.uservoice.com/forums/300492-ideas/suggestions/17451757-support-v3-and-newer-certificate-templates-for-htt#{toggle_previous_statuses}

**Comment by aczechowski** [comment]
Yes, see [CNG Certificates Overview](https://docs.microsoft.com/sccm/core/plan-design/network/cng-certificates-overview).

The article referenced in this issue hasn't been reviewed for a long time.
