### ISSUE TITLE
Device Category Rule

### ISSUE THREAD

**Issue by alygcode** [MicrosoftDocs/SCCMdocs#552]
You can make management of your devices easier by associating device categories by associating device categories with the device collections....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 669ca4f9-5d5d-acd7-cdbe-7b3127bb4a58
* Version Independent ID: c2e872b3-4faf-820c-c0f1-84963955f9d5
* Content: [Create collections - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/collections/create-collections#feedback)
* Content Source: [sccm/core/clients/manage/collections/create-collections.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/collections/create-collections.md)
* Service: **unspecified**
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback @alygcode. The topic of device categories on collections is covered in the separate article, [Automatically categorize devices into collections](https://docs.microsoft.com/sccm/core/clients/manage/collections/automatically-categorize-devices-into-collections). Fair feedback that there should be some mention of that on this page with a reference.

**Comment by aczechowski** [comment]
The issue is closed because I revised the article. It should publish live shortly.
