### ISSUE TITLE
Collection Evaluation description

### ISSUE THREAD

**Issue by jpoling1** [MicrosoftDocs/SCCMdocs#553]
I often find I need to explain to our team that collections - how they evaluate, how many we have, how the membership rules are constructed, etc. - impact the overall performance of ConfigMgr.  Would it be possible to have a summary of how the collection evaluator works?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b4224c5-6cb2-0f7d-5d48-fa8b28300e5b
* Version Independent ID: a79373c3-8801-6c23-87cf-4f96ab180c70
* Content: [Collections introduction - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/collections/introduction-to-collections)
* Content Source: [sccm/core/clients/manage/collections/introduction-to-collections.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/collections/introduction-to-collections.md)
* Service: **unspecified**
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Sorry I didn't catch this earlier, this is a dupe: https://github.com/MicrosoftDocs/SCCMdocs/issues/1237
