### ISSUE TITLE
Operating System Installation Package

### ISSUE THREAD

**Issue by strats85** [MicrosoftDocs/SCCMdocs#555]
In the console for Configuration Manager this object is named Operating System Upgrade Package. They are the same object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70f4fb1c-8d88-ff2f-813a-3f2e7a9a6cfc
* Version Independent ID: df2889fa-04c0-163b-0bae-050990930c81
* Content: [OSD infrastructure requirements - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/plan-design/infrastructure-requirements-for-operating-system-deployment)
* Content Source: [sccm/osd/plan-design/infrastructure-requirements-for-operating-system-deployment.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/plan-design/infrastructure-requirements-for-operating-system-deployment.md)
* Service: **unspecified**
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I fixed this at some point along the way, so closing
