### ISSUE TITLE
Do not automatically upgrade superseded applications is not for Required deployments

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#557]
[Do not automatically upgrade superseded applications](https://docs.microsoft.com/sccm/core/plan-design/changes/whats-new-in-version-1802#do-not-automatically-upgrade-superseded-applications) option is only for Available deployments, targeted to a device collection, and for an application with a superseding relationship. 

Also update the note for this option under [Specify deployment settings](https://docs.microsoft.com/sccm/apps/deploy-use/deploy-applications#specify-deployment-settings).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4b8caa-0b30-fba6-c031-d08b2facd201
* Version Independent ID: b0c6c951-511b-5920-8e24-656b6dc53ab0
* Content: [New version 1802 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/whats-new-in-version-1802#feedback)
* Content Source: [sccm/core/plan-design/changes/whats-new-in-version-1802.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/changes/whats-new-in-version-1802.md)
* Service: **unspecified**
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by ChrisKibble** [comment]
Looks like this is fixed in #682 and #689.
