### ISSUE TITLE
What do customers do that already deployed CMG before 1802 and ARM was not avaialble

### ISSUE THREAD

**Issue by RobG-MSFT** [MicrosoftDocs/SCCMdocs#558]
what about customers that have already deployed CMG before 1802.  Do they need to redeploy CMG for ARM or can they use the existing configuration?
what is the best method to migrate / move their existing deployemnt to the new ARM method?
If they move to ARM are they going to lose control of all internet based clients once the original CMG / Cloud Management Point is recofigured to use ARM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fb371d2-b1f1-68ca-ed95-abf37e3ecf28
* Version Independent ID: cd7fc055-b430-3a4a-1002-c69087f30714
* Content: [Set up cloud management gateway - Configuraton Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/setup-cloud-management-gateway)
* Content Source: [sccm/core/clients/manage/cmg/setup-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/setup-cloud-management-gateway.md)
* Service: **unspecified**
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @RobG-MSFT, sorry you didn't find this information. There is a section at the bottom of this article on how to [Modify a CMG](https://docs.microsoft.com/sccm/core/clients/manage/cmg/setup-cloud-management-gateway#modify-a-cmg) which includes guidance for this very scenario. I'm closing this issue; please reopen if you have any additional concerns with that content.
