### ISSUE TITLE
Devices on internet not connecting to the management point

### ISSUE THREAD

**Issue by gholland-inmar** [MicrosoftDocs/SCCMdocs#559]
We have been trying to complete setting up the cloud management point and the cloud distribution point for a few weeks now.
The cloud DP appears to be working fine. I've uploaded a program to test and see it on the server. So I think we are good there.
The problem is that my clients are not connecting to the MP.
The device is on the internet and it shows as being on the internet in the client location log.

![image](https://user-images.githubusercontent.com/17626020/40440411-fcc4845e-5e8b-11e8-82b6-d04e779739cd.png)

However, when I look in the SCCM console. The device doesn't show a connection to the MP. It has the gray and white x indicator.

![image](https://user-images.githubusercontent.com/17626020/40439811-165ae040-5e8a-11e8-9933-e3d8b05d457b.png)

Not sure if this is an indicator of an issue or not but when I reset ccmexec service.
I don't get the "Client is in Internet" message.
I just get the message: Domain joined client is in Unknown location. Default to internet to be conservative
But it doesn't indicate in the log that it is on the internet.

![image](https://user-images.githubusercontent.com/17626020/40440349-d07c7ab4-5e8b-11e8-9c60-10f76444556b.png)

Any ideas?

**Comment by aczechowski** [comment]
Thanks for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums]( https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
