### ISSUE TITLE
Clarify - Server authentication certificate issued by public provider - Section

### ISSUE THREAD

**Issue by nathanmaslin** [MicrosoftDocs/SCCMdocs#565]
Hi 

Can there be some clarity added on the above section please, it doesn't seem clear especially when it comes to certificates from a public provider

1) If the wizard extracts the CN from the certificate and then appends .cloudapp.net, what URL do the clients actually access? The way this documentation reads to me is the SCCM clients will be told to access, as per the provided example, GraniteFalls.CloudApp.net but the certificate is GraniteFalls.contoso.com, would that not cause a certificate miss match error? Is there a way to force it to the GraniteFalls.contoso.com URL to avoid the error?

2) How do the wildcards work, again the documentation says the wizard will extract the CN which is "*" how do you configure it to use a specific CN? Doesn't describe how to do that at all.

Thanks

Nathan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c095180-90a2-79c6-a7fb-6504cafbcfb6
* Version Independent ID: fb9c2930-b213-3eef-c7bb-c8f11ec97aca
* Content: [CMG Certificates](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway)
* Content Source: [sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md)
* Service: **unspecified**
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by nathanmaslin** [comment]
Hey @aczechoswki,

Thanks for the feedback but I'm still not quite clear on this topic, the way I am reading this is, no matter where the certificate comes from, the ConfigMgr client policy that's handed to the clients will also be granitefalls..cloudapp.net yet the CMG service will have a certificate with DNS SAN FQDN of granitefalls.contoso.com and my assumption would be that's going to cause a DNS Name mismatch error on the client or is there something that happens at the Azure layer that redirects it to the correct DNS name to prevent this? 

There is no information about how to change the ConfigMgr client configuration to the custom name either, it seems the wizard seems to do it all automatically which is fine, but it just seems like it's more geared towards using private certificates rather than public ones. 

Personally, I'd like to see two sections, one on how to configure CMG with private certificates and another for certificates from a public provider so it's clearer.

Thanks

 Nathan

**Comment by RobYork** [comment]
Any azure cloud service receives a cloudapp.net FQDN as standard. Unless you use an Internal CA you are unable to sign a certificate for a cloudapp FQDN.

The clients will communicate via the FQDN specified in the certificates subject name, hence why the DNS CNAME is required. In your example clients would access GraniteFalls.contoso.com

**Comment by aczechowski** [comment]
I added some additional language on this topic. I'm closing the issue. Please reopen with further detail if you think its needed.
