### ISSUE TITLE
Add limitation regarding site expansion

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#568]
Reference internal bug 498184. Adding a CAS to an existing standalone primary site fails when SQL AlwaysOn is in use. Need to add this as a [limitation](https://docs.microsoft.com/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database#limitations-and-known-issues).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53d1da83-d988-fb2b-82c5-fd9cf117cd42
* Version Independent ID: 2b1a3bd2-5116-1f21-c196-e3e5698a83c9
* Content: [SQL Server Always On - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database#feedback)
* Content Source: [sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md)
* Service: **unspecified**
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by pfurches** [comment]
Documentation is incorrect: It states that additional HA groups must be set to manual failover prior to 1610. This is incorrect. I just did and 1802 update and it required all SQL HA groups to match this configuration fore allowing the installation of HA to proceed.

SQL servers that host additional availability groups:
Prior to Configuration Manager version 1610, when an availability group on a SQL Server hosts one or more availability groups in addition to the group you use for Configuration Manager, each replica in each of those additional availability groups must have the following configurations set at the time you run Configuration Manager Setup or install an update for Configuration Manager:
Manual Failover
allow any read-only connection

**Comment by aczechowski** [comment]
Fixed with linked internal pull request. *Once merged*, this change should be live with the next daily publishing process. Right now that *should* be tomorrow (Wednesday, 22 August) around 11:00 Pacific time. I'm closing this issue.
