### ISSUE TITLE
How do clients determine whether they are considered on the Internet or Intranet?

### ISSUE THREAD

**Issue by bmilbauer** [MicrosoftDocs/SCCMdocs#571]
Would be nice to have a section in here explaining how SCCM clients determine whether they are considered on the internet in the context of internet-based client management, or a jump to another page with the explanation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bbbb304-1fa3-48c0-e4ad-1cba21d2125d
* Version Independent ID: 72a36cdb-f4c8-447b-4a11-fa5abbe4699d
* Content: [Internet-based client management - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/plan-internet-based-client-management)
* Content Source: [sccm/core/clients/manage/plan-internet-based-client-management.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/plan-internet-based-client-management.md)
* Service: **unspecified**
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the comment @bmilbauer. Good point that we don't have any language in this older IBCM article. There is a description of the behavior in the section to [Configure clients for CMG](https://docs.microsoft.com/sccm/core/clients/manage/cmg/setup-cloud-management-gateway#configure-clients-for-cmg), which is the same for clients whether they are using CMG or IBCM.

**Comment by DawnWertz** [comment]
Along with documenting how a client determines it is on the Internet, also if you go from the Office to Home, how long before the client connects to cloud instead of trying for internal management point.

**Comment by aczechowski** [comment]
Thanks @1RedOne for fixing this a while ago, I just never closed it. :)
