### ISSUE TITLE
Install Account

### ISSUE THREAD

**Issue by PJMarcum** [MicrosoftDocs/SCCMdocs#572]
I think it would be worth noting the importance of the account used to install ConfigMgr. This should always be a dedicated account rather than a normal users account because it has permissions that even full admins do not get. I can't remember the specifics but if the account gets deleted the only way to assign the permissions to someone else is by manually editing the database.

(5/31 admin edit: added GitHub footer for linking with target article)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f80cf3-6f36-cb44-d0e5-d186164d6281
* Version Independent ID: ada8a281-7d9f-e82e-e4e8-056b93e8b36d
* Content: [Accounts used - Configuraton Manager](https://review.docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/accounts?branch=live#accounts-that-configuration-manager-uses)
* Content Source: [sccm/core/plan-design/hierarchy/accounts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/accounts.md)
* Service: **unspecified**
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by PJMarcum** [comment]
It was documented for 2007 but didn’t call out the issues associated with deleting the account.

Typos compliments of Siri
Sent from my iOS device

On May 31, 2018, at 12:58 PM, Aaron Czechowski <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @PJMarcum<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPJMarcum&data=02%7C01%7C%7Cefe4da41004e4dbb7d6108d5c717aeb0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636633826874571284&sdata=jw3sxdFYt4KgtencM3O%2FGxuwLQ2ail1N3FLMKdEz2rA%3D&reserved=0> for the comment. In the future, you can click Feedback from a target article and file an issue directly, which automatically links the issue and the article.

Good point to call out, I don't think our documentation has ever discussed this account.

**Comment by aczechowski** [comment]
Is this the SCCM 2007 article to which you are referring? [About the Account Used To Install Configuration Manager](https://technet.microsoft.com/library/bb632954.aspx)
I did a few keyword searches and don't find any related text in the current branch documentation library.

**Comment by aczechowski** [comment]
There is some language in the article for [Prerequisites for installing sites](https://docs.microsoft.com/sccm/core/servers/deploy/install/prerequisites-for-installing-sites) but I agree that we should mention this account on the Accounts article.

**Comment by PJMarcum** [comment]
I did find this documented just not with all the other accounts. It's here https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/prerequisites-for-installing-sites


John Marcum
MCP, MCTS, MCSA
MVP - Enterprise Mobility


________________________________

**Comment by Silencer0001** [comment]
I would love to get some additional information on this as well. I've worked in many environments and was never operating under the "installation account". I've always had enough rights if my account was configured as "full administrator" for "all instances". If my account was only configured for the default scopes, I wasn't able to "promote pre-production client" for instance. In some environments, the installation was done with a personal account from an administrator who has already left the company. Afterwards, a general "installation account" was added as "full administrator for all instances" and added as "Sysadmin" on the instance of the SQL-server which hosts the site database. Is this enough to always be in charge of the SCCM environment? Thanks!

**Comment by aczechowski** [comment]
Closing this issue. I published revisions to this article today, and included a new section for the [Site installation account](https://docs.microsoft.com/sccm/core/plan-design/hierarchy/accounts#site-installation-account)

**Comment by PJMarcum** [comment]
Thanks man!

Typos compliments of Siri
Sent from my iOS device

On Oct 31, 2018, at 1:18 PM, Aaron Czechowski <notifications@github.com<mailto:notifications@github.com>> wrote:


Closing this issue. I published revisions to this article today, and included a new section for the Site installation account<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fsccm%2Fcore%2Fplan-design%2Fhierarchy%2Faccounts%23site-installation-account&data=02%7C01%7C%7C4910116e983a4aaef2dc08d63f5d3bd0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636766066992383823&sdata=JKzQqbJ9WRE3HxqmNNjfPn5RNmjA8bdxHoPS3YOGB1E%3D&reserved=0>
