### ISSUE TITLE
Configuration Manager and Intune workload management 

### ISSUE THREAD

**Issue by TheJonCallahan** [MicrosoftDocs/SCCMdocs#574]
This document should clarify that Configruation Manager will handle all workloads (such as device configurations, apps, etc.) except for those workloads that have been explicitly transitioned to Intune. Older versions of this page had:

After you enable co-management, Configuration Manager continues to manage all workloads.

It should be clearly stated that Intune will not handle workloads such as app deployments and device configuration policies after co-management is enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07e9b780-6cad-d3f3-d0f2-e13a577890cc
* Version Independent ID: 18c7f0aa-884a-349b-e416-74d02adc4474
* Content: [Co-management for Windows 10 devices - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/co-management-overview#feedback)
* Content Source: [sccm/core/clients/manage/co-management-overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/co-management-overview.md)
* Service: **unspecified**
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @TheJonCallahan for the comment. I agree we need to better clarify a few things like this.

**Comment by iaasazure** [comment]
@TheJonCallahan critical information.  Microsoft  please update the article with a complete breakdown of workloads not available on Intune when in Co management.  Please could you also explain if it is supported to use Sccm and Intune without Co management as two standalone solutions.

**Comment by aczechowski** [comment]
@iaasazure to your second point - not on the same device. For any single device, you have three options for device authority: SCCM, Intune, or co-managed. In any single organization, you can use a combination of those three for different devices as needed to meet your business requirements.

**Comment by iaasazure** [comment]
@aczechowski  thanks.  Is it possible to concurrently manage a device with Intune using MDM (standalone) and SCCM for legacy apps with the SCCM client.
Essentally we have a very basic customer requirement to leave legacy apps on SCCM but would like to implement Intune with all features available and limited changes to on premises SCCM. 
We would like to have all the features of Intune available for Windows 10 MDM clients including configuration policies and app deployment, concurrently the client would only use SCCM for management of legacy applications. 
Ideally we would run both Intune and SCCM in isolation just as you would if using SCCM for legacy apps and a third party MDM solution. 
I have this working in the lab with no changes in SCCM, no Intune subscription or Co management has been configured in SCCM. This has been achieved by setting the Enrollments\ExternallyManaged registry dword which SCCM appears to set which blocks MDM provisioning. Is it supported to modify this registry key? 
I think SCCM hybrid MDM with the pilot group setup moving to clients to Intune Standalone MDM would achieve the same aim of all Intune features and the SCCM client still able to manage legacy apps. Am I correct in my understanding of the use of the SCCM hybrid pilot group?

It would be great if hybrid can do what I would like but it's not currently working in the second lab I have with that setup.

There isn't much documentation on the ExternallyManaged registry key.  I can't find anything regarding if it is supported to use SCCM with third party MDM.
https://msdn.microsoft.com/en-us/library/windows/desktop/dn574815(v=vs.85).aspx

https://foxdeploy.com/2017/08/04/mdm-errors-failures-and-how-to-fix-them/amp/

**Comment by aczechowski** [comment]
@iaasazure, it's not supported to modify that registry key. We use Windows APIs. We continue to iterate by adding additional features on co-managed devices (for example, [O365 in 1806 TP](https://docs.microsoft.com/sccm/core/get-started/capabilities-in-technical-preview-1806#transition-office-365-workload-to-intune-using-co-management)), which is our supported method to complete this scenario. If you have product feedback about additional functionality that you'd like to see in the product, please see [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) on several paths to do that.

**Comment by daves83** [comment]
@AaronCzechowski - @iaasazure If I have not misunderstood with SCCM 1806 and Co-Management, you can deploy an application through Intune and a legacy application through Config Manager on the same device.
As reported in this article: "After you transition this workload, any available apps deployed from Intune are available in the Company Portal. Apps that you deploy from Configuration Manager are available in Software Center."

**Comment by aczechowski** [comment]
I'm closing this issue. A big revision to the co-management content will publish soon, and I think it addresses this issue. After the new content is published, if you still think further clarity is necessary, please file a new issue on the new article.
