### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by nromyn** [MicrosoftDocs/SCCMdocs#580]
The Note section, containing information about the known issue, is slightly confusing. The paragraph immediately above it suggests that there's only two options; the note section suggests a third, and isn't clear about what the proper workaround for the known issue is.

&gt; To enable Android for Work, you must use the **Manage all supported devices as Android for Work** option.

Is this the **Manage all devices as Android**, or the **Manage supported devices as Android for Work** option? 

Lines 52-58.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d56b4d20-bcf7-819c-d7ed-b6d8eaa0dd20
* Version Independent ID: 27b9d371-8b26-3b97-c464-b8e473f01274
* Content: [Set up Android hybrid device management with Microsoft Intune - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/enroll-hybrid-android)
* Content Source: [sccm/mdm/deploy-use/enroll-hybrid-android.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/enroll-hybrid-android.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by tycastMSFT** [comment]
@nromyn I apologize for the confusion. The right option is "Manage supported devices as Android for Work". I'll go ahead and update the doc. Thanks for bringing this to our attention.

**Comment by nromyn** [comment]
Thanks!

**Comment by aczechowski** [comment]
Thanks @nromyn for catching this! I just merged the change from @tycastMSFT, which should publish live tomorrow morning around midday Pacific. I'm closing this issue.
