### ISSUE TITLE
Incorrect spelling of update

### ISSUE THREAD

**Issue by StevybSC** [MicrosoftDocs/SCCMdocs#581]
References to the log file used for Third-party software updates is incorrectly spelt.
SMS_ISVUDPATES_SYNCAGENT.log =/= SMS_ISVUPDATES_SYNCAGENT.log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a8e07fe-e439-3807-ce09-06e9d942c958
* Version Independent ID: d9d9902c-ed76-6e07-1228-9beb61c979ad
* Content: [Technical Preview 1806 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/capabilities-in-technical-preview-1806#feedback)
* Content Source: [sccm/core/get-started/capabilities-in-technical-preview-1806.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/capabilities-in-technical-preview-1806.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @StevybSC for catching this. :) I just fixed this, it should publish live tomorrow around midday Pacific time.
