### ISSUE TITLE
Other tool dependecies 

### ISSUE THREAD

**Issue by prashanthmiryala** [MicrosoftDocs/SCCMdocs#587]
we have lot of blogs and documents out there but no one mentioned whether all other dependency products like MDT required version and whether a upgrade is required for the same if we upgrade configuration manger .
currently we are on 1710 and thinking to upgrade to 1802 my major concern is whether we need to upgrade our ADK and MDT?
our ADK version:10.1.16299.15 but here in the document states 1703 which is strange :-( our MDT version is 6.3.8450 and not sure whether we need a update for the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca18d72d-ad7b-0862-f17b-df1f4c66b562
* Version Independent ID: 2cad51ef-780d-a5b6-6502-b8c8c8cddbcd
* Content: [Checklist for 1802 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/checklist-for-installing-update-1802#feedback)
* Content Source: [sccm/core/servers/manage/checklist-for-installing-update-1802.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/checklist-for-installing-update-1802.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @prashanthmiryala for the feedback. A few comments:
- The section of this article that talks about the ADK says "1703 or later" and then refers to the matrix in the Support for Windows 10 article. That support article shows that Configuration Manager 1802 supports Windows ADK versions 1703 or later. So I think that's accurate.
- There are a lot of first- and third-party extensions available for Configuration Manager. The best resource for whether those components need to be upgraded at the same time is the product documentation for that product.
    - I recently revised the [MDT release notes](https://docs.microsoft.com/en-us/sccm/mdt/release-notes).
    - I agree that this article should include information about the possible need to update extensions. I'll use this issue to track that change.

**Comment by aczechowski** [comment]
I just added a new section in the code, as well as in the section at the bottom after updating. It should publish live on Monday about midday Pacific time.

**Comment by prashanthmiryala** [comment]
thanks a lot..

________________________________
