### ISSUE TITLE
Non information about OS for patches

### ISSUE THREAD

**Issue by ilnuri** [MicrosoftDocs/SCCMdocs#592]
NO information about OS applicability of the patches for WSUS in this article. It misleads people. My peer tried to install those patches to server 2016 for two days.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 216e808f-64f5-7681-3f7b-bfc1f4193b71
* Version Independent ID: 8f9a6ef6-6eff-430f-a6d8-b59143c7fdb2
* Content: [Manage Windows as a Service - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/manage-windows-as-a-service)
* Content Source: [sccm/osd/deploy-use/manage-windows-as-a-service.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/manage-windows-as-a-service.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @ilnuri, thank you for sharing and I'm sorry for the difficulties. I assume you're referring to the prerequisites? 
This article in general is on the backlog for a revision. I'll use this issue to track that effort.

**Comment by ilnuri** [comment]
Hello,

Thank you! 

Отправлено с iPhone

**Comment by bchand** [comment]
is there any Windows 10 License Consideration for using Windows as Service ( SCCM )
