### ISSUE TITLE
Replace old screen shot

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/SCCMdocs#593]
In Step 3, item 2, the screen shot is from the old Intune portal, this should be replaced with the current version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69caa436-7335-8209-200f-3d9b8e86e7b4
* Version Independent ID: 3bf97b11-a3ed-e089-24f1-4c609b490fe0
* Content: [Manage SharePoint Online access - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/manage-sharepoint-online-access#configure-conditional-access-for-sharepoint-online)
* Content Source: [sccm/mdm/deploy-use/manage-sharepoint-online-access.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/manage-sharepoint-online-access.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @DeanGross for filing this. There are unfortunately probably a number of these sort of old screenshots in the MDM content as Intune moved to the Azure portal. One challenge of using screenshots. :(

**Comment by DeanGross** [comment]
Should there be some guidance to authors not to include screen shots ?

**Comment by ChrisKibble** [comment]
Tagging @AdamGrossTX who I know has a lot of Intune shots and may want to update in his down time.

**Comment by aczechowski** [comment]
Thanks @ChrisKibble, but honestly I wouldn't bother at this point given hybrid is deprecated and we're turning it off in a few months. In fact, I'll just close and decline this issue. (There are probably other issues on hybrid content that we can close as we're not going to fix at this point.)

**Comment by ChrisKibble** [comment]
Thanks @aczechowski, sorry for the false alarm @AdamGrossTX :)

I'm going through most of the issues, I'll keep an eye out and tag any open ones still mentioning hybrid as I come across them.
