### ISSUE TITLE
How to upgrade an evaluation installation of System Center Configuration Manager to a full installation

### ISSUE THREAD

**Issue by thutrang162** [MicrosoftDocs/SCCMdocs#594]
There is no option called "Upgrade the evaluation edition to a licensed edition" on the Site Maintenance Setup Wizard page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d9ccce-774e-a95b-7730-32412b51b16f
* Version Independent ID: a2b9f5ae-acd8-0327-c031-b6aa13627658
* Content: [Upgrade evaluation installs - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/upgrade-an-evaluation-install-to-a-full-install)
* Content Source: [sccm/core/servers/deploy/install/upgrade-an-evaluation-install-to-a-full-install.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/upgrade-an-evaluation-install-to-a-full-install.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by theznerd** [comment]
Experiencing the same thing on an 1803 EVAL install as well.
![image](https://user-images.githubusercontent.com/12768931/42706075-ce1d8086-8692-11e8-966b-c84b6c2bed7b.png)

**Comment by baardhermansen** [comment]
Strange that this has not already been closed. I take it for granted that the described behavior is now known to be by design. A TP cannot be upgraded to a full version. 

#officedocsbot Close
