### ISSUE TITLE
Include note that script parameters don't overwrite default script values

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#595]
From [Feedback Hub](https://aka.ms/feedbackhuburi/?ContextId=927&feedbackId=855fc41a-6452-4196-9068-77f1e7a663f4&form=1&src=1):
> If there is a default parameter in the script, we’ll enumerate that in our parameter UI and users can set it, but we don't overwrite the default value (since we never modify the script directly). You can think of this as “pre-populated suggested values” are provided in the UI, but SCCM doesn't provide access to “default” values at run-time. This can be worked around by the Script that is written.

Reference internal bug 515526

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c7d1db7-6812-ff3c-9aac-0f55800ed665
* Version Independent ID: a4499cf7-ed5a-710c-66e0-005563b9c015
* Content: [Create and run scripts - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/create-deploy-scripts#feedback)
* Content Source: [sccm/apps/deploy-use/create-deploy-scripts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/create-deploy-scripts.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by mestew** [comment]
This information was added under the [parameters section](https://docs.microsoft.com/sccm/apps/deploy-use/create-deploy-scripts#script-parameters). The changes should be published in the next day or so.
#please-close
