### ISSUE TITLE
Restart Behavior and CLient Notification

### ISSUE THREAD

**Issue by jpoling1** [MicrosoftDocs/SCCMdocs#596]
The restart behaviors and client notification section does not describe a situation we are seeing with CB 1802. Not sure if we are seeing expected behavior or a bug. The pop up notification from Office is appearing directly after a deployment is created, even though the deadline for the deployment is several hours away.   Also, the Office applications were force closed - which is different from what the doc says is supposed to happen in 1802? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1da48af-4783-bd17-67f3-f265df93503f
* Version Independent ID: 17432b22-04cb-f47f-1634-e5b7fc99c37d
* Content: [Manage Office 365 ProPlus updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/manage-office-365-proplus-updates#restart-behavior-and-client-notifications-for-office-365-updates)
* Content Source: [sccm/sum/deploy-use/manage-office-365-proplus-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/manage-office-365-proplus-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
[Twitter thread](https://twitter.com/AaronCzechowski/status/1007340254876094465) for reference. Have an internal email to clarify.

**Comment by RobCCTZ** [comment]
This happens in 1806 as well. Deployed to a test group with immediate availability and a deadline of 7:30PM that night ( deployment created at 10AM). 30 minutes later my test group started to get prompted to close office apps and proceed or postpone.  Am I missing something here?

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
