### ISSUE TITLE
Very nice document!

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/SCCMdocs#602]
The new layout and formatting help make this easier to read than the previous incarnation.  I just wanted to add a compliment, rather than picking at it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 972d8899-c8a4-28c5-fabe-5ab294bac22d
* Version Independent ID: 7f772e7a-836c-a18d-df8d-c3d115cb3d9f
* Content: [Log files for troubleshooting - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/log-files#BKMK_FunctionLogs)
* Content Source: [sccm/core/plan-design/hierarchy/log-files.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/log-files.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thank you @Skatterbrainz for the feedback! I think this is my first opportunity to use the "kudos" tag. :) 

Although a followup question before I close this. I actually haven't made any changes to this doc yet, and the format/layout was one thing I was considering changing. (I'm not yet sure 'to what' I would to change it.) Can you share more specifics what it is about the layout/format that you like? How is it structured now that you find easy to use?

**Comment by Skatterbrainz** [comment]
It's a combination of several factors that often get overlooked in technical documentation:  font, spacing (and white space), table border margins, and the actual descriptions for each log.  They're concise and easy to understand.  Most of my wishlist ideas would fall on the console side of the relationship than on the web site, at this point anyway.
