### ISSUE TITLE
Log filtering suggestions

### ISSUE THREAD

**Issue by PotentEngineer** [MicrosoftDocs/SCCMdocs#603]
One of the most useful tips we give techs when viewing logs is what to filter on in CMTrace to see pertinent information. 

ie.) Filter smsts.log on entry text containing "the action" or "the group". Filter InventoryAgent.log where entry text contains "destination".

Could useful filters be added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 972d8899-c8a4-28c5-fabe-5ab294bac22d
* Version Independent ID: 7f772e7a-836c-a18d-df8d-c3d115cb3d9f
* Content: [Log files for troubleshooting - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/log-files#BKMK_SU_NAPLog)
* Content Source: [sccm/core/plan-design/hierarchy/log-files.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/log-files.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Yes, thanks @PotentEngineer for the idea. I'm thinking about an entirely separate article on tools to include a section on CMTrace with all of its goodness. I'll use this issue to track that work. :)

**Comment by PotentEngineer** [comment]
Sounds good. I'll happily add some tricks.

-Daniel Ratliff

**Comment by aczechowski** [comment]
A whole new article on CMTrace coming soon! I included your two filter suggestions. Once it's published, I welcome the community's contributions with more suggestions and tips and examples! The article is in review, will merge to our private release branch today or tomorrow. It will publish live with 1806 content *soon*. So I'm closing this issue.
