### ISSUE TITLE
Co-Management on AADJ devices 

### ISSUE THREAD

**Issue by maayanbarn** [MicrosoftDocs/SCCMdocs#605]
It is not clear from this article that co-management is supported not only on hybrid AADJ devices, but also on AADJ devices that are not domain joined. Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07e9b780-6cad-d3f3-d0f2-e13a577890cc
* Version Independent ID: 18c7f0aa-884a-349b-e416-74d02adc4474
* Content: [Co-management for Windows 10 devices - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/co-management-overview#feedback)
* Content Source: [sccm/core/clients/manage/co-management-overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/co-management-overview.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @maayanbarn for filing this issue, will get this added to clarify.

**Comment by aczechowski** [comment]
I fixed this while adding new content for 1806. The updates for this article should publish live later today around midday. I'm closing this issue.
