### ISSUE TITLE
Space needed on ACertificate registration point

### ISSUE THREAD

**Issue by A-A-Ron42** [MicrosoftDocs/SCCMdocs#609]
#NWSCUGHackadoc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e6c9b24-f28e-464b-d625-53b7453082b9
* Version Independent ID: 1a657226-b1e7-e14f-656c-dee37cab5beb
* Content: [PKI certificate requirements - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/network/pki-certificate-requirements#feedback)
* Content Source: [sccm/core/plan-design/network/pki-certificate-requirements.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/network/pki-certificate-requirements.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Fixed with PR #610
