### ISSUE TITLE
How can you tell if you have an ARM vs Classic CMG

### ISSUE THREAD

**Issue by AhzX** [MicrosoftDocs/SCCMdocs#611]
Consider if an Engineer or Consultant goes into a new environment. Is there any way to tell which type is set up? Can we link an article or give a note? #NWSCUGHackadoc

(Admin edit, adding metadata to link with target article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fb371d2-b1f1-68ca-ed95-abf37e3ecf28
* Version Independent ID: cd7fc055-b430-3a4a-1002-c69087f30714
* Content: [Set up cloud management gateway - Configuraton Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/setup-cloud-management-gateway#modify-a-cmg)
* Content Source: [sccm/core/clients/manage/cmg/setup-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/setup-cloud-management-gateway.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @AhzX, good idea. I think this would work well in the linked article, Modify a CMG section.

**Comment by aczechowski** [comment]
Added a new tip. Closing this issue.

**Comment by AhzX** [comment]
Thanks Aaron, I’d just say add a note with the old designation as well… “Azure Service Manager” ?

**Comment by aczechowski** [comment]
You're right, from a search engine optimization perspective, should add the term "Azure Service Manager" for clarity and completeness. That's how we generally refer to the classic deployment. Reopening the issue.

**Comment by aczechowski** [comment]
This issue is closed because I made a tweak to the article for this feedback. The change should publish live later today.
