### ISSUE TITLE
Conflict explaination

### ISSUE THREAD

**Issue by toxarisswe** [MicrosoftDocs/SCCMdocs#616]
Could someone please rewrite the section about conflict resolving, I fint it very confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f077a2a9-9f27-c636-4e7f-51c899c38b69
* Version Independent ID: e9d5f894-6214-95a0-54ef-1656cc02e518
* Content: [Protect apps using mobile application management policies - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/protect-apps-using-mam-policies#learn-how-policy-conflicts-are-resolved)
* Content Source: [sccm/mdm/deploy-use/protect-apps-using-mam-policies.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/protect-apps-using-mam-policies.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @toxarisswe for the feedback. I'll see what we can do to improve that section.

**Comment by iecompattest** [comment]
test


yuyyjhg



lijhdsifd

sdfdjsf;ds

**Comment by aczechowski** [comment]
hybrid end of service is this coming weekend, closing this issue
