### ISSUE TITLE
MessageTimeout must be set to 1 (not 0) to disable reboot message

### ISSUE THREAD

**Issue by oyvsi** [MicrosoftDocs/SCCMdocs#617]
Tested on 1710 and 2012 R2 SP1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ad040a6-4c0d-27b4-03da-8656146d48de
* Version Independent ID: b2b5223c-b4f8-884e-2433-22c167b90916
* Content: [SMS_TaskSequence_RebootAction Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/osd/sms_tasksequence_rebootaction-server-wmi-class)
* Content Source: [sccm/develop/reference/osd/sms_tasksequence_rebootaction-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/osd/sms_tasksequence_rebootaction-server-wmi-class.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @oyvsi for sharing this feedback. I'm checking with the OSD feature team on what behavior it *should* be, to help determine whether it's a doc bug or product bug.

**Comment by aczechowski** [comment]
@oyvsi can you please provide some more info? How are you using this method? When you set this property to 0, what's the behavior? When you set it to 1, it disables notification, and not just sets the timeout to one second? Are you setting a message (I assume not)?

**Comment by oyvsi** [comment]
Thanks for looking into this.  We use it to generate task sequences. 

Message is never set. If MessageTimeout.IntegerValue is set to 0 then the resulting behavior is that the default notification message is set and message display time-out is set to 60. If MessageTimeout.IntegerValue is set to 1 then notification is disabled and message display time-out is grayed out in the GUI.

**Comment by aczechowski** [comment]
Great thanks. We're pretty sure this is a product bug; the documentation is correct how it should behave. I'm closing this doc issue. (If you want to file on as [Product Feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) in Feedback Hub then you should be able to get notification of the issue that way.)
