### ISSUE TITLE
The correct approach to enable RandomAdminPassword is very confusing

### ISSUE THREAD

**Issue by oyvsi** [MicrosoftDocs/SCCMdocs#618]
AdminPassword: "This property must be set, but it is ignored if the RandomAdminPassword property is set to e". RandomAdminPassword is a boolean. I'm guessing that it needs to be true and that AdminPassword cannot be null(?) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab30ff5a-8bc6-f4a0-f92a-0a1d805ca4e8
* Version Independent ID: f366d2cb-7f1a-0ecd-2bdb-c8eada68934c
* Content: [SMS_TaskSequence_ApplyWindowsSettingsAction Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/osd/sms_tasksequence_applywindowssettingsaction-server-wmi-class)
* Content Source: [sccm/develop/reference/osd/sms_tasksequence_applywindowssettingsaction-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/osd/sms_tasksequence_applywindowssettingsaction-server-wmi-class.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @oyvsi for catching this. Yes, it should be `true` instead of `e`.

**Comment by aczechowski** [comment]
Closing this issue as it will be fixed later today with the linked pull request.
