### ISSUE TITLE
Cloud Management Gateway Section

### ISSUE THREAD

**Issue by nathanmaslin** [MicrosoftDocs/SCCMdocs#619]
Hey Team

Any chance we can get the ports for Cloud Management Gateway added to this page? It's nice to have all the port information in one place so there is no need to go digging

Thanks

Nathan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f658ee4b-d051-0d7c-4656-19a846908469
* Version Independent ID: 3478e881-199c-f0c4-b218-0dd609eb0427
* Content: [Ports used for connections - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/ports)
* Content Source: [sccm/core/plan-design/hierarchy/ports.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/ports.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @nathanmaslin for your feedback. Yes, this information should be here. I was tracking this via a legacy internal doc bug (511054 for my reference), but will use this going forward. The information is in the article to [Plan for CMG](https://docs.microsoft.com/sccm/core/clients/manage/cmg/plan-cloud-management-gateway#ports-and-data-flow).

**Comment by aczechowski** [comment]
Added CMG ports. Closing this issue.
