### ISSUE TITLE
Install Google for Windows 10 Interprise

### ISSUE THREAD

**Issue by ClausFrede** [MicrosoftDocs/SCCMdocs#622]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f658ee4b-d051-0d7c-4656-19a846908469
* Version Independent ID: 3478e881-199c-f0c4-b218-0dd609eb0427
* Content: [Ports used for connections - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/ports)
* Content Source: [sccm/core/plan-design/hierarchy/ports.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/ports.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I'm guessing this is misfired text, as I don't understand the connection between SCCM ports and installing Google for Win10. So I'm going to close this issue; please reactivate with more information if this is legitimate feedback on SCCM documentation.
