### ISSUE TITLE
Minor Correction

### ISSUE THREAD

**Issue by Phil2Pint** [MicrosoftDocs/SCCMdocs#625]
'Delivery Optimization coordinates with Configuration Manager and downloads the ranges from a local distribution point or peers if available. ' Nope it doesn't. BITS does the downloading. DO is just the requesting app. You can see this in DeltaDownloader.log DO only comes into play if it finds content on Peers

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: def581b6-f8e0-f512-2113-9c3495be54c2
* Version Independent ID: 8effe9f9-9e7b-3d6e-033c-639b56acd648
* Content: [Optimize Windows 10 update delivery - Configuration Manager](https://docs.microsoft.com/en-gb/sccm/sum/deploy-use/optimize-windows-10-update-delivery)
* Content Source: [sccm/sum/deploy-use/optimize-windows-10-update-delivery.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/optimize-windows-10-update-delivery.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Phil2Pint for the feedback. I'm discussing with the feature team.

**Comment by mestew** [comment]
Changing this now. I'm removing the mention of BITS since it confuses the issue and just referring to the downloaded ranges.
