### ISSUE TITLE
Script Runners can still create scripts

### ISSUE THREAD

**Issue by jannin75** [MicrosoftDocs/SCCMdocs#627]
I added the Script Runners permissions to a security role and they can actually create scripts.  I verified they are not in any other role.  Is there an issue with the documentation?  I was just wondering if anyone had tried it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c7d1db7-6812-ff3c-9aac-0f55800ed665
* Version Independent ID: a4499cf7-ed5a-710c-66e0-005563b9c015
* Content: [Create and run scripts - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/create-deploy-scripts)
* Content Source: [sccm/apps/deploy-use/create-deploy-scripts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/create-deploy-scripts.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jannin75 for filing the feedback. I checked with the engineering team. The **Script Runners** role doesn't require the permission to create. I need to remove the line (SMS Scripts  Create  Yes) in that section (Script Runners).

Internal reference 518419

**Comment by aczechowski** [comment]
Thanks to @jocasti for making this edit. The change should be live by Tuesday, 19 February around 11am Pacific time.
