### ISSUE TITLE
Links to task sequence variables point to wrong page

### ISSUE THREAD

**Issue by sigurd-de** [MicrosoftDocs/SCCMdocs#630]
The two notes around SMSTSMPListRequestTimeout are pointing to ‘Task sequence built-in variables’ (https://docs.microsoft.com/en-us/sccm/osd/understand/task-sequence-built-in-variables)  , but should Point to ‘Task sequence action variables’ (https://docs.microsoft.com/en-us/sccm/osd/understand/task-sequence-action-variables#BKMK_InstallApplication )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1187d55d-d8b3-ebc8-37e8-8de14807be4e
* Version Independent ID: daff4a99-10ac-b424-f08a-9024407e667a
* Content: [Task sequence steps - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/understand/task-sequence-steps)
* Content Source: [sccm/osd/understand/task-sequence-steps.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/understand/task-sequence-steps.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @sigurd-de for the feedback, I have plans on reworking these articles, which aligns with this request. :)

**Comment by aczechowski** [comment]
I fixed this with an internal update to this article that's currently in review. Along with partial resolution of issue #551, I created a new article: https://docs.microsoft.com/sccm/osd/understand/task-sequence-variables, which combines the two previous variable articles into a single, comprehensive reference. It should publish live by the end of this week. I'm closing this issue.
