### ISSUE TITLE
Improved secure client communications for SUP

### ISSUE THREAD

**Issue by jemmail** [MicrosoftDocs/SCCMdocs#631]
Hi,
Is the new Improved secure client communications also available to secure transfer from the client to a Software Update Point (SUP) over 8531 ?

Is this also available via the Cloud Management Gateway to the SUP ?

and last but not least, is this a test feature or will it be OK for productive environments (when implemented in CB) ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a504ecc8-34dd-2827-660a-0e5303e88e49
* Version Independent ID: 79ba1a30-59d4-2fd0-f73d-4c1e9fcada74
* Content: [Technical Preview 1805 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/capabilities-in-technical-preview-1805)
* Content Source: [sccm/core/get-started/capabilities-in-technical-preview-1805.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/capabilities-in-technical-preview-1805.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @jemmail, thanks asking. The SUP currently doesn't benefit from this feature. 
Regarding your third question, see [Technical Preview](https://docs.microsoft.com/sccm/core/get-started/technical-preview) for information about using this branch. The technical preview branch is only for lab use. When we release a new current branch version (for production use), if features from a technical preview are ready for production use then we include them in the current branch. The above page displays a list of features that are still in technical preview as well as ones that are available in current branch. 
I'm closing this issue as there doesn't appear to be anything actionable for a documentation revision.
