### ISSUE TITLE
Issues with User AD Object in Sccm since it was added as default object

### ISSUE THREAD

**Issue by jcsubzerologic** [MicrosoftDocs/SCCMdocs#632]
Before in SCCM you had to add whenCreated as a custom object to be scanned from AD for user's and that works fine but ever since this object was moved to default it does not pull the date from AD. I have 495 who where added to sccm by AD before and they have whenCreated dates but since the SCCM update that made this object default in SCCM i have 544 users without whenCreated dates in SCCM. I need this to work correctly as I have Audit reports my Help desk uses for Audit new user's that where created in the last 90 day. Please let me know what I can do to fix this issue and get the whenCreated object in AD to sync with SCCM 1710

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 181af3ed-e579-507a-9885-97284578fc3c
* Version Independent ID: 53e85e7f-febf-b8ce-5306-75b84c84cae6
* Content: [Find help - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/understand/find-help#product-feedback)
* Content Source: [sccm/core/understand/find-help.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/find-help.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
