### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by vorear** [MicrosoftDocs/SCCMdocs#633]
Another site http://www.techiessphere.com/2017/05/explained-wsus-update-classification.html described Updates as "Broadly released files for specific problems addressing a non-critical, non-security related bugs for applications or components which is currently installed." Is that a better definition?  At https://docs.microsoft.com/en-us/windows-server/administration/windows-server-update-services/manage/viewing-and-managing-updates it's described as "Broadly released fixes for specific problems addressing non-critical, non-security related bugs."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a1f31d1-13b4-d057-572b-b1a58af29692
* Version Independent ID: a79a4b2b-145d-b47b-54b9-6536db780f82
* Content: [Configure classifications and products - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/get-started/configure-classifications-and-products)
* Content Source: [sccm/sum/get-started/configure-classifications-and-products.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/get-started/configure-classifications-and-products.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @vorear for the feedback. Agreed these classifications should be revised. This is the source content I'll reference: [Description of the standard terminology that is used to describe Microsoft software updates](https://support.microsoft.com/help/824684/description-of-the-standard-terminology-that-is-used-to-describe-micro)

**Comment by birch64** [comment]
Looking at the minor builds of Windows ex. 10.0.16299.[726]. I have trouble finding the KB's for these minor builds. I would assume they are in the security updates classification but downloading all of these over WSUS don't seem to include the minor builds.

**Comment by aczechowski** [comment]
FYI, this issue was closed because @jocasti submitted a change last week to revise the list
