### ISSUE TITLE
Removing of CEIP feature 

### ISSUE THREAD

**Issue by thutrang162** [MicrosoftDocs/SCCMdocs#639]
Removing of CEIP feature should be also mentioned here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4b8caa-0b30-fba6-c031-d08b2facd201
* Version Independent ID: b0c6c951-511b-5920-8e24-656b6dc53ab0
* Content: [New version 1802 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/whats-new-in-version-1802#configuration-manager-console)
* Content Source: [sccm/core/plan-design/changes/whats-new-in-version-1802.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/changes/whats-new-in-version-1802.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @thutrang162 for the comment. Linking to issue #517

**Comment by aczechowski** [comment]
Just realized that #517 was closed from PR #736, so closing this as well.
