### ISSUE TITLE
Heartbeat not Hardware Inventory

### ISSUE THREAD

**Issue by Phil2Pint** [MicrosoftDocs/SCCMdocs#641]
"The client's last hardware inventory submission determines the current boundary of a Peer Cache content source". - is incorrect. It's the Heartbeat inventory - according to Kerwin! :-) https://social.technet.microsoft.com/Forums/en-US/e6b29fac-0f80-4fcb-8117-f0e35ee47aed/peer-cache-laptop-population?forum=ConfigMgrCBGeneral 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29b8c8d-60fa-4403-29a7-8e7c61b2f638
* Version Independent ID: c7610ca2-5607-d1fe-f629-9d0614a26569
* Content: [Client Peer Cache - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/client-peer-cache)
* Content Source: [sccm/core/plan-design/hierarchy/client-peer-cache.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/client-peer-cache.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Phil2Pint, I have some revisions planned for this article in the near future, so will look to catch this at the same time.

**Comment by Phil2Pint** [comment]
Perfect, thanks.

**Comment by aczechowski** [comment]
I revised this article for 1806 release, to include this information. The content should publish soon. I'm closing this issue.
