### ISSUE TITLE
Migration Point Requirements not correct

### ISSUE THREAD

**Issue by FISHMANPET** [MicrosoftDocs/SCCMdocs#645]
On Server 2016, the State Migration Point requires IIS 6 Metabase Compatibility but it is not listed as a requirement on this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9070eb9b-0e5f-a877-e02e-2d1cea2a2b38
* Version Independent ID: df251762-f2d6-9f06-4fa9-ec5cea2cca0a
* Content: [Site prerequisites - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/site-and-site-system-prerequisites)
* Content Source: [sccm/core/plan-design/configs/site-and-site-system-prerequisites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/site-and-site-system-prerequisites.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @FISHMANPET for noting this. I did some research, and I don't know why that was never included. I have some work on this article in the near future and will pick this up at the same time.

**Comment by FISHMANPET** [comment]
After fighting with this for a few days, I discovered it also required asp.net 4.6 (which automatically selected isapi extensions, isapi filters, and .net extensibility 4.6)

**Comment by aczechowski** [comment]
I updated this with the 1806 content, which will publish soon. I'm closing this issue.
