### ISSUE TITLE
Documentation Incorrect - SQL HA Group Failover to Manual

### ISSUE THREAD

**Issue by pfurches** [MicrosoftDocs/SCCMdocs#649]
Documentation is incorrect: It states that additional HA groups must be set to manual failover prior to 1610. This is still true in 1802. I just did an 1802 update and it required all SQL HA groups to be configured to manual failover before allowing the installation of HA to proceed.

(admin edit: add metadata block to link with article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53d1da83-d988-fb2b-82c5-fd9cf117cd42
* Version Independent ID: 2b1a3bd2-5116-1f21-c196-e3e5698a83c9
* Content: [SQL Server Always On - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database#limitations-and-known-issues)
* Content Source: [sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/sql-server-alwayson-for-a-highly-available-site-database.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @pfurches for filing this. I'll check with engineering if this is a known limitation, or possibly a product bug.

**Comment by aczechowski** [comment]
Fixed with linked internal pull request. *Once merged*, this change should be live with the next daily publishing process. Right now that *should* be tomorrow (Wednesday, 22 August) around 11:00 Pacific time. I'm closing this issue.
