### ISSUE TITLE
Need to add *.azureedge.net to the list of suffixes for Updates and Servicing

### ISSUE THREAD

**Issue by KBThornley** [MicrosoftDocs/SCCMdocs#650]
Customer reports that the DMPDOWNLOADER is try to get file from URL https://configmgrbits.azureedge.net/adminuicontent/ConfigMgr.AdminUIContent.cab            SMS_DMP_DOWNLOADER     02/07/2018 14:24:06      4944 (0x1350)

I believe this is the result of a recent change to the hosting of the CAB so the suffix is legit and just needs to be added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26fc3067-8a85-2455-8b71-69cf46cbb7e0
* Version Independent ID: a90ca598-c5fa-f245-eafc-0fd95f9eaca9
* Content: [Service connection point - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/about-the-service-connection-point#feedback)
* Content Source: [sccm/core/servers/deploy/configure/about-the-service-connection-point.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/about-the-service-connection-point.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by mestew** [comment]
The change is already merged in the private repo (PR#2723). @aczechowski this issue can be closed.
