### ISSUE TITLE
Incorrect Documentation - Altering sending email address of non-compliance emails

### ISSUE THREAD

**Issue by maimpone** [MicrosoftDocs/SCCMdocs#652]
The following section is incorrect: "You must enter the following information: a. Name: E-mail template name. b. From: E-mail address sending the e-mail notification. c. Subject: An subject that explains the e-mail notification being sent. d. Message body: More details on the e-mail notification."

It isn't possible to change the sending email address for non-compliance emails, as the option isn't given when creating actions for non-compliance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d37c99fa-25a3-0482-6394-af84e2795511
* Version Independent ID: cd006dce-6ed2-9b98-238b-397078b984b3
* Content: [Actions for noncompliance - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/actions-for-noncompliance)
* Content Source: [sccm/mdm/deploy-use/actions-for-noncompliance.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/actions-for-noncompliance.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @maimpone for filing this. Correct, the user doesn't input an email for the “from” field. It's auto-populated with a no-reply email from Microsoft. We need to remove 'b' from that statement.

**Comment by aczechowski** [comment]
Fixed with linked internal pull request. *Once merged*, this change should be live with the next daily publishing process. Right now that *should* be tomorrow (Wednesday, 22 August) around 11:00 Pacific time. I'm closing this issue.
