### ISSUE TITLE
Restart behavior and client notifications for Office 365 updates

### ISSUE THREAD

**Issue by n8from206** [MicrosoftDocs/SCCMdocs#655]
Customer, jpoling1, submitted feedback on the site (#596). Adding to comment with additional information.

I pinged author who noted that when it was changed, it should have been "behavior is for 1706 and higher" not just 1706. It was reverted intentionally to state behavior "In Configuration Manager version 1706.."

I'd like to confirm if the behavior applies to version 1706 and higher or only to Configuration Manager 1706 as stated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1da48af-4783-bd17-67f3-f265df93503f
* Version Independent ID: 17432b22-04cb-f47f-1634-e5b7fc99c37d
* Content: [Manage Office 365 ProPlus updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/manage-office-365-proplus-updates#restart-behavior-and-client-notifications-for-office-365-updates)
* Content Source: [sccm/sum/deploy-use/manage-office-365-proplus-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/manage-office-365-proplus-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @n8from206, we have some work planned on this article for the 1806 release, and will get this clarified.

**Comment by nanish7** [comment]
How's it going with 1806 behavior? Please add it.

**Comment by miaminemo** [comment]
@aczechowski - any update pending for 1806 or 1902 of what the defined behavior and known issues for o365 notifications are/should be?

**Comment by aczechowski** [comment]
@mestew is working with Office content team on revamping this article

**Comment by aczechowski** [comment]
@mestew made some recent revisions to this article to remove the older versions.
