### ISSUE TITLE
Web server certificates - Subject name

### ISSUE THREAD

**Issue by mt7479** [MicrosoftDocs/SCCMdocs#658]
What is the particular reason of the requeriment that the web server certificate should not have a subject name ?

If notification channel connections to port TCP/10123 are used SQL server must have a certificate . This certificate must match the certificate  imported in IIS. SQL server will not allow you to import a certificate without a common name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c66e3e8a-bd8e-7ae3-aecc-cd9073e2238e
* Version Independent ID: 45572c91-8194-096d-2356-80a9b1b356ef
* Content: [Deployment PKI certificates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/network/example-deployment-of-pki-certificates#to-request-the-web-server-certificate)
* Content Source: [sccm/core/plan-design/network/example-deployment-of-pki-certificates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/network/example-deployment-of-pki-certificates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback @mt7479, this article is unfortunately in need of some major review and revision. For example, it's not even linked in the table of contents. To your specific question, I don't know the real reason *why* it's not needed, that will require further research with engineering when we revise this article. But if you look at the note under step 13 in that section, it talks about use of the subject alternative name, and the last sentence says:

> If devices have limited support for SAN values in certificates, you might have to change the order of the FQDNs or use the Subject value instead.

So the example you provide might be an instance in which you need to use the Subject value.

**Comment by mt7479** [comment]
I overlooked that bit when filing the issue. Clarification would be nice though, because I know of some people who follow those instructions to the exact wording.

Even I tried until I discovered the notification channel breakage :-)

**Comment by aczechowski** [comment]
I'm resolving this issue in part because we moved repositories, but also because I'm going to track this work via an internal work item.

(internal reference 2841906)
