### ISSUE TITLE
Office 365 update not installing if Office apps open

### ISSUE THREAD

**Issue by alexledger1** [MicrosoftDocs/SCCMdocs#659]
I have seen issue in my environment with Office 365 update not applying properly if Office apps are open during installation.  The update is shown as successful and restart required in Software Center.  After restart original Office 365 build is still installed, next Software Update Deployment Evaluation Cycle, the update is reapplied.  Only way around it for me was to close Office Apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1da48af-4783-bd17-67f3-f265df93503f
* Version Independent ID: 17432b22-04cb-f47f-1634-e5b7fc99c37d
* Content: [Manage Office 365 ProPlus updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/manage-office-365-proplus-updates)
* Content Source: [sccm/sum/deploy-use/manage-office-365-proplus-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/manage-office-365-proplus-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
- If the behavior is consistently reproducible, file [Product feedback]( https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) to be considered as a product bug. 
I'm closing this issue as I don't think there's anything actionable for docs at this time.

**Comment by alexledger1** [comment]
Great I can consistently reproduce so will file on Product Feedback

**Comment by alexledger1** [comment]
Turns out it was the O365 update itself that caused the issue .  The following versions of O365 have not had same issue
