### ISSUE TITLE
Step needs to be added to "Cryptography tab" step

### ISSUE THREAD

**Issue by motaj1** [MicrosoftDocs/SCCMdocs#660]
You have to explicitly select provider as “Microsoft Software Key Storage Provider” when provider category is “Key Storage Provider”.

Providers listed are CNG KSPs. It is a requirement CNG KSP is selected for v3 cert.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 980e2274-7f4a-08cb-4c3d-cdf23e6552c7
* Version Independent ID: f6c565a3-f371-1c56-cac3-84c08338016a
* Content: [CNG certificates overview - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/network/cng-certificates-overview)
* Content Source: [sccm/core/plan-design/network/cng-certificates-overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/network/cng-certificates-overview.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for filing this @motaj1. I have some work planned on this article in the 1806 release timeframe, so will look at revising this then.

**Comment by aczechowski** [comment]
Fixed with SCCMDocs-pr PR [2801](https://github.com/MicrosoftDocs/SCCMDocs-pr/pull/2801). The revision will publish with 1806 content soon. I'm closing this issue.
