### ISSUE TITLE
Async SQL Versions

### ISSUE THREAD

**Issue by xstaindx** [MicrosoftDocs/SCCMdocs#662]
Is it supported to run a different version of SQL on the Datawarehouse?    Have 2014 on Site Server DB;  wanted to setup this up; can I set it up with SQL 2016 or 2017 while my Site DB runs 2014?  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a4274db-5f5b-c169-c69e-68146e92836f
* Version Independent ID: a28966e9-88cc-6910-c270-7f14818f832a
* Content: [Data warehouse - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/data-warehouse)
* Content Source: [sccm/core/servers/manage/data-warehouse.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/data-warehouse.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I confirmed with engineering feature team: yes, these can be different versions.

**Comment by aczechowski** [comment]
Closing this issue. I made an update that will publish soon with 1810 content
