### ISSUE TITLE
Deploy app as required?

### ISSUE THREAD

**Issue by toxarisswe** [MicrosoftDocs/SCCMdocs#665]
Do I have to deploy the app as required in order for the App Configuration Policy to be applied? I tested with a available deployment but it says that app isnt managed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c908b31-64b8-d929-0776-d5163bd094b0
* Version Independent ID: da6aaaef-bc4e-96fb-4998-4a711ea4130d
* Content: [Configure iOS apps with app configuration policies - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/configure-ios-apps-with-app-configuration-policies)
* Content Source: [sccm/mdm/deploy-use/configure-ios-apps-with-app-configuration-policies.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/configure-ios-apps-with-app-configuration-policies.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
hybrid end of service is this coming weekend, closing this issue
