### ISSUE TITLE
.NET 4.7.2 support?

### ISSUE THREAD

**Issue by Andy-Dawson** [MicrosoftDocs/SCCMdocs#666]
As the Microsoft .NET Framework 4.7.2 is now being pushed out as an important update, can the documentation be updated to confirm whether this is supported or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9070eb9b-0e5f-a877-e02e-2d1cea2a2b38
* Version Independent ID: df251762-f2d6-9f06-4fa9-ec5cea2cca0a
* Content: [Site prerequisites - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/site-and-site-system-prerequisites)
* Content Source: [sccm/core/plan-design/configs/site-and-site-system-prerequisites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/site-and-site-system-prerequisites.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Andy-Dawson, I confirmed that 4.7.2 is tested and supported. We'll revise the content.

**Comment by aczechowski** [comment]
Fixed with linked internal pull request. *Once merged*, this change should be live with the next daily publishing process. Right now that *should* be tomorrow (Wednesday, 22 August) around 11:00 Pacific time. I'm closing this issue.
