### ISSUE TITLE
Add Azure and SCCM Security Rights Requirements to Pre-Req Section

### ISSUE THREAD

**Issue by dctardy** [MicrosoftDocs/SCCMdocs#667]
Question: What are the Azure Resource Manager (ARM) rights required when setting up cloud management gateway (CMG) / cloud distribution point (CDP)?
Answer: Azure Subscription Administrator

Question: What are the Azure rights required for setting up the Cloud Services Server & Client apps?
Answer: Azure Active Directory (AAD) global admin if creating the apps in the SCCM console (follow the instructions to grant app permission in the Azure portal).  If just importing the Azure client & server apps in the SCCM console then SCCM admin rights are required.
 
Question: What are the Azure rights required when setting up Co-Management through the Co-Management Wizard?
Answer: As long as the Azure Active Directory (AAD) user has AAD 'user rights' they are able to on-board Co-Management through the SCCM wizard.  That user is required to have SCCM full-admin and all scope rights in the SCCM console.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7294682b-1bfb-54e4-0bdb-178e6fe2cc9a
* Version Independent ID: 6c5f1cfb-ae12-1fd2-80ef-1f67e419f4c5
* Content: [Prepare Windows 10 for co-management - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/co-management-prepare)
* Content Source: [sccm/core/clients/manage/co-management-prepare.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/co-management-prepare.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @dctardy. @mestew is working on this article soon, so hoping we can add this at the same time.

**Comment by mestew** [comment]
@dctardy @aczechowski  this shouldn't be a problem to add in while I'm there.

**Comment by aczechowski** [comment]
Oops, I missed closing this.
New section: https://docs.microsoft.com/sccm/core/clients/manage/co-management-prepare#prerequisite-azure-resource-manager-roles
