### ISSUE TITLE
Additional Tips?

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/SCCMdocs#670]
Any other tips would be very helpful.  Such as nesting/limiting collections.  Direct membership vs. Query, vs. mixing both in a given collection (not), when to use /not-use full refresh scheduling.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbccb59f-9513-3990-28b3-822f5cd44c69
* Version Independent ID: 89404c66-cedd-c696-a98a-c4ac8d062eb6
* Content: [Collections best practices - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/collections/best-practices-for-collections)
* Content Source: [sccm/core/clients/manage/collections/best-practices-for-collections.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/collections/best-practices-for-collections.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Skatterbrainz for the feedback. If you haven't already seen the [Configuration Manager Perf and Scale Guidance Whitepaper - Preview](https://gallery.technet.microsoft.com/Configuration-Manager-ba55428e), this has some further guidance on collections. I think once we finalize that whitepaper content and integrate into the core docs, this is probably a good home for that collection content.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. I am tracking the work on the perf/scale whitepaper in an internal item, so I'll link to this for future reference. But am going to close this issue.
