### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by RottenRonnie** [MicrosoftDocs/SCCMdocs#675]
Provide information for troubleshooting, such as location of log files:
Logging: 
C:\Windows\CCM\Logs\AppEnforce.log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67a999a9-9597-9dcf-bd61-c8320b8a1fae
* Version Independent ID: d99205df-c3d9-f101-13fc-bf7988848190
* Content: [Software Center user guide - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/understand/software-center)
* Content Source: [sccm/core/understand/software-center.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/software-center.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @RottenRonnie for the suggestion. The intent of this article is a guide for end users (or at least a template that SCCM administrators can use to create their own end user guide). So I don't think adding deeper technical content aligns with that intent. 

If we add troubleshooting content such as you suggested in issue #674, and improve the information in the [Log files](https://docs.microsoft.com/sccm/core/plan-design/hierarchy/log-files) article, then I hope this will address your feedback. So I'm going to close this specific issue.
