### ISSUE TITLE
Proxy Requirements

### ISSUE THREAD

**Issue by xstaindx** [MicrosoftDocs/SCCMdocs#677]
What are the Proxy Requirements for Setup Downloader to function?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc31b4b-0600-707c-a8e7-d512d4d1a1f3
* Version Independent ID: 46eb3b49-548c-da2d-db55-01bef95ee4d0
* Content: [Setup Downloader - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/setup-downloader)
* Content Source: [sccm/core/servers/deploy/install/setup-downloader.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/setup-downloader.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the question @xstaindx. I'm checking with engineering...

**Comment by xstaindx** [comment]
I would assume its similar to this: https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/about-the-service-connection-point#bkmk_urls  because the In Servicing downloads the prerequisites. 

Anyway if you can confirm, thanks aaron :)

**Comment by aczechowski** [comment]
I made a change for this, it will publish tomorrow
