### ISSUE TITLE
Order of operations to move site DB back to single instance is out of order from our experience

### ISSUE THREAD

**Issue by sashonk34** [MicrosoftDocs/SCCMdocs#679]
We just moved from an Always ON AG back to single instance on an existing SCCM site.  When attempting Step 4 our SQL DBAs encountered an error stating that members of an AG require FULL backup and they could not reconfigure backup model from FULL to SIMPLE.  FULL is a requirement for an AG per MS Docs:  https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/prereqs-restrictions-recommendations-always-on-availability?view=sql-server-2017#RequirementsDb  We worked around this by performing Step 10, then Step 4 and on through Step 9 with no issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90a6316d-7ce8-8cb9-6d9c-d6c923f12706
* Version Independent ID: 3476d25b-b42b-f9f4-a58d-80d95e97ac42
* Content: [Configure Availability Groups - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/configure-aoag#stop-using-an-availability-group)
* Content Source: [sccm/core/servers/deploy/configure/configure-aoag.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/configure-aoag.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback @sashonk34. We'll look at revising this in the future. An initial comment back from the engineering team (more for my future memory):
> I think we need a step 3.5 that says if you are planning to move from AG to standalone on an existing replica, the db needs to be removed from the ag first.  Step 10 is kind of a generic “how to finish teardown” step that might be too heavyweight for before step 4 but is appropriate as step 10.

**Comment by sashonk34** [comment]
Agreed on adding step 3.5.  That is exactly what we did, since we dropped back to the primary db instance in the ag, and then proceeded through the rest, leaving the rest of step 10 for the end (post-config/validation).  Worked as we expected in our environment.
