### ISSUE TITLE
Synchronization icon list

### ISSUE THREAD

**Issue by DavClk** [MicrosoftDocs/SCCMdocs#681]
would it be possible to include the icons for the different phases for SUP sync status. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e83bc71-2454-616c-db6d-838edb68e540
* Version Independent ID: d087f1df-8090-e0a3-cf7f-f66200410151
* Content: [Manage software updates synchronization - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/get-started/synchronize-software-updates)
* Content Source: [sccm/sum/get-started/synchronize-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/get-started/synchronize-software-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @DavClk for the feedback. Perhaps a note on this page with a link to the [article for icons](https://docs.microsoft.com/sccm/sum/understand/software-updates-icons) with a new section there for monitoring. From our email thread, I understand you're referring to the icons used in Monitoring > Software Update Point Synchronization Status.

**Comment by ChrisKibble** [comment]
@aczechowski, aren't these just the generic Green Checkmark or Red X used through the console, or are there others that I may have never seen?  If so, do we already have something we can just point to for generic pass/fail icons?

**Comment by aczechowski** [comment]
There's at least one other icon type, so needs some deeper investigation to determine what are the possible icons. For example:
![image](https://user-images.githubusercontent.com/26784733/60992546-8ef18b00-a301-11e9-8e26-f7318bf8cd7f.png)

@mestew FYI

**Comment by mestew** [comment]
This one is my personal favorite: 
![image](https://user-images.githubusercontent.com/33289333/61008586-caea1780-a324-11e9-9761-89ce2b8600b7.png)

**Comment by ChrisKibble** [comment]
Oh, we're picking favorites now?  I'll have to think about my answer.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
