### ISSUE TITLE
Small change request

### ISSUE THREAD

**Issue by kerimhanif** [MicrosoftDocs/SCCMdocs#685]
"When a client uses fallback to seek content from a neighbor boundary group, the list of content source locations does not include a Peer Cache client in a neighbor boundary group. " 
We should change this to something like:
"Management point server does not return client peer cache sources from a neighboring boundary group, only distribution point servers from a neighboring boundary group will be returned." 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29b8c8d-60fa-4403-29a7-8e7c61b2f638
* Version Independent ID: c7610ca2-5607-d1fe-f629-9d0614a26569
* Content: [Client Peer Cache - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/client-peer-cache)
* Content Source: [sccm/core/plan-design/hierarchy/client-peer-cache.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/client-peer-cache.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @kerimhanif, will target to revise this along with updates for 1806 coming soon

**Comment by aczechowski** [comment]
I revised this article for 1806 release, to include this information. The content should publish soon. I'm closing this issue.
