### ISSUE TITLE
Misspelled word

### ISSUE THREAD

**Issue by NelsonSierra** [MicrosoftDocs/SCCMdocs#686]
First Paragraph "....or network IP address that is identified by the Configuratoin Manager client that is installed on the device."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bfeaa2f-4365-4907-9fbf-370b3900a337
* Version Independent ID: b40e58d6-fe71-fa1c-eb65-53286e184285
* Content: [Define boundaries - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/boundaries)
* Content Source: [sccm/core/servers/deploy/configure/boundaries.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/boundaries.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @NelsonSierra. 
Did you know that if you click Edit on the page, you can submit the change yourself? This is a great simple one to get started! 😄 See [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute) for more information.

**Comment by missmatsuko** [comment]
Looks like this was fixed in #712

**Comment by aczechowski** [comment]
Indeed, thanks for the reminder @missmatsuko. I'm closing this issue.
