### ISSUE TITLE
Voting: Allow deployments using application model to be installed from DP rather than downloaded to ccmcache folder

### ISSUE THREAD

**Issue by LUCScape** [MicrosoftDocs/SCCMdocs#690]
Can vote for feature on UserVoice:
Allow deployments using application model to be installed from DP rather than downloaded to ccmcache folder
https://configurationmanager.uservoice.com/forums/300492-ideas/suggestions/8875516-allow-deployments-using-application-model-to-be-in

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b49b7692-2fba-a5b6-cc24-3b2621b7f5dd
* Version Independent ID: bbc48abf-20cb-18f4-0db4-467cb0408b30
* Content: [Manage distribution points - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/install-and-configure-distribution-points)
* Content Source: [sccm/core/servers/deploy/configure/install-and-configure-distribution-points.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/install-and-configure-distribution-points.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for taking the time to provide feedback on Configuration Manager! This is an interesting feature idea, and it looks like you've already given it directly to the engineering team on UserVoice. I'm closing this issue as there's nothing actionable for docs at this time.
