### ISSUE TITLE
Missing precision about workloads.

### ISSUE THREAD

**Issue by mathieudesjardins** [MicrosoftDocs/SCCMdocs#694]
There is no list of all the available workloads or at least a text to specify that Intune Configuration Policies will not be applied once the ConfigMgr client will be installed because it is not one of the workloads that are sent to Intune. Once you understand the behavior, it is absolutely normal but when you have no idea of what workloads are available or what is a workload, you are missing something important.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1f1c30-04ba-c53a-a54e-a6ca46729486
* Version Independent ID: a46c4692-8887-04b0-13ef-60623d6a7818
* Content: [Switch Configuration Manager workloads to Intune - Configuraton Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/co-management-switch-workloads#workloads-able-to-be-transitioned-to-intune)
* Content Source: [sccm/core/clients/manage/co-management-switch-workloads.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/co-management-switch-workloads.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback @mathieudesjardins. We are hoping to revise this page in the next few months.

**Comment by aczechowski** [comment]
I'm closing this issue. A big revision to the co-management content will publish soon and address this issue. After the new content publishes, if you think this topic needs further clarification, please file a new issue on the new article.
