### ISSUE TITLE
Remove the Windows 10 1607 client requirement 

### ISSUE THREAD

**Issue by kerimhanif** [MicrosoftDocs/SCCMdocs#699]
LEDBAT team says we should remove the Windows 10 1607 client requirement from https://docs.microsoft.com/en-us/sccm/core/get-started/capabilities-in-technical-preview-1805#enable-distribution-points-to-use-network-congestion-control 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a504ecc8-34dd-2827-660a-0e5303e88e49
* Version Independent ID: 79ba1a30-59d4-2fd0-f73d-4c1e9fcada74
* Content: [Technical Preview 1805 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/capabilities-in-technical-preview-1805#enable-distribution-points-to-use-network-congestion-control)
* Content Source: [sccm/core/get-started/capabilities-in-technical-preview-1805.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/capabilities-in-technical-preview-1805.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Fixed with linked internal pull request. *Once merged*, this change should be live with the next daily publishing process. Right now that *should* be tomorrow (Wednesday, 22 August) around 11:00 Pacific time. I'm closing this issue.
