### ISSUE TITLE
LEDBAT in Windows Server 2016

### ISSUE THREAD

**Issue by arwidmark** [MicrosoftDocs/SCCMdocs#702]
As of the July 2018 CU (KB4284833), LEDBAT is also available in Windows Server 2016.

**Comment by aczechowski** [comment]
Thanks @arwidmark for filing this. We're working closely with the Windows team on our documentation for this feature. I had an issue in our private repository tracking this topic, but will close that and use this one instead. :)

**Comment by aczechowski** [comment]
See linked duplicate issue. To be clear: SCCM 1806 currently only supports Windows Server version 1709 with this setting. While Server 2016 technically supports LEDBAT, it's not yet supported with SCCM.

**Comment by arwidmark** [comment]
The irony is that while apparently being supported, Windows Server, version 1709 is the one version you didn’t test, and that doesn't work because of a bug in the ConfigMgr 1806 LEDBAT configuration. Windows Server 2016 works just fine.

**Comment by aczechowski** [comment]
Sorry that you're having problems with it. In talking with the engineers, the bugs have been addressed with SCCM 1806 and Windows Server 1709, but there are still open issues with SCCM 1806 and Server 2016. If you are having issues, please file [Product feedback]( https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) so that it gets directly into the hands of the engineers.

**Comment by aczechowski** [comment]
I was reminded that this is unresolved.

Minimum requirements for LEDBAT support in SCCM:
- SCCM 1806 GA
    - Windows Server, version 1709 or later
- SCCM 1806 with update rollup (4462978), or later
    - Windows Server, version 1709 or later
    - Windows Server 2016 with the following updates:
        - KB4132216
        - KB4284833 
- SCCM 1810 or later, the same as above plus:
    - Windows Server 2019

**Comment by Brenduns** [comment]
Closing this issue, as content  for using LEDBAT with SCCM was updated on Monday, 6 May, via another Github issue. 

The details  appear at https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/install-and-configure-distribution-points#bkmk_config-general
