### ISSUE TITLE
Information regarding which antimalware products are automatically uninstalled

### ISSUE THREAD

**Issue by theboymango** [MicrosoftDocs/SCCMdocs#708]
Is there no information similar to https://docs.microsoft.com/en-us/previous-versions/system-center/system-center-2012-R2/gg682067(v=technet.10)#BKMK_EndpointProtectionDeviceSettings which details those AV products that SCCM/SCEP will automatically uninstall?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f74f4a-560f-2510-1ae8-fd3976a2197e
* Version Independent ID: 0851f834-e9a1-d0a6-ee60-934bcd3a79fe
* Content: [Client settings - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/deploy/about-client-settings#automatically-remove-previously-installed-antimalware-software-before-endpoint-protection-is-installed)
* Content Source: [sccm/core/clients/deploy/about-client-settings.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/about-client-settings.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @theboymango for the feedback. Some changes are coming to this for the 1806 content very soon. So I'm closing this issue. 

In short: we don't recommend using this setting. It's a legacy option that doesn't often work with newer products.
