### ISSUE TITLE
Co-management dashboard - Azure AD Joined instead of Hybrid Azure AD Joined

### ISSUE THREAD

**Issue by lexios** [MicrosoftDocs/SCCMdocs#710]
Hello,

Although SCCM should fill n the piechart with machines that are Hybrid Azure AD joined, it shows them as Azure AD Joined. This is wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80f53e25-43cc-f91c-b247-d751993534f8
* Version Independent ID: 5a20ad59-ce85-6af6-32eb-c3efaf81e324
* Content: [Co-management Dashboard - Configuraton Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/co-management-dashboard)
* Content Source: [sccm/core/clients/manage/co-management-dashboard.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/co-management-dashboard.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
@lexios can you please clarify. Are you saying that the documentation is wrong, or the dashboard itself is displaying incorrectly?

**Comment by aczechowski** [comment]
I'm closing this issue. If you're referring to something in the documentation, please reopen and clarify. If you're referring to the product itself, please share [product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback).
