### ISSUE TITLE
Incorrect Deployment Settings Checkbox Name for “Pre-deploy software to the user’s primary device”

### ISSUE THREAD

**Issue by jamescavery** [MicrosoftDocs/SCCMdocs#713]
The documentation shows "Deploy automatically according to schedule whether or not a user is logged on:" and it should be “Pre-deploy software to the user’s primary device”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58bf38ca-c7d6-50e3-9a88-32313f789d62
* Version Independent ID: 393cd01c-1b5f-086a-33cc-28a86a26e303
* Content: [Deploy applications - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/deploy-applications)
* Content Source: [sccm/apps/deploy-use/deploy-applications.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/deploy-applications.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jamescavery for noticing and filing feedback. Refresh the page. :) I just revised the article for 1806 content, and included that revision. I'm closing this issue.
