### ISSUE TITLE
consolidate all internet access requirements

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#714]
The [ports](https://docs.microsoft.com/sccm/core/plan-design/hierarchy/ports) doc doesn't include any URLs. The following articles include URLs that are needed for various features:
- [Service connection point](https://docs.microsoft.com/sccm/core/servers/deploy/configure/about-the-service-connection-point#bkmk_urls)
- [Software updates](https://docs.microsoft.com/sccm/sum/plan-design/plan-for-software-updates#restrict-access-to-specific-domains)
- [CMG](https://docs.microsoft.com/sccm/core/clients/manage/cmg/plan-cloud-management-gateway#internet-access-requirements)

Consolidate all needed URLs, sectioned by feature, to a single page. Perhaps create a new article instead of overloading the ports article.

**Comment by aczechowski** [comment]
From bug 521456, rename "Microsoft Intune" section to something like "Cloud Services", as it applies elsewhere.

**Comment by aczechowski** [comment]
From #1316, make sure to cross-reference with the following article:

* Content: [Proxy server support - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/network/proxy-server-support)
* Content Source: [sccm/core/plan-design/network/proxy-server-support.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/network/proxy-server-support.md)

**Comment by Stroell** [comment]
Please don´t forget O365 Updates. They are missing [here ](https://docs.microsoft.com/de-de/sccm/sum/plan-design/plan-for-software-updates#restrict-access-to-specific-domains) as well

**Comment by sonya1st** [comment]
On Jun 19, 2019 4:16 PM, James Dunn <notifications@github.com> wrote:

Closed #714<https://github.com/MicrosoftDocs/SCCMdocs/issues/714>.

**Comment by aczechowski** [comment]
This issue is closed because I've created a new article to address it. The new article will publish live tomorrow (Thursday, 20 June) around 11am Pacific at the following address: https://docs.microsoft.com/sccm/core/plan-design/network/internet-endpoints
