### ISSUE TITLE
Document the operators

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#720]
From [Twitter](https://twitter.com/bflegg/status/1025128704068935680) with Brett:

Document our operators - 1806 it is a bit limited but can extend as needed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c8158c-1c8e-1567-d96d-222f5b4aec21
* Version Independent ID: f6674943-3564-2250-2334-b88c42f3a8a6
* Content: [CMPivot for real-time data - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/cmpivot#feedback)
* Content Source: [sccm/core/servers/manage/cmpivot.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/cmpivot.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by JordanTheITGuy** [comment]
Thank you sir much appreciated.

**Comment by aczechowski** [comment]
Looks like Meghan already did this, closing
