### ISSUE TITLE
Hello. From my Microsoft account!

### ISSUE THREAD

**Issue by ArnfinnA** [MicrosoftDocs/SCCMdocs#726]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0144c22-6123-7fc0-e653-321cfaf9fe56
* Version Independent ID: a32f1b70-7e08-8e58-b8a0-92a7ae4efe0d
* Content: [Introduction - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/understand/introduction)
* Content Source: [sccm/core/understand/introduction.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/introduction.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Locking and closing this issue
