### ISSUE TITLE
Ignore some users for UDA? 

### ISSUE THREAD

**Issue by rasldasl** [MicrosoftDocs/SCCMdocs#729]
We have many users who have two accounts, one is normal and the other sort of a "technician" account. I would like to configure UDA to ignore the "technician" accounts as they are used in a run-as capacity or when setting up a machine for another user. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29b8309-10a5-f867-546e-ebcd3669253d
* Version Independent ID: 10aa34a9-3cbf-b5b6-5ce6-c4739653477e
* Content: [Link users and devices with user device affinity - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/link-users-and-devices-with-user-device-affinity)
* Content Source: [sccm/apps/deploy-use/link-users-and-devices-with-user-device-affinity.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/link-users-and-devices-with-user-device-affinity.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by AdamGrossTX** [comment]
Consider posting this to UserVoice as product feedback for possible future enhancement. https://configurationmanager.uservoice.com

**Comment by Shloeb** [comment]
Maybe, make sure that those "technician" accounts are not discovered in SCCM, so they are not assigned as primary users for the devices by "mistake"

**Comment by rasldasl** [comment]
@AdamGrossTX I found this and voted for it. Thanks!
[https://configurationmanager.uservoice.com/forums/300492-ideas/suggestions/14819547-user-device-affinity-exceptions](url)

@Shloeb I don't think we can do this as we make certain apps available to those user accounts.

**Comment by aczechowski** [comment]
Thanks @rasldasl for sharing your idea, I'm glad you found it on UserVoice. And thanks to @AdamGrossTX and @Shloeb for your help!
