### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/SCCMdocs#733]
Under "Examples" the first example should be setupdl, not setupd

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc31b4b-0600-707c-a8e7-d512d4d1a1f3
* Version Independent ID: 46eb3b49-548c-da2d-db55-01bef95ee4d0
* Content: [Setup Downloader - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/setup-downloader)
* Content Source: [sccm/core/servers/deploy/install/setup-downloader.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/setup-downloader.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Skatterbrainz for catching this. It looks like @AdamGrossTX already submitted an edit for this! :)

**Comment by jocasti** [comment]
Fixed by https://github.com/MicrosoftDocs/SCCMdocs/pull/734

**Comment by aczechowski** [comment]
Yes, thanks! Closing
