### ISSUE TITLE
BranchCache Note error

### ISSUE THREAD

**Issue by Phil2Pint** [MicrosoftDocs/SCCMdocs#735]
Doc states - "Starting in version 1802, Windows BranchCache is always enabled on clients." Which is not true, it's the deployments/deployment types that are always enabled. Clients still have to be enabled via Client Settings. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29b8c8d-60fa-4403-29a7-8e7c61b2f638
* Version Independent ID: c7610ca2-5607-d1fe-f629-9d0614a26569
* Content: [Client Peer Cache - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/client-peer-cache)
* Content Source: [sccm/core/plan-design/hierarchy/client-peer-cache.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/client-peer-cache.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Yes, good clarification @Phil2Pint.

**Comment by aczechowski** [comment]
I fixed this with an internal update to this article that's currently in review. It should publish live by the end of this week. I'm closing this issue.
