### ISSUE TITLE
Note about users enrolling in Intune

### ISSUE THREAD

**Issue by shburbid** [MicrosoftDocs/SCCMdocs#738]
Add a note near the top explaining that users may enroll into Intune SA even if they have been blocked through the ConfigMgr console. The recommendation for this is to not license the unwanted users for Intune. Without a license, they will not be able to enroll.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4913cd11-dd09-791f-af96-9849efa08ef9
* Version Independent ID: 4e271b5d-8d9f-7837-867e-1fc1fffd3242
* Content: [Change the MDM authority for specific users (mixed MDM authority) - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/migrate-mixed-authority)
* Content Source: [sccm/mdm/deploy-use/migrate-mixed-authority.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/migrate-mixed-authority.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @shburbid for filing this :)

**Comment by aczechowski** [comment]
Fixed with linked internal pull request. *Once merged*, this change should be live with the next daily publishing process. Right now that *should* be tomorrow (Wednesday, 22 August) around 11:00 Pacific time. I'm closing this issue.
