### ISSUE TITLE
Overlapping Boundaries - nearest server

### ISSUE THREAD

**Issue by rasldasl** [MicrosoftDocs/SCCMdocs#739]
How does the client determine the nearest server? For example, if client is a boundary/boundary group for a physical location that has a DP and also in a boundary group covering multiple physical sites which will it choose? Does it matter if one boundary is an IP subnet and one is an AD site? Will one be preferred over the other? 

>**Overlapping boundaries**
>Configuration Manager supports overlapping boundary configurations for content location. When the client network location belongs to multiple boundary groups:
>
> - When a client requests content, Configuration Manager sends the client a list of all distribution points that have the content.
> - When a client requests a server to send or receive its state migration information, Configuration Manager sends the client a list of all state migration points associated with a boundary group that includes the current network location of the client.  
>
>This behavior enables the client to select the nearest server from which to transfer the content or state migration information.

(admin edit: clarifying the quoted text, added anchor in link below)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7db5025d-eff5-5acb-dd57-0895828e1657
* Version Independent ID: 1b5e1df8-e30a-6eef-b5c6-5f3a4c89131c
* Content: [Configure boundary groups - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/boundary-groups#overlapping-boundaries)
* Content Source: [sccm/core/servers/deploy/configure/boundary-groups.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/boundary-groups.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
