### ISSUE TITLE
Migrate SQL Views content

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#740]
From [previous version content](https://docs.microsoft.com/en-us/previous-versions/system-center/system-center-2012-R2/dn581954(v=technet.10))

- What content to keep/migrate?
- What's the target structure, path, and TOC? (Under develop with SDK content?)
- How to address new content delta?

**Comment by raghuke** [comment]
From reporting perspective, we can take all of it and make updates from 2012 version to current branch.  AFAIK, in current branch we have added new but have not removed anything from old.  Once we have done that, we can update with any new views created.  Also, I mentioned, we can use the SQL query and put it in the overview as a generic rule of thumb for catch all scenarios.

**Comment by aczechowski** [comment]
Core content is migrated, now available here:
https://docs.microsoft.com/sccm/develop/core/understand/sqlviews/create-custom-reports-using-sql-server-views
Closing issue 😄
