### ISSUE TITLE
cmpivot related log files

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#742]
The logs for troubleshooting are:
**Server side**:
- Smsprov.log
- bgbserver.log
- Statesys.log

**Client side**:
- CcmNotificationAgent.log
- Scripts.log
- StateMessage.log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c8158c-1c8e-1567-d96d-222f5b4aec21
* Version Independent ID: f6674943-3564-2250-2334-b88c42f3a8a6
* Content: [CMPivot for real-time data - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/cmpivot#feedback)
* Content Source: [sccm/core/servers/manage/cmpivot.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/cmpivot.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by eugenevalley** [comment]
Aaron, you may want to add rcmctrl.log to the list of troubleshooting logs. This is where we log the info for the creation of the CMPivot views.

**Comment by aczechowski** [comment]
@eugenevalley can you please file a new issue with that feedback? We'll never act upon a comment in a closed issue
