### ISSUE TITLE
Prerequites in complex environment

### ISSUE THREAD

**Issue by AndresPae** [MicrosoftDocs/SCCMdocs#747]
Hi.
What are communication requirements between Workstation(where running SCCM console)  - SCCM server - Endpoint when using CM pivot ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c8158c-1c8e-1567-d96d-222f5b4aec21
* Version Independent ID: f6674943-3564-2250-2334-b88c42f3a8a6
* Content: [CMPivot for real-time data - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/cmpivot)
* Content Source: [sccm/core/servers/manage/cmpivot.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/cmpivot.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @AndresPae for the feedback. That's good additional detail to include. CMPivot uses the client notification channel, which is on port 10123 by default. For reference, you can see that in the [Ports](https://docs.microsoft.com/sccm/core/plan-design/hierarchy/ports#BKMK_PortsClient-MP) article.

**Comment by aczechowski** [comment]
This issue is closed because @mestew made changes to this article, which should publish later today.
