### ISSUE TITLE
Obtaining media for other licensing types

### ISSUE THREAD

**Issue by troyphil** [MicrosoftDocs/SCCMdocs#749]
Please specify how to obtain installation media and license key when ConfigMgr is licensed via Intune, EMS,  Microsoft 365 etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 295caa58-e5d5-4b95-9287-62af7e118241
* Version Independent ID: 77e831e1-ff78-2b4e-2d90-341bb4c3b3a4
* Content: [Get installation media - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/install/get-install-media)
* Content Source: [sccm/core/servers/deploy/install/get-install-media.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/install/get-install-media.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @troyphil for the feedback. I think adding a note to this page would be beneficial. 

To help answer your question, see the information in this FAQ: https://docs.microsoft.com/en-us/sccm/core/understand/product-and-licensing-faq#bkmk_csp.

This is also related to issue #493.

**Comment by troyphil** [comment]
Not sure how difficult a change it is, but it would be a better experience for the end user to not  need to contact support - maybe publish ConfigMgr license key in Intune portal (not sure where ATA would make sense)

**Comment by aczechowski** [comment]
Thanks @troyphil for the feedback. For product feedback, please share that directly with the engineering team. For more information, see [product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback).
