### ISSUE TITLE
Supported or not supported?

### ISSUE THREAD

**Issue by Stroell** [MicrosoftDocs/SCCMdocs#751]
Here it states "For example, restoring a database from SQL Server 2014 to SQL Server 2016 isn't supported" However here https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/support-for-sql-server-versions#upgrade-options-for-sql-server you will find "Upgrade options for SQL Server: Use backup and recovery". Is it supported or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2bf93f-aa79-ef8a-ee16-c1ed27eb8e13
* Version Independent ID: d64f0463-a1e0-b80b-f16b-39f54dd87154
* Content: [Site recovery - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/recover-sites)
* Content Source: [sccm/core/servers/manage/recover-sites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/recover-sites.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Zebbelin for calling out that discrepancy. I want to confirm what I think is the right answer, stay tuned.

**Comment by JOBTheITGuy** [comment]
Aczechowski - Did you ever confirm if this is supported?

**Comment by aczechowski** [comment]
Thanks @JOBTheITGuy for the reminder. There's not a definitively clear response on this, as these statements have actually flipped a few times. Microsoft Support generally asks customers to use the same version to avoid any SQL problems. After discussion and testing, we changed the statement from "same version" to "any version". So I think the safest route is same version, but across version *should* work (and we've seen it work in some testing).

**Comment by aczechowski** [comment]
I revised this article, the changes will publish live on Monday 8/26 around 11am Pacific time.
