### ISSUE TITLE
Deprecation of Linux/Unix client

### ISSUE THREAD

**Issue by drockwood94** [MicrosoftDocs/SCCMdocs#752]
Does the deprecation of the Linux/Unix client include the Macintosh client, or will that one continue to be developed after this year?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b4b8caa-0b30-fba6-c031-d08b2facd201
* Version Independent ID: b0c6c951-511b-5920-8e24-656b6dc53ab0
* Content: [New version 1802 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/whats-new-in-version-1802)
* Content Source: [sccm/core/plan-design/changes/whats-new-in-version-1802.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/changes/whats-new-in-version-1802.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I should have closed this a while ago. We did release an update to the Mac client for Catalina support. See [support configurations for clients](https://docs.microsoft.com/mem/configmgr/core/plan-design/configs/supported-operating-systems-for-clients-and-devices#mac-computers)
