### ISSUE TITLE
Log Files

### ISSUE THREAD

**Issue by felymich** [MicrosoftDocs/SCCMdocs#753]
Hello, 
I will be excellent to add a link to the log files used by the deployment of a software update during the process to make the troubleshooting easier.

Thanks,
Dom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e48c839-f6ee-2d03-6f5b-e0ffb05ec595
* Version Independent ID: 13547c80-3295-92e8-59c9-20e99948f2e8
* Content: [Monitor software updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/monitor-software-updates)
* Content Source: [sccm/sum/deploy-use/monitor-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/monitor-software-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @felymich for the feedback. Agreed, that's definitely something worthwhile. 

Also need to add a link to the [Software Updates Management whitepaper](https://www.microsoft.com/download/confirmation.aspx?id=44578). While it was originally written for Configuration Manager 2012 R2, most of the concepts are also applicable to Configuration Manager current branch.
