### ISSUE TITLE
Clarify UI columns

### ISSUE THREAD

**Issue by MSGriz** [MicrosoftDocs/SCCMdocs#755]
for Cloud DP there is a non-default column for data egress (as well as a few others).  It is not explained in this doc, and the time frame that it covers (1 day, 30 days, lifetime) is not clarified either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44cd259e-b744-f8db-431a-06e884e8349a
* Version Independent ID: 6ee1e977-135e-f83d-77d7-e0ad0e018c67
* Content: [Install cloud distribution points - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/install-cloud-based-distribution-points-in-microsoft-azure#bkmk_monitor)
* Content Source: [sccm/core/servers/deploy/configure/install-cloud-based-distribution-points-in-microsoft-azure.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/install-cloud-based-distribution-points-in-microsoft-azure.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I just added a note for this, it will publish live tomorrow.
