### ISSUE TITLE
question regarding data warehouse db size

### ISSUE THREAD

**Issue by spencer987** [MicrosoftDocs/SCCMdocs#756]
do you have Information how to size the db for 2000 machines with daily sync enabled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a4274db-5f5b-c169-c69e-68146e92836f
* Version Independent ID: a28966e9-88cc-6910-c270-7f14818f832a
* Content: [Data warehouse - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/data-warehouse)
* Content Source: [sccm/core/servers/manage/data-warehouse.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/data-warehouse.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback @spencer987. This information is good detail to include. The general recommendation is to have the same configuration as your site database. While the data warehouse will be smaller at first, it will grow overtime.

**Comment by aczechowski** [comment]
Closing this issue. I made an update that will publish soon with 1810 content
