### ISSUE TITLE
Allow extended cloud check to block and scan for up to (seconds) = 0 ?

### ISSUE THREAD

**Issue by josesonic** [MicrosoftDocs/SCCMdocs#763]
Hello @aczechowski, Jose from IU here.

Can I assume "Allow extended cloud check to block and scan for up to (seconds)" = 0 would mean the extended cloud check to block and scan could take an infinite amount of time? If so, is there a default time out?

Sincerely,
Jose

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5215a151-f390-9123-5384-516ec3ed3078
* Version Independent ID: 62124728-8029-4565-79a6-88f842ad1e73
* Content: [Endpoint Protection antimalware policies - Configuration Manager](https://docs.microsoft.com/en-us/sccm/protect/deploy-use/endpoint-antimalware-policies#cloud-protection-service)
* Content Source: [sccm/protect/deploy-use/endpoint-antimalware-policies.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/endpoint-antimalware-policies.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @josesonic for the feedback. I tracked down some more information that I think will be good to include. This setting is always a default 10 seconds plus the time you specify. So if you set this value to 0, then the block and scan waits for 10 seconds. If you specify 50, there is a 60 second hold time.
