### ISSUE TITLE
Additional Requirements?

### ISSUE THREAD

**Issue by SCCMWalker** [MicrosoftDocs/SCCMdocs#765]
I found several things not called out here that in my environment needed to be modified. Hopefully this helps someone.

ADK needs to be installed on the new passive site server. In this article and the prerequisite for installing a primary site server it's not specified. The prerequisite check does show this but it would be nice to have it documented so we can install it before we get to that step.

I could not get the "SQL Server sysadmin rights" prerequisite to pass until I enabled SSL3.0 TLS 1.0 and TLS 1.1. In my environment we had these all disabled. There was no indication within the prerequisite check that was the issue. I was receiving errors in the event viewer "A fatal error occurred while creating a TLS client credential. The internal error state is 10013." Most likely I enabled too much in a shotgun blast attempt to resolve it but it certainly wouldn't pass with just 1.2 enabled for me.

Additionally I needed to give the active primary site server's machine account admin rights on the content library server. Before doing this (and with having full rights on the file share) I was receiving errors that the share was unreachable. This might be a specific limitation I have in my environment and there might be a better way to resolve this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c416209-7476-14b2-a60b-9f3477dc79be
* Version Independent ID: 765534af-f933-c768-0994-fa8d0a5712a0
* Content: [Site server high availability - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/site-server-high-availability)
* Content Source: [sccm/core/servers/deploy/configure/site-server-high-availability.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/site-server-high-availability.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
@SCCMWalker thanks for sharing this feedback! It's probably good to be more explicit on these requirements; right now it's implicit to configure the passive mode server like any new site server. Same with the content library server.

As for the TLS 1.2 issue - I suggest filing that as [product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback). I think that engineering should investigate that, I would expect this feature to work with only TLS 1.2 enabled.

**Comment by SCCMWalker** [comment]
Thanks for the quick feedback. I will try and do the product feedback today. 

It would be nice to be able to use this page and the pages linked as a guide but without having all the information it requires a lot of tribal knowledge and stopping to search for steps not called out here and on linked pages.  This made the process a bit longer than needed, if the ADK for instance had been called out as a prerequisite in the "prerequisites for setting up a primary site" documentation I would have done that while waiting for other steps to finish, such as the remote content manger transferring over to a new DFS.

Just my two cents on the subject. I appreciate what you and the rest of the MS team are doing for the SCCM product and I am very excited to get this up and running in production.

**Comment by aczechowski** [comment]
Made revisions to this article and included this feedback, so closing this issue. The changes should publish later today or tomorrow morning at the latest.
