### ISSUE TITLE
IP Helper vs. DHCP Options

### ISSUE THREAD

**Issue by Zebbelin** [MicrosoftDocs/SCCMdocs#766]
It would be great to have a clear statement in the SCCM Documentation, that only IP Helper is supported as PXE Method and DHCP Options should not be used 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3527c358-cf3f-07ec-1cb8-88982ff99122
* Version Independent ID: 2c618192-bb71-d934-d20e-1ceb15cb2e01
* Content: [Use PXE for OSD over the network - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network)
* Content Source: [sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Zebbelin for the feedback. I thought we had some statement on this topic already, but I can't find it. I'm checking with some other folks what I'm remembering. Stay tuned...

**Comment by aczechowski** [comment]
Will be fixed by linked pull request. Closing this issue.

**Comment by santoshseth** [comment]
Hi, Has this been fixed?

**Comment by aczechowski** [comment]
@santoshseth yes. The following note was added to this section: https://docs.microsoft.com/sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network#BKMK_Configure

> Note
> When configuring a single PXE enabled distribution point to support multiple subnets it is not supported to use DHCP options. Configure IP helpers on the routers to allow PXE requests to be forwarded to your PXE enabled distribution points.
