### ISSUE TITLE
Missing workloads in next steps

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#769]
Next steps section includes links to Intune content for workloads, but not 1806 workloads.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a1f1c30-04ba-c53a-a54e-a6ca46729486
* Version Independent ID: a46c4692-8887-04b0-13ef-60623d6a7818
* Content: [Switch Configuration Manager workloads to Intune - Configuraton Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/co-management-switch-workloads#feedback)
* Content Source: [sccm/core/clients/manage/co-management-switch-workloads.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/co-management-switch-workloads.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by MJ-Webber** [comment]
Still waiting on Next Steps for workloads such as Device Configuration. Additionally, Device Configuration workload requires additional detail such as: Any possible side-effects of workload migration affecting existing systems; reasoning for the requirement to also migrate Endpoint Protection and Resource Access policies, etc.

**Comment by aczechowski** [comment]
Thanks for the feedback @MJ-Webber. I'm hoping to work on the co-management content along with the 1810 release in the next several months.

**Comment by aczechowski** [comment]
I'm closing this issue. A big revision to the co-management content will publish soon and address this issue.
