### ISSUE TITLE
Question on the pre-cache feature

### ISSUE THREAD

**Issue by rtruss** [MicrosoftDocs/SCCMdocs#770]
I have been experimenting with this and have noticed that there may be a 'flaw' in the process?  For instance I am upgrading a Japanese OS (not English with a LP installed) and if I follow the steps within this doc it fails to upgrade.  The Language specified in the OS upgrade package does not match my locale so it never sees that the Japanese OS is needed.  My Locale is 0409 and the 'locale' of the Japanese OS is 0411. If I use this for targeting it sees a match: SELECT OsLanguage FROM Win32_OperatingSystem WHERE OsLanguage='1041' and OSArchitecture like "64%" (I discovered that OSArch reports quite differently from os language to os language in WMIC so using like 64% has never failed me)

So am I missing something here or is it a 'flaw'/bug?

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfe3442-b59d-0d77-d9af-f18e787ec99d
* Version Independent ID: 60cb54a2-d1fd-92b5-b027-de8a85c7af64
* Content: [Create an OS upgrade task sequence - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system)
* Content Source: [sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @rtruss for taking the time to share this with the Configuration Manager documentation team. I'm assuming you're talking about the section to [Configure pre-cache content](https://docs.microsoft.com/sccm/osd/deploy-use/create-a-task-sequence-to-upgrade-an-operating-system#configure-pre-cache-content)? I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time. If I'm mistaken, or after further investigation there's specifically an issue with the doc content on this, please reopen this issue.

**Comment by rtruss** [comment]
I did, yes and thanks for the direction.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
