### ISSUE TITLE
Needs More Detail: Detect with Custom Script

### ISSUE THREAD

**Issue by VertigoRay** [MicrosoftDocs/SCCMdocs#773]
Specifically regarding the [To detect an application installation by using a custom script](https://docs.microsoft.com/en-us/sccm/compliance/deploy-use/create-custom-configuration-items-for-windows-desktop-and-server-computers-managed-with-the-client#to-detect-an-application-installation-by-using-a-custom-script) section ...

There's a lot to be desired. How is detection deemed "detected" or "not detected"? I assume it follows [application detection method rules](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/create-applications#bkmk_detect-script), but if so, it should be documented as so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed8d46c-8310-ef2e-dcaf-525e270dfb6d
* Version Independent ID: 97cc9d50-62d1-d05e-99bc-f930128237a9
* Content: [Create configuration items for client-managed Windows computers  - Configuration Manager](https://docs.microsoft.com/en-us/sccm/compliance/deploy-use/create-custom-configuration-items-for-windows-desktop-and-server-computers-managed-with-the-client#to-detect-an-application-installation-by-using-a-custom-script)
* Content Source: [sccm/compliance/deploy-use/create-custom-configuration-items-for-windows-desktop-and-server-computers-managed-with-the-client.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/compliance/deploy-use/create-custom-configuration-items-for-windows-desktop-and-server-computers-managed-with-the-client.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @VertigoRay for the feedback. Yeah, this article hasn't had much love for a while. This section in particular could definitely use some enhancement, like an example. I don't know when we'll get an opportunity to revise this, but will track the effort with this item.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
