### ISSUE TITLE
CMPivot status message queries / auditing?

### ISSUE THREAD

**Issue by tstolswo** [MicrosoftDocs/SCCMdocs#774]
Just installed 1806, CMPivot is amazing - I saw in the document for CMPivot the log files, but what about auditing use / status message queries for it?

Apologies if this is not the correct venue or method for such an inquiry.

**Comment by aczechowski** [comment]
Thanks @tstolswo for the feedback. Good question, I don't know, but will check. If yes, it's good addition to add to the article (especially regarding auditing). If no, I'll redirect you to the correct venue to file product feedback. :)

**Comment by aczechowski** [comment]
The audit message for CMPivot is the same as when running a script: user A has initiated the client operation type 135 on collection B. 
That's some interesting detail I can add to this article.
If you're interested in the product doing more along these lines, then see [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback).

**Comment by tstolswo** [comment]
Thanks for the prompt responses, @aczechowski; exactly what I was looking for.

**Comment by aczechowski** [comment]
Oops, lets keep the issue open. My tracking item to update the doc! :)

**Comment by aczechowski** [comment]
Meghan took care of this a while back when she created the [troubleshooting article for CMPivot](https://docs.microsoft.com/mem/configmgr/core/servers/manage/cmpivot-tsg#get-information-from-the-site-server)
