### ISSUE TITLE
Unclear when and how to use the ampersand symbol in the web server certificate

### ISSUE THREAD

**Issue by merlinfrombelgium** [MicrosoftDocs/SCCMdocs#780]
From SCCMdocs/sccm/core/plan-design/network/pki-certificate-requirements.md
PKI Certificates for Servers, first section

> If the site system accepts connections from both the Internet and the intranet, both the Internet FQDN and the intranet FQDN (or computer name) must be specified by using the ampersand (&) symbol delimiter between the two names.

I have not found any reference to using the '&' delimiter in a certificate subject or SAN attribute, nor am I an expert on PKI. First doubt I have is whether this scenario applies when using the CMG. Does the use of CMG imply that the site system accepts connections from the internet (it would seem so) or does that apply more/exclusively to an IBCM scenario?
Second clarification I'd like, is on how to use the ampersand in the web server certificate request. Would that be in the subject or SAN field? CN, DNS or Full DN?

(admin edit 8/23 with metadata block for article linking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e6c9b24-f28e-464b-d625-53b7453082b9
* Version Independent ID: 1a657226-b1e7-e14f-656c-dee37cab5beb
* Content: [PKI certificate requirements - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/network/pki-certificate-requirements)
* Content Source: [sccm/core/plan-design/network/pki-certificate-requirements.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/network/pki-certificate-requirements.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @merlinfrombelgium for the feedback. A good question. This article is woefully out of date, and is on the backlog to revise, just a big project. 

To answer your specific question, that blurb is only for [internet-based client management](https://docs.microsoft.com/sccm/core/clients/manage/plan-internet-based-client-management) (in fact, as is any reference in this article for "internet" clients). It does not apply to certificates for CMG.

**Comment by aczechowski** [comment]
I'm resolving this issue in part because we moved repositories, but also because I'm going to track this work via an internal work item.

(internal reference 2841906)
