### ISSUE TITLE
duplicate URL's

### ISSUE THREAD

**Issue by cmolstad** [MicrosoftDocs/SCCMdocs#782]
In the section "Revised documentation for task sequence variables", the links to the two new articles go to to the same URL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22765ffe-cef8-a88f-5f71-00caf9b47046
* Version Independent ID: cb5ad492-39d1-f63d-0bd2-7f3a0b1d8af0
* Content: [What's new in version 1806 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/whats-new-in-version-1806#other-improvements-to-os-deployment)
* Content Source: [sccm/core/plan-design/changes/whats-new-in-version-1806.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/changes/whats-new-in-version-1806.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @cmolstad. Do you want to try clicking Edit on that article and submit the change? See [Contribute](https://docs.microsoft.com/en-us/sccm/core/understand/use-docs#bkmk_contribute) for the basic steps. The first link should point to this article: https://docs.microsoft.com/sccm/osd/understand/using-task-sequence-variables.

**Comment by cmolstad** [comment]
Change submitted!
On 8/23/2018 4:15:53 PM, Aaron Czechowski <notifications@github.com> wrote:
Thanks @cmolstad [https://github.com/cmolstad]. Do you want to try clicking Edit on that article and submit the change? See Contribute [https://docs.microsoft.com/en-us/sccm/core/understand/use-docs#bkmk_contribute] for the basic steps. The first link should point to this article: https://docs.microsoft.com/sccm/osd/understand/using-task-sequence-variables [https://docs.microsoft.com/sccm/osd/understand/using-task-sequence-variables].

**Comment by aczechowski** [comment]
Hi @cmolstad, thanks for your willingness to help, but I haven't seen any pull requests yet. Make sure you create the pull request after you propose the change.

**Comment by cmolstad** [comment]
Sorry about that.  I just did a pull request a bit ago and it said I could merge it without issues so I did that.

**Comment by aczechowski** [comment]
Something's awry. There's no [pull request](https://github.com/MicrosoftDocs/SCCMdocs/pulls) (even closed). Go through the process again, and make sure to create the pull request. There are actually *two* buttons for **Create pull request**. See Step 5 of the [Basic steps to contribute to SCCMdocs](https://docs.microsoft.com/en-us/sccm/core/understand/use-docs#bkmk_contribute). 

We're almost there! Thanks for sticking with this. The first time is always a good learning experience.

**Comment by jocasti** [comment]
@aczechowski This issue should be fixed. Verified the links are now valid for the referenced articles.

**Comment by aczechowski** [comment]
Thanks @jocasti for catching this. Yes, it was fixed by #787. Closing
