### ISSUE TITLE
CMPivot failure

### ISSUE THREAD

**Issue by terjohnny** [MicrosoftDocs/SCCMdocs#784]
I have a weird issue regarding CMPivot, it runs but it returns failure on most computers in the environment. The one that work are just random and a small percentage of the PCs (10%), all the logs seem to look OK. Are there any known bugs to this? Any checks worth doing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c8158c-1c8e-1567-d96d-222f5b4aec21
* Version Independent ID: f6674943-3564-2250-2334-b88c42f3a8a6
* Content: [CMPivot for real-time data - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/cmpivot)
* Content Source: [sccm/core/servers/manage/cmpivot.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/cmpivot.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @terjohnny for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:  
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced,   knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.   

I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by terjohnny** [comment]
Actually there is something that you should update in the documentation. Although you mention that some features work only with Powershell 5.0, you don't mention the minimum version to use other features. In my case, I had windows 7 with Poweshell version 2.0 and nothing works. I upgraded to version 4.0 and most commands work. Can you add a minimum powershell version required by CMPivot?

**Comment by aczechowski** [comment]
Thanks for the followup. I'm reopening this issue, and will check on the prereq.

**Comment by russrimm** [comment]
Beware if you use bit9 or similar technologies, you'll get alerts (and a lot of helpdesk calls!) from all clients about a script being blocked in c:\windows\ccm\scriptstore as well which can also prevent successful execution of the CMPivot scripts.

**Comment by aczechowski** [comment]
Thanks @russrimm, good tip!

**Comment by aczechowski** [comment]
This issue is closed because @mestew made changes to this article, which should publish later today.
