### ISSUE TITLE
VPN authentication with EAP PEAP is not  applied to the client

### ISSUE THREAD

**Issue by scoarem** [MicrosoftDocs/SCCMdocs#785]
When creating a windows 10 VPN profile the authentication with EAP PEAP the settings is not correctly applied to the client devices. 
The client gets the EAP-MSCHAP v2 as the authentication protocol.
See the details below.

----
I created a new VPN profile in SCCM, with the settings form below.
  Success: The Create VPN Profile Wizard completed successfully.
 
 New VPN profile will be saved as:
·	Profile name: VPN.company.be
·	Description:
 
 The following platform versions are supported:
·	All Windows 10 (64-bit)
·	All Windows 10 (32-bit)
·	All Windows 10 (ARM64)
·	All Windows 10 Holographic Enterprise and higher
·	All Windows 10 Holographic and higher
·	All Windows 10 Team and higher
·	All Windows 10 Mobile and higher
 VPN Profile Connection Settings:
·	Connection type: IKEv2
·	Server List:
·	Friendly Name: vpn.company.be
·	Address: vpn.company.be
 
 VPN Profile Authentication Settings:
·	Authentication method: Microsoft protected EAP (PEAP)
·	Remember credential: Yes
·	Select a client certificate for client authentication: (not selected)
·	Enterprise Data Protection Primary Domain :
 
 VPN Profile Proxy Settings:
·	Use automatic detection script: No
·	Use a proxy server: No
 
 These desktop applications will automatically connect to this VPN:
 
 These universal applications will automatically connect to this VPN:

 ----

The VPN profile is deployed to the clients and the device compliance is successfully.
When viewing the VPN settings on the client the authentication is set to EAP-MSCHAP v2 and not the EAP PEAP configured in SCCM.

Windows stores the VPN settings in the %userprofile%\AppData\Roaming\Microsoft\Network\Connections\Pbk file.
When viewing the configuration the CustomAuthKey is set to 0. After manually changing to the correct authentication in windows 10 the CustomAuthKey is set to 25.
It looks like the CustomAuthKey is not set correctly by SCCM.
I use the latest 1806 version of SCCM and the client are windows 10 1803 or windows 10 1709.
Is this a bug or is there a solution for this issue?

Kinds Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00dc376a-59ae-7dae-847b-71a21b2e22b8
* Version Independent ID: d22c6d38-299a-9956-b1bd-1cc07ef8daef
* Content: [How to Create VPN profiles  - Configuration Manager](https://docs.microsoft.com/en-us/sccm/protect/deploy-use/create-vpn-profiles#create-a-vpn-profile)
* Content Source: [sccm/protect/deploy-use/create-vpn-profiles.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/create-vpn-profiles.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @scoarem for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

You could also file [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) to have the engineering team take it into consideration as a bug. This option doesn't have any service level agreement as with support channels, so no guarantee that it will solve your problem.

I'm closing this issue as there's nothing actionable for docs at this time.
