### ISSUE TITLE
Add "you can" to the first sentence under the ARM section.

### ISSUE THREAD

**Issue by MCureton** [MicrosoftDocs/SCCMdocs#790]
Starting in version 1806, create a cloud distribution point using an Azure Resource Manager deployment. 

Should read Starting in version 1806, you can create a cloud distribution point using an Azure Resource Manager deployment.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd3d8fd7-a335-5975-4a96-5f33ce66751e
* Version Independent ID: 287e8c87-f76a-e4de-5698-0c80ed822eab
* Content: [Cloud distribution point - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/use-a-cloud-based-distribution-point#feedback)
* Content Source: [sccm/core/plan-design/hierarchy/use-a-cloud-based-distribution-point.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/use-a-cloud-based-distribution-point.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @MCureton for the feedback! 😄 I appreciate you taking the time to file this feedback, although I'm going to push back for the following two reasons:
- Microsoft Style to [revise weak writing](https://docs.microsoft.com/style-guide/top-10-tips-style-voice#revise-weak-writing)
- General recommendation for customers to use Azure Resource Manager deployments.
I'm going to close this issue, but let me know if you're passionate about this change.

**Comment by MCureton** [comment]
Not sure I follow the push back. I actually filed the feedback item due to the inconsistency between the CMG and CDP content. Sounds like I should have filed an item to drop the you can instead?

https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/plan-cloud-management-gateway#azure-resource-manager

Starting in version 1802, you can create the CMG using an Azure Resource Manager deployment. Azure Resource Manager is a modern platform for managing all solution resources as a single entity, called a resource group.

**Comment by aczechowski** [comment]
Yeah. And I have some revisions to make there soon, so will pick up that change then. Thanks!
