### ISSUE TITLE
Reporting Services Server name does not stay !!!

### ISSUE THREAD

**Issue by felymich** [MicrosoftDocs/SCCMdocs#791]
Hello,
for the steps:

3.On the Home tab, in the Settings group, click Report Options. 
4.Select the default report server in the list, and then click OK. If no reporting services points are listed in the list, verify that you have a reporting services point successfully installed and configured in the site. 

I am doing this to point to our Reporting Services Server but if I am going back to 4. it is gone !! with a red ! on the right... something to be checked... in front of doing this action...
Thanks,
Dom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed3637a6-0616-a14a-2864-9c7d6bbc70e0
* Version Independent ID: 7b0ddfd8-2c0f-9518-39e6-e49130ae2f58
* Content: [Configure reporting - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/configuring-reporting)
* Content Source: [sccm/core/servers/manage/configuring-reporting.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/configuring-reporting.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @felymich for sharing this feedback, and I'm sorry that you're having trouble. Can you help clarify what you mean? What do you suggest is checked before doing this action? 

Also, if you're having technical problems, I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

**Comment by felymich** [comment]
Thank you @aczechowski . 
When opening "Report Options" as describe in the article I am getting an empty field with a red exclamation mark.
![2018-08-30 11_25_52-vrpsccmpr01 - remote desktop connection](https://user-images.githubusercontent.com/24902345/44871499-75fc6000-ac82-11e8-8e12-f76d577b8f2b.png)
then I am filling up using the drop down (it is our Reporting Server)
![2018-08-30 11_28_49-vrpsccmpr01 - remote desktop connection](https://user-images.githubusercontent.com/24902345/44871588-c1167300-ac82-11e8-9f3a-cdadd34dcf23.png)
Click ok
The list of reports is refresh but still I cannot use the Create/Edit options only the Run is working...
![2018-08-30 11_32_14-vrpsccmpr01 - remote desktop connection](https://user-images.githubusercontent.com/24902345/44871694-19e60b80-ac83-11e8-86cc-8b88559d3955.png)

if I go back to Report Options I have again the same screen as before with the red exclamation mark...

Thanks,
Dom

**Comment by aczechowski** [comment]
This sounds related to issue #803, if not the same? For support requests, please use the options mentioned above. 

I'll keep this issue open to include a note similar to the warning you received. This article touches upon Report Builder version in the section to [Configure reporting to Use Report Builder 3.0](https://docs.microsoft.com/sccm/core/servers/manage/configuring-reporting#BKMK_ReportBuilder3), but we could provide further information about the versions needing to match.

**Comment by felymich** [comment]
Yes it looks like it was the same between #803 and #791. 
Report Builder works perfectly on the Reporting Server by itself...
but apparently is not accessible from the Primary Server where the console is hosted...
I can run the report from the Primary Server but that's it !

Thank you,
Dom

**Comment by yoke88** [comment]
Encounter the same problem, and i resolved my problem by:
1. Add firewall exceptions to 80,443 port on the reporting service server
2. change regedit on the server which installed ConfigMgr [Console to use report builder 3.0](https://docs.microsoft.com/sccm/core/servers/manage/configuring-reporting#BKMK_ReportBuilder3)

**Comment by aczechowski** [comment]
I revised this article, the changes will publish live around 11am Pacific time
