### ISSUE TITLE
Windows features not turned on

### ISSUE THREAD

**Issue by jose-camacaro** [MicrosoftDocs/SCCMdocs#793]
Reference: https://social.technet.microsoft.com/Forums/en-US/518aea48-fbd8-4cff-a3e9-344788a4a5b9/windows-defender-application-guard-does-hyper-v-needs-to-be-enabled-on-every-machine-in-enterprise?forum=winservermanager

It appears the expectation is that a WDAG policy deployment via ConfigMgr automatically enables both "Hyper-V" and "Windows Defender Application Guard" features. As you can see on that technet thread, I am not seeing that.

Any help is highly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19e8b884-6b28-1dd9-e049-8a996c32d118
* Version Independent ID: 211a14a2-921f-0144-104e-d9b4cffdf6a6
* Content: [Create and deploy a Windows Defender Application Guard policy - Configuraton Manager](https://docs.microsoft.com/en-us/sccm/protect/deploy-use/create-deploy-application-guard-policy)
* Content Source: [sccm/protect/deploy-use/create-deploy-application-guard-policy.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/create-deploy-application-guard-policy.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @josesonic for the feedback. I'll check on whether there are any Windows feature prerequisites that we don't explicitly document. 

I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
