### ISSUE TITLE
Details for new Software Center and App Catalog Website Point

### ISSUE THREAD

**Issue by excelsi84** [MicrosoftDocs/SCCMdocs#795]
Some more details on "In some scenarios, the new Software Center communicates with the application catalog website point." please....Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46761dfa-340e-5156-a555-455e7f953aac
* Version Independent ID: 7ebf80eb-7d7c-847e-8e90-eada2ed48359
* Content: [Deprecated features - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/deprecated/removed-and-deprecated-cmfeatures)
* Content Source: [sccm/core/plan-design/changes/deprecated/removed-and-deprecated-cmfeatures.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/changes/deprecated/removed-and-deprecated-cmfeatures.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for the feedback @excelsi84. I'll have more information published on this topic in the near future. I'll keep this issue open until I make updates, including to the [What's New](https://docs.microsoft.com/sccm/core/plan-design/changes/whats-new-in-version-1806#software-center-infrastructure-improvements) article and the core content.

**Comment by aczechowski** [comment]
I've updated this article with an internal pull request that's currently in review. It will publish by the end of next week. I'm closing this issue.
