### ISSUE TITLE
Missing PowerShell Cmdlet documentation - Set-CMTSStepSetDynamicVariable

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/SCCMdocs#798]
I in the PowerShell Configuration Manager docs here https://docs.microsoft.com/en-us/powershell/module/ConfigurationManager/, there is no documentation for Set-CMTSStepSetDynamicVariable. I attempted to comment there, but it appears that repository hasn't been updated to GitHub and the LiveFyre comments didn't seem to work.

**Comment by mumian** [comment]
I have updated the article.  It will be published today or tomorrow.
