### ISSUE TITLE
Recover Site from Database missing requirement

### ISSUE THREAD

**Issue by torontojc** [MicrosoftDocs/SCCMdocs#799]
Hi,
When restoring a database backup via 'Recover the site database using a backup set'. An error is thrown saying 'Make sure ConfigMgr database does not exist before running recovery from backup.' . It may be worth adding this requirement into the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2bf93f-aa79-ef8a-ee16-c1ed27eb8e13
* Version Independent ID: d64f0463-a1e0-b80b-f16b-39f54dd87154
* Content: [Site recovery - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/recover-sites)
* Content Source: [sccm/core/servers/manage/recover-sites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/recover-sites.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @torontojc for the feedback. I think there's mention of this in another article (I need to find the reference), but agreed that it definitely should be here as well. I think best in the procedure section.

**Comment by ChrisKibble** [comment]
@aczechowski - this is mentioned already in the "Recover the Site Database Using a Backup Set":

> Note
> If you select to restore the site database by using a backup set, but the site database already exists, the recovery fails.

Suspect this can now be closed.

**Comment by aczechowski** [comment]
Good catch, thanks @ChrisKibble. 😄 
@torontojc I'm closing this issue. If you disagree, please reopen
