### ISSUE TITLE
Registry exclusion list vs UI for duplicate hardware IDs

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#802]
Reference [BUG 2841923](https://msazure.visualstudio.com/Configmgr/_workitems/edit/2841923)
Perhaps reorder these sections, and note in "Create an exclusion list for PXE deployments" that they can just use the info in "Manage duplicate hardware identifiers" as an easier method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3527c358-cf3f-07ec-1cb8-88982ff99122
* Version Independent ID: 2c618192-bb71-d934-d20e-1ceb15cb2e01
* Content: [Use PXE for OSD over the network - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network#BKMK_PXEExclusionList)
* Content Source: [sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/deploy-use/use-pxe-to-deploy-windows-over-the-network.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by KerwinM** [comment]
The ignore list in the registry is very different from the duplicate ID list.
The ignore list will never boot a client with the listed MAC address, no matter what.
The duplicated ID list simply does will not use the MAC address to find the TS policy for a client. If there is match in the SMBIOS or if there is a TS policy for unknown machines, the client will still be allowed to boot.

**Comment by aczechowski** [comment]
I revised the article and included this information. The change will be live on or about Monday, 6 May. I'm closing this issue.
