### ISSUE TITLE
Connection Primary Server (with Console) and Reporting Server

### ISSUE THREAD

**Issue by felymich** [MicrosoftDocs/SCCMdocs#803]
Hello,
"6.Verify that status message ID 1015 is listed, which indicates that the reporting services point was successfully installed. Alternatively, you can open the Srsrp.log file, located in &lt;ConfigMgr Installation Path&gt;\Logs, and look for Installation was successful"
I do not see the ID 1015 but I see 
Severity	Type	Site code	Date / Time	System	Component	Message ID	Description
Information	Milestone	UCP	8/3/2018 3:38:11 PM	VRPSCCMRS01.AD.MEDCTR.UCLA.EDU	SMS_SRS_REPORTING_POINT	1019	Site Component Manager successfully reinstalled this component on this site system.
I can run reports from anywhere  but when I am trying to create/edit report from the Primary Server it refused so far ... 
"Before you can create or edit reports, your computer must run a version o SQL Server Report Builder that matches the version of SQL Server that you use for your report server."
When running on the Reporting Server everything is working Run/Create/Edit.

Do I need Reporting Server or Report Builder on all machines used to create reports or they connect to the Reporting Server and run locally ...!!!? 
Thanks,
Dom

Thanks Dom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed3637a6-0616-a14a-2864-9c7d6bbc70e0
* Version Independent ID: 7b0ddfd8-2c0f-9518-39e6-e49130ae2f58
* Content: [Configure reporting - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/configuring-reporting)
* Content Source: [sccm/core/servers/manage/configuring-reporting.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/configuring-reporting.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by felymich** [comment]
I found in srsrp.log
Successfully checked that the SRS web service is healthy on server VRPSCCMRS01.AD	SMS_SRS_REPORTING_POINT	8/30/2018 8:30:57 AM	5092 (0x13E4)
Waiting for changes for 1 minutes	SMS_SRS_REPORTING_POINT	8/30/2018 10:24:13 AM	5092 (0x13E4)

**Comment by aczechowski** [comment]
Thanks @felymich for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time. If later you find there's something specific missing from this article, please reopen this issue or file a new one.
