### ISSUE TITLE
core.windows.net domain requirement needs a change

### ISSUE THREAD

**Issue by motaj1** [MicrosoftDocs/SCCMdocs#806]
Under Internet access requirement using a web proxy, please add * as subdomain to core.windows.net as we discovered blob.core.windows.net also needs to be allowed in Proxy and it is possible we may also need to allow table.core.windows.net. Either list all the sub-domains used or list *.core.windows.net as a requirement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778368d0-1054-678c-4d74-5dce1b5826c8
* Version Independent ID: aaac7308-66e6-66f0-8248-14e1505c11a6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/plan-cloud-management-gateway)
* Content Source: [sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @motaj1 for shaing this feedback. Per our discussion, I agree that we need to clarify the use of these subdomains.

**Comment by aczechowski** [comment]
This issue is closed because I made a tweak to the article for this feedback. The change should publish live later today.
