### ISSUE TITLE
Does this replace SCUP?

### ISSUE THREAD

**Issue by TechsUK** [MicrosoftDocs/SCCMdocs#807]
If this feature replaces or negates the need for SCUP, could it be mentioned? do we need to remove SCUP first?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 054797d3-c4d8-2c2e-9940-e8763f6f3881
* Version Independent ID: 9751d801-35de-ebd8-29ea-57e459f845dc
* Content: [Enable third party updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/third-party-software-updates)
* Content Source: [sccm/sum/deploy-use/third-party-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/third-party-software-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by DavstewMS** [comment]
The feature does not negate/replace SCUP and SCUP does not have to be removed.  

- SCUP has additional catalogs available that may not yet be available in the updated format that works best with CM1806.  There are additional signing and format requirements to work well with CM1806.
- SCUP is required for update authoring scenarios.
- SCUP has more granular/manual control over how and what gets published to WSUS.  
- Integrated feature set has simplified controls, cert deployment automation, automatic WSUS configuration and automated synchronization.

CM admins will decide if they want to use SCUP or the integrated feature or some mix of the two.  There is a known issue called out where the integrated feature does not support publishing content for metadata only update that were published with other tools.

**Comment by aczechowski** [comment]
Thanks @TechsUK for the feedback, and thanks @DavstewMS for the clarification.

**Comment by aczechowski** [comment]
Looks like David answered this, closing
