### ISSUE TITLE
DaysOfWeek field requires update on this documentation

### ISSUE THREAD

**Issue by PraveenGururaj** [MicrosoftDocs/SCCMdocs#810]
Hello There,

I could see this field has been given with some predefined values, but when I query WMI it shows some other values which is not the one shared in the document. Sample given below:

MOF Instance of a task from SCCM Primary Site:
instance of SMS_SCI_SQLTask
{
	BeginTime = "00000000000000.000000+***";
	DaysOfWeek = 127;
	DeleteOlderThan = 30;
	DeviceName = "";
	Enabled = TRUE;
	FileType = 2;
	ItemName = "Delete Aged Client Download History";
	ItemType = "SQL Task";
	LatestBeginTime = "00000000050000.000000+***";
	NumRefreshDays = 1;
	SiteCode = "XXX";
	TaskName = "Delete Aged Client Download History";
	TaskType = 3;
}; 

This task is enabled for all days with delete option data &gt; 30 days, but in WMI it shows 127, how can we calculate the days if this documentation proved to be right?

~Praveen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b61e290-f893-381d-2a4d-ed2fe0a46d87
* Version Independent ID: 0cb1ffe5-de99-b1e5-39a0-fbc9caf6ab88
* Content: [SMS_SCI_SQLTask Class - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/reference/core/servers/configure/sms_sci_sqltask-server-wmi-class#feedback)
* Content Source: [sccm/develop/reference/core/servers/configure/sms_sci_sqltask-server-wmi-class.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/reference/core/servers/configure/sms_sci_sqltask-server-wmi-class.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks to @jpcast88 for contributing content for this issue, which is why it closed. The changes will publish live tomorrow around 11:00 Pacific time.
