### ISSUE TITLE
MVP-Policy interval

### ISSUE THREAD

**Issue by dotraphael** [MicrosoftDocs/SCCMdocs#823]
Information about Policy interval should be added as well as information of best practices and what implications can occur when it is changed.

I'm aware of decreasing the policy interval from 60 to 30min will also decrease the number of supported devices, but this info is not know by many people.

> (7 September admin edit: added metadata block to link with article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f74f4a-560f-2510-1ae8-fd3976a2197e
* Version Independent ID: 0851f834-e9a1-d0a6-ee60-934bcd3a79fe
* Content: [Client settings - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/deploy/about-client-settings#client-policy)
* Content Source: [sccm/core/clients/deploy/about-client-settings.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/about-client-settings.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @dotraphael for the feedback. Is there a specific article that you're referring to?

**Comment by aczechowski** [comment]
I submitted a change for this that will publish early next week, so I'm closing this issue.
