### ISSUE TITLE
Use the Configuration Manager console to convert the long-term servicing branch

### ISSUE THREAD

**Issue by Garthmj** [MicrosoftDocs/SCCMdocs#824]
What is the minimum version that you can upgrade CM LTSB to CB, is it 1511, 1602, etc? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00157df5-6247-ad98-25aa-809e8648f653
* Version Independent ID: d87af8e3-6dda-6943-0f7e-fe8d06e7269c
* Content: [Upgrade the long-term servicing branch to the current branch  - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/understand/convert-to-current-branch)
* Content Source: [sccm/core/understand/convert-to-current-branch.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/convert-to-current-branch.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Garthmj for the feedback. Does this paragraph in the article answer your question?

https://docs.microsoft.com/sccm/core/understand/convert-to-current-branch#run-setup-to-convert-the-long-term-servicing-branch
> For example, because the LTSB is based on version 1606, you cannot use the baseline 1511 media to convert to the Current Branch. Instead, you run setup from the same version 1606 baseline media that you used to install the LTSB site, and choose the licensing option for the Current Branch. Alternately, if a later baseline of the Current Branch has been released, you can run setup from that baseline media.

If not, can you please further clarify your question?

**Comment by aczechowski** [comment]
Based on email conversation, I'm going to close this issue. I think the referenced content answers the question. If you think there's anything still actionable for to revise in this article, please reopen the issue and clarify.
