### ISSUE TITLE
open Hierarchy Settings

### ISSUE THREAD

**Issue by Garthmj** [MicrosoftDocs/SCCMdocs#825]
What tab should this feature of upgrading to CB exist on?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00157df5-6247-ad98-25aa-809e8648f653
* Version Independent ID: d87af8e3-6dda-6943-0f7e-fe8d06e7269c
* Content: [Upgrade the long-term servicing branch to the current branch  - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/understand/convert-to-current-branch)
* Content Source: [sccm/core/understand/convert-to-current-branch.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/convert-to-current-branch.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Garthmj for the feedback, that's a good question. I've honestly never personally seen an LTSB build, so need to check. But agree it would be good to clarify how to locate this option.

**Comment by aczechowski** [comment]
In **Hierarchy Settings**, switch to the **Licensing** tab, and select the option to **Convert to Current Branch**.

**Comment by Garthmj** [comment]
So my version of CM didn't have the Lic tab. it must have been added after 1602. OR even though I was full Admin it could have been hidden by not having all objects. see twit for more details. https://twitter.com/GarthMJ/status/1038131612515553285

**Comment by aczechowski** [comment]
Thanks @jocasti for submitting a change for this issue. It should publish live on Monday around 11am Pacific.
