### ISSUE TITLE
Update content to include developer tools command lines

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/SCCMdocs#829]
Please include the command line references from the linked article into the main ConfigMgr Console reference document. 

https://docs.microsoft.com/en-us/sccm/develop/reference/core/servers/console/console-command-line-options
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f81b196-6d86-0a9e-91ac-471f70dafdbb
* Version Independent ID: 20ce3020-2518-9175-4d32-f5ee5b5f2aaa
* Content: [Configuration Manager Console - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/admin-console)
* Content Source: [sccm/core/servers/manage/admin-console.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/admin-console.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @AdamGrossTX 😄 
Reference [Twitter thread](https://twitter.com/AdamGrossTX/status/1038293319640604672)

**Comment by AdamGrossTX** [comment]
Since it's Hacktoberfest, I went ahead and copied the table over to the Using the console page.

**Comment by aczechowski** [comment]
Closing this issue as it will be fixed later today by the linked pull request
