### ISSUE TITLE
Details update

### ISSUE THREAD

**Issue by Shibaruraya** [MicrosoftDocs/SCCMdocs#832]
hi
can you add few more details on
1. Site expansion support for secondary site or MP with replica configured
2. Using CNAME instead of listener name during re-configuring the SCCM 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90a6316d-7ce8-8cb9-6d9c-d6c923f12706
* Version Independent ID: 3476d25b-b42b-f9f4-a58d-80d95e97ac42
* Content: [Configure Availability Groups - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/configure-aoag)
* Content Source: [sccm/core/servers/deploy/configure/configure-aoag.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/configure-aoag.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Shibaruraya for the feedback. I'll need to investigate this further with engineering.

**Comment by aczechowski** [comment]
When we talk about "site expansion" that's always about adding a CAS to a standalone primary site. But I double-checked with engineering, no config changes for adding a secondary site.

We haven't tested the scenario with an MP replica. SQL appears to have [limited support](https://docs.microsoft.com/sql/database-engine/availability-groups/windows/replication-subscribers-and-always-on-availability-groups-sql-server), so it might work as-is.

In theory using CNAME over listener should work, but it's not tested.

I'm updating this article for 1906 release, so added a note about the secondary site. 

For the other two items that we haven't tested (thus technically don't support), please file [product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) to get it directly into the hands of the engineering team.
