### ISSUE TITLE
Documentation reflecting how to move from a co-managed state to fully cloud managed 

### ISSUE THREAD

**Issue by patster23** [MicrosoftDocs/SCCMdocs#836]
I would like to see documentation showing the process to move from a co-managed state to a full cloud managed state using Microsoft Intune. What is the process to remove the SCCM agent from the device using Intune? How do unjoin the AD domain so my devices are fully cloud managed. 

(1/13/2019: admin edit to rehome to new article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f24ae716-bf27-7d45-cb15-0bc6eea64374
* Version Independent ID: f444ef64-9b7d-999f-3fb3-6ac6cda3ef88
* Content: [Co-management for Windows 10 devices - Configuration Manager](https://docs.microsoft.com/en-us/sccm/comanage/overview)
* Content Source: [sccm/comanage/overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/comanage/overview.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by EMCjvang** [comment]
Any idea when this would be done? Looking for a similar solution.

**Comment by aczechowski** [comment]
Hi @EMCjvang, we are working to reduce the number of doc issues, but this one will take some time. We need to coordinate with the feature PM and engineering team to develop the proper guidance. We don't currently have this effort planned.

**Comment by gate502** [comment]
This would also be helpful for our organization

**Comment by Mike-Crowley** [comment]
Any update here?

**Comment by bryandam** [comment]
I'd like to fifth this.  It seems like a great addition to the existing How-to Guides.

Currently people are resorting to doing things that are probably not supported (ex. [here](https://www.reddit.com/r/Intune/comments/brqjfn/not_using_comanagement_but_devices_still_saying/) and [here](https://www.reddit.com/r/SCCM/comments/jsxojb/from_comanaged_to_intune_only/)).  Or maybe 'That is the Way' ... who knows at this point.

**Comment by aczechowski** [comment]
I'm actually going to close this issue, and use @bryandam's latest issue (MicrosoftDocs/memdocs#999) to track this request going forward. We have more eyes on the newer MEMDocs repo than this one.

**Comment by aczechowski** [comment]
Adding this comment here to make sure others get notified: 

We do have a high-level overview of the “move to Intune” process in the new [Intune setup deployment guide](https://docs.microsoft.com/mem/intune/fundamentals/deployment-guide-intune-setup#option-3-move-from-configuration-manager-to-intune).
