### ISSUE TITLE
Supersedence chain

### ISSUE THREAD

**Issue by maxbaldt** [MicrosoftDocs/SCCMdocs#840]
Any words about how deep you can use a supersedence chain, in the sense of App7 supersedes App6 which supersedes App5, and so on down to App1?  As it builds up the set of policies the client has to go through, (the same goes with dependencies) is there a max / a support statement?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1b7a162-24aa-0b1b-9f21-ee200369ce6d
* Version Independent ID: 9539b94f-a539-76bf-d1ab-a44d6fca1639
* Content: [Revise and supersede applications - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/revise-and-supersede-applications)
* Content Source: [sccm/apps/deploy-use/revise-and-supersede-applications.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/revise-and-supersede-applications.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @maxbaldt, thanks for the feedback! I had a quick chat with the feature team. The general recommendation that you might see in forums is five levels. This is mainly based on the level of testing we've traditionally done with this feature. But there is no strict/supported limit, and we know there are customers that have much deeper chains. So we're going to revisit this before documenting anything explicit. I'll use this issue to track that effort.
