### ISSUE TITLE
Maintenance Windows

### ISSUE THREAD

**Issue by rogersud** [MicrosoftDocs/SCCMdocs#841]
I'm a little bit confused by the part about maintenance windows. With version 1706, software update deployments will not install in the default "All Deployments" maintenance window regardless of subsequent windows. I wasted numerous weekends, even with Premier Support sharing my desktop trying to understand why this doesn't work. Not once did either of their 'experts' inform me of this  faulty configuration. I finally figured it out from another source, just before this article was published - no help from Support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcd257d7-741e-084d-3f7f-f1bf249e7b8e
* Version Independent ID: afa0693a-3941-70d7-d46d-26dcae9f4255
* Content: [Technical preview 1809 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/capabilities-in-technical-preview-1809)
* Content Source: [sccm/core/get-started/capabilities-in-technical-preview-1809.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/capabilities-in-technical-preview-1809.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @rogersud for sharing this feedback. I know this change came up through our sustained engineering team as a bug fix, which often comes up from support cases. Can you clarify your confusion? It sounds like you were hitting this issue, which you should now be able to address in this Technical Preview version with this new setting.

**Comment by aczechowski** [comment]
@rogersud can you please clarify your confusion on this? Otherwise I'm going to close this issue. As I noted in my previous comment, I don't think there's anything actionable for documentation at this time.

**Comment by rogersud** [comment]
The text in this article specifies that this happens when there is a subsequent "Software updates" window. In my experience, the "All deployments'" window can be the one and only window and the updates still fail.

**Comment by aczechowski** [comment]
Sorry to hear about the difficulties. I checked with the engineer that worked on the fix, and the scenario you describe worked in his tests. I encourage you to try the same scenario with the new technical preview. I know you already went down the route with Microsoft Support, but that's the avenue that you'll need to follow for additional assistance.
I'm closing this issue as there's nothing actionable for docs at this time.
