### ISSUE TITLE
Pre-requisite for installing Endpoint Protection Point role on a Windows 2016 server

### ISSUE THREAD

**Issue by desengu** [MicrosoftDocs/SCCMdocs#845]
"Windows Defender features" needs to enable on a Windows 2016 server before installing Endpoint Protection Point role and this part is missing from the above document. Please verify and do the needful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9070eb9b-0e5f-a877-e02e-2d1cea2a2b38
* Version Independent ID: df251762-f2d6-9f06-4fa9-ec5cea2cca0a
* Content: [Site prerequisites - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/site-and-site-system-prerequisites#bkmk_2012EPPpreq)
* Content Source: [sccm/core/plan-design/configs/site-and-site-system-prerequisites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/site-and-site-system-prerequisites.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @desengu for the feedback. You're right, good catch. If you refer to the separate article to [Create an Endpoint Protection point site system role](https://docs.microsoft.com/sccm/protect/deploy-use/endpoint-protection-site-role), there's a note at the top about installation of the Endpoint Protection client. On Server 2016, that's Windows Defender. 😄

**Comment by aczechowski** [comment]
this issue was closed because @jocasti submitted a change for this issue. It should go live tomorrow
