### ISSUE TITLE
Links to specific support areas

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/SCCMdocs#846]
Hi,
It might be an idea to have a link to specific support areas on these pages.  E.G. a link to a page you can go and ask a question when something doesn't work the way the document says it should.  For example, maybe a link to https://social.technet.microsoft.com/Forums/en-US/home?forum=ConfigMgrCBGeneral%2CConfigMgrDeployment%2CConfigMgrMDM%2CConfigMgrMigration%2CConfigMgrCompliance%2CConfigMgrAppManagement%2CConfigMgrPowerShell%2CConfigMgrCBOSD&filter=alltypes&sort=lastpostdesc might be suitable for this page ( maybe there is a better one...)
when I install SCEP on W7, I get a prompt that the definitions are out of date and I should update and another one from action center asking if I want to run SCEP ( probably because the cert is out of date-expired in 2015 even though part of the latest SCCM client install). For end users, I don't want them to get these prompts, so I need advice on how to automate these.  Our end users are just as likely to choose NO and don't remind me again.  alternately, direction on this page on how to deal with these type of possible scenarios might be useful too.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 940822dc-f344-a2ee-b63d-bc65e2705584
* Version Independent ID: 1f85b90e-b13f-f89f-99e9-d0e11d1fab1e
* Content: [Troubleshooting Windows Defender or Endpoint Protection client - Configuration Manager](https://docs.microsoft.com/en-us/sccm/protect/deploy-use/troubleshoot-endpoint-client)
* Content Source: [sccm/protect/deploy-use/troubleshoot-endpoint-client.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/troubleshoot-endpoint-client.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @PaulKlerkx for the feedback. Providing additional troubleshooting resources is a great idea! 

It would probably also be good to include (perhaps in this article, or perhaps elsewhere on setup) information on how to update SCEP immediately after install. Applying updates for *both* the engine and signatures is how to address this issue.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
