### ISSUE TITLE
SCCM CML License

### ISSUE THREAD

**Issue by TomGreenham** [MicrosoftDocs/SCCMdocs#848]
Hello, We have a SCCM CML License and need clarification if this includes the use of a SQL Server License as stated in the FAQ??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3b9a7fa-9585-a2fb-590e-0b74e128035d
* Version Independent ID: 9aae8e97-de68-c274-b4c6-cd925568c75b
* Content: [Product and Licensing FAQ - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/understand/product-and-licensing-faq)
* Content Source: [sccm/core/understand/product-and-licensing-faq.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/product-and-licensing-faq.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @TomGreenham for the question. If you're a volume license customer, if you can view/access SQL in the [Volume License Service Center](https://www.microsoft.com/Licensing/servicecenter/default.aspx), then most likely it's included with your license.

Also, refer to the [product terms](http://microsoftvolumelicensing.com/DocumentSearch.aspx?mode=1) as referenced at the top of this article. 

In general, work with your Microsoft account executive for licensing questions. I'm going to close this issue as I don't see anything directly actionable for this article at this time. Please reopen the issue if you disagree.
