### ISSUE TITLE
Add a note that explains the need to upgrade the SCCM clients  

### ISSUE THREAD

**Issue by kerimhanif** [MicrosoftDocs/SCCMdocs#850]
To take advantage of new Configuration Manager features, first update clients to the latest version. While new functionality appears in the Configuration Manager console when you update the site and console, the complete scenario isn't functional until the client version is also the latest.  

(admin edit: adding metadata for article link)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29b8c8d-60fa-4403-29a7-8e7c61b2f638
* Version Independent ID: c7610ca2-5607-d1fe-f629-9d0614a26569
* Content: [Client Peer Cache - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/client-peer-cache#requirements)
* Content Source: [sccm/core/plan-design/hierarchy/client-peer-cache.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/client-peer-cache.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
This article already includes the specific note about updating clients (in the requirements section). Although the important note to add, as well as to the [What's new in version 1806](https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/whats-new-in-version-1806) article, is that clients need to be updated to share content between versions.

**Comment by aczechowski** [comment]
Resolved by private pull request. Content should publish tomorrow (Friday, September 21) around 11:00 Pacific.
