### ISSUE TITLE
AND or OR

### ISSUE THREAD

**Issue by MagicalWallaby7** [MicrosoftDocs/SCCMdocs#851]
Is this an AND or an OR method if you have multiple categories selected? Does it only search those drive that have all the categories or does is search the drivers that have just one of those categories?

https://docs.microsoft.com/en-us/sccm/osd/understand/task-sequence-steps#limit-driver-matching-to-only-consider-drivers-in-selected-categories

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1187d55d-d8b3-ebc8-37e8-8de14807be4e
* Version Independent ID: daff4a99-10ac-b424-f08a-9024407e667a
* Content: [Task sequence steps - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/understand/task-sequence-steps#limit-driver-matching-to-only-consider-drivers-in-selected-categories)
* Content Source: [sccm/osd/understand/task-sequence-steps.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/understand/task-sequence-steps.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @MagicalWallaby7 for the feedback. I need to check with engineering on the specific behavior.

**Comment by aczechowski** [comment]
It returns all matching drivers that are present in any of those categories. So it is equivalent to OR operation.

**Comment by aczechowski** [comment]
I revised the article and included this information. The change will be live on or about Monday, 6 May. I'm closing this issue.
