### ISSUE TITLE
Transcription output

### ISSUE THREAD

**Issue by keenehteek** [MicrosoftDocs/SCCMdocs#855]
Hello,

During testing of a script using the Run Scripts feature in ConfigMgr i noticed my Transcription log was practically empty. My script mostly uses Write-Output.

So i tested with the following:
```
if (!(Test-Path c:\temp)){ new-item c:\temp -ItemType Directory -Force }
Start-Transcript -path C:\temp\output.log
Write-output 'write-output output'
write-host 'write-host output'
echo 'echo output'
'unspecified output'
Stop-Transcript

```

Only the Write-Host output is stored in the Transcription log. This only happens when the script is run through ConfigMgr, tested with both 1802 and 1806: I've piped everything to ConverTo-Json too, but the result was the same.

```
**********************
Windows PowerShell transcript start
Start time: 20180920083217
Username: VMCORP\SYSTEM
RunAs User: VMCORP\SYSTEM
Configuration Name: 
Machine: WS003 (Microsoft Windows NT 10.0.16299.0)
Host Application: C:\Windows\system32\WindowsPowerShell\v1.0\PowerShell.exe -NonInteractive -NoProfile -ExecutionPolicy RemoteSigned -Command & { . 'C:\Windows\CCM\ScriptStore\4A09F407-7120-4EBA-8ADB-A37A64FE9C44_1B2BA05635E2B9FE471BAD14C06059E02C7940852AF4A0ACE1D0C3EDE6848240.ps1'  | ConvertTo-Json -Compress } 
Process ID: 8104
PSVersion: 5.1.16299.98
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.16299.98
BuildVersion: 10.0.16299.98
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
write-host output
**********************
Windows PowerShell transcript end
End time: 20180920083217
**********************
```

Running a custom logging Function works, but since the introduction of Start-/Stop-Transcript, i kind of stopped using those. Where does my output go ?

**Comment by aczechowski** [comment]
Thanks @keenehteek for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.  

I'm closing this issue as there's nothing actionable for docs at this time.
