### ISSUE TITLE
References to Log Analytics reference materials broken

### ISSUE THREAD

**Issue by CJRicard** [MicrosoftDocs/SCCMdocs#861]
Links to https://docs.loganalytics.io/docs/Language-Reference/Change-log do not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c8158c-1c8e-1567-d96d-222f5b4aec21
* Version Independent ID: f6674943-3564-2250-2334-b88c42f3a8a6
* Content: [CMPivot for real-time data - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/cmpivot)
* Content Source: [sccm/core/servers/manage/cmpivot.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/cmpivot.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @CJRicard for reporting this. It appears to be an issue with that website https://docs.loganalytics.io/. I've reported to the docs support team.

**Comment by aczechowski** [comment]
The Azure Log Analytics language content is now available at:
https://docs.microsoft.com/azure/kusto/query/

The URL should be redirected soon. I'll update our link to this new location.

**Comment by aczechowski** [comment]
Fixed with a private pull request, which should publish tomorrow (Wednesday, 26 September) about 11:00 Pacific time. I'm closing this issue.
