### ISSUE TITLE
Version 3 certificates have been supported, just not version 3 certificate templates.

### ISSUE THREAD

**Issue by RobG-MSFT** [MicrosoftDocs/SCCMdocs#866]
Starting in version 1710, support for Version 3 certificates. 

This statement needs to be changed to state Version 3 Certificate Templates if using Microsoft Active Directory Certificate Services.  Version 3 certificates have always been supported by CMG and the OS.  When you are talking about Crypto Next Generation (CNG) you are actually stating that you support CNG API's which require the use of Key Storage Providers (KSPs) which are only available when using version 3 certificate templates.

However in the latest versions of PKI for the OS we have gotten away from even saying Version 3 certificate templates, so the best / accurate statement is to say that it supports the use of Key Storage Providers for certificate private keys.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c095180-90a2-79c6-a7fb-6504cafbcfb6
* Version Independent ID: fb9c2930-b213-3eef-c7bb-c8f11ec97aca
* Content: [CMG Certificates](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway)
* Content Source: [sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Closing this issue. I made some changes to this article today and included this update.
