### ISSUE TITLE
Internet access requirement must include Cloud Services Manager

### ISSUE THREAD

**Issue by motaj1** [MicrosoftDocs/SCCMdocs#867]
"Cloud Services Manager" component on Service Connection Point also needs access to the endpoints listed under "Internet access requirements" 
Please update this statement to include "Cloud Services Manager" along with CMG Connection Point.
"The CMG connection point site system supports using a web proxy. For more information on configuring this role for a proxy, see Proxy server support. The CMG connection point requires connectivity to the following endpoints:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778368d0-1054-678c-4d74-5dce1b5826c8
* Version Independent ID: aaac7308-66e6-66f0-8248-14e1505c11a6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/plan-cloud-management-gateway)
* Content Source: [sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by MSFTJerryAb** [comment]
See internal thread on this issue with subject: SCCMdocs:867: RE: CMG Setup:

**Comment by aczechowski** [comment]
This issue is closed because I made a tweak to the article for this feedback. The change should publish live later today.
