### ISSUE TITLE
Create an Advertisement and Correct RemoteClientFlags

### ISSUE THREAD

**Issue by KrenidaN** [MicrosoftDocs/SCCMdocs#870]
Documentation is very good and does help out a lot, but on the topic of Creating an Advertisement in the Example section, one of the C# lines is:

newAdvertisement["AdvertFlags"].IntegerValue = newAdvertisementFlags;

I can see where the newAdvertisementFlags variable stems from and how it is passed, but I cannot find any reference to how to actually set this variable. What should be set and what is mandatory to be set? How do I go about doing this?

Any info and/or guidance will be helpful.

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a720b746-490b-de14-2649-2f083655fec3
* Version Independent ID: cd55113a-59d8-0959-f769-9d0586bab51f
* Content: [Create an Advertisement - Configuration Manager](https://docs.microsoft.com/en-us/sccm/develop/core/servers/configure/how-to-create-an-advertisement)
* Content Source: [sccm/develop/core/servers/configure/how-to-create-an-advertisement.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/develop/core/servers/configure/how-to-create-an-advertisement.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by ramseygr** [comment]
here's the enum for advertisement flags:

https://github.com/MicrosoftDocs/SCCMdocs/blob/master/sccm/develop/reference/core/servers/configure/sms_advertisement-server-wmi-class.md

**Comment by aczechowski** [comment]
Thanks @KrenidaN for the feedback, and thank you @ramseygr for the reference. The URL for the published article is https://docs.microsoft.com/sccm/develop/reference/core/servers/configure/sms_advertisement-server-wmi-class.
@KrenidaN does this answer your question?

**Comment by KrenidaN** [comment]
Not completely, as I have already read that article. As far as I understood, I only have to "pipe" all the settings I require to the
newAdvertisement["AdvertFlags"].IntegerValue
like so:

newAdvertisement["AdvertFlags"].IntegerValue = newAdvertisement["AdvertFlags"].IntegerValue | NO_DISPLAY;

where NO_DISPLAY variable is converted to integer and so on for all the settings.

Please correct me if I'm wrong.

**Comment by aczechowski** [comment]
Thanks for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
