### ISSUE TITLE
Alert for outdated malware client

### ISSUE THREAD

**Issue by jocasti** [MicrosoftDocs/SCCMdocs#871]
From the section above, "You can now view Antimalware Client Version and Endpoint Protection Deployment Status by going Assets and Compliance &gt; Overview &gt; Device Collections &gt; All Desktops and Server Clients."

Followed this navigation in my test lab admin console, but could not find the antimalware client  version and protection deployment status.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0eabddcb-8049-59c7-7784-abe31633d274
* Version Independent ID: e31eb614-07aa-4085-9a17-50a4e0bf7587
* Content: [Configure Endpoint Protection alerts - Configuration Manager](https://docs.microsoft.com/en-us/sccm/protect/deploy-use/endpoint-configure-alerts)
* Content Source: [sccm/protect/deploy-use/endpoint-configure-alerts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/endpoint-configure-alerts.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jocasti for the feedback, I agree that's poorly worded. What it should say is that from any device collection you can add a column to the list for those two attributes. Right-click the column header and select those columns to add. (Although the latter column name is Endpoint Protection Deployment State.)

**Comment by jocasti** [comment]
@aczechowski Create PR#884 using your recommended changes.

**Comment by jocasti** [comment]
Moved to PR#884
