### ISSUE TITLE
Clarify how rate limits impacts Sender options

### ISSUE THREAD

**Issue by LeviStevens** [MicrosoftDocs/SCCMdocs#872]
There is not clear documentation on how rate limits impacts Software Distribution Component settings.  I believe setting any rate limit automatically restricts it to a package at a time at site, instead of multiple.  If the documentation could clarify this it would be helpful.

Also, more granular details on how the "yielding" works, if I choose 50% rate, does does that mean that runs hot for 30 minutes and yields for 30 minutes? Or does it run for 1 minute, and yield for 1 minute?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b49b7692-2fba-a5b6-cc24-3b2621b7f5dd
* Version Independent ID: bbc48abf-20cb-18f4-0db4-467cb0408b30
* Content: [Manage distribution points - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/install-and-configure-distribution-points)
* Content Source: [sccm/core/servers/deploy/configure/install-and-configure-distribution-points.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/install-and-configure-distribution-points.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @LeviStevens for the feedback.

**Comment by codaamok** [comment]
Yes, +1 to this. I've found here that (https://www.experts-exchange.com/articles/12177/SCCM-2012-How-Rate-Limiting-Pulse-Mode-saved-the-day.html) Chris suggests any rate limit configured limits package transfer manager to only handling 1 package at a time. 

It's also a very good question re the yielding. If I configure 50%, what is the behavior of the timings? 

Again, we could suck it and see for ourselves with both of these questions. But we would all benefit from planning and learning if it were documented.

**Comment by aczechowski** [comment]
Thanks again for the feedback. We recently moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
