### ISSUE TITLE
Revise CMPivot permissions prereq

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#878]
The second bullet in the prereqs section should read as follows:

- The Configuration Manager administrator needs the **Read** permission on the **SMS Scripts** object, the **Run Scripts** permission on the collection, and the **default scope**. The **Scripts Runner** role has these permissions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0c8158c-1c8e-1567-d96d-222f5b4aec21
* Version Independent ID: f6674943-3564-2250-2334-b88c42f3a8a6
* Content: [CMPivot for real-time data - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/cmpivot#prerequisites)
* Content Source: [sccm/core/servers/manage/cmpivot.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/cmpivot.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by jocasti** [comment]
@aczechowski Created Pull request #970 with your recommended changes.

**Comment by aczechowski** [comment]
Closing this issue; fixed with referenced pull request by @jocasti
