### ISSUE TITLE
1806 - HTTP Management Point - Enhanced HTTP site system 

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/SCCMdocs#881]
This should be updated to say Starting in version 1806, the Management Point does not need be HTTPS to allow Cloud Management Gateway Traffic if the pre-release feature "Enhanced HTTP site system" is enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c095180-90a2-79c6-a7fb-6504cafbcfb6
* Version Independent ID: fb9c2930-b213-3eef-c7bb-c8f11ec97aca
* Content: [CMG Certificates](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway#enable-management-point-for-https)
* Content Source: [sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/certificates-for-cloud-management-gateway.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @nhogarth86 for the feedback. The content for Enhanced HTTP feature is still in progress.

**Comment by aczechowski** [comment]
Closing this issue. Content updated today with information for Enhanced HTTP
