### ISSUE TITLE
1806 - Enhanced HTTP site system

### ISSUE THREAD

**Issue by nhogarth86** [MicrosoftDocs/SCCMdocs#882]
Under the requirements it says "Starting in version 1802, you must configure all CMG-enabled management points to use HTTPS." Starting in version 1806, the Management Point does not need be HTTPS to allow Cloud Management Gateway Traffic if the pre-release feature "Enhanced HTTP site system" is enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 778368d0-1054-678c-4d74-5dce1b5826c8
* Version Independent ID: aaac7308-66e6-66f0-8248-14e1505c11a6
* Content: [Plan for cloud management gateway - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/cmg/plan-cloud-management-gateway#scenarios)
* Content Source: [sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/cmg/plan-cloud-management-gateway.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @nhogarth86 for the feedback. The content for Enhanced HTTP feature is still in progress.

**Comment by aczechowski** [comment]
Closing this issue. I published updates to this article today for Enhanced HTTP.
