### ISSUE TITLE
LEDBAT on Server 1709 (Server 2016)

### ISSUE THREAD

**Issue by faulknerp** [MicrosoftDocs/SCCMdocs#883]
Just a note about support on Windows Server 1709..... I was interested in hearing more so I raised a support call with Premier Support, who then told me that LEDBAT is not officially yet supported on Server 2016 and only will be on Server 2019. They've released LEDBAT in Server 2016 for testing/feedback purposes only, here's the response...

Please understand that LEDBAT still needs improvement and hence this feature has been introduced in Windows 2016 for extensive testing. 
At the moment, there are no plans to officially provide full support for LEDBAT on Windows 2016. But, if there is a change of plan, public article would be published for the users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b49b7692-2fba-a5b6-cc24-3b2621b7f5dd
* Version Independent ID: bbc48abf-20cb-18f4-0db4-467cb0408b30
* Content: [Manage distribution points - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/install-and-configure-distribution-points#bkmk_config-general)
* Content Source: [sccm/core/servers/deploy/configure/install-and-configure-distribution-points.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/install-and-configure-distribution-points.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by faulknerp** [comment]
Disregard this: David James and Daniel Havey have confirmed LEDBAT 100% supported on Server 2016..
https://twitter.com/Win10Transports/status/1047860988043714560

**Comment by dahavey** [comment]
There will be a public blogpost from the Windows team today explaining support and configuration for LEDBAT.  There was a misconfiguration that keeps LEDBAT from being able to leverage unused bandwidth.  I will include all the details and a workaround for WS2016, 1709 and WS2019.

**Comment by aczechowski** [comment]
I was reminded that this is unresolved.

Minimum requirements for LEDBAT support in SCCM:
- SCCM 1806 GA
    - Windows Server, version 1709 or later
- SCCM 1806 with update rollup (4462978), or later
    - Windows Server, version 1709 or later
    - Windows Server 2016 with the following updates:
        - KB4132216
        - KB4284833 
- SCCM 1810 or later, the same as above plus:
    - Windows Server 2019

**Comment by aczechowski** [comment]
I revised the article and included this information. The change will be live on or about Monday, 6 May. I'm closing this issue.
