### ISSUE TITLE
Security Alerts for Software Center links in Office apps

### ISSUE THREAD

**Issue by FC-EricWeller** [MicrosoftDocs/SCCMdocs#886]
While slightly out of scope for this document, it's probably worth noting that if you're sending the e-mail that you paste your URL into via Outlook, it won't automatically hyperlink.  You can use CTRL-K or Insert&gt;Hyperlink though and it will work fine when recipients click it.

Also - by default Outlook RECEIVING such a link will present a security alert for the softwarecenter: protocol when the links are clicked.  You can prevent this in your domain environment by adding a Trusted Protocol key to the registry as follows:
HKCU\Software\Policies\Microsoft\Office\16.0\Common\Security\Trusted Protocols\All Applications\softwarecenter:

Mileage with other e-mail apps may vary :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e65ca5e8-8561-05a0-937e-e2ffbd63400a
* Version Independent ID: b6619e02-422f-ad86-ad2e-c3baf4518982
* Content: [Share applications in the Software Center - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/share-applications)
* Content Source: [sccm/apps/deploy-use/share-applications.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/share-applications.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @FC-EricWeller for the great tip! If you're interested and willing, you can add this tip yourself by contributing to our documentation. :) For more information on the process, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute). I'm happy to help you with formatting and style with the `> [!Tip]` element.

**Comment by jocasti** [comment]
@aczechowski Created PR https://github.com/MicrosoftDocs/SCCMDocs-pr/pull/3046 for this issue. First time using the !TIP element, so definitely need help with formatting.

**Comment by ChrisKibble** [comment]
@aczechowski - this was fixed in the private repo so I don't think it was flagged for you to close, but I confirmed in the public repo that the tip is there, well formatted, and you can close this issue.
