### ISSUE TITLE
MDT version table

### ISSUE THREAD

**Issue by BritV8** [MicrosoftDocs/SCCMdocs#887]
Would be good to add the supported MDT versions for each SCCM version

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc732ec0-eb14-8da2-7688-dd74a72cdae5
* Version Independent ID: a93682ff-2984-38e0-5a0d-6f77c1c9e5db
* Content: [Support for Windows 10 - Configuration Manager](https://docs.microsoft.com/en-nz/sccm/core/plan-design/configs/support-for-windows-10)
* Content Source: [sccm/core/plan-design/configs/support-for-windows-10.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/support-for-windows-10.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @BritV8 for the feedback. The [MDT release notes](https://docs.microsoft.com/en-us/sccm/mdt/release-notes) include its supported configurations. 

As there are a lot of Microsoft and third-party add-ons to Configuration Manager, we aren't able to centralize all of those support grids here. So we use the specific product pages to state their support.
