### ISSUE TITLE
Add UserService.log to list of log files

### ISSUE THREAD

**Issue by lxyang85** [MicrosoftDocs/SCCMdocs#890]
Currently, there's no documentation on the Management Point log file for User Service. The log file is located on :<installDir>\Program Files\SMS_CCM\Logs\UserService.log

https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/log-files#BKMK_ServerLogs

It should probably read something like this:

UserService.log - Records the User Reqeusts from Software Center

(admin edit: add metadata block to link with target article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 972d8899-c8a4-28c5-fabe-5ab294bac22d
* Version Independent ID: 7f772e7a-836c-a18d-df8d-c3d115cb3d9f
* Content: [Log files for troubleshooting - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/log-files#BKMK_ServerLogs)
* Content Source: [sccm/core/plan-design/hierarchy/log-files.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/log-files.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by lxyang85** [comment]
https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/log-files#BKMK_ServerLogs

**Comment by aczechowski** [comment]
Thanks @lxyang85 for the feedback. This is the new log in 1806 for User Service endpoint (serving SWCenter traffic) on the Management Point. This endpoint is the replacement for the app catalog roles and shows logs for SWCenter retrieving/installing user-available applications from the server.

**Comment by aczechowski** [comment]
While making another change to this article, I added this entry. It should publish live tomorrow, so I closed the issue.
