### ISSUE TITLE
Enhanced http

### ISSUE THREAD

**Issue by ReneKierstein** [MicrosoftDocs/SCCMdocs#893]
Will it be possible to include Technical information related to the certificate created by Configmgr. Security departments lige to know stuff like that.

(admin edit, changing metadata to 1806 article)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22765ffe-cef8-a88f-5f71-00caf9b47046
* Version Independent ID: cb5ad492-39d1-f63d-0bd2-7f3a0b1d8af0
* Content: [What's new in version 1806 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/changes/whats-new-in-version-1806)
* Content Source: [sccm/core/plan-design/changes/whats-new-in-version-1806.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/changes/whats-new-in-version-1806.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ReneKierstein for the feedback. The content for Enhanced HTTP feature is still in progress.

**Comment by aczechowski** [comment]
Closing this issue. I published updates today to include [Enhanced HTTP](https://docs.microsoft.com/sccm/core/plan-design/hierarchy/enhanced-http)

**Comment by surferstylee** [comment]
Is there any confirmation on a bug with Enhanced HTTP incorrectly handing out the CCMAUTHTOKEN path to ACPs?  I have run into challenges with 1E Nomad (they have identified the challenge and have current workaround *see attached) and 2Pint OSD Toolkit (they have also identified and have implemented resolution into product).
I have not found any official documentation on this bug but I understand the resolution is expected in 1902.
Do I sound like a raving lunatic or can this be confirmed?

![1e Enhanced HTTP Workaround](https://user-images.githubusercontent.com/17766354/54464255-30166d80-4776-11e9-8022-5a0fde833553.jpg)
