### ISSUE TITLE
Peer PXE

### ISSUE THREAD

**Issue by Btreyo** [MicrosoftDocs/SCCMdocs#895]
The Peer PXE settings which enable PXE responder settings at the workstation - are not detailed here this was introduced is 1712 tech preview.. Has this feature been deprecated? or not yet fully released?

**Comment by aczechowski** [comment]
Hi @Btreyo, this feature is still in technical preview. See the list of features in previous technical preview releases that are not yet in a current branch release: https://docs.microsoft.com/sccm/core/get-started/technical-preview#features-in-previous-technical-previews

**Comment by Btreyo** [comment]
Thank you Aaron, are you permitted to indicate which version we can expect to see this as full release?

**Comment by aczechowski** [comment]
We don't have a target release yet. We're quality driven, not schedule driven. We'll release the feature after we receive and review customer feedback, and make whatever improvements we think are necessary to get it to production-ready quality. I suggest you [provide feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) on the feature to help the team understand your usage. 

Also, look at the [Improvements to PXE-enabled distribution points](https://docs.microsoft.com/sccm/core/plan-design/changes/whats-new-in-version-1806#improvements-to-pxe-enabled-distribution-points) in version 1806. This feature doesn't require WDS, so enables you to add a PXE-enabled distribution point role to a supported client.
