### ISSUE TITLE
Client upgrades honor any Configuration Manager maintenance windows you have configured.

### ISSUE THREAD

**Issue by ryanb22** [MicrosoftDocs/SCCMdocs#896]
Can we provide some details on this note? It appears that the upgrade will actually require two maintenance windows in this scenario. With restricting windows in place, the client only randomizes the download of the content. 

Here is the workflow i'm seeing when using ACU to deploy the production client with maintenance windows. 

1. Client receives the production upgrade policy. (mandatory advert created in ccm\policy\machine\actualconfig\ccm_softwaredistribution)
2. During the first maintenance window, the client will download CCMSETUP.exe and generate a scheduled task (the trigger will be randomized time based on the hierarchy settings in step 7).
3. When the scheduled tasks executes, it will download the rest of the client bits. (outside of MWs)
4. The client will upgrade at the next maintenance window. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7000ae26-9f15-9644-55b9-e5db68c47ff2
* Version Independent ID: 8a672552-6e90-cd91-419c-ba6a5292fabf
* Content: [Upgrade clients - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/upgrade/upgrade-clients-for-windows-computers)
* Content Source: [sccm/core/clients/manage/upgrade/upgrade-clients-for-windows-computers.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/upgrade/upgrade-clients-for-windows-computers.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ryanb22 for the feedback. I'm checking with the engineering team on this.

**Comment by aczechowski** [comment]
Ok, confirmed. Some further details:

> The first wait is for the upgrade program itself which only contains ccmsetup.exe. Execmgr (CcmExec) will only run ccmsetup.exe during service window. If it’s embedded devices when WF is on, ccmsetup won’t randomize the download and will download/install likely at the same window.
> 
> However if it’s non-embedded, as Ryan said, ccmsetup will run and will randomize a time for content download. After download, it will compile a local policy back to execmgr (ccmexec) to schedule the actual upgrade in the next window.
> 
> Unfortunately we cannot consolidate into the same time frame because on embedded we have to launch the upgrade program in the window, thus it’s marked as honoring window as well.

**Comment by aczechowski** [comment]
I expanded this note with further details, it will publish live tomorrow
