### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by Shloeb** [MicrosoftDocs/SCCMdocs#902]
Hello, 

The link http://www.microsoft.com/security/portal/Definitions/HowToForeFront.aspx is broken. It is referenced in the below statement.

For more information about how to download the definition and engine updates to store on the file share, see Install the latest Microsoft antimalware and antispyware software.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffa0bf4e-0b62-8992-3d60-7c2077f5b341
* Version Independent ID: b6204363-a548-aa8f-8004-e02278a9737f
* Content: [Endpoint Protection malware definitions from network share - Configuration Manager](https://docs.microsoft.com/en-us/sccm/protect/deploy-use/endpoint-definitions-network)
* Content Source: [sccm/protect/deploy-use/endpoint-definitions-network.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/protect/deploy-use/endpoint-definitions-network.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Shloeb for catching that! If you're interested and willing, you can make the change yourself by contributing to our documentation. :) For more information on the process, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute). 

I think the proper link to use instead is: https://www.microsoft.com/wdsi/definitions

**Comment by Stephanevg** [comment]
Hi @aczechowski 
Not sure this was the correct link, but I updated it, and did a PR [907](https://github.com/MicrosoftDocs/SCCMdocs/pull/907) Let me know if it was correct.

**Comment by aczechowski** [comment]
CLosing this issue as it will be fixed shortly by the linked pull request
