### ISSUE TITLE
CMPivot uses internet browser style controls for accessibility

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#905]
Treat CMPivot like the browser, and use browser controls. For example, **Ctrl+1** for first tab, or focus on Address and put “Alt+&lt;” to go “back” on the address. 
Sample tips: https://support.microsoft.com/help/17456/windows-internet-explorer-ease-of-access-options 

Cross reference this tip from [CMPivot](https://docs.microsoft.com/sccm/core/servers/manage/cmpivot) article. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8116c71f-c2e1-0d19-7a06-10daf832cc62
* Version Independent ID: 93d928a8-b733-1dec-b31b-339c0730ab84
* Content: [Accessibility - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/understand/accessibility-features#feedback)
* Content Source: [sccm/core/understand/accessibility-features.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/understand/accessibility-features.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by ChrisKibble** [comment]
Starting working on this in this branch of my fork - does anyone who has used it have a larger list of shortcuts to start with?

https://github.com/ChrisKibble/SCCMdocs/blob/cmPivotShortcuts/sccm/core/understand/accessibility-features.md

I'll run through it myself, but would love some input on what others are using.

**Comment by aczechowski** [comment]
Meghan's going to work on pulling @ChrisKibble's changes from his fork of sccmdocs over to the new memdocs repo and get this published. 😄

**Comment by mestew** [comment]
Pulled this into memdocs. Resolved with private PR 788. I pulled the commit into the new repo, i just don't see Chris's name on the new doc. @ChrisKibble if this is a massive bummer to you, ping me or aaron on Twitter and we'll work with you on getting you credit in the new repo.
