### ISSUE TITLE
Remove #4 and #5 from the Content source priority list

### ISSUE THREAD

**Issue by kerimhanif** [MicrosoftDocs/SCCMdocs#908]
We have removed these we no longer check "A peer source in the same Active Directory site" and "A distribution point in the same Active Directory site"
So please remove these from the content source priority list. 
There should be 10 items there remaining..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff2f1985-822a-f9aa-8368-9abf85c50118
* Version Independent ID: 3401e963-f1cf-a15d-01f2-c1754a7d9336
* Content: [Content management fundamentals - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management#content-source-priority)
* Content Source: [sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/fundamental-concepts-for-content-management.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
CLosing this issue as it will be fixed by the linked pull request
