### ISSUE TITLE
Add explanation for to the 8004 port 

### ISSUE THREAD

**Issue by kerimhanif** [MicrosoftDocs/SCCMdocs#910]
In this section 
https://docs.microsoft.com/en-us/sccm/core/clients/deploy/about-client-settings#enable-configuration-manager-client-in-full-os-to-share-content

We mention the use of broadcast from port 8004, we need to explain that this broadcast is used both in WinPE more and also in TS even in full OS, the TS agent will perform the subnet broadcast to get content locations before the start of the TS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f74f4a-560f-2510-1ae8-fd3976a2197e
* Version Independent ID: 0851f834-e9a1-d0a6-ee60-934bcd3a79fe
* Content: [Client settings - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/deploy/about-client-settings#enable-configuration-manager-client-in-full-os-to-share-content)
* Content Source: [sccm/core/clients/deploy/about-client-settings.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/deploy/about-client-settings.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I submitted a change for this that will publish early next week, so I'm closing this issue.
