### ISSUE TITLE
SUP no longer supported on Server 2008 R2

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#911]
We only allow for DPs on Server 2008 R2 per [supported config](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/supported-operating-systems-for-site-system-servers#bkmk_2008r2sp1).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c3e8dd5-a5d0-c96c-841a-21589d58d20b
* Version Independent ID: 09984eaa-b26b-bc94-7250-c4e5db8f5f58
* Content: [Prerequisites for software updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/plan-design/prerequisites-for-software-updates#windows-server-update-services)
* Content Source: [sccm/sum/plan-design/prerequisites-for-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/plan-design/prerequisites-for-software-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by jocasti** [comment]
@aczechowski Created PR https://github.com/MicrosoftDocs/SCCMDocs-pr/pull/3045 for this issue. Also, I wanted to add a reference to this document, https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/supported-operating-systems-for-site-system-servers#bkmk_2008r2sp1, but wasn't sure the correct path for the link.

**Comment by jocasti** [comment]
Fixed by https://github.com/MicrosoftDocs/SCCMDocs-pr/pull/3045

**Comment by aczechowski** [comment]
Thanks @jocasti, closing
