### ISSUE TITLE
Server 2019

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/SCCMdocs#912]
Which version of SCCM Current Branch is or will support Server 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dc0edfd-7799-9246-2e23-f202e31517f9
* Version Independent ID: 8c401426-fcf8-79a9-08fa-95a724b5756d
* Content: [Supported site system servers - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/supported-operating-systems-for-site-system-servers)
* Content Source: [sccm/core/plan-design/configs/supported-operating-systems-for-site-system-servers.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/configs/supported-operating-systems-for-site-system-servers.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Testing is still in progress, support as a server role is expected in a future release.

**Comment by aczechowski** [comment]
Closing this issue, it's fixed with 1810 content that will publish soon.

**Comment by marshgm** [comment]
Can you update this to reflect 2019 under Core for DPs?

**Comment by aczechowski** [comment]
Yes, thanks @marshgm for catching that. I'll do that now, it should publish live tomorrow (Wednesday) around 11am Pacific time.
