### ISSUE TITLE
How does one force a 3rd party sync only?

### ISSUE THREAD

**Issue by ThomasHughesIV** [MicrosoftDocs/SCCMdocs#913]
I'm having some issues getting this working.  HP is not showing up on my 3rd party list.  My SMS_ISVUPDATES log is saying
:ScheduledWorkMonitor: Scheduled item (PartnerCatalogListSyncTask:00000000-0000-0000-0000-000000000000) is due in 6.23:05:03.9084160.

...is that 6 years when it will do sync next?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 054797d3-c4d8-2c2e-9940-e8763f6f3881
* Version Independent ID: 9751d801-35de-ebd8-29ea-57e459f845dc
* Content: [Enable third party updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/third-party-software-updates)
* Content Source: [sccm/sum/deploy-use/third-party-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/third-party-software-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ThomasHughesIV for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
