### ISSUE TITLE
ALO VPN

### ISSUE THREAD

**Issue by yannara** [MicrosoftDocs/SCCMdocs#914]
ALO VPN capabilities, like AutoConnect and SplitTunnel vs. Force Tunnel seems to be missing from SCCM VPN profile capabilities. In ALOVPN, these options are configured inside xml and are deployed with Powershell. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48e93b6c-c2a0-5528-faf3-9bf6ebfecad7
* Version Independent ID: 07c149c3-ee5e-002d-efff-fcadf1801dfa
* Content: [VPN profiles - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/create-vpn-profiles)
* Content Source: [sccm/mdm/deploy-use/create-vpn-profiles.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/create-vpn-profiles.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @yannara for the feedback. Are you saying that the product includes these capabilities, but they're not captured in this document? Or that the product doesn't currently support but should include?

**Comment by yannara** [comment]
I think document is fine I guess, but SCCM itself seems to be missing ALO VPN capabilities to depoy. MS whitepaper for ALOVPN guides to deploy VPN profile with Package using SCCM, not VPN-profile function in the SCCM console. I think there is no sense to push ALOVPN profile directly with SCCM concole, because then you cannot deploy AutoConnect and Split tunnel functionalities.

**Comment by aczechowski** [comment]
Thanks for the clarification. The docs represent the product capabilities and what it supports. So I'm closing this issue as I don't think there's anything actionable for the docs at this time. Please file [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) to get this idea into the hands of the engineering team.
