### ISSUE TITLE
Please surface the whole list of ./Vendor/MSFT/WorkProfile/ configuration CSP options for AfW (Android for work) Work Profile configuration

### ISSUE THREAD

**Issue by peterjlay** [MicrosoftDocs/SCCMdocs#918]
Please surface the whole list of ./Vendor/MSFT/WorkProfile/ configuration CSP options for AfW (Android for work) Work Profile configuration, as Intune SDK integration with Intune Managed Browser does not work with Kiosk devices enrolled, as they have no user context, only a device context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c7dc362-5227-b8bf-cbbd-762bde22ec43
* Version Independent ID: 7d838c1c-fcd7-f126-2d22-93312f0e3d65
* Content: [How to create configuration items for Android for Work devices managed with Intune - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/create-configuration-items-for-android-for-work-devices-managed-without-the-client)
* Content Source: [sccm/mdm/deploy-use/create-configuration-items-for-android-for-work-devices-managed-without-the-client.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/create-configuration-items-for-android-for-work-devices-managed-without-the-client.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @peterjlay for the feedback. I checked with the engineering team, there are no settings available with custom policies that aren't available in the Intune console as first-class policy settings. 

If you have further feedback on this, it would be as product feedback. Note, [hybrid MDM](https://docs.microsoft.com/sccm/mdm/understand/hybrid-mobile-device-management) is deprecated. You can submit feedback on Microsoft [Intune on UserVoice](https://microsoftintune.uservoice.com/).

I'm closing this issue as there's nothing actionable for this article at this time.
