### ISSUE TITLE
Please fix the issue that Intune SDK integration supporting Key-Value pairs with Intune Managed Browser does not work with Kiosk devices enrolled using Android for Work (AfW Work Profiles)

### ISSUE THREAD

**Issue by peterjlay** [MicrosoftDocs/SCCMdocs#919]
Please fix the issue that Intune SDK integration supporting Key-Value pairs with Intune Managed Browser does not work with Kiosk devices enrolled using Android for Work (AfW Work Profiles), as they have no user context, only a device context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18cb389b-ff7f-912c-6454-c8b104b37011
* Version Independent ID: d6ebc038-e66e-f5fc-669f-718b6224d8cc
* Content: [Manage Internet access using managed browser policies - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/manage-internet-access-using-managed-browser-policies)
* Content Source: [sccm/mdm/deploy-use/manage-internet-access-using-managed-browser-policies.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/manage-internet-access-using-managed-browser-policies.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use Microsoft Support to search for the issue, or open a case with professional support. For more information, see [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support).
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
