### ISSUE TITLE
Native task sequence support for Windows Auto Pilot for existing devices

### ISSUE THREAD

**Issue by KumaresanLakshmanan** [MicrosoftDocs/SCCMdocs#920]
Need conformation on this feature in technical preview release of SCCM 1810. We can see this feature listed in Public techcommunity blog but not in Microsoft docs. Also, like to have procedure on how to enable and use this feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac2470bb-8bcb-d07d-71c3-261b84762419
* Version Independent ID: 868cabe3-5088-fa54-cba0-56ff1d2259ef
* Content: [Technical preview 1810 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/capabilities-in-technical-preview-1810)
* Content Source: [sccm/core/get-started/capabilities-in-technical-preview-1810.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/capabilities-in-technical-preview-1810.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
CLosing this issue as the content published earlier today for this feature.
