### ISSUE TITLE
Bug in description Product lifecycle dashboard

### ISSUE THREAD

**Issue by AdamZajacT** [MicrosoftDocs/SCCMdocs#921]
Tile Top five products nearing end-of-life shows products that are nearing end-of-life in next eighteen months not six as it is currently written

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e5b5231-0498-f10a-fcd7-58230e43cca5
* Version Independent ID: aa3f037a-f646-e683-867e-b8e16f27966d
* Content: [Product lifecycle dashboard - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/asset-intelligence/product-lifecycle-dashboard)
* Content Source: [sccm/core/clients/manage/asset-intelligence/product-lifecycle-dashboard.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/asset-intelligence/product-lifecycle-dashboard.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @AdamZajacT for catching that! If you would like to submit an edit for this, I'll happily review it. For more information on how to contribute, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute).

**Comment by aczechowski** [comment]
CLosing this issue as it is resolved by the linked pull request.
