### ISSUE TITLE
Ramifications to moving the role

### ISSUE THREAD

**Issue by MSGriz** [MicrosoftDocs/SCCMdocs#922]
There are many items that are encrypted in the DB based on the computer certificate of the connection point role.  When moving the role there are several potential things such as Azure Apps secret keys and such that must be updated or reconfigured post move to re-encrypt with the new computer cert.  It would be great to list out what those potential reconfigure points are so everyone is aware of what additional actions might need to be taken on a connection point move.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26fc3067-8a85-2455-8b71-69cf46cbb7e0
* Version Independent ID: a90ca598-c5fa-f245-eafc-0fd95f9eaca9
* Content: [Service connection point - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/deploy/configure/about-the-service-connection-point)
* Content Source: [sccm/core/servers/deploy/configure/about-the-service-connection-point.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/deploy/configure/about-the-service-connection-point.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @MSGriz for the feedback 😉

**Comment by CaptainUnlikely** [comment]
I would be interested to know if there is a list of these points anywhere as I'm looking at moving my SCP role soon.  Happy to raise a case for clarification by support for my own information if this is backlogged, but I support the idea that it would be nice to have this aspect documented at some point.

**Comment by aczechowski** [comment]
I made updates to this article with broader hybrid deprecation work that will publish soon. I'm closing this issue.
