### ISSUE TITLE
SCCM conditional access scenario not yet supported in Intune Standalone

### ISSUE THREAD

**Issue by Matgard** [MicrosoftDocs/SCCMdocs#924]
Just a PSA: If you are using Azure AD Conditional Access to check for compliance on SCCM managed PCs (W7, 8.1, 10), then removing the Intune Hybrid subscription will cause this feature to break. This feature and its reliance on the Intune Hybrid subscription is explained here: https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/manage-access-to-o365-services-for-pcs-managed-by-sccm

Support for the feature without requiring Intune Hybrid is coming, but pending, as per the update to Intune's Support Blog here:  https://blogs.technet.microsoft.com/intunesupport/2018/08/14/move-from-hybrid-mobile-device-management-to-intune-on-azure/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e430e343-868a-8116-62d5-cd5bf14b6648
* Version Independent ID: 0746a0dd-35ab-f81e-41d7-7c05c16be612
* Content: [Migrate hybrid MDM resources to Intune standalone - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/migrate-hybridmdm-to-intunesa)
* Content Source: [sccm/mdm/deploy-use/migrate-hybridmdm-to-intunesa.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/migrate-hybridmdm-to-intunesa.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks for sharing @Matgard

**Comment by aczechowski** [comment]
hybrid end of service is this coming weekend, closing this issue
