### ISSUE TITLE
Clarify o365 fallback to Office CDN works the same way as Windows update fallback to WU/MU and content fallback behavior for internet clients

### ISSUE THREAD

**Issue by MSFTJerryAb** [MicrosoftDocs/SCCMdocs#925]
Office doc’d it here: https://techcommunity.microsoft.com/t5/Office-365-ProPlus/Configuring-fallback-for-Office-365-ProPlus-updates-in/td-p/141358

On internet fallback behavior, we add more clarity on internet clients here: https://docs.microsoft.com/en-us/sccm/core/clients/manage/plan-internet-based-client-management 

When you have a software update point that is configured to accept connections from the Internet, Configuration Manager Internet-based clients on the Internet always scan against this software update point, to determine which software updates are required. However, when these clients are on the Internet, they first try to download the software updates from Microsoft Update, rather than from an Internet-based distribution point. Only if this fails, will they then try to download the required software updates from an Internet-based distribution point. Clients that are not configured for Internet-based client management never try to download the software updates from Microsoft Update, but always use Configuration Manager distribution points.

We should link to it and include CloudDPs behavior in the following content ("Internet-based clients always go to Microsoft Update for software updates content."):

If software updates are not available on distribution point in current, neighbor or site boundary groups, download content from Microsoft Updates: Select this setting to have intranet-connected clients download software updates from Microsoft Update if updates aren't available on distribution points. Internet-based clients always go to Microsoft Update for software updates content.

2 spots:
https://docs.microsoft.com/en-us/sccm/sum/deploy-use/automatically-deploy-software-updates#bkmk_adr-process
https://docs.microsoft.com/en-us/sccm/sum/deploy-use/manually-deploy-software-updates#process-to-manually-deploy-the-software-updates-in-a-software-update-group 

Reference internal email thread on this issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc1bc8d-2e4b-650b-7644-84e5790e4630
* Version Independent ID: 9488c8c6-c912-1667-db02-f8a29f5c2023
* Content: [Automatically deploy software updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/automatically-deploy-software-updates#bkmk_adr-process)
* Content Source: [sccm/sum/deploy-use/automatically-deploy-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/automatically-deploy-software-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @MSFTJerryAb 😃

**Comment by ChrisKibble** [comment]
Something the community can help update here @aczechowski, or is there something in the internal email thread where it should be someone internal instead?

**Comment by aczechowski** [comment]
Thanks @ChrisKibble, I think @MSFTJerryAb added all of the salient info in his original comment. Just noting that there was an internal thread on the topic. 

@mestew FYI

**Comment by aczechowski** [comment]
Thanks again for the feedback. We moved this content to a new GitHub repository, so this issue is no longer tracked with the original article. As part of that process, we reviewed our backlog of feedback, and made some tough decisions on items that we don't think we'll realistically ever address. If you're passionate about this specific feedback, please refile it on the current article, now under docs.microsoft.com/mem/configmgr.
