### ISSUE TITLE
Add require URL if using internet proxy/firewall for whitelisting

### ISSUE THREAD

**Issue by StevenElTaino** [MicrosoftDocs/SCCMdocs#929]
[Enter feedback here]
If you are using an internet proxy/firewall, you will need to allow connectivity officecdn.microsoft.com in order to perform SUP syncs for Office 365 Client updates. Refer to blog https://blogs.technet.microsoft.com/askpfeplat/2017/03/23/troubleshooting-office-365-proplus-patching-through-system-center-configuration-manager/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1da48af-4783-bd17-67f3-f265df93503f
* Version Independent ID: 17432b22-04cb-f47f-1634-e5b7fc99c37d
* Content: [Manage Office 365 ProPlus updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/manage-office-365-proplus-updates)
* Content Source: [sccm/sum/deploy-use/manage-office-365-proplus-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/manage-office-365-proplus-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @StevenElTaino for the feedback

**Comment by MSFTJerryAb** [comment]
Just adding a note that config.office.com is needed, as noted by @vinaypamnani-msft noted in https://github.com/MicrosoftDocs/SCCMDocs-pr/issues/2967

**Comment by aczechowski** [comment]
This issue is closed because I've created a new article to address it. The new article will publish live tomorrow (Thursday, 20 June) around 11am Pacific at the following address: https://docs.microsoft.com/sccm/core/plan-design/network/internet-endpoints
