### ISSUE TITLE
SMS Provider section missing words

### ISSUE THREAD

**Issue by aw3t** [MicrosoftDocs/SCCMdocs#933]
https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/plan-for-site-system-servers-and-site-system-roles#sms-provider

"The assigns this role to each computer that hosts an instance of the SMS Provider."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05e32b45-38c1-5960-1d2c-69398c5121fa
* Version Independent ID: 38dcc0d5-4a5b-28ca-f15d-70549e2eddbc
* Content: [Plan site system roles - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/plan-for-site-system-servers-and-site-system-roles#sms-provider)
* Content Source: [sccm/core/plan-design/hierarchy/plan-for-site-system-servers-and-site-system-roles.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/plan-for-site-system-servers-and-site-system-roles.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @aw3t, I think that should read, "The *site* assigns this role...." 

Do you want to make the edit yourself? For more information, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute). Let me know if you have any questions.

**Comment by aw3t** [comment]
Just made the edit!  Thanks.

-Aaron
