### ISSUE TITLE
Visio Sample Query

### ISSUE THREAD

**Issue by alayac** [MicrosoftDocs/SCCMdocs#940]
The Visio sample query returns a lot of false positives in my environment.  Replace "%Visio%" with "Microsoft%Visio%" for a more accurate result.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44e3c4b0-bea3-e89b-e041-3f8bc248dabb
* Version Independent ID: ff58a586-3084-6d25-2883-6012722fbb04
* Content: [Create queries - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/create-queries)
* Content Source: [sccm/core/servers/manage/create-queries.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/create-queries.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @alayac for the feedback and suggestion. Do you want to make the edit yourself? For more information, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute). Let me know if you have any questions or need help.

**Comment by Pacers31Colts18** [comment]
@aczechowski  dibs on this one #MMS2019Docathon

**Comment by ChrisKibble** [comment]
Fixed by #947 , think you can close this one @aczechowski .
