### ISSUE TITLE
Update Catalogs

### ISSUE THREAD

**Issue by jmheeren** [MicrosoftDocs/SCCMdocs#941]
The proper syntax to remove a 3rd party update catalog is:
select * from SMS_ISVCatalogs where DownloadURL="http://www.contoso.com/catalog.cab"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d939da4b-0438-c605-73a7-98d764b09b4c
* Version Independent ID: 04a03c1a-0006-9457-dd2f-9177825dd8a8
* Content: [Technical Preview 1806.2 - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/get-started/capabilities-in-technical-preview-1806-2)
* Content Source: [sccm/core/get-started/capabilities-in-technical-preview-1806-2.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/get-started/capabilities-in-technical-preview-1806-2.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jmheeren for the feedback. This version of technical preview is no longer supported, and this is no longer a known issue in the current branch version 1806. I'm closing this issue. 

(If you're super passionate about fixing that query string, you can submit an edit and I'll review and approve it. 😃 For more information, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute).)
