### ISSUE TITLE
Allowing the tool to work via a proxy

### ISSUE THREAD

**Issue by tgakk** [MicrosoftDocs/SCCMdocs#946]
Can you please update the "Things to know before you run the tool" section to include information on which config files to update to allow it to work via a proxy?  

Insert  the following XML node into the config files below.
IntuneDataImporter.exe.config
Microsoft.IntuneDataImporter.dll.config

&lt;configuration&gt;
….
  &lt;system.net&gt; &lt;!--This node should be child of configuration node.--&gt;
    &lt;defaultProxy useDefaultCredentials="True"&gt;
      &lt;proxy usesystemdefault="True"/&gt;
    &lt;/defaultProxy&gt;
  &lt;/system.net&gt;
….
&lt;configuration&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a66ca7e7-3852-4e00-495f-dad6bac697c6
* Version Independent ID: ee83d1d2-3a25-8c07-da71-dea35e7db694
* Content: [Import data to Microsoft Intune - Configuration Manager](https://docs.microsoft.com/en-us/sccm/mdm/deploy-use/migrate-import-data#feedback)
* Content Source: [sccm/mdm/deploy-use/migrate-import-data.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/mdm/deploy-use/migrate-import-data.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by ChrisKibble** [comment]
I don't have a proxy to test on - do we know if this is accurate and supported?  I can make the update, but don't want to do it blind.

**Comment by aczechowski** [comment]
Thanks @ChrisKibble, @tgakk is one of the PMs for the feature, so I trust that his info is accurate. 😉 
While it's for hybrid content that we're turning off soon, this does specifically address migration. But the issue has been open for a while and I haven't heard any other comments on it. So if someone is reading the article, they can at least see this open issue to get the information. If you want to submit a change for it, I'll accept it, but I'd say it's a low priority. We're already working on a plan to retire this content altogether.

**Comment by ChrisKibble** [comment]
I'm going to go ahead and ignore this one then, thanks :-)

**Comment by aczechowski** [comment]
We discontinued the hybrid MDM service in September 2019. For more information, see the main [hybrid MDM](https://docs.microsoft.com/sccm/mdm/understand/hybrid-mobile-device-management) article. We plan to completely retire the documentation in a couple of months. Since we're no longer maintaining this content, I'm closing this issue.
