### ISSUE TITLE
Futher documentation needed

### ISSUE THREAD

**Issue by torontojc** [MicrosoftDocs/SCCMdocs#967]
It is worth noting in the documentation that in the upgrade mechanism, a new ccmsetup.exe file is downloaded and executed on ALL machines, even those who are part of the exclusion list. It's the ccmsetup.exe that determines if a machine should be upgraded. This is worth noting this as by using the auto-upgrade we are now touching systems when we're not intending to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7000ae26-9f15-9644-55b9-e5db68c47ff2
* Version Independent ID: 8a672552-6e90-cd91-419c-ba6a5292fabf
* Content: [Upgrade clients - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/upgrade/upgrade-clients-for-windows-computers)
* Content Source: [sccm/core/clients/manage/upgrade/upgrade-clients-for-windows-computers.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/upgrade/upgrade-clients-for-windows-computers.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @torontojc for the feedback. Yes, that's an important clarification to include.

**Comment by ChrisKibble** [comment]
I'm happy to take on this update, but I'm not sure what is based on this conversation.  Are we saying the following statement is wrong?

> Beginning in version 1610, you can exclude clients from being upgraded by specifying an exclusion group. For more information, see How to exclude upgrading clients for Windows computers.

**Comment by aczechowski** [comment]
@ChrisKibble no, that statement is still valid (but can remove the "starting in version 1610" bit, as that now encompasses everything that's a supported build.) What we need to add is a note/tip that excluded clients still download and run ccmsetup, that's how the client determines it's excluded from upgrade.

**Comment by ChrisKibble** [comment]
Thanks, so something like this?

> You can exclude clients from being upgraded by specifying an exclusion group. For more information, see How to exclude upgrading clients for Windows computers.  Excluded clients will still download and execute CCMSETUP, but will not upgrade.

If we can avoid using another tip/note block we probably should as there are two others below this bullet already.

**Comment by aczechowski** [comment]
Good point. String generally looks ok, some style suggestions:
- don't use "execute" use "run ([style reference](https://docs.microsoft.com/style-guide/a-z-word-list-term-collections/e/execute) - it translates badly 💀 😨)
- contract "will not" to "won't" ([style reference](https://docs.microsoft.com/style-guide/top-10-tips-style-voice#project-friendliness))

So:
`Excluded clients still download and run CCMSETUP, but won't upgrade.`

**Comment by ChrisKibble** [comment]
D'oh!  You've mentioned the _execute_ one to me before, that one has been a tough habit to break.

> You can exclude clients from being upgraded by specifying an exclusion group. For more information, see How to exclude upgrading clients for Windows computers. Excluded clients still download and run CCMSETUP, but won't upgrade.

Thanks.
