### ISSUE TITLE
Move scale info to central article

### ISSUE THREAD

**Issue by aczechowski** [MicrosoftDocs/SCCMdocs#968]
Move the scale info in this article to the central size and scale numbers article https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/size-and-scale-numbers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d69fe2fa-2d4c-e3fe-ed03-3fae067bca3b
* Version Independent ID: 9b781cea-18dc-79af-0158-59abc861b601
* Content: [Plan for software updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/plan-design/plan-for-software-updates)
* Content Source: [sccm/sum/plan-design/plan-for-software-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/plan-design/plan-for-software-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by jocasti** [comment]
Hi @aczechowski How can I help? What exactly do you need moved? Do you want to move just the bullets below to under the software update point section on the central size article (https://docs.microsoft.com/en-us/sccm/core/plan-design/configs/size-and-scale-numbers#software-update-point)? 
- The software update point can support up to 25,000 clients when WSUS runs on the software update point server, and the software update point co-exists with another site system role. 
- The software update point can support up to 150,000 clients when a remote server meets WSUS requirements, WSUS is used with Configuration Manager, and you configure the following settings:
- IIS Application Pools:
       - Increase the WsusPool Queue Length to 2000
       - Increase the WsusPool Private Memory limit x4 times, or set to 0 (unlimited). For example, if the default limit is 1,843,200 KB, increase it to 7,372,800. For more information, see this Configuration Manager support team blog post.
