### ISSUE TITLE
Selective wipe

### ISSUE THREAD

**Issue by tieronebanter** [MicrosoftDocs/SCCMdocs#973]
The follow through link for Selective wipe on this page states that this feature is only supported on the iOS and Android platform. Please confirm if this is supported or not for Co-Managed Windows 10 devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07e9b780-6cad-d3f3-d0f2-e13a577890cc
* Version Independent ID: 18c7f0aa-884a-349b-e416-74d02adc4474
* Content: [Co-management for Windows 10 devices - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/co-management-overview)
* Content Source: [sccm/core/clients/manage/co-management-overview.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/co-management-overview.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @tieronebanter, good question. I'll check...stay tuned.

**Comment by tieronebanter** [comment]
Is there any update on this?

**Comment by aczechowski** [comment]
No, sorry, I'm still trying to get clarity.

**Comment by aczechowski** [comment]
I'm closing this issue. A big revision to the co-management content will publish soon and address this issue.
I think it was a mistake that "selective" wipe was included. From what I've been able to determine is that the applicable remote action for co-managed clients is *device wipe*. (The new content goes into more detail on remote actions.)

**Comment by tieronebanter** [comment]
Appreciate the response. Thank you!

**Comment by aczechowski** [comment]
An update on this issue. Turns out selective wipe *is* supported on Windows 10. I've submitted a change to the [new remote actions article](https://docs.microsoft.com/sccm/comanage/quickstart-remote-actions) to include it, and am submitting a change to the [Intune article](https://docs.microsoft.com/intune/apps-selective-wipe) as well. Sorry for the delay, and my inaccurate response last week.
