### ISSUE TITLE
Reinstall hotfixes

### ISSUE THREAD

**Issue by faulknerp** [MicrosoftDocs/SCCMdocs#977]
"After a site recovery, you must reinstall any hotfixes that were applied to the site server"

I do not believe this is the case for HOTFIX ROLLUPS such as KB4462978 as the binaries are included in the cd.latest folder which should be backed up.

Maybe this section should be amended so it only applies to out of band hotfixes like the ones described here...
https://docs.microsoft.com/en-us/sccm/core/servers/manage/use-the-hotfix-installer-to-install-updates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d2bf93f-aa79-ef8a-ee16-c1ed27eb8e13
* Version Independent ID: d64f0463-a1e0-b80b-f16b-39f54dd87154
* Content: [Site recovery - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/servers/manage/recover-sites)
* Content Source: [sccm/core/servers/manage/recover-sites.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/servers/manage/recover-sites.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @faulknerp for the suggestion. Let me check on this. Stay tuned.

**Comment by faulknerp** [comment]
I don't suppose there's any update on this please? Thanks.

**Comment by aczechowski** [comment]
Thanks @faulknerp for bumping this. I was able to confirm that for [reinstalling hotfixes for site recovery](https://docs.microsoft.com/sccm/core/servers/manage/recover-sites#reinstall-hotfixes), it only applies to [out-of-band hotfixes](https://docs.microsoft.com/sccm/core/servers/manage/updates#bkmk_outofband) specifically via the [Hotfix Installer](https://docs.microsoft.com/sccm/core/servers/manage/use-the-hotfix-installer-to-install-updates). (Which to date we actually haven't yet done for current branch!)
