### ISSUE TITLE
Ports requirement for setting up Remote content library for the site server

### ISSUE THREAD

**Issue by suhailabdulsalam** [MicrosoftDocs/SCCMdocs#984]
Starting in version 1806, to configure site server high availability or to free up hard drive space on your central administration or primary site servers we can relocate the content library to another storage location. 
Currently, we don't have ports requirements published for this scenario.

If customers want to setup remote content library for the Central or Primary site server, they need to plan for Ports Requirements from Site Server -> Remote Server hosting Content Library while designing the hierarchy or high availability designs.

It would be great if ports requirements are published by the System Center Configuration Manager Product Group.

**Comment by aczechowski** [comment]
Thanks @suhailabdulsalam for the feedback. Good point, let me check on it.

**Comment by aczechowski** [comment]
This was fixed a while back by jpcast88 in a private edit, MicrosoftDocs/SCCMDocs-pr#3599
