### ISSUE TITLE
Terminology Change

### ISSUE THREAD

**Issue by torontojc** [MicrosoftDocs/SCCMdocs#985]
The documentation lists says to clear the checkbox for "Do not allow script authors to approve their own scripts". This option has been renamed to "Script authors require additional script approver" in the console.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c7d1db7-6812-ff3c-9aac-0f55800ed665
* Version Independent ID: a4499cf7-ed5a-710c-66e0-005563b9c015
* Content: [Create and run scripts - Configuration Manager](https://docs.microsoft.com/en-us/sccm/apps/deploy-use/create-deploy-scripts)
* Content Source: [sccm/apps/deploy-use/create-deploy-scripts.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/apps/deploy-use/create-deploy-scripts.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
@jocasti yes, just use the full URL. 
I'm closing this issue, as your private pull request fixes it (will publish tomorrow)
