### ISSUE TITLE
Link to blog of consultant does not exist

### ISSUE THREAD

**Issue by GerrieLouw** [MicrosoftDocs/SCCMdocs#988]
Seems that the blog article about the candidate reports is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29b8c8d-60fa-4403-29a7-8e7c61b2f638
* Version Independent ID: c7610ca2-5607-d1fe-f629-9d0614a26569
* Content: [Client Peer Cache - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/client-peer-cache)
* Content Source: [sccm/core/plan-design/hierarchy/client-peer-cache.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/client-peer-cache.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by GerrieLouw** [comment]
Hi, any update ?

**Comment by aczechowski** [comment]
Yes, I'm talking with Seth. The blog was retired. You may be able to use your favorite internet search engine to view a cached version of the blog post (it worked for me a few days ago). Seth is working to revamp his blog, but I don't have an ETA.

**Comment by GerrieLouw** [comment]
Hi,

I managed to open a cached version of the blog post and got the information.  Thanks for the "cache" tip. In the meantime these reports will suffice.

**Comment by aczechowski** [comment]
Seth moved his post, made a few updates, tested with latest CM version, and added instructions for adding required hardware inventory classes.

https://blogs.technet.microsoft.com/askpfeplat/2018/11/21/configuration-manager-peer-cache-custom-reporting-examples/

@GerrieLouw if you want to make the edit yourself, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute). I'm happy to help if you have any questions.

**Comment by aczechowski** [comment]
Reopening this issue, because it moved again. Current path:

https://techcommunity.microsoft.com/t5/core-infrastructure-and-security/configuration-manager-peer-cache-custom-reporting-examples/ba-p/570801
