### ISSUE TITLE
Configure a task sequence for Windows PE Peer Cache - Collection variables only?

### ISSUE THREAD

**Issue by faulknerp** [MicrosoftDocs/SCCMdocs#989]
Would be good to clarify if the task sequence variables listed in this section can ONLY be collection variables. I.e. can they be set as variables at the start of the task sequence itself or not. I've seen this same question asked on a few other sites and no-one has the answer so it would be good to clarify here if possible please :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd7a196d-4829-4b01-0bc0-8c14fd52dc1a
* Version Independent ID: db302fc5-0610-b270-0202-16fb4606a588
* Content: [Prepare Windows PE peer cache to reduce WAN traffic - Configuration Manager](https://docs.microsoft.com/en-us/sccm/osd/get-started/prepare-windows-pe-peer-cache-to-reduce-wan-traffic)
* Content Source: [sccm/osd/get-started/prepare-windows-pe-peer-cache-to-reduce-wan-traffic.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/osd/get-started/prepare-windows-pe-peer-cache-to-reduce-wan-traffic.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @faulknerp for the feedback. You must set these variables on the collection so that they are available right away when the task sequence starts. It sets the content locations (which depend upon these variables) before any steps process.

**Comment by faulknerp** [comment]
Thanks for getting back to me...… I wonder if they could be set as the very first steps of the task sequence in order to give more control over which clients will use it.

For example, we only use peer cache at one location. Rather than having a separate collection for those clients, it would be good to have it set as the first step of the task sequence where we can use conditions in the task sequence to control which systems apply the peer cache settings.

If that is the way it is, I will raise a uservoice suggestion to that effect instead :)

**Comment by aczechowski** [comment]
@faulknerp yes please post on UserVoice for product feedback. 😃

**Comment by aczechowski** [comment]
Additional notes on this:

clarify variable must be set for task sequence to pick up at execution start

Update the docs to reflect that this variable is not just during WinPE but for everywhere we need the content to be downloaded from peers during task sequence.

- https://docs.microsoft.com/sccm/osd/understand/task-sequence-variables#SMSTSPeerDownload
- https://docs.microsoft.com/sccm/osd/understand/task-sequence-variables#SMSTSPeerRequestPort

**Comment by aczechowski** [comment]
I'm resolving this issue in part because we moved repositories, but also because I'm going to track this work via an internal work item.

(internal reference 2838731)
