### ISSUE TITLE
Add details for enabling verbose, trace and SQL logging

### ISSUE THREAD

**Issue by scott-ip1** [MicrosoftDocs/SCCMdocs#992]
It would also be helpful to add details on enabling the verbose, trace and SQL logging options and the settings that are applicable
eg.
Increase logging levels (default):
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\CCM\Logging\@Global\Loglevel = 0 (1)
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SMS\Tracing\SqlEnabled = 1 (0)
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SMS\Tracing\[COMPONENT]\LoggingLevel = 0 (1)
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\SMS\Tracing\[COMPONENT]\DebugLogging = 1 (0)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 972d8899-c8a4-28c5-fabe-5ab294bac22d
* Version Independent ID: 7f772e7a-836c-a18d-df8d-c3d115cb3d9f
* Content: [Log files for troubleshooting - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/log-files)
* Content Source: [sccm/core/plan-design/hierarchy/log-files.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/plan-design/hierarchy/log-files.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @scott-ip1 for the feedback! This information is good to include when I revise this article.

**Comment by aczechowski** [comment]
Another comment on similar that came today from the engineering team, we also need to include information on server role logging. For example, for the DP role:

SOFTWARE\Microsoft\SMS\DP\Logging (create the logging key)
- LogEnabled
- LogLevel
- LogMaxHistory
- LogMaxSize

**Comment by DavidHBaur** [comment]
Aczechowski, I have tried your settings on a DP for the SMSDPMON.LOG, but it has not impacted that log at all.

**Comment by aczechowski** [comment]
Hi @DavidHBaur, I'm sorry you're having problems. I just updated my comment with a bit more detail to help, but confirmed with the engineering team that's the right registry keys. If you're still having issues, I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

**Comment by aczechowski** [comment]
Closing this issue, fixed with 1906 content (coming soon)
