### ISSUE TITLE
Corrupted HTML in the "SEmi-Annual (Targeted) links

### ISSUE THREAD

**Issue by KyleSchroeder** [MicrosoftDocs/SCCMdocs#993]
In the section #change-the-update-channel-after-you-enable..., there is broken HTML (apparently) in the URL and a comment following it, directly before this "Feedback" section of the page.  Confirmed on Chrome and Edge.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1da48af-4783-bd17-67f3-f265df93503f
* Version Independent ID: 17432b22-04cb-f47f-1634-e5b7fc99c37d
* Content: [Manage Office 365 ProPlus updates - Configuration Manager](https://docs.microsoft.com/en-us/sccm/sum/deploy-use/manage-office-365-proplus-updates#change-the-update-channel-after-you-enable-office-365-clients-to-receive-updates-from-configuration-manager)
* Content Source: [sccm/sum/deploy-use/manage-office-365-proplus-updates.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/sum/deploy-use/manage-office-365-proplus-updates.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Closing this issue. @jocasti submitted a private pull request to fix the comment. It should publish later today or tomorrow at the latest.

**Comment by KyleSchroeder** [comment]
Thanks.  I tried to make the update myself, but apparently it didn't take/save, or more likely I didn't submit it properly.
