### ISSUE TITLE
Reporting for Product Lifecycle

### ISSUE THREAD

**Issue by malcatraz** [MicrosoftDocs/SCCMdocs#997]
The reports are under Reports &gt; Asset Intelligence &gt;Section.  

The reports are as follows in CM 1806
Lifecycle 01A Computers with a specific software product
Lifecycle 02A - List of machines with expired products in the organization
Lifecycle 03A - List of expired products found in the organization
Lifecycle 04A - General Product Lifecycle overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e5b5231-0498-f10a-fcd7-58230e43cca5
* Version Independent ID: aa3f037a-f646-e683-867e-b8e16f27966d
* Content: [Product lifecycle dashboard - Configuration Manager](https://docs.microsoft.com/en-us/sccm/core/clients/manage/asset-intelligence/product-lifecycle-dashboard)
* Content Source: [sccm/core/clients/manage/asset-intelligence/product-lifecycle-dashboard.md](https://github.com/Microsoft/SCCMdocs/blob/master/sccm/core/clients/manage/asset-intelligence/product-lifecycle-dashboard.md)
* Product: **configuration-manager**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @malcatraz for the feedback. These are documented on the [List of reports](https://docs.microsoft.com/sccm/core/servers/manage/list-of-reports#asset-intelligence). I'll keep this issue open to add a cross-link to that article.

**Comment by aczechowski** [comment]
Closing this issue, it's fixed with 1810 content that will publish soon.
